src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Parent_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Lookup to Parent Account</inlineHelpText>
        <label>Parent Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Properties</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Recurring_Billing__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>An indicator to tell whether the Property Account is on autopay. Only used to update the message on the bill. To take a customer off of autopay, use the payment component on the Billing Account to Manage Autopay</inlineHelpText>
        <label>Autopay</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Account_Bill__c.object
<CustomObject>
    <fields>
        <fullName>Bill_Number_Guard__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Bill Number Guard</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Bill_Number__c</fullName>
        <label>Bill Number</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Bill Statment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Last_Shared_Solar_System_ID__c</fullName>
        <label>Last Shared Solar System ID</label>
        <length>35</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent_Account__c</fullName>
        <label>Property Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Bills</relationshipLabel>
        <relationshipName>Account_Bills</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product_Profile__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Profile</label>
        <referenceTo>Product_Profile__c</referenceTo>
        <relationshipLabel>Account Bills</relationshipLabel>
        <relationshipName>Account_Bills</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shared_Solar_System__c</fullName>
        <label>Shared Solar System</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unique_ID__c</fullName>
        <externalId>true</externalId>
        <label>Unique ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Account Bill</label>
    <nameField>
        <label>Account Bill Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Bills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Energy_Usage_Update__c.object
<CustomObject>
    <description>Energy_Usage_Update__c</description>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Shared_Solar_System__c</fullName>
        <label>Shared Solar System</label>
        <referenceTo>Shared_Solar_System__c</referenceTo>
        <relationshipLabel>Production Updates</relationshipLabel>
        <relationshipName>Production_Updates</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Production Update</label>
    <nameField>
        <label>Energy Update</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Production Updates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Customer_Group__c</fullName>
        <label>Customer Group</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Residential</fullName>
                </value>
                <value>
                    <fullName>Non-Residential</fullName>
                    <default>true</default>
                    <label>Non-Residential</label>
                </value>
                <value>
                    <fullName>Anchor</fullName>
                </value>
                <value>
                    <fullName>Business</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Parent_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shared_Solar_System__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>To change this system, use the Change SSS quick action</inlineHelpText>
        <label>Shared Solar System</label>
        <referenceTo>Shared_Solar_System__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Unique_ID__c</fullName>
        <label>Unique ID</label>
        <length>45</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Product_Profile__c.object
<CustomObject>
    <fields>
        <fullName>Account_Bill__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Bill</label>
        <referenceTo>Account_Bill__c</referenceTo>
        <relationshipLabel>Product Profiles</relationshipLabel>
        <relationshipName>Product_Profiles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shared_Solar_System__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Shared Solar System</label>
        <referenceTo>Shared_Solar_System__c</referenceTo>
        <relationshipLabel>Product Profiles</relationshipLabel>
        <relationshipName>Product_Profiles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Profile</label>
    <nameField>
        <label>Product Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Shared_Solar_System__c.object
<CustomObject
     >
    <articleTypeChannelDisplay n1:nil="true" />
    <customSettingsType n1:nil="true" />
    <description n1:nil="true" />
    <eventType n1:nil="true" />
    <fields>
        <fullName>Unique_ID__c</fullName>
        <displayFormat>SSS-{000000}</displayFormat>
        <externalId>true</externalId>
        <label>Unique ID</label>
        <type>AutoNumber</type>
    </fields>
    <gender n1:nil="true" />
    <household>false</household>
    <label>Shared Solar System</label>
    <nameField>
        <label>Shared Solar System Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shared Solar Systems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <startsWith n1:nil="true" />
</CustomObject>

src/objects/System_Bill__c.object
<CustomObject>
    <fields>
        <fullName>Account_Bill__c</fullName>
        <label>Account Bill</label>
        <referenceTo>Account_Bill__c</referenceTo>
        <relationshipLabel>System Bills</relationshipLabel>
        <relationshipName>System_Bills</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Bill_Number__c</fullName>
        <label>Bill Number</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <inlineHelpText>The Production Update date, set when creating the System Bill</inlineHelpText>
        <label>Bill Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>System Bills</relationshipLabel>
        <relationshipName>System_Bills</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>System Bills</relationshipLabel>
        <relationshipName>System_Bills</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Recurring_Billing__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Recurring Billing</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Shared_Solar_System_ID__c</fullName>
        <formula>LEFT(Shared_Solar_System_ID2__c,15)</formula>
        <label>Shared Solar System ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Shared_Solar_System__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Shared Solar System</label>
        <referenceTo>Shared_Solar_System__c</referenceTo>
        <relationshipLabel>System Bills</relationshipLabel>
        <relationshipName>System_Bills</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Unique_ID__c</fullName>
        <externalId>true</externalId>
        <label>Unique ID</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>System Bill</label>
    <nameField>
        <label>System Bill Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>System Bills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Utility_Account_Bill__c.object
<CustomObject>
    <fields>
        <fullName>Account_Bill__c</fullName>
        <label>Account Bill</label>
        <referenceTo>Account_Bill__c</referenceTo>
        <relationshipLabel>Utility Account Bills</relationshipLabel>
        <relationshipName>Utility_Account_Bills</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Bill_Number__c</fullName>
        <label>Bill Number</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Shared_Solar_System__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Shared Solar System</label>
        <referenceTo>Shared_Solar_System__c</referenceTo>
        <relationshipName>CS_Billing_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Unique_Id__c</fullName>
        <externalId>true</externalId>
        <label>Unique Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Utility_Account_Log__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Utility Account Log</label>
        <referenceTo>Utility_Account_Log__c</referenceTo>
        <relationshipName>CS_Billing_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Utility Account Bill</label>
    <nameField>
        <label>CS Billing Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Account Bills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Utility_Account_Log__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Utility Account Logs</relationshipLabel>
        <relationshipName>Utility_Account_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Utility Account Log</label>
    <nameField>
        <label>Utility Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Account Logs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Utility_Account_Subscription__c.object
<CustomObject>
    <fields>
        <fullName>Customer_Group__c</fullName>
        <formula>Text(Opportunity__r.Customer_Group__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Customer Group</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Utility Account Subscriptions</relationshipLabel>
        <relationshipName>Utility_Account_Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shared_Solar_System__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the SSS on the Opportunity when the UAS was created. The SSS on an existing UAS should never be changed.</description>
        <inlineHelpText>This is the SSS on the Opportunity when the UAS was created. The SSS on an existing UAS should never be changed.</inlineHelpText>
        <label>Shared Solar System</label>
        <referenceTo>Shared_Solar_System__c</referenceTo>
        <relationshipLabel>Utility Account Subscriptions</relationshipLabel>
        <relationshipName>Utility_Account_Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Utility_Account_Log__c</fullName>
        <inlineHelpText>The related UAL</inlineHelpText>
        <label>Utility Account Log</label>
        <referenceTo>Utility_Account_Log__c</referenceTo>
        <relationshipLabel>Utility Account Subscriptions</relationshipLabel>
        <relationshipName>Utility_Account_Subscriptions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Utility Account Subscription</label>
    <nameField>
        <label>Utility Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Account Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/EnergyUsageUpdateTriggerHandler.cls
/*
 * Tested by: RecurringPaymentsHandlerTestClass
 */

public with sharing class EnergyUsageUpdateTriggerHandler {
    private boolean m_isExecuting = false;
    private Integer BatchSize = 0;
    
    public EnergyUsageUpdateTriggerHandler(boolean isExecuting, Integer size){
        m_isExecuting = isExecuting;
        BatchSize = size;
    }
    public void OnAfterInsert(Energy_Usage_Update__c[] newEnergyUsageUpdates){
        printCPULimit('Before createCSBillingLog');

        createCSBillingLog(newEnergyUsageUpdates);

        printCPULimit('After createCSBillingLog');
    }

    public static void printCPULimit(String prefix) {
        System.debug(LoggingLevel.ERROR, 'Limits: ' + prefix + ': ' + Limits.getCpuTime() + 'ms of ' 
                     + Limits.getLimitCpuTime() + 'ms used');
    }

    private void createCSBillingLog(List<Energy_Usage_Update__c> euuList){
        Map<Id, Energy_Usage_Update__c> sssIdToEUUMap = new Map<Id, Energy_Usage_Update__c>();
        Map<string, product_profile__c> productProfileMap = new Map<string, product_profile__c>();
        Map<Id, Shared_Solar_System__c> sssIdMap = new Map<Id, Shared_Solar_System__c>();
        integer abCounter = 1;
        integer tsbCounter = 1;
        integer i; 
        
        //load the triggered production updates into the instantiated map and set the SSS as the key value.
        for(Energy_Usage_Update__c euu : euuList){
            sssIdToEUUMap.put(euu.Shared_Solar_System__c, euu);
        }

        //select the UAS that are related to the shared solar systems that have production updates being logged.
        List<Utility_Account_Subscription__c> uasList = [SELECT   Id, Name, 
                                                         Utility_Account_Log__c, 
                                                         Opportunity__r.Name,
                                                         Opportunity__r.Account.Name,
                                                         Opportunity__r.Shared_Solar_System__r.Name,
                                                         Opportunity__r.Shared_Solar_System__c,
                                                         Opportunity__r.Shared_Solar_System__r.Id,
                                                         Opportunity__r.AccountId
                                                         FROM Utility_Account_Subscription__c 
                                                         WHERE Utility_Account_Log__c != null
                                                         //AND Opportunity__r.StageName = 'Complete' 
                                                         AND Opportunity__c != null 
                                                         AND Customer_Group__c != 'Anchor'
                                                         AND Opportunity__r.Shared_Solar_System__c IN : sssIdToEUUMap.keySet() 
                                                         ORDER BY Name];

        //select the UAS that are related to the shared solar systems that have production updates being logged.
        List<Opportunity> oppList = [SELECT   Id, Name, Account.Name, Shared_Solar_System__r.Name, Shared_Solar_System__c, 
                                     AccountId, Account.Id, Account.Recurring_Billing__c
                                     FROM Opportunity 
                                     WHERE StageName = 'Complete' 
                                     AND Customer_Group__c != 'Anchor'
                                     AND Shared_Solar_System__c IN : sssIdToEUUMap.keySet() 
                                     ORDER BY Name];                                                           
        for(Shared_Solar_System__c sss : [  SELECT  Id, Name
                                            FROM Shared_Solar_System__c 
                                            WHERE Id IN : sssIdToEUUMap.keySet() 
                                            ORDER BY Name]){
            sssIdMap.put(sss.Id, sss);
        }
        //Generate a list of all account bills                                                   
        List<Account_Bill__c> accountBillList =  [ SELECT ID,Parent_Account__c, Unique_Id__c, Bill_Number__c, 
                                                   Parent_Account__r.Id, Last_Shared_Solar_System_ID__c, Name, 
                                                   Bill_Number_Guard__c
                                                   FROM Account_Bill__c
                                                   WHERE Id != null];                                       
      
        List<Utility_Account_Bill__c> utilityAccountBillList =  [ SELECT ID, Account_Bill__r.Parent_Account__c, 
                                                                  Account_Bill__r.Parent_Account__r.Id
                                                                  FROM Utility_Account_Bill__c
                                                                  WHERE Id != null];

        //Generate a list of all System Bills                                                  
        List<System_Bill__c> systemBillList =  [ SELECT ID, Shared_Solar_System__c,Shared_Solar_System_ID__c, 
                                                 Property_Account__r.Id, Opportunity__c, 
                                                 Shared_Solar_System__r.Name, Property_Account__r.Name
                                                 FROM System_Bill__c
                                                 WHERE Id != null];                                                                                                                                            
        System.debug(LoggingLevel.ERROR, 'Energy Usage Update Account Bill Size: ' + accountBillList.size());                                     
        Map<String, Account_Bill__c> abKeyToAccountBillMap = new Map<String, Account_Bill__c>();
        Map<String, Account_Bill__c> accountBillMapBillNumberFix = new Map<String, Account_Bill__c>();
        List<Account_Bill__c> myAccountBillList = new List<Account_Bill__c>();    

        printCPULimit('Before first uas loop');

        for(Utility_Account_Subscription__c uas : uasList){
            if(sssIdToEUUMap.containsKey(uas.Opportunity__r.Shared_Solar_System__c)){    
                Energy_Usage_Update__c euu = sssIdToEUUMap.get(uas.Opportunity__r.Shared_Solar_System__c);
                //count how many accountBills exist in the system for this specific Parent Account 
                for(i=0;i<accountBillList.size();i++){
                    if(accountBillList.get(i).Parent_Account__r.Id == uas.Opportunity__r.Account.Id ){
                        myAccountBillList.add(accountBillList.get(i));
                        abCounter = abCounter + 1;      
                    }                                                  
                }
                Account_Bill__c ab = new Account_Bill__c(Name = uas.Opportunity__r.Account.Name + ' ' + 
                                                         euu.MonthDate__c + ' ' + euu.YearDate__c, 
                                                         Date__c =  euu.Date__c,
                                                         Parent_Account__c = uas.Opportunity__r.Account.Id,
                                                         Bill_Number__c = abCounter,
                                                         Last_Shared_Solar_System_ID__c = uas.Opportunity__r.Shared_Solar_System__r.Id);                                                         
                ab.Unique_Id__c = uas.Opportunity__r.Account.Id + ' ' + 
                    DateTime.newInstance(euu.Date__c.year(), euu.Date__c.month(),euu.Date__c.day()).format('yyyy-MM');
                abKeyToAccountBillMap.put(ab.Unique_Id__c, ab);
            }
            abCounter = 1;
        }

        printCPULimit('After first uas loop');

        integer c;
        integer check = 0;
        for(c=0;c<accountBillList.size();c++){
            check = 1;
            accountBillMapBillNumberFix.put(accountBillList.get(c).Unique_Id__c, accountBillList.get(c));
        }   
        for(Account_Bill__c abCounterFix : abKeyToAccountBillMap.values()){
            if(accountBillMapBillNumberFix.containsKey(abCounterFix.Unique_Id__c)){
                abCounterFix.Bill_Number__c = abCounterFix.Bill_Number__c - 1;
            }
        }        
        //Create the Account Bills
        if(abKeyToAccountBillMap.size() > 0){
            upsert abKeyToAccountBillMap.values() Unique_Id__c;
        }
        for(Utility_Account_Subscription__c uas : uasList){
            if(sssIdMap.containsKey(uas.Opportunity__r.Shared_Solar_System__c)){
                Energy_Usage_Update__c euu = sssIdToEUUMap.get(uas.Opportunity__r.Shared_Solar_System__c);
                Shared_Solar_System__c sss = sssIdMap.get(uas.Opportunity__r.Shared_Solar_System__c);
            }
        }
        
        printCPULimit('After Account Bills upserted');

        Set<System_Bill__c> systemBillSet = new Set<System_Bill__c>();
        for(Opportunity opp : oppList){
            set<string> sbSetCheck = new set<string>();
            Energy_Usage_Update__c euu = sssIdToEUUMap.get(opp.Shared_Solar_System__c);
            String systemKey = 
                opp.Shared_Solar_System__c + ' ' + 
                DateTime.newInstance(euu.Date__c.year(), euu.Date__c.month(),euu.Date__c.day()).format('yyyy-MM');
            String parentKey = opp.Account.Id + ' ' + 
                DateTime.newInstance(euu.Date__c.year(), euu.Date__c.month(),euu.Date__c.day()).format('yyyy-MM');            
            Account_Bill__c ab = abKeyToAccountBillMap.get(parentKey);
            integer sbCounter = 1;
            // Totalized_System_Bill__c tsb = sbKeyToTSBMap.get(systemKey);            
            string systemBillIdentifier;
            for(i=0;i<systemBillList.size();i++){
                integer ifCheck = 0;
                if(systemBillList.get(i).Shared_Solar_System__r.Id == opp.Shared_Solar_System__r.Id
                   && systemBilllist.get(i).Property_Account__r.Id == opp.Account.Id){
                    ifCheck = 1;
                    sbCounter = sbCounter + 1;
                }
            } 
            if(opp.Account.Recurring_Billing__c == true){          
                System_Bill__c sb = new System_Bill__c(Name = opp.Name + ' ' + 
                                                       opp.Shared_Solar_System__r.Name + ' ' + euu.MonthDate__c + ' ' + euu.YearDate__c,
                                                       Shared_Solar_System_ID2__c = opp.Shared_Solar_System__r.Id,
                                                       Account_Bill__c = ab.Id,
                                                       Recurring_Billing__c = true,
                                                       Date__c =  euu.Date__c,
                                                       Bill_Number__c = sbCounter,
                                                       Shared_Solar_System__c = opp.Shared_Solar_System__r.Id,
                                                       Property_Account__c = opp.Account.Id,
                                                       Opportunity__c = opp.Id);                                                                                 
                sb.Unique_Id__c = opp.Name + ' ' + opp.Shared_Solar_System__r.Name + ' ' + 
                    DateTime.newInstance(euu.Date__c.year(), euu.Date__c.month(),euu.Date__c.day()).format('yyyy-MM');
                systemBillIdentifier = opp.Name + ' ' + opp.Shared_Solar_System__r.Name + ' ' + 
                    DateTime.newInstance(euu.Date__c.year(), euu.Date__c.month(),euu.Date__c.day()).format('yyyy-MM');
                if(!sbSetCheck.contains(systemBillIdentifier)){
                    systemBillSet.add(sb);
                    sbSetCheck.add(systemBillIdentifier);
                }
                sbCounter = sbcounter + 1;                   
            }
            else{
                System_Bill__c sb = new System_Bill__c(Name = opp.Name + ' ' + 
                                                       opp.Shared_Solar_System__r.Name + ' ' + euu.MonthDate__c + ' ' + euu.YearDate__c,
                                                       Shared_Solar_System_ID2__c = opp.Shared_Solar_System__r.Id,
                                                       Account_Bill__c = ab.Id,
                                                       Date__c =  euu.Date__c,
                                                       Bill_Number__c = sbCounter,
                                                       Shared_Solar_System__c = opp.Shared_Solar_System__r.Id,
                                                       Property_Account__c = opp.Account.Id,
                                                       Opportunity__c = opp.Id);                    
                sb.Unique_Id__c = opp.Name + ' ' + opp.Shared_Solar_System__r.Name + ' ' + 
                    DateTime.newInstance(euu.Date__c.year(), euu.Date__c.month(),euu.Date__c.day()).format('yyyy-MM');                
                systemBillIdentifier = opp.Name + ' ' + opp.Shared_Solar_System__r.Name + ' ' + 
                    DateTime.newInstance(euu.Date__c.year(), euu.Date__c.month(),euu.Date__c.day()).format('yyyy-MM');
                if(!sbSetCheck.contains(systemBillIdentifier)){
                    systemBillSet.add(sb);
                    sbSetCheck.add(systemBillIdentifier);
                } 
                sbcounter = sbcounter + 1;     
            }                                                             
            sbCounter = 1;               
        }

        printCPULimit('Before System Bills upserted');

        //Create the Utility Account Bills
        if(systemBillSet.size() > 0){
            upsert new List<System_Bill__c>(systemBillSet) Unique_Id__c;
        }        
          

        printCPULimit('After System Bills upserted');

        Set<Utility_Account_Bill__c> uabSet = new Set<Utility_Account_Bill__c>();  
        for(Utility_Account_Subscription__c uas : uasList){
            integer uabCounter = 1;
            Energy_Usage_Update__c euu = sssIdToEUUMap.get(uas.Opportunity__r.Shared_Solar_System__c);
            String parentKey = uas.Opportunity__r.Account.Id + ' ' + 
                DateTime.newInstance(euu.Date__c.year(), euu.Date__c.month(),euu.Date__c.day()).format('yyyy-MM');
            if(abKeyToAccountBillMap.containsKey(parentKey)){ 
                for(i=0;i<utilityAccountBillList.size();i++){
                    if(utilityAccountBillList.get(i).Account_Bill__r.Parent_Account__r.Id == uas.Opportunity__r.Account.Id){
                        uabCounter = uabCounter + 1;
                    }
                }                           
                Account_Bill__c ab = abKeyToAccountBillMap.get(parentKey);
                Utility_Account_Bill__c uab = 
                    new Utility_Account_Bill__c(Name = uas.Opportunity__r.Name + ' ' + 
                                                euu.MonthDate__c + ' ' + euu.YearDate__c + ' ' + uas.Name,
                                                Production_Update__c = euu.Id,
                                                Shared_Solar_System__c = euu.Shared_Solar_System__c,
                                                Date__c =  euu.Date__c,
                                                Utility_Account_Log__c = uas.Utility_Account_Log__c,
                                                Bill_Number__c = uabCounter,
                                                Account_Bill__c = ab.Id);
                
                uab.Unique_Id__c = uas.Utility_Account_Log__c + ' - ' + 
                    DateTime.newInstance(euu.Date__c.year(), euu.Date__c.month(),euu.Date__c.day()).format('yyyy-MM');
                uabSet.add(uab);
            }
            uabCounter = 1;            
        }

        printCPULimit('Before Utility Account Bills upserted');

        //Create the Utility Account Bills
        if(uabSet.size() > 0){
            Database.executeBatch(new GenericBatchDMLOperation(new List<Utility_Account_Bill__c>(uabSet), 'Upsert'));
        }
    }                  

}