src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Account is Closed if all Opportunities are Cancelled, Duplicate, Expired or Dead</inlineHelpText>
        <label>CS Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Client_Invoicing_Memo__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Invoice_Line_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Populated when the Generate Invoice flow creates a new invoice and pulls this record in. Used to tell if this record has been included in an invoice</inlineHelpText>
        <label>Invoice Line Item</label>
        <referenceTo>Invoice_Line_Item__c</referenceTo>
        <relationshipLabel>Client Invoicing Memos</relationshipLabel>
        <relationshipName>Client_Invoicing_Memos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shared_Solar_System__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Used for Utilization Adjustments to Management Fees, populated by the Utilization Adjustment flow</inlineHelpText>
        <label>Shared Solar System</label>
        <referenceTo>Shared_Solar_System__c</referenceTo>
        <relationshipLabel>Client Invoicing Memos</relationshipLabel>
        <relationshipName>Client_Invoicing_Memos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subscription_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subscription Order</label>
        <referenceTo>Subscription_Order__c</referenceTo>
        <relationshipLabel>Client Invoicing Memos</relationshipLabel>
        <relationshipName>Client_Invoicing_Memos</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Client Invoicing Memo</label>
    <nameField>
        <displayFormat>CIM-{000000}</displayFormat>
        <label>Client Invoicing Memo Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Invoicing Memos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contract_Fee_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Shared_Solar_System__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Used to make this CFD specific to a SSS when the ClientInvoicingFeeAssignmentService assigns a CFD to a Subscription Order when the SO is approved.</inlineHelpText>
        <label>Shared Solar System</label>
        <referenceTo>Shared_Solar_System__c</referenceTo>
        <relationshipLabel>Contract Fee Detail</relationshipLabel>
        <relationshipName>Contract_Fee_Detail</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contract Fee Detail</label>
    <nameField>
        <displayFormat>CFD-{000000}</displayFormat>
        <label>Contract Fee Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Fee Detail</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Invoice__c.object
<CustomObject>
    <description>Zuora Invoice object. Invoices are bills that you send to customers.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Related Client Account for Client Invoices, or a partner account</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <inlineHelpText>Date on or before which Subscription Orders and Client Invoicing Memos need to be effective for the Invoice Generation flow to pull in</inlineHelpText>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Received &gt;&gt; QC</fullName>
                </value>
                <value>
                    <fullName>QC Complete &gt;&gt; Submit to Accounting</fullName>
                </value>
                <value>
                    <fullName>Submitted to Accounting</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Invoice_Line_Item__c.object
<CustomObject>
    <description>Details that roll up to an Invoice object, used for Client Invoicing</description>
    <fields>
        <fullName>Assignment_Agreement_Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Assignment Agreement, set by the Generate Invoice flow, if this Invoice Line Item is applicable to an assignment.</inlineHelpText>
        <label>Assignment Agreement Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Invoice Line Items</relationshipLabel>
        <relationshipName>Invoice_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Client_Invoicing_Memo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Related Client Invoicing Memo (if applicable), set when the Invoice Line Item is created through the Generate Invoice flow</inlineHelpText>
        <label>Client Invoicing Memo</label>
        <referenceTo>Client_Invoicing_Memo__c</referenceTo>
        <relationshipLabel>Invoice Line Items</relationshipLabel>
        <relationshipName>Invoice_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Invoice__c</fullName>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Invoice Line Items</relationshipLabel>
        <relationshipName>Invoice_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Shared_Solar_System__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Set when the Generate Invoice flow creates Invoice Line Items</inlineHelpText>
        <label>Shared Solar System</label>
        <referenceTo>Shared_Solar_System__c</referenceTo>
        <relationshipLabel>Invoice Line Items</relationshipLabel>
        <relationshipName>Invoice_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subscription_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Related Subscription Order (if applicable), set when the Invoice Line Item is created through the Generate Invoice flow</inlineHelpText>
        <label>Subscription Order</label>
        <referenceTo>Subscription_Order__c</referenceTo>
        <relationshipLabel>Invoice Line Items</relationshipLabel>
        <relationshipName>Invoice_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>ILI-{0000}</displayFormat>
        <label>Invoice Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Shared_Solar_System__c.object
<CustomObject
     >
    <articleTypeChannelDisplay n1:nil="true" />
    <customSettingsType n1:nil="true" />
    <description n1:nil="true" />
    <eventType n1:nil="true" />
    <fields>
        <fullName>Client_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The client account field designates that party in which this shared solar system is being serviced for.</description>
        <inlineHelpText>The client account field designates that party in which this shared solar system is being serviced for.</inlineHelpText>
        <label>Client Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Shared Solar Systems</relationshipLabel>
        <relationshipName>Shared_Solar_Systems</relationshipName>
        <type>Lookup</type>
    </fields>
    <gender n1:nil="true" />
    <household>false</household>
    <label>Shared Solar System</label>
    <nameField>
        <label>Shared Solar System Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shared Solar Systems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <startsWith n1:nil="true" />
</CustomObject>

src/objects/Subscription_Order__c.object
<CustomObject>
    <fields>
        <fullName>Client_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>This is the Client Account that was on the related Shared Solar System at the time the Subscription Order was created.</description>
        <inlineHelpText>This is the Client Account that was on the related Shared Solar System at the time the Subscription Order was created.</inlineHelpText>
        <label>Client Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscription Orders</relationshipLabel>
        <relationshipName>Subscription_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Client_Assignment_Agreement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Assignment Agreement contract, populated when the Assignment Agreement on the corresponding Opportunity (or Opportunity&apos;s Contract) is populated or changed</inlineHelpText>
        <label>Client Assignment Agreement</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Subscription Orders</relationshipLabel>
        <relationshipName>Subscription_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <description>This is the date that the Subscription Order was approved. It is populated automatically when the Status field is set to approved. Subscription Orders cannot be edited once they&apos;ve been approved.</description>
        <inlineHelpText>This is the date that the Subscription Order was approved. It is populated automatically when the Status field is set to approved. Subscription Orders cannot be edited once they&apos;ve been approved.</inlineHelpText>
        <label>Effective Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Invoice_Line_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Populated when the Generate Invoice flow creates a new invoice and pulls this record in. Used to tell if this record has been included in an invoice</inlineHelpText>
        <label>Invoice Line Item</label>
        <referenceTo>Invoice_Line_Item__c</referenceTo>
        <relationshipLabel>Subscription Orders</relationshipLabel>
        <relationshipName>Subscription_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Utility_Account_Subscription__c</fullName>
        <label>Utility Account Subscription</label>
        <referenceTo>Utility_Account_Subscription__c</referenceTo>
        <relationshipLabel>Subscription Orders</relationshipLabel>
        <relationshipName>Subscription_Orders</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Subscription Order</label>
    <nameField>
        <displayFormat>SO-{00000}</displayFormat>
        <label>Subscription Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscription Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Utility_Account_Subscription__c.object
<CustomObject>
    <fields>
        <fullName>Shared_Solar_System__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the SSS on the Opportunity when the UAS was created. The SSS on an existing UAS should never be changed.</description>
        <inlineHelpText>This is the SSS on the Opportunity when the UAS was created. The SSS on an existing UAS should never be changed.</inlineHelpText>
        <label>Shared Solar System</label>
        <referenceTo>Shared_Solar_System__c</referenceTo>
        <relationshipLabel>Utility Account Subscriptions</relationshipLabel>
        <relationshipName>Utility_Account_Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>This is displayed in the customer portal as a way of showing the status of a customer&apos;s subscription using a combination of Current Allocation Schedule Status, Next Allocation Schedule Status, and Date Removed</description>
        <formula>IF(
 ISBLANK(Date_Removed_from_Project__c)=false,
&quot;Inactive&quot;,

IF(

  ISPICKVAL(Next_Schedule_Z_Status__c,&quot;Active Subscription&quot;)
&amp;&amp;
 Current_Schedule_Z_Status__c=&quot;Not Yet Enacted&quot;,
&quot;Coming Soon&quot;,

IF(
  ISPICKVAL(Next_Schedule_Z_Status__c,&quot;Active Subscription&quot;)
&amp;&amp;
 Current_Schedule_Z_Status__c=&quot;Enacted&quot;,
&quot;Active&quot;,

IF(
  ISPICKVAL(Next_Schedule_Z_Status__c,&quot;Inactive Subscription&quot;)
&amp;&amp;
 Current_Schedule_Z_Status__c=&quot;Enacted&quot;,
&quot;Pending Removal&quot;,&quot;&quot;)


)
)
)</formula>
        <inlineHelpText>This is displayed in the customer portal as a way of showing the status of a customer&apos;s subscription using a combination of Current Allocation Schedule Status, Next Allocation Schedule Status, and Date Removed</inlineHelpText>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <label>Utility Account Subscription</label>
    <nameField>
        <label>Utility Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Account Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ClientInvoiceGenerator.cls
/**
 * @description Generates Client Invoices based on Subscription Orders and Client Invoicing Memos related to Shared Solar Systems
 * Created by peteryao on 10/19/20.
 * Tested By: ClientInvoiceGeneratorTest
 */

public without sharing class ClientInvoiceGenerator {
    private static SubscriptionOrderSelector subscriptionOrderSelector = new SubscriptionOrderSelector();
    private static ClientInvoicingMemoSelector clientInvoicingMemoSelector = new ClientInvoicingMemoSelector();
    private static SharedSolarSystemsSelector sharedSolarSystemsSelector = new SharedSolarSystemsSelector();
    private static Id clientInvoicingRecordTypeId =
        Schema.SObjectType.Invoice__c.getRecordTypeInfosByName().get('Client Invoice').getRecordTypeId();

    @TestVisible
    private static fflib_SObjectUnitOfWork uow = new fflib_SObjectUnitOfWork(
        new List<SObjectType> {
            Invoice__c.SObjectType,
            Invoice_Line_Item__c.SObjectType,
            Subscription_Order__c.SObjectType,
            Client_Invoicing_Memo__c.SObjectType
        }
    );

    /**
     * @description Generates invoices, one per client, for the list of SSS
     * @param sssIds List of Shared Solar Systems to get invoices
     * @param includeAssignmentFees True if this should generate an Invoice Line Item for records related to Assignment Agreements
     * @param includeChangeFees True if this should generate an Invoice Line Item for records not related to Assignment Agreements
     * @param effectiveDate Cutoff date for Subscription Orders and Client Invoicing Memos
     * @return List of Invoices
     */
    public List<Invoice__c> generateInvoices(Set<Id> sssIds, Boolean includeAssignmentFees, Boolean includeChangeFees, Datetime effectiveDate) {
        List<Shared_Solar_System__c> sharedSolarSystems = sharedSolarSystemsSelector.selectAll(sssIds);
        MultiMap sssByClientAccount =
            CollectionUtil.multiMapByField(sharedSolarSystems, Shared_Solar_System__c.Client_Account__c);

        List<Invoice__c> invoices = new List<Invoice__c>();
        for (Object clientAccountId : sssByClientAccount.keySet()) {
            List<Shared_Solar_System__c> sharedSolarSystemsForClient =
                (List<Shared_Solar_System__c>) CollectionUtil.toTypedList(sssByClientAccount.getValues(clientAccountId), new List<Shared_Solar_System__c>());
            Invoice__c clientInvoice =
                generateInvoiceForClient(
                    (Id) clientAccountId,
                    sharedSolarSystemsForClient[0].Client_Account__r.Name,
                    sharedSolarSystemsForClient,
                    includeAssignmentFees,
                    includeChangeFees,
                    effectiveDate
                );
            invoices.add(clientInvoice);
        }
        uow.commitWork();
        return invoices;
    }

    /**
     * @description Exposes commitWork from the private uow
     */
    public void commitWork() {
        uow.commitWork();
    }

    private Invoice__c generateInvoiceForClient(Id clientAccountId,
        String clientName,
        List<Shared_Solar_System__c> sharedSolarSystems,
        Boolean includeAssignmentFees,
        Boolean includeChangeFees,
        Datetime effectiveDate
    ) {
        Invoice__c invoice = new Invoice__c(
            Name = clientName + ' ' + System.today().format(),
            RecordTypeId = clientInvoicingRecordTypeId,
            Account__c = clientAccountId,
            Status__c = 'Draft',
            Effective_Date__c = Date.newInstance(effectiveDate.year(), effectiveDate.month(), effectiveDate.day())
        );
        uow.registerNew(invoice);
        List<Subscription_Order__c> subscriptionOrders = subscriptionOrderSelector.getUninvoicedBySSS(sharedSolarSystems, effectiveDate);
        for (Subscription_Order__c subscriptionOrder : subscriptionOrders) {
            generateLineItemFromSO(subscriptionOrder, invoice, includeAssignmentFees, includeChangeFees);
        }
        List<Client_Invoicing_Memo__c> clientInvoicingMemos = clientInvoicingMemoSelector.getUninvoicedBySSS(sharedSolarSystems, effectiveDate);
        for (Client_Invoicing_Memo__c cim : clientInvoicingMemos) {
            generateLineItemFromCIM(cim, invoice, includeAssignmentFees, includeChangeFees);
        }
        return invoice;
    }

    /**
     * @description Registers a new Invoice Line Item with this class's UOW
     * @param subscriptionOrder The Subscription Order to relate to an Invoice
     * @param invoice The Invoice to relate to the Subscription Order
     * @param includeAssignmentFees If True, generates an Invoice Line Item if the SO is related to an Assignment Agreement
     * @param includeChangeFees If True, generates an Invoice Line Item if the SO is not related to an Assignment Agreement
     * @return The Invoice Line Item, or null if none was registered
     */
    public Invoice_Line_Item__c generateLineItemFromSO(
        Subscription_Order__c subscriptionOrder,
        Invoice__c invoice,
        Boolean includeAssignmentFees,
        Boolean includeChangeFees
    ) {
        if ((includeAssignmentFees && subscriptionOrder.Client_Assignment_Agreement__c != null) ||
            (includeChangeFees && subscriptionOrder.Client_Assignment_Agreement__c == null)) {
            LineItemDetails details = new LineItemDetails(subscriptionOrder);
            Invoice_Line_Item__c invoiceLineItem = new Invoice_Line_Item__c(
                Subscription_Order__c = subscriptionOrder.Id,
                Assignment_Agreement_Contract__c = subscriptionOrder.Client_Assignment_Agreement__c,
                Shared_Solar_System__c = subscriptionOrder.Utility_Account_Subscription__r.Shared_Solar_System__c,
                Amount__c = subscriptionOrder.Client_Invoicing_Fee__c,
                Details__c = JSON.serializePretty(details)
            );
            uow.registerNew(invoiceLineItem, Invoice_Line_Item__c.Invoice__c, invoice);
            uow.registerDirty(subscriptionOrder, Subscription_Order__c.Invoice_Line_Item__c, invoiceLineItem);
            return invoiceLineItem;
        }
        return null;
    }

    /**
     * @description Registers a new Invoice Line Item with this class's UOW
     * @param cim The Subscription Order to relate to an Invoice
     * @param invoice The Invoice to relate to the Subscription Order
     * @param includeAssignmentFees If True, generates an Invoice Line Item if the SO is related to an Assignment Agreement
     * @param includeChangeFees If True, generates an Invoice Line Item if the SO is not related to an Assignment Agreement
     * @return The Invoice Line Item, or null if none was registered
    */
    public Invoice_Line_Item__c generateLineItemFromCIM(
        Client_Invoicing_Memo__c cim,
        Invoice__c invoice,
        Boolean includeAssignmentFees,
        Boolean includeChangeFees
    ) {
        if ((includeAssignmentFees && cim.Subscription_Order__r.Client_Assignment_Agreement__c != null) ||
            (includeChangeFees && cim.Subscription_Order__r.Client_Assignment_Agreement__c == null)) {
            LineItemDetails details = new LineItemDetails(cim);
            Invoice_Line_Item__c invoiceLineItem = new Invoice_Line_Item__c(
                Client_Invoicing_Memo__c = cim.Id,
                Subscription_Order__c = cim.Subscription_Order__c,
                Assignment_Agreement_Contract__c = cim.Subscription_Order__r.Client_Assignment_Agreement__c,
                Shared_Solar_System__c = cim.Subscription_Order__r.Utility_Account_Subscription__r.Shared_Solar_System__c,
                Amount__c = cim.Amount__c,
                Details__c = JSON.serializePretty(details)
            );
            uow.registerNew(invoiceLineItem, Invoice_Line_Item__c.Invoice__c, invoice);
            uow.registerDirty(cim, Client_Invoicing_Memo__c.Invoice_Line_Item__c, invoiceLineItem);
            return invoiceLineItem;
        }
        return null;
    }

    private class LineItemDetails {
        private Decimal fee;
        private Id contractFeeDetailId;
        private Decimal approvedChange;
        private String feeType;
        private LineItemDetails(Subscription_Order__c so) {
            this.fee = so.Contract_Fee_Detail__r.Fee__c;
            this.contractFeeDetailId = so.Contract_Fee_Detail__c;
            this.approvedChange = so.Approved_Change_in_Subscription__c;
            if (so.Contract_Fee_Detail__r.Acquisition_Type_Acquisition__c) {
                feeType = 'Acquisition';
            } else if (so.Contract_Fee_Detail__r.Acquisition_Type_Reacquisition__c) {
                feeType = 'Reacqusition';
            } else {
                feeType = 'Neither Acq nor Reacq';
            }
        }
        private LineItemDetails(Client_Invoicing_Memo__c cim) {
            this.fee = cim.Subscription_Order__r.Contract_Fee_Detail__r.Fee__c;
            this.contractFeeDetailId = cim.Subscription_Order__r.Contract_Fee_Detail__c;
            this.approvedChange = cim.Subscription_Order__r.Approved_Change_in_Subscription__c;
            feeType = cim.Type__c;
        }
    }
}