src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Late_Fee_Payments__c</fullName>
        <label>Late Fee Payments</label>
        <summarizedField>Account_Bill__c.Late_Fee_Payments__c</summarizedField>
        <summaryForeignKey>Account_Bill__c.Parent_Account__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Parent_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Lookup to Parent Account</inlineHelpText>
        <label>Parent Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Properties</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Account_Bill__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <label>Bill Statment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Parent_Account__c</fullName>
        <label>Property Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Bills</relationshipLabel>
        <relationshipName>Account_Bills</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Shared_Solar_System__c</fullName>
        <label>Shared Solar System</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_Payments_This_Month__c</fullName>
        <formula>Overpayment_Amount_Rollup__c +  Total_Payments_SB__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Payments This Month</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Account Bill</label>
    <nameField>
        <label>Account Bill Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Bills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Bill_Adjustment__c.object
<CustomObject>
    <description>CS Billing: If we know that a UAS is going to need adjustments on a future bill, they are stored here until that bill is generated</description>
    <fields>
        <fullName>Account_Bill__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>XXAccount Bill</label>
        <referenceTo>Account_Bill__c</referenceTo>
        <relationshipLabel>Bill Adjustments</relationshipLabel>
        <relationshipName>Bill_Adjustments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Bill Adjustments (Account)</relationshipLabel>
        <relationshipName>Bill_Adjustments1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Adjustment_Amount__c</fullName>
        <label>Adjustment Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <defaultValue>&quot;Unapproved&quot;</defaultValue>
        <inlineHelpText>Set automatically by the approval process</inlineHelpText>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Unapproved</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Overpayment__c</fullName>
        <defaultValue>false</defaultValue>
        <label>XXOverpayment</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Reason_For_Adjustment__c</fullName>
        <label>Reason For Adjustment:</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Source_ID__c</fullName>
        <label>Source ID</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Utility_Account_Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Utility Account Subscription</label>
        <referenceTo>Utility_Account_Subscription__c</referenceTo>
        <relationshipLabel>Bill Adjustments</relationshipLabel>
        <relationshipName>Bill_Adjustments_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Bill Adjustment</label>
    <nameField>
        <label>Bill Adjustment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bill Adjustments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Parent_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shared_Solar_System__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>To change this system, use the Change SSS quick action</inlineHelpText>
        <label>Shared Solar System</label>
        <referenceTo>Shared_Solar_System__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Overpayment__c.object
<CustomObject>
    <fields>
        <fullName>Account_Bill__c</fullName>
        <label>Account Bill</label>
        <referenceTo>Account_Bill__c</referenceTo>
        <relationshipLabel>Overpayments</relationshipLabel>
        <relationshipName>Overpayments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Entity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Entity</label>
        <referenceTo>Entity__c</referenceTo>
        <relationshipLabel>Overpayments</relationshipLabel>
        <relationshipName>Overpayments</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Overpayment_Amount__c</fullName>
        <label>Overpayment Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Overpayment</label>
    <nameField>
        <displayFormat>OP{000000}</displayFormat>
        <label>Overpayment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Overpayments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Shared_Solar_System__c.object
<CustomObject
     >
    <articleTypeChannelDisplay n1:nil="true" />
    <customSettingsType n1:nil="true" />
    <description n1:nil="true" />
    <eventType n1:nil="true" />
    <fields>
        <fullName>BWC_Project_Entity_Manual__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Entity name of project.</inlineHelpText>
        <label>Project Entity</label>
        <referenceTo>Entity__c</referenceTo>
        <relationshipLabel>Shared Solar Systems</relationshipLabel>
        <relationshipName>Shared_Solar_Systems</relationshipName>
        <type>Lookup</type>
    </fields>
    <gender n1:nil="true" />
    <household>false</household>
    <label>Shared Solar System</label>
    <nameField>
        <label>Shared Solar System Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shared Solar Systems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <startsWith n1:nil="true" />
</CustomObject>

src/objects/System_Bill__c.object
<CustomObject>
    <fields>
        <fullName>Account_Bill_Number__c</fullName>
        <formula>Account_Bill__r.Bill_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Bill Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Account_Bill__c</fullName>
        <label>Account Bill</label>
        <referenceTo>Account_Bill__c</referenceTo>
        <relationshipLabel>System Bills</relationshipLabel>
        <relationshipName>System_Bills</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <inlineHelpText>The Production Update date, set when creating the System Bill</inlineHelpText>
        <label>Bill Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_of_Last_Payment__c</fullName>
        <label>Date of Last Payment</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>System Bills</relationshipLabel>
        <relationshipName>System_Bills</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shared_Solar_System__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Shared Solar System</label>
        <referenceTo>Shared_Solar_System__c</referenceTo>
        <relationshipLabel>System Bills</relationshipLabel>
        <relationshipName>System_Bills</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total_Payments_This_Month__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total Payments This Month</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>System Bill</label>
    <nameField>
        <label>System Bill Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>System Bills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Utility_Account_Log__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Utility Account Logs</relationshipLabel>
        <relationshipName>Utility_Account_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Utility Account Logs</relationshipLabel>
        <relationshipName>Utility_Account_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Utility Account Log</label>
    <nameField>
        <label>Utility Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Account Logs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Utility_Account_Subscription__c.object
<CustomObject>
    <fields>
        <fullName>Next_Schedule_Z_Status__c</fullName>
        <defaultValue>&quot;Active Subscription&quot;</defaultValue>
        <inlineHelpText>Controls whether this subscription should be added to future Allocation Schedules. Select &apos;Active Subscription&apos; to include it, or &apos;Inactive Subscription&apos; to exclude it.</inlineHelpText>
        <label>Next Allocation Schedule Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active Subscription</fullName>
                    <default>true</default>
                    <label>Active Subscription</label>
                </value>
                <value>
                    <fullName>Inactive Subscription</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Utility Account Subscriptions</relationshipLabel>
        <relationshipName>Utility_Account_Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shared_Solar_System__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the SSS on the Opportunity when the UAS was created. The SSS on an existing UAS should never be changed.</description>
        <inlineHelpText>This is the SSS on the Opportunity when the UAS was created. The SSS on an existing UAS should never be changed.</inlineHelpText>
        <label>Shared Solar System</label>
        <referenceTo>Shared_Solar_System__c</referenceTo>
        <relationshipLabel>Utility Account Subscriptions</relationshipLabel>
        <relationshipName>Utility_Account_Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Utility_Account_Log__c</fullName>
        <inlineHelpText>The related UAL</inlineHelpText>
        <label>Utility Account Log</label>
        <referenceTo>Utility_Account_Log__c</referenceTo>
        <relationshipLabel>Utility Account Subscriptions</relationshipLabel>
        <relationshipName>Utility_Account_Subscriptions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Utility Account Subscription</label>
    <nameField>
        <label>Utility Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Account Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ReturnedTransactionHandler.cls
/**
 * Created by mstackhouse on 10/1/2018.
 * Description: Provides a method for reversing transactions that have been returned due to an ACH issue. Implemented as a button
 * on the transaction page and has validations to make sure there isn't another system bill published.
 * Test: TestBillCreationandPayment
 */


global without sharing class ReturnedTransactionHandler {
    webService static void unrollPayments(Id transactionId) {
        ChargentOrders__Transaction__c chTransaction;
        Map<Id,Account> propaccountMap;
        List<System_Bill__c> systemBills;
        Map<Id,Account_Bill__c> accountBillMap;
        Datetime lastSystemBillDate;

        List<System_Bill__c> finalGroupedSystemBillsToUpdate = new List<System_Bill__c>();
        List<Account_Bill__c> finalAccountBillsToUpdate = new List<Account_Bill__c>();
        List<Bill_Adjustment__c> finalAdjustmentsToInsertList = new List<Bill_Adjustment__c>();

        SystemBillPaymentRollUpHandler.SystemBillRepo sbRepo = new SystemBillPaymentRollUpHandler.SystemBillRepo(new List<Id>{transactionId});
        if (sbRepo.getTransactions().size() != 1 || sbRepo.getTransactions()[0].Id != transactionId) {
            throw new Util.BWException('Transaction cannot be marked for return.');
        }
        chTransaction = sbRepo.getTransactions()[0];
        systemBills = sbRepo.getSystemBills();
        accountBillMap = sbRepo.getAccountBillMap();
        propaccountMap = sbRepo.getPropertyAccountMap();

        List<System_Bill__c> groupedSystemBillsList = new List<System_Bill__c>();
        String parentID = chTransaction.ChargentOrders__Order__r.Account_Bill__r.Parent_Account__r.Id;
        String entityId = chTransaction.ChargentOrders__Order__r.Entity__c;
        Decimal payment = chTransaction.ChargentOrders__Amount__c;
        Decimal maxbillnumber = 0;

        Date dateOfLastPayment = Date.newInstance(System.today().year(), System.today().month(), System.today().day());

        for (System_Bill__c sbill : systemBills) {
            if (sbill.Account_Bill__r.Parent_Account__r.Id == parentID
                && sbill.Shared_Solar_System__r.BWC_Project_Entity_Manual__r.Id == entityId) {
                //add the system bills in reverse order so newest is first
                if (groupedSystemBillsList.isEmpty()) {
                    groupedSystemBillsList.add(sbill);
                } else {
                    groupedSystemBillsList.add(0, sbill);
                    maxbillnumber = sbill.Account_Bill_Number__c;
                    lastSystemBillDate = sbill.Date__c;
                }
            }
        }
        chTransaction.ChargentOrders__Response_Status__c = 'Returned';
        Datetime chCreatedDatetime = chTransaction.CreatedDate;
        Date chCreatedDate = Date.newInstance(chCreatedDatetime.year(), chCreatedDatetime.month(), chCreatedDatetime.day());
        if (lastSystemBillDate < chCreatedDate) {
            SystemBillPaymentRollUpHandler.listObject objectList = removePaymentFromSBs( groupedSystemBillsList,
                accountBillMap,
                payment,
                maxbillnumber,
                dateOfLastPayment,
                chTransaction);
            finalGroupedSystemBillsToUpdate.addAll(objectList.systemBills);
            finalAccountBillsToUpdate.addAll(objectList.accountBills);
            finalAdjustmentsToInsertList.addAll(objectList.billAdjustments);
            propaccountMap.get(parentID).Date_of_Last_Payment__c = dateOfLastPayment;

            if (finalGroupedSystemBillsToUpdate.size() > 0) {
                update finalGroupedSystemBillsToUpdate;
            }
            if (finalAdjustmentsToInsertList.size() > 0) {
                insert finalAdjustmentsToInsertList;
            }
            if (finalAccountBillsToUpdate.size() > 0) {
                update finalAccountBillsToUpdate;
            }
            update propaccountMap.values();
        } else {
            List<Utility_Account_Subscription__c> utilAccSubs = [
                SELECT Id, Opportunity__r.Shared_Solar_System__r.BWC_Project_Entity_Manual__c
                FROM Utility_Account_Subscription__c
                WHERE Utility_Account_Log__r.Account__c = : parentID
                AND Opportunity__r.Shared_Solar_System__c = : groupedSystemBillsList[0].Shared_Solar_System__c
                AND Next_Schedule_Z_Status__c = 'Active Subscription'
            ];

            Bill_Adjustment__c adjust = new Bill_Adjustment__c( Name = 'Returned Payment: ' + groupedSystemBillsList[0].Account_Bill__r.Name + ' ' + dateOfLastPayment.format(),
                Adjustment_Amount__c = payment,
                Overpayment__c = false,
                Entity__c = utilAccSubs[0].Opportunity__r.Shared_Solar_System__r.BWC_Project_Entity_Manual__c,
                Utility_Account_Subscription__c = utilAccSubs[0].Id,
                Source_ID__c = transactionId,
                Approval_Status__c = 'Approved',
                Reason_For_Adjustment__c = 'Payment was Marked as Returned after new Bills have been Published'
            );
            insert adjust;
        }
        update chTransaction;
    }

    public static SystemBillPaymentRollUpHandler.listObject removePaymentFromSBs (  List<System_Bill__c> groupedSystemBillsList,
        Map<Id,Account_Bill__c> accountBillMap,
        Decimal payment,
        Decimal maxbillnumber,
        Date dateOfLastPayment,
        ChargentOrders__Transaction__c chTransaction) {
        String transactionId = chTransaction.Id;
        List<System_Bill__c> groupedSystemBillsToUpdate = new List <System_Bill__c>();
        Map<String, Bill_Adjustment__c> adjustmentsToInsertList = new Map<String, Bill_Adjustment__c>();
        Map<Id, Decimal> reversedPaymentsToSSSThisMonth = new Map<Id, Decimal>();
        for (System_Bill__c systemBill : groupedSystemBillsList) {
            Account_Bill__c accountBill = accountBillMap.get(systemBill.Account_Bill__c);
            if (systemBill.Account_Bill_Number__c == maxbillnumber) {
                String entityId = chTransaction.ChargentOrders__Order__r.Entity__c;
                Decimal sbEntityOverpayments = getOverpaymentAmount(entityId, accountBill.Id, adjustmentsToInsertList);
                Decimal reversedAmount = Math.min(payment, systemBill.Total_Payments_This_Month__c + sbEntityOverpayments);

                // reduce overpayments by reversed payment amount
                Decimal applicationAmount = Math.min(reversedAmount, sbEntityOverpayments);
                payment -= applicationAmount;
                accountBill.Overpayment_Amount__c -= applicationAmount;
                if (applicationAmount > 0) {
                    Bill_Adjustment__c adjust = new Bill_Adjustment__c( Name = 'Reversed Overpayment: ' + systemBill.Account_Bill__r.Name + ' ' + dateOfLastPayment.format(),
                        Adjustment_Amount__c = applicationAmount,
                        Account_Bill__c = systemBill.Account_Bill__c,
                        Overpayment__c = true,
                        Entity__c = systemBill.Shared_Solar_System__r.BWC_Project_Entity_Manual__r.Id,
                        Source_ID__c = transactionId,
                        Approval_Status__c = 'Approved',
                        Reason_For_Adjustment__c = 'Payment was Marked as Returned'
                    );
                    String key = adjust.Account_Bill__c + '_' + adjust.Entity__c;
                    adjustmentsToInsertList.put(key, adjust);
                }
                accountBillMap.put(accountBill.Id, accountBill);

                // remove late fee payments from maxBill
                Decimal lateFeePayments = systemBill.Late_Fee_Payments__c;
                applicationAmount = Math.min(reversedAmount, lateFeePayments);
                payment -= applicationAmount;
                systemBill.Late_Fee_Payments__c -= applicationAmount;
                addAmountToMap(applicationAmount, systemBill.Shared_Solar_System__c, reversedPaymentsToSSSThisMonth);

                // remove Payments Net Previous Balances from maxBill
                Decimal paymentsNetPreviousBalances = systemBill.Payments_Net_Previous_Balances__c;
                applicationAmount = Math.min(reversedAmount, paymentsNetPreviousBalances);
                payment -= applicationAmount;
                systemBill.Payments_Net_Previous_Balances__c -= applicationAmount;
                addAmountToMap(applicationAmount, systemBill.Shared_Solar_System__c, reversedPaymentsToSSSThisMonth);

                groupedSystemBillsToUpdate.add(systemBill);

            } else if (systemBill.Account_Bill_Number__c < maxbillnumber) {
                // remove Late Payments from Previous bills
                Decimal latePayments = systemBill.Late_Payments__c;
                Decimal applicationAmount = Math.min(payment, latePayments);
                payment -= applicationAmount;
                systemBill.Late_Payments__c -= applicationAmount;
                addAmountToMap(applicationAmount, systemBill.Shared_Solar_System__c, reversedPaymentsToSSSThisMonth);
                groupedSystemBillsToUpdate.add(systemBill);
            }
        }
        for (System_Bill__c systemBill : groupedSystemBillsToUpdate) {
            if (systemBill.Account_Bill__r.Is_Most_Recent__c
                && reversedPaymentsToSSSThisMonth.containsKey(systemBill.Shared_Solar_System__c)) {
                systemBill.Total_Payments_This_Month__c -= reversedPaymentsToSSSThisMonth.get(systemBill.Shared_Solar_System__c);
            }
        }
        SystemBillPaymentRollUpHandler.listObject lists = new SystemBillPaymentRollUpHandler.listObject();
        lists.systemBills = groupedSystemBillsToUpdate;
        lists.accountBills = accountBillMap.values();
        lists.billAdjustments = adjustmentsToInsertList.values();
        return lists;
    }

    @testVisible
    private static Decimal getOverpaymentAmount(String entityId, Id accountBillId, Map<String, Bill_Adjustment__c> adjustmentsToInsertList) {
        List<Bill_Adjustment__c> overpayments = [
            SELECT Id, Overpayment__c, Entity__c, Outstanding__c
            FROM Bill_Adjustment__c
            WHERE Overpayment__c = true
            AND Entity__c = : entityId
            AND Account_Bill__c = : accountBillId
            AND Outstanding__c != 0
        ];
        Bill_Adjustment__c newAdjustment = adjustmentsToInsertList.get(accountBillId + '_'+ entityId);
        if (newAdjustment != null) {
            overpayments.add(newAdjustment);
        }
        System.debug(overpayments);
        Decimal totalOverpayments = 0;
        for (Bill_Adjustment__c overpayment : overpayments) {
            if (overpayment.Outstanding__c != null) {
                totalOverpayments += -1 * overpayment.Outstanding__c;
            } else {
                totalOverpayments += -1 * overpayment.Adjustment_Amount__c;
            }
        }
        System.debug('Overpayments');
        System.debug(totalOverpayments);
        return totalOverpayments;
    }

    private static void addAmountToMap(Decimal amount, Id idValue, Map<Id, Decimal> valueMap) {
        Decimal previousValue = valueMap.get(idValue);
        valueMap.put(idValue, Util.NullToZero(previousValue) + amount);
    }
}