src/objects/Account_Bill__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <label>Bill Statment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Published__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Published</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Reason_For_Unpublish__c</fullName>
        <label>Reason For Unpublish</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>Account Bill</label>
    <nameField>
        <label>Account Bill Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Bills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Bill_Adjustment__c.object
<CustomObject>
    <description>CS Billing: If we know that a UAS is going to need adjustments on a future bill, they are stored here until that bill is generated</description>
    <fields>
        <fullName>Account_Bill__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>XXAccount Bill</label>
        <referenceTo>Account_Bill__c</referenceTo>
        <relationshipLabel>Bill Adjustments</relationshipLabel>
        <relationshipName>Bill_Adjustments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Adjustment_Amount__c</fullName>
        <label>Adjustment Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Adjustment_Type__c</fullName>
        <inlineHelpText>Determines how this adjustment will be pulled into client reports: use &quot;Production&quot; for any delayed, missed or incorrectly billed credits. &quot;BW Credit&quot; for any adjustment for which BW will need to pay a client, etc. Contact Accounting with ?s</inlineHelpText>
        <label>Adjustment Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Production</fullName>
                </value>
                <value>
                    <fullName>Late Fee Waived</fullName>
                </value>
                <value>
                    <fullName>Customer Refund</fullName>
                </value>
                <value>
                    <fullName>BW Credit</fullName>
                </value>
                <value>
                    <fullName>Project Payment Transfer</fullName>
                </value>
                <value>
                    <fullName>Returned Payment</fullName>
                </value>
                <value>
                    <fullName>Client Credit</fullName>
                </value>
                <value>
                    <fullName>Returned Check Payment</fullName>
                </value>
                <value>
                    <fullName>No Longer Billing</fullName>
                </value>
                <value>
                    <fullName>Plympton TBD</fullName>
                    <isActive>false</isActive>
                    <label>Plympton TBD</label>
                </value>
                <value>
                    <fullName>Write - Off</fullName>
                    <isActive>false</isActive>
                    <label>Write - Off</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <defaultValue>&quot;Unapproved&quot;</defaultValue>
        <inlineHelpText>Set automatically by the approval process</inlineHelpText>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Unapproved</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Credits_Allocated__c</fullName>
        <label>Credits Allocated</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Reason_For_Adjustment__c</fullName>
        <label>Reason For Adjustment:</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>UASB__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Utility Account Subscription Bill</label>
        <referenceTo>UASB__c</referenceTo>
        <relationshipLabel>Bill Adjustments</relationshipLabel>
        <relationshipName>Bill_Adjustments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Utility_Account_Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Utility Account Subscription</label>
        <referenceTo>Utility_Account_Subscription__c</referenceTo>
        <relationshipLabel>Bill Adjustments</relationshipLabel>
        <relationshipName>Bill_Adjustments_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora_Id__c</fullName>
        <label>Zuora Id</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <label>Bill Adjustment</label>
    <nameField>
        <label>Bill Adjustment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bill Adjustments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Error_Log__c.object
<CustomObject>
    <description>Used for custom logging</description>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <length>130000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Error Log</label>
    <nameField>
        <displayFormat>EL-{0000}</displayFormat>
        <label>Error log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/UASB__c.object
<CustomObject
     >
    <description n1:nil="true" />
    <fields>
        <fullName>Adjustment_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Adjustment Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Credits_Allocated__c</fullName>
        <label>Credits Allocated</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Utility_Account_Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Utility Account Subscription</label>
        <referenceTo>Utility_Account_Subscription__c</referenceTo>
        <relationshipLabel>Utility Account Subscription Bills</relationshipLabel>
        <relationshipName>Utility_Account_Subscription_Bills</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora_Id__c</fullName>
        <label>Zuora Id</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <label>Utility Account Subscription Bill</label>
    <nameField>
        <displayFormat>UASB-{0000000}</displayFormat>
        <label>Utility Account Subscription Bill Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Utility Account Subscription Bills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Utility_Account_Subscription__c.object
<CustomObject>
    <label>Utility Account Subscription</label>
    <nameField>
        <label>Utility Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Account Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ZuoraCreditDebitMemoServiceTest.cls
@isTest
public class ZuoraCreditDebitMemoServiceTest {
    @testSetup public static void testDataSetup() {
        MultipleMonthProductionUpdateTest.multipleMonthTest();
        setBillsToUnPublished();

        List<UASB__c> uasbList = [
            SELECT Id, Name, Utility_Account_Subscription__r.Id
            FROM UASB__c
            ORDER BY Date__c
            LIMIT 2
        ];

        Bill_Adjustment__c adjustOne = new Bill_Adjustment__c(
            Name = 'UASoneAdjustment',
            Utility_Account_Subscription__c = uasbList[0].Utility_Account_Subscription__r.Id,
            UASB__c = uasbList[0].Id,
            Adjustment_Type__c = 'BW Credit',
            Adjustment_Amount__c = 90,
            Credits_Allocated__c = 100,
            Approval_Status__c = 'Approved',
            Reason_For_Adjustment__c = 'Needs adjustment');

        Bill_Adjustment__c adjustTwo = new Bill_Adjustment__c(
            Name = 'UASoneAdjustment2',
            Utility_Account_Subscription__c = uasbList[0].Utility_Account_Subscription__r.Id,
            UASB__c = uasbList[0].Id,
            Adjustment_Type__c = 'Client Credit',
            Adjustment_Amount__c = 45,
            Credits_Allocated__c = 50,
            Approval_Status__c = 'Approved',
            Reason_For_Adjustment__c = 'Needs adjustment');

        Bill_Adjustment__c adjustThree = new Bill_Adjustment__c(
            Name = 'UASoneAdjustment2',
            Utility_Account_Subscription__c = uasbList[1].Utility_Account_Subscription__r.Id,
            UASB__c = uasbList[1].Id,
            Adjustment_Type__c = 'BW Credit',
            Adjustment_Amount__c = 15,
            Approval_Status__c = 'Approved',
            Reason_For_Adjustment__c = 'Needs adjustment');

        Bill_Adjustment__c adjustFour = new Bill_Adjustment__c(
            Name = 'UASoneAdjustment2',
            Utility_Account_Subscription__c = uasbList[1].Utility_Account_Subscription__r.Id,
            UASB__c = uasbList[1].Id,
            Adjustment_Type__c = 'BW Credit',
            Adjustment_Amount__c = 99,
            Approval_Status__c = 'Approved',
            Zuora_Id__c = 'XXXXXXXXXXXXXXXXXX',
            Reason_For_Adjustment__c = 'Needs adjustment');

        insert new List<Bill_Adjustment__c>{adjustOne, adjustTwo, adjustThree, adjustFour};
    }

    public static void setBillsToUnPublished() {
        List <Account_Bill__c> listAccountBills = [
            SELECT Id, Published__c
            FROM Account_Bill__c
            WHERE Published__c = TRUE
        ];
        for (Account_Bill__c acctBill : listAccountBills) {
            acctBill.Published__c = FALSE;
            acctBill.Reason_For_Unpublish__c = 'Test reason for unpublishing this bill';
        }
        update listAccountBills;
    }

    @IsTest
    private static void testAPICallWithMock() {
        List<Bill_Adjustment__c> beforeCallList = AdjustmentSelector.getAdjustmentsNotYetInZuora(false);
        System.assertEquals(3, beforeCallList.size());

        Test.startTest();
        ZuoraCreditMemoBatchSend zSend = new ZuoraCreditMemoBatchSend();
        zSend.executeBatch();
        Test.stopTest();

        List<Bill_Adjustment__c> adjustList = [
            SELECT Id, Name, Zuora_Id__c
            FROM Bill_Adjustment__c
            WHERE Zuora_Id__c = '2c92c0fa6a3458e1016a45ac238e0d74'
        ];
        System.assertEquals(3, adjustList.size());

        List<Error_Log__c> errors = [
            SELECT Id, Message__c
            FROM Error_Log__c
        ];
        System.assertEquals(0, errors.size());
    }
}