src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Partner</label>
        <referenceTo>Partner__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Line__c</fullName>
        <label>Product Line</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Application_Type__c</fullName>
        <label>Application Type</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Income__c</fullName>
        <label>Income</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>LASERCA__Home_State__c</fullName>
        <label>Home State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Co-Applicants</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Partner_Lookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Link to the Partner Object related to this contact</inlineHelpText>
        <label>Partner Lookup</label>
        <referenceTo>Partner__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Line__c</fullName>
        <label>Product Line</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/LASERCA__Personal_Credit_Report__c.object
<CustomObject>
    <description>Experian Personal Credit Report, direct connect to Experian</description>
    <fields>
        <fullName>LASERCA__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Guarantors&apos; credit to be run
If this holds a value, DTI is calculated off Coapplicant Income</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Personal Credit Report</relationshipLabel>
        <relationshipName>Personal_Credit_Reports</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LASERCA__Credit_Score_TransUnion__c</fullName>
        <label>Credit Score (TransUnion)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LASERCA__Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Personal Credit Reports</relationshipLabel>
        <relationshipName>Personal_Credit_Reports</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Personal Credit Report</label>
    <nameField>
        <label>Personal Credit Report Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Personal Credit Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LASERCA__Trade_Accounts__c.object
<CustomObject>
    <description>The Liability Accounts listed on the credit report.</description>
    <fields>
        <fullName>Exclude_From_Rollup__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Excludes this trade account&apos;s monthly debt from the PCR &quot;Adjusted Monthly Personal Debt&quot; field, set by Avidia to remove trade accounts that are double-counted between main and co-applicants.</inlineHelpText>
        <label>Exclude From Rollup</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LASERCA__Account_Balance__c</fullName>
        <label>Account Balance</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>LASERCA__Account_Ownership_Type__c</fullName>
        <inlineHelpText>Account Ownership; Authorized User, Comaker, Individual, Joint Contractual Liability, Joint Participating, Maker, On Behalf Of, Terminated, Undesignated</inlineHelpText>
        <label>Account Ownership Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LASERCA__Credit_Loan_Type__c</fullName>
        <inlineHelpText>Type of Debt</inlineHelpText>
        <label>Credit Loan Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LASERCA__Monthly_Payment__c</fullName>
        <label>Monthly Payment</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>LASERCA__Name_of_the_Institution__c</fullName>
        <description>Name of the debt holder</description>
        <label>Name of the Institution</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LASERCA__Open_Date__c</fullName>
        <label>Open Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LASERCA__Personal_Credit_Report__c</fullName>
        <label>Personal Credit Report</label>
        <referenceTo>LASERCA__Personal_Credit_Report__c</referenceTo>
        <relationshipLabel>Trade Accounts</relationshipLabel>
        <relationshipName>Trade_Accounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>LASERCA__Remaining_Term__c</fullName>
        <label>Remaining Term</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>Trade Accounts</label>
    <nameField>
        <label>Trade Accounts Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trade Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Annual_Income_Currency__c</fullName>
        <label>Annual Income</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Application_Type__c</fullName>
        <label>Application Type</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Automatic_Product_Assignment__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Automatic Product Assignment</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Co_Applicant_Income__c</fullName>
        <label>Co-Applicant Income</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Joint_Applicant_Type__c</fullName>
        <label>Joint Applicant Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Co-Applicant</fullName>
                </value>
                <value>
                    <fullName>Co-Signer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LASERCA__Home_State__c</fullName>
        <label>Home State</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Partner_Lookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Partner</label>
        <referenceTo>Partner__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Personal_Credit_Report_Co_Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Personal Credit Report (Co-Applicant)</label>
        <referenceTo>LASERCA__Personal_Credit_Report__c</referenceTo>
        <relationshipLabel>Leads (Personal Credit Report (Co-Applicant))</relationshipLabel>
        <relationshipName>Leads2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Personal_Credit_Report__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Personal Credit Report</label>
        <referenceTo>LASERCA__Personal_Credit_Report__c</referenceTo>
        <relationshipLabel>Leads (Personal Credit Report)</relationshipLabel>
        <relationshipName>Leads1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Program__c</fullName>
        <description>This designates what program the customer&apos;s product is a part of. It gets its value from the product record relates to this lead. An example would be Perch&apos;s Solar Loan took part in the Massachusetts Solar Loan Program so the program would be MSLP.</description>
        <inlineHelpText>This designates what program the customer&apos;s product is a part of. It gets its value from the product record relates to this lead. An example would be Perch&apos;s Solar Loan took part in the Massachusetts Solar Loan Program so the program would be MSLP.</inlineHelpText>
        <label>Product Program</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>BlueWave Solar Loan</fullName>
                </value>
                <value>
                    <fullName>MSLP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_line__c</fullName>
        <label>Product Line</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unfinished_Lead__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This designates whether or not the full application has been completed by the applicant. If an application is still in process, this checkbox will stay unfinished (true).</description>
        <inlineHelpText>This designates whether or not the full application has been completed by the applicant. If an application is still in process, this checkbox will stay unfinished (true).</inlineHelpText>
        <label>Unfinished Lead</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Lead</fullName>
        <active>true</active>
        <businessProcess>CS</businessProcess>
        <label>Lead</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Partner__c.object
<CustomObject>
    <label>Partner</label>
    <nameField>
        <label>Partner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partners</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/PCRTradeAccountHandlerTest.cls
/**
 * Created by mstackhouse on 7/10/2018.
 * Description: 
 * Test: 
 */

@isTest
public with sharing class PCRTradeAccountHandlerTest {
    @TestSetup public static void testSetup() {
        LoanTestRecordWarehouse.partnerSetup();
        insert LoanTestRecordWarehouse.getLoanProductsVariableInterestRatesandTerms();

        RecordType solarLoanType = [
            SELECT Id
            FROM RecordType
            WHERE Name = 'BlueWave Solar Loan'
            AND SobjectType = 'Lead'
        ];

        Partner__c partner = [SELECT Id FROM Partner__c WHERE Name = 'Bluewave Inside Sales' LIMIT 1];


        Lead newLead = new Lead(
            LastName = 'PCRTradeAccountHandlerTest',
            RecordTypeId = solarLoanType.Id,
            FirstName = 'test',
            Automatic_Product_Assignment__c = false,
            Email = 'test@email.com',
            Company = 'Cloud Jedi',
            Status = 'Ready for Credit Check',
            Partner_Lookup__c = partner.Id,
            Annual_Income_Currency__c = 100000,
            Loan_Amount__c = 20000,
            Requested_Loan_Amount__c = 20000,
            Product_Line__c = 'Residential Loan',
            Product_Program__c = 'BlueWave Solar Loan',
            LASERCA__Home_State__c = 'MA',
            Application_Type__c = 'Joint',
            Joint_Applicant_Type__c = 'Co-Applicant',
            Unfinished_Lead__c = true,
            Co_Applicant_Income__c = 60000
        );
        insert newLead;

        Contact newContact = new Contact(
            FirstName = 'CoApplicant',
            LastName = 'Contact',
            Lead__c = newLead.Id,
            Income__c = newLead.Co_Applicant_Income__c
        );
        insert newContact;

        LASERCA__Personal_Credit_Report__c leadPCR = new LASERCA__Personal_Credit_Report__c(
            LASERCA__Lead__c = newLead.Id,
            LASERCA__Credit_Score_TransUnion__c = '700'
        );

        LASERCA__Personal_Credit_Report__c contactPCR = new LASERCA__Personal_Credit_Report__c(
            LASERCA__Contact__c = newContact.Id,
            LASERCA__Credit_Score_TransUnion__c = '700'
        );

        insert new List<LASERCA__Personal_Credit_Report__c>{leadPCR, contactPCR};

        newLead.Personal_Credit_Report__c = leadPCR.Id;
        newLead.Personal_Credit_Report_Co_Applicant__c = contactPCR.Id;
        update newLead;
    }

    @isTest static void testDeduplicateTradeAccounts() {
        Test.startTest();
        Lead lead = getLeadForTest();

        List<LASERCA__Personal_Credit_Report__c> pcrs = getPCRsForLead(lead);

        List<LASERCA__Trade_Accounts__c> tradeAccounts = new List<LASERCA__Trade_Accounts__c>();
        List<String> tradeAccountStrings = new List<String>();

        // add duplicate trade lines
        for (LASERCA__Personal_Credit_Report__c pcr : pcrs) {
            LASERCA__Trade_Accounts__c newTradeAccount = new LASERCA__Trade_Accounts__c(
                LASERCA__Name_of_the_Institution__c = 'JC Pennys',
                LASERCA__Account_Ownership_Type__c = 'JointContractualLiability',
                LASERCA__Account_Balance__c = 3402.12,
                LASERCA__Monthly_Payment__c = 123.45,
                LASERCA__Open_Date__c = Date.newInstance(2016, 1, 1),
                LASERCA__Personal_Credit_Report__c = pcr.Id
            );
            tradeAccounts.add(newTradeAccount);
            tradeAccountStrings.add(PCRTradeAccountHandler.matchAccountCriteria(newTradeAccount));
        }

        // add non-duplicate trade line for Co applicant
        tradeAccounts.add(new LASERCA__Trade_Accounts__c(
            LASERCA__Name_of_the_Institution__c = 'US Bank',
            LASERCA__Account_Ownership_Type__c = 'Individual',
            LASERCA__Account_Balance__c = 1200.00,
            LASERCA__Monthly_Payment__c = 100,
            LASERCA__Open_Date__c = Date.newInstance(2011, 4, 1),
            LASERCA__Personal_Credit_Report__c = lead.Personal_Credit_Report_Co_Applicant__c
        ));
        insert tradeAccounts;

        PCRTradeAccountHandler.makeTradeAccountAdjustments(lead);

        Test.stopTest();

        lead = getLeadForTest();
        System.assertEquals(tradeAccountStrings[0], tradeAccountStrings[1]);
        // only one trade account on the primary PCR it is a duplcate, but we keep the primary's trade account
        System.assertEquals(123.45, lead.Personal_Credit_Report__r.Adjusted_Monthly_Personal_Debt__c);
        // the JC Penny trade account gets excluded, so only the US Bank account counts
        System.assertEquals(100, lead.Personal_Credit_Report_Co_Applicant__r.Adjusted_Monthly_Personal_Debt__c);
        for (LASERCA__Trade_Accounts__c tradeAccount : [
            SELECT Id, Exclude_From_Rollup__c, LASERCA__Personal_Credit_Report__c, LASERCA__Name_of_the_Institution__c
            FROM LASERCA__Trade_Accounts__c
        ]) {
            if (tradeAccount.LASERCA__Personal_Credit_Report__c == lead.Personal_Credit_Report__c) {
                System.assertEquals(false, tradeAccount.Exclude_From_Rollup__c);
            } else {
                if (tradeAccount.LASERCA__Name_of_the_Institution__c == 'US Bank') {
                    System.assertEquals(false, tradeAccount.Exclude_From_Rollup__c);
                } else {
                    System.assertEquals(true, tradeAccount.Exclude_From_Rollup__c);
                }
            }
        }
    }

    @isTest static void testAutoTradeAccountAdjustments() {
        Test.startTest();
        Lead lead = getLeadForTest();

        List<LASERCA__Personal_Credit_Report__c> pcrs = getPCRsForLead(lead);

        List<LASERCA__Trade_Accounts__c> tradeAccounts = new List<LASERCA__Trade_Accounts__c>();
        List<String> tradeAccountStrings = new List<String>();

        // automotive trade account with more than 6 payments left should be included in rollup
        tradeAccounts.add(new LASERCA__Trade_Accounts__c(
            LASERCA__Name_of_the_Institution__c = 'More than 6 remaining term',
            LASERCA__Account_Ownership_Type__c = 'Individual',
            LASERCA__Credit_Loan_Type__c = 'Automotive',
            LASERCA__Account_Balance__c = 1200.00,
            LASERCA__Monthly_Payment__c = 112,
            LASERCA__Open_Date__c = Date.newInstance(2011, 4, 1),
            LASERCA__Remaining_Term__c = '12',
            LASERCA__Personal_Credit_Report__c = lead.Personal_Credit_Report_Co_Applicant__c
        ));

        // automotive trade account with 6 payments left should be excluded from rollup
        tradeAccounts.add(new LASERCA__Trade_Accounts__c(
            LASERCA__Name_of_the_Institution__c = 'Less than 6 remaining term',
            LASERCA__Account_Ownership_Type__c = 'Individual',
            LASERCA__Credit_Loan_Type__c = 'Automotive',
            LASERCA__Account_Balance__c = 1200.00,
            LASERCA__Monthly_Payment__c = 106,
            LASERCA__Open_Date__c = Date.newInstance(2011, 4, 1),
            LASERCA__Remaining_Term__c = '6',
            LASERCA__Personal_Credit_Report__c = lead.Personal_Credit_Report_Co_Applicant__c
        ));

        // automotive trade account with less than 6 payments left should be excluded from rollup
        tradeAccounts.add(new LASERCA__Trade_Accounts__c(
            LASERCA__Name_of_the_Institution__c = 'null remaining term',
            LASERCA__Account_Ownership_Type__c = 'Individual',
            LASERCA__Credit_Loan_Type__c = 'Automotive',
            LASERCA__Account_Balance__c = 1200.00,
            LASERCA__Monthly_Payment__c = 100,
            LASERCA__Open_Date__c = Date.newInstance(2011, 4, 1),
            LASERCA__Remaining_Term__c = null,
            LASERCA__Personal_Credit_Report__c = lead.Personal_Credit_Report_Co_Applicant__c
        ));
        insert tradeAccounts;

        PCRTradeAccountHandler.makeTradeAccountAdjustments(lead);

        Test.stopTest();

        lead = getLeadForTest();
        // only one trade account on the primary PCR should be counted
        System.assertEquals(112, lead.Personal_Credit_Report__r.Adjusted_Monthly_Personal_Debt__c);
        for (LASERCA__Trade_Accounts__c tradeAccount : [
            SELECT Id, Exclude_From_Rollup__c, LASERCA__Personal_Credit_Report__c, LASERCA__Name_of_the_Institution__c
            FROM LASERCA__Trade_Accounts__c
        ]) {
            if (tradeAccount.LASERCA__Name_of_the_Institution__c == 'More than 6 remaining term') {
                System.assertEquals(false, tradeAccount.Exclude_From_Rollup__c);
            } else if (tradeAccount.LASERCA__Name_of_the_Institution__c == 'Less than 6 remaining term') {
                System.assertEquals(true, tradeAccount.Exclude_From_Rollup__c);
            } else if (tradeAccount.LASERCA__Name_of_the_Institution__c == 'null remaining term') {
                System.assertEquals(true, tradeAccount.Exclude_From_Rollup__c);
            }
        }
    }

    static Lead getLeadForTest() {
        Lead lead = [
            SELECT Id, Application_Type__c, Personal_Credit_Report__c, Personal_Credit_Report_Co_Applicant__c,
                Personal_Credit_Report__r.Adjusted_Monthly_Personal_Debt__c,
                Personal_Credit_Report_Co_Applicant__r.Adjusted_Monthly_Personal_Debt__c
            FROM Lead
            WHERE LastName = 'PCRTradeAccountHandlerTest'
        ];
        return lead;
    }

    static List<LASERCA__Personal_Credit_Report__c> getPCRsForLead(Lead lead) {
        List<LASERCA__Personal_Credit_Report__c> pcrs = [
            SELECT Id
            FROM LASERCA__Personal_Credit_Report__c
            WHERE Id = : lead.Personal_Credit_Report__c
            OR Id = : lead.Personal_Credit_Report_Co_Applicant__c
        ];
        return pcrs;
    }
}