src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Partner</label>
        <referenceTo>Partner__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Product lookup, for loans, set by an installer upon sending a new application or set by code after a credit check has determined qualifying products.</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Lead</fullName>
        <active>true</active>
        <businessProcess>CS</businessProcess>
        <label>Lead</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Loan__c.object
<CustomObject>
    <fields>
        <fullName>Commencement_Datee__c</fullName>
        <inlineHelpText>The estimated commencement date of the loan, 30 days after the estimated completion date. Set by installers when providing system information.</inlineHelpText>
        <label>Commencement Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Financing_Fee__c</fullName>
        <description>Set by Apex from the Lead&apos;s Loan Financing Fee field.</description>
        <inlineHelpText>LoanHandler code sets this from the Lead&apos;s &quot;Loan Financing Fee&quot; field when creating the Loan.</inlineHelpText>
        <label>Financing Fee</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Set by LoanHandler when creating the Loan from the lead</inlineHelpText>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Loans</relationshipLabel>
        <relationshipName>Loans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Loan_Number__c</fullName>
        <displayFormat>BW{0000000}</displayFormat>
        <externalId>true</externalId>
        <inlineHelpText>Auto-Number used to identify the Loan with external parties (like third party servicing)</inlineHelpText>
        <label>Loan Number</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Loan_Term__c</fullName>
        <description>This is a formula referencing the Loan Term as defined in the assigned Product.  It represents the length of the amortization period of the loan in months.</description>
        <formula>Product__r.Loan_Term__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>This is a formula referencing the Loan Term as defined in the assigned Product.  It represents the length of the amortization period of the loan in months.</inlineHelpText>
        <label>Loan Term</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Loan_Tranche__c</fullName>
        <label>Loan Tranche</label>
        <referenceTo>Loan_Traunch__c</referenceTo>
        <relationshipLabel>Loans</relationshipLabel>
        <relationshipName>Loans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Set by LoanHandler when the Loan&apos;s Lead is converted to an Opportunity</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Loans</relationshipLabel>
        <relationshipName>Loans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Set by LoanHandler when the Loan is created from a Lead</inlineHelpText>
        <label>Partner</label>
        <referenceTo>Partner__c</referenceTo>
        <relationshipLabel>Loans</relationshipLabel>
        <relationshipName>Loans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is a lookup to the Product record assigned to this loan.  The designated Product informs key loan determinants (e.g. interest rate, term, form of promissory note).</description>
        <inlineHelpText>This is a lookup to the Product record assigned to this loan.  The designated Product informs key loan determinants (e.g. interest rate, term, form of promissory note).</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Loans</relationshipLabel>
        <relationshipName>Loans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>System_Costt__c</fullName>
        <inlineHelpText>The request loan amount (could be different than the true system cost)</inlineHelpText>
        <label>XXX System Cost</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Loan</label>
    <nameField>
        <label>Loan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loans</pluralLabel>
    <recordTypes>
        <fullName>Loan</fullName>
        <active>true</active>
        <label>Loan</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Loan_Traunch__c.object
<CustomObject>
    <label>Loan Tranche</label>
    <nameField>
        <label>Tranche</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Tranches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Set by OpportunityTriggerHandler on Opportunity creation, assuming Opportunity.Lead_ID__c (a text field) is also being set via Lead Mapping.</inlineHelpText>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Partner__c.object
<CustomObject>
    <label>Partner</label>
    <nameField>
        <label>Partner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partners</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Loan_Interest_Only_Period__c</fullName>
        <label>Loan Interest Only Period</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Loan_Interest_Rate__c</fullName>
        <label>Loan Interest Rate</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Loan_Term__c</fullName>
        <label>Loan Term</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/LeaseDimensionsImportControllerTest.cls
/*************************************************************************************
 * Created By:  Peter Yao 
 * Description: Tests LeaseDimensionsImportController and CSVReader
 *************************************************************************************/
@isTest
public with sharing class LeaseDimensionsImportControllerTest {
    @testSetup static void setupTestData() {
        LoanServicerTest.setupTestData();

        Product2 ma10Yr = [SELECT Id, Loan_Interest_Rate__c, Loan_Term__c, Loan_Interest_Only_Period__c
                           FROM Product2
                           WHERE Name = 'BlueWave Solar Loan - MA - 10 Year Term - 5.99%' LIMIT 1];
        Loan_Traunch__c loanTraunch = [SELECT Id FROM Loan_Traunch__c WHERE Name = 'Tranche Assignment Pending' LIMIT 1];
        Lead testLead = [SELECT Id FROM Lead WHERE LastName = 'Testerson' LIMIT 1];
        Opportunity opp = [SELECT Id FROM Opportunity WHERE Name = 'Testerson Loan' LIMIT 1];
        Partner__c partner = [SELECT Id FROM Partner__c WHERE Name = 'Partner' LIMIT 1];

        Loan__c loan = new Loan__c(Product__c = ma10Yr.Id,
                                   Lead__c = testLead.Id,
                                   Partner__c = partner.Id,
                                   Opportunity__c = opp.Id,
                                   Loan_Tranche__c = loanTraunch.Id,
                                   System_Costt__c = 40316.93,
                                   Financing_Fee__c = 2015.85,
                                   Commencement_Datee__c = Date.today());
        insert loan;
    }

    static testMethod void testFileLoad() {
        Loan__c loan = [SELECT Loan_Number__c from Loan__c LIMIT 1];
        testFile = testFile.replace('GOODLOANINIO', loan.Loan_Number__c.replace('BW',''));

        System.debug(LoggingLevel.ERROR, testFile);

        testFile = testFile.replace('GOODLOANINPI', loan.Loan_Number__c);

        System.debug(LoggingLevel.ERROR, testFile);

        Test.startTest();
        LeaseDimensionsImportController ldic = new LeaseDimensionsImportController();
        ldic.document = new Document(name='foo',
                                     body = Blob.valueOf(testFile));
        ldic.loadCSV();
        System.debug(LoggingLevel.ERROR, ldic.loanNumbers);
        System.assertEquals(3, ldic.loanNumbers.size());
        
        System.assertEquals(1, ldic.loansFound.size());
        Test.stopTest();
        
    }

    public static string testFile = 
        'Portfolio,Company,Region,Office,Account #,Customer Name,Process Date,Payment Effective Date,Invoice Due Date,Transaction Description,Invoice Number,Check Number,Cash Code, Amount ,Reversal Reason,Comments\n' +
        '2,1,1,4,GOODLOANINIO,Daniel Prince,5/19/2017,5/27/2017,5/27/2017,IBL PMT - INTEREST,2866,5486,125, 131.74 ,,\n' +
        '2,1,2,1,GOODLOANINPI,Michael Woodcock and Lauren Woodcock,5/19/2017,6/6/2017,6/6/2017,IBL PMT - INTEREST,3033,A051817,125, 74.12 ,,\n' +
        '2,1,2,1,GOODLOANINPI,Michael Woodcock and Lauren Woodcock,5/19/2017,6/6/2017,6/6/2017,IBL PMT - PRINCIPAL,3033,A051817,125, 186.18 ,,\n' +
        '2,1,2,1,BW0099999,Kathryn Farrell and Donald Fail,5/19/2017,4/3/2017,,IBL PRN WRITE-DOWN,,BW IBLS PAYDOWN APR 17,130," (6,121.50)",UNDO,\n' +
        ',,,,,,,,,,,,,,,\n';        
}