src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Client_Brand_Key__c</fullName>
        <inlineHelpText>Set before an opportunity is inserted, or if the Account, SSS, or Stage is updated on the opportunity. Also set if the Client Brand Key on a SSS is updated.</inlineHelpText>
        <label>Client Brand Key</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Client_Logo_Filenames</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Count_of_Large_Offtake_Opps__c</fullName>
        <inlineHelpText>Count of non-Cancelled Anchor opportunities that indicate whether this Property Account is large offtake, in which case the cancellation process is manual.</inlineHelpText>
        <label>Count of Large Offtake Opps</label>
        <summaryFilterItems>
            <field>Opportunity.Customer_Group__c</field>
            <operation>equals</operation>
            <value>Anchor</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Opportunity.StageName</field>
            <operation>notEqual</operation>
            <value>Cancelled</value>
        </summaryFilterItems>
        <summaryForeignKey>Opportunity.AccountId</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Parent_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Lookup to Parent Account</inlineHelpText>
        <label>Parent Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Properties</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Recurring_Billing__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>An indicator to tell whether the Property Account is on autopay. Only used to update the message on the bill. To take a customer off of autopay, use the payment component on the Billing Account to Manage Autopay</inlineHelpText>
        <label>Autopay</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Zuora_Id__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>Set by ZuoraAccountService after it creates the account in Zuora from a converted lead</inlineHelpText>
        <label>Zuora Id</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora_Invoice_Message_1_of_2__c</fullName>
        <inlineHelpText>If left blank, the default autopay or non-autopay message will be used. Limited to 200 characters. Shows up in top left box of invoice template</inlineHelpText>
        <label>Zuora Invoice Message 1 of 2</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Zuora_Invoice_Message_2_of_2__c</fullName>
        <inlineHelpText>If left blank, the default autopay or non-autopay message will be used. Limited to 200 characters</inlineHelpText>
        <label>Zuora Invoice Message 2 of 2</label>
        <type>TextArea</type>
    </fields>
    <recordTypes>
        <fullName>Property</fullName>
        <active>true</active>
        <label>Property</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/CS_Bill_Setting__c.object
<CustomObject>
    <description>Used to manage CS Billing settings</description>
    <fields>
        <fullName>Default_Bill_Message_for_Autopay__c</fullName>
        <inlineHelpText>CongaTemplateAssigner copies this value onto Account Bills for autopay customers when assigning bill templates.</inlineHelpText>
        <label>Default Bill Message for Autopay</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Default_Bill_Message_for_Non_Autopay__c</fullName>
        <inlineHelpText>CongaTemplateAssigner copies this value onto Account Bills for autopay customers when assigning bill templates.</inlineHelpText>
        <label>Default Bill Message for Non-Autopay</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <label>CS Bill Setting</label>
    <nameField>
        <displayFormat>CSBS-{0000}</displayFormat>
        <label>CS Bill Setting Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CS Bill Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Error_Log__c.object
<CustomObject>
    <description>Used for custom logging</description>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <length>130000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Method__c</fullName>
        <label>Method</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Error Log</label>
    <nameField>
        <displayFormat>EL-{0000}</displayFormat>
        <label>Error log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Customer_Group__c</fullName>
        <label>Customer Group</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Residential</fullName>
                </value>
                <value>
                    <fullName>Non-Residential</fullName>
                    <default>true</default>
                    <label>Non-Residential</label>
                </value>
                <value>
                    <fullName>Anchor</fullName>
                </value>
                <value>
                    <fullName>Business</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Parent_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/zqu__InvoiceTemplate__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Anchor__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Anchor</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Autopay__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Autopay</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Brand_Key__c</fullName>
        <label>Brand Key</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Client_Logo_Filenames</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

src/globalValueSets/Client_Logo_Filenames.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>AmpBlack</fullName>
    </customValue>
    <customValue>
        <fullName>BluewaveLogo</fullName>
    </customValue>
    <customValue>
        <fullName>AmpRed</fullName>
    </customValue>
    <customValue>
        <fullName>DSD</fullName>
    </customValue>
    <masterLabel>Client Logo Filenames</masterLabel>
</GlobalValueSet>

src/classes/InvoiceTemplateAssignerTest.cls
@isTest
public class InvoiceTemplateAssignerTest {
    public static final String NON_AUTOPAY_MESSAGE = 'Non-Autopay Message';
    public static final String AUTOPAY_MESSAGE = 'Autopay Message';

    @testSetup static void setupTestData() {
        zqu__InvoiceTemplate__c anchorTemplate = new zqu__InvoiceTemplate__c(
            Active__c = true,
            Autopay__c = false,
            Anchor__c = true,
            Brand_Key__c = 'BluewaveLogo',
            zqu__ZuoraId__c = 'anchorTemplate'
        );

        zqu__InvoiceTemplate__c inactiveTemplate = new zqu__InvoiceTemplate__c(
            Active__c = false,
            Autopay__c = false,
            Anchor__c = true,
            Brand_Key__c = 'BluewaveLogo',
            zqu__ZuoraId__c = 'inactiveTemplate'
        );

        zqu__InvoiceTemplate__c bwNonAnchor = new zqu__InvoiceTemplate__c(
            Active__c = true,
            Autopay__c = false,
            Anchor__c = false,
            Brand_Key__c = 'BluewaveLogo',
            zqu__ZuoraId__c = 'bwNonAnchor'
        );

        zqu__InvoiceTemplate__c ampNonAnchor = new zqu__InvoiceTemplate__c(
            Active__c = true,
            Autopay__c = false,
            Anchor__c = false,
            Brand_Key__c = 'AmpRed',
            zqu__ZuoraId__c = 'ampNonAnchor'
        );

        zqu__InvoiceTemplate__c bwAutopay = new zqu__InvoiceTemplate__c(
            Active__c = true,
            Autopay__c = true,
            Anchor__c = false,
            Brand_Key__c = 'BluewaveLogo',
            zqu__ZuoraId__c = 'bwAutopay'
        );

        zqu__InvoiceTemplate__c ampAutopay = new zqu__InvoiceTemplate__c(
            Active__c = true,
            Autopay__c = true,
            Anchor__c = true,
            Brand_Key__c = 'AmpRed',
            zqu__ZuoraId__c = 'ampAutopay'
        );

        // Missing: AMP Short Autopay to test error handling
        insert new List<zqu__InvoiceTemplate__c>{
            anchorTemplate, inactiveTemplate, bwNonAnchor,
            ampNonAnchor, bwAutopay, ampAutopay
        };

        Account accountParent = new Account(
            Name = 'Amp ParentAccount',
            Client_Brand_Key__c = 'AmpRed');
        Account accountParent2 = new Account(
            Name = 'BlueWave ParentAccount',
            Client_Brand_Key__c = 'BluewaveLogo');
        insert new List<Account>{accountParent,accountParent2};

        Account accountA = new Account(
            Name = 'Anchor Property',
            Recurring_Billing__c = true,
            Zuora_Id__c = 'AnchorAutopay',
            Zuora_Invoice_Message_1_of_2__c = 'Custom Message One',
            Zuora_Invoice_Message_2_of_2__c = 'Custom Message Two',
            Parent_Account__c = accountParent.Id);
        Account accountB = new Account(
            Name = 'Smallofftake Property',
            Recurring_Billing__c = false,
            Zuora_Id__c = 'SmallNonAutopay',
            Parent_Account__c = accountParent2.Id);
        insert new List<Account>{accountA, accountB};

        Opportunity opportunityone =
            new Opportunity(Name = 'Anchor Opp',
                AccountId = accountA.Id,
                StageName = 'Complete',
                Customer_Group__c = 'Anchor',
                CloseDate = System.today());

        Opportunity opportunitytwo =
            new Opportunity(Name = 'Resi One',
                AccountId = accountB.Id,
                StageName = 'Complete',
                Customer_Group__c = 'Residential',
                CloseDate = System.today());

        Opportunity opportunitythree =
            new Opportunity(Name = 'PublicOfftake Two',
                AccountId = accountA.Id,
                StageName = 'Complete',
                Customer_Group__c = 'Public Offtake',
                CloseDate = System.today());
        insert new List<Opportunity>{
            opportunityone, opportunitytwo, opportunitythree
        };

        CS_Bill_Setting__c csBillSetting = new CS_Bill_Setting__c(
            Default_Bill_Message_for_Autopay__c = AUTOPAY_MESSAGE,
            Default_Bill_Message_for_Non_Autopay__c = NON_AUTOPAY_MESSAGE
        );
        insert csBillSetting;
    }

    @isTest public static void testBatchRun(){
        List<Error_Log__c> oldLogs = [
            SELECT Id, Message__c
            FROM Error_Log__c
            WHERE Class__c = 'ZuoraAPIHelper'
        ];
        System.assertEquals(0,oldLogs.size());

        Test.startTest();
        InvoiceTemplateAssigner assigner = new InvoiceTemplateAssigner();
        assigner.executeBatch();
        Test.stopTest();

        List<Error_Log__c> logs = [
            SELECT Id, Message__c
            FROM Error_Log__c
            WHERE Class__c = 'ZuoraAPIHelper'
        ];
        System.assertEquals(1,logs.size());
    }

    @isTest public static void testAutopay() {
        List<Account> acctList = [
            SELECT Id, Name, Zuora_Id__c,
                Parent_Account__r.Client_Brand_Key__c,
                Recurring_Billing__c, Count_of_Large_Offtake_Opps__c,
                Zuora_Invoice_Message_1_of_2__c, Zuora_Invoice_Message_2_of_2__c
            FROM Account
            WHERE Zuora_Id__c != null ];

        InvoiceTemplateAssigner assigner = new InvoiceTemplateAssigner();
        List<zqu__InvoiceTemplate__c> templates = assigner.getTemplateList();
        List<ZuoraAPI.ZuoraAccount> zuoraAccount = assigner.assignTemplates(acctList,templates);

        // 6 templates exist, only 5 are active:
        System.assertEquals(5, templates.size());
        System.assertEquals(2, zuoraAccount.size());

        for (ZuoraAPI.ZuoraAccount account : zuoraAccount){
            if (account.Id == 'AnchorAutopay'){
                System.assertEquals('ampAutopay', account.InvoiceTemplateId);
                System.assertEquals('Custom Message One', account.Notes);
                System.assertEquals('Custom Message Two', account.BillMessage_Zcustom);
            } else {
                System.assertEquals('bwNonAnchor', account.InvoiceTemplateId);
                System.assertEquals(NON_AUTOPAY_MESSAGE, account.Notes);
            }
        }
    }

    @isTest public static void testHTMLTags(){
        List<CS_Bill_Setting__c> billSetting = [
            SELECT Id, Default_Bill_Message_for_Non_Autopay__c
            FROM CS_Bill_Setting__c
        ];

        billSetting[0].Default_Bill_Message_for_Non_Autopay__c = 'This message has <b> some html </b> tags';

        update billSetting[0];

        Test.startTest();
        InvoiceTemplateAssigner assigner = new InvoiceTemplateAssigner();
        assigner.executeBatch();
        Test.stopTest();

        List<Error_Log__c> logs = [
            SELECT Id, Message__c, Method__c
            FROM Error_Log__c
            WHERE Method__c = 'Bill Message contains hmtl tag'
        ];
        System.assertEquals(1,logs.size());
    }
}