src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Max_Account_Bill_Number__c</fullName>
        <label>Max Account Bill Number</label>
        <summarizedField>Account_Bill__c.Bill_Number__c</summarizedField>
        <summaryFilterItems>
            <field>Account_Bill__c.Published__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>Account_Bill__c.Parent_Account__c</summaryForeignKey>
        <summaryOperation>max</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Parent_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Lookup to Parent Account</inlineHelpText>
        <label>Parent Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Properties</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Account_Bill__c.object
<CustomObject>
    <fields>
        <fullName>Bill_Number__c</fullName>
        <label>Bill Number</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Carry_Over_Balance__c</fullName>
        <label>Carry Over Balance</label>
        <summarizedField>System_Bill__c.Carry_Over_Balance__c</summarizedField>
        <summaryForeignKey>System_Bill__c.Account_Bill__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Due_Date_SB__c</fullName>
        <label>Due Date</label>
        <summarizedField>System_Bill__c.Bill_Due_Date__c</summarizedField>
        <summaryFilterItems>
            <field>System_Bill__c.Bill_Due_Date__c</field>
            <operation>notEqual</operation>
            <value></value>
        </summaryFilterItems>
        <summaryForeignKey>System_Bill__c.Account_Bill__c</summaryForeignKey>
        <summaryOperation>min</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Parent_Account__c</fullName>
        <label>Property Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Bills</relationshipLabel>
        <relationshipName>Account_Bills</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Shared_Solar_System__c</fullName>
        <label>Shared Solar System</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>Account Bill</label>
    <nameField>
        <label>Account Bill Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Bills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Autopay_Schedule__c.object
<CustomObject>
    <description>Used to drive when recurring Chargent Orders are updated, and to consolidate pre-charge QC results</description>
    <fields>
        <fullName>Summary__c</fullName>
        <inlineHelpText>Populated by code after the RecurringPaymentHandler is finished</inlineHelpText>
        <label>Summary</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Autopay Schedule</label>
    <nameField>
        <displayFormat>APS-{0000}</displayFormat>
        <label>Autopay Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Autopay Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Shared_Solar_System__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Shared Solar System</label>
        <referenceTo>Shared_Solar_System__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Case</fullName>
        <active>true</active>
        <businessProcess>Customer Care Case</businessProcess>
        <label>Case</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Entity__c.object
<CustomObject>
    <fields>
        <fullName>Gateway__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Gateway</label>
        <referenceTo>ChargentBase__Gateway__c</referenceTo>
        <relationshipLabel>Entities</relationshipLabel>
        <relationshipName>Entities</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Entity</label>
    <nameField>
        <label>Entity</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Shared_Solar_System__c.object
<CustomObject
     >
    <articleTypeChannelDisplay n1:nil="true" />
    <customSettingsType n1:nil="true" />
    <description n1:nil="true" />
    <eventType n1:nil="true" />
    <fields>
        <fullName>BWC_Project_Entity_Manual__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Entity name of project.</inlineHelpText>
        <label>Project Entity</label>
        <referenceTo>Entity__c</referenceTo>
        <relationshipLabel>Shared Solar Systems</relationshipLabel>
        <relationshipName>Shared_Solar_Systems</relationshipName>
        <type>Lookup</type>
    </fields>
    <gender n1:nil="true" />
    <household>false</household>
    <label>Shared Solar System</label>
    <nameField>
        <label>Shared Solar System Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shared Solar Systems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <startsWith n1:nil="true" />
</CustomObject>

src/objects/System_Bill__c.object
<CustomObject>
    <fields>
        <fullName>Account_Bill__c</fullName>
        <label>Account Bill</label>
        <referenceTo>Account_Bill__c</referenceTo>
        <relationshipLabel>System Bills</relationshipLabel>
        <relationshipName>System_Bills</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Bill_Number__c</fullName>
        <label>Bill Number</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Carry_Over_Balance__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Carry Over Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Property_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>System Bills</relationshipLabel>
        <relationshipName>System_Bills</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shared_Solar_System__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Shared Solar System</label>
        <referenceTo>Shared_Solar_System__c</referenceTo>
        <relationshipLabel>System Bills</relationshipLabel>
        <relationshipName>System_Bills</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>System Bill</label>
    <nameField>
        <label>System Bill Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>System Bills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/AutopayChecker.cls
/*************************************************************************************
 * Created By: peteryao on 10/17/18
 * Description:
 * Tested by: AutopayCheckerTest
 *************************************************************************************/

public with sharing class AutopayChecker implements Queueable {
    Id autopayScheduleId;
    Map<Id, ChargentBase__Gateway__c> gateways;
    List<ChargentOrders__ChargentOrder__c> recurringOrders;
    public AutopayChecker(Id autopayScheduleId) {
        this.autopayScheduleId = autopayScheduleId;
        recurringOrders = [
            SELECT Id, Account_Bill__c, Account_Bill__r.Bill_Number__c, Account_Bill__r.Parent_Account__r.Max_Account_Bill_Number__c,
                Account_Bill__r.Due_Date_SB__c, Property_Account__c, Account_Bill__r.Carry_Over_Balance__c,
                ChargentOrders__Charge_Date__c, ChargentOrders__Charge_Amount__c, ChargentOrders__Payment_Start_Date__c,
                ChargentOrders__Next_Transaction_Date__c, Entity__c, ChargentOrders__Gateway__c, ChargentOrders__Billing_Last_Name__c
            FROM ChargentOrders__ChargentOrder__c
            WHERE ChargentOrders__Payment_Status__c = 'Recurring'
        ];
        gateways = new Map<Id, ChargentBase__Gateway__c>([SELECT Id, Name FROM ChargentBase__Gateway__c]);
    }

    public void execute(QueueableContext context) {
        Autopay_Schedule__c autopaySchedule;
        List<Autopay_Schedule__c> autopaySchedules = [
            SELECT Id, Summary__c
            FROM Autopay_Schedule__c
            WHERE Id =: autopayScheduleId
            LIMIT 1
        ];
        if (autopaySchedules.size() != 1) {
            Logger.logNow('AutopayChecker', 'execute', 'No autopay schedule found with Id ' + autopayScheduleId);
            return;
        } else {
            autopaySchedule = autopaySchedules[0];
        }
        autopaySchedule.Summary__c += '\n\n';
        autopaySchedule.Summary__c += getTotalAmountByGateway().message + '\n';
        autopaySchedule.Summary__c += checkRecurringOrdersOnLastAccountBill().message + '\n';
        autopaySchedule.Summary__c += checkSingleOrderPerAccountEntity().message + '\n';
        autopaySchedule.Summary__c += checkChargeAmountEqualsCarryoverBalance().message + '\n';
        autopaySchedule.Summary__c += checkZeroDollarChargentOrdersNotToFire().message + '\n';
        autopaySchedule.Summary__c += checkChargentOrderEntitiesAndGatewaysAgainstAccountBill().message + '\n';

        update autopaySchedule;
    }

    public QCResult getTotalAmountByGateway() {
        // In case we have payments on different charge dates (not 01 or 1):
        Map<Integer, Map<Id, GatewayTotal>> gatewayTotalsByChargeDate = getGatewayTotalsByChargeDate();
        String message = 'Gateway Totals by Charge Date:\n';
        for (Integer chargeDate : gatewayTotalsByChargeDate.keySet()) {
            message += 'Charge Date: ' + chargeDate + '\n';
            List<GatewayTotal> gatewayTotals = gatewayTotalsByChargeDate.get(chargeDate).values();
            gatewayTotals.sort();
            for (GatewayTotal gatewayTotal : gatewayTotals) {
                message += gatewayTotal.gatewayName + ': $' + gatewayTotal.total.format() + '\n';
            }
        }
        return new QCResult(true, message);
    }

    private Map<Integer, Map<Id, GatewayTotal>> getGatewayTotalsByChargeDate() {
        List<AggregateResult> results = [
            SELECT ChargentOrders__Charge_Date__c, ChargentOrders__Gateway__c, SUM(ChargentOrders__Charge_Amount__c) total
            FROM ChargentOrders__ChargentOrder__c
            WHERE ChargentOrders__Payment_Status__c = 'Recurring'
            GROUP BY ChargentOrders__Charge_Date__c, ChargentOrders__Gateway__c
        ];

        Map<Integer, Map<Id, GatewayTotal>> gatewayTotalsByChargeDate = new Map<Integer, Map<Id, GatewayTotal>>();
        for (AggregateResult result : results) {
            Integer chargeDate = 0;
            if (result.get('ChargentOrders__Charge_Date__c') != null) {
                chargeDate = Integer.valueOf(result.get('ChargentOrders__Charge_Date__c'));
            }
            GatewayTotal gatewayTotal = new GatewayTotal(this, result);
            if (gatewayTotalsByChargeDate.containsKey(chargeDate)) {
                gatewayTotal.addToGatewayTotalList(gatewayTotalsByChargeDate.get(chargeDate));
            } else {
                gatewayTotalsByChargeDate.put(chargeDate, new Map<Id, GatewayTotal>{gatewayTotal.gatewayId=>gatewayTotal});
            }
        }
        return gatewayTotalsByChargeDate;
    }

    public QCResult checkRecurringOrdersOnLastAccountBill() {
        Boolean passed = true;
        List<Id> orderIds = new List<Id>();
        for (ChargentOrders__ChargentOrder__c order : recurringOrders) {
            if (order.Account_Bill__c == null ||
                order.Account_Bill__r.Bill_Number__c != order.Account_Bill__r.Parent_Account__r.Max_Account_Bill_Number__c ||
                order.Account_Bill__r.Due_Date_SB__c < Date.today()) {
                passed = false;
                orderIds.add(order.Id);
            }
        }
        String message;
        if (orderIds.isEmpty()) {
            message = 'All recurring orders are the latest account bill';
        } else {
            message = 'These orders are not on the latest account bill: (' + trimIdList(orderIds) + ')\n';
        }
        return new QCResult(passed, message);
    }

    public QCResult checkSingleOrderPerAccountEntity() {
        List<AggregateResult> results = [
            SELECT Account_Bill__r.Parent_Account__c account, Entity__c, COUNT(Id) numOrders
            FROM ChargentOrders__ChargentOrder__c
            WHERE ChargentOrders__Payment_Status__c = 'Recurring'
            AND Account_Bill__c != NULL
            GROUP BY Account_Bill__r.Parent_Account__c, Entity__c
            ORDER BY COUNT(Id) DESC
        ];

        Boolean passed = true;
        List<Id> accountIds = new List<Id>();
        for (AggregateResult result : results) {
            if ((Integer) result.get('numOrders') > 1) {
                accountIds.add((Id) result.get('account'));
                passed = false;
            } else {
                break;
            }
        }
        String message;
        if (accountIds.isEmpty()) {
            message = 'All accounts and entities combinations have a single order';
        } else {
            message = 'These accounts have multiple chargent orders for the same entity: ' +
                '(' + trimIdList(accountIds) + ')\n';
        }

        return new QCResult(passed, message);
    }

    public QCResult checkChargeAmountEqualsCarryoverBalance() {
        Map<Id, Decimal> chargeAmountByAccountBill = new Map<Id, Decimal>();
        Map<Id, Decimal> carryoverByAccountBill = new Map<Id, Decimal>();
        for (ChargentOrders__ChargentOrder__c order : recurringOrders) {
            // Orders without an Account Bill are reported by checkRecurringOrdersOnLastAccountBill
            if (order.Account_Bill__c == null) {
                continue;
            }
            if (chargeAmountByAccountBill.containsKey(order.Account_Bill__c)) {
                chargeAmountByAccountBill.put(order.Account_Bill__c,
                    chargeAmountByAccountBill.get(order.Account_Bill__c) + order.ChargentOrders__Charge_Amount__c);
            } else {
                chargeAmountByAccountBill.put(order.Account_Bill__c, order.ChargentOrders__Charge_Amount__c);
            }
            carryoverByAccountBill.put(order.Account_Bill__c, order.Account_Bill__r.Carry_Over_Balance__c);
        }
        List<Id> accountBillsWithIncorrectChargentOrders = new List<Id>();
        Boolean passed = true;
        for (Id accountBillId : carryoverByAccountBill.keySet()) {
            if (chargeAmountByAccountBill.get(accountBillId) != carryoverByAccountBill.get(accountBillId)) {
                accountBillsWithIncorrectChargentOrders.add(accountBillId);
                passed = false;
            }
        }
        String message;
        if (accountBillsWithIncorrectChargentOrders.isEmpty()) {
            message = 'All Chargent Order Charge Amounts total the Account Bill Carryover Balances';
        } else {
            message = accountBillsWithIncorrectChargentOrders.size() + ' Account Bills have Chargent Orders that don\'t add up: ' +
                '(' + trimIdList(accountBillsWithIncorrectChargentOrders) + ')\n';
        }
        return new QCResult(passed, message);
    }

    public QCResult checkZeroDollarChargentOrdersNotToFire() {
        Boolean passed = true;
        String message = 'All zero dollar Chargent Orders have been pushed to the future';
        List<Id> orderIds = new List<Id>();

        for (ChargentOrders__ChargentOrder__c order : recurringOrders) {
            Date nextAutopayDate =
                RecurringPaymentsHandler.getNextAutopayDate(Date.today(), Integer.valueOf(order.ChargentOrders__Charge_Date__c));
            if (order.Account_Bill__c != null &&
                order.ChargentOrders__Charge_Amount__c == 0 &&
                order.ChargentOrders__Payment_Start_Date__c <= nextAutopayDate) {
                orderIds.add(order.Id);
                passed = false;
            }
        }
        if (!passed) {
            message = orderIds.size() + ' Chargent Orders will be charged $0 on the Charge Date and get stopped: ' +
                '(' + trimIdList(orderIds) + ')\n';
        }

        return new QCResult(passed, message);
    }

    public QCResult checkChargentOrderEntitiesAndGatewaysAgainstAccountBill() {
        Boolean passed = true;
        String message = 'All Chargent Orders have an Entity and Gateway on their corresponding System Bill';
        List<Id> chargentOrdersWithUnexpectedEntityGateway = new List<Id>();

        Set<Id> accountBillIds = new Set<Id>();
        for (ChargentOrders__ChargentOrder__c order : recurringOrders) {
            accountBillIds.add(order.Account_Bill__c);
        }
        Map<Id, Account_Bill__c> accountBillMap = new Map<Id, Account_Bill__c>([
            SELECT Id,
            (SELECT Id, Shared_Solar_System__r.BWC_Project_Entity_Manual__c,
                Shared_Solar_System__r.BWC_Project_Entity_Manual__r.Gateway__c
            FROM System_Bills__r)
            FROM Account_Bill__c
            WHERE Id = :accountBillIds
        ]);
        for (ChargentOrders__ChargentOrder__c order : recurringOrders) {
            Boolean foundEntityAndGateway = false;
            if (order.Account_Bill__c == null) {
                // Orders without an Account Bill are reported by checkRecurringOrdersOnLastAccountBill
                continue;
            }
            for (System_Bill__c systemBill : accountBillMap.get(order.Account_Bill__c).System_Bills__r) {
                if (systemBill.Shared_Solar_System__r.BWC_Project_Entity_Manual__c == order.Entity__c &&
                    systemBill.Shared_Solar_System__r.BWC_Project_Entity_Manual__r.Gateway__c == order.ChargentOrders__Gateway__c) {
                    foundEntityAndGateway = true;
                    break;
                }
            }
            if (!foundEntityAndGateway) {
                passed = false;
                chargentOrdersWithUnexpectedEntityGateway.add(order.Id);
            }
        }
        if (chargentOrdersWithUnexpectedEntityGateway.size() > 0) {
            message = chargentOrdersWithUnexpectedEntityGateway.size() +
                ' Chargent Orders have an unexpected Entity or Gateway: ' +
                '(' + trimIdList(chargentOrdersWithUnexpectedEntityGateway) + ')\n';
        }

        return new QCResult(passed, message);
    }

    private String trimIdList(List<Id> ids) {
        String idString = String.join(ids, ',');
        if (idString.length() > 500) {
            idString = idString.left(500) + '...';
        }
        return idString;
    }

    public class QCResult {
        public Boolean passed;
        public String message;

        QCResult(Boolean passed, String message) {
            this.passed = passed;
            this.message = message;
        }
    }

    public class GatewayTotal implements Comparable {
        public AutopayChecker apc;
        public Id gatewayId;
        public String gatewayName;
        public Decimal total;

        GatewayTotal(AutopayChecker apc, AggregateResult result) {
            this.apc = apc;
            this.gatewayId = (Id) result.get('ChargentOrders__Gateway__c');
            this.gatewayName = apc.gateways.get(this.gatewayId).Name;
            this.total = (Decimal) result.get('total');
        }

        public Integer compareTo(Object compareTo) {
            GatewayTotal compareToGT = (GatewayTotal) compareTo;
            Integer returnValue = 0;
            if (this.total < compareToGT.total) {
                returnValue = 1;
            } else if (this.total > compareToGT.total) {
                returnValue = -1;
            }
            return returnValue;
        }

        public void addToGatewayTotalList(Map<Id, GatewayTotal> totals) {
            if (totals.get(this.gatewayId) == null) {
                totals.put(this.gatewayId, this);
            } else {
                totals.get(this.gatewayId).total += this.total;
            }
        }
    }
}