src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Partner</label>
        <referenceTo>Partner__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Line__c</fullName>
        <label>Product Line</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Account is Closed if all Opportunities are Cancelled, Duplicate, Expired or Dead</inlineHelpText>
        <label>CS Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Commission_Payment__c.object
<CustomObject>
    <fields>
        <fullName>Due_Date__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Due_to_Accounting__c</fullName>
        <label>Due to Accounting</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Invoice__c</fullName>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Commission Payments</relationshipLabel>
        <relationshipName>Commission_Payments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Due</fullName>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Commission Payment</label>
    <nameField>
        <label>Commission Payment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Commission Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Invoice__c.object
<CustomObject>
    <description>Zuora Invoice object. Invoices are bills that you send to customers.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Related Client Account for Client Invoices, or a partner account</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Received &gt;&gt; QC</fullName>
                </value>
                <value>
                    <fullName>QC Complete &gt;&gt; Submit to Accounting</fullName>
                </value>
                <value>
                    <fullName>Submitted to Accounting</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <recordTypes>
        <fullName>Partner_Invoice</fullName>
        <active>true</active>
        <label>Partner Invoice</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Due_to_Accounting__c.field-meta.xml
<CustomField>
    <fullName>Due_to_Accounting__c</fullName>
    <label>Due to Accounting</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Invoice_Type__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Type__c</fullName>
    <label>Invoice Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Direct</fullName>
            </value>
            <value>
                <fullName>Submitted by Partner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner</label>
    <referenceTo>Partner__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <label>Product Line</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Community Solar</fullName>
            </value>
            <value>
                <fullName>Residential Loan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Product_Line__c</fullName>
        <label>Product Line</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Partner__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Link to partner or client account</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Partners</relationshipLabel>
        <relationshipName>Partners</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Partner</label>
    <nameField>
        <label>Partner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partners</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Subscription_Order__c.object
<CustomObject>
    <label>Subscription Order</label>
    <nameField>
        <displayFormat>SO-{00000}</displayFormat>
        <label>Subscription Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscription Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/PartnerCommissionGenerator.cls
/**
 * @description Created by jeffparlin on 2/24/22. Queueable class to run to generate Partner Commission records. Accepts
 * a List<Id> of Partner Account Ids and processes ONE Partner per queueable execution.
 */
public without sharing class PartnerCommissionGenerator implements Queueable, Finalizer {

    @TestVisible private static OpportunitiesSelector oppSelector = new OpportunitiesSelector();
    @TestVisible private static AccountsSelector accountsSelector = new AccountsSelector();
    @TestVisible private static PartnerInvoiceSelector partnerInvoiceSelector = new PartnerInvoiceSelector();

    private Id currentPartner;
    private Account currentPartnerAccount;
    private List<Id> partnersToProcess;
    private Map<Id,Opportunity> variableRateOpportunities;
    private fflib_SObjectUnitOfWork unitOfWork;
    private Invoice__c partnerInvoice;

    public PartnerCommissionGenerator(List<Id> partnerAccountIds) {
        this.partnersToProcess = partnerAccountIds;
        this.currentPartner = partnerAccountIds.get(partnerAccountIds.size()-1);
    }

    public void execute(QueueableContext ctx) {
        executeSynchronous();
    }

    public void execute(FinalizerContext ctx) {
        // Chain next job if any partner Ids remain to have yet be processed
        partnersToProcess.remove(partnersToProcess.size()-1);
        if (!partnersToProcess.isEmpty()) {
            System.enqueueJob(new PartnerCommissionGenerator(partnersToProcess));
        }
    }

    public void executeSynchronous() {
        unitOfWork = new fflib_SObjectUnitOfWork(new List<SObjectType> {
            Commission_Payment__c.SObjectType,
            Subscription_Order__c.SObjectType
        });
        try {
            locatePartnerInvoice();
            generateCommissionPayments();
        } catch (Exception e) {
            String message = e.getMessage() + '\n\n' + e.getStackTraceString();
            Logger.postLog('PartnerCommissionGenerator', 'execute (Queueable)', message, System.now(), Logger.ERROR);
        }
    }

    private void locatePartnerInvoice() {
        currentPartnerAccount = accountsSelector.getPartnerAccountDetails(currentPartner);
        Id legacyPartnerId = currentPartnerAccount.Partner__c;
        List<Invoice__c> existingInvoices = partnerInvoiceSelector.getPendingPartnerInvoices(
            new Set<Id>{legacyPartnerId}, getDueDate()
        );
        partnerInvoice = existingInvoices.get(0) != null ? existingInvoices[0] : createPartnerInvoice();
    }

    private Invoice__c createPartnerInvoice() {
        Date dueDate = getDueDate();
        Id recordTypeId = SObjectType.Invoice__c.getRecordTypeInfosByDeveloperName().get('Partner_Invoice').getRecordTypeId();
        Date dueToAccountingDate = Date.newInstance(dueDate.year(), dueDate.month(), 3);
        Datetime dueDatetime = Datetime.newInstance(dueDate.year(), dueDate.month(), dueDate.day());

        Invoice__c invoice = new Invoice__c(
            Name = currentPartnerAccount.Name + ' ' + dueDatetime.format('MMMM dd, yyyy'),
            Due_Date__c = dueDate,
            Due_to_Accounting__c = dueToAccountingDate,
            Invoice_Type__c = 'Direct',
            Partner__c = currentPartnerAccount.Partner__c,
            Product_Line__c = 'Community Solar',
            Status__c = 'Received >> QC',
            RecordTypeId = recordTypeId,
            Account__c = currentPartnerAccount.Id
        );
        insert invoice;
        return invoice;
    }

    private Date getDueDate() {
        Date monthFromToday = System.today().addMonths(1);
        return Date.newInstance(monthFromToday.year(), monthFromToday.month(), 15);
    }

    private void generateCommissionPayments() {
        variableRateOpportunities = oppSelector.getVariableRateCommissionOppsForPartner(currentPartner);
        if (!variableRateOpportunities.isEmpty()) {
            new VariableRateCommissionProcessor(variableRateOpportunities, unitOfWork, partnerInvoice).generateCommissionPayments();
        }
        unitOfWork.commitWork();
    }
}