src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Cancellation_Comments__c</fullName>
        <label>Cancellation Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Cancellation_Reason__c</fullName>
        <inlineHelpText>Reason the customer cancelled their CS Subscription</inlineHelpText>
        <label>Cancellation Reason - Internal</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Lack of Payment</fullName>
                    <label>Lack of Payment - Default</label>
                </value>
                <value>
                    <fullName>Lack of Payment - Unhappy with BW Service</fullName>
                </value>
                <value>
                    <fullName>Lack of Payment - Does Not Understand Product</fullName>
                </value>
                <value>
                    <fullName>Lack of Payment - Product Does Not Meet Needs</fullName>
                </value>
                <value>
                    <fullName>Lack of Payment - Financial Hardship</fullName>
                </value>
                <value>
                    <fullName>Lack of Payment - Unable to Establish Communication</fullName>
                </value>
                <value>
                    <fullName>Lack of Payment - Other</fullName>
                </value>
                <value>
                    <fullName>Customer Moved</fullName>
                </value>
                <value>
                    <fullName>Business Sold/Out of Business</fullName>
                </value>
                <value>
                    <fullName>Does Not Understand Product</fullName>
                </value>
                <value>
                    <fullName>Product Does Not Meet Needs</fullName>
                </value>
                <value>
                    <fullName>Unhappy with BW Service</fullName>
                </value>
                <value>
                    <fullName>Unable to Establish Communication</fullName>
                </value>
                <value>
                    <fullName>Financial Hardship</fullName>
                </value>
                <value>
                    <fullName>Death</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Cancellation_Request_Date__c</fullName>
        <inlineHelpText>Must fill out &quot;Cancellation Reason&quot; before saving</inlineHelpText>
        <label>Cancellation Request Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Client_Brand_Key__c</fullName>
        <inlineHelpText>Set before an opportunity is inserted, or if the Account, SSS, or Stage is updated on the opportunity. Also set if the Client Brand Key on a SSS is updated.</inlineHelpText>
        <label>Client Brand Key</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Client_Logo_Filenames</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Days_Past_Due__c</fullName>
        <formula>IF(Total_Outstanding_Balance_Merge__c &gt; 1,
MAX(TODAY()-Max_Overdue_Due_Date_Merge__c,0),
0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Days Past Due</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Send_Bills_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Send Bills Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Property</fullName>
        <active>true</active>
        <label>Property</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Account/fields/Cancelled_By__c.field-meta.xml
<CustomField>
    <fullName>Cancelled_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>User who enters in cancellation reason and request date</inlineHelpText>
    <label>Cancelled By</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.UserType</field>
            <operation>equals</operation>
            <value>Standard</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Co-Applicants</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to relate multiple Client Contracts to a single opportunity</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This is used for customer contracts to show the product and contract that was used.</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Cancellation_Request_Date__c</fullName>
        <formula>Account.Cancellation_Request_Date__c</formula>
        <inlineHelpText>This is the Cancellation Request Date for the Account.</inlineHelpText>
        <label>Cancellation Request Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Cancellation_Paragraph_Three__c</fullName>
        <inlineHelpText>CSCancellationService pulls into the cancellation confirmation email when the customer cancels. Intended to have termination language, and can be left blank. If not blank, the email template assumes the text starts and ends with &lt;br&gt; and &lt;/br&gt;.</inlineHelpText>
        <label>Cancellation Paragraph Three</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Cancellation_Paragraph_Two__c</fullName>
        <inlineHelpText>CSCancellationService pulls into the cancellation confirmation email when the customer cancels. Intended to contain timing information. Follows paragraph one, which confirms the written cancellation request. This text should be surrounded by &lt;br&gt;.</inlineHelpText>
        <label>Cancellation Paragraph Two</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <recordTypes>
        <fullName>Default</fullName>
        <active>true</active>
        <label>Default</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Subscription_Order__c.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Subscription Orders</relationshipLabel>
        <relationshipName>Subscription_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Utility_Account_Subscription__c</fullName>
        <label>Utility Account Subscription</label>
        <referenceTo>Utility_Account_Subscription__c</referenceTo>
        <relationshipLabel>Subscription Orders</relationshipLabel>
        <relationshipName>Subscription_Orders</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Subscription Order</label>
    <nameField>
        <displayFormat>SO-{00000}</displayFormat>
        <label>Subscription Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscription Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/User/fields/Client_Brand_Key__c.field-meta.xml
<CustomField>
    <fullName>Client_Brand_Key__c</fullName>
    <formula>TEXT(Contact.Account.Client_Brand_Key__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Client Brand Key</label>
    <type>Text</type>
</CustomField>

src/objects/Utility_Account_Log__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Utility Account Logs</relationshipLabel>
        <relationshipName>Utility_Account_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Utility Account Logs</relationshipLabel>
        <relationshipName>Utility_Account_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Utility Account Log</label>
    <nameField>
        <label>Utility Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Account Logs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Utility_Account_Subscription__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Utility Account Subscriptions</relationshipLabel>
        <relationshipName>Utility_Account_Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Utility_Account_Log__c</fullName>
        <inlineHelpText>The related UAL</inlineHelpText>
        <label>Utility Account Log</label>
        <referenceTo>Utility_Account_Log__c</referenceTo>
        <relationshipLabel>Utility Account Subscriptions</relationshipLabel>
        <relationshipName>Utility_Account_Subscriptions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Utility Account Subscription</label>
    <nameField>
        <label>Utility Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Account Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/Client_Logo_Filenames.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>AmpBlack</fullName>
    </customValue>
    <customValue>
        <fullName>BluewaveLogo</fullName>
    </customValue>
    <customValue>
        <fullName>AmpRed</fullName>
    </customValue>
    <customValue>
        <fullName>DSD</fullName>
    </customValue>
    <masterLabel>Client Logo Filenames</masterLabel>
</GlobalValueSet>

src/classes/CSCancellationAccountService.cls
/**
 * @description Handles account-related cancellation activity. See the Cancellation Process lucid chart for more detail:
 * https://lucid.app/lucidchart/28ddde15-529b-4b09-b858-35bba5e77e37/edit?shared=true&invitationId=inv_805406f1-b7d7-46cc-af1a-45901bb1d4e2&page=0_0#
 * Tested By: CSCancellationServiceTest
 */

@SuppressWarnings('PMD.ApexCRUDViolation')
public without sharing class CSCancellationAccountService {
    @TestVisible private List<Account> overdueAccounts = new List<Account>();
    @TestVisible private static final Id CANCELLED_BY_ID = [SELECT Id FROM User WHERE LastName = 'API' LIMIT 1].Id;
    public static final String AUTOMATED_CANCELLATION_COMMENT = 'Automated Cancellation';
    @TestVisible private static final String CANCELLATION_PARAGRAPH_TWO_LABEL = '{!Cancellation_Paragraph_Two__c}';
    @TestVisible private static final String DEFAULT_CANCELLATION_PARAGRAPH_TWO = '<br>Per our records, you have multiple subscriptions ' +
        'and the terms of service may vary for each. Your utility may process the cancellations at different times over ' +
        'many months. During this time, you are responsible for all solar credits transferred to your account. We will ' +
        'email you when the utility removes all your subscriptions and you stop receiving credits.</br>';
    @TestVisible private static final String CANCELLATION_PARAGRAPH_THREE_LABEL = '{!Cancellation_Paragraph_Three__c}';
    @TestVisible private static final String DEFAULT_CANCELLATION_PARAGRAPH_THREE = '<br><i>Please refer to your contract(s) for more ' +
        'details about the terms of service for each of your subscriptions including any applicable early termination fees.</i></br>';

    public String handleOverdueAccounts(Boolean preview) {
        String outputMessage = CSCancellationScheduler.ACCOUNT_OVERDUE_DESCRIPTION;
        overdueAccounts = AccountsSelector.selectCS67DaysPastDueWithAnchorOpps();
        if (!preview) {
            outputMessage = outputMessage.replace('will get', 'got');
            handleOverdueAccounts(overdueAccounts);
        }
        for (Account account : overdueAccounts) {
            outputMessage += account.Id + ', ' + account.Name + ' ' + account.Days_Past_Due__c + '\n';
        }
        return outputMessage;
    }

    // W-008422: Finds accounts that are overdue, and sets the Account's cancellation reason, comments, and request date,
    // which in turn triggers the cancellation process. We skip Anchor or Public Offtake accounts as well as those that
    // have an override checkbox checked.
    @TestVisible private static void handleOverdueAccounts(List<Account> accountList) {
        List<Account> updatedAccounts = new List<Account>();

        for (Account acct : accountList) {
            if (acct.Opportunities.isEmpty()){
                acct.Cancellation_Reason__c = 'Lack of Payment';
                acct.Cancellation_Request_Date__c = System.today();
                acct.Cancelled_By__c = CANCELLED_BY_ID;
                acct.Cancellation_Comments__c = AUTOMATED_CANCELLATION_COMMENT;
                updatedAccounts.add(acct);
            }
        }

        update updatedAccounts;
    }

    // W-008413: Called by the AccountTrigger after Property Accounts are updated with a Cancellation Request Date, to
    // remove all UASes from the next schedule Z, and send the customer(s) an email confirming their cancellation request.
    public void processSubscriptionCancellations(List<Utility_Account_Subscription__c> uasesToMarkInactive) {
        UtilityAccountSubscriptions subscriptions = new UtilityAccountSubscriptions(uasesToMarkInactive);
        subscriptions.removeFromNextScheduleZ();
        fflib_SObjectUnitOfWork uow = new fflib_SObjectUnitOfWork(
            new List<SObjectType>{
                Subscription_Order__c.SObjectType
            }
        );
        subscriptions.registerSubscriptionOrdersToZeroOutUAS('Cancellation', uow);
        uow.commitWork();
        sendCancellationConfirmationEmails(uasesToMarkInactive);
    }

    private static void sendCancellationConfirmationEmails(List<Utility_Account_Subscription__c> uasesCancelled) {
        List<Messaging.SingleEmailMessage> cancellationEmails = new List<Messaging.SingleEmailMessage>();
        Map<Account, Map<String, String>> accountToCancellationParagraphs = accountToCancellationParagraphs(uasesCancelled);

        for (Account account : accountToCancellationParagraphs.keySet()) {
            try {
                cancellationEmails.add(
                    CSCancellationService.createCSCancellationEmail(
                        account,
                        'CS_Cancellation_Request_Confirmation',
                        'Cancellation Request Acknowledgement',
                        accountToCancellationParagraphs.get(account)
                    )
                );
            } catch (Util.BWException bwe) {
                Logger.logLater('CSCancellationService', 'sendCancellationConfirmationEmails', bwe.getMessage());
            }
        }
        CSCancellationService.sendCancellationEmails(cancellationEmails);
        Logger.flushLogs();
    }

    @TestVisible
    private static Map<Account, Map<String, String>> accountToCancellationParagraphs(List<Utility_Account_Subscription__c> uasesCancelled) {
        Map<Account, Map<String, String>> accountIdToReplacementMap = new Map<Account, Map<String, String>>();
        for (Utility_Account_Subscription__c uas : uasesCancelled) {
            // We don't send cancellation confirmation for automatically cancelled accounts, so we skip them
            if (uas.Utility_Account_Log__r.Account__r.Cancellation_Comments__c == CSCancellationAccountService.AUTOMATED_CANCELLATION_COMMENT) {
                continue;
            }
            if (uas.Opportunity__r.Product__r.Cancellation_Paragraph_Two__c == null) {
                String text = 'While trying to cancel this account, we found product: ' + uas.Opportunity__r.Product__c +
                    ' to have a missing Cancellation Paragraph Two. Please ask an administrator to update it.';
                throw new Util.BWException(text);
            }

            Account account = uas.Utility_Account_Log__r.Account__r;
            addAccountToReplacementMap(accountIdToReplacementMap, account);
            resolveConflictingCancellationMessages(accountIdToReplacementMap, account, uas);
        }

        return accountIdToReplacementMap;
    }


    private static void addAccountToReplacementMap(Map<Account, Map<String, String>> accountIdToReplacementMap, Account account) {
        if (accountIdToReplacementMap.containsKey(account)) {
            return;
        }
        Map<String, String> replacements = new Map<String, String>{
            CANCELLATION_PARAGRAPH_TWO_LABEL => '',
            CANCELLATION_PARAGRAPH_THREE_LABEL => '',
            '{!Contact.FirstName}' => account.Send_Bills_Contact__r.FirstName
        };
        if (account.Client_Brand_Key__c.contains('Amp')) {
            replacements.put('{!$Label.Company_Name} Community Solar', 'Amp-{!$Label.Company_Name}');
        }
        accountIdToReplacementMap.put(account,replacements);
    }

    // If two opportunities have products with conflicting cancellation information, we should show a default cancellation message
    private static void resolveConflictingCancellationMessages(Map<Account, Map<String, String>> accountIdToReplacementMap, Account account, Utility_Account_Subscription__c uas) {
        Map<String, String> replacementMap = accountIdToReplacementMap.get(account);
        if (replacementMap.get(CANCELLATION_PARAGRAPH_TWO_LABEL) == '') {
            replacementMap.put(CANCELLATION_PARAGRAPH_TWO_LABEL, uas.Opportunity__r.Product__r.Cancellation_Paragraph_Two__c);
        } else if (replacementMap.get(CANCELLATION_PARAGRAPH_TWO_LABEL) != uas.Opportunity__r.Product__r.Cancellation_Paragraph_Two__c) {
            replacementMap.put(CANCELLATION_PARAGRAPH_TWO_LABEL, DEFAULT_CANCELLATION_PARAGRAPH_TWO);
        }
        if (replacementMap.get(CANCELLATION_PARAGRAPH_THREE_LABEL) == '') {
            replacementMap.put(CANCELLATION_PARAGRAPH_THREE_LABEL, uas.Opportunity__r.Product__r.Cancellation_Paragraph_Three__c);
        } else if (replacementMap.get(CANCELLATION_PARAGRAPH_THREE_LABEL) != uas.Opportunity__r.Product__r.Cancellation_Paragraph_Three__c) {
            replacementMap.put(CANCELLATION_PARAGRAPH_THREE_LABEL, DEFAULT_CANCELLATION_PARAGRAPH_THREE);
        }
    }
}