src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Partner</label>
        <referenceTo>Partner__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Commission_Structure__c.object
<CustomObject>
    <fields>
        <fullName>Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Partner</label>
        <referenceTo>Partner__c</referenceTo>
        <relationshipLabel>Commission Structures</relationshipLabel>
        <relationshipName>Commission_Structures</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Commission Structure</label>
    <nameField>
        <label>Commission Structure Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Commission Structures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Partner__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Link to partner or client account</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Partners</relationshipLabel>
        <relationshipName>Partners</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Commission_Structure__c</fullName>
        <label>Commission Structure</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <label>Partner</label>
    <nameField>
        <label>Partner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partners</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Partner_Shared_Solar_System_Eligibility__c.object
<CustomObject>
    <description>Control partner access to Shared Solar Systems</description>
    <fields>
        <fullName>Account__c</fullName>
        <inlineHelpText>Partner Account</inlineHelpText>
        <label>Partner Account</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The Account must have a record type of Partner Account</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Partner Account</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Shared Solar Systems</relationshipLabel>
        <relationshipName>Partner_Shared_Solar_System_Accesses</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Commission_Structure__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Commission Structure that applies when a partner acquires customers for this Shared Solar System</inlineHelpText>
        <label>Commission Structure</label>
        <referenceTo>Commission_Structure__c</referenceTo>
        <relationshipLabel>Partner Shared Solar System</relationshipLabel>
        <relationshipName>Partner_Shared_Solar_System_Accesses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <inlineHelpText>Date after which this record ceases to be active</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IsActive__c</fullName>
        <formula>AND( TODAY() &gt;= Start_Date__c,
     OR(ISBLANK(End_Date__c), TODAY() &lt;= End_Date__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Checked, if today is between the start and end date (or end date is blank). Once active, this record is locked.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Shared_Solar_System__c</fullName>
        <inlineHelpText>Shared Solar System that the partner is eligible to sell</inlineHelpText>
        <label>Shared Solar System</label>
        <referenceTo>Shared_Solar_System__c</referenceTo>
        <relationshipLabel>Eligible Partners</relationshipLabel>
        <relationshipName>Partner_Shared_Solar_System_Accesses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <inlineHelpText>Date on which this record begins to be active</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Partner Shared Solar System Access</label>
    <nameField>
        <displayFormat>PSSA-{0000}</displayFormat>
        <label>Partner Shared Solar System Access Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Shared Solar System Accesses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Shared_Solar_System__c.object
<CustomObject
     >
    <articleTypeChannelDisplay n1:nil="true" />
    <customSettingsType n1:nil="true" />
    <description n1:nil="true" />
    <eventType n1:nil="true" />
    <gender n1:nil="true" />
    <household>false</household>
    <label>Shared Solar System</label>
    <nameField>
        <label>Shared Solar System Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shared Solar Systems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <startsWith n1:nil="true" />
</CustomObject>

src/classes/PartnerSSSEligibilitySelector.cls
/**
 * Created by PeterYao on 11/14/2020.
 * Tested By: PartnerSSSEligibilitySelectorTest
 */
@SuppressWarnings('PMD.ApexCRUDViolation')
public inherited sharing class PartnerSSSEligibilitySelector {
    public MultiMap getPartnersBySSS() {
        List<Partner_Shared_Solar_System_Eligibility__c> allPartnerEligibilities = [
            SELECT Id, Account__c, Account__r.Partner__c, Shared_Solar_System__c
            FROM Partner_Shared_Solar_System_Eligibility__c
            WHERE IsActive__c = TRUE
        ];
        MultiMap sssIdToEligiblePartners = MultiMap.newSetInstance();
        for (Partner_Shared_Solar_System_Eligibility__c eligibility : allPartnerEligibilities) {
            sssIdToEligiblePartners.putValue(eligibility.Shared_Solar_System__c, eligibility.Account__c);
            sssIdToEligiblePartners.putValue(eligibility.Shared_Solar_System__c, eligibility.Account__r.Partner__c);
        }
        return sssIdToEligiblePartners;
    }

    //
    //
    /**
     * @description This should not select just active eligibilities, because it is used to find overlapping
     * eligibilities (so we want to find eligibilities that may be active in the future)
     * @param partnerIds An Account Id for a Partner, for which to find eligibility records
     * @return List of Partner_Shared_Solar_System_Eligibility__c
     */
    public List<Partner_Shared_Solar_System_Eligibility__c> getSSSByPartner(Set<Id> partnerIds) {
        return [
            SELECT Id, Commission_Structure__c, Account__c, Shared_Solar_System__c, Start_Date__c, End_Date__c
            FROM Partner_Shared_Solar_System_Eligibility__c
            WHERE Account__c IN :partnerIds
        ];
    }

    /**
     * @description Used to get eligibility records on a start date or end date, in order to update sharing. Intended
     * to be run daily, with a start date of today and an end date of yesterday, in order to get the shares that should change
     * @param startDate The start date for eligibility records
     * @param endDate The end date for eligibility records
     * @return List of eligibility records that start or end on the input dates
     */
    public List<Partner_Shared_Solar_System_Eligibility__c> getRecentPartnerSSSEligibilities(Date startDate, Date endDate) {
        return [
            SELECT Id, Account__c, Shared_Solar_System__c, Start_Date__c, End_Date__c, IsActive__c
            FROM Partner_Shared_Solar_System_Eligibility__c
            WHERE Start_Date__c = :startDate
            OR End_Date__c = :endDate
        ];
    }
}