src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Parent_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Lookup to Parent Account</inlineHelpText>
        <label>Parent Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Properties</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Account_Bill__c.object
<CustomObject>
    <fields>
        <fullName>Bill_Attach_Document__c</fullName>
        <inlineHelpText>Used in CS customer portal for link to file</inlineHelpText>
        <label>Bill Attach Document</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bill_Number__c</fullName>
        <label>Bill Number</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Bill Statment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Parent_Account__c</fullName>
        <label>Property Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Bills</relationshipLabel>
        <relationshipName>Account_Bills</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Published__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Published</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Ready_For_Paper_Bill_Queue__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Ready For Paper Bill Queue</label>
        <type>Checkbox</type>
    </fields>
    <label>Account Bill</label>
    <nameField>
        <label>Account Bill Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Bills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ContentVersion.object
<CustomObject>
</CustomObject>

force-app/main/default/objects/ContentVersion/fields/Ready_for_Paper_Bill_Queue__c.field-meta.xml
<CustomField>
    <fullName>Ready_for_Paper_Bill_Queue__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Set to true to have the ContentMailerScheduler mail this pdf via LetterStream</inlineHelpText>
    <label>Ready for Paper Bill Queue</label>
    <type>Checkbox</type>
</CustomField>

src/classes/AccountBillSelectorTest.cls
/**
 * Created by mstackhouse on 1/16/2019.
 * Description: 
 * Test: 
 */

@IsTest
public with sharing class AccountBillSelectorTest {
    @IsTest
    public static void testCanGetAllReadyAccountBillsWithoutIDs() {
        Account accountParent1 = getParentAccount();
        ContentDocument doc = getContentDocument();

        Date billDate = Date.newInstance(2019, 2, 12);

        Account_Bill__c readyAccountBill = new Account_Bill__c(
            Parent_Account__c = accountParent1.Id,
            Bill_Number__c = 2,
            Published__c = true,
            Date__c = billDate,
            Ready_For_Paper_Bill_Queue__c = true,
            Bill_Attach_Document__c = doc.Id
        );

        Account_Bill__c unPublishedAccountBill = new Account_Bill__c(
            Parent_Account__c = accountParent1.Id,
            Bill_Number__c = 2,
            Published__c = false,
            Date__c = billDate,
            Ready_For_Paper_Bill_Queue__c = false,
            Bill_Attach_Document__c = doc.Id
        );

        Account_Bill__c publishedNotReadyAccountBill = new Account_Bill__c(
            Parent_Account__c = accountParent1.Id,
            Bill_Number__c = 2,
            Published__c = true,
            Date__c = billDate,
            Ready_For_Paper_Bill_Queue__c = false,
            Bill_Attach_Document__c = doc.Id
        );

        Account_Bill__c noDocAccountBill = new Account_Bill__c(
            Parent_Account__c = accountParent1.Id,
            Bill_Number__c = 2,
            Published__c = true,
            Date__c = billDate,
            Ready_For_Paper_Bill_Queue__c = false
        );

        insert new List<Account_Bill__c>{readyAccountBill, unPublishedAccountBill, publishedNotReadyAccountBill, noDocAccountBill};

        List<Account_Bill__c> queriedBills = AccountBillSelector.getAccountBillsReadyToBeSent(null);
        System.assertEquals(1, queriedBills.size());

        List<AggregateResult> abSummary = AccountBillSelector.getAccountBillSummary(2, '2019');
        System.assertEquals(3, abSummary.size());
    }

    @IsTest
    public static void testCanGetAllReadyAccountBillsByIDs() {
        Account accountParent1 = getParentAccount();
        ContentDocument doc = getContentDocument();

        Account_Bill__c readyAccountBill = new Account_Bill__c(
            Parent_Account__c = accountParent1.Id,
            Bill_Number__c = 2,
            Published__c = true,
            Ready_For_Paper_Bill_Queue__c = true,
            Bill_Attach_Document__c = doc.Id
        );

        Account_Bill__c unPublishedAccountBill = new Account_Bill__c(
            Parent_Account__c = accountParent1.Id,
            Bill_Number__c = 2,
            Published__c = false,
            Ready_For_Paper_Bill_Queue__c = false,
            Bill_Attach_Document__c = doc.Id
        );

        Account_Bill__c publishedNotReadyAccountBill = new Account_Bill__c(
            Parent_Account__c = accountParent1.Id,
            Bill_Number__c = 2,
            Published__c = true,
            Ready_For_Paper_Bill_Queue__c = false,
            Bill_Attach_Document__c = doc.Id
        );

        insert new List<Account_Bill__c>{readyAccountBill, unPublishedAccountBill, publishedNotReadyAccountBill};
        Set<Id> accountBillIds = new Set<Id>{
            readyAccountBill.Id,
            unPublishedAccountBill.Id,
            publishedNotReadyAccountBill.Id
        };

        List<Account_Bill__c> queriedBills = AccountBillSelector.getAccountBillsReadyToBeSent(accountBillIds);
        System.assertEquals(1, queriedBills.size());
    }

    public static Account getParentAccount() {
        Id parentAccountRT =
            Schema.SObjectType.Account.getRecordTypeInfosByName().get('Parent Account').getRecordTypeId();

        Account accountParent1 = new Account(
            name = 'Account Parent',
            RecordTypeId = parentAccountRT,
            BillingStreet = '123 Fake St',
            BillingCity = 'City',
            BillingState = 'Colorado',
            BillingPostalCode = '80525'
        );
        insert accountParent1;
        return accountParent1;
    }

    public static ContentDocument getContentDocument() {
        ContentVersion documentVersion3 = new ContentVersion(
            Title = 'test document',
            PathOnClient = 'test_Doc.pdf',
            VersionData = Blob.valueOf('testDoc')
        );
        Util.insertSObjs(new List<ContentVersion>{documentVersion3});

        ContentDocument contentDocument = [
            SELECT Id, LatestPublishedVersionId
            FROM ContentDocument
            WHERE LatestPublishedVersionId = : documentVersion3.Id
            LIMIT 1
        ];

        return contentDocument;
    }
}