src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Payment_Gateway__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used by AccountReconciliationService.reconcileZuoraWithSFDC</description>
        <inlineHelpText>Default payment gateway used for customers subscribed to this client&apos;s systems.</inlineHelpText>
        <label>Payment Gateway</label>
        <referenceTo>Zuora__PaymentGateway__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Zuora__CustomerAccount__c.object
<CustomObject>
    <description>Zuora Billing Account object.  An account is a customer account that collects all of the critical information about the customer, such as contact information, payment terms, and payment methods. You can use a customer account to track subscriptions, amendments, and transactions, such as invoices and payments.</description>
    <fields>
        <fullName>Zuora__Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>R00N40000001kyLcEAI</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Zuora__PaymentGateway__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Payment Gateway</label>
        <referenceTo>Zuora__PaymentGateway__c</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>Billing_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Zuora__Payment__c.object
<CustomObject>
    <description>Zuora Payment object.  A payment is the money that customers send to pay for charges related to their subscriptions.
The Payment object holds all of the information about an individual payment, including the payment amount and to which invoices the payment is applied.</description>
    <fields>
        <fullName>Lockbox_Formula__c</fullName>
        <formula>IF(ISPICKVAL(Zuora__Type__c, &quot;External&quot;), 
   Lockbox__c,
   &quot;&quot;)</formula>
        <inlineHelpText>Lockbox used for external payments (checks)</inlineHelpText>
        <label>Lockbox</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lockbox__c</fullName>
        <inlineHelpText>Lockbox, as set in Zuora. It&apos;s defaulted and set for all payments, but only meaningful for external payments (checks)</inlineHelpText>
        <label>Zuora Lockbox</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Gateway__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The default payment gateway on the Billing Account when the Payment is downloaded (which is the payment gateway that is used to make the payment).</inlineHelpText>
        <label>Payment Gateway</label>
        <referenceTo>Zuora__PaymentGateway__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The CRM Account that this payment is related to.</description>
        <inlineHelpText>The CRM Account that this payment is related to.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora__BillingAccount__c</fullName>
        <description>The billing account that the payment is for.</description>
        <inlineHelpText>The billing account that the payment is for.</inlineHelpText>
        <label>Billing Account</label>
        <referenceTo>Zuora__CustomerAccount__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Zuora__EXT_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>External Id For Payment object,   Represents a Zuora Payment object Id</description>
        <externalId>true</externalId>
        <label>Unique External Id</label>
        <length>32</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Zuora__Type__c</fullName>
        <description>Indicates if the payment is external or electronic.</description>
        <inlineHelpText>Indicates if the payment is external or electronic.</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Electronic</fullName>
                </value>
                <value>
                    <fullName>External</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Payment</label>
    <nameField>
        <label>Payment Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Zuora__PaymentGateway__c.object
<CustomObject>
    <fields>
        <fullName>Zuora__IsDefault__c</fullName>
        <label>IsDefault</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Payment Gateway</label>
    <nameField>
        <label>PaymentGateway Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Gateways</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ZuoraGatewayAssignerTest.cls
/**
 * Created by PeterYao on 7/8/2021.
 */
@IsTest
public with sharing class ZuoraGatewayAssignerTest {
    @IsTest
    private static void systemTest() {
        Zuora__PaymentGateway__c ampGateway = new Zuora__PaymentGateway__c(
            Name = 'Amp Gateway',
            Zuora__IsDefault__c = 'false'
        );
        Zuora__PaymentGateway__c bcsGateway = new Zuora__PaymentGateway__c(
            Name = 'BCS Single Gateway',
            Zuora__IsDefault__c = 'true'
        );
        insert new List<Zuora__PaymentGateway__c>{ampGateway, bcsGateway};

        Account account1 = new Account(
            Name = 'Test'
        );
        Account account2 = new Account(
            Name = 'Test2'
        );
        insert new List<Account>{account1, account2};

        Zuora__CustomerAccount__c billingAccount1 = new Zuora__CustomerAccount__c(
            Name = 'Test',
            Zuora__Account__c = account1.Id
        );
        Zuora__CustomerAccount__c billingAccount2 = new Zuora__CustomerAccount__c(
            Name = 'Test2',
            Zuora__PaymentGateway__c = ampGateway.Id,
            Zuora__Account__c = account2.Id
        );
        insert new List<Zuora__CustomerAccount__c>{billingAccount1, billingAccount2};

        Zuora__Payment__c bcsPayment1 = new Zuora__Payment__c(
            Zuora__BillingAccount__c = billingAccount1.Id,
            Zuora__EXT_ID__c = '1234',
            Zuora__Type__c = 'Electronic',
            Lockbox__c = 'BWTrust'
        );
        Zuora__Payment__c bcsPayment2 = new Zuora__Payment__c(
            Zuora__BillingAccount__c = billingAccount1.Id,
            Zuora__EXT_ID__c = '5678',
            Zuora__Type__c = 'Electronic',
            Lockbox__c = 'BWTrust'
        );
        Zuora__Payment__c ampPayment3 = new Zuora__Payment__c(
            Zuora__BillingAccount__c = billingAccount2.Id,
            Zuora__EXT_ID__c = '2345',
            Zuora__Type__c = 'Electronic',
            Lockbox__c = 'BWTrust'
        );
        Zuora__Payment__c ampPayment4 = new Zuora__Payment__c(
            Zuora__BillingAccount__c = billingAccount2.Id,
            Zuora__EXT_ID__c = '6789',
            Zuora__Type__c = 'Electronic',
            Lockbox__c = 'BWTrust'
        );
        Zuora__Payment__c ampPayment5 = new Zuora__Payment__c(
            Zuora__BillingAccount__c = billingAccount2.Id,
            Zuora__EXT_ID__c = '7890',
            Zuora__Type__c = 'External',
            Lockbox__c = 'AmpTrust'
        );
        insert new List<Zuora__Payment__c>{bcsPayment1, bcsPayment2, ampPayment3, ampPayment4, ampPayment5};

        List<Zuora__CustomerAccount__c> customerAccounts = [
            SELECT Id, Name, Zuora__PaymentGateway__c
            FROM Zuora__CustomerAccount__c
            ORDER BY Name
        ];

        Map<Id, Zuora__Payment__c> payments = new Map<Id, Zuora__Payment__c>([
            SELECT Id, Payment_Gateway__c, Lockbox_Formula__c
            FROM Zuora__Payment__c
        ]);
        System.assertEquals(bcsGateway.Id, payments.get(bcsPayment1.Id).Payment_Gateway__c,
            'ZuoraGatewayAssigner should have assigned the default gateway to a billing account without a gateway');
        System.assertEquals(null, payments.get(bcsPayment1.Id).Lockbox_Formula__c,
            'Lockbox should be null for an Electronic payment');
        System.assertEquals(bcsGateway.Id, payments.get(bcsPayment2.Id).Payment_Gateway__c,
            'ZuoraGatewayAssigner should have assigned the default gateway to a billing account without a gateway');
        System.assertEquals(ampGateway.Id, payments.get(ampPayment3.Id).Payment_Gateway__c,
            'ZuoraGatewayAssigner should have assigned the gateway that is on the billing account');
        System.assertEquals(ampGateway.Id, payments.get(ampPayment4.Id).Payment_Gateway__c,
            'ZuoraGatewayAssigner should have assigned the gateway that is on the billing account');
        System.assertEquals(null, payments.get(ampPayment5.Id).Payment_Gateway__c,
            'Payment Gateway should be null for an external payment');
        System.assertEquals(ampPayment5.Lockbox__c, payments.get(ampPayment5.Id).Lockbox_Formula__c,
            'Lockbox should be populated for an External payment');
        System.assertEquals('Test', customerAccounts[0].Name, 'First customer account should be Test');
        System.assertEquals(bcsGateway.Id, customerAccounts[0].Zuora__PaymentGateway__c,
            'First customer account was inserted without a Payment Gateway, and should have been assigned the default');
        System.assertEquals(ampGateway.Id, customerAccounts[1].Zuora__PaymentGateway__c,
            'Second customer account was inserted with the Amp Gateway');

        customerAccounts[0].Zuora__PaymentGateway__c = ampGateway.Id;
        customerAccounts[1].Zuora__PaymentGateway__c = null;
        update customerAccounts;

        customerAccounts = [
            SELECT Id, Name, Zuora__PaymentGateway__c
            FROM Zuora__CustomerAccount__c
            ORDER BY Name
        ];
        System.assertEquals(ampGateway.Id, customerAccounts[0].Zuora__PaymentGateway__c,
            'First customer account was updated to have the Amp Gateway');
        System.assertEquals(bcsGateway.Id, customerAccounts[1].Zuora__PaymentGateway__c,
            'Second customer account was updated to have the default, but should have been assigned the default');

    }

}