src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Number__c</fullName>
        <description>CS Account Number</description>
        <displayFormat>BW-{0000000}</displayFormat>
        <label>CS Account Number</label>
        <type>AutoNumber</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Zuora__PaymentGateway__c.object
<CustomObject>
    <fields>
        <fullName>Client_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Owner</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Payment Gateways</relationshipLabel>
        <relationshipName>Payment_Gateways</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora__External_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Payment Gateway</label>
    <nameField>
        <label>PaymentGateway Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Gateways</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/GatewaySelector.cls
/**
 * Created by PeterYao on 10/9/2019.
 * Tested By: BatchAuthNetReturnedTransactionsTest, GatewaySelectorTest
 */
// Since this should run as system
@SuppressWarnings('PMD.ApexCRUDViolation')
public without sharing class GatewaySelector {
    public List<Zuora__PaymentGateway__c> getAllZuoraGateways() {
        return [
            SELECT Id, Name,
                Zuora__External_Id__c,
                Client_Owner__r.Account_Number__c
            FROM Zuora__PaymentGateway__c
        ];
    }
}