src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Parent_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Lookup to Parent Account</inlineHelpText>
        <label>Parent Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Properties</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora_Payment_Ref_Id__c</fullName>
        <description>Zuora Payment Reference Id should be passed from the Originations platform during their processes. The Payment Info Id will need to be associated with a customer&apos;s Zuora account once we create it. The Payment information expires, so reference Zuora_Payment_Ref_Id_Expiration_Date__c to make sure the Id is still valid.</description>
        <label>Zuora Payment Ref Id</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Continue_Application_Link__c</fullName>
        <description>A generic URL field that can be set by a UI to provide a link specific to this lead</description>
        <inlineHelpText>Stores URL to visit an application as this lead</inlineHelpText>
        <label>Continue Application Link</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Zuora_Payment_Ref_Id__c</fullName>
        <description>Zuora Payment Reference Id should be passed from the Originations platform during their processes. The Payment Info Id will need to be associated with a customer&apos;s Zuora account once we create it. The Payment information expires, so reference Zuora_Payment_Ref_Id_Expiration_Date__c to make sure the Id is still valid.</description>
        <label>Zuora Payment Ref Id</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Lead</fullName>
        <active>true</active>
        <businessProcess>CS</businessProcess>
        <label>Lead</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Utility_Account_Log__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Utility Account Logs</relationshipLabel>
        <relationshipName>Utility_Account_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Utility Account Logs</relationshipLabel>
        <relationshipName>Utility_Account_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Name_on_Account__c</fullName>
        <label>Name on Utility Account</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Address__c</fullName>
        <label>Service Address</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_City__c</fullName>
        <label>Service City</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_State__c</fullName>
        <label>Service State</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Zip_Code__c</fullName>
        <label>Service Zip Code</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>Utility Account Log</label>
    <nameField>
        <label>Utility Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Account Logs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/LeadSelectorTest.cls
/*************************************************************************************
 * Created By: peteryao on 2019-04-30  
   *************************************************************************************/
@IsTest
public with sharing class LeadSelectorTest {
    @IsTest
    public static void testSelectById() {
        Lead testLead = new Lead(
            FirstName = 'FirstName',
            LastName = 'LastName',
            Company = 'Company',
            Email = 'email@sample.com',
            Status = 'Qualified',
            Zuora_Payment_Ref_Id__c = '2c92c0f86a6e0622016a6fc7f32e010a'
        );
        insert testLead;
        Database.LeadConvert lc = new Database.LeadConvert();
        lc.setLeadId(testLead.Id);
        LeadStatus convertStatus = [SELECT Id, MasterLabel FROM LeadStatus WHERE IsConverted=TRUE LIMIT 1];
        lc.setConvertedStatus(convertStatus.MasterLabel);
        lc.setDoNotCreateOpportunity(true);
        Database.convertLead(lc);

        System.assertEquals(testLead.Zuora_Payment_Ref_Id__c, LeadSelector.selectConvertedByIds(new List<Id>{testLead.Id})[0].Zuora_Payment_Ref_Id__c);
    }

    @IsTest
    private static void testSelectOneWithPropertiesAndUtilities() {
        Lead testLead = new Lead(
            FirstName = 'FirstName',
            LastName = 'LastName',
            Company = 'Company',
            Email = 'email@sample.com',
            Status = 'Qualified'
        );
        insert testLead;

        Account a = new Account(
            Lead__c = testLead.Id,
            Name = 'Test Account', 
            BillingStreet = '123 Test St', 
            BillingCity = 'Testcity', 
            BillingStateCode = 'MA', 
            BillingPostalCode = '02633'
        );
        insert a;

        Utility_Account_Log__c ual = new Utility_Account_Log__c(
            Lead__c = testLead.Id,
            Account__c = a.Id, 
            Name = '123456', 
            Name_on_Account__c = 'Firstname Lastname', 
            Service_Address__c = '123 Test St', 
            Service_City__c = 'Testcity', 
            Service_State__c = 'MA', 
            Service_Zip_Code__c = '02633' 
        );
        insert ual;

        LeadSelector selector = new LeadSelector();
        Lead l = selector.selectOneWithPropertiesAndUtilities(testLead.Id);
        System.assertNotEquals(null, l, 'Selector should have returned a lead record');
        System.assertEquals(1, l.Accounts__r.size(), 'Selector should have returned a child account with the lead record');
        System.assertEquals(1, l.Utility_Account_Logs__r.size(), 'Selector should have returned a child utility account log with the lead record');
    }

    @IsTest
    private static void testSelectOneIncompleteSSFLeadByEmail() {
        Lead matchingLead = new Lead(
            FirstName = 'Match',
            LastName = 'Testcase',
            Email = 'test@email.com',
            Company = 'Testcase',
            LeadSource = 'Switch',
            Continue_Application_Link__c = 'continueURL.com'
        );

        insert matchingLead;

        Lead checkLead = new LeadSelector().selectOneIncompleteSSFLeadByEmail('test@email.com');
        System.assertNotEquals(null, checkLead);
        Lead noMatchLead = new LeadSelector().selectOneIncompleteSSFLeadByEmail('nomatch@email.com');
        System.assertEquals(null, noMatchLead);
    }
}