src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Date_Removed_from_Project__c</fullName>
        <inlineHelpText>Automatically filled when this Property Account has been removed from all enacted Schedule Z&apos;s.</inlineHelpText>
        <label>Date Removed from Last Project</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Parent_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Lookup to Parent Account</inlineHelpText>
        <label>Parent Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Properties</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Account is Closed if all Opportunities are Cancelled, Duplicate, Expired or Dead</inlineHelpText>
        <label>CS Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Property</fullName>
        <active>true</active>
        <label>Property</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Date_Removed_from_Project__c</fullName>
        <inlineHelpText>Automatically set when all UASes related to this Opportunity are inactive, with a Date Removed From project, with at least one Allocation Schedule Subscription that was enacted, (unless all UASes related to the Opp are transferring).</inlineHelpText>
        <label>Date Removed from Project</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Parent_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shared_Solar_System__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>To change this system, use the Change SSS quick action</inlineHelpText>
        <label>Shared Solar System</label>
        <referenceTo>Shared_Solar_System__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Schedule_Z__c.object
<CustomObject>
    <fields>
        <fullName>Shared_Solar_System__c</fullName>
        <label>Shared Solar System</label>
        <referenceTo>Shared_Solar_System__c</referenceTo>
        <relationshipName>Schedule_Zs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Must be updated via the &quot;Update Status &amp; Date&quot; button</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>QC in Process</fullName>
                    <default>true</default>
                    <label>QC in Process</label>
                </value>
                <value>
                    <fullName>QC Complete</fullName>
                </value>
                <value>
                    <fullName>Rejected Internal</fullName>
                </value>
                <value>
                    <fullName>Submitted to Asset Owner</fullName>
                </value>
                <value>
                    <fullName>Executed by Asset Owner</fullName>
                </value>
                <value>
                    <fullName>Submitted to Utility</fullName>
                </value>
                <value>
                    <fullName>Rejected by Utility</fullName>
                </value>
                <value>
                    <fullName>Enacted by Utility</fullName>
                </value>
                <value>
                    <fullName>Billing</fullName>
                </value>
                <value>
                    <fullName>Replaced</fullName>
                </value>
                <value>
                    <fullName>Executed by Asset Owner (old version)</fullName>
                    <isActive>false</isActive>
                    <label>Executed by Asset Owner &gt;&gt;&gt; Submit to Utility</label>
                </value>
                <value>
                    <fullName>Front Page QC Completed &gt;&gt;&gt; Submit to Asset Owner</fullName>
                    <isActive>false</isActive>
                    <label>Front Page QC Completed &gt;&gt;&gt; Submit to Asset Owner</label>
                </value>
                <value>
                    <fullName>New</fullName>
                    <isActive>false</isActive>
                    <label>New &gt;&gt;&gt; Complete Subscription QC</label>
                </value>
                <value>
                    <fullName>Rejected by Utility (old version)</fullName>
                    <isActive>false</isActive>
                    <label>Rejected</label>
                </value>
                <value>
                    <fullName>Replaced with newly Enacted Schedule Z</fullName>
                    <isActive>false</isActive>
                    <label>Replaced with newly Enacted Schedule Z</label>
                </value>
                <value>
                    <fullName>Submitted to Asset Owner &gt;&gt;&gt; Contact Asset Owner to get it Executed</fullName>
                    <isActive>false</isActive>
                    <label>Submitted to Asset Owner &gt;&gt;&gt; Contact Asset Owner to get it Executed</label>
                </value>
                <value>
                    <fullName>Submitted to Utility (old version)</fullName>
                    <isActive>false</isActive>
                    <label>Submitted to Utility &gt;&gt;&gt; Contact Utility to get it Enacted</label>
                </value>
                <value>
                    <fullName>QC Complete (old version)</fullName>
                    <isActive>false</isActive>
                    <label>Subscription QC Completed &gt;&gt;&gt; Complete Front Page QC</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Allocation Schedule</label>
    <nameField>
        <label>Allocation Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Allocation Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Schedule_Z_Subscription__c.object
<CustomObject>
    <fields>
        <fullName>Utility_Account_Subscription__c</fullName>
        <label>Utility Account Subscription</label>
        <referenceTo>Utility_Account_Subscription__c</referenceTo>
        <relationshipName>Schedule_Z_Subscriptions</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Allocation Schedule Subscription</label>
    <nameField>
        <displayFormat>ALSS-{0000}</displayFormat>
        <label>Allocation Schedule Subscription Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Allocation Schedule Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Utility_Account_Log__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Utility Account Logs</relationshipLabel>
        <relationshipName>Utility_Account_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Annual_Cost_of_Electricity__c</fullName>
        <description>This is used for the SREC CS Product sizing. It is the total dollar amount a customer spends annually on their electric utility bill for this account. It is initially filled in with an estimate from the customer/partner during the CS application process, then filled in by Ops with the QCed amount.</description>
        <inlineHelpText>Used for SREC CS Product sizing. It&apos;s the total dollar amount spent annually on the electric utility bill. It is initially filled in with an estimate from the customer/partner during the CS application process, then filled in by Ops with the QCed amount.</inlineHelpText>
        <label>Annual Cost of Electricity</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Name_on_Account__c</fullName>
        <label>Name on Utility Account</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Utility Account Logs</relationshipLabel>
        <relationshipName>Utility_Account_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Utility Account Log</label>
    <nameField>
        <label>Utility Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Account Logs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Utility_Account_Subscription__c.object
<CustomObject>
    <fields>
        <fullName>Annual_Cost_of_Electricity__c</fullName>
        <description>Total cost of electricity at the UAL level.</description>
        <label>Full Annual Cost of Electricity</label>
        <precision>9</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Date_Removed_from_Project__c</fullName>
        <inlineHelpText>Populated with Date Allocation Schedule Retired by Utility when &quot;Date Allocation Schedule Retired by Utility&quot; on all related Allocation Schedule Subscriptions is populated AND Date Utility Account Cancelled is NOT populated</inlineHelpText>
        <label>Date Removed from Project</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Name_on_Account__c</fullName>
        <description>Customer&apos;s name on their electric bill</description>
        <label>Name on Account</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Next_Schedule_Z_Status__c</fullName>
        <defaultValue>&quot;Active Subscription&quot;</defaultValue>
        <inlineHelpText>Controls whether this subscription should be added to future Allocation Schedules. Select &apos;Active Subscription&apos; to include it, or &apos;Inactive Subscription&apos; to exclude it.</inlineHelpText>
        <label>Next Allocation Schedule Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active Subscription</fullName>
                    <default>true</default>
                    <label>Active Subscription</label>
                </value>
                <value>
                    <fullName>Inactive Subscription</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Utility Account Subscriptions</relationshipLabel>
        <relationshipName>Utility_Account_Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shared_Solar_System__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the SSS on the Opportunity when the UAS was created. The SSS on an existing UAS should never be changed.</description>
        <inlineHelpText>This is the SSS on the Opportunity when the UAS was created. The SSS on an existing UAS should never be changed.</inlineHelpText>
        <label>Shared Solar System</label>
        <referenceTo>Shared_Solar_System__c</referenceTo>
        <relationshipLabel>Utility Account Subscriptions</relationshipLabel>
        <relationshipName>Utility_Account_Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>This is displayed in the customer portal as a way of showing the status of a customer&apos;s subscription using a combination of Current Allocation Schedule Status, Next Allocation Schedule Status, and Date Removed</description>
        <formula>IF(
 ISBLANK(Date_Removed_from_Project__c)=false,
&quot;Inactive&quot;,

IF(

  ISPICKVAL(Next_Schedule_Z_Status__c,&quot;Active Subscription&quot;)
&amp;&amp;
 Current_Schedule_Z_Status__c=&quot;Not Yet Enacted&quot;,
&quot;Coming Soon&quot;,

IF(
  ISPICKVAL(Next_Schedule_Z_Status__c,&quot;Active Subscription&quot;)
&amp;&amp;
 Current_Schedule_Z_Status__c=&quot;Enacted&quot;,
&quot;Active&quot;,

IF(
  ISPICKVAL(Next_Schedule_Z_Status__c,&quot;Inactive Subscription&quot;)
&amp;&amp;
 Current_Schedule_Z_Status__c=&quot;Enacted&quot;,
&quot;Pending Removal&quot;,&quot;&quot;)


)
)
)</formula>
        <inlineHelpText>This is displayed in the customer portal as a way of showing the status of a customer&apos;s subscription using a combination of Current Allocation Schedule Status, Next Allocation Schedule Status, and Date Removed</inlineHelpText>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Utility_Account_Log__c</fullName>
        <inlineHelpText>The related UAL</inlineHelpText>
        <label>Utility Account Log</label>
        <referenceTo>Utility_Account_Log__c</referenceTo>
        <relationshipLabel>Utility Account Subscriptions</relationshipLabel>
        <relationshipName>Utility_Account_Subscriptions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Utility Account Subscription</label>
    <nameField>
        <label>Utility Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Account Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/InvocableDateEnactedALSUpdateTestclass.cls
/**
 * Created by SarahRenfro on 12/15/2020.
 */

@IsTest

private class InvocableDateEnactedALSUpdateTestclass {
    @TestSetup
    static void testSetup() {
        SubscriptionManagementServiceTest.setupData();
    }

    /****************
    * UNIT TESTS
    *****************/

    @IsTest
    static void testFindRetiredUASes() {
        useMocks();
        InvocableDateEnactedALSUpdate invocableService = new InvocableDateEnactedALSUpdate();
        List<Utility_Account_Subscription__c> checkUASes = invocableService.findRetiredUASes(getReplacedScheduleZ().Id, Date.newInstance(2020, 01, 08), Date.newInstance(2020, 01, 12) );

        System.assertEquals(2, checkUASes.size(), 'Only the UASes with a matching Date Removed From Project get updated.');
        System.assertEquals(Date.newInstance(2020, 01, 12), checkUASes[0].Date_Removed_from_Project__c, 'UAS updated with new Date Removed From Utility from ALS');
        System.assertEquals(Date.newInstance(2020, 01, 12), checkUASes[1].Date_Removed_from_Project__c, 'UAS updated with new Date Removed From Utility from ALS');

    }

    @IsTest
    static void testFindRetiredOpportunities() {
        useMocks();
        InvocableDateEnactedALSUpdate invocableService = new InvocableDateEnactedALSUpdate();
        List<Opportunity> checkOpps = invocableService.findRetiredOpportunities();

        System.assertEquals(1, checkOpps.size(), 'Only update Opportunities where the UAS change in Date Removed From Project resulted in new max Date Removed From Project');
        System.assertEquals(Date.newInstance(2020, 01, 12), checkOpps[0].Date_Removed_from_Project__c, 'Opp is updated with Date Removed From Project from UAS');
    }

    @IsTest
    static void testFindRetiredAccounts() {
        useMocks();
        InvocableDateEnactedALSUpdate invocableService = new InvocableDateEnactedALSUpdate();
        List<Account> checkAccounts = invocableService.findRetiredAccounts();


        System.assertEquals(1, checkAccounts.size(), 'Only update Accounts where the Opp change in Date Removed From Project resulted in a new max Date Removed From Project');
        System.assertEquals(Date.newInstance(2020, 01, 12), checkAccounts[0].Date_Removed_from_Project__c, 'Account is updated with Date Removed from Project from Opp');
    }

    /**
     * SYSTEM TEST
    */

    @IsTest
    static void testHappyPath() {
        Shared_Solar_System__c sss = [
            SELECT Id
            FROM Shared_Solar_System__c
            LIMIT 1
        ];

        Date oldRetiredDate = Date.newInstance(2020, 01, 08);
        Date newRetiredDate = Date.newInstance(2020, 01, 12);

        Id parentAccountRT =
            Schema.SObjectType.Account.getRecordTypeInfosByName().get('Parent Account').getRecordTypeId();

        Account parentAccount = new Account(
            Name = 'Parent Account',
            RecordTypeId = parentAccountRT
        );
        insert parentAccount;

        Account propertyAccount = new Account(
            Name = 'Property Account',
            Parent_Account__c = parentAccount.Id,
            Date_Removed_from_Project__c = oldRetiredDate
        );
        insert propertyAccount;

        Opportunity opp = new Opportunity(
            Name = 'Opportunity A',
            AccountId = propertyAccount.Id,
            Date_Removed_from_Project__c = oldRetiredDate,
            Shared_Solar_System__c = sss.Id,
            StageName = 'Complete',
            CloseDate = System.today()
        );
        insert opp;

        Utility_Account_Log__c ual =
            new Utility_Account_Log__c(Name = '0000234',
                Account__c = propertyAccount.Id,
                Annual_Cost_of_Electricity__c = 10000,
                Name_on_Account__c = 'sarah testcase');
        insert ual;

        Utility_Account_Subscription__c uas =
            new Utility_Account_Subscription__c(Name = '0000234',
                Utility_Account_Log__c = ual.Id,
                Opportunity__c = opp.Id,
                Next_Schedule_Z_Status__c = 'Inactive Subscription',
                Date_Removed_from_Project__c = oldRetiredDate
            );
        insert uas;

        Schedule_Z__c enactedALS = new Schedule_Z__c(
            Name = 'Enacted ALS',
            Shared_Solar_System__c = sss.Id,
            Status__c = 'Enacted By Utility',
            Date_Enacted_by_Utility__c = oldRetiredDate
        );

        Schedule_Z__c billingALS = new Schedule_Z__c(
            Name = 'Billing ALS',
            Shared_Solar_System__c = sss.Id,
            Status__c = 'Billing',
            Date_Schedule_Z_Retired_by_Utility__c = oldRetiredDate
        );

        insert new List<Schedule_Z__c>{enactedALS, billingALS};
        List<Id> alsList = new List<Id>{enactedALS.Id, billingALS.Id};

        Schedule_Z_Subscription__c alss = new Schedule_Z_Subscription__c(
            Schedule_Z__c = billingALS.Id,
            Utility_Account_Subscription__c = uas.Id,
            Number_of_Decimal_Places__c = 4,
            Customer_Subscription_kW_DC__c = 5,
            System_Size_kW_DC__c = 100
        );
        insert alss;

        enactedALS.Date_Enacted_by_Utility__c = newRetiredDate;
        update enactedALS;

        InvocableDateEnactedALSUpdate.updateDateRemovedFromProject(new List<List<Id>>{alsList});

        Schedule_Z__c checkALS = [
            SELECT Id, Date_Schedule_Z_Retired_by_Utility__c
            FROM Schedule_Z__c
            WHERE Status__c = 'Billing'
            LIMIT 1
        ];

        System.assertEquals(newRetiredDate, checkALS.Date_Schedule_Z_Retired_by_Utility__c, 'Billing ALS should be updated with "Date Enacted By Utility" from Enacted ALS');

        Utility_Account_Subscription__c checkUAS = [
            SELECT Id, Date_Removed_from_Project__c
            FROM Utility_Account_Subscription__c
            LIMIT 1
        ];
        System.assertEquals(newRetiredDate, checkUAS.Date_Removed_from_Project__c, 'UAS should be updated with new Date Removed from Project from retired ALS');

        Opportunity checkOpp = [
            SELECT Id, Date_Removed_from_Project__c
            FROM Opportunity
            LIMIT 1
        ];
        System.assertEquals(newRetiredDate, checkOpp.Date_Removed_from_Project__c, 'Opp should be updated with new Date Removed from Project from UAS');


        Account checkAccount = [
            SELECT Id, Date_Removed_from_Project__c
            FROM Account
            WHERE Id = :propertyAccount.Id
        ];
        System.assertEquals(newRetiredDate, checkAccount.Date_Removed_from_Project__c, 'Account should be updated with new Date Removed from Project from Opportunity');
    }

    /***************************
     * MOCKS & HELPER METHODS
    ***************************/

    public static Schedule_Z__c getReplacedScheduleZ() {
        Date retiredDate = Date.newInstance(2020,01,08);
        Schedule_Z__c scheduleZ = new Schedule_Z__c(
            Id = 'a3z0a000000pJnEAAU',
            Date_Schedule_Z_Retired_by_Utility__c = retiredDate,
            Shared_Solar_System__c = 'a1J0a000008l0FdEAI'
        );
        return scheduleZ;
    }

    private static void useMocks() {
        InvocableDateEnactedALSUpdate.szsSelector = (ScheduleZSubscriptionSelector) Test.createStub(ScheduleZSubscriptionSelector.class, new MockScheduleZSubscriptionSelector());
        InvocableDateEnactedALSUpdate.oppSelector = (OpportunitiesSelector) Test.createStub(OpportunitiesSelector.class, new MockOpportunitiesSelector());
        InvocableDateEnactedALSUpdate.acctSelector = (AccountsSelector) Test.createStub(AccountsSelector.class, new MockAccountSelector());
    }

    public class MockScheduleZSubscriptionSelector extends MockProvider {
        public MockScheduleZSubscriptionSelector() {
        }
        public override Object handleMethodCall(MethodCall methodCall) {
            String retiredDate = '2020-01-08';
            // 2 UASes with a Date Removed From Project from an ALS
            // 1 UAS with a Date Removed From Project from a finalled UAL
            String szs = '[{"attributes" : {"type" : "Schedule_Z_Subscription__c","url" : "/services/data/v47.0/sobjects/Schedule_Z_Subscription__c/a540a000000UxtGAAA"},' +
                '"Id" : "a540a000000UxtGAAA",' +
                '"Name" : "szsA",' +
                '"Utility_Account_Subscription__c": "a1d0a000001npymAAA" ,' +
                    '"Utility_Account_Subscription__r": {"attributes" : {"type" : "Utility_Account_Subscription__c","url" : "/services/data/v47.0/sobjects/Utility_Account_Subscription__c/a1d0a000001npymAAA"},' +
                    '"Id" : "a1d0a000001npymAAA",' +
                    '"Date_Removed_from_Project__c" : "'+ retiredDate + '"' +
                    '},' +
                '"Schedule_Z__c": "a3z0a000000pJnEAAU",' +
                    '"Schedule_Z__r": {"attributes": {"type" : "Schedule_Z__c","url" : "/services/data/v47.0/sobjects/Schedule_Z__c/a3z0a000000pJnEAAU"}, ' +
                    '"Id": "a3z0a000000pJnEAAU",' +
                    '"Date_Schedule_Z_Retired_by_Utility__c": "'+ retiredDate + '"' +
                    '}'+
                '},' +
                '{"attributes" : {"type" : "Schedule_Z_Subscription__c","url" : "/services/data/v47.0/sobjects/Schedule_Z_Subscription__c/a540a000000UxtGBBB"},' +
                '"Id" : "a540a000000UxtGBBB",' +
                '"Name" : "szsB",' +
                '"Utility_Account_Subscription__c": "a1d0a000001npymBBB" ,' +
                    '"Utility_Account_Subscription__r": {"attributes" : {"type" : "Utility_Account_Subscription__c","url" : "/services/data/v47.0/sobjects/Utility_Account_Subscription__c/a1d0a000001npymBBB"},' +
                    '"Id" : "a1d0a000001npymBBB",' +
                    '"Date_Removed_from_Project__c" : "' + retiredDate + '"' +
                    '},' +
                '"Schedule_Z__c": "a3z0a000000pJnEAAU",' +
                    '"Schedule_Z__r": {"attributes": {"type" : "Schedule_Z__c","url" : "/services/data/v47.0/sobjects/Schedule_Z__c/a3z0a000000pJnEAAU"}, ' +
                    '"Id": "a3z0a000000pJnEAAU",' +
                    '"Date_Schedule_Z_Retired_by_Utility__c": "' + retiredDate + '"' +
                    '}' +
                '},' +
                '{"attributes" : {"type" : "Schedule_Z_Subscription__c","url" : "/services/data/v47.0/sobjects/Schedule_Z_Subscription__c/a540a000000UxtGCCC"},' +
                '"Id" : "a540a000000UxtGCCC",' +
                '"Name" : "szsC",' +
                '"Utility_Account_Subscription__c": "a1d0a000001npymCCC" ,' +
                    '"Utility_Account_Subscription__r": {"attributes" : {"type" : "Utility_Account_Subscription__c","url" : "/services/data/v47.0/sobjects/Utility_Account_Subscription__c/a1d0a000001npymCCC"},' +
                    '"Id" : "a1d0a000001npymCCC",' +
                    '"Date_Removed_from_Project__c" : "2019-11-01"' +
                    '},' +
                '"Schedule_Z__c": "a3z0a000000pJnEAAU",' +
                    '"Schedule_Z__r": {"attributes": {"type" : "Schedule_Z__c","url" : "/services/data/v47.0/sobjects/Schedule_Z__c/a3z0a000000pJnEAAU"}, ' +
                    '"Id": "a3z0a000000pJnEAAU",' +
                    '"Date_Schedule_Z_Retired_by_Utility__c": "' + retiredDate + '"' +
                    '}' +
                '}]';

            switch on methodCall.stubbedMethodName {
                when 'getRetiredALSSFromALS' {
                    return (List<Schedule_Z_Subscription__c>) JSON.deserialize(szs, List<Schedule_Z_Subscription__c>.class);
                }
            }
            return null;
        }
    }

    public class MockOpportunitiesSelector extends MockProvider {
        public MockOpportunitiesSelector() {
        }
        public override Object handleMethodCall(MethodCall methodCall) {
            String retiredDate = '2020-01-08';
            String newRetiredDate = '2020-01-12';
            String opps = '[{"attributes" : {"type" : "Opportunity","url" : "/services/data/v47.0/sobjects/Opportunity/006e000000MJSVoAAP"},' +
                '"AccountId":"001j0000011mR6LAAU",' +
                '"Id" : "006e000000MJSVoAAA",' +
                '"Name" : "oppA",' +
                '"Date_Removed_From_Project__c": "2020-04-02",' +
                '"Shared_Solar_System__c": "a1J0a000008l0FdEAI",' +
                '"Utility_Account_Subscriptions__r": {' +
                '    "totalSize": 2,' +
                '       "done": true,' +
                '       "records": ' +
                '           [' +
                '               {' +
                '                   "attributes": {' +
                '                       "type": "Utility_Account_Subscription__c",' +
                '                       "url": "/services/data/v48.0/sobjects/Utility_Account_Subscription__c/a1d0a000001npymAAA"' +
                '                   },' +
                '                   "Opportunity__c": "006e000000MJSVoAAA",' +
                '                   "Id": "a1d0a000001npymAAA",' +
                '                   "Date_Removed_From_Project__c": "' + newRetiredDate + '"' +
                '               },' +
                '               {' +
                '                   "attributes": {' +
                '                       "type": "Utility_Account_Subscription__c",' +
                '                       "url": "/services/data/v48.0/sobjects/Utility_Account_Subscription__c/a1d0a000001npymBBB"' +
                '                   },' +
                '                   "Opportunity__c": "006e000000MJSVoAAA",' +
                '                   "Id": "a1d0a000001npymBBB",' +
                '                   "Date_Removed_From_Project__c": "2020-04-02"' +
                '               }' +
                '           ]' +
                '   }' +
                '}, '  +
                '{"attributes" : {"type" : "Opportunity","url" : "/services/data/v47.0/sobjects/Opportunity/006e000000MJSVoBBB"},' +
                '"AccountId":"001j0000011mR6LBBB",' +
                '"Id" : "006e000000MJSVoBBB",' +
                '"Name" : "oppB",' +
                '"Date_Removed_From_Project__c": "' + retiredDate + '",' +
                '"Shared_Solar_System__c": "a1J0a000008l0FdEAI",' +
                '"Utility_Account_Subscriptions__r": {' +
                '    "totalSize": 1,' +
                '       "done": true,' +
                '       "records": ' +
                '           [' +
                '               {' +
                '                   "attributes": {' +
                '                       "type": "Utility_Account_Subscription__c",' +
                '                       "url": "/services/data/v48.0/sobjects/Utility_Account_Subscription__c/a1d0a000001npymCCC"' +
                '                   },' +
                '                   "Opportunity__c": "006e000000MJSVoBBB",' +
                '                   "Id": "a1d0a000001npymCCC",' +
                '                   "Date_Removed_From_Project__c": "' + newRetiredDate + '"' +
                '               }' +
                '           ]' +
                '   }' +
                '}]';

            switch on methodCall.stubbedMethodName {
                when 'selectRetiredOpportunities' {
                    return (List<Opportunity>) JSON.deserialize(opps, List<Opportunity>.class);
                }
            }


            return null;
        }
    }

    public class MockAccountSelector extends MockProvider {
        public MockAccountSelector() {
        }
        public override Object handleMethodCall(MethodCall methodCall) {
            String retiredDate = '2020-01-08';
            String newRetiredDate = '2020-01-12';
            String accts = '[{"attributes" : {"type" : "Account","url" : "/services/data/v47.0/sobjects/Account/001e000001Zo2EMAAA"},' +
                '"Id" : "001e000001Zo2EMAAA",' +
                '"Name" : "Account A",' +
                '"Date_Removed_From_Project__c": "2020-04-02",' +
                '"Opportunities": {' +
                '    "totalSize": 2,' +
                '       "done": true,' +
                '       "records": ' +
                '           [' +
                '               {' +
                '                   "attributes": {' +
                '                       "type": "Opportunity",' +
                '                       "url": "/services/data/v48.0/sobjects/Opportunity/006e000000MJSVoAAA"' +
                '                   },' +
                '                   "Id": "006e000000MJSVoAAA",' +
                '                   "Date_Removed_From_Project__c": "' + newRetiredDate + '"' +
                '               },' +
                '               {' +
                '                   "attributes": {' +
                '                       "type": "Opportunity",' +
                '                       "url": "/services/data/v48.0/sobjects/Opportunity/006e000000MJSVoBBB"' +
                '                   },' +
                '                   "Id": "006e000000MJSVoAAA",' +
                '                   "Date_Removed_From_Project__c": "2020-04-02"' +
                '               }' +
                '           ]' +
                '   }' +
                '},' +
                '{"attributes" : {"type" : "Account","url" : "/services/data/v47.0/sobjects/Account/001e000001Zo2EMBBB"},' +
                '"Id" : "001e000001Zo2EMBBB",' +
                '"Name" : "Account B",' +
                '"Date_Removed_From_Project__c": "' + retiredDate + '",' +
                '"Opportunities": {' +
                '    "totalSize": 1,' +
                '       "done": true,' +
                '       "records": ' +
                '           [' +
                '               {' +
                '                   "attributes": {' +
                '                       "type": "Opportunity",' +
                '                       "url": "/services/data/v48.0/sobjects/Opportunity/006e000000MJSVoCCC"' +
                '                   },' +
                '                   "Id": "006e000000MJSVoCCC",' +
                '                   "Date_Removed_From_Project__c": "' + newRetiredDate + '"' +
                '               }' +
                '           ]' +
                '   }' +
                '}]';


            switch on methodCall.stubbedMethodName {
                when 'getRetiredAccounts' {
                    return (List<Account>) JSON.deserialize(accts, List<Account>.class);
                }
            }
            return null;
        }
    }
}