src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>State__c</fullName>
        <label>Service State</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Entity__c.object
<CustomObject>
    <fields>
        <fullName>Client_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Entities</relationshipLabel>
        <relationshipName>Entities</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Entity</label>
    <nameField>
        <label>Entity</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Product_Type__c</fullName>
        <label>Product Type</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
                <value>
                    <fullName>MN</fullName>
                </value>
                <value>
                    <fullName>MS</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
                <value>
                    <fullName>NE</fullName>
                </value>
                <value>
                    <fullName>NV</fullName>
                </value>
                <value>
                    <fullName>NH</fullName>
                </value>
                <value>
                    <fullName>NJ</fullName>
                </value>
                <value>
                    <fullName>NM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Service_Territory__c.object
<CustomObject>
    <fields>
        <fullName>Service_Territory__c</fullName>
        <label>Service Territory</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Service Territory</label>
    <nameField>
        <label>Zip Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Territories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Shared_Solar_System__c.object
<CustomObject
     >
    <articleTypeChannelDisplay n1:nil="true" />
    <customSettingsType n1:nil="true" />
    <description n1:nil="true" />
    <eventType n1:nil="true" />
    <fields>
        <fullName>Client_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The client account field designates that party in which this shared solar system is being serviced for.</description>
        <inlineHelpText>The client account field designates that party in which this shared solar system is being serviced for.</inlineHelpText>
        <label>Client Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Shared Solar Systems</relationshipLabel>
        <relationshipName>Shared_Solar_Systems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Utility__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Utility</label>
        <referenceTo>Utility__c</referenceTo>
        <relationshipLabel>Shared Solar Systems</relationshipLabel>
        <relationshipName>Shared_Solar_Systems</relationshipName>
        <type>Lookup</type>
    </fields>
    <gender n1:nil="true" />
    <household>false</household>
    <label>Shared Solar System</label>
    <nameField>
        <label>Shared Solar System Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shared Solar Systems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <startsWith n1:nil="true" />
</CustomObject>

src/objects/Utility__c.object
<CustomObject>
    <fields>
        <fullName>Number_of_Decimal_Places__c</fullName>
        <inlineHelpText>Used for calculating kW subscriptions for SOs</inlineHelpText>
        <label>Number of Decimal Places</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Utility</label>
    <nameField>
        <label>Utility Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/EntitySelectorTest.cls
/**
 * Created by peteryao on 9/25/20.
 */
@IsTest
public with sharing class EntitySelectorTest {
    @IsTest
    private static void testGetContractAssignmentEntitiesForClient() {
        Utility__c eversource = new Utility__c(
            Name = 'Eversource',
            Number_of_Decimal_Places__c = 2
        );
        insert eversource;

        Product2 normalCSProduct = new Product2(Name = 'BlueWave Community Solar',
            Family = 'Community Solar',
            Product_Type__c = 'Community Solar',
            State__c = 'MA',
            ProductCode = 'CS - BlueWave - 10%',
            IsActive = true);
        insert normalCSProduct;

        Account clientAccount = new Account(Name = 'Test Client');
        Account ampAccount = new Account(Name = 'AMP');
        insert new List<Account>{ampAccount, clientAccount};

        Entity__c entity1 = new Entity__c(
            Name = 'Project A Oak Road',
            Client_Account__c = clientAccount.Id
        );
        Entity__c entity2 = new Entity__c(
            Name = 'Project B Oak Road',
            Client_Account__c = clientAccount.Id
        );
        insert new List<Entity__c>{entity1, entity2};

        Shared_Solar_System__c sss1 =
            new Shared_Solar_System__c(Name = 'Project A Oak Road',
                Service_Territory__c = 'SEMA',
                Client_Account__c = clientAccount.Id,
                System_Utility__c = 'Eversource',
                Product__c = normalCSProduct.Id,
                BWC_Project_Entity_Manual__c = entity1.Id,
                Utility__c = eversource.Id,
                Contract_Assignment_Entity__c = entity1.Id
            );
        Shared_Solar_System__c sss2 =
            new Shared_Solar_System__c(Name = 'Project B Oak Road',
                Service_Territory__c = 'SEMA',
                Client_Account__c = clientAccount.Id,
                System_Utility__c = 'Eversource',
                Product__c = normalCSProduct.Id,
                BWC_Project_Entity_Manual__c = entity2.Id,
                Utility__c = eversource.Id,
                Contract_Assignment_Entity__c = entity2.Id
            );
        Shared_Solar_System__c sss3 =
            new Shared_Solar_System__c(Name = 'Project B Oak Road',
                Service_Territory__c = 'SEMA',
                Client_Account__c = clientAccount.Id,
                System_Utility__c = 'Eversource',
                Product__c = normalCSProduct.Id,
                BWC_Project_Entity_Manual__c = entity1.Id,
                Utility__c = eversource.Id,
                Contract_Assignment_Entity__c = entity1.Id
            );
        insert new List<Shared_Solar_System__c>{sss1, sss2, sss3};

        Test.startTest();
        EntitySelector entitySelector = new EntitySelector();
        List<List<Entity__c>> testClientEntities = InvocableEntitySelector.getContractAssignmentEntitiesByClient(new List<Id>{clientAccount.Id});
        System.assertEquals(1, testClientEntities.size(),
            'Expected to find a single list of entities since to support the invocable method');
        System.assertEquals(2, testClientEntities[0].size(),
            'Test Client should have two entities: A and B');
        System.assertEquals(0, entitySelector.getContractAssignmentEntitiesForClient(ampAccount.Id).size(),
            'Did not expect to find an entity for Amp');
        Test.stopTest();
    }
}