src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Partner_Email__c</fullName>
        <label>Partner Email</label>
        <type>Email</type>
    </fields>
    <recordTypes>
        <fullName>Property</fullName>
        <active>true</active>
        <label>Property</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Application__c.object
<CustomObject>
    <fields>
        <fullName>Application_Type__c</fullName>
        <label>Application Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pre_Application</fullName>
                    <label>Pre-Application</label>
                </value>
                <value>
                    <fullName>Interconnection Application</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Application</label>
    <nameField>
        <label>Application</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <recordTypes>
        <fullName>Case</fullName>
        <active>true</active>
        <businessProcess>Customer Care Case</businessProcess>
        <label>Case</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Application_Type__c</fullName>
        <label>Application Type</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Co-Applicants</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Partner_Lookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Link to the Partner Object related to this contact</inlineHelpText>
        <label>Partner Lookup</label>
        <referenceTo>Partner__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Annual_Income_Currency__c</fullName>
        <label>Annual Income</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Application_Type__c</fullName>
        <label>Application Type</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Application__c</fullName>
        <formula>CreatedDate</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The date that the lead was created, used to map the Lead&apos;s Created Date to the Opportunity (since we can&apos;t use CreatedDate in lead mapping)</inlineHelpText>
        <label>Application Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Co_Applicant_Address__c</fullName>
        <label>Co-Applicant Address</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Co_Applicant_Date_of_Birth__c</fullName>
        <label>Co-Applicant Date of Birth</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Co_Applicant_Email__c</fullName>
        <label>Co-Applicant Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Co_Applicant_First_Name__c</fullName>
        <label>Co-Applicant First Name</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Co_Applicant_Income__c</fullName>
        <label>Co-Applicant Income</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Co_Applicant_Last_Name__c</fullName>
        <label>Co-Applicant Last Name</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Co_Applicant_Phone__c</fullName>
        <label>Co-Applicant Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Date_of_Application_2__c</fullName>
        <formula>LEFT(Date_of_Application__c,10)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>For Residential Loan leads, the date that the application was submitted (prior to 1/10/18), or the date that credit was pulled (1/10/18).</inlineHelpText>
        <label>Date of Application</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date_of_Application__c</fullName>
        <inlineHelpText>Set by Form Assembly: YYYY-MM-DD-HH:MM</inlineHelpText>
        <label>Date of Application Key</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date_of_Issuance__c</fullName>
        <label>Date of Issuance</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Direct_Disbursal_to_Installer_Authorized__c</fullName>
        <description>Fed from DOER application form</description>
        <label>Direct Disbursal to Installer Authorized</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Electronic_Disbursal_Authorized__c</fullName>
        <description>Fed from Application form for DOER loan</description>
        <label>Electronic Disbursal Authorized?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Email_Re_Enter__c</fullName>
        <label>Email Re-Enter</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>IBLS_Category__c</fullName>
        <defaultValue>&quot;No category selected&quot;</defaultValue>
        <description>Manually Select the IBLS Category Based off of MCEC Technical Confirmation</description>
        <label>IBLS Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No category selected</fullName>
                </value>
                <value>
                    <fullName>None</fullName>
                    <default>true</default>
                    <label>None</label>
                </value>
                <value>
                    <fullName>Category 1</fullName>
                </value>
                <value>
                    <fullName>Category 2</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Income_Type_2__c</fullName>
        <label>Income Type (2)</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Income_Type__c</fullName>
        <label>Income Type</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Joint_Applicant_Type__c</fullName>
        <label>Joint Applicant Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Co-Applicant</fullName>
                </value>
                <value>
                    <fullName>Co-Signer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Lead_ID__c</fullName>
        <formula>Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Lead ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Partner_Email__c</fullName>
        <label>Partner Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Partner_Lookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Partner</label>
        <referenceTo>Partner__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Partner_Tag__c</fullName>
        <label>Partner Tag</label>
        <length>35</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Personal_Credit_Report_Co_Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Personal Credit Report (Co-Applicant)</label>
        <referenceTo>LASERCA__Personal_Credit_Report__c</referenceTo>
        <relationshipLabel>Leads (Personal Credit Report (Co-Applicant))</relationshipLabel>
        <relationshipName>Leads2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Personal_Credit_Report__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Personal Credit Report</label>
        <referenceTo>LASERCA__Personal_Credit_Report__c</referenceTo>
        <relationshipLabel>Leads (Personal Credit Report)</relationshipLabel>
        <relationshipName>Leads1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Product lookup, for loans, set by an installer upon sending a new application or set by code after a credit check has determined qualifying products.</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Lead</fullName>
        <active>true</active>
        <businessProcess>CS</businessProcess>
        <label>Lead</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Application_Date__c</fullName>
        <description>Maps created date from the lead.</description>
        <inlineHelpText>Maps created date from the lead.</inlineHelpText>
        <label>Application Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Application_Type__c</fullName>
        <label>Application Type</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Co_Applicant_Address__c</fullName>
        <label>Co-Applicant Address</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Co_Applicant_Date_of_Birth__c</fullName>
        <label>Co-Applicant Date of Birth</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Co_Applicant_Email__c</fullName>
        <label>Co-Applicant Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Co_Applicant_First_Name__c</fullName>
        <label>Co-Applicant First Name</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Co_Applicant_Last_Name__c</fullName>
        <label>Co-Applicant Last Name</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Co_Applicant_Phone__c</fullName>
        <label>Co-Applicant Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Customer_Phone__c</fullName>
        <label>Customer Phone</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date_of_Application__c</fullName>
        <label>Date of Application</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Joint_Applicant_Type__c</fullName>
        <label>Joint Applicant Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Co-Applicant</fullName>
                </value>
                <value>
                    <fullName>Co-Signer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Lead_ID__c</fullName>
        <inlineHelpText>Set by Lead Mapping on conversion</inlineHelpText>
        <label>Lead ID</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Set by OpportunityTriggerHandler on Opportunity creation, assuming Opportunity.Lead_ID__c (a text field) is also being set via Lead Mapping.</inlineHelpText>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lived_at_residence_more_than_six_months__c</fullName>
        <label>Lived at residence more than six months</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Partner_Email__c</fullName>
        <label>Partner Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Partner_Tag__c</fullName>
        <label>Partner Tag</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Partner_tag_lookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Partner</label>
        <referenceTo>Partner__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Personal_Credit_Report2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Personal Credit Report</label>
        <referenceTo>LASERCA__Personal_Credit_Report__c</referenceTo>
        <relationshipLabel>Opportunities (Personal Credit Report)</relationshipLabel>
        <relationshipName>Opportunities2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Personal_Credit_Report_Co_Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Personal Credit Report (Co-Applicant)</label>
        <referenceTo>LASERCA__Personal_Credit_Report__c</referenceTo>
        <relationshipLabel>Opportunities (Personal Credit Report (Co-Applicant))</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/LeadService.cls
/**
 * Created by SarahRenfro on 5/15/2019.
 *
 * Tested By: LeadServiceTestclass
 */

public without sharing class LeadService {
    public static Boolean firstRun = true;
    private Map<String, String> leadToOppConvertMap = new Map<String, String> {
        'Annual_Income_Currency__c'=>'Annual_Independent_Income__c',
        'Application__c'=>'Application_Date__c',
        'Application_Type__c'=>'Application_Type__c',
        'Co_Applicant_Address__c'=>'Co_Applicant_Address__c',
        'Co_Applicant_Date_of_Birth__c'=>'Co_Applicant_Date_of_Birth__c',
        'Co_Applicant_Email__c'=>'Co_Applicant_Email__c',
        'Co_Applicant_First_Name__c'=>'Co_Applicant_First_Name__c',
        'Co_Applicant_Income__c'=>'Co_Applicant_Income__c',
        'Co_Applicant_Last_Name__c'=>'Co_Applicant_Last_Name__c',
        'Co_Applicant_Phone__c'=>'Co_Applicant_Phone__c',
        'Company'=>'Name',
        'Date_of_Application_2__c'=>'Date_of_Application__c',
        'Date_of_Issuance__c'=>'Date_of_Issuance__c',
        'Direct_Disbursal_to_Installer_Authorized__c'=>'Direct_Disbursal_to_Installer_Authorized__c',
        'DOER_Solar_Loan__c'=>'DOER_Solar_Loan__c',
        'Electronic_Disbursal_Authorized__c'=>'Electronic_Disbursal_Authorized__c',
        'Email_Re_Enter__c'=>'Email__c',
        'Employed_for_more_than_one_year__c'=>'Employed_for_more_than_one_year__c',
        'Employed_for_more_than_six_months__c'=>'Employed_for_more_than_six_months__c',
        'IBLS_Category__c'=>'IBLS_Category_MappedFromLead__c',
        'Income_Type__c'=>'Income_Type__c',
        'Income_Type_2__c'=>'Income_Type_2__c',
        'Joint_Applicant_Type__c'=>'Joint_Applicant_Type__c',
        'Lead_ID__c'=>'Lead_ID__c',
        'MobilePhone'=>'Customer_Phone__c',
        'lived_residence_six_months__c'=>'Lived_at_residence_more_than_six_months__c',
        'Partner_Lookup__c'=>'Partner_tag_lookup__c',
        'Partner_Email__c'=>'Partner_Email__c',
        'Partner_Tag__c'=>'Partner_Tag__c',
        'Personal_Credit_Report__c'=>'Personal_Credit_Report2__c',
        'Personal_Credit_Report_Co_Applicant__c'=>'Personal_Credit_Report_Co_Applicant__c',
        'Product__c'=>'Product__c',
        'Product_line__c'=>'Product_Line__c',
        'Product_Program__c'=>'Product_Program__c',
        'Project_Identification_Number__c'=>'project_identification_number__c',
        'Referral_Email__c'=>'Referral_Email__c',
        'Requested_Loan_Amount__c'=>'Requested_Loan_Amount__c',
        'Residence_Owner__c'=>'Residence_Owner__c',
        'bs_Sales_ID__c'=>'BS_Sales_ID__c',
        'Sales_Person__c'=>'Sales_Person_Tag__c',
        'SREC_Product__c'=>'SREC_Product__c',
        'State_of_Issuance__c'=>'State_of_Issuance__c',
        'System_Cost__c'=>'Loan_Principle__c',
        'OwnerId'=>'OwnerId'
    };

    public void setupPropertyAccount(List<Lead> updatedLeads, Map<Id, Lead> oldLeadMap) {
        List<Account> propertyAccounts = new List<Account>();
        Id recordType = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Property').getRecordTypeId();

        for (Lead lead : updatedLeads) {
            if (lead.Status == 'Qualified' && oldLeadMap.get(lead.Id).Status != 'Qualified') {
                //Create Property Account for Qualified Leads - will store UALs
                Account propAcct = new Account(
                    Name = lead.Company,
                    Product_Line__c = lead.Product_line__c,
                    RecordTypeId = recordType,
                    Electricity_Provider__c = lead.Utility_relationship__r.Id,
                    Lead__c = lead.Id,
                    BillingStreet = lead.LASERCA__Home_Address__c,
                    BillingCity = lead.LASERCA__Home_City__c,
                    BillingState = BlueWaveParent.convertAbbreviationToState(lead.LASERCA__Home_State__c.toUpperCase()),
                    BillingPostalCode = lead.LASERCA__Home_Zip__c
                );

                propertyAccounts.add(propAcct);
            }
        }

        try {
            insert propertyAccounts;
        } catch (DmlException e) {
            Logger.logNow('LeadService', 'setupQualifiedLead', 'Failed to create Property Account for Leads: ' +  e.getMessage() + System.JSON.serializePretty(updatedLeads));
        }
    }

    public void completeLeadConversion(List<Lead> updatedLeads, Map<Id, Lead> oldLeadMap){
        List<Lead> convertedCSLeads = new List<Lead>();

        for (Lead lead : updatedLeads) {
            if (lead.IsConverted && !oldLeadMap.get(lead.Id).IsConverted &&
                lead.ConvertedAccountId != null &&
                lead.Product_line__c == 'Community Solar' &&
                firstRun) {
                convertedCSLeads.add(lead);
            }

            if (lead.ConvertedAccountId != null) {
                setupSwitchLead(lead);
            }
        }

        if (!convertedCSLeads.isEmpty()) {
            CSSubscriptionEnroller repo = new CSSubscriptionEnroller(convertedCSLeads);
            repo.enroll();
            firstRun = false;
        }

        List<Opportunity> oppsToUpdate = new List<Opportunity>();
        for (Lead lead : updatedLeads) {
            if (lead.IsConverted) {
                Opportunity opp = getUpdatedOpp(lead, oldLeadMap.get(lead.Id));
                if (opp != null) {
                    oppsToUpdate.add(opp);
                }
            }
        }
        if (!oppsToUpdate.isEmpty()) {
            try {
                update oppsToUpdate;
            } catch(Exception e) {
                Logger.logNow('LeadService', 'completeLeadConversion', 'Couldn\'t update opps after lead update: ' + e.getMessage() + System.JSON.serializePretty(oppsToUpdate));
            }
        }
    }

    private Opportunity getUpdatedOpp(Lead newLead, Lead oldLead) {
        Boolean returnNull = true;
        Opportunity opp = new Opportunity(Id = newLead.ConvertedOpportunityId);
        for (String field : leadToOppConvertMap.keySet()) {
            if (newLead.get(field) != oldLead.get(field)) {
                opp.put(leadToOppConvertMap.get(field), newLead.get(field));
                returnNull=false;
            }
        }

        return (returnNull?null:opp);
    }


    public void setupSwitchLead(Lead lead){
        List<Account> propAcctsList = new List<Account>();
        List<Account> updateAccounts = new List<Account>();

        Account convertedAccount = [SELECT Id FROM Account WHERE Id = :lead.ConvertedAccountId LIMIT 1];
        Contact convertedContact = [SELECT Id FROM Contact WHERE Id = :lead.ConvertedContactId LIMIT 1];

        propAcctsList = [
            SELECT Id, Parent_Account__c, Send_Bills_Contact__c
            FROM Account
            WHERE Lead__c = :lead.Id AND RecordType.Name = 'Property'
        ];

        Id recordType = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Parent Account').getRecordTypeId();
        User apiUser = [
            SELECT Id, Name, Username
            FROM User
            WHERE Name = 'API'
            AND IsActive = TRUE
            LIMIT 1
        ];

        convertedAccount.ShippingStreet = lead.Street;
        convertedAccount.ShippingCity = lead.City;
        convertedAccount.ShippingState = lead.State;
        convertedAccount.ShippingPostalCode = lead.PostalCode;
        convertedAccount.RecordTypeId = recordType;
        convertedAccount.BillingStreet = lead.LASERCA__Home_Address__c;
        convertedAccount.BillingCity = lead.LASERCA__Home_City__c;
        convertedAccount.BillingState = BlueWaveParent.convertAbbreviationToState(lead.LASERCA__Home_State__c);
        convertedAccount.BillingPostalCode = lead.LASERCA__Home_Zip__c;
        convertedAccount.OwnerId = apiUser.Id;

        convertedContact.LASERCA__Home_Address__c = lead.LASERCA__Home_Address__c;
        convertedContact.LASERCA__Home_City__c = lead.LASERCA__Home_City__c;
        convertedContact.LASERCA__Home_State__c = lead.LASERCA__Home_State__c;
        convertedContact.LASERCA__Home_Zip__c = lead.LASERCA__Home_Zip__c;
        convertedContact.Product_Line__c = 'Community Solar';

        update convertedContact;
        updateAccounts.add(convertedAccount);


        for (Account propAcct : propAcctsList) {
            propAcct.Parent_Account__c = convertedAccount.Id;
            propAcct.Send_Bills_Contact__c = convertedContact.Id;
            propAcct.UAL_Convert__c = true;
            updateAccounts.add(propAcct);
        }

        if (updateAccounts.size() > 0 ) {
            update updateAccounts;
        }

    }

    public void convertCasesToContact(List<Lead> convertedLeads) {
        List<Case> updateCases = new List<Case>();
        List<Case> casesList = [
            SELECT Id, Subject, Lead_Lookup__r.ConvertedAccountId, Lead_Lookup__r.ConvertedContactId, Lead_Lookup__r.IsConverted,
                Lead_Lookup__r.Product_line__c, AccountId, ContactId
            FROM Case
            WHERE Lead_Lookup__r.Id IN :convertedLeads
            AND Lead_Lookup__r.IsConverted = TRUE
            AND (AccountId = NULL OR ContactId = NULL)
        ];

        for (Case caseToUpdate : casesList) {
            if (caseToUpdate.ContactId == null)  {
                caseToUpdate.ContactId = caseToUpdate.Lead_Lookup__r.ConvertedContactId;
                updateCases.add(caseToUpdate);
            }
        }

        if (updateCases.size() > 0 ) {
            update updateCases;
        }

    }




}