src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Cancellation_Request_Date__c</fullName>
        <inlineHelpText>Must fill out &quot;Cancellation Reason&quot; before saving</inlineHelpText>
        <label>Cancellation Request Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_Removed_from_Project__c</fullName>
        <inlineHelpText>Automatically filled when this Property Account has been removed from all enacted Schedule Z&apos;s.</inlineHelpText>
        <label>Date Removed from Last Project</label>
        <type>Date</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Cancellation_Request_Date__c</fullName>
        <formula>Account.Cancellation_Request_Date__c</formula>
        <inlineHelpText>This is the Cancellation Request Date for the Account.</inlineHelpText>
        <label>Cancellation Request Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>355</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Date_Removed_from_Project__c</fullName>
        <inlineHelpText>Automatically set when all UASes related to this Opportunity are inactive, with a Date Removed From project, with at least one Allocation Schedule Subscription that was enacted, (unless all UASes related to the Opp are transferring).</inlineHelpText>
        <label>Date Removed from Project</label>
        <type>Date</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Subscription_Order__c.object
<CustomObject>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <description>Subscription Orders will not be rolled up to the utility account subscription until they are marked as approved. Once approved, they cannot be changed.</description>
        <inlineHelpText>Subscription Orders will not be rolled up to the utility account subscription until they are marked as approved. Once approved, they cannot be changed.</inlineHelpText>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <description>This is the date that the Subscription Order was approved. It is populated automatically when the Status field is set to approved. Subscription Orders cannot be edited once they&apos;ve been approved.</description>
        <inlineHelpText>This is the date that the Subscription Order was approved. It is populated automatically when the Status field is set to approved. Subscription Orders cannot be edited once they&apos;ve been approved.</inlineHelpText>
        <label>Effective Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>New_Annual_Cost__c</fullName>
        <inlineHelpText>This is the new annual cost that the UAS will have once the SO is effective.</inlineHelpText>
        <label>New Annual Cost</label>
        <precision>16</precision>
        <scale>6</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>New_Annual_kWh__c</fullName>
        <inlineHelpText>This is the new annual kwh that the UAS will have once this SO is effective.</inlineHelpText>
        <label>New Annual kWh</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Transfer</fullName>
                </value>
                <value>
                    <fullName>Cancellation</fullName>
                </value>
                <value>
                    <fullName>Shared Solar System Update</fullName>
                </value>
                <value>
                    <fullName>Resize</fullName>
                </value>
                <value>
                    <fullName>Initial</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Utility_Account_Subscription__c</fullName>
        <label>Utility Account Subscription</label>
        <referenceTo>Utility_Account_Subscription__c</referenceTo>
        <relationshipLabel>Subscription Orders</relationshipLabel>
        <relationshipName>Subscription_Orders</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Subscription Order</label>
    <nameField>
        <displayFormat>SO-{00000}</displayFormat>
        <label>Subscription Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscription Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Utility_Account_Log__c.object
<CustomObject>
    <fields>
        <fullName>Date_Utility_Account_Cancelled__c</fullName>
        <inlineHelpText>Triggers all related UAS&apos;s to go to Inactive; Creates Partner Support case to fill capacity</inlineHelpText>
        <label>Date Utility Account Cancelled</label>
        <type>Date</type>
    </fields>
    <label>Utility Account Log</label>
    <nameField>
        <label>Utility Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Account Logs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Utility_Account_Subscription__c.object
<CustomObject>
    <fields>
        <fullName>Date_Removed_from_Project__c</fullName>
        <inlineHelpText>Populated with Date Allocation Schedule Retired by Utility when &quot;Date Allocation Schedule Retired by Utility&quot; on all related Allocation Schedule Subscriptions is populated AND Date Utility Account Cancelled is NOT populated</inlineHelpText>
        <label>Date Removed from Project</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Future_Customer_Subscription_KWDC_Rollup__c</fullName>
        <inlineHelpText>This is a rollup of all approved subscription orders.</inlineHelpText>
        <label>Future Customer Subscription (KW DC)</label>
        <summarizedField>Subscription_Order__c.Approved_Change_in_Subscription__c</summarizedField>
        <summaryFilterItems>
            <field>Subscription_Order__c.Approval_Status__c</field>
            <operation>equals</operation>
            <value>Approved</value>
        </summaryFilterItems>
        <summaryForeignKey>Subscription_Order__c.Utility_Account_Subscription__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Next_Schedule_Z_Status__c</fullName>
        <defaultValue>&quot;Active Subscription&quot;</defaultValue>
        <inlineHelpText>Controls whether this subscription should be added to future Allocation Schedules. Select &apos;Active Subscription&apos; to include it, or &apos;Inactive Subscription&apos; to exclude it.</inlineHelpText>
        <label>Next Allocation Schedule Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active Subscription</fullName>
                    <default>true</default>
                    <label>Active Subscription</label>
                </value>
                <value>
                    <fullName>Inactive Subscription</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subscription_Type__c</fullName>
        <description>This is the Customer Subscription Type field from the Product assigned to the Opportunity the UAS is for. It determines if the UAS should use the Annual kWh of Annual Cost fields for sizing, and is used by a validation rule to prevent the wrong sizing fields from being used.</description>
        <formula>TEXT(Opportunity__r.Product__r.Customer_Subscription_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>This is the Customer Subscription Type field from the Product assigned to the Opportunity the UAS is for. Determines if the Annual kWh or the Annual Cost fields should be used, and is used by a validation rule to prevent usage of the wrong sizing fields.</inlineHelpText>
        <label>Subscription Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transferring_Subsc_to_Another_UAS__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Transferring Subsc. to Another UAS</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Utility_Account_Log__c</fullName>
        <inlineHelpText>The related UAL</inlineHelpText>
        <label>Utility Account Log</label>
        <referenceTo>Utility_Account_Log__c</referenceTo>
        <relationshipLabel>Utility Account Subscriptions</relationshipLabel>
        <relationshipName>Utility_Account_Subscriptions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Utility Account Subscription</label>
    <nameField>
        <label>Utility Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Account Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/UtilityAccountSubscriptions.cls
/*************************************************************************************
 * Created By: peteryao on 1/12/19  
 * Description: Could be extend the fflib_SObjectDomain class
 * Tested By: CSCancellationServiceTest
 *************************************************************************************/

@SuppressWarnings('PMD.ApexCRUDViolation')
public inherited sharing class UtilityAccountSubscriptions {
    public List<Utility_Account_Subscription__c> records;
    @TestVisible
    private static SubscriptionManagementService subscriptionSerivce = new SubscriptionManagementService();
    @TestVisible
    private static FeatureService featureService = new FeatureService();

    public UtilityAccountSubscriptions(List<Utility_Account_Subscription__c> sObjectList) {
        records = sObjectList;
    }

    public void removeFromNextScheduleZ() {
        for (Utility_Account_Subscription__c uas : records) {
            uas.Next_Schedule_Z_Status__c = 'Inactive Subscription';
        }
        update records;
    }

    public void registerSubscriptionOrdersToZeroOutUAS(String zeroType, fflib_SObjectUnitOfWork uow) {
        for (Utility_Account_Subscription__c uas : records) {
            if (uas.Future_Customer_Subscription_KWDC_Rollup__c == 0) {
                // This is already zeroed, so it doesn't need another SO
                continue;
            }
            Subscription_Order__c zeroedSO = new Subscription_Order__c(
                Type__c = zeroType,
                Approval_Status__c = 'Approved',
                Effective_Date__c = System.now(),
                Utility_Account_Subscription__c = uas.Id,
                Comments__c = 'Subscription Order was created to zero out UAS'
            );
            if (uas.Subscription_Type__c == 'kWh') {
                zeroedSO.New_Annual_kWh__c = 0;
            } else {
                zeroedSO.New_Annual_Cost__c = 0;
            }
            uow.registerNew(zeroedSO);
        }
    }

    public void handleFinaledAccounts() {
        for (Utility_Account_Subscription__c uas : records) {
            uas.Next_Schedule_Z_Status__c = 'Inactive Subscription';
            uas.Date_Removed_from_Project__c = uas.Utility_Account_Log__r.Date_Utility_Account_Cancelled__c;
            // When we mark a utility account as finaled, we set it to transferring by default to pause the cancellation
            // process. Otherwise, this may trigger the opportunity to go to Cancelled and the Account CS Status to go to Closed.
            uas.Transferring_Subsc_to_Another_UAS__c = true;
        }
        update records;
    }

    public static List<Utility_Account_Subscription__c> getUASesForManuallyCancelledAccounts(Map<Id, Account> triggerNewMap, Map<Id, Account> triggerOldMap) {
        List<Id> accountsCancelled = new List<Id>();
        List<Utility_Account_Subscription__c> uasesToMarkInactive = new List<Utility_Account_Subscription__c>();
        for (Id newAccountId : triggerNewMap.keySet()) {
            if (triggerOldMap.get(newAccountId).Cancellation_Request_Date__c == null &&
                triggerNewMap.get(newAccountId).Cancellation_Request_Date__c != null) {
                accountsCancelled.add(newAccountId);
            }
        }

        if (accountsCancelled.isEmpty()) {
            return uasesToMarkInactive;
        }

        uasesToMarkInactive = UASSelector.selectUASesByAccounts(new Set<Id>(accountsCancelled));
        return uasesToMarkInactive;
    }
}