src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Additional_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>CS Bills and payment transaction errors will be sent to this contact&apos;s email address</inlineHelpText>
        <label>Additional Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts (Additional Contact)</relationshipLabel>
        <relationshipName>AdditionalContact</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Parent_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Lookup to Parent Account</inlineHelpText>
        <label>Parent Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Properties</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Send_Bills_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Send Bills Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Property</fullName>
        <active>true</active>
        <label>Property</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Account_Bill__c.object
<CustomObject>
    <fields>
        <fullName>Bill_Attach_Document__c</fullName>
        <inlineHelpText>Used in CS customer portal for link to file</inlineHelpText>
        <label>Bill Attach Document</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bill_Attach_Version__c</fullName>
        <inlineHelpText>Used in CS Invoice Email - Attachment must be a content version ID</inlineHelpText>
        <label>Bill Attach Version</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bill_Number__c</fullName>
        <label>Bill Number</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Parent_Account__c</fullName>
        <label>Property Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Bills</relationshipLabel>
        <relationshipName>Account_Bills</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Published__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Published</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Ready_for_Email_Send__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Ready for Email Send</label>
        <type>Checkbox</type>
    </fields>
    <label>Account Bill</label>
    <nameField>
        <label>Account Bill Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Bills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Parent_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/BatchCSBillEmailHandlerTest.cls
@isTest
private class BatchCSBillEmailHandlerTest {
    // Can't use @testSetup since we need to use SeeAllData=true to exercise CommunityAPI. Otherwise, we get:
    // System.UnsupportedOperationException: ConnectApi methods are not supported in data siloed tests. Please use @IsTest(SeeAllData=true).
    private static void setupTestData(){
        Integer i;
        List<Account_Bill__c> abList = new List<Account_Bill__c>();

        Account parentAccount = new Account ( Name = 'Parent Account');
        insert parentAccount;

        Account propertyAccount = new Account ( Name = 'Property Account',
                                                Parent_Account__c = parentAccount.Id);
        insert propertyAccount;

        Contact contactOne = new Contact (  FirstName = 'First',
                                            LastName = 'Last',
                                            AccountId = parentAccount.Id,
                                            Email = 'jpentaleri@bluewavesolar.com');
        insert contactOne;


        Contact contactTwo = new Contact (  FirstName = 'First',
                                            LastName = 'Second',
                                            AccountId = parentAccount.Id,
                                            Email = 'pentalerij@gmail.com');
        insert contactTwo;

        propertyAccount.Send_Bills_Contact__c = contactOne.Id;
        propertyAccount.Additional_Contact__c = contactTwo.Id;
        update propertyAccount;

        for (i=0;i<9;i++) {
            Account_Bill__c abOne = new Account_Bill__c (
                                        Name = 'Bill' + i,
                                        Bill_Number__c = i,
                                        Parent_Account__c = propertyAccount.Id,
                                        Ready_for_Email_Send__c = true,
                                        Published__c = false);
            abList.add(abOne);
        }
        insert abList;
    }

    @IsTest(SeeAllData=true)
    static void testSendEmails () {
        setupTestData();
        Test.StartTest();

        InvocableCSBillEmailBatchSend.sendEmails();

        Test.StopTest();

        AsyncApexJob job = [
            SELECT Id, Status, NumberOfErrors,
                JobItemsProcessed,
                TotalJobItems, CreatedBy.Email
            FROM AsyncApexJob
            WHERE Id =: BatchCSBillEmailHandler.batchJobId
        ];

        System.assertEquals(0, job.NumberOfErrors);
        System.assertEquals('Completed', job.Status);
        System.assertEquals(1, job.TotalJobItems);
        // There might be more than 9 emails since SeeAllData is true
        System.assertEquals(true, MessagingService.emailsSent.size() >= 9);
    }

    @isTest
    static void testAccountBillsPublishedWithoutEmails() {
        List<Account_Bill__c> abList = new List<Account_Bill__c>();

        Account parentAccount = new Account ( Name = 'Parent Account');
        insert parentAccount;

        Account propertyAccount = new Account ( Name = 'Property Account',
            Parent_Account__c = parentAccount.Id);
        insert propertyAccount;

        Contact contactOne = new Contact (  FirstName = 'First',
            LastName = 'Last',
            AccountId = parentAccount.Id);
        insert contactOne;


        Contact contactTwo = new Contact (  FirstName = 'First',
            LastName = 'Second',
            AccountId = parentAccount.Id,
            Email = 'pentalerij@gmail.com');
        insert contactTwo;

        propertyAccount.Send_Bills_Contact__c = contactOne.Id;
        propertyAccount.Additional_Contact__c = contactTwo.Id;
        update propertyAccount;

        TestFactory.insertBWAddress();

        for (Integer i=0;i<9;i++) {
            Account_Bill__c abOne = new Account_Bill__c (
                Name = 'Bill' + i,
                Bill_Number__c = i,
                Parent_Account__c = propertyAccount.Id,
                Ready_for_Email_Send__c = true,
                Published__c = false);
            abList.add(abOne);
        }
        insert abList;
        Set<Id> abIds = new Set<Id>{};
        for (Account_Bill__c accountBill : abList) {
            abIds.add(accountBill.Id);
        }

        Test.StartTest();

        InvocableCSBillEmailBatchSend.sendEmails();

        Test.StopTest();

        List<Account_Bill__c> accountBills = [
            SELECT Id, Published__c, Ready_for_Email_Send__c
            FROM Account_Bill__c
            WHERE Id IN : abIds
        ];

        for (Account_Bill__c accountBill : accountBills) {
            System.assert(accountBill.Published__c);
        }
    }

    @IsTest(SeeAllData=true)
    static void testCreateLink() {
        setupTestData();
        Test.startTest();
        ContentVersion csBillCV = new ContentVersion (Title ='Cole\'s Coffee August 2017 Community Solar Bill.pdf',
                                                      PathOnClient='/Community Solar Bill.pdf' );
        csBillCV.VersionData = Blob.valueOf('This is the body of the pdf');
        Util.insertSObj(csBillCV);
        ContentVersion testContent = [  SELECT ContentDocumentId 
                                        FROM ContentVersion 
                                        WHERE Id = : csBillCV.Id]; 

        Account_Bill__c accountBill = [
            SELECT Id, Name
            FROM Account_Bill__c
            WHERE Bill_Number__c != NULL
            LIMIT 1
        ];

        ContentDocumentLink newLink = new ContentDocumentLink ( ContentDocumentId = testContent.ContentDocumentId,
                                                                LinkedEntityId = accountBill.Id,
                                                                ShareType = 'V' );
        insert newLink;
        Test.stopTest();

        Account_Bill__c abUpdated = [   SELECT Id, Bill_Attach_Version__c, Bill_Attach_Document__c
                                        FROM Account_Bill__c 
                                        WHERE Id = : accountBill.Id];
        System.assertNotEquals('', abUpdated.Bill_Attach_Version__c);
        System.assertNotEquals('', abUpdated.Bill_Attach_Document__c);
    }

}