src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Zuora_Id__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>Set by ZuoraAccountService after it creates the account in Zuora from a converted lead</inlineHelpText>
        <label>Zuora Id</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Customer_Group__c</fullName>
        <label>Customer Group</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Residential</fullName>
                </value>
                <value>
                    <fullName>Non-Residential</fullName>
                    <default>true</default>
                    <label>Non-Residential</label>
                </value>
                <value>
                    <fullName>Anchor</fullName>
                </value>
                <value>
                    <fullName>Business</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Schedule_Z_Subscription__c.object
<CustomObject>
    <fields>
        <fullName>Utility_Account_Subscription__c</fullName>
        <label>Utility Account Subscription</label>
        <referenceTo>Utility_Account_Subscription__c</referenceTo>
        <relationshipName>Schedule_Z_Subscriptions</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Allocation Schedule Subscription</label>
    <nameField>
        <displayFormat>ALSS-{0000}</displayFormat>
        <label>Allocation Schedule Subscription Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Allocation Schedule Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/UASB__c.object
<CustomObject
     >
    <description n1:nil="true" />
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Utility Account Subscription Bills (Account)</relationshipLabel>
        <relationshipName>Utility_Account_Subscription_Bills1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Billing_Method__c</fullName>
        <inlineHelpText>Blank unless the UASB is billed via UCB.</inlineHelpText>
        <label>Billing Method</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>UCB</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Ending_Banked_Credits__c</fullName>
        <label>Ending Banked Credits</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Externally_Serviced__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If checked, UASB is billed by RadianGen. Bill will NOT be sent to customer</inlineHelpText>
        <label>Externally Serviced</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Utility Account Subscription Bills</relationshipLabel>
        <relationshipName>Utility_Account_Subscription_Bills</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ready_For_Production_Detail__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Only externally serviced UASBs get marked with this checkbox on insertion, to be caught by production detail creation scheduled job</inlineHelpText>
        <label>Ready For Production Detail</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Schedule_Z_Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Allocation Schedule Subscription this bill was created with.</description>
        <label>Allocation Schedule Subscription</label>
        <referenceTo>Schedule_Z_Subscription__c</referenceTo>
        <relationshipLabel>Utility Account Subscription Bills</relationshipLabel>
        <relationshipName>Utility_Account_Subscription_Bills</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subscription_Production_kWh_Static__c</fullName>
        <label>Subscription Production (kWh) Static</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Utility_Account_Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Utility Account Subscription</label>
        <referenceTo>Utility_Account_Subscription__c</referenceTo>
        <relationshipLabel>Utility Account Subscription Bills</relationshipLabel>
        <relationshipName>Utility_Account_Subscription_Bills</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora_Id__c</fullName>
        <label>Zuora Id</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <label>Utility Account Subscription Bill</label>
    <nameField>
        <displayFormat>UASB-{0000000}</displayFormat>
        <label>Utility Account Subscription Bill Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Utility Account Subscription Bills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Utility_Account_Log__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Utility Account Logs</relationshipLabel>
        <relationshipName>Utility_Account_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Annual_Cost_of_Electricity__c</fullName>
        <description>This is used for the SREC CS Product sizing. It is the total dollar amount a customer spends annually on their electric utility bill for this account. It is initially filled in with an estimate from the customer/partner during the CS application process, then filled in by Ops with the QCed amount.</description>
        <inlineHelpText>Used for SREC CS Product sizing. It&apos;s the total dollar amount spent annually on the electric utility bill. It is initially filled in with an estimate from the customer/partner during the CS application process, then filled in by Ops with the QCed amount.</inlineHelpText>
        <label>Annual Cost of Electricity</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Name_on_Account__c</fullName>
        <label>Name on Utility Account</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Utility Account Logs</relationshipLabel>
        <relationshipName>Utility_Account_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subscribed_Annual_Cost_of_Electricity__c</fullName>
        <description>Used for SREC CS Product sizing. It&apos;s the sum of the Annual Cost of Electricity (future) field on all related Utility Account Subscriptions.</description>
        <inlineHelpText>Used for SREC CS Product sizing. It&apos;s the sum of the Annual Cost of Electricity (future) field on all related Utility Account Subscriptions.</inlineHelpText>
        <label>xxSubscribed Annual Cost of Electricity</label>
        <summarizedField>Utility_Account_Subscription__c.Subscribed_Annual_Cost_of_Electricity__c</summarizedField>
        <summaryFilterItems>
            <field>Utility_Account_Subscription__c.Next_Schedule_Z_Status__c</field>
            <operation>equals</operation>
            <value>Active Subscription</value>
        </summaryFilterItems>
        <summaryForeignKey>Utility_Account_Subscription__c.Utility_Account_Log__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Utility Account Log</label>
    <nameField>
        <label>Utility Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Account Logs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Utility_Account_Subscription__c.object
<CustomObject>
    <fields>
        <fullName>Annual_Cost_of_Electricity__c</fullName>
        <description>Total cost of electricity at the UAL level.</description>
        <label>Full Annual Cost of Electricity</label>
        <precision>9</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Customer_Group__c</fullName>
        <formula>Text(Opportunity__r.Customer_Group__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Customer Group</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Externally_Serviced__c</fullName>
        <formula>IF (  
 ISPICKVAL( Externally_Serviced_Override__c , &quot;&quot;),

IF (  
 AND( 
  OR (
    ISPICKVAL(Opportunity__r.Customer_Sub_Group__c, &quot;Public Offtake&quot;),
    ISPICKVAL(Opportunity__r.Customer_Group__c, &quot;Anchor&quot;)
  ),
   
   IF(
     $CustomMetadata.Custom_Feature_Enablement__mdt.Subscription_Orders.Feature_is_Enabled__c=true,
      AND(
       NOT(ISPICKVAL(Shared_Solar_System__r.Billing_Anchors__c, &quot;&quot;)),
       NOT(ISPICKVAL(Shared_Solar_System__r.Billing_Anchors__c, &quot;BlueWave&quot;))
          ),

   AND(
    NOT(ISPICKVAL(Opportunity__r.Shared_Solar_System__r.Billing_Anchors__c, &quot;&quot;)),
    NOT(ISPICKVAL(Opportunity__r.Shared_Solar_System__r.Billing_Anchors__c, &quot;BlueWave&quot;))
  )
      )
 ),
TRUE, FALSE),

IF (
 ISPICKVAL( Externally_Serviced_Override__c , &quot;Externally Serviced&quot;), true, false)

)</formula>
        <inlineHelpText>Checked if subscription is billed by RadianGen</inlineHelpText>
        <label>Externally Serviced</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Name_on_Account__c</fullName>
        <description>Customer&apos;s name on their electric bill</description>
        <label>Name on Account</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Next_Schedule_Z_Status__c</fullName>
        <defaultValue>&quot;Active Subscription&quot;</defaultValue>
        <inlineHelpText>Controls whether this subscription should be added to future Allocation Schedules. Select &apos;Active Subscription&apos; to include it, or &apos;Inactive Subscription&apos; to exclude it.</inlineHelpText>
        <label>Next Allocation Schedule Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active Subscription</fullName>
                    <default>true</default>
                    <label>Active Subscription</label>
                </value>
                <value>
                    <fullName>Inactive Subscription</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Utility Account Subscriptions</relationshipLabel>
        <relationshipName>Utility_Account_Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subscribed_Annual_Cost_of_Electricity__c</fullName>
        <description>Used for SREC CS contracts. Check the Subscription Type to see if this fields should be used. It is used to calculate the future customer subscription kW DC field for Opportunities with the SREC CS Product. It is populated manually.</description>
        <inlineHelpText>Used for SREC CS contracts. Check the Subscription Type to see if this fields should be used. It is used to calculate the future customer subscription kW DC field for Opportunities with the SREC CS Product. It is populated manually.</inlineHelpText>
        <label>xxAnnual Cost of Electricity (Future)</label>
        <precision>16</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Utility_Account_Log__c</fullName>
        <inlineHelpText>The related UAL</inlineHelpText>
        <label>Utility Account Log</label>
        <referenceTo>Utility_Account_Log__c</referenceTo>
        <relationshipLabel>Utility Account Subscriptions</relationshipLabel>
        <relationshipName>Utility_Account_Subscriptions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>calculated_annual_cost_of_electricity__c</fullName>
        <defaultValue>0</defaultValue>
        <description>The Minimum of Total UAL Cost and Maximum SSS Cost. (As more UAS are created, UAL Cost is deducted)</description>
        <label>Calculated Annual Cost of Electricity</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Utility Account Subscription</label>
    <nameField>
        <label>Utility Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Account Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/UASBSelectorTest.cls
@IsTest
public class UASBSelectorTest {
    @TestSetup public static void setupTestData() {
        // Disable triggers so that we don't have to populate client account, sss, entity when inserting UASes and UASBs:
        Util.disableTrigger('Disable_Client_Objects_Trigger__c');
        Util.disableTrigger('Disable_UASBTrigger__c');

        String firstName1 = 'Ashley';
        String lastName1 = 'Smith';
        String accountName1 = firstName1 + ' ' + lastName1;

        Account propAccount1 = new Account(
            Name = accountName1);
        insert propAccount1;

        Utility_Account_Log__c ualog1 = new Utility_Account_Log__c(
            Name = '0000234',
            Account__c = propAccount1.Id,
            Annual_Cost_of_Electricity__c = 10000,
            Name_on_Account__c = accountName1);
        insert ualog1;

        Opportunity opportunity1 = new Opportunity(
            Name = accountName1,
            AccountId = propAccount1.Id,
            StageName = 'Complete',
            Customer_Group__c = 'Residential',
            CloseDate = System.today());
        insert opportunity1;

        Utility_Account_Subscription__c uas1 = new Utility_Account_Subscription__c(
            Name = '0000234',
            Utility_Account_Log__c = ualog1.Id,
            Opportunity__c = opportunity1.Id,
            Next_Schedule_Z_Status__c = 'Active Subscription',
            calculated_annual_cost_of_electricity__c = 1400,
            Subscribed_Annual_Cost_of_Electricity__c = 1400
        );
        insert uas1;
    }

    @IsTest public static void testGetUASBsFromExternalIds() {
        List<Utility_Account_Subscription__c> uasList = [
            SELECT Id, Opportunity__r.AccountId
            FROM Utility_Account_Subscription__c
        ];

        UASB__c billOne = new UASB__c(
            Account__c = uasList[0].Opportunity__r.AccountId,
            Zuora_Id__c = 'bbb1230005',
            Utility_Account_Subscription__c = uasList[0].Id
        );
        UASB__c billTwo = new UASB__c(
            Account__c = uasList[0].Opportunity__r.AccountId,
            Zuora_Id__c = 'bbb1230001',
            Utility_Account_Subscription__c = uasList[0].Id
        );
        UASB__c billThree = new UASB__c(
            Account__c = uasList[0].Opportunity__r.AccountId,
            Zuora_Id__c = 'bbb1230001',
            Utility_Account_Subscription__c = uasList[0].Id
        );
        insert new List<UASB__c>{billOne, billTwo, billThree};

        UASBSelector selector = new UASBSelector();
        Map<String,List<UASB__c>> billMap = selector.getUASBMapFromExternalIds(new Set<String>{
            'bbb1230001', 'bbb1230004', 'bbb1230005'
        });
        List<UASB__c> billListOne = billMap.get('bbb1230001');
        List<UASB__c> billListTwo = billMap.get('bbb1230005');

        System.assertEquals(2,billListOne.size());
        System.assertEquals(1,billListTwo.size());
    }

    @IsTest
    public static void testSelectAggregateAnchorUASBs(){
        Opportunity anchorOpp = [
            SELECT Id, Customer_Group__c
            FROM Opportunity
            LIMIT 1
        ];
        anchorOpp.Customer_Group__c = 'Anchor';
        update anchorOpp;

        Utility_Account_Subscription__c anchorUAS = [
            SELECT Id, Opportunity__r.AccountId
            FROM Utility_Account_Subscription__c
            LIMIT 1
        ];

        Date billDate = System.today();

        UASB__c billOne = new UASB__c(
            Account__c = anchorUAS.Opportunity__r.AccountId,
            Utility_Account_Subscription__c = anchorUAS.Id,
            Date__c = billDate.addMonths(-13),
            Subscription_Production_kWh_Static__c = 100
        );
        UASB__c billTwo = new UASB__c(
            Account__c = anchorUAS.Opportunity__r.AccountId,
            Utility_Account_Subscription__c = anchorUAS.Id,
            Date__c = billDate.addMonths(-13),
            Subscription_Production_kWh_Static__c = 100
        );
        UASB__c billThree = new UASB__c(
            Account__c = anchorUAS.Opportunity__r.AccountId,
            Utility_Account_Subscription__c = anchorUAS.Id,
            Date__c = billDate.addMonths(-13),
            Subscription_Production_kWh_Static__c = 100
        );
        insert new List<UASB__c>{billOne, billTwo, billThree};
        UASBSelector uasbSelector = new UASBSelector();
        List<AggregateResult> results = uasbSelector.selectAggregateAnchorUASBs();

        System.assertNotEquals(null, results);
        for (AggregateResult result : results) {
            System.assertEquals(300, result.get('productionSummary'));
        }

    }

    @IsTest public static void testGetUnservicedWithoutProductionDetail(){
        List<Utility_Account_Subscription__c> uasList = [
            SELECT Id, Opportunity__r.AccountId
            FROM Utility_Account_Subscription__c
        ];

        // On insert, Ready_for_Production_Detail__c is set to true if Externally Serviced = true
        Util.enableTrigger('Disable_UASBTrigger__c');

        UASB__c billOne = new UASB__c(
            Account__c = uasList[0].Opportunity__r.AccountId,
            Externally_Serviced__c = true,
            Utility_Account_Subscription__c = uasList[0].Id
        );
        UASB__c billTwo = new UASB__c(
            Account__c = uasList[0].Opportunity__r.AccountId,
            Externally_Serviced__c = true,
            Utility_Account_Subscription__c = uasList[0].Id
        );
        UASB__c billThree = new UASB__c(
            Account__c = uasList[0].Opportunity__r.AccountId,
            Externally_Serviced__c = false,
            Utility_Account_Subscription__c = uasList[0].Id
        );
        insert new List<UASB__c>{billOne, billTwo, billThree};

        billOne.Ready_For_Production_Detail__c = true;
        billTwo.Ready_For_Production_Detail__c = true;
        billThree.Ready_For_Production_Detail__c = true;
        update new List<UASB__c>{billOne, billTwo, billThree};

        UASBSelector selector = new UASBSelector();
        List<UASB__c> uasbList = selector.getUnservicedWithoutProductionDetail(5);

        System.assertEquals(2,uasbList.size());
    }

    @IsTest
    public static void testDeleteUASBs() {
        List<Utility_Account_Subscription__c> uasList = [
            SELECT Id, Opportunity__r.AccountId
            FROM Utility_Account_Subscription__c
        ];

        UASB__c uasb = new UASB__c(
            Account__c = uasList[0].Opportunity__r.AccountId,
            Externally_Serviced__c = true,
            Zuora_Id__c = 'aaa1230002',
            Utility_Account_Subscription__c = uasList[0].Id
        );
        insert uasb;
        Util.enableTrigger('Disable_UASBTrigger__c');

        try {
            delete uasb;
            System.assert(false, 'Expected delete of UASB to throw an error - UASB cannot be deleted when Zuora_Id is populated');
        } catch (Exception e) {
            System.assert(e.getMessage().contains('Oops! This UASB cannot be deleted'), e.getMessage() + '\n' + e.getStackTraceString());
        }
    }

    @IsTest
    private static void testGetLatestUcbUasbBySzs() {
        // Test setup
        UASBSelector selector = new UASBSelector();
        CSPaymentTest.csPaymentSetupTestData();
        Schedule_Z_Subscription__c szs = [
            SELECT Id, Utility_Account_Subscription__c
            FROM Schedule_Z_Subscription__c
            LIMIT 1
        ];
        Utility_Account_Subscription__c uas = [
            SELECT Id, Opportunity__r.AccountId
            FROM Utility_Account_Subscription__c
            WHERE Id =: szs.Utility_Account_Subscription__c
            LIMIT 1
        ];
        UASB__c previousBillOne = new UASB__c(
            Account__c = uas.Opportunity__r.AccountId,
            Externally_Serviced__c = true,
            Utility_Account_Subscription__c = uas.Id,
            Date__c = Date.today().addDays(-1),
            Billing_Method__c = 'UCB',
            Ending_Banked_Credits__c = 100
        );
        UASB__c previousBillTwo = new UASB__c(
            Account__c = uas.Opportunity__r.AccountId,
            Externally_Serviced__c = true,
            Utility_Account_Subscription__c = uas.Id,
            Date__c = Date.today().addDays(-60),
            Billing_Method__c = 'UCB',
            Ending_Banked_Credits__c = 50
        );
        List<UASB__c> previousBills = new List<UASB__c>{previousBillOne, previousBillTwo};
        insert previousBills;

        // Run test
        List<Schedule_Z_Subscription__c> szsList = new List<Schedule_Z_Subscription__c>{szs};
        Map<String,UASB__c> priorUASBMap = selector.getLatestUcbUasbBySzs(szsList);

        // Verify database / system conditions
        String mapKey = new List<String>(priorUASBMap.keySet())[0];
        UASB__c priorUASBResult = priorUASBMap.get(szs.Id);
        System.assertEquals(szs.Id, mapKey, 'Incorrect map key for query return data');
        System.assertEquals(Date.today().addDays(-1), priorUASBResult.Date__c, 'Incorrect Date__c field on UASB');
        System.assertEquals(previousBillOne.Ending_Banked_Credits__c, priorUASBResult.Ending_Banked_Credits__c, 'Wrong ending banked credits');
        System.assertEquals(previousBillOne.Id, priorUASBResult.Id, 'Incorrect prior UASB__c record in map');
    }
}