src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Number__c</fullName>
        <description>CS Account Number</description>
        <displayFormat>BW-{0000000}</displayFormat>
        <label>CS Account Number</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Partner</label>
        <referenceTo>Partner__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Account_Number__c</fullName>
        <formula>Account.Account_Number__c</formula>
        <label>Account Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Related_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Related Opportunity to Case</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shared_Solar_System__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Shared Solar System</label>
        <referenceTo>Shared_Solar_System__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Case</fullName>
        <active>true</active>
        <businessProcess>Customer Care Case</businessProcess>
        <label>Case</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Commission_Payment__c.object
<CustomObject>
    <fields>
        <fullName>Amount_Due__c</fullName>
        <label>Amount Due</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Commission_Structure__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Commission Structure</label>
        <referenceTo>Commission_Structure__c</referenceTo>
        <relationshipLabel>Commission Payments</relationshipLabel>
        <relationshipName>Commission_Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Commission_Type__c</fullName>
        <label>Commission Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Contract Execution</fullName>
                </value>
                <value>
                    <fullName>First Bill Sent</fullName>
                </value>
                <value>
                    <fullName>First Bill Paid</fullName>
                </value>
                <value>
                    <fullName>Cancellation/Refund</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Invoice__c</fullName>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Commission Payments</relationshipLabel>
        <relationshipName>Commission_Payments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Commission Payments</relationshipLabel>
        <relationshipName>Commission_Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Commission Payment</label>
    <nameField>
        <label>Commission Payment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Commission Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Commission_Structure__c.object
<CustomObject>
    <fields>
        <fullName>Cents_kW_DC_Up_Front__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Enter the cents per kW DC the partner receives up front, after full contract execution.</description>
        <inlineHelpText>Enter the cents per kW DC the partner receives up front, after full contract execution.</inlineHelpText>
        <label>Cents/kW DC Contract Execution</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Partner_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Partner Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Commission Structures</relationshipLabel>
        <relationshipName>Commission_Structures</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Partner</label>
        <referenceTo>Partner__c</referenceTo>
        <relationshipLabel>Commission Structures</relationshipLabel>
        <relationshipName>Commission_Structures</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Commission Structures</relationshipLabel>
        <relationshipName>Commission_Structures</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Commission Structure</label>
    <nameField>
        <label>Commission Structure Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Commission Structures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to relate multiple Client Contracts to a single opportunity</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This is used for customer contracts to show the product and contract that was used.</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Invoice__c.object
<CustomObject>
    <description>Zuora Invoice object. Invoices are bills that you send to customers.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Related Client Account for Client Invoices, or a partner account</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner</label>
    <referenceTo>Partner__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>CS_Capacity_Allocated__c</fullName>
        <inlineHelpText>Sum of Future Customer Subscription (KW DC) on Utility Account Subscriptions when Opportunity is set to Complete. Used in Docusign.</inlineHelpText>
        <label>Customer Subscription kW DC at Complete</label>
        <precision>9</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Commission_Structure__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Commission Structure</label>
        <referenceTo>Commission_Structure__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Partner_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Relates Opportunities to the Partner Account. Note that this is different from the Partner Object.</description>
        <inlineHelpText>Relates Opportunities to the Partner Account. Note that this is different from the Partner Object.</inlineHelpText>
        <label>Partner Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities (Partner Account)</relationshipLabel>
        <relationshipName>Opportunities2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Partner_tag_lookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Partner</label>
        <referenceTo>Partner__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shared_Solar_System__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>To change this system, use the Change SSS quick action</inlineHelpText>
        <label>Shared Solar System</label>
        <referenceTo>Shared_Solar_System__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Unique_ID__c</fullName>
        <label>Unique ID</label>
        <length>45</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Partner__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Link to partner or client account</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Partners</relationshipLabel>
        <relationshipName>Partners</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Commission_Structure__c</fullName>
        <label>Commission Structure</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <label>Partner</label>
    <nameField>
        <label>Partner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partners</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Partner_Shared_Solar_System_Eligibility__c.object
<CustomObject>
    <description>Control partner access to Shared Solar Systems</description>
    <fields>
        <fullName>Account__c</fullName>
        <inlineHelpText>Partner Account</inlineHelpText>
        <label>Partner Account</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The Account must have a record type of Partner Account</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Partner Account</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Shared Solar Systems</relationshipLabel>
        <relationshipName>Partner_Shared_Solar_System_Accesses</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Commission_Structure__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Commission Structure that applies when a partner acquires customers for this Shared Solar System</inlineHelpText>
        <label>Commission Structure</label>
        <referenceTo>Commission_Structure__c</referenceTo>
        <relationshipLabel>Partner Shared Solar System</relationshipLabel>
        <relationshipName>Partner_Shared_Solar_System_Accesses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shared_Solar_System__c</fullName>
        <inlineHelpText>Shared Solar System that the partner is eligible to sell</inlineHelpText>
        <label>Shared Solar System</label>
        <referenceTo>Shared_Solar_System__c</referenceTo>
        <relationshipLabel>Eligible Partners</relationshipLabel>
        <relationshipName>Partner_Shared_Solar_System_Accesses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Partner Shared Solar System Access</label>
    <nameField>
        <displayFormat>PSSA-{0000}</displayFormat>
        <label>Partner Shared Solar System Access Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Shared Solar System Accesses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Shared_Solar_System__c.object
<CustomObject
     >
    <articleTypeChannelDisplay n1:nil="true" />
    <customSettingsType n1:nil="true" />
    <description n1:nil="true" />
    <eventType n1:nil="true" />
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Primary customer product.</inlineHelpText>
        <label>Default Enrollment Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Shared Solar Systems</relationshipLabel>
        <relationshipName>Shared_Solar_Systems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Unique_ID__c</fullName>
        <displayFormat>SSS-{000000}</displayFormat>
        <externalId>true</externalId>
        <label>Unique ID</label>
        <type>AutoNumber</type>
    </fields>
    <gender n1:nil="true" />
    <household>false</household>
    <label>Shared Solar System</label>
    <nameField>
        <label>Shared Solar System Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shared Solar Systems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <startsWith n1:nil="true" />
</CustomObject>

src/classes/PartnerCommissionServiceTest.cls
@IsTest
@SuppressWarnings('PMD.AvoidHardcodingId')
public class PartnerCommissionServiceTest {

    @IsTest
    private static void testContractExecution(){
        useMocks();
        PartnerCommissionService.PendingCommission pendingComm = new PartnerCommissionService.PendingCommission();
        pendingComm.opportunitiesToRun = getOpportunityMockForContractExecutionType();
        pendingComm.typeOfCommission = PartnerCommissionService.CommissionType.CONTRACTEXECUTION;

        /*
            10 Opportunities total:

            1 Opportunity is assigned a different Partner that does not have a Partner_Shared_Solar_System_Eligibility__c
            Will result in a case because Partner does not have access to Shared Solar System

            1 Opportunity is assigned a different SSS that has a Partner_Shared_Solar_System_Eligibility__c
            with a different Commission Structure.

            2 opportunities already have pending payments (which should update instead of insert)
            1 opportunity already has CS_Capacity_Allocated__c populated and should not be updated
        */

        Test.startTest();
        fflib_SObjectUnitOfWork uow = new fflib_SObjectUnitOfWork(
            new List<SObjectType> {
                Opportunity.SObjectType,
                Commission_Payment__c.SObjectType,
                Case.SObjectType
            }
        );
        PartnerCommissionService service = new PartnerCommissionService();
        service.calculateCommissionRecords(pendingComm, uow);
        Test.stopTest();

        List<Opportunity> opportunitiesToUpdate = (List<Opportunity>)
            FFLibHelperTest.getRegisterDirtyListFromUnitOfWork(uow, 'Opportunity');
        List<Case> casesToInsert = (List<Case>)
            FFLibHelperTest.getRegisterNewListFromUnitOfWork(uow, 'Case');
        List<Commission_Payment__c> commissionPaymentRecordsToInsert = (List<Commission_Payment__c>)
            FFLibHelperTest.getRegisterNewListFromUnitOfWork(uow, 'Commission_Payment__c');
        List<Commission_Payment__c> commissionPaymentRecordsToUpdate = (List<Commission_Payment__c>)
            FFLibHelperTest.getRegisterDirtyListFromUnitOfWork(uow, 'Commission_Payment__c');

        System.debug(LoggingLevel.ERROR, JSON.serialize(opportunitiesToUpdate));
        System.assertEquals(9,opportunitiesToUpdate.size());
        System.assertEquals(1,casesToInsert.size());
        System.assertEquals(7,commissionPaymentRecordsToInsert.size());
        System.assertEquals(2,commissionPaymentRecordsToUpdate.size());

        Boolean containsOpp = false;
        for (Commission_Payment__c payment : commissionPaymentRecordsToInsert){
            System.assertEquals('Contract Execution',payment.Commission_Type__c);
            System.assert(payment.Amount_Due__c > 0);
            if (payment.Opportunity__c == '0063K000003pyqLQAQ'){
                System.assertNotEquals(1434.564,payment.Amount_Due__c);
                System.assertEquals(1434.56,payment.Amount_Due__c);
                containsOpp = true;
            }
        }
        System.assert(containsOpp);

        Integer countOfNullCommissionStructure = 0;
        for (Opportunity opp : opportunitiesToUpdate){
            System.assertNotEquals(null,opp.CS_Capacity_Allocated__c);
            if (opp.Commission_Structure__c == null){
                countOfNullCommissionStructure += 1;
            }
            if (opp.Id == '0063K000003pyqPQAQ') {
                System.assertEquals(15, opp.CS_Capacity_Allocated__c, 'CS Capacity Allocated should only be populated once on Status Complete');
            }
        }
        System.assertEquals(1, countOfNullCommissionStructure);

        Case caseToInsert = casesToInsert[0];
        System.assertEquals('Issue with Creation of Commission Payment',caseToInsert.Subject);
        System.assertEquals('0063K000003pyqJQAQ',caseToInsert.Related_Opportunity__c);
    }

    @IsTest
    private static void testFirstBillorPayCommissionPayment() {
        useMocks();
        PartnerCommissionService.PendingCommission pendingComm = new PartnerCommissionService.PendingCommission();
        pendingComm.opportunitiesToRun = getOpportunityMockForBilledType();
        pendingComm.typeOfCommission = PartnerCommissionService.CommissionType.FIRSTBILLPAID;

        System.assertEquals(10,pendingComm.opportunitiesToRun.size());
        fflib_SObjectUnitOfWork uow = new fflib_SObjectUnitOfWork(
            new List<SObjectType> {
                Opportunity.SObjectType,
                Commission_Payment__c.SObjectType,
                Case.SObjectType
            }
        );
        PartnerCommissionService service = new PartnerCommissionService();
        service.calculateCommissionRecords(pendingComm, uow);

        List<Opportunity> opportunitiesToUpdate = (List<Opportunity>)
            FFLibHelperTest.getRegisterDirtyListFromUnitOfWork(uow, 'Opportunity');
        List<Case> casesToInsert = (List<Case>)
            FFLibHelperTest.getRegisterNewListFromUnitOfWork(uow, 'Case');
        List<Commission_Payment__c> commissionPaymentRecordsToInsert = (List<Commission_Payment__c>)
            FFLibHelperTest.getRegisterNewListFromUnitOfWork(uow, 'Commission_Payment__c');
        List<Commission_Payment__c> commissionPaymentRecordsToUpdate = (List<Commission_Payment__c>)
            FFLibHelperTest.getRegisterDirtyListFromUnitOfWork(uow, 'Commission_Payment__c');


        // Only Contract Execution Type should update opportunities, update comm. payments or insert cases:
        System.assertEquals(0,opportunitiesToUpdate.size());
        System.assertEquals(0,casesToInsert.size());
        System.assertEquals(0,commissionPaymentRecordsToUpdate.size());
        System.assertEquals(10,commissionPaymentRecordsToInsert.size());
    }

    @IsTest
    private static void testPartnerInvoiceCreation(){
        PartnerCommissionService service = new PartnerCommissionService();
        Invoice__c partnerInvoice = service.createPartnerInvoice('a0s3K0000006wCMQAY','Partner One', '0013K000006yKHOQA2');
        System.assertEquals('a0s3K0000006wCMQAY',partnerInvoice.Partner__c);
        System.assertEquals(15,partnerInvoice.Due_Date__c.day());
        System.assertEquals('0013K000006yKHOQA2', partnerInvoice.Account__c);
    }

    private static void useMocks() {
        PartnerCommissionService.utilityaccountSelector = (UASSelector) Test.createStub(UASSelector.class, new MockUASSelector());
        PartnerCommissionService.commissionPaySelector = (CommissionPaymentSelector) Test.createStub(CommissionPaymentSelector.class, new MockCommPaySelector());
        PartnerCommissionService.partnerInvoiceSelector = (PartnerInvoiceSelector) Test.createStub(PartnerInvoiceSelector.class, new MockPartnerInvoiceSelector());
    }

    public static List<Opportunity> getOpportunityMockForContractExecutionType(){
        // First opp has a different SSS from the rest (same partner)
        // Second opp has a different Partner from the rest (same SSS)
        String queryData = '[' +
            '{"Id":"0063K000003pyqIQAQ","StageName":"Complete","Name":"Ashley Smith","AccountId":"0013K000006yKHDQA2","Shared_Solar_System__c":"a1J3K0000005hM0UAI","Product__c":"01t3K000000Rb2VQAS","Commission_Structure__c":"a4w3K0000000EMXQA2","Partner_tag_lookup__c":"a0s3K0000006wCRQAY","Partner_Account__c":"0010a00001Ljv4ZAAR","Account":{"Id":"0013K000006yKHDQA2","Account_Number__c":"BW-0035450"},"Commission_Structure__r":{"Id":"a4w3K0000000EMXQA2","Cents_kW_DC_Up_Front__c":0.16},"Shared_Solar_System__r":{"Id":"a1J3K0000005hM0UAI","Unique_ID__c":"SSS-000181", "Name": "Test SSS B"},"Partner_tag_lookup__r": {"Id":"a0s3K0000006wCRQAY","Name":"Test Partner", "Account__c":"0010a00001Ljv4ZAAR"},"Partner_Account__r": {"Id":"0010a00001Ljv4ZAAR","Name":"Test Partner Account"}},' +
            '{"Id":"0063K000003pyqJQAQ","StageName":"Complete","Name":"Steven Ward","AccountId":"0013K000006yKHEQA2","Shared_Solar_System__c":"a1J3K0000005hM1UAI","Product__c":"01t3K000000Rb2VQAS","Commission_Structure__c":null,"Partner_tag_lookup__c":"a0s3K0000006wCMQAY","Partner_Account__c":"0010a00001Ljv4ZAAL","Account":{"Id":"0013K000006yKHEQA2","Account_Number__c":"BW-0035451"},"Shared_Solar_System__r":{"Id":"a1J3K0000005hM1UAI","Unique_ID__c":"SSS-000182", "Name": "Test SSS A"},"Partner_tag_lookup__r": {"Id":"a0s3K0000006wCMQAY","Name":"Test Partner 2", "Account__c":"0010a00001Ljv4ZAAL"},"Partner_Account__r": {"Id":"0010a00001Ljv4ZAAL","Name":"Test Partner Account 2"}},' +
            '{"Id":"0063K000003pyqKQAQ","StageName":"Complete","Name":"Marie Mitchell","AccountId":"0013K000006yKHFQA2","Shared_Solar_System__c":"a1J3K0000005hM1UAI","Product__c":"01t3K000000Rb2VQAS","Commission_Structure__c":"a4w3K0000000EMXQA2","Partner_tag_lookup__c":"a0s3K0000006wCRQAY","Partner_Account__c":"0010a00001Ljv4ZAAR","Account":{"Id":"0013K000006yKHFQA2","Account_Number__c":"BW-0035452"},"Commission_Structure__r":{"Id":"a4w3K0000000EMXQA2","Cents_kW_DC_Up_Front__c":0.16},"Shared_Solar_System__r":{"Id":"a1J3K0000005hM1UAI","Unique_ID__c":"SSS-000182", "Name": "Test SSS A"},"Partner_tag_lookup__r": {"Id":"a0s3K0000006wCRQAY","Name":"Test Partner", "Account__c":"0010a00001Ljv4ZAAR"},"Partner_Account__r": {"Id":"0010a00001Ljv4ZAAR","Name":"Test Partner Account"}},' +
            '{"Id":"0063K000003pyqLQAQ","StageName":"Complete","Name":"Justin Jenkins","AccountId":"0013K000006yKHGQA2","Shared_Solar_System__c":"a1J3K0000005hM1UAI","Product__c":"01t3K000000Rb2UQAS","Commission_Structure__c":"a4w3K0000000EMXQA2","Partner_tag_lookup__c":"a0s3K0000006wCRQAY","Partner_Account__c":"0010a00001Ljv4ZAAR","Account":{"Id":"0013K000006yKHGQA2","Account_Number__c":"BW-0035453"},"Commission_Structure__r":{"Id":"a4w3K0000000EMXQA2","Cents_kW_DC_Up_Front__c":0.1},"Shared_Solar_System__r":{"Id":"a1J3K0000005hM1UAI","Unique_ID__c":"SSS-000182", "Name": "Test SSS A"},"Partner_tag_lookup__r": {"Id":"a0s3K0000006wCRQAY","Name":"Test Partner", "Account__c":"0010a00001Ljv4ZAAR"},"Partner_Account__r": {"Id":"0010a00001Ljv4ZAAR","Name":"Test Partner Account"}},' +
            '{"Id":"0063K000003pyqNQAQ","StageName":"Complete","Name":"Cobie Croft","AccountId":"0013K000006yKHIQA2","Shared_Solar_System__c":"a1J3K0000005hM1UAI","Product__c":"01t3K000000Rb2UQAS","Commission_Structure__c":"a4w3K0000000EMVQA2","Partner_tag_lookup__c":"a0s3K0000006wCRQAY","Partner_Account__c":"0010a00001Ljv4ZAAR","Account":{"Id":"0013K000006yKHIQA2","Account_Number__c":"BW-0035455"},"Commission_Structure__r":{"Id":"a4w3K0000000EMVQA2","Cents_kW_DC_Up_Front__c":0.1},"Shared_Solar_System__r":{"Id":"a1J3K0000005hM1UAI","Unique_ID__c":"SSS-000182", "Name": "Test SSS A"},"Partner_tag_lookup__r": {"Id":"a0s3K0000006wCRQAY","Name":"Test Partner", "Account__c":"0010a00001Ljv4ZAAR"},"Partner_Account__r": {"Id":"0010a00001Ljv4ZAAR","Name":"Test Partner Account"}},' +
            '{"Id":"0063K000003pyqOQAQ","StageName":"Complete","Name":"Ridwan Conner","AccountId":"0013K000006yKHJQA2","Shared_Solar_System__c":"a1J3K0000005hM1UAI","Product__c":"01t3K000000Rb2UQAS","Commission_Structure__c":"a4w3K0000000EMVQA2","Partner_tag_lookup__c":"a0s3K0000006wCRQAY","Partner_Account__c":"0010a00001Ljv4ZAAR","Account":{"Id":"0013K000006yKHJQA2","Account_Number__c":"BW-0035456"},"Commission_Structure__r":{"Id":"a4w3K0000000EMVQA2","Cents_kW_DC_Up_Front__c":0.1},"Shared_Solar_System__r":{"Id":"a1J3K0000005hM1UAI","Unique_ID__c":"SSS-000182", "Name": "Test SSS A"},"Partner_tag_lookup__r": {"Id":"a0s3K0000006wCRQAY","Name":"Test Partner", "Account__c":"0010a00001Ljv4ZAAR"},"Partner_Account__r": {"Id":"0010a00001Ljv4ZAAR","Name":"Test Partner Account"}},' +
            '{"Id":"0063K000003pyqPQAQ","StageName":"Complete","Name":"Margaux Maldonado","CS_Capacity_Allocated__c": "15.0", "AccountId":"0013K000006yKHKQA2","Shared_Solar_System__c":"a1J3K0000005hM1UAI","Commission_Structure__c":"a4w3K0000000EMVQA2","Product__c":"01t3K000000Rb2UQAS","Partner_tag_lookup__c":"a0s3K0000006wCRQAY","Partner_Account__c":"0010a00001Ljv4ZAAR","Account":{"Id":"0013K000006yKHKQA2","Account_Number__c":"BW-0035457"},"Commission_Structure__r":{"Id":"a4w3K0000000EMVQA2","Cents_kW_DC_Up_Front__c":0.1},"Shared_Solar_System__r":{"Id":"a1J3K0000005hM1UAI","Unique_ID__c":"SSS-000182", "Name": "Test SSS A"},"Partner_tag_lookup__r": {"Id":"a0s3K0000006wCRQAY","Name":"Test Partner", "Account__c":"0010a00001Ljv4ZAAR"},"Partner_Account__r": {"Id":"0010a00001Ljv4ZAAR","Name":"Test Partner Account"}},' +
            '{"Id":"0063K000003pyqQQAQ","StageName":"Complete","Name":"Conor Schmitt", "AccountId":"0013K000006yKHLQA2","Shared_Solar_System__c":"a1J3K0000005hM1UAI","Product__c":"01t3K000000Rb2UQAS","Commission_Structure__c":"a4w3K0000000EMVQA2","Partner_tag_lookup__c":"a0s3K0000006wCRQAY","Partner_Account__c":"0010a00001Ljv4ZAAR","Account":{"Id":"0013K000006yKHLQA2","Account_Number__c":"BW-0035458"},"Commission_Structure__r":{"Id":"a4w3K0000000EMVQA2","Cents_kW_DC_Up_Front__c":0.1},"Shared_Solar_System__r":{"Id":"a1J3K0000005hM1UAI","Unique_ID__c":"SSS-000182", "Name": "Test SSS A"},"Partner_tag_lookup__r": {"Id":"a0s3K0000006wCRQAY","Name":"Test Partner", "Account__c":"0010a00001Ljv4ZAAR"},"Partner_Account__r": {"Id":"0010a00001Ljv4ZAAR","Name":"Test Partner Account"}},' +
            '{"Id":"0063K000003pyqRQAQ","StageName":"Complete","Name":"Akbar Boyce","AccountId":"0013K000006yKHMQA2","Shared_Solar_System__c":"a1J3K0000005hM1UAI","Product__c":"01t3K000000Rb2UQAS","Commission_Structure__c":"a4w3K0000000EMVQA2","Partner_tag_lookup__c":"a0s3K0000006wCRQAY","Partner_Account__c":"0010a00001Ljv4ZAAR","Account":{"Id":"0013K000006yKHMQA2","Account_Number__c":"BW-0035459"},"Commission_Structure__r":{"Id":"a4w3K0000000EMVQA2","Cents_kW_DC_Up_Front__c":0.1},"Shared_Solar_System__r":{"Id":"a1J3K0000005hM1UAI","Unique_ID__c":"SSS-000182", "Name": "Test SSS A"},"Partner_tag_lookup__r": {"Id":"a0s3K0000006wCRQAY","Name":"Test Partner", "Account__c":"0010a00001Ljv4ZAAR"},"Partner_Account__r": {"Id":"0010a00001Ljv4ZAAR","Name":"Test Partner Account"}},' +
            '{"Id":"0063K000003pyqSQAQ","StageName":"Complete","Name":"Viaan Faulkner","AccountId":"0013K000006yKHNQA2","Shared_Solar_System__c":"a1J3K0000005hM1UAI","Product__c":"01t3K000000Rb2UQAS","Commission_Structure__c":"a4w3K0000000EMVQA2","Partner_tag_lookup__c":"a0s3K0000006wCRQAY","Partner_Account__c":"0010a00001Ljv4ZAAR","Account":{"Id":"0013K000006yKHNQA2","Account_Number__c":"BW-0035460"},"Commission_Structure__r":{"Id":"a4w3K0000000EMVQA2","Cents_kW_DC_Up_Front__c":0.1},"Shared_Solar_System__r":{"Id":"a1J3K0000005hM1UAI","Unique_ID__c":"SSS-000182", "Name": "Test SSS A"},"Partner_tag_lookup__r": {"Id":"a0s3K0000006wCRQAY","Name":"Test Partner", "Account__c":"0010a00001Ljv4ZAAR"},"Partner_Account__r": {"Id":"0010a00001Ljv4ZAAR","Name":"Test Partner Account"}}' +
            ']';
        return (List<Opportunity>) JSON.deserialize(queryData, List<Opportunity>.class);
    }

    public static List<Opportunity> getOpportunityMockForBilledType(){
        String queryData = '[' +
            '{"Id":"0063K000003pyqIQAQ","Name":"Ashley Smith","AccountId":"0013K000006yKHDQA2","Shared_Solar_System__c":"a1J3K0000005hM0UAI","CS_Capacity_Allocated__c":11.6550,"Commission_Structure__c":"a4w3K0000000EMXQA2","Partner_tag_lookup__c":"a0s3K0000006wCRQAY","Account":{"Id":"0013K000006yKHDQA2","Account_Number__c":"BW-0035450"},"Shared_Solar_System__r":{"Id":"a1J3K0000005hM0UAI","Unique_ID__c":"SSS-000181"},"Commission_Structure__r":{"Id":"a4w3K0000000EMXQA2","Cents_kW_DC_First_Bill_Paid__c":0.2400},"Partner_tag_lookup__r":{"Id":"a0s3K0000006wCRQAY","Name":"Test Partner 2"}},' +
            '{"Id":"0063K000003pyqJQAQ","Name":"Steven Ward","AccountId":"0013K000006yKHEQA2","Shared_Solar_System__c":"a1J3K0000005hM1UAI","CS_Capacity_Allocated__c":5.8275,"Commission_Structure__c":"a4w3K0000000EMXQA2","Partner_tag_lookup__c":"a0s3K0000006wCRQAY","Account":{"Id":"0013K000006yKHEQA2","Account_Number__c":"BW-0035451"},"Shared_Solar_System__r":{"Id":"a1J3K0000005hM1UAI","Unique_ID__c":"SSS-000182"},"Commission_Structure__r":{"Id":"a4w3K0000000EMXQA2","Cents_kW_DC_First_Bill_Paid__c":0.2400},"Partner_tag_lookup__r":{"Id":"a0s3K0000006wCRQAY","Name":"Test Partner 2"}},' +
            '{"Id":"0063K000003pyqKQAQ","Name":"Marie Mitchell","AccountId":"0013K000006yKHFQA2","Shared_Solar_System__c":"a1J3K0000005hM1UAI","CS_Capacity_Allocated__c":5.8275,"Commission_Structure__c":"a4w3K0000000EMXQA2","Partner_tag_lookup__c":"a0s3K0000006wCRQAY","Account":{"Id":"0013K000006yKHFQA2","Account_Number__c":"BW-0035452"},"Shared_Solar_System__r":{"Id":"a1J3K0000005hM1UAI","Unique_ID__c":"SSS-000182"},"Commission_Structure__r":{"Id":"a4w3K0000000EMXQA2","Cents_kW_DC_First_Bill_Paid__c":0.2400},"Partner_tag_lookup__r":{"Id":"a0s3K0000006wCRQAY","Name":"Test Partner 2"}},' +
            '{"Id":"0063K000003pyqLQAQ","Name":"Justin Jenkins","AccountId":"0013K000006yKHGQA2","Shared_Solar_System__c":"a1J3K0000005hM1UAI","CS_Capacity_Allocated__c":5.8275,"Commission_Structure__c":"a4w3K0000000EMXQA2","Partner_tag_lookup__c":"a0s3K0000006wCRQAY","Account":{"Id":"0013K000006yKHGQA2","Account_Number__c":"BW-0035453"},"Shared_Solar_System__r":{"Id":"a1J3K0000005hM1UAI","Unique_ID__c":"SSS-000182"},"Commission_Structure__r":{"Id":"a4w3K0000000EMXQA2","Cents_kW_DC_First_Bill_Paid__c":0.2400},"Partner_tag_lookup__r":{"Id":"a0s3K0000006wCRQAY","Name":"Test Partner 2"}},' +
            '{"Id":"0063K000003pyqNQAQ","Name":"Cobie Croft","AccountId":"0013K000006yKHIQA2","Shared_Solar_System__c":"a1J3K0000005hM1UAI","CS_Capacity_Allocated__c":5.8275,"Commission_Structure__c":"a4w3K0000000EMVQA2","Partner_tag_lookup__c":"a0s3K0000006wCRQAY","Account":{"Id":"0013K000006yKHIQA2","Account_Number__c":"BW-0035455"},"Shared_Solar_System__r":{"Id":"a1J3K0000005hM1UAI","Unique_ID__c":"SSS-000182"},"Commission_Structure__r":{"Id":"a4w3K0000000EMVQA2","Cents_kW_DC_First_Bill_Paid__c":0.2500},"Partner_tag_lookup__r":{"Id":"a0s3K0000006wCRQAY","Name":"Test Partner 2"}},' +
            '{"Id":"0063K000003pyqOQAQ","Name":"Ridwan Conner","AccountId":"0013K000006yKHJQA2","Shared_Solar_System__c":"a1J3K0000005hM1UAI","CS_Capacity_Allocated__c":5.8275,"Commission_Structure__c":"a4w3K0000000EMVQA2","Partner_tag_lookup__c":"a0s3K0000006wCRQAY","Account":{"Id":"0013K000006yKHJQA2","Account_Number__c":"BW-0035456"},"Shared_Solar_System__r":{"Id":"a1J3K0000005hM1UAI","Unique_ID__c":"SSS-000182"},"Commission_Structure__r":{"Id":"a4w3K0000000EMVQA2","Cents_kW_DC_First_Bill_Paid__c":0.2500},"Partner_tag_lookup__r":{"Id":"a0s3K0000006wCRQAY","Name":"Test Partner 2"}},' +
            '{"Id":"0063K000003pyqPQAQ","Name":"Margaux Maldonado","AccountId":"0013K000006yKHKQA2","Shared_Solar_System__c":"a1J3K0000005hM1UAI","CS_Capacity_Allocated__c":5.8275,"Commission_Structure__c":"a4w3K0000000EMVQA2","Partner_tag_lookup__c":"a0s3K0000006wCRQAY","Account":{"Id":"0013K000006yKHKQA2","Account_Number__c":"BW-0035457"},"Shared_Solar_System__r":{"Id":"a1J3K0000005hM1UAI","Unique_ID__c":"SSS-000182"},"Commission_Structure__r":{"Id":"a4w3K0000000EMVQA2","Cents_kW_DC_First_Bill_Paid__c":0.2500},"Partner_tag_lookup__r":{"Id":"a0s3K0000006wCRQAY","Name":"Test Partner 2"}},' +
            '{"Id":"0063K000003pyqQQAQ","Name":"Conor Schmitt","AccountId":"0013K000006yKHLQA2","Shared_Solar_System__c":"a1J3K0000005hM1UAI","CS_Capacity_Allocated__c":5.8275,"Commission_Structure__c":"a4w3K0000000EMVQA2","Partner_tag_lookup__c":"a0s3K0000006wCRQAY","Account":{"Id":"0013K000006yKHLQA2","Account_Number__c":"BW-0035458"},"Shared_Solar_System__r":{"Id":"a1J3K0000005hM1UAI","Unique_ID__c":"SSS-000182"},"Commission_Structure__r":{"Id":"a4w3K0000000EMVQA2","Cents_kW_DC_First_Bill_Paid__c":0.2500},"Partner_tag_lookup__r":{"Id":"a0s3K0000006wCRQAY","Name":"Test Partner 2"}},' +
            '{"Id":"0063K000003pyqRQAQ","Name":"Akbar Boyce","AccountId":"0013K000006yKHMQA2","Shared_Solar_System__c":"a1J3K0000005hM1UAI","CS_Capacity_Allocated__c":5.8275,"Commission_Structure__c":"a4w3K0000000EMVQA2","Partner_tag_lookup__c":"a0s3K0000006wCRQAY","Account":{"Id":"0013K000006yKHMQA2","Account_Number__c":"BW-0035459"},"Shared_Solar_System__r":{"Id":"a1J3K0000005hM1UAI","Unique_ID__c":"SSS-000182"},"Commission_Structure__r":{"Id":"a4w3K0000000EMVQA2","Cents_kW_DC_First_Bill_Paid__c":0.2500},"Partner_tag_lookup__r":{"Id":"a0s3K0000006wCRQAY","Name":"Test Partner 2"}},' +
            '{"Id":"0063K000003pyqSQAQ","Name":"Viaan Faulkner","AccountId":"0013K000006yKHNQA2","Shared_Solar_System__c":"a1J3K0000005hM1UAI","CS_Capacity_Allocated__c":5.8275,"Commission_Structure__c":"a4w3K0000000EMVQA2","Partner_tag_lookup__c":"a0s3K0000006wCRQAY","Account":{"Id":"0013K000006yKHNQA2","Account_Number__c":"BW-0035460"},"Shared_Solar_System__r":{"Id":"a1J3K0000005hM1UAI","Unique_ID__c":"SSS-000182"},"Commission_Structure__r":{"Id":"a4w3K0000000EMVQA2","Cents_kW_DC_First_Bill_Paid__c":0.2500},"Partner_tag_lookup__r":{"Id":"a0s3K0000006wCRQAY","Name":"Test Partner 2"}}' +
            ']';
        return (List<Opportunity>) JSON.deserialize(queryData, List<Opportunity>.class);
    }

    public class MockUASSelector extends MockProvider {
        public override Object handleMethodCall(MethodCall methodCall) {
            String queryData = '{' +
                '"0063K000003pyqPQAQ":10.0,' +
                '"0063K000003pyqJQAQ":25.0,' +
                '"0063K000003pyqIQAQ":25.0,' +
                '"0063K000003pyqQQAQ":25.0,' +
                '"0063K000003pyqLQAQ":14.3456,' +
                '"0063K000003pyqKQAQ":33.3333,' +
                '"0063K000003pyqNQAQ":12.0,' +
                '"0063K000003pyqSQAQ":12.34,' +
                '"0063K000003pyqRQAQ":45.45,' +
                '"0063K000003pyqOQAQ":10000.0' +
                '}';
            switch on methodCall.stubbedMethodName {
                when 'getUASSummaryByOpportunity' {
                    return (Map<Id,Decimal>) JSON.deserialize(queryData, Map<Id,Decimal>.class);
                }
            }
            return null;
        }
    }

    public class MockCommPaySelector extends MockProvider {
        public override Object handleMethodCall(MethodCall methodCall) {
            String queryData = '[' +
                '{"Id":"a4v3K0000000HLKQA2","Opportunity__c":"0063K000003pyqPQAQ", "Future_Customer_Subscription_kW_DC__c": "15.0"},' +
                '{"Id":"a4v3K0000000HMSQA2","Opportunity__c":"0063K000003pyqQQAQ", "Future_Customer_Subscription_kW_DC__c": "25.0"}' +
                ']';
            switch on methodCall.stubbedMethodName {
                when 'getPendingCommissionPayments' {
                    return (List<Commission_Payment__c>) JSON.deserialize(queryData, List<Commission_Payment__c>.class);
                }
            }
            return null;
        }
    }

    public class MockPartnerInvoiceSelector extends MockProvider {
        public override Object handleMethodCall(MethodCall methodCall) {
            Date monthFromToday = System.today().addMonths(1);
            Date today = System.today();

            Invoice__c nextMonthsInvoice = new Invoice__c(
                Id = 'a0c3K000000F0pUQAS',
                Partner__c = 'a0s3K0000006wCRQAY',
                Due_Date__c = Date.newInstance(monthFromToday.year(), monthFromToday.month(), 15)
            );
            Invoice__c thisMonthsInvoicePartner1 = new Invoice__c(
                Id = 'a0c3K000000F0pUQAS',
                Partner__c = 'a0s3K0000006wCRQAY',
                Due_Date__c = Date.newInstance(today.year(), today.month(), 15)
            );
            Invoice__c thisMonthsInvoicePartner2 = new Invoice__c(
                Id = 'a0c3K000000F0pUQAT',
                Partner__c = 'a0s3K0000006wCMQAY',
                Due_Date__c = Date.newInstance(today.year(), today.month(), 15)
            );

            switch on methodCall.stubbedMethodName {
                when 'getPendingPartnerInvoices' {
                    return new List<Invoice__c>{
                        nextMonthsInvoice, thisMonthsInvoicePartner1, thisMonthsInvoicePartner2
                    };
                }
            }
            return null;
        }
    }
}