src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Number__c</fullName>
        <description>CS Account Number</description>
        <displayFormat>BW-{0000000}</displayFormat>
        <label>CS Account Number</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Zuora_Id__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>Set by ZuoraAccountService after it creates the account in Zuora from a converted lead</inlineHelpText>
        <label>Zuora Id</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Bill_Adjustment__c.object
<CustomObject>
    <description>CS Billing: If we know that a UAS is going to need adjustments on a future bill, they are stored here until that bill is generated</description>
    <fields>
        <fullName>Adjustment_Amount__c</fullName>
        <label>Adjustment Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Adjustment_Type__c</fullName>
        <inlineHelpText>Determines how this adjustment will be pulled into client reports: use &quot;Production&quot; for any delayed, missed or incorrectly billed credits. &quot;BW Credit&quot; for any adjustment for which BW will need to pay a client, etc. Contact Accounting with ?s</inlineHelpText>
        <label>Adjustment Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Production</fullName>
                </value>
                <value>
                    <fullName>Late Fee Waived</fullName>
                </value>
                <value>
                    <fullName>Customer Refund</fullName>
                </value>
                <value>
                    <fullName>BW Credit</fullName>
                </value>
                <value>
                    <fullName>Project Payment Transfer</fullName>
                </value>
                <value>
                    <fullName>Returned Payment</fullName>
                </value>
                <value>
                    <fullName>Client Credit</fullName>
                </value>
                <value>
                    <fullName>Returned Check Payment</fullName>
                </value>
                <value>
                    <fullName>No Longer Billing</fullName>
                </value>
                <value>
                    <fullName>Plympton TBD</fullName>
                    <isActive>false</isActive>
                    <label>Plympton TBD</label>
                </value>
                <value>
                    <fullName>Write - Off</fullName>
                    <isActive>false</isActive>
                    <label>Write - Off</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <defaultValue>&quot;Unapproved&quot;</defaultValue>
        <inlineHelpText>Set automatically by the approval process</inlineHelpText>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Unapproved</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Stamped with UAS.Opp.SSS.Entity.Client at creation</inlineHelpText>
        <label>Client</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Bill Adjustments</relationshipLabel>
        <relationshipName>Bill_Adjustments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Credits_Allocated__c</fullName>
        <label>Credits Allocated</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Discount__c</fullName>
        <formula>IF(ISPICKVAL(Adjustment_Type__c,&apos;Production&apos; ), ( Credits_Allocated__c -  Adjustment_Amount__c ), NULL)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Discount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Transfer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Required for Production Adjustments</inlineHelpText>
        <label>Transfer</label>
        <referenceTo>Transfer__c</referenceTo>
        <relationshipLabel>Adjustments</relationshipLabel>
        <relationshipName>Bill_Adjustments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Utility_Account_Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Utility Account Subscription</label>
        <referenceTo>Utility_Account_Subscription__c</referenceTo>
        <relationshipLabel>Bill Adjustments</relationshipLabel>
        <relationshipName>Bill_Adjustments_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora_Id__c</fullName>
        <label>Zuora Id</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <label>Bill Adjustment</label>
    <nameField>
        <label>Bill Adjustment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bill Adjustments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Shared_Solar_System__c.object
<CustomObject
     >
    <articleTypeChannelDisplay n1:nil="true" />
    <customSettingsType n1:nil="true" />
    <description n1:nil="true" />
    <eventType n1:nil="true" />
    <fields>
        <fullName>UCB__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Used to determine if the project will be billed under UCB. It determines the communications the customer will receive (UCB vs non UCB)</inlineHelpText>
        <label>UCB</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Unique_ID__c</fullName>
        <displayFormat>SSS-{000000}</displayFormat>
        <externalId>true</externalId>
        <label>Unique ID</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Utility__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Utility</label>
        <referenceTo>Utility__c</referenceTo>
        <relationshipLabel>Shared Solar Systems</relationshipLabel>
        <relationshipName>Shared_Solar_Systems</relationshipName>
        <type>Lookup</type>
    </fields>
    <gender n1:nil="true" />
    <household>false</household>
    <label>Shared Solar System</label>
    <nameField>
        <label>Shared Solar System Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shared Solar Systems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <startsWith n1:nil="true" />
</CustomObject>

src/objects/Transfer__c.object
<CustomObject>
    <fields>
        <fullName>Date_of_Transfer__c</fullName>
        <label>Date of Transfer</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Shared_Solar_System__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Transfer object is looking up to the SSS object.</description>
        <label>Shared Solar System</label>
        <referenceTo>Shared_Solar_System__c</referenceTo>
        <relationshipLabel>Transfers</relationshipLabel>
        <relationshipName>Transfers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UCB__c</fullName>
        <formula>Shared_Solar_System__r.UCB__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>UCB</label>
        <type>Checkbox</type>
    </fields>
    <label>Transfer</label>
    <nameField>
        <label>Transfer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transfers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Transfer_Part__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Transfer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>A lookup relationship from Transfer Parts up to Transfer.</description>
        <label>Transfer</label>
        <referenceTo>Transfer__c</referenceTo>
        <relationshipName>Transfer_Parts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Transfer</fullName>
                </value>
                <value>
                    <fullName>Fee</fullName>
                </value>
                <value>
                    <fullName>Incentive Payment</fullName>
                </value>
                <value>
                    <fullName>Unsubscribed Credits</fullName>
                </value>
                <value>
                    <fullName>Customer Savings</fullName>
                </value>
                <value>
                    <fullName>Payment</fullName>
                </value>
                <value>
                    <fullName>Unserviced</fullName>
                </value>
                <value>
                    <fullName>Bill</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Production Detail</label>
    <nameField>
        <label>Transfer Parts Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Production Detail</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Utility_Account_Subscription__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Utility Account Subscriptions</relationshipLabel>
        <relationshipName>Utility_Account_Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shared_Solar_System__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the SSS on the Opportunity when the UAS was created. The SSS on an existing UAS should never be changed.</description>
        <inlineHelpText>This is the SSS on the Opportunity when the UAS was created. The SSS on an existing UAS should never be changed.</inlineHelpText>
        <label>Shared Solar System</label>
        <referenceTo>Shared_Solar_System__c</referenceTo>
        <relationshipLabel>Utility Account Subscriptions</relationshipLabel>
        <relationshipName>Utility_Account_Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Utility_Account_Log__c</fullName>
        <inlineHelpText>The related UAL</inlineHelpText>
        <label>Utility Account Log</label>
        <referenceTo>Utility_Account_Log__c</referenceTo>
        <relationshipLabel>Utility Account Subscriptions</relationshipLabel>
        <relationshipName>Utility_Account_Subscriptions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Utility__c</fullName>
        <formula>Opportunity__r.UtilityMapper__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Utility</label>
        <type>Text</type>
    </fields>
    <label>Utility Account Subscription</label>
    <nameField>
        <label>Utility Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Account Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/AdjustmentSelector.cls
/*
 * Tested by: ZuoraUsageServiceTest, ZuoraCreditDebitMemoServiceTest, AdjustmentSelectorTest
 */
@SuppressWarnings('PMD.ApexCRUDViolation')
public without sharing class AdjustmentSelector {
    /**
     * @description Used to get all adjustments to send to Zuora, with no Id filter (used by the Bill Gen Console)
     * @param typeIsUsage  True to select positive Production adjustments
     * @param mode Selects adjustments that are Post When Approved
     * @return QueryLocator of Bill Adjustments to send to Zuora
     */
    public static Database.QueryLocator getAdjustmentsNotYetInZuora(Boolean typeIsUsage, ZuoraCreditMemoBatchSend.AdjustmentType mode) {
        return getAdjustmentsNotYetInZuora(typeIsUsage, mode, new Set<Id>());
    }

    public static Database.QueryLocator getAdjustmentsNotYetInZuora(Boolean typeIsUsage, ZuoraCreditMemoBatchSend.AdjustmentType mode, Set<Id> billAdjustmentIds) {
        String queryString =
            'SELECT ' +
                'Id, Name, ' +
                'Utility_Account_Subscription__r.Opportunity__r.Shared_Solar_System__r.Utility__r.Name, ' +
                'Utility_Account_Subscription__r.Opportunity__r.Shared_Solar_System__r.Name, ' +
                'Utility_Account_Subscription__r.Utility_Account_Log__r.Name, ' +
                'Client__r.Account_Number__c, ' +
                'Utility_Account_Subscription__r.Opportunity__r.Shared_Solar_System__r.Unique_ID__c, ' +
                'Utility_Account_Subscription__r.Opportunity__r.Account.Zuora_Id__c, ' +
                'Adjustment_Amount__c, ' +
                'Adjustment_Type__c, ' +
                'Discount__c, ' +
                'Credits_Allocated__c, ' +
                'Zuora_Id__c, ' +
                'Transfer__r.Date_of_Transfer__c ' +
                'FROM Bill_Adjustment__c ' +
                'WHERE Zuora_Id__c = null ' +
                'AND Approval_Status__c = \'Approved\' ' +
                // handle various UCB and externally serviced permutations
                'AND (' +
                '(Utility_Account_Subscription__r.Shared_Solar_System__r.UCB__c = TRUE AND Utility_Account_Subscription__r.Externally_Serviced_Override__c = \'Internally Serviced\') ' +
                'OR (Utility_Account_Subscription__r.Shared_Solar_System__r.UCB__c = FALSE AND ' +
                '        Utility_Account_Subscription__r.Externally_Serviced__c = FALSE AND ' +
                '        Externally_Serviced__c = FALSE)' +
                ') ' +
                // Ignore Returns, because we'll always create a debit memo for returned payments in Zuora
                'AND Adjustment_Type__c != \'Returned Payment\' ' +
                'AND Adjustment_Type__c != \'Returned Check Payment\' ' +
                'AND Adjustment_Type__c != \'Project Payment Transfer\' ';

        if (typeIsUsage) {
            queryString += 'AND Adjustment_Type__c = \'Production\' ';
            queryString += 'AND Adjustment_Amount__c >= 0 ';
        } else {
            queryString += 'AND(Adjustment_Type__c != \'Production\' ';
            queryString += 'OR Adjustment_Amount__c < 0) ';
        }

        if (mode == ZuoraCreditMemoBatchSend.AdjustmentType.POST_WHEN_APPROVED) {
            queryString += 'AND Effective__c = \'Post When Approved\' ';
        }
        if (!billAdjustmentIds.isEmpty()) {
            queryString += 'AND Id IN :billAdjustmentIds ';
        }

        queryString += ' ORDER BY Utility_Account_Subscription__r.Opportunity__r.AccountId';
        return Database.getQueryLocator(queryString);
    }

    public Map<String, List<Bill_Adjustment__c>> getAdjustmentMapFromExternalIds(Set<String> zuoraIds) {
        Map<String, List<Bill_Adjustment__c>> externalIdToAdjustMap = new Map<String, List<Bill_Adjustment__c>>();
        List<Bill_Adjustment__c> adjustList = [
            SELECT Id, Transfer__c, Discount__c, Zuora_Id__c, Adjustment_Amount__c
            FROM Bill_Adjustment__c
            WHERE Zuora_Id__c IN :zuoraIds
        ];
        for (Bill_Adjustment__c adjust : adjustList) {
            if (externalIdToAdjustMap.containsKey(adjust.Zuora_Id__c)) {
                List<Bill_Adjustment__c> existingList = externalIdToAdjustMap.get(adjust.Zuora_Id__c);
                existingList.add(adjust);
                externalIdToAdjustMap.put(adjust.Zuora_Id__c, existingList);
            } else {
                externalIdToAdjustMap.put(adjust.Zuora_Id__c, new List<Bill_Adjustment__c>{
                    adjust
                });
            }
        }
        return externalIdToAdjustMap;
    }

    public List<Bill_Adjustment__c> getUnservicedWithoutProductionDetail(Integer batchSize) {
        return new List<Bill_Adjustment__c>([
            SELECT Id, Externally_Serviced__c, Transfer__c, Credits_Allocated__c
            FROM Bill_Adjustment__c
            WHERE Externally_Serviced__c = TRUE
            AND Ready_for_Production_Detail__c = TRUE
            LIMIT :batchSize
        ]);
    }

    public List<AggregateResultProxy> selectForReconciliation(List<Bill_Adjustment__c> billAdjustmentsToReconcile) {
        List<AggregateResultProxy> groupedResultProxies = new List<AggregateResultProxy>();
        for (AggregateResult result : [
            SELECT Externally_Serviced_Bill_Adjustment__c, SUM(Amount__c) AMOUNT
            FROM Transfer_Part__c
            WHERE Externally_Serviced_Bill_Adjustment__c IN :billAdjustmentsToReconcile
            AND Type__c != 'Customer Savings'
            GROUP BY Externally_Serviced_Bill_Adjustment__c
        ]) {
            groupedResultProxies.add(new AggregateResultProxy().withAggregateResult(result));
        }
        return groupedResultProxies;
    }
}