src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Parent_Account_ID__c</fullName>
        <formula>Parent_Account__r.Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>CS Parent Account ID</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Product_Profile__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Product Profiles</relationshipLabel>
        <relationshipName>Product_Profiles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>My_Current_Balance__c</fullName>
        <label>My Current Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Profile_Type__c</fullName>
        <label>Profile Type</label>
        <picklist>
            <picklistValues>
                <fullName>Community Solar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Solar Loan</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Product Profile</label>
    <nameField>
        <label>Product Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Parent_Account_ID__c</fullName>
        <formula>Contact.Account.Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Parent Account ID</label>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/DashboardHeaderController.cls
public with sharing class DashboardHeaderController {
    
    @AuraEnabled
    public static List<Account> getMenuLabelList() {
    list<Account> propertyAccountLabelList = new list<Account>();
    User u = [Select Id, ContactId, Parent_account_id__c, Contact.Account.Id  from User where Id = :UserInfo.getUserId()];
    String userAccountId = (string)u.Contact.Account.Id;    
    system.debug(LoggingLevel.info, u.Parent_account_id__c);    
    system.debug(LoggingLevel.info, u.Id);   
    for(Account propertyAccount : [SELECT Id, name, Parent_Account_ID__c FROM Account WHERE Parent_Account_ID__c = : u.Parent_account_id__c]){
        system.debug(LoggingLevel.info, propertyAccount.Parent_Account_ID__c);
        propertyAccountLabelList.add(propertyAccount);
    }    
    system.debug(LoggingLevel.info, propertyAccountLabelList);
    return propertyAccountLabelList;
    }
   
    @AuraEnabled
    public static Boolean hasBill() {
      Boolean hasBill = false;
      User u = [Select Id, ContactId from User where Id = :UserInfo.getUserId()];
      if(u.ContactId != null) {
        try {
          Product_Profile__c pp = [Select Id, My_Current_Balance__c from Product_Profile__c where Contact__c = :u.ContactId and Profile_Type__c = 'Community Solar'];
          if(pp.My_Current_Balance__c != null)
            hasBill = true;
        }
        catch(Exception ex) {
          
        }
      }
      return hasBill;
    } 
    
    @AuraEnabled
    public static String getName() {
      return UserInfo.getFirstName();
    } 
}