src/objects/Account_Bill__c.object
<CustomObject>
    <fields>
        <fullName>Balance_Net_Late_Payments__c</fullName>
        <label>Balance Net of Late Payments</label>
        <summarizedField>System_Bill__c.Balance_Net_Late_Payments__c</summarizedField>
        <summaryForeignKey>System_Bill__c.Account_Bill__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Bill_Number__c</fullName>
        <label>Bill Number</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Due_This_Month__c</fullName>
        <label>Due This Month</label>
        <summarizedField>System_Bill__c.Due_This_Month__c</summarizedField>
        <summaryForeignKey>System_Bill__c.Account_Bill__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Parent_Account__c</fullName>
        <label>Property Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Bills</relationshipLabel>
        <relationshipName>Account_Bills</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Published__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Published</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Shared_Solar_System__c</fullName>
        <label>Shared Solar System</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>Account Bill</label>
    <nameField>
        <label>Account Bill Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Bills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Adjustment_Application__c.object
<CustomObject>
    <fields>
        <fullName>Adjustment_Amount__c</fullName>
        <label>Adjustment Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Bill_Adjustment__c</fullName>
        <label>Bill Adjustment</label>
        <referenceTo>Bill_Adjustment__c</referenceTo>
        <relationshipLabel>Adjustment Applications</relationshipLabel>
        <relationshipName>Adjustment_Applications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>System_Bill__c</fullName>
        <label>System Bill</label>
        <referenceTo>System_Bill__c</referenceTo>
        <relationshipLabel>Adjustment Applications</relationshipLabel>
        <relationshipName>Adjustment_Applications</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Adjustment Application</label>
    <nameField>
        <label>Adjustment Applications Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Adjustment Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/APXT_BPM__Conductor__c.object
<CustomObject
     >
    <articleTypeChannelDisplay n1:nil="true" />
    <customSettingsType n1:nil="true" />
    <description n1:nil="true" />
    <eventType n1:nil="true" />
    <fields>
        <fullName>Apply_Overpay_Adjust__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Apply Overpayments/Adjustments</label>
        <type>Checkbox</type>
    </fields>
    <gender n1:nil="true" />
    <household>false</household>
    <label>Conga Conductor</label>
    <nameField>
        <displayFormat>Conductor-{0000}</displayFormat>
        <label>Conductor Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Conga Conductors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <startsWith n1:nil="true" />
</CustomObject>

src/objects/Bill_Adjustment__c.object
<CustomObject>
    <description>CS Billing: If we know that a UAS is going to need adjustments on a future bill, they are stored here until that bill is generated</description>
    <fields>
        <fullName>Account_Bill__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>XXAccount Bill</label>
        <referenceTo>Account_Bill__c</referenceTo>
        <relationshipLabel>Bill Adjustments</relationshipLabel>
        <relationshipName>Bill_Adjustments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Adjustment_Amount__c</fullName>
        <label>Adjustment Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <defaultValue>&quot;Unapproved&quot;</defaultValue>
        <inlineHelpText>Set automatically by the approval process</inlineHelpText>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Unapproved</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Intermediate_Outstanding__c</fullName>
        <inlineHelpText>Used in OverpaymentApplication, even though it isn&apos;t populated</inlineHelpText>
        <label>Intermediate Outstanding</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opportunity_ID__c</fullName>
        <formula>UASB__r.System_Bill__r.Opportunity__r.Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Opportunity ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Outstanding__c</fullName>
        <formula>Adjustment_Amount__c -  Total_Adjustments_Distributed__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Outstanding</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Overpayment__c</fullName>
        <defaultValue>false</defaultValue>
        <label>XXOverpayment</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>UASB__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Utility Account Subscription Bill</label>
        <referenceTo>UASB__c</referenceTo>
        <relationshipLabel>Bill Adjustments</relationshipLabel>
        <relationshipName>Bill_Adjustments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Bill Adjustment</label>
    <nameField>
        <label>Bill Adjustment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bill Adjustments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Overpayment__c.object
<CustomObject>
    <fields>
        <fullName>Account_Bill__c</fullName>
        <label>Account Bill</label>
        <referenceTo>Account_Bill__c</referenceTo>
        <relationshipLabel>Overpayments</relationshipLabel>
        <relationshipName>Overpayments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Entity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Entity</label>
        <referenceTo>Entity__c</referenceTo>
        <relationshipLabel>Overpayments</relationshipLabel>
        <relationshipName>Overpayments</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Intermediate_Outstanding__c</fullName>
        <label>Intermediate Outstanding</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Outstanding__c</fullName>
        <formula>Overpayment_Amount__c + Total_Funds_Distributed__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Outstanding</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Overpayment</label>
    <nameField>
        <displayFormat>OP{000000}</displayFormat>
        <label>Overpayment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Overpayments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Shared_Solar_System__c.object
<CustomObject
     >
    <articleTypeChannelDisplay n1:nil="true" />
    <customSettingsType n1:nil="true" />
    <description n1:nil="true" />
    <eventType n1:nil="true" />
    <fields>
        <fullName>BWC_Project_Entity_Manual__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Entity name of project.</inlineHelpText>
        <label>Project Entity</label>
        <referenceTo>Entity__c</referenceTo>
        <relationshipLabel>Shared Solar Systems</relationshipLabel>
        <relationshipName>Shared_Solar_Systems</relationshipName>
        <type>Lookup</type>
    </fields>
    <gender n1:nil="true" />
    <household>false</household>
    <label>Shared Solar System</label>
    <nameField>
        <label>Shared Solar System Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shared Solar Systems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <startsWith n1:nil="true" />
</CustomObject>

src/objects/System_Bill__c.object
<CustomObject>
    <fields>
        <fullName>Account_Bill__c</fullName>
        <label>Account Bill</label>
        <referenceTo>Account_Bill__c</referenceTo>
        <relationshipLabel>System Bills</relationshipLabel>
        <relationshipName>System_Bills</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Balance_Adjustments__c</fullName>
        <label>XXBalance Adjustments</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Balance_Net_Late_Payments__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>Used for collections and days past due. Calculated when bills are generated as Due This Month - Payments Applied</inlineHelpText>
        <label>Balance Net Late Payments</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Bill_Number__c</fullName>
        <label>Bill Number</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Due_This_Month__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>New charges calculated this month (not including late fees, adjustments, etc.)</inlineHelpText>
        <label>Due This Month</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Entity_ID__c</fullName>
        <formula>Shared_Solar_System__r.BWC_Project_Entity_Manual__r.Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Entity ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_Id__c</fullName>
        <formula>Opportunity__r.Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Opportunity Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>System Bills</relationshipLabel>
        <relationshipName>System_Bills</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shared_Solar_System__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Shared Solar System</label>
        <referenceTo>Shared_Solar_System__c</referenceTo>
        <relationshipLabel>System Bills</relationshipLabel>
        <relationshipName>System_Bills</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>System Bill</label>
    <nameField>
        <label>System Bill Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>System Bills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/UASB__c.object
<CustomObject
     >
    <description n1:nil="true" />
    <fields>
        <fullName>Adjustment_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Adjustment Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Utility Account Subscription Bills</relationshipLabel>
        <relationshipName>Utility_Account_Subscription_Bills</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shared_Solar_System__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Shared Solar System</label>
        <referenceTo>Shared_Solar_System__c</referenceTo>
        <relationshipLabel>Utility Account Subscription Bills</relationshipLabel>
        <relationshipName>Utility_Account_Subscription_Bills</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>System_Bill__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>System Bill</label>
        <referenceTo>System_Bill__c</referenceTo>
        <relationshipLabel>Utility Account Subscription Bills</relationshipLabel>
        <relationshipName>Utility_Account_Subscription_Bills</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Utility Account Subscription Bill</label>
    <nameField>
        <displayFormat>UASB-{0000000}</displayFormat>
        <label>Utility Account Subscription Bill Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Utility Account Subscription Bills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/OverpaymentApplication.cls
/*
 * Description: applies overpayments to bills when we tell conga to generate bills and apply overpayments
 * Test: TestBillCreationandPayment {testAdjustment, testAdjustment2, testMultipleAdjustments}
 */

public without sharing class OverpaymentApplication {
    public static Map<String, List<Bill_Adjustment__c>> adjustMap;
    public static List<Adjustment_Application__c> adjustmentsToInsertList;

    public static void triggerApplication(Map<Id,APXT_BPM__Conductor__c> oldMap, List<APXT_BPM__Conductor__c> newList) {
        for (APXT_BPM__Conductor__c conductor : newList) {
            if (conductor.Apply_Overpay_Adjust__c && !oldMap.get(conductor.Id).Apply_Overpay_Adjust__c) {
                applyOverpayments();
            }
        }
    }

    public static void applyOverpayments() {
        List<String> propertyAccountIdList = new List<String>();
        List<String> opportunityIdList = new List<String>();
        Decimal adjustAmount = 0;
        adjustMap = new Map<String, List<Bill_Adjustment__c>>();
        adjustmentsToInsertList = new List<Adjustment_Application__c>();

        List<Bill_Adjustment__c> adjustments = [
            SELECT Id, Name, Account_Bill__c, Entity__r.Id, Adjustment_Amount__c, Account_Bill__r.Bill_Number__c,
                Account_Bill__r.Parent_Account__c, Outstanding__c, Opportunity_ID__c,
                Overpayment__c,UASB__c, UASB__r.Opportunity__c, Approval_Status__c
            FROM Bill_Adjustment__c
            WHERE Outstanding__c != 0
            AND(Approval_Status__c = 'Approved' OR Overpayment__c = TRUE)
            ORDER BY Adjustment_Amount__c DESC
        ];

        for(Bill_Adjustment__c adjustment : adjustments){
            String adjustKey;
            if (adjustment.Account_Bill__c != NULL) {
                propertyAccountIdList.add(adjustment.Account_Bill__r.Parent_Account__c);
                adjustKey = adjustment.Entity__r.Id;
                adjustKey = adjustKey.Substring(0,15) + '_' + adjustment.Account_Bill__r.Parent_Account__c;
            } else if (adjustment.UASB__c != NULL) {
                opportunityIdList.add(adjustment.UASB__r.Opportunity__c);
                adjustKey = adjustment.UASB__r.Opportunity__c;
            }
            adjustment.Intermediate_Outstanding__c = adjustment.Outstanding__c;
            if (adjustKey != null) {
                List<Bill_Adjustment__c> keyAdjustments;
                if (adjustMap.containsKey(adjustKey)) {
                    keyAdjustments = adjustMap.get(adjustKey);
                } else {
                    keyAdjustments = new List<Bill_Adjustment__c>();
                }
                keyAdjustments.add(adjustment);
                adjustMap.put(adjustKey, keyAdjustments);
            }
        }

        if (adjustMap.size() > 0) {
            List<System_Bill__c> systemBills = [
                SELECT Id, Name, Account_Bill__c, Due_This_Month__c, Entity_Id__c, Account_Bill__r.Bill_Number__c,
                    Account_Bill__r.Parent_Account__c, Balance_Net_Late_Payments__c, Bill_Number__c,
                    Balance_Adjustments__c, Opportunity__c, Shared_Solar_System__r.BWC_Project_Entity_Manual__c
                FROM System_Bill__c
                WHERE Account_Bill__r.Published__c = false
                AND (Account_Bill__r.Parent_Account__c IN : propertyAccountIdList
                OR Opportunity__c IN : opportunityIdList)
                ORDER BY Bill_Number__c ASC
            ];

            for (System_Bill__c sbill : systemBills ) {
                sbill.Balance_Net_Late_Payments__c = checkForAdjustments(sbill);
                checkForOverpayments(sbill);
            }
            if (adjustmentsToInsertList.size() > 0) {
                insert adjustmentsToInsertList;
            }
        }
    }

    public static Decimal checkForAdjustments (System_Bill__c sbill) {
        String sbKey = sbill.Opportunity__c;

        if (adjustMap.containsKey(sbKey)) {
            List<Bill_Adjustment__c> adjustments = adjustMap.get(sbKey);
            Decimal sBillBalance = sbill.Balance_Net_Late_Payments__c;
            for (Bill_Adjustment__c adjust : adjustments) {
                Decimal adjustmentAmount = 0;
                Decimal outstanding = adjust.Intermediate_Outstanding__c;
                Decimal originalAdjust = adjust.Adjustment_Amount__c;

                if (sBillBalance > 0
                    && originalAdjust > 0
                    && outstanding > 0){
                    adjustmentAmount += outstanding;
                } else if (sBillBalance > 0
                    && originalAdjust < 0
                    && outstanding < 0){
                    if (sBillBalance > Math.abs(outstanding)) {
                        adjustmentAmount += outstanding;
                    } else {
                        adjustmentAmount += -1 * sBillBalance;
                    }
                }
                if (adjustmentAmount != 0) {
                    Adjustment_Application__c adjustApp = createAdjustApp(sbill, adjustmentAmount, adjust, sbKey);
                    adjustmentsToInsertList.add(adjustApp);
                }
                sBillBalance += adjustmentAmount;
            }
            return sBillBalance;
        } else {
            return sBill.Balance_Net_Late_Payments__c;
        }
    }

    public static void checkForOverpayments (System_Bill__c sbill) {
        String sbKey = sbill.Shared_Solar_System__r.BWC_Project_Entity_Manual__c;
        sbKey = sbKey.substring(0,15) + '_' + sbill.Account_Bill__r.Parent_Account__c;

        if (adjustMap.containsKey(sbKey)) {
            List<Bill_Adjustment__c> adjustments = adjustMap.get(sbKey);
            Decimal sBillBalance = sbill.Balance_Net_Late_Payments__c;
            for (Bill_Adjustment__c adjust : adjustments) {
                Decimal originalAdjust = adjust.Adjustment_Amount__c;
                Decimal outstanding = adjust.Intermediate_Outstanding__c;
                Adjustment_Application__c adjustApp;
                if (sBillBalance > 0
                    && originalAdjust < 0
                    && outstanding < 0) {
                    Decimal amount;
                    if (Math.abs(outstanding) >= sBillBalance)  {
                        amount = -1 * sBillBalance;
                    } else {
                        amount = outstanding;
                    }
                    sBillBalance += amount;
                    adjustApp = createAdjustApp(sbill, amount, adjust, sbKey);
                    adjustmentsToInsertList.add(adjustApp);
                }
            }
        }
    }

    public static Adjustment_Application__c createAdjustApp (System_Bill__c systemBill, Decimal amount, Bill_Adjustment__c adjust, String key) {
        Adjustment_Application__c newApplication = new Adjustment_Application__c (	Name = adjust.Name,
                                                                                    Bill_Adjustment__c = adjust.Id,
                                                                                    System_Bill__c = systemBill.Id);
        if (adjust.Overpayment__c){
            newApplication.Overpayment_Amount__c = amount;
        } else {
            newApplication.Adjustment_Amount__c = amount;
        }
        List<Bill_Adjustment__c> adjustments = adjustMap.get(key);
        for (Bill_Adjustment__c adjustment : adjustments) {
            if (adjustment.Id == adjust.Id) {
                adjustment.Intermediate_Outstanding__c = adjust.Intermediate_Outstanding__c - amount;
            }
        }
        adjustMap.put(key, adjustments);
        return newApplication;
    }

}