src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Account is Closed if all Opportunities are Cancelled, Duplicate, Expired or Dead</inlineHelpText>
        <label>CS Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Commission_Payment__c.object
<CustomObject>
    <fields>
        <fullName>Commission_Structure__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Commission Structure</label>
        <referenceTo>Commission_Structure__c</referenceTo>
        <relationshipLabel>Commission Payments</relationshipLabel>
        <relationshipName>Commission_Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Commission_Type__c</fullName>
        <label>Commission Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Contract Execution</fullName>
                </value>
                <value>
                    <fullName>First Bill Sent</fullName>
                </value>
                <value>
                    <fullName>First Bill Paid</fullName>
                </value>
                <value>
                    <fullName>Cancellation/Refund</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Invoice__c</fullName>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Commission Payments</relationshipLabel>
        <relationshipName>Commission_Payments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Commission Payments</relationshipLabel>
        <relationshipName>Commission_Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Due</fullName>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Commission Payment</label>
    <nameField>
        <label>Commission Payment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Commission Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Commission_Structure__c.object
<CustomObject>
    <fields>
        <fullName>Cents_kW_DC_First_Bill_Paid__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Enter the cents per kW DC the partner receives when the customer pays their first bill. This could be zero if they get the second part of their commission after the first bill is sent.</description>
        <inlineHelpText>Enter the cents per kW DC the partner receives when the customer pays their first bill. This could be zero if they get the second part of their commission after the first bill is sent.</inlineHelpText>
        <label>Cents/kW DC First Bill Paid</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Cents_kW_DC_First_Bill__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Enter the cents per kW DC the partner receives up when the customer gets their first bill. This could be zero if they get the second part of their commission after the first bill is fully paid.</description>
        <inlineHelpText>Enter the cents per kW DC the partner receives up when the customer gets their first bill. This could be zero if they get the second part of their commission after the first bill is fully paid.</inlineHelpText>
        <label>Cents/kW DC First Bill Sent</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Currency</type>
    </fields>
    <label>Commission Structure</label>
    <nameField>
        <label>Commission Structure Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Commission Structures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to relate multiple Client Contracts to a single opportunity</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Invoice__c.object
<CustomObject>
    <description>Zuora Invoice object. Invoices are bills that you send to customers.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Related Client Account for Client Invoices, or a partner account</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Received &gt;&gt; QC</fullName>
                </value>
                <value>
                    <fullName>QC Complete &gt;&gt; Submit to Accounting</fullName>
                </value>
                <value>
                    <fullName>Submitted to Accounting</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Commission_Structure__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Commission Structure</label>
        <referenceTo>Commission_Structure__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Partner_tag_lookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Partner</label>
        <referenceTo>Partner__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/First_Bill_Paid_Date__c.field-meta.xml
<CustomField>
    <fullName>First_Bill_Paid_Date__c</fullName>
    <description>Datetime when Salesforce recognizes that the first bill has been marked paid (in part or in full) by Zuora. Used for Partner Commission generation. Implemented in W-024076.</description>
    <label>First Bill Paid Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/First_Bill_Sent_Date__c.field-meta.xml
<CustomField>
    <fullName>First_Bill_Sent_Date__c</fullName>
    <description>Datetime when Salesforce recognizes that the first bill has been sent by Zuora. Used for Partner Commission generation. Implemented in W-024076.</description>
    <label>First Bill Sent Date</label>
    <type>DateTime</type>
</CustomField>

src/objects/Partner__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Link to partner or client account</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Partners</relationshipLabel>
        <relationshipName>Partners</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Commission_Structure__c</fullName>
        <label>Commission Structure</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <label>Partner</label>
    <nameField>
        <label>Partner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partners</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Subscription_Order__c.object
<CustomObject>
    <label>Subscription Order</label>
    <nameField>
        <displayFormat>SO-{00000}</displayFormat>
        <label>Subscription Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscription Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription_Order__c/fields/Contract_Close_Commission__c.field-meta.xml
<CustomField>
    <fullName>Contract_Close_Commission__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Contract Close Commission Payment record this Subscription Order is applied to. If no value, this Subscription Order has not been applied to a Commission Payment record yet.</inlineHelpText>
    <label>Contract Close Commission</label>
    <referenceTo>Commission_Payment__c</referenceTo>
    <relationshipLabel>Contract_Close_Subscription_Orders</relationshipLabel>
    <relationshipName>Subscription_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscription_Order__c/fields/First_Bill_Paid_Commission__c.field-meta.xml
<CustomField>
    <fullName>First_Bill_Paid_Commission__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>First Bill Paid Commission Payment record this Subscription Order is applied to. If no value, this Subscription Order has not been applied to a Commission Payment record yet.</inlineHelpText>
    <label>First Bill Paid Commission</label>
    <referenceTo>Commission_Payment__c</referenceTo>
    <relationshipLabel>Subscription Orders (First Bill Paid Commission)</relationshipLabel>
    <relationshipName>First_Bill_Paid_Subscription_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscription_Order__c/fields/First_Bill_Sent_Commission__c.field-meta.xml
<CustomField>
    <fullName>First_Bill_Sent_Commission__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>First Bill Sent Commission Payment record this Subscription Order is applied to. If no value, this Subscription Order has not been applied to a Commission Payment record yet.</inlineHelpText>
    <label>First Bill Sent Commission</label>
    <referenceTo>Commission_Payment__c</referenceTo>
    <relationshipLabel>Subscription Orders (First Bill Sent Commission)</relationshipLabel>
    <relationshipName>First_Bill_Subscription_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscription_Order__c/fields/Included_in_Contract_Close__c.field-meta.xml
<CustomField>
    <fullName>Included_in_Contract_Close__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Set during Perch Countersignature flow and implemented in W-024422</description>
    <inlineHelpText>Designates if this Subscription Order has been applied to the Contract Close Commission Payment for the corresponding deal.</inlineHelpText>
    <label>Included in Contract Close</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/VariableRateCommissionProcessor.cls
/**
 * @description Created by jeffparlin on 2/25/22. Processes Variable Rate Commissions for single Partner. Creates
 * Partner_Payment__c records corresponding to Subscription_Order__c records for a subscription, and applies those payment
 * records to the specified Invoice__c record to be later remitted to the Partner by Accounting.
 * Tested By: PartnerCommissionGenerationTest
 */
public without sharing class VariableRateCommissionProcessor extends PartnerCommissionProcessor {

    @TestVisible private static SubscriptionOrderSelector soSelector = new SubscriptionOrderSelector();
    @TestVisible private static CommissionPaymentSelector paymentSelector = new CommissionPaymentSelector();
    @TestVisible private static FeatureService featureService = new FeatureService();
    private static Boolean clawbackPaymentsEnabled;

    public VariableRateCommissionProcessor(Map<Id, Opportunity> variableRateOpps, fflib_SObjectUnitOfWork uow,
        Id currentPartner) {
        super.opportunities = variableRateOpps;
        super.unitOfWork = uow;
        super.currentPartner = currentPartner;
        retrieveDependencies();
    }

    public override void retrieveDependencies() {
        clawbackPaymentsEnabled = featureService.isEnabled('Clawback_Partner_Commissions');
        constructIterableDealSummaries();
    }

    public override void generateCommissionPayments() {
        for (DealSummary deal : deals) {
            try {
                if (contractExecutionCommissionNeeded(deal)) {
                    generateContractExecutionCommission(deal);
                } else if (firstBillSentCommissionNeeded(deal)) {
                    generateFirstBillSentCommission(deal);
                } else if (firstBillPaidCommissionNeeded(deal)) {
                    generateFirstBillPaidCommission(deal);
                } else if (clawbackCommissionNeeded(deal)) {
                    generateClawbackCommission(deal);
                }
            } catch (Exception e) {
                String message = deal + '\n\n' + e.getMessage() + ' ' + e.getStackTraceString();
                Logger.logLater('VariableRateCommissionProcessor', 'generateCommissionPayments', message, Logger.ERROR);
            }
        }
        calculateCommissionAmounts();
        Logger.flushLogs();
    }

    private void constructIterableDealSummaries() {
        Map<Id, List<Subscription_Order__c>> ordersByOpp = soSelector.getByOppForVariableCommission(opportunities.keySet());
        Map<Id, List<Commission_Payment__c>> paymentsByOpp = paymentSelector.getByOppForVariableCommission(opportunities.keySet());
        for (Id oppId : opportunities.keySet()) {
            DealSummary deal = new DealSummary();
            deal.opportunity = opportunities.get(oppId);
            deal.subscriptionOrders = ordersByOpp.get(oppId);
            deal.commissionPayments = paymentsByOpp.get(oppId);
            deals.add(deal);
        }
    }

    private Boolean contractExecutionCommissionNeeded(DealSummary deal) {
        Boolean dealMeetsCriteria = deal.opportunity.StageName == 'Complete' && !deal.subscriptionOrders.isEmpty();
        return dealMeetsCriteria && !existingCommissionFound(deal.commissionPayments, 'Contract Execution');
    }

    private Boolean firstBillSentCommissionNeeded(DealSummary deal) {
        Boolean dealMeetsCriteria = deal.opportunity.StageName == 'Complete' &&
            Util.nullToZero(deal.opportunity.Commission_Structure__r.Cents_kW_DC_First_Bill__c) != 0 &&
            deal.opportunity.First_Bill_Sent_Date__c != null;
        return dealMeetsCriteria && !existingCommissionFound(deal.commissionPayments, 'First Bill Sent');
    }

    private Boolean firstBillPaidCommissionNeeded(DealSummary deal) {
        Boolean dealMeetsCriteria = deal.opportunity.StageName == 'Complete' &&
            Util.nullToZero(deal.opportunity.Commission_Structure__r.Cents_kW_DC_First_Bill_Paid__c) != 0 &&
            deal.opportunity.First_Bill_Paid_Date__c != null;
        return dealMeetsCriteria && !existingCommissionFound(deal.commissionPayments, 'First Bill Paid');
    }

    private Boolean clawbackCommissionNeeded(DealSummary deal) {
        Boolean dealMeetsCriteria = deal.opportunity.StageName != 'Complete';
        return dealMeetsCriteria &&
            existingCommissionFound(deal.commissionPayments, 'Contract Execution') &&
            !existingCommissionFound(deal.commissionPayments, 'Cancellation/Refund');
    }

    private void generateContractExecutionCommission(DealSummary deal) {
        PartnerCommissionCalculator.Input payment = new PartnerCommissionCalculator.Input();
        payment.record = buildBaseCommissionPayment(deal, 'Contract Execution', 'Contract Execution');

        for (Subscription_Order__c order : deal.subscriptionOrders) {
            if (!order.Included_in_Contract_Close__c) {
                continue;
            }
            linkOrderToCommissionPayment(
                order, Subscription_Order__c.Contract_Close_Commission__c, payment.record, payment.contractCloseOrders
            );
        }
        super.paymentDetails.add(payment);
    }

    private void generateFirstBillSentCommission(DealSummary deal) {
        PartnerCommissionCalculator.Input payment = new PartnerCommissionCalculator.Input();
        payment.record = buildBaseCommissionPayment(deal, 'First Bill Sent', 'First Bill Sent');

        for (Subscription_Order__c order : deal.subscriptionOrders) {
            if (!order.Included_in_Contract_Close__c) {
                continue;
            }
            linkOrderToCommissionPayment(
                order, Subscription_Order__c.Contract_Close_Commission__c, payment.record, payment.firstBillSentOrders
            );
            linkOrderToCommissionPayment(
                order, Subscription_Order__c.First_Bill_Sent_Commission__c, payment.record, payment.firstBillSentOrders
            );
        }
        super.paymentDetails.add(payment);
    }

    private void generateFirstBillPaidCommission(DealSummary deal) {
        PartnerCommissionCalculator.Input payment = new PartnerCommissionCalculator.Input();
        payment.record = buildBaseCommissionPayment(deal, 'First Bill Paid', 'First Bill Paid');

        for (Subscription_Order__c order : deal.subscriptionOrders) {
            if (!order.Included_in_Contract_Close__c) {
                continue;
            }
            linkOrderToCommissionPayment(
                order, Subscription_Order__c.Contract_Close_Commission__c, payment.record, payment.firstBillPaidOrders
            );
            linkOrderToCommissionPayment(
                order, Subscription_Order__c.First_Bill_Sent_Commission__c, payment.record, payment.firstBillPaidOrders
            );
            linkOrderToCommissionPayment(
                order, Subscription_Order__c.First_Bill_Paid_Commission__c, payment.record, payment.firstBillPaidOrders
            );
        }
        super.paymentDetails.add(payment);
    }

    private void generateClawbackCommission(DealSummary deal) {
        PartnerCommissionCalculator.Input payment = new PartnerCommissionCalculator.Input();
        payment.record = buildBaseCommissionPayment(deal, 'Chargeback', 'Cancellation/Refund');

        for (Subscription_Order__c order : deal.subscriptionOrders) {
            linkOrderToCommissionPayment(
                order, Subscription_Order__c.Contract_Close_Commission__c, payment.record, payment.contractCloseOrders
            );
            linkOrderToCommissionPayment(
                order, Subscription_Order__c.First_Bill_Sent_Commission__c, payment.record, payment.firstBillSentOrders
            );
            linkOrderToCommissionPayment(
                order, Subscription_Order__c.First_Bill_Paid_Commission__c, payment.record, payment.firstBillPaidOrders
            );
        }
        if (clawbackPaymentsEnabled) {
            super.paymentDetails.add(payment);
        }
    }

    private Commission_Payment__c buildBaseCommissionPayment(DealSummary deal, String nameSuffix, String type) {
        return new Commission_Payment__c(
            Commission_Structure__c = deal.opportunity.Commission_Structure__c,
            Name = deal.opportunity.Partner_tag_lookup__r.Account__r.Name + ' - ' +
                deal.opportunity.Name.left(50) + ' - ' + nameSuffix,
            Opportunity__c = deal.opportunity.Id,
            Status__c = 'Pending Approval',
            Commission_Type__c = type,
            Invoice__c = getInvoiceForPartner().Id
        );
    }

    private Boolean existingCommissionFound(List<Commission_Payment__c> commissionPayments, String commissionType) {
        if (commissionPayments == null || commissionPayments?.isEmpty()) {
            return false;
        }
        for (Commission_Payment__c payment : commissionPayments) {
            if (payment.Commission_Type__c == commissionType) {
                return true;
            }
        }
        return false;
    }

    /**
     * @description Link a Subscription Order to a Commission Payment if eligible
     * @param order Subscription Order in question
     * @param commissionPaymentLookup Lookup field on Subscription Order for specific commission (e.g. Contract Close Commission)
     * @param commissionPayment Commission Payment to relate Subscription Order to
     * @param relatedListToApplyTo Related List to relate Subscription Order to (for PartnerCommissionCalculator)
     */
    private void linkOrderToCommissionPayment(
        Subscription_Order__c order,
        SObjectField commissionPaymentLookup,
        Commission_Payment__c commissionPayment,
        List<Subscription_Order__c> relatedListToApplyTo)
    {
        if (order.get(commissionPaymentLookup) == null) {
            unitOfWork.registerDirty(order, commissionPaymentLookup, commissionPayment);
            relatedListToApplyTo.add(order);
        }
    }

    private void calculateCommissionAmounts() {
        PartnerCommissionCalculator calculator = new PartnerCommissionCalculator(super.paymentDetails);
        calculator.calculate();
        for (PartnerCommissionCalculator.Input payment : super.paymentDetails) {
            unitOfWork.registerNew(payment.record);
        }
    }
}