src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>ActiveContract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Active version of this contract; this field is normally populated when a contract has been superseded or replaced by another version.</inlineHelpText>
        <label>Active Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Previous Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Generate_Disclosure_Form__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Generate Disclosure Form</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Generate_Review_Version__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>This is used in SSF to generate the review version of the contract via Conga.</inlineHelpText>
        <label>Generate Review Version</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This is used for Customer contracts that are generated when the customer is still a lead.</inlineHelpText>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This is used for customer contracts to show the product and contract that was used.</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Product lookup, for loans, set by an installer upon sending a new application or set by code after a credit check has determined qualifying products.</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Lead</fullName>
        <active>true</active>
        <businessProcess>CS</businessProcess>
        <label>Lead</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Disclosure_Form_Conga_Template__c</fullName>
        <inlineHelpText>This is the ID of the Conga template used in SSF for the disclosure form for Contracts generated off of the Contract object.</inlineHelpText>
        <label>Disclosure Form Conga Template</label>
        <length>180</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Rate_Class__c.object
<CustomObject>
    <description>This object stores utility rate class information. It&apos;s different from NMC Tariffs.</description>
    <fields>
        <fullName>Suppress_Disclosure_Form__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Suppress Disclosure Form</label>
        <type>Checkbox</type>
    </fields>
    <label>Rate Class</label>
    <nameField>
        <label>Rate Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rate Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Utility_Account_Log__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Utility Account Logs</relationshipLabel>
        <relationshipName>Utility_Account_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Cleaned_Utility_Account_Number__c</fullName>
        <inlineHelpText>Utility Account Number stripped of leading 0&apos;s and dashes, used for duplicate matching</inlineHelpText>
        <label>Cleaned Utility Account Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Utility Account Logs</relationshipLabel>
        <relationshipName>Utility_Account_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Utility_Rate_Class__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is populated by sales/operations. It is the utility rate class that a specific utility account has.</description>
        <inlineHelpText>Automatically populated for EDI-enabled utilities if related UDRP records have a Rate Class/Subclass matching a Rate Class record. Otherwise, manually populated by sales/ops from the Utility Bill and changed through the &quot;Recalculate Subscriptions&quot; button.</inlineHelpText>
        <label>Rate Class</label>
        <referenceTo>Rate_Class__c</referenceTo>
        <relationshipLabel>Utility Account Logs</relationshipLabel>
        <relationshipName>Utility_Account_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Utility Account Log</label>
    <nameField>
        <label>Utility Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Account Logs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Utility_Account_Subscription__c.object
<CustomObject>
    <fields>
        <fullName>Utility_Account_Log__c</fullName>
        <inlineHelpText>The related UAL</inlineHelpText>
        <label>Utility Account Log</label>
        <referenceTo>Utility_Account_Log__c</referenceTo>
        <relationshipLabel>Utility Account Subscriptions</relationshipLabel>
        <relationshipName>Utility_Account_Subscriptions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Utility Account Subscription</label>
    <nameField>
        <label>Utility Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Account Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/UtilityAccountLogTriggerHandler.cls
/**
 * @description  Created by mstackhouse on 12/17/2018.
 * Test: UtilityAccountLogTriggerHandlerTest, CSCancellationServiceTest
 */
public without sharing class UtilityAccountLogTriggerHandler {
    
    private Map<Id, Utility_Account_Log__c> oldMap;
    private List<Utility_Account_Log__c> newList;

    public UtilityAccountLogTriggerHandler(Map<Id, Utility_Account_Log__c> oldMap, List<Utility_Account_Log__c> newList) {
        this.oldMap = oldMap;
        this.newList = newList;
    }
    
    public void beforeInsert() {
        setCleanedUtilityAccountNumberBeforeSave();
    }
    
    public void beforeUpdate() {
        setCleanedUtilityAccountNumberBeforeSave();
    }

    public void afterUpdate() {
        List<Utility_Account_Subscription__c> uasesToFinal =
            CSCancellationService.getUASesForFinaledUALs(newList, oldMap);
        if (!uasesToFinal.isEmpty()) {
            CSCancellationService.processFinaledUtilityAccounts(uasesToFinal);
        }
        Set<Id> leadIdSet = new Set<Id>();
        for (Utility_Account_Log__c ual : newList) {
            if (ual.Utility_Rate_Class__c != oldMap.get(ual.Id).Utility_Rate_Class__c) {
                leadIdSet.add(ual.Lead__c);
            }
        }
        if (!leadIdSet.isEmpty()) {
            updateRateClassOnContract(leadIdSet);
        }
        new SystemCapacityRollupCalculator(new UALCapacityRollupInitializer(oldMap, newList)).performRollup();
    }

    @SuppressWarnings('PMD.ApexCRUDViolation')
    private void updateRateClassOnContract(Set<Id> leadIdSet) {
        List<Lead> leadList = [
            SELECT Id, (
                SELECT Id, Generate_Disclosure_Form__c, Product__c, Product__r.Disclosure_Form_Conga_Template__c
                FROM Contracts__r
            ), (
                SELECT Id, Utility_Rate_Class__c, Utility_Rate_Class__r.Suppress_Disclosure_Form__c
                FROM Utility_Account_Logs__r
            )
            FROM Lead
            WHERE Id = :leadIdSet
        ];
        List<Contract> contractsForUpdate = new List<Contract>();
        for (Lead associatedLead : leadList) {
            for (Contract c : associatedLead.Contracts__r) {
                Boolean generateDisclosureForm = calculateGenerateDisclosureForm(c.Product__r, associatedLead.Utility_Account_Logs__r);
                if (c.Generate_Disclosure_Form__c != generateDisclosureForm) {
                    c.Generate_Disclosure_Form__c = generateDisclosureForm;
                    c.Generate_Review_Version__c = true;
                    contractsForUpdate.add(c);
                }
            }
        }
        if (!contractsForUpdate.isEmpty()) {
            Util.updateAndLog(contractsForUpdate, 'UtilityAccountLogTriggerHandler', 'updateRateClassOnContract');
        }
    }

    private Boolean calculateGenerateDisclosureForm(Product2 product, List<Utility_Account_Log__c> ualList) {
        if (product == null || product.Disclosure_Form_Conga_Template__c == null) {
            return false;
        }
        Boolean allSuppress = true;
        Boolean allNull = true;
        for (Utility_Account_Log__c ual : ualList) {
            if (ual.Utility_Rate_Class__c != null) {
                allNull = false;
            }
            if (ual.Utility_Rate_Class__c == null || !ual.Utility_Rate_Class__r.Suppress_Disclosure_Form__c) {
                allSuppress = false;
            }
        }
        if (allNull) {
            return true;
        }
        if (allSuppress) {
            return false;
        }
        return true;
    }

    /**
     * @description Strips dashes and leading 0's from Utility Account Numbers and sets in a new text field, for duplicate
     * purposes
     */
    private void setCleanedUtilityAccountNumberBeforeSave() {
        for (Utility_Account_Log__c utilityAccountLog : newList) {
            utilityAccountLog.Cleaned_Utility_Account_Number__c = cleanUtilityAccountNumber(utilityAccountLog.Name);
        }
    }

    @TestVisible
    private String cleanUtilityAccountNumber(String utilityAccountNumber) {
        if (utilityAccountNumber == null) {
            return null;
        }
        String cleaned = utilityAccountNumber.remove('-').remove(' ');
        return stripLeadingCharacter(cleaned, '0');
    }

    private String stripLeadingCharacter(String dirtyString, String stringToStrip) {
        Integer indexOfNonSpace = dirtyString.indexOfAnyBut(stringToStrip);
        if (indexOfNonSpace != -1) {
            return dirtyString.substring(dirtyString.indexOfAnyBut(stringToStrip));
        }
        return '';
    }
}