src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Autopay_Date_Last_Enrolled__c</fullName>
        <inlineHelpText>The last day someone opted in to Autopay</inlineHelpText>
        <label>Autopay Date Last Enrolled</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Billing_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Zuora Billing Account, updated when Z360 syncs a new Billing Account to Salesforce</inlineHelpText>
        <label>Billing Account</label>
        <referenceTo>Zuora__CustomerAccount__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Days_Past_Due__c</fullName>
        <formula>IF(Total_Outstanding_Balance_Merge__c &gt; 1,
MAX(TODAY()-Max_Overdue_Due_Date_Merge__c,0),
0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Days Past Due</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Last_Bill_Send_Date_New_Charges_Zuora__c</fullName>
        <inlineHelpText>Last Invoice Date where new charges were &gt; 0</inlineHelpText>
        <label>Last Bill Send Date New Charges Zuora</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Max_Overdue_Due_Date_Zuora__c</fullName>
        <inlineHelpText>Zuora Data : Due date of oldest invoice or debit memo with a balance</inlineHelpText>
        <label>Max Overdue Due Date Zuora</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Parent_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Lookup to Parent Account</inlineHelpText>
        <label>Parent Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Properties</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Line__c</fullName>
        <label>Product Line</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Recurring_Billing__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>An indicator to tell whether the Property Account is on autopay. Only used to update the message on the bill. To take a customer off of autopay, use the payment component on the Billing Account to Manage Autopay</inlineHelpText>
        <label>Autopay</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Total_Outstanding_Balance_Merge__c</fullName>
        <formula>IF($CustomMetadata.Zuora_Setting__mdt.Production.Zuora_Is_Live__c, Total_Outstanding_Balance_Zuora__c , Total_Outstanding_Balance__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Outstanding Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Account/fields/Suppress_Collections__c.field-meta.xml
<CustomField>
    <fullName>Suppress_Collections__c</fullName>
    <inlineHelpText>If populated, suppresses collection cases, emails and letters. A blank value means collections automation will happen as normal. If suppressed until no longer past due, the morning Days Past Due automation will blank this picklist out when this account is no longer past due.</inlineHelpText>
    <label>Suppress Collections</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Suppress collections until no longer past due</fullName>
            </value>
            <value>
                <fullName>Suppress collections forever</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Case_Type__c</fullName>
        <label>Case Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Customer</fullName>
                </value>
                <value>
                    <fullName>3rd Party</fullName>
                </value>
                <value>
                    <fullName>Vendor</fullName>
                </value>
                <value>
                    <fullName>Perch</fullName>
                </value>
                <value>
                    <fullName>BlueWave</fullName>
                    <isActive>false</isActive>
                    <label>BlueWave</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <description>Select all options that best describe what the customer case was about.</description>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Product_Line__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Onboarding</fullName>
                </value>
                <value>
                    <fullName>TPF/Collections</fullName>
                </value>
                <value>
                    <fullName>SREC</fullName>
                </value>
                <value>
                    <fullName>Billing</fullName>
                    <label>Billing-Issue</label>
                </value>
                <value>
                    <fullName>Subscription Change</fullName>
                    <label>Subscription Transfer</label>
                </value>
                <value>
                    <fullName>Technical Assistance</fullName>
                </value>
                <value>
                    <fullName>Product Question</fullName>
                </value>
                <value>
                    <fullName>Subscription Adjustment</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>SRECs</fullName>
                </value>
                <value>
                    <fullName>Application Status</fullName>
                </value>
                <value>
                    <fullName>Disbursals</fullName>
                </value>
                <value>
                    <fullName>Loan Terms</fullName>
                </value>
                <value>
                    <fullName>Amortization Table</fullName>
                </value>
                <value>
                    <fullName>Portal Issue</fullName>
                    <label>Portal Support</label>
                </value>
                <value>
                    <fullName>Underwriting</fullName>
                </value>
                <value>
                    <fullName>Poor Review</fullName>
                </value>
                <value>
                    <fullName>Credit Allocation Issue</fullName>
                </value>
                <value>
                    <fullName>Cancelled Utility Account</fullName>
                </value>
                <value>
                    <fullName>Final Bill</fullName>
                </value>
                <value>
                    <fullName>Payment Plan</fullName>
                </value>
                <value>
                    <fullName>Do not send bill</fullName>
                </value>
                <value>
                    <fullName>Bill % Incorrect: Rounding error</fullName>
                </value>
                <value>
                    <fullName>Bill % Incorrect: Unknown error</fullName>
                </value>
                <value>
                    <fullName>UAS Marked as Cancelled: On Transfer Sheet</fullName>
                </value>
                <value>
                    <fullName>UAS Marked as Cancelled: Not on Transfer Sheet</fullName>
                </value>
                <value>
                    <fullName>Custom Message Update</fullName>
                </value>
                <value>
                    <fullName>Transfer</fullName>
                </value>
                <value>
                    <fullName>Cancellation</fullName>
                </value>
                <value>
                    <fullName>Product Terms</fullName>
                </value>
                <value>
                    <fullName>Collections</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Disable_Followup_Email__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checking this box will stop the automated email that goes out when a customer care or partner support case is closed that contains the survey.</description>
        <inlineHelpText>Checking this box will stop the automated email that goes out when a customer care or partner support case is closed that contains the survey.</inlineHelpText>
        <label>Disable Followup Email</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Product_Line__c</fullName>
        <label>Product Line</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Community Solar</fullName>
                </value>
                <value>
                    <fullName>Solar Loan</fullName>
                </value>
                <value>
                    <fullName>None</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Recurring_Billing__c</fullName>
        <formula>Account.Recurring_Billing__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Recurring Billing?</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Case</fullName>
        <active>true</active>
        <businessProcess>Customer Care Case</businessProcess>
        <label>Case</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Zuora__CustomerAccount__c.object
<CustomObject>
    <description>Zuora Billing Account object.  An account is a customer account that collects all of the critical information about the customer, such as contact information, payment terms, and payment methods. You can use a customer account to track subscriptions, amendments, and transactions, such as invoices and payments.</description>
    <fields>
        <fullName>Zuora__Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>R00N40000001kyLcEAI</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Zuora__AutoPay__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Auto Pay</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Zuora__Zuora_Id__c</fullName>
        <description>The Zuora Id (external primary key) of this Billing Account.</description>
        <inlineHelpText>The Zuora Id (external primary key) of this Billing Account.</inlineHelpText>
        <label>Zuora Id</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ZuoraBillingAccountService.cls
/*
   Tested By: ZuoraBillingAccountServiceTest
 */

@SuppressWarnings('PMD.ApexCRUDViolation')
public without sharing class ZuoraBillingAccountService implements Schedulable, ZuoraDataQueryService.Processor {
    @TestVisible private static ZuoraAccountSelector zuoraAcctSelector = new ZuoraAccountSelector();
    private static CaseFactory caseFactory = new CaseFactory();
    @TestVisible private static fflib_SObjectUnitOfWork uow = new fflib_SObjectUnitOfWork(
        new List<SObjectType>{
            Case.SObjectType
        }
    );
    @TestVisible private static final String SUPPRESS_COLLECTIONS_TEMPORARILY = 'Suppress collections until no longer past due';
    @TestVisible private static final String SUPPRESS_COLLECTIONS_PERMANENTLY = 'Suppress collections forever';

    public void checkPropertyAccountDiscrepancy(List<Zuora__CustomerAccount__c> billingAccounts) {
        checkPropertyAccountDiscrepancyFuture(CollectionUtil.toIds(CollectionUtil.getIds(billingAccounts)));
    }

    public void execute(SchedulableContext ctx) {
        startDaysPastDueUpdate();
    }

    @Future
    // Future methods must be declared as static, and can't have sobject parameters (like List<Zuora__CustomerAccount__c>)
    private static void checkPropertyAccountDiscrepancyFuture(Set<Id> accountsToCheck) {
        try {
            List<Account> propAccountsToUpdate = new List<Account>();
            List<Zuora__CustomerAccount__c> zuoraAccounts = zuoraAcctSelector.getBillingAccountsById(accountsToCheck);

            for (Zuora__CustomerAccount__c zAccount : zuoraAccounts) {
                if (zAccount.Zuora__AutoPay__c != zAccount.Zuora__Account__r.Recurring_Billing__c) {
                    Account propAccount = new Account(
                        Id = zAccount.Zuora__Account__r.Id,
                        Recurring_Billing__c = zAccount.Zuora__AutoPay__c,
                        Autopay_Date_Last_Enrolled__c = zAccount.Zuora__AutoPay__c ? Date.today() : null
                    );
                    propAccountsToUpdate.add(propAccount);
                }
            }

            Util.updateSObjs(propAccountsToUpdate);
        } catch (Exception excep) {
            Logger.logNow('ZuoraBillingAccountService', 'checkPropertyAccountDiscrepancy', excep.getMessage() + '\n' + excep.getStackTraceString());
        }
    }

    public void setBillingAccountOnPropertyAccount(List<Zuora__CustomerAccount__c> billingAccounts) {
        setBillingAccountOnPropertyAccountFuture(CollectionUtil.toIds(CollectionUtil.getIds(billingAccounts)));
    }

    @Future
    private static void setBillingAccountOnPropertyAccountFuture(Set<Id> billingAccountsInserted) {
        try {
            List<Account> propAccountsToUpdate = new List<Account>();
            List<Zuora__CustomerAccount__c> zuoraAccounts = zuoraAcctSelector.getBillingAccountsById(billingAccountsInserted);

            for (Zuora__CustomerAccount__c zAccount : zuoraAccounts) {
                propAccountsToUpdate.add(new Account(
                    Id = zAccount.Zuora__Account__r.Id,
                    Billing_Account__c = zAccount.Id
                ));
            }
            update propAccountsToUpdate;
        } catch (Exception e) {
            Logger.logNow('ZuoraBillingAccountService', 'setBillingAccountOnPropertyAccountFuture', e.getMessage() + '\n' + e.getStackTraceString());
        }
    }

    @TestVisible
    private void startDaysPastDueUpdate() {
        try {
            ZuoraDataQueryService.ProcessingParameter finishMethod = new ZuoraDataQueryService.ProcessingParameter();
            finishMethod.className = 'ZuoraBillingAccountService';
            String queryString;
            queryString = ZuoraInvoiceSelector.getOutstandingBalanceByAccountQuery();
            ZuoraDataQueryService.callFromApex(queryString, finishMethod);
        } catch (Exception excep) {
            Logger.logNow('ZuoraBillingAccountService', 'startDaysPastDueUpdate', excep.getMessage() + excep.getStackTraceString());
        }
    }

    public void executePostQueryJob(ZuoraDataQueryService.ProcessingParameter parameter, String response) {
        updateDaysPastDue(response);
    }

    @TestVisible
    private void updateDaysPastDue(String queryResponse) {
        List<Account> accountsToUpdate = new List<Account>();
        Map<String, AccountSummary> zuoraIdToAccountSummary = summarizeBalanceQueryResult(queryResponse);
        List<Zuora__CustomerAccount__c> zuoraBillingAccounts = zuoraAcctSelector.getAllBillingAccounts();
        for (Zuora__CustomerAccount__c zuoraAccount : zuoraBillingAccounts) {
            String zuoraId = zuoraAccount.Zuora__Zuora_Id__c;
            Account propertyToUpdate = new Account(
                Id = zuoraAccount.Zuora__Account__r.Id,
                Suppress_Collections__c = zuoraAccount.Zuora__Account__r.Suppress_Collections__c
            );
            AccountSummary accountSummary = zuoraIdToAccountSummary.get(zuoraId);
            setAccountPastDueFields(accountSummary, propertyToUpdate);
            registerPropertyForUpdate(propertyToUpdate, zuoraAccount, accountsToUpdate);
            unsetSuppressCollections(propertyToUpdate);
            if (inBadDebtGracePeriod(zuoraAccount) &&
                noLongerPastDue(propertyToUpdate)) {
                uow.registerNew(getCaseToReactivateCustomer(zuoraAccount));
            }
        }
        if (accountsToUpdate.size() > 200) {
            Database.executeBatch(new GenericBatchDMLOperation(accountsToUpdate, 'Update'));
        } else {
            Util.updateSObjs(accountsToUpdate);
        }
        uow.commitWork();
    }

    @TestVisible
    private Account unsetSuppressCollections(Account propertyToUpdate) {
        if (propertyToUpdate.Suppress_Collections__c == SUPPRESS_COLLECTIONS_TEMPORARILY &&
            noLongerPastDue(propertyToUpdate)) {
            propertyToUpdate.Suppress_Collections__c = null;
        }
        return propertyToUpdate;
    }

    private void registerPropertyForUpdate(Account propertyToUpdate, Zuora__CustomerAccount__c zuoraAccount, List<Account> accountsToUpdate) {
        if (pastDueFieldChanged(propertyToUpdate, zuoraAccount)) {
            accountsToUpdate.add(propertyToUpdate);
        }
    }

    private Boolean inBadDebtGracePeriod(Zuora__CustomerAccount__c zuoraAccount) {
        return zuoraAccount.Zuora__Account__r.Days_Past_Due__c >= CSCancellationScheduler.DAYS_PAST_DUE_DEACTIVATION_TRIGGER &&
            zuoraAccount.Zuora__Account__r.Days_Past_Due__c < CSCancellationScheduler.DAYS_PAST_DUE_BAD_DEBT_TRIGGER;
    }

    private Boolean pastDueFieldChanged(Account propertyToUpdate, Zuora__CustomerAccount__c zuoraAccount) {
        return propertyToUpdate.Total_Outstanding_Balance_Merge__c != zuoraAccount.Zuora__Account__r.Total_Outstanding_Balance_Merge__c ||
            propertyToUpdate.Max_Overdue_Due_Date_Zuora__c != zuoraAccount.Zuora__Account__r.Max_Overdue_Due_Date_Zuora__c ||
            propertyToUpdate.Last_Bill_Send_Date_New_Charges_Zuora__c != zuoraAccount.Zuora__Account__r.Last_Bill_Send_Date_New_Charges_Zuora__c;
    }

    private void setAccountPastDueFields(AccountSummary accountSummary, Account propertyToUpdate) {
        if (accountSummary != null) {
            propertyToUpdate.Max_Overdue_Due_Date_Zuora__c = accountSummary.MinDueDate;
            propertyToUpdate.Last_Bill_Send_Date_New_Charges_Zuora__c = accountSummary.LastBillSendDate;
        } else {
            // No invoices or debit memos with a balance were returned for that account, so set to null:
            propertyToUpdate.Max_Overdue_Due_Date_Zuora__c = null;
            propertyToUpdate.Last_Bill_Send_Date_New_Charges_Zuora__c = null;
        }
    }

    private Boolean noLongerPastDue(Account propertyToUpdate) {
        return propertyToUpdate.Max_Overdue_Due_Date_Zuora__c == null || propertyToUpdate.Max_Overdue_Due_Date_Zuora__c >= System.today();
    }

    private Case getCaseToReactivateCustomer(Zuora__CustomerAccount__c zuoraAccount) {
        Case collectionsCase = caseFactory.getCase('Collections');
        collectionsCase.Subject = '67-90 days past due customer fully paid their balance';
        collectionsCase.Description = zuoraAccount.Name + ' (' + zuoraAccount.Zuora__Account__r.Id + ') was at ' +
            zuoraAccount.Zuora__Account__r.Days_Past_Due__c + ' days past due and fully paid their balance. ' +
            'Please review their subscriptions status to see if they should be reactivated';
        collectionsCase.AccountId = zuoraAccount.Zuora__Account__r.Parent_Account__c;
        collectionsCase.Category__c = 'Billing-Payment';
        collectionsCase.Priority = 'Medium';
        collectionsCase.Product_Line__c = 'Community Solar';
        collectionsCase.Origin = 'Other';
        collectionsCase.Case_Type__c = 'BlueWave';
        collectionsCase.Disable_Followup_Email__c = true;
        return collectionsCase;
    }

    @SuppressWarnings('PMD.FieldNamingConventions')
    private class AccountSummary {
        public Decimal TotalBalance;
        public Date MinDueDate;
        public Date LastBillSendDate;
    }
    @TestVisible
    @SuppressWarnings('PMD.FieldNamingConventions')
    private class BalanceQueryResult {
        public Decimal MemoBalance;
        public Date MemoDueDate;
        public Date LastBillSendDate;
        public Decimal InvoiceBalance;
        public Date InvoiceDueDate;
        public String AccountId;
    }

    private static Map<String, AccountSummary> summarizeBalanceQueryResult(String queryResponse) {
        Map<String, AccountSummary> zuoraIdToAccountSummary = new Map<String, AccountSummary>();
        List<BalanceQueryResult> results;
        results = (List<BalanceQueryResult>) JSON.deserialize(queryResponse, List<BalanceQueryResult>.class);

        for (BalanceQueryResult result : results) {
            AccountSummary summary = new AccountSummary();
            summary.TotalBalance = Util.nullToZero(result.MemoBalance) + Util.nullToZero(result.InvoiceBalance);
            summary.MinDueDate = DateUtil.min(result.MemoDueDate, result.InvoiceDueDate);
            summary.LastBillSendDate = result.LastBillSendDate;
            zuoraIdToAccountSummary.put(result.AccountId, summary);
        }
        return zuoraIdToAccountSummary;
    }
}