src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Max_Overdue_Due_Date_Zuora__c</fullName>
        <inlineHelpText>Zuora Data : Due date of oldest invoice or debit memo with a balance</inlineHelpText>
        <label>Max Overdue Due Date Zuora</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Max_Overdue_Due_Date__c</fullName>
        <label>Max Overdue Due Date</label>
        <summarizedField>Account_Bill__c.Due_Date_SB__c</summarizedField>
        <summaryFilterItems>
            <field>Account_Bill__c.Balance_Net_Late_Payments__c</field>
            <operation>greaterThan</operation>
            <value>1</value>
        </summaryFilterItems>
        <summaryForeignKey>Account_Bill__c.Parent_Account__c</summaryForeignKey>
        <summaryOperation>min</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Total_Outstanding_Balance_Zuora__c</fullName>
        <inlineHelpText>Zuora Data: sum of balance on all debit memos and invoices</inlineHelpText>
        <label>Total Outstanding Balance Zuora</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Outstanding_Balance__c</fullName>
        <inlineHelpText>Should not be negative, unless cross-subscribed: (Due This Month + Late Fees + Adjustments + Previous Overpayments) - Payments Applied to SB</inlineHelpText>
        <label>Total Outstanding Balance</label>
        <summarizedField>Account_Bill__c.Outstanding_Balance_Rollup__c</summarizedField>
        <summaryFilterItems>
            <field>Account_Bill__c.Published__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>Account_Bill__c.Parent_Account__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Error_Log__c.object
<CustomObject>
    <description>Used for custom logging</description>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <length>130000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Method__c</fullName>
        <label>Method</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Error Log</label>
    <nameField>
        <displayFormat>EL-{0000}</displayFormat>
        <label>Error log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Shared_Solar_System__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>To change this system, use the Change SSS quick action</inlineHelpText>
        <label>Shared Solar System</label>
        <referenceTo>Shared_Solar_System__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Shared_Solar_System__c.object
<CustomObject
     >
    <articleTypeChannelDisplay n1:nil="true" />
    <customSettingsType n1:nil="true" />
    <description n1:nil="true" />
    <eventType n1:nil="true" />
    <fields>
        <fullName>Class__c</fullName>
        <formula>IF ( OR( 

Name = &quot;Oxford Barrett St. P2&quot;, Name = &quot;Oxford Barrett St. P1&quot;), &quot;Class 2&quot;,

IF(AND(   Total_System_Size_kW_AC__c &gt; 60, Total_System_Size_kW_AC__c &lt;= 1000), &quot;Class 2&quot;, 

IF ( Total_System_Size_kW_AC__c &gt; 1000, &quot;Class 3&quot;, null)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>MA Specific
Based on size of project (1MW), if the SSS falls into Class II or Class III categories</inlineHelpText>
        <label>System Class</label>
        <type>Text</type>
    </fields>
    <gender n1:nil="true" />
    <household>false</household>
    <label>Shared Solar System</label>
    <nameField>
        <label>Shared Solar System Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shared Solar Systems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <startsWith n1:nil="true" />
</CustomObject>

src/objects/UASB__c.object
<CustomObject
     >
    <description n1:nil="true" />
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Utility Account Subscription Bills</relationshipLabel>
        <relationshipName>Utility_Account_Subscription_Bills</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shared_Solar_System__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Shared Solar System</label>
        <referenceTo>Shared_Solar_System__c</referenceTo>
        <relationshipLabel>Utility Account Subscription Bills</relationshipLabel>
        <relationshipName>Utility_Account_Subscription_Bills</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Utility Account Subscription Bill</label>
    <nameField>
        <displayFormat>UASB-{0000000}</displayFormat>
        <label>Utility Account Subscription Bill Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Utility Account Subscription Bills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CSCancellationSchedulerTest.cls
/**
 * Created by Sarah Renfro on 12/13/2018.
 */

@IsTest
private class CSCancellationSchedulerTest {
    @TestSetup public static void setupTestData() {
        CustomerCommunicationHandlerTest.setupData();
    }

    @IsTest
    static void testExecute() {
        List<Shared_Solar_System__c> sss = [SELECT Id FROM Shared_Solar_System__c ORDER BY Name ASC ];

        CSCancellationServiceTest.createBills(System.today() - 88, sss[0].Id);

        UASB__c uasb = [
            SELECT Id, Opportunity__r.AccountId
            FROM UASB__c
            LIMIT 1
        ];

        Account acct = [
            SELECT Id,
                Max_Overdue_Due_Date_Zuora__c,
                Total_Outstanding_Balance_Zuora__c,
                Max_Overdue_Due_Date__c,
                Total_Outstanding_Balance__c
            FROM Account
            WHERE Id = : uasb.Opportunity__r.AccountId
            LIMIT 1
        ];
        acct.Max_Overdue_Due_Date_Zuora__c = System.Today().addDays(-68);
        acct.Total_Outstanding_Balance_Zuora__c = 12.00;
        update acct;

        Test.startTest();
        CSCancellationScheduler cancellationScheduler = new CSCancellationScheduler();
        cancellationScheduler.execute(null);
        Test.stopTest();

        // There should be one overdue account, with opps set to cancelled, but not yet removed
        System.assertEquals(1, cancellationScheduler.overdueAccounts.size());
        System.assertEquals(1, cancellationScheduler.cancelledOpportunities.size());
        System.assertEquals(0, cancellationScheduler.accountsRemovedFromAllProjects.size());

        // There should be just one error log describing the results
        List<Error_Log__c> errorLogs = [SELECT Message__c FROM Error_Log__c WHERE Class__c = 'CSCancellationScheduler'];
        System.assertEquals(1, errorLogs.size());
        System.assert(errorLogs[0].Message__c.contains('Overdue Accounts set as overdue:'),
            'Expected an error log with a cancellation summary, but got this instead:' + errorLogs[0].Message__c);
        System.assert(errorLogs[0].Message__c.contains('Cancelled Opps:'),
            'Expected an error log with a cancellation summary, but got this instead:' + errorLogs[0].Message__c);
    }

    @IsTest
    static void testPreview() {
        CustomerCommunicationHandlerTest.setDaysPastDue(System.Today().addDays(-68), 10);

        List<Error_Log__c> errorLogs = [SELECT Id FROM Error_Log__c];
        System.assertEquals(0, errorLogs.size(), 'Expected no error logs');

        Test.startTest();
        CSCancellationScheduler cancellationScheduler = new CSCancellationScheduler(true);
        cancellationScheduler.execute(null);
        Test.stopTest();

        errorLogs = [SELECT Id, Method__c FROM Error_Log__c];
        System.assertEquals(1, errorLogs.size());
        System.assertEquals('previewCancellation', errorLogs[0].Method__c, 'Expected a previewCancellation error log');
    }
}