src/objects/Account_Bill__c.object
<CustomObject>
    <fields>
        <fullName>Adjustments__c</fullName>
        <inlineHelpText>Shows the total adjustments the customer receives, even if only some of the adjustment is applied this bill (for instance, if they get a credit for more than their current bill)</inlineHelpText>
        <label>Adjustments</label>
        <summarizedField>System_Bill__c.Adjustments__c</summarizedField>
        <summaryForeignKey>System_Bill__c.Account_Bill__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Balance_Net_Late_Payments__c</fullName>
        <label>Balance Net of Late Payments</label>
        <summarizedField>System_Bill__c.Balance_Net_Late_Payments__c</summarizedField>
        <summaryForeignKey>System_Bill__c.Account_Bill__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Bill_Number__c</fullName>
        <label>Bill Number</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Carry_Over_Balance__c</fullName>
        <label>Carry Over Balance</label>
        <summarizedField>System_Bill__c.Carry_Over_Balance__c</summarizedField>
        <summaryForeignKey>System_Bill__c.Account_Bill__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Bill Statment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Due_This_Month__c</fullName>
        <label>Due This Month</label>
        <summarizedField>System_Bill__c.Due_This_Month__c</summarizedField>
        <summaryForeignKey>System_Bill__c.Account_Bill__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Late_Fee_Payments__c</fullName>
        <label>Late Fee Payments</label>
        <summarizedField>System_Bill__c.Late_Fee_Payments__c</summarizedField>
        <summaryForeignKey>System_Bill__c.Account_Bill__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Late_Fees__c</fullName>
        <label>Late Fees</label>
        <summarizedField>System_Bill__c.Late_Fees__c</summarizedField>
        <summaryForeignKey>System_Bill__c.Account_Bill__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Late_Payments__c</fullName>
        <label>Late Payments</label>
        <summarizedField>System_Bill__c.Late_Payments__c</summarizedField>
        <summaryForeignKey>System_Bill__c.Account_Bill__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Payment_Plan_Balance__c</fullName>
        <label>Payment Plan Balance</label>
        <summarizedField>System_Bill__c.Payment_Plan_Balance__c</summarizedField>
        <summaryForeignKey>System_Bill__c.Account_Bill__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Payments_Net_Previous_Balances__c</fullName>
        <label>Payments Net Previous Balances</label>
        <summarizedField>System_Bill__c.Payments_Net_Previous_Balances__c</summarizedField>
        <summaryForeignKey>System_Bill__c.Account_Bill__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Previous_Month_Overdue_Balance__c</fullName>
        <label>Previous Month Overdue Balance</label>
        <summarizedField>System_Bill__c.Previous_Month_Overdue_Balance__c</summarizedField>
        <summaryForeignKey>System_Bill__c.Account_Bill__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Shared_Solar_System__c</fullName>
        <label>Shared Solar System</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_Due__c</fullName>
        <label>Total Due</label>
        <summarizedField>System_Bill__c.Total_Due__c</summarizedField>
        <summaryForeignKey>System_Bill__c.Account_Bill__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Total_Payments_This_Month__c</fullName>
        <formula>Overpayment_Amount_Rollup__c +  Total_Payments_SB__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Payments This Month</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Unique_ID__c</fullName>
        <externalId>true</externalId>
        <label>Unique ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Account Bill</label>
    <nameField>
        <label>Account Bill Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Bills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Shared_Solar_System__c.object
<CustomObject
     >
    <articleTypeChannelDisplay n1:nil="true" />
    <customSettingsType n1:nil="true" />
    <description n1:nil="true" />
    <eventType n1:nil="true" />
    <fields>
        <fullName>Unique_ID__c</fullName>
        <displayFormat>SSS-{000000}</displayFormat>
        <externalId>true</externalId>
        <label>Unique ID</label>
        <type>AutoNumber</type>
    </fields>
    <gender n1:nil="true" />
    <household>false</household>
    <label>Shared Solar System</label>
    <nameField>
        <label>Shared Solar System Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shared Solar Systems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <startsWith n1:nil="true" />
</CustomObject>

src/objects/System_Bill__c.object
<CustomObject>
    <fields>
        <fullName>Account_Bill__c</fullName>
        <label>Account Bill</label>
        <referenceTo>Account_Bill__c</referenceTo>
        <relationshipLabel>System Bills</relationshipLabel>
        <relationshipName>System_Bills</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Adjustments__c</fullName>
        <label>Adjustments</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Amount_to_Add__c</fullName>
        <label>XX Amount to Add</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Amount_to_Deduct__c</fullName>
        <label>XX Amount to Deduct</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Balance_Net_Late_Payments__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>Used for collections and days past due. Calculated when bills are generated as Due This Month - Payments Applied</inlineHelpText>
        <label>Balance Net Late Payments</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Bill_Number__c</fullName>
        <label>Bill Number</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Carry_Forward_Adjustments__c</fullName>
        <defaultValue>0</defaultValue>
        <label>XX Carry Forward Adjustments</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Carry_Over_Balance__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Carry Over Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Date_Refunded__c</fullName>
        <label>Date Refunded</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <inlineHelpText>The Production Update date, set when creating the System Bill</inlineHelpText>
        <label>Bill Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_of_Last_Payment__c</fullName>
        <label>Date of Last Payment</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Distribute_This_Balance_12mo__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Distribute as Payment Plan? (12 months)</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Distribute_This_Balance_as_Payment_Plan__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Distribute as Payment Plan? (6 months)</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Due_This_Month__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>New charges calculated this month (not including late fees, adjustments, etc.)</inlineHelpText>
        <label>Due This Month</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Early_Payments__c</fullName>
        <label>XXEarly Payments</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Late_Fee_Payments__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Late Fee Payments</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Late_Fees__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Late Fees</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Late_Payments__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>Payments applied after this bill was due.</inlineHelpText>
        <label>Late Payments</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>System Bills</relationshipLabel>
        <relationshipName>System_Bills</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Past_Bill_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Past Bill Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Past_Bill_Payment__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Past Bill Payment</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Payment_Plan_Balance__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Payment Plan Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Payment_Plan_Balance_to_Distribute__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Payment Plan Balance to Distribute</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Payments_Net_Previous_Balances__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>Total payments applied this period - Late Payments</inlineHelpText>
        <label>Payments Net Previous Balances</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Previous_Month_Overdue_Balance__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Previous Month Overdue Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Property_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>System Bills</relationshipLabel>
        <relationshipName>System_Bills</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Recurring_Billing__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Recurring Billing</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Refund_this_Balance__c</fullName>
        <defaultValue>false</defaultValue>
        <label>XX Add Adjustment</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Shared_Solar_System_ID2__c</fullName>
        <label>Shared Solar System ID2</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Shared_Solar_System__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Shared Solar System</label>
        <referenceTo>Shared_Solar_System__c</referenceTo>
        <relationshipLabel>System Bills</relationshipLabel>
        <relationshipName>System_Bills</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total_Due__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>Due This Month + Previous Month&apos;s Overdue Balance + Late Fees and Adjustments</inlineHelpText>
        <label>Total Due</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Payments_This_Month__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total Payments This Month</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Unique_ID__c</fullName>
        <externalId>true</externalId>
        <label>Unique ID</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Waive_Late_Fees__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Waive Late Fees</label>
        <type>Checkbox</type>
    </fields>
    <label>System Bill</label>
    <nameField>
        <label>System Bill Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>System Bills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SystemBillQualityCheckerTest.cls
/**
 * Created by pyao on 12/17/2018.
 */
@IsTest
public with sharing class SystemBillQualityCheckerTest {
    @TestSetup
    public static void setupTestData() {
        CSPaymentTest.CSPaymentSetupTestData();
    }

    @IsTest
    public static void testTooManyDecimalsOnInsert() {
        List<System_Bill__c> systemBills = [
            SELECT Id, Name, Account_Bill__c, Property_Account__c, Opportunity__c, Shared_Solar_System__c, Shared_Solar_System_ID2__c,
                Unique_ID__c, Total_Due__c, Balance_Net_Late_Payments__c, Carry_Over_Balance__c, Due_This_Month__c, Bill_Number__c,
                Date__c, Date_of_Last_Payment__c, Late_Fee_Payments__c, Late_Fees__c, Late_Payments__c,
                Payments_Net_Previous_Balances__c, Previous_Month_Overdue_Balance__c, Total_Payments_This_Month__c,
                Waive_Late_Fees__c, Recurring_Billing__c, Payment_Plan_Balance__c, Payment_Plan_Balance_to_Distribute__c,
                Distribute_This_Balance_as_Payment_Plan__c, Past_Bill_Amount__c, Past_Bill_Payment__c, Refund_this_Balance__c,
                Date_Refunded__c, Adjustments__c, Amount_to_Add__c, Amount_to_Deduct__c, Early_Payments__c,
                Carry_Forward_Adjustments__c, Distribute_This_Balance_12mo__c, Carry_Forward_Payments__c, Balance_Adjustments__c
            FROM System_Bill__c
            LIMIT 1
        ];
        List<Error_Log__c> errorLogs = [SELECT Id FROM Error_Log__c WHERE Class__c = 'SystemBillQualityChecker'];
        System.assertEquals(0, errorLogs.size());

        Test.startTest();
        System_Bill__c systemBillWithTooManyDecimals = systemBills[0].clone();
        systemBillWithTooManyDecimals.Adjustments__c = .0012345;
        insert systemBillWithTooManyDecimals;
        Test.stopTest();

        errorLogs = [SELECT Id FROM Error_Log__c WHERE Class__c = 'SystemBillQualityChecker'];
        System.assertEquals(1, errorLogs.size());
    }

    @IsTest
    public static void testTooManyDecimalsOnUpdate() {
        List<System_Bill__c> systemBills = [SELECT Id FROM System_Bill__c LIMIT 1];
        List<Error_Log__c> errorLogs = [SELECT Id FROM Error_Log__c WHERE Class__c = 'SystemBillQualityChecker'];
        System.assertEquals(0, errorLogs.size());

        Test.startTest();
        systemBills[0].Total_Payments_This_Month__c = .0012345;
        update systemBills[0];
        Test.stopTest();

        errorLogs = [SELECT Id FROM Error_Log__c WHERE Class__c = 'SystemBillQualityChecker'];
        System.assertEquals(1, errorLogs.size());
    }

    @IsTest
    public static void testGetSBList() {
        Test.startTest();
        Map<Id, System_Bill__c> systemBillMap = new Map<Id, System_Bill__c>([SELECT Id FROM System_Bill__c]);
        List<SObject> systemBillsWithCurrencyFields = SystemBillQualityChecker.getSystemBillsWithCurrencyFields(new List<Id>(systemBillMap.keySet()));
        System.assertEquals(systemBillMap.values().size(), systemBillsWithCurrencyFields.size());

    }
}