src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Partner_Account</fullName>
        <active>true</active>
        <label>Partner Account</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Commission_Structure__c.object
<CustomObject>
    <fields>
        <fullName>Cents_kW_DC_First_Bill_Paid__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Enter the cents per kW DC the partner receives when the customer pays their first bill. This could be zero if they get the second part of their commission after the first bill is sent.</description>
        <inlineHelpText>Enter the cents per kW DC the partner receives when the customer pays their first bill. This could be zero if they get the second part of their commission after the first bill is sent.</inlineHelpText>
        <label>Cents/kW DC First Bill Paid</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Cents_kW_DC_First_Bill__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Enter the cents per kW DC the partner receives up when the customer gets their first bill. This could be zero if they get the second part of their commission after the first bill is fully paid.</description>
        <inlineHelpText>Enter the cents per kW DC the partner receives up when the customer gets their first bill. This could be zero if they get the second part of their commission after the first bill is fully paid.</inlineHelpText>
        <label>Cents/kW DC First Bill Sent</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Cents_kW_DC_Up_Front__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Enter the cents per kW DC the partner receives up front, after full contract execution.</description>
        <inlineHelpText>Enter the cents per kW DC the partner receives up front, after full contract execution.</inlineHelpText>
        <label>Cents/kW DC Contract Execution</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Partner_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Partner Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Commission Structures</relationshipLabel>
        <relationshipName>Commission_Structures</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Commission Structure</label>
    <nameField>
        <label>Commission Structure Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Commission Structures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Commission_Structure__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <inlineHelpText>Controls how Commission Payments are generated</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Variable by kW</fullName>
            </value>
            <value>
                <fullName>Fixed by Annual kWh</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Active_Communities_User__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>This field has one hour delay from when the user is activated.</inlineHelpText>
        <label>Active Communities User</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>User record associated to a contact. Only applicable to internal users</inlineHelpText>
        <label>User</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.UserType</field>
                <operation>equals</operation>
                <value>Standard</value>
            </filterItems>
            <infoMessage>This lookup is for internal users.</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </recordTypes>
    <recordTypes>
        <fullName>Partner_Contact</fullName>
        <active>true</active>
        <label>Partner Contact</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Partner_Shared_Solar_System_Eligibility__c.object
<CustomObject>
    <description>Control partner access to Shared Solar Systems</description>
    <fields>
        <fullName>Account__c</fullName>
        <inlineHelpText>Partner Account</inlineHelpText>
        <label>Partner Account</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The Account must have a record type of Partner Account</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Partner Account</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Shared Solar Systems</relationshipLabel>
        <relationshipName>Partner_Shared_Solar_System_Accesses</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Commission_Structure__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Commission Structure that applies when a partner acquires customers for this Shared Solar System</inlineHelpText>
        <label>Commission Structure</label>
        <referenceTo>Commission_Structure__c</referenceTo>
        <relationshipLabel>Partner Shared Solar System</relationshipLabel>
        <relationshipName>Partner_Shared_Solar_System_Accesses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shared_Solar_System__c</fullName>
        <inlineHelpText>Shared Solar System that the partner is eligible to sell</inlineHelpText>
        <label>Shared Solar System</label>
        <referenceTo>Shared_Solar_System__c</referenceTo>
        <relationshipLabel>Eligible Partners</relationshipLabel>
        <relationshipName>Partner_Shared_Solar_System_Accesses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <inlineHelpText>Date on which this record begins to be active</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Partner Shared Solar System Access</label>
    <nameField>
        <displayFormat>PSSA-{0000}</displayFormat>
        <label>Partner Shared Solar System Access Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Shared Solar System Accesses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Shared_Solar_System__c.object
<CustomObject
     >
    <articleTypeChannelDisplay n1:nil="true" />
    <customSettingsType n1:nil="true" />
    <description n1:nil="true" />
    <eventType n1:nil="true" />
    <gender n1:nil="true" />
    <household>false</household>
    <label>Shared Solar System</label>
    <nameField>
        <label>Shared Solar System Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shared Solar Systems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <startsWith n1:nil="true" />
</CustomObject>

force-app/main/default/classes/UserTriggerHandlerTest.cls
@IsTest
private without sharing class UserTriggerHandlerTest {

    @IsTest
    private static void afterInsertTest() {
        Account partnerAccount = new Account(
            Name = 'Perch Energy',
            RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Partner_Account').getRecordTypeId()
        );
        insert partnerAccount;

        Contact partnerContact = new Contact(
            AccountId = partnerAccount.Id,
            FirstName = 'Test',
            LastName = 'Partner',
            RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Partner_Contact').getRecordTypeId()
        );
        insert partnerContact;

        Contact partnerContact1 = new Contact(
            AccountId = partnerAccount.Id,
            FirstName = 'Test1',
            LastName = 'Partner1',
            RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Partner_Contact').getRecordTypeId()
        );
        insert partnerContact1;

        Shared_Solar_System__c sss = new Shared_Solar_System__c(
            Name = 'Test Shared Solar System'
        );
        insert sss;

        Commission_Structure__c commissionStructure = new Commission_Structure__c(
            Name = 'Test Commission Structure',
            Cents_kW_DC_First_Bill__c = 0.03,
            Cents_kW_DC_Up_Front__c = 0.08,
            Cents_kW_DC_First_Bill_Paid__c = 0.02,
            Partner_Account__c = partnerAccount.Id,
            Type__c = 'Variable by kW'
        );
        insert commissionStructure;

        Partner_Shared_Solar_System_Eligibility__c eligibility = new Partner_Shared_Solar_System_Eligibility__c(
            Account__c = partnerAccount.Id,
            Shared_Solar_System__c = sss.Id,
            Commission_Structure__c = commissionStructure.Id,
            Start_Date__c = Date.newInstance(2020,1,1)
        );
        insert eligibility;

        Test.startTest();
        User u = new User(
            ProfileId = [SELECT Id FROM Profile WHERE Name = 'Partner Portal Community User'].Id,
            ContactId = partnerContact.Id,
            FirstName = 'Partner',
            LastName = 'Test',
            Email = 'test@gearscrm.test',
            Username = 'test@gearscrm.test' + System.currentTimeMillis(),
            CommunityNickname = 'pt',
            CompanyName = 'GearsCRM',
            Title = 'Tester',
            Alias = 'test',
            TimeZoneSidKey = 'America/New_York',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US'
        );
        User standardUser = new User(
            ProfileId = [SELECT Id FROM Profile WHERE Name = 'Standard User'].Id,
            FirstName = 'User',
            LastName = 'Test',
            Email = 'test@perchenergy.com',
            Username = 'test@perchenergy.com' + System.currentTimeMillis(),
            CommunityNickname = 'ptt',
            CompanyName = 'GearsCRM',
            Title = 'Tester',
            Alias = 'test',
            TimeZoneSidKey = 'America/New_York',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US'
        );
        User communitySolarCommunityUser = new User(
            ProfileId = [SELECT Id FROM Profile WHERE Name = 'Community Solar Community User'].Id,
            ContactId = partnerContact1.Id,
            FirstName = 'Partnedr',
            LastName = 'Test1',
            Email = 'test3423@perchenergy.com',
            Username = 'test@perchenergy.com' + System.currentTimeMillis(),
            CommunityNickname = 'pt23',
            CompanyName = 'GearsCRM',
            Title = 'Tester',
            Alias = 'test',
            TimeZoneSidKey = 'America/New_York',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US'
        );

        List<User> usersList=new List<User>();
        usersList.add(u);
        usersList.add(standardUser);
        usersList.add(communitySolarCommunityUser);
        insert usersList;
        Test.stopTest();
        List<Shared_Solar_System__Share> shares = [
            SELECT Id, ParentId, UserOrGroupId
            FROM Shared_Solar_System__Share
        ];
        Contact cnt=[SELECT Id,Active_Communities_User__c FROM Contact WHERE User__c = :standardUser.Id];
        System.assertNotEquals(null, cnt.Id, 'Expected to create a Contact related to the Perch Energy account after inserting a user with a Standard license type and perchenergy.com in the email');
        User ur=[SELECT Id,IsPortalEnabled FROM User WHERE Id= :communitySolarCommunityUser.Id];
        System.assertEquals(2, shares.size(), 'Expected 2 Shared_Solar_System__share record to be created');
        System.assertEquals(sss.Id, shares[0].ParentId, 'Expected the Shared_Solar_System__share record to have a ParentId equal to the ID of the test Shared_Solar_System__c record');
        System.assertEquals(u.Id, shares[0].UserOrGroupId, 'Expected the Shared_Solar_System__share record to have a UserOrGroupId equal to the ID of the test User record');
        System.assertEquals(true, ur.IsPortalEnabled, 'Expected the user record to have IsPortalEnabled');
    }
    @IsTest
    private static void afterUpdateTest() {
        Account partnerAccount = new Account(
            Name = 'Perch Energy',
            RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Partner_Account').getRecordTypeId()
        );
        insert partnerAccount;

        Contact partnerContact = new Contact(
            AccountId = partnerAccount.Id,
            FirstName = 'Partner',
            LastName = 'Test',
            Email = 'test@perchenergy.com',
            RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Partner_Contact').getRecordTypeId()
        );
        insert partnerContact;

        User communitySolarCommunityUser = new User(
            ProfileId = [SELECT Id FROM Profile WHERE Name = 'Community Solar Community User'].Id,
            ContactId = partnerContact.Id,
            FirstName = 'Partnedr',
            LastName = 'Test1',
            Email = 'test567@perchenergy.com',
            Username = 'test@perchenergy.com' + System.currentTimeMillis(),
            CommunityNickname = 'pt23',
            CompanyName = 'GearsCRM',
            Title = 'Tester',
            Alias = 'test',
            TimeZoneSidKey = 'America/New_York',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            IsActive=true,
            LocaleSidKey = 'en_US'
        );

        List<User> usersList=new List<User>();
        usersList.add(communitySolarCommunityUser);
        insert usersList;

        Shared_Solar_System__c sss = new Shared_Solar_System__c(
            Name = 'Test Shared Solar System'
        );
        insert sss;

        Commission_Structure__c commissionStructure = new Commission_Structure__c(
            Name = 'Test Commission Structure',
            Cents_kW_DC_First_Bill__c = 0.03,
            Cents_kW_DC_Up_Front__c = 0.08,
            Cents_kW_DC_First_Bill_Paid__c = 0.02,
            Partner_Account__c = partnerAccount.Id,
            Type__c = 'Variable by kW'
        );
        insert commissionStructure;

        Partner_Shared_Solar_System_Eligibility__c eligibility = new Partner_Shared_Solar_System_Eligibility__c(
            Account__c = partnerAccount.Id,
            Shared_Solar_System__c = sss.Id,
            Commission_Structure__c = commissionStructure.Id,
            Start_Date__c = Date.newInstance(2020,1,1)
        );
        insert eligibility;
        Test.startTest();
        System.runAs(communitySolarCommunityUser){
            communitySolarCommunityUser.Email='test891@perchenergy.com';
            update communitySolarCommunityUser;
            User u=[SELECT Id,Email FROM User WHERE Id=:communitySolarCommunityUser.Id];
            System.assertEquals(u.Email, 'test891@perchenergy.com', 'User email should be updated');
        }
        Test.stopTest();
    }
    @IsTest
    private static void afterUpdateTestActiveCheckBox() {
        Account partnerAccount = new Account(
            Name = 'Perch Energy',
            RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Partner_Account').getRecordTypeId()
        );
        insert partnerAccount;

        Contact partnerContact = new Contact(
            AccountId = partnerAccount.Id,
            FirstName = 'Partner',
            LastName = 'Test',
            Email = 'test@perchenergy.com',
            RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Partner_Contact').getRecordTypeId()
        );
        insert partnerContact;

        User communitySolarCommunityUser = new User(
            ProfileId = [SELECT Id FROM Profile WHERE Name = 'Community Solar Community User'].Id,
            ContactId =partnerContact.Id,
            FirstName = 'Partnedr',
            LastName = 'Test1',
            Email = 'test567@perchenergy.com',
            Username = 'test@perchenergy.com' + System.currentTimeMillis(),
            CommunityNickname = 'pt23',
            CompanyName = 'GearsCRM',
            Title = 'Tester',
            Alias = 'test',
            TimeZoneSidKey = 'America/New_York',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            IsActive=true,
            LocaleSidKey = 'en_US'
        );

        List<User> usersList=new List<User>();
        usersList.add(communitySolarCommunityUser);
        insert usersList;
        User usr=[SELECT Id,IsPortalEnabled FROM User WHERE Id=:UserInfo.getUserId()];

        Test.startTest();
        System.runAs(usr){
            partnerContact.Active_Communities_User__c=false;
            update partnerContact;
            communitySolarCommunityUser.isActive=true;
            communitySolarCommunityUser.IsPortalEnabled=false;
            update communitySolarCommunityUser;
        }
        Test.stopTest();
        Contact cnt=[SELECT Id,Email,Active_Communities_User__c FROM Contact WHERE Id=:partnerContact.Id];
        System.assertEquals(cnt.Active_Communities_User__c, true, 'Active Communities User value should be true');
        User u = [SELECT Id,IsPortalEnabled from User where id =: communitySolarCommunityUser.id];
        System.assertEquals(true, u.IsPortalEnabled, 'Expected the user record to have IsPortalEnabled');
    }
}