src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Late_Fee_Payments__c</fullName>
        <label>Late Fee Payments</label>
        <summarizedField>Account_Bill__c.Late_Fee_Payments__c</summarizedField>
        <summaryForeignKey>Account_Bill__c.Parent_Account__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <recordTypes>
        <fullName>Property</fullName>
        <active>true</active>
        <label>Property</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/System_Bill__c.object
<CustomObject>
    <fields>
        <fullName>Adjustments__c</fullName>
        <label>Adjustments</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Amount_to_Add__c</fullName>
        <label>XX Amount to Add</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Amount_to_Deduct__c</fullName>
        <label>XX Amount to Deduct</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Balance_Net_Late_Payments__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>Used for collections and days past due. Calculated when bills are generated as Due This Month - Payments Applied</inlineHelpText>
        <label>Balance Net Late Payments</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Bill_Number__c</fullName>
        <label>Bill Number</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Carry_Forward_Adjustments__c</fullName>
        <defaultValue>0</defaultValue>
        <label>XX Carry Forward Adjustments</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Carry_Over_Balance__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Carry Over Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Date_Refunded__c</fullName>
        <label>Date Refunded</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Discounted_Bill__c</fullName>
        <label>Discounted Bill</label>
        <summarizedField>UASB__c.Discounted_Bill__c</summarizedField>
        <summaryForeignKey>UASB__c.System_Bill__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Distribute_This_Balance_12mo__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Distribute as Payment Plan? (12 months)</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Distribute_This_Balance_as_Payment_Plan__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Distribute as Payment Plan? (6 months)</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Due_This_Month__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>New charges calculated this month (not including late fees, adjustments, etc.)</inlineHelpText>
        <label>Due This Month</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Late_Fee_Payments__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Late Fee Payments</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Late_Fees__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Late Fees</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Late_Payments__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>Payments applied after this bill was due.</inlineHelpText>
        <label>Late Payments</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Past_Bill_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Past Bill Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Past_Bill_Payment__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Past Bill Payment</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Payment_Plan_Balance__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Payment Plan Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Payment_Plan_Balance_to_Distribute__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Payment Plan Balance to Distribute</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Payments_Net_Previous_Balances__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>Total payments applied this period - Late Payments</inlineHelpText>
        <label>Payments Net Previous Balances</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Previous_Month_Overdue_Balance__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Previous Month Overdue Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Property_Account_ID__c</fullName>
        <formula>Property_Account__r.Id</formula>
        <label>Property Account ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Refund_this_Balance__c</fullName>
        <defaultValue>false</defaultValue>
        <label>XX Add Adjustment</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Savings__c</fullName>
        <label>Savings</label>
        <summarizedField>UASB__c.Savings__c</summarizedField>
        <summaryForeignKey>UASB__c.System_Bill__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Shared_Solar_System_ID__c</fullName>
        <formula>LEFT(Shared_Solar_System_ID2__c,15)</formula>
        <label>Shared Solar System ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_Due__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>Due This Month + Previous Month&apos;s Overdue Balance + Late Fees and Adjustments</inlineHelpText>
        <label>Total Due</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Payments_This_Month__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total Payments This Month</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Waive_Late_Fees__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Waive Late Fees</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>YTD_Billed__c</fullName>
        <label>YTD Billed</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>YTD_Payments__c</fullName>
        <label>YTD Payments</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>System Bill</label>
    <nameField>
        <label>System Bill Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>System Bills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SystemBillAccountingLogicHandler.cls
// Accounting Logic Class
// Turning Accounting Logic Trigger into Class
// https://cs4.salesforce.com/01pj0000004XxuM

public with sharing class SystemBillAccountingLogicHandler {
    private boolean m_isExecuting = false;
    private Integer BatchSize = 0;
    
    public SystemBillAccountingLogicHandler (boolean isExecuting, Integer size){
        m_isExecuting = isExecuting;
        BatchSize = size;
    }
    
  public void OnBeforeUpdate (System_Bill__c[] newSystemBill){
      systemBillAccountingLogic(newSystemBill);
      }
  public void OnBeforeInsert (System_Bill__c[] newSystemBill){
      systemBillAccountingLogic(newSystemBill);
      }    

  private void systemBillAccountingLogic (List <System_Bill__c> systemBill){

    integer j;
    integer i;
    integer k;
    integer l;
    integer h;
    integer g;
    string stringPropertyAccount;
    decimal carryoverbalance = 0;  
    decimal pastbillamount = 0;
    decimal pastbillpayment = 0;
    list<id> propertyaccountIds = new list<id>();
    list<string> propertyaccountIdsstring = new list<string>();  
    list<decimal> previousmonthlist = new list<decimal>();  


    for(j = 0; j < systemBill.size(); j++){
        propertyaccountIds.add(systemBill.get(j).Property_Account_ID__c);
        stringPropertyAccount = string.valueOf(systemBill.get(j).Property_Account_ID__c);
        propertyaccountIdsstring.add(stringPropertyAccount);
        system.debug(propertyaccountIdsstring);
    }      

// List of all system bills (including previous months) associated with the property account

    List <System_Bill__c> listsystemBills = [SELECT Id, Property_Account_ID__c, Shared_Solar_System_ID__c, Bill_Number__c, Discounted_Bill__c,  
                                            Payments_Net_Previous_Balances__c, Waive_Late_Fees__c, Total_Payments_This_Month__c, Carry_Over_Balance__c, 
                                            Late_Payments__c, Balance_Net_Late_Payments__c, Distribute_This_Balance_12mo__c, 
                                            Late_Fee_Payments__c, Late_Fees__c, Carry_Forward_Adjustments__c, Due_This_Month__c, Payment_Plan_Balance__c, Total_Due__c, Distribute_This_Balance_as_Payment_Plan__c,
                                            Payment_Plan_Balance_to_Distribute__c, Savings__c
                                            FROM System_Bill__c
                                            WHERE Property_Account_ID__c IN : propertyaccountIdsstring ORDER BY Bill_Number__c DESC];

// For each triggered system bill, 

      for(j = 0; j < systemBill.size(); j++){
          string ParentID = systemBill.get(j).Property_Account_ID__c;
          system.debug(ParentID);

          string SSSid = systemBill.get(j).Shared_Solar_System_ID__c;
          system.debug(SSSid);
          
          decimal currentbill = systemBill.get(j).Bill_Number__c;
          decimal previousbill = currentbill-1 ; 
          decimal pastsixbills = 0;
          decimal pasttwelvebills = 0;
          system.debug(previousbill);
          
              if(currentbill>7) {
              pastsixbills = currentbill-7;}
                    else {pastsixbills = 0;}
              system.debug(pastsixbills);

              if(currentbill>13) {
              pasttwelvebills = currentbill-13;}
                    else {pasttwelvebills = 0;}
              system.debug(pasttwelvebills);
                    
          Decimal sumLateFees = 0;
          Decimal sumLateFeePay = 0;
          Decimal overdue = 0;
          Decimal ppbalance = 0;
          Decimal twelveppbalance = 0;
          Decimal ytdbilled = 0;
          Decimal ytdpayments = 0;
          boolean morerecentbills = FALSE;
          Decimal dueThisMonth = systemBill.get(j).Discounted_Bill__c ;  

          if(systemBill.get(j).Refund_this_Balance__c == TRUE){
              systemBill.get(j).Date_Refunded__c = system.today();
          }
          
          IF( systemBill.get(j).Late_Payments__c ==NULL){
          systemBill.get(j).Late_Payments__c=0;}
          
          IF( systemBill.get(j).Total_Payments_This_Month__c ==NULL){
          systemBill.get(j).Total_Payments_This_Month__c=0;}
          
          IF( systemBill.get(j).Payments_Net_Previous_Balances__c ==NULL){
          systemBill.get(j).Payments_Net_Previous_Balances__c =0 ;}
          
          IF( systemBill.get(j).Carry_Over_Balance__c ==NULL){
          systemBill.get(j).Carry_Over_Balance__c = 0 ;}
          
          IF( systemBill.get(j).Balance_Net_Late_Payments__c ==NULL){
          systemBill.get(j).Balance_Net_Late_Payments__c = 0 ;}
          
          IF( systemBill.get(j).Late_Fee_Payments__c ==NULL){
          systemBill.get(j).Late_Fee_Payments__c=0;}
          
          IF( systemBill.get(j).Late_Fees__c ==NULL){
          systemBill.get(j).Late_Fees__c=0;} 

          IF( systemBill.get(j).Carry_Forward_Adjustments__c ==NULL){
          systemBill.get(j).Carry_Forward_Adjustments__c=0;} 

         system.debug(currentbill);

// If first bill, there are no previous bills so logic is different
         
          if(currentbill == 1){

             systemBill.get(j).Due_This_Month__c = dueThisMonth;
             systemBill.get(j).Total_Due__c = dueThisMonth; 
             systemBill.get(j).Previous_Month_Overdue_Balance__c = 0 ;
             systemBill.get(j).Late_Fees__c = 0; 
             systemBill.get(j).Payment_Plan_Balance__c = 0;
             systemBill.get(j).Adjustments__c = 0;                             
             systemBill.get(j).Carry_Over_Balance__c = systemBill.get(j).Total_Due__c - systemBill.get(j).Total_Payments_This_Month__c;

            for(g=0; g<listsystemBills.size(); g++){
                if(listsystembills.get(g).Property_Account_ID__c == ParentID 
                   && listsystembills.get(g).Bill_Number__c > currentbill 
                   && listsystembills.get(g).Shared_Solar_System_ID__c == SSSid){
                         morerecentbills = TRUE;
                }
            } 

            if(systemBill.get(j).Refund_this_Balance__c == TRUE && systemBill.get(j).Amount_to_Add__c > 0){
                  systembill.get(j).Adjustments__c = -systembill.get(j).Amount_to_Add__c;
            }
                        else if(systemBill.get(j).Refund_this_Balance__c == TRUE && systemBill.get(j).Amount_to_Deduct__c > 0){
                            systembill.get(j).Adjustments__c = -1 * systembill.get(j).Amount_to_Deduct__c;
                        }

            if (systemBill.get(j).Distribute_This_Balance_as_Payment_Plan__c == TRUE || systemBill.get(j).Distribute_This_Balance_12mo__c == TRUE && morerecentbills == FALSE) {
                            systemBill.get(j).Payment_Plan_Balance_to_Distribute__c = systemBill.get(j).Carry_Over_Balance__c;
            }

            if (systemBill.get(j).Refund_this_Balance__c == FALSE){
                  systemBill.get(j).Balance_Net_Late_Payments__c = dueThisMonth - systemBill.get(j).Late_Payments__c - systemBill.get(j).Payments_Net_Previous_Balances__c; 
            }
                        else if (systemBill.get(j).Refund_this_Balance__c == TRUE){
                            systemBill.get(j).Balance_Net_Late_Payments__c = dueThisMonth + systemBill.get(j).Adjustments__c - systemBill.get(j).Late_Payments__c - systemBill.get(j).Payments_Net_Previous_Balances__c; 
                        }

          }
  
  // for each triggered bills, finds the previous month's bill (with same SSS and Property) 

          if(currentbill != 1){

                    for(h=0; h<listsystemBills.size();h++){
                               if(listsystembills.get(h).Property_Account_ID__c == ParentID 
                               && listsystembills.get(h).Bill_Number__c > currentbill 
                               && listsystembills.get(h).Shared_Solar_System_ID__c == SSSid){
                                      morerecentbills = TRUE;
                               }
                    }

                    for(i=0; i<listsystemBills.size();i++){
                            if(listsystembills.get(i).Property_Account_ID__c == ParentID 
                               && listsystembills.get(i).Bill_Number__c == previousbill 
                               && listsystembills.get(i).Shared_Solar_System_ID__c == SSSid){
                                    pastbillamount = listsystembills.get(i).Total_Due__c;
                                    pastbillpayment = listsystembills.get(i).Total_Payments_This_Month__c;

                                      if(listsystembills.get(i).Distribute_This_Balance_as_Payment_Plan__c == TRUE || listsystembills.get(i).Distribute_This_Balance_12mo__c == TRUE){
                                        carryoverbalance = 0;
                                        system.debug(carryoverbalance);
                                      }
                                          else {
                                            carryoverbalance = listsystembills.get(i).Carry_Over_Balance__c;
                                            system.debug(carryoverbalance);
                                          }
                              }     
                     }  

                     // Looks through past 6 months of bills for payment plan balances
                     for(k=0; k<listsystemBills.size();k++){
                            system.debug(listsystemBills.get(k).Bill_Number__c);
                            system.debug(listsystemBills.get(k).Distribute_This_Balance_as_Payment_Plan__c);
                            
                            if(listsystembills.get(k).Property_Account_ID__c == ParentID 
                                && listsystembills.get(k).Shared_Solar_System_ID__c == SSSid
                                && listsystembills.get(k).Bill_Number__c < currentbill 
                                && listsystembills.get(k).Bill_Number__c > pastsixbills
                                && listsystembills.get(k).Distribute_This_Balance_as_Payment_Plan__c == TRUE
                                && ppbalance == 0){
                                        ppbalance = listsystembills.get(k).Payment_Plan_Balance_to_Distribute__c / 6 ;
                            }

                            if(listsystembills.get(k).Property_Account_ID__c == ParentID 
                                && listsystembills.get(k).Shared_Solar_System_ID__c == SSSid
                                && listsystembills.get(k).Bill_Number__c < currentbill 
                                && listsystembills.get(k).Bill_Number__c > pasttwelvebills
                                && listsystembills.get(k).Distribute_This_Balance_12mo__c == TRUE
                                && ppbalance == 0){
                                        twelveppbalance = listsystembills.get(k).Payment_Plan_Balance_to_Distribute__c / 12 ;
                            }
                      }

                     // Sums past 12 months of bills for YTD data
                     for(l=0; l<listsystemBills.size();l++){
                            system.debug(listsystemBills.get(l).Bill_Number__c);
                            if(listsystembills.get(l).Property_Account_ID__c == ParentID 
                                && listsystembills.get(l).Shared_Solar_System_ID__c == SSSid
                                && listsystembills.get(l).Bill_Number__c <= currentbill 
                                && listsystembills.get(l).Bill_Number__c >= pasttwelvebills){
                                        ytdbilled = ytdbilled + listsystembills.get(l).Discounted_Bill__c + listsystembills.get(l).Late_Fees__c ;
                                        ytdpayments = ytdpayments + listsystembills.get(l).Total_Payments_This_Month__c;
                                }
                      }
                     
                  overdue = carryoverbalance;
                  system.debug(overdue);
                  system.debug(ppbalance);
                  system.debug(twelveppbalance);

                  systemBill.get(j).Previous_Month_Overdue_Balance__c = overdue;
                  systemBill.get(j).Due_This_Month__c = dueThisMonth; 
                  systemBill.get(j).Past_Bill_Amount__c = pastbillamount;
                  systemBill.get(j).Past_Bill_Payment__c = pastbillpayment;
                  systemBill.get(j).YTD_Billed__c = ytdbilled;
                  systemBill.get(j).YTD_Payments__c = ytdpayments;
                  systemBill.get(j).Adjustments__c = 0;
                    
                    if(ppbalance > 0){
                        systemBill.get(j).Payment_Plan_Balance__c = ppbalance;
                    }

                        else if(twelveppbalance > 0){
                            systemBill.get(j).Payment_Plan_Balance__c = twelveppbalance;
                        }           

                    if(systemBill.get(j).Waive_Late_Fees__c==FALSE){
                        systemBill.get(j).Late_Fees__c = (0.01*overdue);
                    }

                        else if(systemBill.get(j).Waive_Late_Fees__c==TRUE){
                                systemBill.get(j).Late_Fees__c = 0;
                        }

                    if(systemBill.get(j).Refund_this_Balance__c == TRUE && systemBill.get(j).Amount_to_Add__c > 0){
                          systemBill.get(j).Adjustments__c = systemBill.get(j).Amount_to_Add__c;
                    }

                        else if(systemBill.get(j).Refund_this_Balance__c == TRUE && systemBill.get(j).Amount_to_Deduct__c > 0){
                                  systemBill.get(j).Adjustments__c = -1 * systemBill.get(j).Amount_to_Deduct__c;
                        }

                    system.debug(systemBill.get(j).Late_Fees__c);
                    system.debug(systemBill.get(j).Adjustments__c);
                    systemBill.get(j).Total_Due__c = dueThisMonth + systemBill.get(j).Late_Fees__c + carryoverbalance + systemBill.get(j).Payment_Plan_Balance__c + systemBill.get(j).Adjustments__c;
                    system.debug(systemBill.get(j).Total_Due__c);
                    systemBill.get(j).Carry_Over_Balance__c = systemBill.get(j).Total_Due__c - systemBill.get(j).Total_Payments_This_Month__c;

                    // If the triggered bill is the original payment plan bill, don't push balance forward: 

                    if (systemBill.get(j).Distribute_This_Balance_as_Payment_Plan__c == TRUE || systemBill.get(j).Distribute_This_Balance_12mo__c == TRUE && morerecentbills == FALSE) {
                            systemBill.get(j).Payment_Plan_Balance_to_Distribute__c = systemBill.get(j).Carry_Over_Balance__c;
                    }

                    systemBill.get(j).Balance_Net_Late_Payments__c = dueThisMonth + systemBill.get(j).Carry_Forward_Adjustments__c - systemBill.get(j).Late_Payments__c - systemBill.get(j).Payments_Net_Previous_Balances__c; 

          } // end if current bill != 1     

        } // end triggered system bills
  }     

}