src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Create_Zuora_Account__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>When checked on a Property Account without a Zuora Id, a process is started to create an account in Zuora with the related Send Bills Contact. If the Account already has a Zuora Id, the process will create subscriptions that are missing.</inlineHelpText>
        <label>Create Zuora Account and Subscriptions</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Custom_ID__c</fullName>
        <label>Partner Custom ID</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Partner</label>
        <referenceTo>Partner__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Representative__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Representative</label>
        <referenceTo>BSST__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora_Id__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>Set by ZuoraAccountService after it creates the account in Zuora from a converted lead</inlineHelpText>
        <label>Zuora Id</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Property</fullName>
        <active>true</active>
        <label>Property</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/BSST__c.object
<CustomObject>
    <fields>
        <fullName>Custom_ID__c</fullName>
        <label>Custom ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Partner__c</fullName>
        <label>Organization</label>
        <referenceTo>Partner__c</referenceTo>
        <relationshipLabel>Sales Team</relationshipLabel>
        <relationshipName>Boston_Solar_Sales_Team</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Sales Team</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Team</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Custom_ID__c</fullName>
        <label>Custom ID</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Representative__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>This is the relationship to the Sales Team object. It allow the portal to show records unique to each Sales Rep.</description>
        <label>Sales Representative</label>
        <referenceTo>BSST__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>PartnerContacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Partner__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <label>Partner</label>
    <nameField>
        <label>Partner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partners</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/AccountTriggerHandlerTestClass.cls
@isTest
public class AccountTriggerHandlerTestClass {
    @testSetup public static void setupTestData(){
        Partner__c partner = new Partner__c(Name = 'Bluewave Inside Sales');
        insert partner;

        BSST__c salesRep = new BSST__c(Name = 'BlueWave User', Partner__c = partner.Id, Custom_ID__c = 'test', Email__c = 'SalesRep@Sales.com');
        insert salesRep;

        Id propertyRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Property').getRecordTypeId();
        Account accountRecord = new Account(Name='Test', RecordTypeId = propertyRecordTypeId);
        insert accountRecord;

        accountRecord.Custom_ID__c = 'test';
        update accountRecord;
    }	
    @IsTest static void testCustomIdSwapAccount() {
		Account account = [SELECT Id, Sales_Representative__r.Id, Partner__r.Id FROM Account WHERE Name = 'Test'];
		Partner__c partner = [SELECT Id FROM Partner__c WHERE Name = 'BlueWave Inside Sales'];
		BSST__c salesRep = [SELECT Id FROM BSST__c WHERE Name = 'BlueWave User'];

		account.Custom_ID__c = 'test';
		update account;

        System.assertEquals(account.Sales_Representative__r.Id, salesRep.Id);
        System.assertEquals(account.Partner__r.Id, partner.Id);
    }

    @IsTest
    private static void testPreventDeletion() {
        Account accountA = new Account(
            Name = 'Test',
            Zuora_Id__c = '2c92a0ff6e3f9d59016e411e1efa6e15'
        );
        insert accountA;
        Account accountB = new Account(
            Name = 'TestB'
        );
        insert accountB;

        Boolean caughtException = false;
        try {
            Database.merge(accountB, accountA);
        } catch (DmlException de) {
            System.assert(de.getMessage().contains('Zuora'));
            caughtException = true;
        }
        System.assert(caughtException, 'Expected the merge to fail because the Zuora account is being deleted');

        caughtException = false;
        Database.MergeResult mergeResult;
        try {
            mergeResult = Database.merge(accountA, accountB);
        } catch (Exception e) {
            System.debug(LoggingLevel.ERROR, e.getMessage());
            System.assert(false, 'Expected the merge to work because the Zuora account is not deleted');
        }
        System.assert(mergeResult.isSuccess());
        System.assert(!caughtException);
    }

    @IsTest
    private static void testZuoraAccountCreation() {
        Id propertyRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Property').getRecordTypeId();
        Id parentRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Parent Account').getRecordTypeId();
        List<Account> accounts = new List<Account>();
        Account propertyAccountCreateOnUpdate = new Account(
            Name = 'propertyAccountCreateOnUpdate',
            RecordTypeId = propertyRecordTypeId
        );
        accounts.add(propertyAccountCreateOnUpdate);
        Account propertyAccountOneCreateOnInsert = new Account(
            Name = 'propertyAccountOneCreateOnInsert',
            RecordTypeId = propertyRecordTypeId,
            Create_Zuora_Account__c = true
        );
        accounts.add(propertyAccountOneCreateOnInsert);
        Account propertyAccountTwoCreateOnInsert = new Account(
            Name = 'propertyAccountTwoCreateOnInsert',
            RecordTypeId = propertyRecordTypeId,
            Create_Zuora_Account__c = true
        );
        accounts.add(propertyAccountTwoCreateOnInsert);
        Account parentAccountDontCreate = new Account(
            Name = 'parentAccountDontCreate',
            RecordTypeId = parentRecordTypeId,
            Create_Zuora_Account__c = true
        );
        accounts.add(parentAccountDontCreate);

        Test.startTest();
        insert accounts;
        Test.stopTest();

        System.assertEquals(3, ZuoraAPIHelper.endpointsCalled.size(), 'Expected three callouts: Account creation, Contact creation and Account update');
        for (ZuoraAPIHelper.EndpointCall endpointCall : ZuoraAPIHelper.endpointsCalled) {
            if (endpointCall.endpoint.contains('action/create') && endpointCall.jsonBody.contains('"type":"Account"')) {
                System.assert(endpointCall.jsonBody.contains('propertyAccountOneCreateOnInsert'), 'Expected to find property account one create');
                System.assert(endpointCall.jsonBody.contains('propertyAccountTwoCreateOnInsert'), 'Expected to find property account two create');
            } else if (endpointCall.endpoint.contains('action/create')) {
                System.assert(endpointCall.jsonBody.contains('"type":"Contact"'), 'Expected a contact create callout');
            }
        }

        List<Account> accountsAfterTriggerRun = [SELECT Id FROM Account WHERE Create_Zuora_Account__c = TRUE];
        System.assertEquals(0, accountsAfterTriggerRun.size(), 'Expected no accounts to have the create flag set');
    }

    @IsTest
    private static void testZuoraAccountCreationViaUpdate() {
        List<Account> accountsCreatedInSetupTestData = [SELECT Id FROM Account WHERE Name = 'Test'];
        System.assertEquals(1, accountsCreatedInSetupTestData.size());
        accountsCreatedInSetupTestData[0].Create_Zuora_Account__c = true;

        Test.startTest();
        update accountsCreatedInSetupTestData;
        Test.stopTest();

        System.assertEquals(3, ZuoraAPIHelper.endpointsCalled.size(), 'Expected three callouts: Account creation, Contact creation and Account update');
        for (ZuoraAPIHelper.EndpointCall endpointCall : ZuoraAPIHelper.endpointsCalled) {
            if (endpointCall.endpoint.contains('action/create') && endpointCall.jsonBody.contains('"type":"Account"')) {
                System.assert(endpointCall.jsonBody.contains('Test'), 'Expected to find property account one create');
            } else if (endpointCall.endpoint.contains('action/create')) {
                System.assert(endpointCall.jsonBody.contains('"type":"Contact"'), 'Expected a contact create callout');
            }
        }

        List<Account> accountsAfterTriggerRun = [SELECT Id FROM Account WHERE Create_Zuora_Account__c = TRUE];
        System.assertEquals(0, accountsAfterTriggerRun.size(), 'Expected no accounts to have the create flag set');
    }
}