src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Billing_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Zuora Billing Account, updated when Z360 syncs a new Billing Account to Salesforce</inlineHelpText>
        <label>Billing Account</label>
        <referenceTo>Zuora__CustomerAccount__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date_Removed_from_Project__c</fullName>
        <inlineHelpText>Automatically filled when this Property Account has been removed from all enacted Schedule Z&apos;s.</inlineHelpText>
        <label>Date Removed from Last Project</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Last_Bill_Send_Date_New_Charges_Zuora__c</fullName>
        <inlineHelpText>Last Invoice Date where new charges were &gt; 0</inlineHelpText>
        <label>Last Bill Send Date New Charges Zuora</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Account is Closed if all Opportunities are Cancelled, Duplicate, Expired or Dead</inlineHelpText>
        <label>CS Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Customer_Sub_Group__c</fullName>
        <inlineHelpText>Further categorizes Customer Group</inlineHelpText>
        <label>Customer Sub-Group</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Public Offtake</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Date_Removed_from_Project__c</fullName>
        <inlineHelpText>Automatically set when all UASes related to this Opportunity are inactive, with a Date Removed From project, with at least one Allocation Schedule Subscription that was enacted, (unless all UASes related to the Opp are transferring).</inlineHelpText>
        <label>Date Removed from Project</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Shared_Solar_System__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>To change this system, use the Change SSS quick action</inlineHelpText>
        <label>Shared Solar System</label>
        <referenceTo>Shared_Solar_System__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Schedule_Z__c.object
<CustomObject>
    <fields>
        <fullName>Shared_Solar_System__c</fullName>
        <label>Shared Solar System</label>
        <referenceTo>Shared_Solar_System__c</referenceTo>
        <relationshipName>Schedule_Zs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Must be updated via the &quot;Update Status &amp; Date&quot; button</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>QC in Process</fullName>
                    <default>true</default>
                    <label>QC in Process</label>
                </value>
                <value>
                    <fullName>QC Complete</fullName>
                </value>
                <value>
                    <fullName>Rejected Internal</fullName>
                </value>
                <value>
                    <fullName>Submitted to Asset Owner</fullName>
                </value>
                <value>
                    <fullName>Executed by Asset Owner</fullName>
                </value>
                <value>
                    <fullName>Submitted to Utility</fullName>
                </value>
                <value>
                    <fullName>Rejected by Utility</fullName>
                </value>
                <value>
                    <fullName>Enacted by Utility</fullName>
                </value>
                <value>
                    <fullName>Billing</fullName>
                </value>
                <value>
                    <fullName>Replaced</fullName>
                </value>
                <value>
                    <fullName>Executed by Asset Owner (old version)</fullName>
                    <isActive>false</isActive>
                    <label>Executed by Asset Owner &gt;&gt;&gt; Submit to Utility</label>
                </value>
                <value>
                    <fullName>Front Page QC Completed &gt;&gt;&gt; Submit to Asset Owner</fullName>
                    <isActive>false</isActive>
                    <label>Front Page QC Completed &gt;&gt;&gt; Submit to Asset Owner</label>
                </value>
                <value>
                    <fullName>New</fullName>
                    <isActive>false</isActive>
                    <label>New &gt;&gt;&gt; Complete Subscription QC</label>
                </value>
                <value>
                    <fullName>Rejected by Utility (old version)</fullName>
                    <isActive>false</isActive>
                    <label>Rejected</label>
                </value>
                <value>
                    <fullName>Replaced with newly Enacted Schedule Z</fullName>
                    <isActive>false</isActive>
                    <label>Replaced with newly Enacted Schedule Z</label>
                </value>
                <value>
                    <fullName>Submitted to Asset Owner &gt;&gt;&gt; Contact Asset Owner to get it Executed</fullName>
                    <isActive>false</isActive>
                    <label>Submitted to Asset Owner &gt;&gt;&gt; Contact Asset Owner to get it Executed</label>
                </value>
                <value>
                    <fullName>Submitted to Utility (old version)</fullName>
                    <isActive>false</isActive>
                    <label>Submitted to Utility &gt;&gt;&gt; Contact Utility to get it Enacted</label>
                </value>
                <value>
                    <fullName>QC Complete (old version)</fullName>
                    <isActive>false</isActive>
                    <label>Subscription QC Completed &gt;&gt;&gt; Complete Front Page QC</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Allocation Schedule</label>
    <nameField>
        <label>Allocation Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Allocation Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Schedule_Z_Subscription__c.object
<CustomObject>
    <fields>
        <fullName>Schedule_Z__c</fullName>
        <label>Allocation Schedule</label>
        <referenceTo>Schedule_Z__c</referenceTo>
        <relationshipName>Schedule_Z_Subscriptions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Utility_Account_Subscription__c</fullName>
        <label>Utility Account Subscription</label>
        <referenceTo>Utility_Account_Subscription__c</referenceTo>
        <relationshipName>Schedule_Z_Subscriptions</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Allocation Schedule Subscription</label>
    <nameField>
        <displayFormat>ALSS-{0000}</displayFormat>
        <label>Allocation Schedule Subscription Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Allocation Schedule Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Shared_Solar_System__c.object
<CustomObject
     >
    <articleTypeChannelDisplay n1:nil="true" />
    <customSettingsType n1:nil="true" />
    <description n1:nil="true" />
    <eventType n1:nil="true" />
    <fields>
        <fullName>Billing_Anchors__c</fullName>
        <label>Billing Anchors on Project</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>BlueWave</fullName>
                </value>
                <value>
                    <fullName>RadianGen</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <gender n1:nil="true" />
    <household>false</household>
    <label>Shared Solar System</label>
    <nameField>
        <label>Shared Solar System Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shared Solar Systems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <startsWith n1:nil="true" />
</CustomObject>

src/objects/Utility_Account_Subscription__c.object
<CustomObject>
    <fields>
        <fullName>Date_Removed_from_Project__c</fullName>
        <inlineHelpText>Populated with Date Allocation Schedule Retired by Utility when &quot;Date Allocation Schedule Retired by Utility&quot; on all related Allocation Schedule Subscriptions is populated AND Date Utility Account Cancelled is NOT populated</inlineHelpText>
        <label>Date Removed from Project</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Utility Account Subscriptions</relationshipLabel>
        <relationshipName>Utility_Account_Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shared_Solar_System__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the SSS on the Opportunity when the UAS was created. The SSS on an existing UAS should never be changed.</description>
        <inlineHelpText>This is the SSS on the Opportunity when the UAS was created. The SSS on an existing UAS should never be changed.</inlineHelpText>
        <label>Shared Solar System</label>
        <referenceTo>Shared_Solar_System__c</referenceTo>
        <relationshipLabel>Utility Account Subscriptions</relationshipLabel>
        <relationshipName>Utility_Account_Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>This is displayed in the customer portal as a way of showing the status of a customer&apos;s subscription using a combination of Current Allocation Schedule Status, Next Allocation Schedule Status, and Date Removed</description>
        <formula>IF(
 ISBLANK(Date_Removed_from_Project__c)=false,
&quot;Inactive&quot;,

IF(

  ISPICKVAL(Next_Schedule_Z_Status__c,&quot;Active Subscription&quot;)
&amp;&amp;
 Current_Schedule_Z_Status__c=&quot;Not Yet Enacted&quot;,
&quot;Coming Soon&quot;,

IF(
  ISPICKVAL(Next_Schedule_Z_Status__c,&quot;Active Subscription&quot;)
&amp;&amp;
 Current_Schedule_Z_Status__c=&quot;Enacted&quot;,
&quot;Active&quot;,

IF(
  ISPICKVAL(Next_Schedule_Z_Status__c,&quot;Inactive Subscription&quot;)
&amp;&amp;
 Current_Schedule_Z_Status__c=&quot;Enacted&quot;,
&quot;Pending Removal&quot;,&quot;&quot;)


)
)
)</formula>
        <inlineHelpText>This is displayed in the customer portal as a way of showing the status of a customer&apos;s subscription using a combination of Current Allocation Schedule Status, Next Allocation Schedule Status, and Date Removed</inlineHelpText>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <label>Utility Account Subscription</label>
    <nameField>
        <label>Utility Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Account Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Zuora__CustomerAccount__c.object
<CustomObject>
    <description>Zuora Billing Account object.  An account is a customer account that collects all of the critical information about the customer, such as contact information, payment terms, and payment methods. You can use a customer account to track subscriptions, amendments, and transactions, such as invoices and payments.</description>
    <fields>
        <fullName>Zuora__Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>R00N40000001kyLcEAI</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Zuora__Balance__c</fullName>
        <label>Bill To Account Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ScheduleZSubscriptionSelectorTest.cls
/**
 * Created by PeterYao on 3/12/2019.
 */
@IsTest
public with sharing class ScheduleZSubscriptionSelectorTest {
    @TestSetup public static void setupData() {
        CSPaymentTest.csPaymentSetupTestData();

        Account parentAccount = new Account(Name = 'Parent Account');
        insert parentAccount;

        Zuora__CustomerAccount__c billingAccount = new Zuora__CustomerAccount__c(Zuora__Account__c = parentAccount.Id, Zuora__Balance__c = 200.00);
        insert billingAccount;
    }

    @IsTest
    public static void testGetList() {
        // All of the opportunities loaded are small offtake - let's change two of them to Public Offtake to test
        // that they're excluded
        List<Opportunity> opportunities = [
            SELECT Id
            FROM Opportunity
            WHERE Name = 'ABike Shop'
        ];
        System.assertEquals(2, opportunities.size());
        for (Opportunity opportunity : opportunities) {
            opportunity.Customer_Sub_Group__c = 'Public Offtake';
        }
        update opportunities;
        Map<Id, Shared_Solar_System__c> sharedSolarSystemMap = new Map<Id, Shared_Solar_System__c>([
            SELECT Id
            FROM Shared_Solar_System__c
            WHERE Name IN ('Oxford Barrett St. P1', 'Oxford Barrett St. P2')
        ]);
        System.assertEquals(2, sharedSolarSystemMap.values().size());
        for (Shared_Solar_System__c sharedSolarSystem : sharedSolarSystemMap.values()) {
            sharedSolarSystem.Billing_Anchors__c = 'RadianGen';
        }
        update sharedSolarSystemMap.values();

        Map<Id, Schedule_Z__c> scheduleZMap= new Map<Id, Schedule_Z__c>([SELECT Id FROM Schedule_Z__c]);

        List<Schedule_Z_Subscription__c> szsList = ScheduleZSubscriptionSelector.getListForBilling(scheduleZMap.keySet());
        //2 are Externally Serviced
        System.assertEquals(15, szsList.size());
    }

    @IsTest
    public static void testGetSZSFromTransfer() {
        Date todaysDate = Date.today();

        Zuora__CustomerAccount__c billingAccount = [SELECT Id FROM Zuora__CustomerAccount__c WHERE Zuora__Balance__c = 200.00 LIMIT 1];

        List<Account> accounts = [
            SELECT Id
            FROM Account
        ];
        for (Account acct : accounts) {
            acct.Billing_Account__c = billingAccount.Id;
            acct.Last_Bill_Send_Date_New_Charges_Zuora__c = todaysDate.addDays(-60);
        }
        update accounts;

        Map<Id, Shared_Solar_System__c> sharedSolarSystemMap = new Map<Id, Shared_Solar_System__c>([
            SELECT Id
            FROM Shared_Solar_System__c
            WHERE Name IN ('Oxford Barrett St. P1', 'Oxford Barrett St. P2')
        ]);

        Map<Id, Schedule_Z__c> schZMap = new Map<Id, Schedule_Z__c>([
            SELECT Id
            FROM Schedule_Z__c
            WHERE Shared_Solar_System__c IN : sharedSolarSystemMap.keySet()
        ]);

        List<Utility_Account_Subscription__c> uases = [
            SELECT Id
            FROM Utility_Account_Subscription__c
            WHERE Opportunity__r.Shared_Solar_System__r.Id IN : sharedSolarSystemMap.keySet()
            ORDER BY Name
        ];

        ScheduleZSubscriptionSelector selector = new ScheduleZSubscriptionSelector();
        List<Schedule_Z_Subscription__c> szsList;

        szsList = selector.getOverdueSZSForBillingOffTransfer(sharedSolarSystemMap.keySet(),null);
        System.assertEquals(14,szsList.size());

        szsList = selector.getOverdueSZSForBillingOffTransfer(sharedSolarSystemMap.keySet(), new Set<Id>{uases[0].Id, uases[1].Id});
        System.assertEquals(12,szsList.size());

        szsList = selector.getOnTimeListForBillingOffTransfer(schZMap.keySet());
        System.assertEquals(14,szsList.size());
    }

    @IsTest
    public static void testGetSZSFromTransferWithNonBillingSZSes() {
        Date todaysDate = Date.today();

        Zuora__CustomerAccount__c billingAccount = [SELECT Id FROM Zuora__CustomerAccount__c WHERE Zuora__Balance__c = 200.00 LIMIT 1];

        List<Account> accounts = [
            SELECT Id
            FROM Account
        ];
        for (Account acct : accounts) {
            acct.Billing_Account__c = billingAccount.Id;
            acct.Last_Bill_Send_Date_New_Charges_Zuora__c = todaysDate.addDays(-60);
        }
        update accounts;

        Map<Id, Shared_Solar_System__c> sharedSolarSystemMap = new Map<Id, Shared_Solar_System__c>([
            SELECT Id
            FROM Shared_Solar_System__c
            WHERE Name IN ('Oxford Barrett St. P1', 'Oxford Barrett St. P2')
        ]);

        Map<Id, Schedule_Z__c> schZMap = new Map<Id, Schedule_Z__c>([
            SELECT Id
            FROM Schedule_Z__c
            WHERE Shared_Solar_System__c IN : sharedSolarSystemMap.keySet()
            ORDER BY Name
        ]);

        Schedule_Z__c szToUpdate = schZMap.values()[0];
        szToUpdate.Status__c = 'Submitted to Utility';
        update szToUpdate;

        List<Utility_Account_Subscription__c> uases = [
            SELECT Id
            FROM Utility_Account_Subscription__c
            WHERE Opportunity__r.Shared_Solar_System__r.Id IN : sharedSolarSystemMap.keySet()
            ORDER BY Name
        ];

        ScheduleZSubscriptionSelector selector = new ScheduleZSubscriptionSelector();
        List<Schedule_Z_Subscription__c> szsList;

        szsList = selector.getOverdueSZSForBillingOffTransfer(sharedSolarSystemMap.keySet(),null);
        System.assertEquals(
            5,
            szsList.size(),
            'Even though there are 14 szs, we not expect to pull in ones from the SZ with status = Submitted to Utility'
        );

        szsList = selector.getOverdueSZSForBillingOffTransfer(sharedSolarSystemMap.keySet(), new Set<Id>{uases[0].Id, uases[1].Id});
        System.assertEquals(3, szsList.size());
    }

    @IsTest
    public static void testGetALSSFromALS() {
        Schedule_Z__c als = [SELECT Id FROM Schedule_Z__c WHERE Name = '18-0515 Oxford Barrett St. P1' LIMIT 1];
        System.assertNotEquals(null, als);
        List<Schedule_Z_Subscription__c> szsList = ScheduleZSubscriptionSelector.getALSSFromALS(new List<Id>{als.Id});
        System.assertEquals(9, szsList.size());

        Set<Id> szsIds = new Set<Id>();
        for (Schedule_Z_Subscription__c szs : szsList) {
            szsIds.add(szs.Id);
        }

        List<Schedule_Z_Subscription__c> testSZSList =  ScheduleZSubscriptionSelector.getScheduleZSubscriptionsList(szsIds);
        System.assertEquals(9, testSZSList.size());
    }

    @IsTest
    public static void testGetRetiredSZS() {
        Utility_Account_Subscription__c uas = [
            SELECT Id, Date_Removed_from_Project__c,
            (SELECT Id, Schedule_Z__c FROM Schedule_Z_Subscriptions__r)
            FROM Utility_Account_Subscription__c
            LIMIT 1
        ];
        Id scheduleZId;
        for (Schedule_Z_Subscription__c szs : uas.Schedule_Z_Subscriptions__r) {
            scheduleZId = szs.Schedule_Z__c;
        }

        uas.Date_Removed_from_Project__c = System.today();
        update uas;
        System.assertNotEquals(null, new ScheduleZSubscriptionSelector().getRetiredALSSFromALS(scheduleZId));
    }
}