src/objects/API_Credential__c.object
<CustomObject>
    <label>API Credential</label>
    <nameField>
        <label>API Credential Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>API Credentials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/API_Credential__c/fields/Credential_Id__c.field-meta.xml
<CustomField>
    <fullName>Credential_Id__c</fullName>
    <label>Credential Id</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/API_Credential__c/fields/Credential_Secret__c.field-meta.xml
<CustomField>
    <fullName>Credential_Secret__c</fullName>
    <label>Credential Secret</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

src/classes/AuthNetScheduler.cls
/**
 * Created by PeterYao on 10/9/2019.
  * Tested By: BatchAuthNetReturnedTransactionsTest
 */

public without sharing class AuthNetScheduler implements Schedulable, Database.AllowsCallouts {
    @TestVisible
    public static APICredentialSelector apiCredentialSelector = new APICredentialSelector();

    public void execute(SchedulableContext sc) {
        AuthNetScheduler.startJob();
    }

    @Future(Callout=true)
    public static void startJob() {
        List<AuthNetAPI.MerchantAuthentication> merchantAuthentications = new List<AuthNetAPI.MerchantAuthentication>();

        List<API_Credential__c> credentials = apiCredentialSelector.getApiCredentials('Authorize');

        for (API_Credential__c credential : credentials){
            AuthNetAPI.MerchantAuthentication m = new AuthNetAPI.MerchantAuthentication();
            m.Zname = credential.Credential_Id__c;
            m.transactionKey = credential.Credential_Secret__c;
            merchantAuthentications.add(m);
        }

        BatchAuthNetReturnedTransactions batchAuthNet = new BatchAuthNetReturnedTransactions();
        batchAuthNet.init(merchantAuthentications);
        System.enqueueJob(batchAuthNet);
    }
}