src/objects/Application__c.object
<CustomObject>
    <fields>
        <fullName>Application_Type__c</fullName>
        <label>Application Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pre_Application</fullName>
                    <label>Pre-Application</label>
                </value>
                <value>
                    <fullName>Interconnection Application</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Application</label>
    <nameField>
        <label>Application</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This is used for Customer contracts that are generated when the customer is still a lead.</inlineHelpText>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This is used for customer contracts to show the product and contract that was used.</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Acquired_By_Client_Closed_By_BlueWave__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Populated by Client Lead form. Signifies this warm lead will be closed by Perch</inlineHelpText>
        <label>Acquired By Client, Closed By Perch</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Annual_Electricity_Cost__c</fullName>
        <label>Annual Electricity Cost (Utility Data)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Application_Type__c</fullName>
        <label>Application Type</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Application__c</fullName>
        <formula>CreatedDate</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The date that the lead was created, used to map the Lead&apos;s Created Date to the Opportunity (since we can&apos;t use CreatedDate in lead mapping)</inlineHelpText>
        <label>Application Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Business_Title__c</fullName>
        <label>Business Title</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Referral__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Referral</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Type_Formula__c</fullName>
        <description>Used to map into Opportunity to trigger workflow that set record type to business/residential. Picklist Customer Group will not fire workflow.</description>
        <formula>Customer_type__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Customer Type (Formula)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_type__c</fullName>
        <label>Customer type</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone2__c</fullName>
        <formula>BLANKVALUE(MobilePhone, Phone)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Used to map the Lead&apos;s phone number to Opportunity.Customer Phone (since standard fields can&apos;t be mapped)</inlineHelpText>
        <label>Phone2</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Product lookup, for loans, set by an installer upon sending a new application or set by code after a credit check has determined qualifying products.</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>bs_Sales_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Person</label>
        <referenceTo>BSST__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Lead</fullName>
        <active>true</active>
        <businessProcess>CS</businessProcess>
        <label>Lead</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Acquired_By_Client_Closed_By_BlueWave__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>When checked, the lead was acquired by Client but closed by Perch. Used for Client Invoicing</inlineHelpText>
        <label>Acquired By Client, Closed By Perch</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Annual_Consumption_kWh__c</fullName>
        <label>Annual Consumption (kWh)</label>
        <precision>15</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Annual_Electricity_Cost2__c</fullName>
        <inlineHelpText>Enter Annual Electricity Cost of the total kWh being sized. If Residential Solar is already installed please enter cost of excess uncovered kWh. If not, please enter total annual cost of electricity.</inlineHelpText>
        <label>Annual Electricity Cost ($)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Annual_Electricity_Cost__c</fullName>
        <inlineHelpText>Enter Annual Electricity Cost of the total kWh being sized. If Residential Solar is already installed please enter cost of excess uncovered kWh. If not, please enter total annual cost of electricity.</inlineHelpText>
        <label>Annual Electricity Cost ($)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Application_Date__c</fullName>
        <description>Maps created date from the lead.</description>
        <inlineHelpText>Maps created date from the lead.</inlineHelpText>
        <label>Application Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Application_Type__c</fullName>
        <label>Application Type</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BS_Sales_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Person</label>
        <referenceTo>BSST__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Business_Title__c</fullName>
        <label>Business Title</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Group__c</fullName>
        <label>Customer Group</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Residential</fullName>
                </value>
                <value>
                    <fullName>Non-Residential</fullName>
                    <default>true</default>
                    <label>Non-Residential</label>
                </value>
                <value>
                    <fullName>Anchor</fullName>
                </value>
                <value>
                    <fullName>Business</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Customer_Phone__c</fullName>
        <label>Customer Phone</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Referral__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Referral</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities (Customer Referral)</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Type__c</fullName>
        <label>Customer Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>County</fullName>
                </value>
                <value>
                    <fullName>Municipality</fullName>
                </value>
                <value>
                    <fullName>Public School</fullName>
                </value>
                <value>
                    <fullName>Private School</fullName>
                </value>
                <value>
                    <fullName>Public Affordable-Surplus</fullName>
                </value>
                <value>
                    <fullName>Public Affordable-Deficit</fullName>
                </value>
                <value>
                    <fullName>Public Affordable-Unknown Budget</fullName>
                </value>
                <value>
                    <fullName>MAPC</fullName>
                </value>
                <value>
                    <fullName>MLP</fullName>
                </value>
                <value>
                    <fullName>C&amp;I</fullName>
                </value>
                <value>
                    <fullName>Private Affordable</fullName>
                </value>
                <value>
                    <fullName>Sewer</fullName>
                </value>
                <value>
                    <fullName>Water</fullName>
                </value>
                <value>
                    <fullName>Fire</fullName>
                </value>
                <value>
                    <fullName>Public Works</fullName>
                </value>
                <value>
                    <fullName>Airport</fullName>
                </value>
                <value>
                    <fullName>Ambulance</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Set by OpportunityTriggerHandler on Opportunity creation, assuming Opportunity.Lead_ID__c (a text field) is also being set via Lead Mapping.</inlineHelpText>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NMC_Tariff__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>NMC Tariff</label>
        <referenceTo>Utility_NMC_Tariff__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity_Order__c</fullName>
        <label>Opportunity Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shared_Solar_System__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>To change this system, use the Change SSS quick action</inlineHelpText>
        <label>Shared Solar System</label>
        <referenceTo>Shared_Solar_System__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>System_Assigned__c</fullName>
        <defaultValue>false</defaultValue>
        <label>System Assigned</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>UAS_Created__c</fullName>
        <defaultValue>false</defaultValue>
        <label>UAS Created</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Shared_Solar_System__c.object
<CustomObject
     >
    <articleTypeChannelDisplay n1:nil="true" />
    <customSettingsType n1:nil="true" />
    <description n1:nil="true" />
    <eventType n1:nil="true" />
    <fields>
        <fullName>Maximum_Subscription_Cost__c</fullName>
        <formula>Maximum_Subscription_Capacity_kWDC__c *  NMC_Value__c *  Expected_Yield_kWh_kW__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Maximum Subscription Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Primary customer product.</inlineHelpText>
        <label>Default Enrollment Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Shared Solar Systems</relationshipLabel>
        <relationshipName>Shared_Solar_Systems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Utility_NMC_Tariff__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sizing Method</label>
        <referenceTo>Utility_NMC_Tariff__c</referenceTo>
        <relationshipLabel>Shared Solar Systems</relationshipLabel>
        <relationshipName>Shared_Solar_Systems</relationshipName>
        <type>Lookup</type>
    </fields>
    <gender n1:nil="true" />
    <household>false</household>
    <label>Shared Solar System</label>
    <nameField>
        <label>Shared Solar System Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shared Solar Systems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <startsWith n1:nil="true" />
</CustomObject>

src/classes/CSOpportunityFactory.cls
/**
 * @description: Created by mstackhouse on 12/14/2018.
 * Used by the CSSubscriptionEnroller to create CS opportunities for a lead from the required input components
 * Tested By: CSOpportunityFactoryTest
 */
public without sharing class CSOpportunityFactory {

    public static List<Opportunity> generateCSOpportunities(Lead lead, List<Shared_Solar_System__c> availableSSS,
        CSSubscriptionEnroller.AnnualEnergyTotal annualTotals, Id propertyAccountId)
    {
        Decimal remainingAccountCostToAllocate = annualTotals.cost;
        Decimal remainingAccountkWhToAllocate = annualTotals.kWh;
        List<Opportunity> oppListToCreate = new List<Opportunity>();
        Integer oppCounter = 1;
		
        for (Shared_Solar_System__c sss : availableSSS) {
            if (remainingAccountCostToAllocate > 0 || remainingAccountkWhToAllocate > 0) {
                Decimal annualElectricityCostAssigned = Math.min(remainingAccountCostToAllocate, sss.Maximum_Subscription_Cost__c);
                if (remainingAccountCostToAllocate > 0) {
                    remainingAccountCostToAllocate -= annualElectricityCostAssigned;
                }
                Decimal annualElectricitykWhAssigned = Math.min(remainingAccountkWhToAllocate, SharedSolarSystems.calculateMaximumkWh(sss));
                if (remainingAccountkWhToAllocate > 0) {
                    remainingAccountkWhToAllocate -= annualElectricitykWhAssigned;
                }
                Opportunity opp = new Opportunity(
                    AccountId = propertyAccountId,
                    Shared_Solar_System__c = sss.Id,
                    Product__c = sss.Product__c,
                    System_Assigned__c = true,
                    NMC_Tariff__c = sss.Utility_NMC_Tariff__c,
                    CloseDate = Date.today(),
                    UAS_Created__c = true,
                    Annual_Electricity_Cost__c = annualElectricityCostAssigned,
                    Annual_Electricity_Cost2__c = annualElectricityCostAssigned,
                    Annual_Consumption_kWh__c = annualElectricitykWhAssigned,
                    Opportunity_Order__c = oppCounter
                );
                opp = setOpportunityStage(lead, opp);
                opp = setDefaultOppFields(lead, opp);
                oppListToCreate.add(opp);
                oppCounter++;
            }
        }
        return oppListToCreate;
    }

    @TestVisible
    private static Opportunity setOpportunityStage(Lead lead, Opportunity opp) {
        if (lead.LeadSource == 'Switch' || lead.LeadSource == 'Third-Party') {
            opp.StageName = 'QC in Process';
        } else {
            opp.StageName = 'Contract Pending';
        }
        return opp;
    }

    @TestVisible
    private static Opportunity setDefaultOppFields(Lead lead, Opportunity opp) {
        opp.Lead__c = lead.Id;
        opp.Acquired_By_Client_Closed_By_BlueWave__c = lead.Acquired_By_Client_Closed_By_BlueWave__c;
        opp.Application_Date__c = lead.Application__c;
        opp.Application_Type__c = lead.Application_Type__c;
        opp.BS_Sales_ID__c = lead.bs_Sales_ID__c;
        opp.Business_Title__c = lead.Business_Title__c;
        opp.Customer_Group__c = lead.Customer_Type_Formula__c;
        opp.Customer_Phone__c = lead.Phone2__c;
        opp.Customer_Referral__c = lead.Customer_Referral__c;
        opp.Customer_Type__c = lead.Customer_type__c;
        opp.Date_of_Application__c = lead.Date_of_Application__c;
        opp.Lead_ID__c = lead.Lead_ID__c;
        opp.LoadZone__c = lead.LoadZone__c;
        opp.Name = lead.Company;
        opp.OwnerId = lead.OwnerId;
        opp.Parcel_ZIp__c = lead.Parcel_Zip__c;
        opp.Partner_Email__c = lead.Partner_Email__c;
        opp.Partner_tag_lookup__c = lead.Partner_Lookup__c;
        opp.Partner_Account__c = lead.Partner_Account__c;
        opp.Partner_Contact__c = lead.Partner_Contact__c;
        opp.Personal_Credit_Report2__c = lead.Personal_Credit_Report__c;
        opp.Product_Line__c = lead.Product_line__c;
        opp.Project_Assignment__c = lead.System_Assignment__c;
        opp.Referral_Email__c = lead.Referral_Email__c;
        opp.State_ab__c = lead.LASERCA__Home_State__c;
        opp.Underwriting_Criteria__c = lead.Underwriting_Criteria__c;
        return opp;
    }
}