src/objects/Bill_Adjustment__c.object
<CustomObject>
    <description>CS Billing: If we know that a UAS is going to need adjustments on a future bill, they are stored here until that bill is generated</description>
    <fields>
        <fullName>Adjustment_Amount__c</fullName>
        <label>Adjustment Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Credits_Allocated__c</fullName>
        <label>Credits Allocated</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Discount__c</fullName>
        <formula>IF(ISPICKVAL(Adjustment_Type__c,&apos;Production&apos; ), ( Credits_Allocated__c -  Adjustment_Amount__c ), NULL)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Discount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Discounted_Bill__c</fullName>
        <label>Discounted Bill</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>UASB__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Utility Account Subscription Bill</label>
        <referenceTo>UASB__c</referenceTo>
        <relationshipLabel>Bill Adjustments</relationshipLabel>
        <relationshipName>Bill_Adjustments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Utility_Account_Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Utility Account Subscription</label>
        <referenceTo>Utility_Account_Subscription__c</referenceTo>
        <relationshipLabel>Bill Adjustments</relationshipLabel>
        <relationshipName>Bill_Adjustments_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Bill Adjustment</label>
    <nameField>
        <label>Bill Adjustment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bill Adjustments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Shared_Solar_System__c.object
<CustomObject
     >
    <articleTypeChannelDisplay n1:nil="true" />
    <customSettingsType n1:nil="true" />
    <description n1:nil="true" />
    <eventType n1:nil="true" />
    <fields>
        <fullName>Utility__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Utility</label>
        <referenceTo>Utility__c</referenceTo>
        <relationshipLabel>Shared Solar Systems</relationshipLabel>
        <relationshipName>Shared_Solar_Systems</relationshipName>
        <type>Lookup</type>
    </fields>
    <gender n1:nil="true" />
    <household>false</household>
    <label>Shared Solar System</label>
    <nameField>
        <label>Shared Solar System Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shared Solar Systems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <startsWith n1:nil="true" />
</CustomObject>

src/objects/UASB__c.object
<CustomObject
     >
    <description n1:nil="true" />
    <fields>
        <fullName>Adjustment_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Adjustment Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Billing_Period_Start_Date__c</fullName>
        <inlineHelpText>From Production Update, the beginning of the related host account billing period</inlineHelpText>
        <label>Billing Period Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Credits_Allocated__c</fullName>
        <label>Credits Allocated</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Discounted_Bill__c</fullName>
        <formula>IF(ISPICKVAL( Pricing_Structure__c, &quot;Use Solar Electric Rate&quot;),Solar_Share_Rate_Bill_Value__c, IF(Above_NM_Rate_Floor__c,Bill_Value__c,Floor_Price_Bill_Value__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Discounted Bill</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Net_Metering_Credits_Allocated__c</fullName>
        <formula>Credits_Allocated__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Net Metering Credits Allocated</label>
        <precision>18</precision>
        <scale>5</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Savings__c</fullName>
        <formula>ROUND(Net_Metering_Credits_Allocated__c,2) - ROUND(Discounted_Bill__c,2)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Savings</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Shared_Solar_System__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Shared Solar System</label>
        <referenceTo>Shared_Solar_System__c</referenceTo>
        <relationshipLabel>Utility Account Subscription Bills</relationshipLabel>
        <relationshipName>Utility_Account_Subscription_Bills</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Utility_Account_Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Utility Account Subscription</label>
        <referenceTo>Utility_Account_Subscription__c</referenceTo>
        <relationshipLabel>Utility Account Subscription Bills</relationshipLabel>
        <relationshipName>Utility_Account_Subscription_Bills</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Utility Account Subscription Bill</label>
    <nameField>
        <displayFormat>UASB-{0000000}</displayFormat>
        <label>Utility Account Subscription Bill Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Utility Account Subscription Bills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Utility__c.object
<CustomObject>
    <label>Utility</label>
    <nameField>
        <label>Utility Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Utility_Account_Log__c.object
<CustomObject>
    <label>Utility Account Log</label>
    <nameField>
        <label>Utility Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Account Logs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Utility_Account_Subscription__c.object
<CustomObject>
    <fields>
        <fullName>Shared_Solar_System__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the SSS on the Opportunity when the UAS was created. The SSS on an existing UAS should never be changed.</description>
        <inlineHelpText>This is the SSS on the Opportunity when the UAS was created. The SSS on an existing UAS should never be changed.</inlineHelpText>
        <label>Shared Solar System</label>
        <referenceTo>Shared_Solar_System__c</referenceTo>
        <relationshipLabel>Utility Account Subscriptions</relationshipLabel>
        <relationshipName>Utility_Account_Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Utility_Account_Log__c</fullName>
        <inlineHelpText>The related UAL</inlineHelpText>
        <label>Utility Account Log</label>
        <referenceTo>Utility_Account_Log__c</referenceTo>
        <relationshipLabel>Utility Account Subscriptions</relationshipLabel>
        <relationshipName>Utility_Account_Subscriptions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Utility__c</fullName>
        <formula>Opportunity__r.UtilityMapper__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Utility</label>
        <type>Text</type>
    </fields>
    <label>Utility Account Subscription</label>
    <nameField>
        <label>Utility Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Account Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ZuoraUsageService.cls
public class ZuoraUsageService implements Database.AllowsCallouts{

    public class ZuoraUsage {
        public String AccountId;
        public String ChargeNumber;
        public Datetime EndDateTime;
        public Decimal Quantity;
        public Datetime StartDateTime;
        public String SubscriptionNumber;
        public String Description;
        public String SolarSavings_Zcustom;
        public String UtilityCredit_Zcustom;
        public String CRM_ID_Zcustom;
        public String UOM = 'Dollars';
    }

    public class ZuoraResponse {
        public String Success;
        public String Id;
        public List<ZuoraError> Errors;
    }

    public class ZuoraError {
        public String Code;
        public String Message;
    }

    public static List<ZuoraUsage> convertSFUsageToZuoraUsage (List<SObject> sfUsageRecord){
        List<ZuoraUsage> zuoraUsageLineItems = new List<ZuoraUsage>();

        for (SObject sfUsage : sfUsageRecord) {
            if (sfUsage.Id.getSObjectType() == UASB__c.sObjectType) {
                UASB__c uasb = (UASB__c) sfUsage;
                ZuoraUsage usage = new ZuoraUsage();
                usage.AccountId = uasb.Utility_Account_Subscription__r.SRPC__r.Zuora__Subscription__r.Zuora__CustomerAccount__r.Zuora__Zuora_Id__c;
                usage.Quantity = uasb.Discounted_Bill__c;
                usage.StartDateTime = uasb.Billing_Period_Start_Date__c;
                usage.EndDateTime = uasb.Billing_Period_Start_Date__c; // change to end date!!
                usage.SubscriptionNumber = uasb.Utility_Account_Subscription__r.SRPC__r.Zuora__Subscription__r.Name;
                usage.ChargeNumber = uasb.Utility_Account_Subscription__r.SRPC__r.Zuora__ChargeNumber__c;
                usage.Description = uasb.Shared_Solar_System__r.Utility__r.Name
                    + ' #'
                    + uasb.Utility_Account_Subscription__r.Utility_Account_Log__r.Name;
                usage.SolarSavings_Zcustom = String.valueOf(uasb.Savings__c);
                usage.UtilityCredit_Zcustom = String.valueOf(Util.roundValue(uasb.Net_Metering_Credits_Allocated__c, 2, 'HALF_UP'));
                usage.CRM_ID_Zcustom = uasb.Id;
                zuoraUsageLineItems.add(usage);
            } else if (sfUsage.Id.getSObjectType() == Bill_Adjustment__c.sObjectType) {
                Bill_Adjustment__c adjust = (Bill_Adjustment__c) sfUsage;
                ZuoraUsage usage = new ZuoraUsage();
                usage.AccountId = adjust.UASB__r.Utility_Account_Subscription__r.SRPC__r.Zuora__Subscription__r.Zuora__CustomerAccount__r.Zuora__Zuora_Id__c;
                usage.Quantity = adjust.Adjustment_Amount__c ;
                usage.StartDateTime = adjust.UASB__r.Billing_Period_Start_Date__c;
                usage.EndDateTime = adjust.UASB__r.Billing_Period_Start_Date__c; // change to end date!!
                usage.SubscriptionNumber = adjust.UASB__r.Utility_Account_Subscription__r.SRPC__r.Zuora__Subscription__r.Name;
                usage.ChargeNumber = adjust.UASB__r.Utility_Account_Subscription__r.SRPC__r.Zuora__ChargeNumber__c;
                usage.Description = adjust.UASB__r.Shared_Solar_System__r.Utility__r.Name
                    + ' #'
                    + adjust.UASB__r.Utility_Account_Subscription__r.Utility_Account_Log__r.Name;
                usage.SolarSavings_Zcustom = String.valueOf(adjust.Discount__c);
                usage.UtilityCredit_Zcustom = String.valueOf(Util.roundValue(adjust.Credits_Allocated__c, 2, 'HALF_UP'));
                usage.CRM_ID_Zcustom = adjust.Id;
                zuoraUsageLineItems.add(usage);
            }
        }
        return zuoraUsageLineItems;
    }

    public static String convertZuoraUsageToJSON (List<ZuoraUsage> zuoraUsageLineItems) {
        String jsonString = JSON.serialize(zuoraUsageLineItems);
        jsonString = '{ "objects": ' + jsonString + ', "type": "Usage" }';
        jsonString = jsonString.replace('_Zcustom','__c');
        return jsonString;
    }

    public static HttpResponse usageAPICall(String jsonString){
        // Replace with general Zuora api class
        HttpRequest request = new HttpRequest();
        request.setMethod('POST');
        request.setEndpoint('https://rest.apisandbox.zuora.com/v1/action/create');
        request.setHeader('Content-Type', 'application/json');
        request.setHeader('zuora-version', '224.0');
        request.setHeader('Accept', 'application/json');
        request.setBody(jsonString);
        Zuora.zApi zApiInstance = new Zuora.zApi();
        HttpResponse response = zApiInstance.sendRequest(request);

        return response;
    }

    public static Map<String, List<SObject>> handleAPIResponse(List<ZuoraUsage> attemptedUsageList, HttpResponse response){
        System.debug(response.getBody());
        // Returns list of Usage Id, or Error Message:
        List<ZuoraResponse> zResponses = new List<ZuoraResponse>();
        zResponses = (List<ZuoraResponse>)JSON.deserialize(response.getBody(), List<ZuoraResponse>.class);

        Integer count = 0;
        List<UASB__c> uasbsToUpdate = new List<UASB__c>();
        List<Bill_Adjustment__c> adjustmentsToUpdate = new List<Bill_Adjustment__c>();

        for (ZuoraUsage attemptedUsage : attemptedUsageList){
            ZuoraResponse usageLine = zResponses[count];
            count += 1;
            if (usageLine.Success == 'true'){
                Id sfID = attemptedUsage.CRM_ID_Zcustom;
                Schema.SObjectType objectType = sfId.getSObjectType();
                if (objectType == UASB__c.sObjectType){
                    UASB__c uasbToUpdate = new UASB__c(
                        Id = sfId,
                        Zuora_Usage_Id__c = usageLine.Id
                    );
                    uasbsToUpdate.add(uasbToUpdate);
                } else if (objectType == Bill_Adjustment__c.sObjectType){
                    Bill_Adjustment__c adjustToUpdate = new Bill_Adjustment__c(
                        Id = sfId,
                        Zuora_Usage_Id__c = usageLine.Id
                    );
                    adjustmentsToUpdate.add(adjustToUpdate);
                }
            } else {
                String errorMessage = attemptedUsage.CRM_ID_Zcustom + '_' + String.valueOf(usageLine.Errors);
                Logger.logLater('ZuoraUsageService', 'handleAPIResponse', errorMessage);
            }
        }
        Map<String, List<SObject>> objectToRecordList = new Map<String, List<SObject>>();
        objectToRecordList.put('UASB',uasbsToUpdate);
        objectToRecordList.put('Bill_Adjustment',adjustmentsToUpdate);
        return objectToRecordList;
    }
}