src/objects/BlueWave_Surveys__c.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>BlueWave Surveys</relationshipLabel>
        <relationshipName>BlueWave_Surveys</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>BlueWave Survey</label>
    <nameField>
        <label>BlueWave Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BlueWave Surveys</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/SurveyHandler.cls
public class SurveyHandler {

    public void deleteDuplicateSubmissions(List<BlueWave_Surveys__c> newSurveys) {
        String surveyUniqueIdentifier;
        String incumbantSurveyUniqueIdentifier;
        List<String> surveyidList = new List<String>();   
        List<BlueWave_Surveys__c> duplicateSurveyList = new List<BlueWave_Surveys__c>();        
        Set<String> surveyUniqueIdentifierList = new Set<String>();
        Set<String> incumbantSurveyUniqueIdentifierList = new Set<String>();

        for (BlueWave_Surveys__c surveyRecord : newSurveys) {
            surveyidList.add(surveyRecord.Id);      
        }       
        for (BlueWave_Surveys__c incumbantsurvey : [SELECT Id, Name, Case__r.Contact.Id FROM BlueWave_Surveys__c WHERE Id NOT IN : surveyIdList]) {
            incumbantSurveyUniqueIdentifier = incumbantsurvey.Case__r.Contact.Id + ' ' + incumbantsurvey.Name;
            incumbantSurveyUniqueIdentifierList.add(incumbantSurveyUniqueIdentifier);
        }
        for (BlueWave_Surveys__c surveyRecord : newSurveys) {
            surveyUniqueIdentifier = surveyRecord.Case__r.Contact.Id + ' ' + surveyRecord.Name; 
            if (incumbantSurveyUniqueIdentifierList.contains(surveyUniqueIdentifier)) {
                duplicateSurveyList.add(surveyRecord);
            }           
        }
        delete duplicateSurveyList;
    }
}