src/objects/BSST__c.object
<CustomObject>
    <fields>
        <fullName>Custom_ID__c</fullName>
        <label>Custom ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Partner__c</fullName>
        <label>Organization</label>
        <referenceTo>Partner__c</referenceTo>
        <relationshipLabel>Sales Team</relationshipLabel>
        <relationshipName>Boston_Solar_Sales_Team</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Sales Team</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Team</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/LASERCA__Personal_Credit_Report__c.object
<CustomObject>
    <description>Experian Personal Credit Report, direct connect to Experian</description>
    <fields>
        <fullName>LASERCA__Credit_Score_TransUnion__c</fullName>
        <label>Credit Score (TransUnion)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LASERCA__Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Personal Credit Reports</relationshipLabel>
        <relationshipName>Personal_Credit_Reports</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Personal Credit Report</label>
    <nameField>
        <label>Personal Credit Report Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Personal Credit Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Custom_ID__c</fullName>
        <label>Custom ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Electricity_Provider__c</fullName>
        <label>Utility from application</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Load_Zone__c</fullName>
        <label>XXXX Load Zone</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>NEMA</fullName>
                </value>
                <value>
                    <fullName>SEMA</fullName>
                </value>
                <value>
                    <fullName>WCMA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Personal_Credit_Report__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Personal Credit Report</label>
        <referenceTo>LASERCA__Personal_Credit_Report__c</referenceTo>
        <relationshipLabel>Leads (Personal Credit Report)</relationshipLabel>
        <relationshipName>Leads1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_line__c</fullName>
        <label>Product Line</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>System_Assignment__c</fullName>
        <label>System Assignment</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Automatic - Assignment Order</fullName>
                    <default>true</default>
                    <label>Automatic - Assignment Order</label>
                </value>
                <value>
                    <fullName>Automatic - COD Date/Available Capacity</fullName>
                </value>
                <value>
                    <fullName>Manual</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Utility_1__c</fullName>
        <label>XXXXX Utility</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>National Grid</fullName>
                </value>
                <value>
                    <fullName>Eversource</fullName>
                </value>
                <value>
                    <fullName>WMECO</fullName>
                </value>
                <value>
                    <fullName>MLP</fullName>
                </value>
                <value>
                    <fullName>Duke Energy</fullName>
                </value>
                <value>
                    <fullName>SCE&amp;G</fullName>
                </value>
                <value>
                    <fullName>National Grid/Eversource</fullName>
                </value>
                <value>
                    <fullName>Eversource / MLP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Lead</fullName>
        <active>true</active>
        <businessProcess>CS</businessProcess>
        <label>Lead</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Custom_ID__c</fullName>
        <label>Custom ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Electricity_Provider__c</fullName>
        <formula>Account.Electricity_Provider__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Electricity Provider</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Set by OpportunityTriggerHandler on Opportunity creation, assuming Opportunity.Lead_ID__c (a text field) is also being set via Lead Mapping.</inlineHelpText>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Line__c</fullName>
        <label>Product Line</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Shared_Solar_System__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>To change this system, use the Change SSS quick action</inlineHelpText>
        <label>Shared Solar System</label>
        <referenceTo>Shared_Solar_System__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Shared_Solar_System__c.object
<CustomObject
     >
    <articleTypeChannelDisplay n1:nil="true" />
    <customSettingsType n1:nil="true" />
    <description n1:nil="true" />
    <eventType n1:nil="true" />
    <fields>
        <fullName>Assemblage_Count__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Assemblage Count</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Assignment_Order__c</fullName>
        <label>Assignment Order</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Capacity_Available_to_be_Reserved__c</fullName>
        <formula>Total_CS_Capacity_kW_DC_Formula__c - (Pending_Small_CS_Capacity__c + Capacity_Committed_kW_DC__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Small CS Capacity not yet committed or pending; Result of Reserved Small CS Capacity - (Committed and Pending Small CS Capacity)</inlineHelpText>
        <label>Available Small CS Capacity</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Capacity_Committed_kW_DC__c</fullName>
        <inlineHelpText>Sum of Complete Small CS Subscriptions</inlineHelpText>
        <label>Committed Small CS Capacity</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Credit_Score_Requirement__c</fullName>
        <defaultValue>700</defaultValue>
        <inlineHelpText>Minimum accepted customer FICO score.</inlineHelpText>
        <label>Credit Score Requirement</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Expected_Yield_kWh_kW__c</fullName>
        <inlineHelpText>How much energy (kWh) is produced for every kW of project capacity. If yield increases, every kW of the project will produce more energy, and need more CS offtakers to use that capacity</inlineHelpText>
        <label>Expected Yield (kWh/kW)</label>
        <precision>12</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Open__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Open</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Reserved_Capacity_kW_DC__c</fullName>
        <inlineHelpText>Sum of New, Pending, or QC in Process Small CS subscriptions</inlineHelpText>
        <label>Pending Small CS Capacity</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Territories__c</fullName>
        <label>Service Territories</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Service_Territories</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>System_Utility__c</fullName>
        <label>Utility</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_System_Size_kW_AC__c</fullName>
        <inlineHelpText>Total system size in kW AC.</inlineHelpText>
        <label>Total System Size (kW AC)</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_System_Size_kWh_DC__c</fullName>
        <inlineHelpText>Total system size in kW DC.</inlineHelpText>
        <label>Total System Size (kW DC)</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Utility_NMC_Tariff__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sizing Method</label>
        <referenceTo>Utility_NMC_Tariff__c</referenceTo>
        <relationshipLabel>Shared Solar Systems</relationshipLabel>
        <relationshipName>Shared_Solar_Systems</relationshipName>
        <type>Lookup</type>
    </fields>
    <gender n1:nil="true" />
    <household>false</household>
    <label>Shared Solar System</label>
    <nameField>
        <label>Shared Solar System Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shared Solar Systems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <startsWith n1:nil="true" />
</CustomObject>

src/objects/Utility_Account_Log__c.object
<CustomObject>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Utility Account Logs</relationshipLabel>
        <relationshipName>Utility_Account_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Partner__c</fullName>
        <label>Partner</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Utility_NMC_Tariff__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Utility NMC Tariff</label>
        <referenceTo>Utility_NMC_Tariff__c</referenceTo>
        <relationshipLabel>Utility Account Logs</relationshipLabel>
        <relationshipName>Utility_Account_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Utility Account Log</label>
    <nameField>
        <label>Utility Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Account Logs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Utility_NMC_Tariff__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Load_Zone__c</fullName>
        <label>Load Zone</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sizing_Rate__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sizing Rate</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Value_of_Net_Metering_Credit__c</fullName>
        <label>Value of Net Metering Credit</label>
        <precision>11</precision>
        <scale>6</scale>
        <type>Currency</type>
    </fields>
    <label>Sizing Method</label>
    <nameField>
        <label>Utility and Class</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sizing Methods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Service_Territories.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>NEMA</fullName>
    </customValue>
    <customValue>
        <fullName>SEMA</fullName>
    </customValue>
    <customValue>
        <fullName>WCMA</fullName>
    </customValue>
    <customValue>
        <fullName>MN</fullName>
    </customValue>
    <customValue>
        <fullName>Capital</fullName>
    </customValue>
    <customValue>
        <fullName>Hudson Valley</fullName>
    </customValue>
    <customValue>
        <fullName>Mohawk Valley</fullName>
    </customValue>
    <customValue>
        <fullName>Central</fullName>
    </customValue>
    <customValue>
        <fullName>Genesee</fullName>
    </customValue>
    <customValue>
        <fullName>Dunwoodie</fullName>
    </customValue>
    <customValue>
        <fullName>N.Y.C.</fullName>
    </customValue>
    <customValue>
        <fullName>Millwood</fullName>
    </customValue>
    <customValue>
        <fullName>Long Island</fullName>
    </customValue>
    <customValue>
        <fullName>North</fullName>
    </customValue>
    <customValue>
        <fullName>West</fullName>
    </customValue>
    <customValue>
        <fullName>Maine</fullName>
    </customValue>
    <customValue>
        <fullName>Maine Public Service</fullName>
    </customValue>
    <customValue>
        <fullName>Bangor Hydro</fullName>
    </customValue>
    <masterLabel>Service Territories</masterLabel>
</GlobalValueSet>

src/classes/LeadTriggerHandlerTest.cls
@isTest
private class LeadTriggerHandlerTest {
    
    @isTest static void customerSubscriptionProcessTest() {

        Utility_NMC_Tariff__c nmcRate =  (Utility_NMC_Tariff__c)TestFactory.createSObject(new Utility_NMC_Tariff__c(Value_of_Net_Metering_Credit__c = 1,
                                                                                                                    Name = 'Nation Grid WCMA Class 2 - S/F 2016',
                                                                                                                    Sizing_Rate__c = true,
                                                                                                                    Date__c = Date.today()));
        insert nmcRate;

        Shared_Solar_System__c sss1 = (Shared_Solar_System__c)TestFactory.createSObject(new Shared_Solar_System__c(Name = 'Oxford Barrett St. P1',
                                                                                                                                Service_Territories__c = 'WCMA; SEMA',
                                                                                                                                Open__c = true,
                                                                                                                                Reserved_Capacity_kW_DC__c = '0',
                                                                                                                                Capacity_Committed_kW_DC__c = 0,
                                                                                                                                Total_System_Size_kWh_DC__c = 1445.86,
                                                                                                                                Total_System_Size_kW_AC__c  = 996,
                                                                                                                                System_Utility__c = 'National Grid',
                                                                                                                                Credit_Score_Requirement__c = 200,
                                                                                                                                Assignment_order__c = '1',
                                                                                                                                Utility_NMC_Tariff__c = nmcRate.Id,
                                                                                                                                Expected_Yield_kWh_kW__c = 1300,
                                                                                                                                Assemblage_Count__c = 1,  
                                                                                                                                Maximum_Subscription_Assemblage__c = 25));

        
        sss1.Sales_Partners__c = 'Barbara Cerullo; Boston Solar'; 
        insert sss1;
        
     
        //Shared_Solar_System__c sss2 = (Shared_Solar_System__c)TestFactory.createSObject(new Shared_Solar_System__c(Name = 'Oxford Barrett St. P2',
        //                                                                                                                        Service_Territories__c = 'WCMA',
        //                                                                                                                        Open__c = true,
        //                                                                                                                        Reserved_Capacity_kW_DC__c = '100',
        //                                                                                                                        Capacity_Committed_kW_DC__c = 100,
        //                                                                                                                        Total_System_Size_kWh_DC__c = 100,
        //                                                                                                                        System_Utility__c = 'National Grid',
        //                                                                                                                        Credit_Score_Requirement__c = 200,
        //                                                                                                                        Assignment_order__c = '2'));
        //Shared_Solar_System__c sss3 = (Shared_Solar_System__c)TestFactory.createSObject(new Shared_Solar_System__c(Name = 'Oxford Barrett St. P3',
        //                                                                                                                        Service_Territories__c = 'WCMA',
        //                                                                                                                        Open__c = true,
        //                                                                                                                        Reserved_Capacity_kW_DC__c = '100',
        //                                                                                                                        Capacity_Committed_kW_DC__c = 100,
        //                                                                                                                        Total_System_Size_kWh_DC__c = 100,
        //                                                                                                                        System_Utility__c = 'National Grid',
        //                                                                                                                        Credit_Score_Requirement__c = 200,
        //                                                                                                                        Assignment_order__c = '3'));


        //Shared_Solar_System__c sss4 = (Shared_Solar_System__c)TestFactory.createSObject(new Shared_Solar_System__c(Name = 'Oxford Barrett St. P4',
        //                                                                                                                        Service_Territories__c = 'WCMA',
        //                                                                                                                        Open__c = true,
        //                                                                                                                        Reserved_Capacity_kW_DC__c = '100',
        //                                                                                                                        Capacity_Committed_kW_DC__c = 100,
        //                                                                                                                        Total_System_Size_kWh_DC__c = 100,
        //                                                                                                                        System_Utility__c = 'National Grid',
        //                                                                                                                        Credit_Score_Requirement__c = 200,
        //                                                                                                                        Assignment_order__c = '4'));
        //insert new List<Shared_Solar_System__c>{sss1, sss2, sss3, sss4};

        system.debug(sss1.Capacity_Available_to_be_Reserved__c);
        system.debug(sss1);      
        
        Partner__c Partner = new Partner__c(Name = 'Boston Solar');
        insert Partner;
        
        BSST__c newSalesTeam = new BSST__c (Name = 'Partner',
                                            Partner__c = Partner.Id,
                                            Custom_ID__c = 'partner');
                                            
        insert newSalesTeam;
        
        Lead lead = (Lead)TestFactory.createSObject(new Lead(LastName = 'Chan',
                                                             FirstName = 'Joey',
                                                             Email = 'test@email.com',
                                                             Electricity_Provider__c = 'National Grid',
                                                             Utility_1__c = 'National Grid',
                                                             Load_Zone__c = 'WCMA',
                                                             Company = 'Cloud Jedi',
                                                             Status = 'Qualified',
                                                             Product_Line__c = 'Community Solar',
                                                             Custom_ID__c = 'partner',
                                                             System_Assignment__c = 'Automatic - Assignment Order'));
        insert lead;
        
        Lead lead2 = new Lead (LastName = 'Jordan',
                                     FirstName = 'Pentaleri',
                                     Email = 'test@email.com',
                                     Electricity_Provider__c = 'National Grid',
                                     Utility_1__c = 'National Grid',
                                     Load_Zone__c = 'WCMA',
                                     Company = 'Cloud Jedi',
                                     Status = 'Qualified',
                                     Product_Line__c = 'Community Solar',
                                     System_Assignment__c = 'Automatic - Assignment Order');
        insert lead2;

        LASERCA__Personal_Credit_Report__c pcr = (LASERCA__Personal_Credit_Report__c)TestFactory.createSObject(new LASERCA__Personal_Credit_Report__c(
                                                                                        LASERCA__Lead__c = lead.Id,
                                                                                        LASERCA__Credit_Score_TransUnion__c = '700'), true);
                                                                                        
        LASERCA__Personal_Credit_Report__c pcr2 = (LASERCA__Personal_Credit_Report__c)TestFactory.createSObject(new LASERCA__Personal_Credit_Report__c(
                                                                                        LASERCA__Lead__c = lead2.Id,
                                                                                       LASERCA__Credit_Score_TransUnion__c = '700'), true);
        lead.Personal_Credit_Report__c = pcr.Id;
        lead2.Personal_Credit_Report__c = pcr2.Id;
        lead.Status = 'Qualified';
        lead2.Status = 'Qualified';
        update lead;

        System.debug([Select Id, Open__c, Capacity_Available_to_be_Reserved__c, Service_Territories__c, System_Utility__c From Shared_Solar_System__c Where Id = :sss1.Id]);


        Utility_Account_Log__c ual = (Utility_Account_Log__c)TestFactory.createSObject(new Utility_Account_Log__c(Lead__c = lead.Id,
                                                                                                                  Annual_Cost_of_Electricity__c = 10000,
                                                                                                                  Name_on_Account__c = 'Joey Chan'));
        insert ual;
        
        Utility_Account_Log__c ual2 = new Utility_Account_Log__c(Lead__c = lead2.Id,
                                                                 Annual_Cost_of_Electricity__c = 10000,
                                                                 Name_on_Account__c = 'Joey Chan');
        insert ual2;


        Test.startTest();
        System.debug('Starting LeadTriggerHandlerTest');
        System.debug('Debug SSS - ' + [Select Id, Open__c, Capacity_Available_to_be_Reserved__c, Service_Territories__c, System_Utility__c From Shared_Solar_System__c Where Id = :sss1.Id ]);
        Database.leadConvert lc = new Database.leadConvert();
        lc.setLeadId(lead.id);
        LeadStatus convertStatus = [SELECT Id, MasterLabel FROM LeadStatus WHERE IsConverted=true LIMIT 1];
        lc.setConvertedStatus(convertStatus.MasterLabel);
        lc.setDoNotCreateOpportunity(true);
        Database.LeadConvertResult lcr = Database.convertLead(lc);
        System.assert(lcr.isSuccess());
        
        Database.leadConvert ld = new Database.leadConvert();
        ld.setLeadId(lead2.id);
        LeadStatus convertStatus2 = [SELECT Id, MasterLabel FROM LeadStatus WHERE IsConverted=true LIMIT 1];
        ld.setConvertedStatus(convertStatus2.MasterLabel);
        ld.setDoNotCreateOpportunity(true);
        Database.LeadConvertResult ldr = Database.convertLead(ld);
       
        System.debug('Verifying the opportunity:');
        List<Opportunity> oppList = [Select Id, Name, AccountId, Shared_Solar_System__c, Shared_Solar_System__r.Name From Opportunity ];
        for(Opportunity opp : oppList){
            System.debug(opp);
        }
        System.assertEquals(1, oppList.size());
        Test.stopTest();
    }
}