src/objects/BSST__c.object
<CustomObject>
    <fields>
        <fullName>Partner__c</fullName>
        <label>Organization</label>
        <referenceTo>Partner__c</referenceTo>
        <relationshipLabel>Sales Team</relationshipLabel>
        <relationshipName>Boston_Solar_Sales_Team</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Sales Team</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Team</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Disbursal__c.object
<CustomObject>
    <fields>
        <fullName>Loan__c</fullName>
        <label>Loan</label>
        <referenceTo>Loan__c</referenceTo>
        <relationshipLabel>Disbursals</relationshipLabel>
        <relationshipName>Disbursals</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Partner__c</fullName>
        <label>Partner</label>
        <referenceTo>Partner__c</referenceTo>
        <relationshipLabel>Disbursals</relationshipLabel>
        <relationshipName>Disbursals</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>This status field marks what stage the disbursal is in the disbursal process. It also marks disbursal as ready for disbursement, which plays a major role in determining which disbursal records show up in the Daily Disbursal reports for BlueWave and Avidia.</description>
        <inlineHelpText>This status field marks what stage the disbursal is in the disbursal process. It also marks disbursal as ready for disbursement, which plays a major role in determining which disbursal records show up in the Daily Disbursal reports for BlueWave and Avidi</inlineHelpText>
        <label>Disbursal Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Ready for Disbursement</fullName>
                </value>
                <value>
                    <fullName>Disbursed</fullName>
                </value>
                <value>
                    <fullName>Hold</fullName>
                </value>
                <value>
                    <fullName>Ready for FBO Funding</fullName>
                </value>
                <value>
                    <fullName>Due</fullName>
                </value>
                <value>
                    <fullName>Reimbursed</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                    <isActive>false</isActive>
                    <label>Complete</label>
                </value>
                <value>
                    <fullName>Not yet disbursed</fullName>
                    <isActive>false</isActive>
                    <label>Not yet disbursed</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Disbursal</label>
    <nameField>
        <label>Disbursal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Disbursals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Annual_Income_Currency__c</fullName>
        <label>Annual Income</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Product lookup, for loans, set by an installer upon sending a new application or set by code after a credit check has determined qualifying products.</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Update_Dummy__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Update Dummy</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Lead</fullName>
        <active>true</active>
        <businessProcess>CS</businessProcess>
        <label>Lead</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Loan__c.object
<CustomObject>
    <fields>
        <fullName>Commencement_Datee__c</fullName>
        <inlineHelpText>The estimated commencement date of the loan, 30 days after the estimated completion date. Set by installers when providing system information.</inlineHelpText>
        <label>Commencement Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Set by LoanHandler when creating the Loan from the lead</inlineHelpText>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Loans</relationshipLabel>
        <relationshipName>Loans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Set by LoanHandler when the Loan is created from a Lead</inlineHelpText>
        <label>Partner</label>
        <referenceTo>Partner__c</referenceTo>
        <relationshipLabel>Loans</relationshipLabel>
        <relationshipName>Loans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Principall__c</fullName>
        <label>XXX Principal</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is a lookup to the Product record assigned to this loan.  The designated Product informs key loan determinants (e.g. interest rate, term, form of promissory note).</description>
        <inlineHelpText>This is a lookup to the Product record assigned to this loan.  The designated Product informs key loan determinants (e.g. interest rate, term, form of promissory note).</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Loans</relationshipLabel>
        <relationshipName>Loans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Agent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Set by LoanHandler when creating the Loan from the Lead</inlineHelpText>
        <label>Sales Agent</label>
        <referenceTo>BSST__c</referenceTo>
        <relationshipLabel>Loans</relationshipLabel>
        <relationshipName>Loans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>System_Costt__c</fullName>
        <inlineHelpText>The request loan amount (could be different than the true system cost)</inlineHelpText>
        <label>XXX System Cost</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Funds_Disbursed__c</fullName>
        <label>Total Funds Disbursed</label>
        <summarizedField>Disbursal__c.Amount__c</summarizedField>
        <summaryFilterItems>
            <field>Disbursal__c.Status__c</field>
            <operation>equals</operation>
            <value>Disbursed</value>
        </summaryFilterItems>
        <summaryForeignKey>Disbursal__c.Loan__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Update_Dummy__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Update Dummy</label>
        <type>Checkbox</type>
    </fields>
    <label>Loan</label>
    <nameField>
        <label>Loan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loans</pluralLabel>
    <recordTypes>
        <fullName>Loan</fullName>
        <active>true</active>
        <label>Loan</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Partner__c.object
<CustomObject>
    <fields>
        <fullName>Total_Funds_Disbursed__c</fullName>
        <description>Sum of funds disbursed to Loan Partner</description>
        <label>Total Funds Disbursed</label>
        <summarizedField>Disbursal__c.Amount__c</summarizedField>
        <summaryFilterItems>
            <field>Disbursal__c.Status__c</field>
            <operation>equals</operation>
            <value>Disbursed</value>
        </summaryFilterItems>
        <summaryForeignKey>Disbursal__c.Partner__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Partner</label>
    <nameField>
        <label>Partner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partners</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Partner_Task__c.object
<CustomObject>
    <description>The Partner Task object is used to highlight exactly what it is the partner has to do next in order to correctly process a customer. They are used specifically in the partner portal, but also internally in the Salesforce UI.</description>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Partner Tasks</relationshipLabel>
        <relationshipName>Partner_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Loan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Loan</label>
        <referenceTo>Loan__c</referenceTo>
        <relationshipLabel>Partner Tasks</relationshipLabel>
        <relationshipName>Partner_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Partner__c</fullName>
        <label>Partner</label>
        <referenceTo>Partner__c</referenceTo>
        <relationshipLabel>Partner Tasks</relationshipLabel>
        <relationshipName>Partner_Tasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sales_Representative__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the relationship to the Sales Team object</description>
        <label>Sales Representative</label>
        <referenceTo>BSST__c</referenceTo>
        <relationshipLabel>Partner Tasks</relationshipLabel>
        <relationshipName>Partner_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Incomplete</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Partner Task</label>
    <nameField>
        <label>Partner Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Residential_Equipment__c.object
<CustomObject>
    <fields>
        <fullName>Generator_Nameplate_Capacity__c</fullName>
        <label>Generator Nameplate Capacity (kW)</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Interconnected__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Interconnected</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Interconnection_Date__c</fullName>
        <label>Interconnection Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Residential Equipment</relationshipLabel>
        <relationshipName>Residential_Equipment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Loan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Loan</label>
        <referenceTo>Loan__c</referenceTo>
        <relationshipLabel>Residential Equipment</relationshipLabel>
        <relationshipName>Residential_Equipment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Mechanical_Installation_Date__c</fullName>
        <label>Mechanical Installation Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Mechanically_Installed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Mechanically Installed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Number_of_Inverters__c</fullName>
        <label>Number of Inverters</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Modules__c</fullName>
        <label>Number of Modules</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type_of_Inverter__c</fullName>
        <label>Type of Inverter</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type_of_Module__c</fullName>
        <label>Type of Module</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Residential Equipment</label>
    <nameField>
        <label>Residential E Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Residential Equipment</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/User/fields/Partner_ID__c.field-meta.xml
<CustomField>
    <fullName>Partner_ID__c</fullName>
    <formula>Contact.Partner_Lookup__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Partner ID</label>
    <type>Text</type>
</CustomField>

src/classes/SLPCustomerHandler.cls
public with sharing class SLPCustomerHandler {    

	@AuraEnabled 
	public static Loan__c getCustomerLoan (String loanId) {
		System.debug('the loanId is ' + loanId);
	  User u = [SELECT Id, Partner_ID__c FROM User WHERE Id = :UserInfo.getUserId()];
		List<Loan__c> loanList = [SELECT Id, Name, Product__r.Name, System_Costt__c, Commencement_Datee__c, 
									Total_Funds_Disbursed__c, Sales_Agent__r.Name, Product__r.ProductCode  
									FROM Loan__c 
									WHERE Id = : loanId];
		System.debug('loanList is ' + loanList);
		return loanList.get(0);    	    
	}

  @AuraEnabled 
  public static List<Loan__c> getAllCustomers (String searchValue) {
    System.debug('Begin the getAllCustomers method');
    User u = [SELECT Id, Partner_ID__c FROM User WHERE Id = :UserInfo.getUserId()];
    if(searchValue == null || searchValue == ''){
      List<Loan__c> loanList = [SELECT Id, Name, Product__r.Name, System_Costt__c, Commencement_Datee__c, 
                    Total_Funds_Disbursed__c, Sales_Agent__r.Name, Product__r.ProductCode,
                    (SELECT Id, Name FROM Partner_Tasks__r WHERE Status__c = 'Pending' LIMIT 1)  
                    FROM Loan__c 
                    WHERE Partner__r.Name = 'BlueWave Customer Care'];      
    return loanList;      
    }else {
      List<Loan__c> loanList = [SELECT Id, Name, Product__r.Name, System_Costt__c, Commencement_Datee__c, 
                    Total_Funds_Disbursed__c, Sales_Agent__r.Name, Product__r.ProductCode,
                    (SELECT Id, Name FROM Partner_Tasks__r WHERE Status__c = 'Pending' LIMIT 1)  
                    FROM Loan__c 
                    WHERE Name LIKE : '%'+searchValue+'%'
                    AND Partner__r.Name = 'BlueWave Customer Care'];
    return loanList;                               
    }
  }

  @AuraEnabled 
  public static Residential_Equipment__c getCustomerInformation (String loanId) {
    System.debug('the loanId is ' + loanId);
    User u = [SELECT Id, Partner_ID__c FROM User WHERE Id = :UserInfo.getUserId()];
    List<Residential_Equipment__c> equipmentList = [SELECT Id, Name, Loan__r.Name, Loan__r.Lead__r.Update_Dummy__c, Loan__r.Lead__r.Annual_Income_Currency__c, Loan__r.Lead__r.Id, Generator_Nameplate_Capacity__c, Type_of_Module__c, Type_of_Inverter__c,
                                                      Number_of_Inverters__c, Number_of_Modules__c, Loan__r.Product__r.Name, Loan__r.System_Costt__c, 
                                                      Loan__r.Commencement_Datee__c, Loan__r.Maturity_Datee__c, Interconnected__c, Mechanically_Installed__c,
                                                      Interconnection_date__c, Mechanical_Installation_Date__c, Loan__r.Principall__c, Loan__r.Principal__c
                                                    FROM Residential_Equipment__c 
                                                    WHERE Loan__c = : loanId 
                                                    LIMIT 1];
    return equipmentList.get(0);         
  }


	@AuraEnabled 
	public static String getProgressBarData(String loanId) {
		System.debug('the loanId is ' + loanId);
		String returnTaskName;
	    User u = [SELECT Id, Partner_ID__c FROM User WHERE Id = :UserInfo.getUserId()];
	    List<Partner_Task__c> completedTaskList = [SELECT Id, Name, Status__c, Completion_Date__c, Task_Sequence__c, Loan__r.Name
	    											FROM Partner_Task__c
	    											WHERE Loan__c = : loanId
	    											AND Status__c = 'Pending'
				                                  	AND Parent__c = true
				                                  	AND Sub_Task_Type__c = null
				                                  	AND Parent_Task__c = null    										
	    											ORDER BY Completion_Date__c, Task_Sequence__c DESC
	    											LIMIT 1];
		if(completedTaskList.size() > 0){
			for (Partner_Task__c task : completedTaskList){
				returnTaskName = task.Name;
			}				
		}   											
		//System.debug('the completedTaskList is ' + completedTaskList.get(0).Name);
		return returnTaskName;    	    
	}

   @AuraEnabled
    public static List<Partner_Task__c> getLoanCustomerTasks(String loanId) {
        User u = [SELECT Id, Partner_ID__c FROM User WHERE Id = :UserInfo.getUserId()];
        List<Partner_Task__c> taskList = [SELECT Id, Name, Completion_Date__c, SubTasks__c, Status__c, Loan__r.Id,
                                        Loan__c, Task_Sequence__c, Task_Type__c
                                  			FROM Partner_Task__c 
                                  			WHERE Loan__c = : loanId 
		                                  	AND Parent__c = true
		                                  	AND Sub_Task_Type__c = null
		                                  	AND Parent_Task__c = null                                  			
                                  			ORDER BY Task_Sequence__c ASC];                               
        return taskList;
    }

   @AuraEnabled
    public static List<Partner_Task__c> getLoanParentSubTasks(String taskId) {
        User u = [SELECT Id, Partner_ID__c FROM User WHERE Id = :UserInfo.getUserId()];
        List<Partner_Task__c> taskList = [SELECT Id, Name, Completion_Date__c, SubTasks__c, Parent_Task__r.Name, 
                                          Status__c, Loan__r.Id, Loan__c, Task_Type__c, Task_Sequence__c
                                  			FROM Partner_Task__c 
		                                  	WHERE Parent_Task__c = : taskId                                 			
                                  			ORDER BY Task_Sequence__c ASC];                               
        
        System.debug('task list is ' + taskList);
        return taskList;
    }  

   @AuraEnabled
    public static List<Disbursal__c> getCompleteLoanDisbursals(String loanId, String searchValue) {
     //change SOQL to one query with parameters in in using database.query and string value concatenated together. see Joey Chan strategy. 
    	  System.debug('begin the getCompleteLoanDisbursals method');
        User u = [SELECT Id, Partner_ID__c FROM User WHERE Id = :UserInfo.getUserId()];
        if(loanId != null && searchValue == null) {
          List<Disbursal__c> disbursalList = [SELECT Id, Name, Partner_Confirmation__c, Date_of_Disbursal__c, Loan__r.Name, 
                                      Disbursal_Percentage__c, Status__c, Amount__c, Type__c 
                                    FROM Disbursal__c 
                                    WHERE Loan__c = : loanId
                                    AND Status__c = 'Complete' 
                                    ORDER BY Date_of_Disbursal__c, createdDate];                               
          return disbursalList;
        }else if(loanId == null && (searchValue == null || searchValue == '')) {
          List<Disbursal__c> disbursalList = [SELECT Id, Name, Partner_Confirmation__c, Date_of_Disbursal__c, Loan__r.Name, 
                                        Disbursal_Percentage__c, Status__c, Amount__c, Type__c 
                                      FROM Disbursal__c 
                                      WHERE Partner__r.Name = 'BlueWave Customer Care'
                                      AND Status__c = 'Complete'                                       
                                      ORDER BY Date_of_Disbursal__c, createdDate ASC];                               
          return disbursalList;          
        }else if(loanId == null && searchValue != null) {
          List<Disbursal__c> disbursalList = [SELECT Id, Name, Partner_Confirmation__c, Date_of_Disbursal__c, Loan__r.Name, 
                                      Disbursal_Percentage__c, Status__c, Amount__c, Type__c 
                                    FROM Disbursal__c 
                                    WHERE Partner__r.Name = 'BlueWave Customer Care' 
                                    AND Loan__r.Name LIKE : '%'+searchValue+'%'
                                    AND Status__c = 'Complete' 
                                    ORDER BY Date_of_Disbursal__c, createdDate ASC];                               
          return disbursalList;          
        }else {
          List<Disbursal__c> disbursalList = [SELECT Id, Name, Partner_Confirmation__c, Date_of_Disbursal__c, Loan__r.Name, 
                                        Disbursal_Percentage__c, Status__c, Amount__c, Type__c 
                                      FROM Disbursal__c 
                                      WHERE Partner__r.Name = 'BlueWave Customer Care'
                                      AND Status__c = 'Complete'                                       
                                      ORDER BY Date_of_Disbursal__c, createdDate ASC];                               
          return disbursalList;          
        }
    }

   @AuraEnabled
    public static List<Disbursal__c> getIncompleteLoanDisbursals(String loanId, String searchValue) {
     //change SOQL to one query with parameters in in using database.query and string value concatenated together. see Joey Chan strategy. 
        System.debug('begin the getIncompleteLoanDisbursals method');
        User u = [SELECT Id, Partner_ID__c FROM User WHERE Id = :UserInfo.getUserId()];
        if(loanId != null && searchValue == null) {
          List<Disbursal__c> disbursalList = [SELECT Id, Name, Partner_Confirmation__c, Date_of_Disbursal__c, Loan__r.Name, 
                                      Disbursal_Percentage__c, Status__c, Amount__c, Type__c 
                                    FROM Disbursal__c 
                                    WHERE Loan__c = : loanId
                                    AND Status__c = 'Not yet disbursed' 
                                    ORDER BY createdDate];                               
          return disbursalList;
        }else if(loanId == null && (searchValue == null || searchValue == '')) {
          List<Disbursal__c> disbursalList = [SELECT Id, Name, Partner_Confirmation__c, Date_of_Disbursal__c, Loan__r.Name, 
                                        Disbursal_Percentage__c, Status__c, Amount__c, Type__c 
                                      FROM Disbursal__c 
                                      WHERE Partner__r.Name = 'BlueWave Customer Care'
                                      AND Status__c = 'Not yet disbursed'                                       
                                      ORDER BY createdDate ASC];                               
          return disbursalList;          
        }else if(loanId == null && searchValue != null) {
          List<Disbursal__c> disbursalList = [SELECT Id, Name, Partner_Confirmation__c, Date_of_Disbursal__c, Loan__r.Name, 
                                      Disbursal_Percentage__c, Status__c, Amount__c, Type__c 
                                    FROM Disbursal__c 
                                    WHERE Partner__r.Name = 'BlueWave Customer Care' 
                                    AND Loan__r.Name LIKE : '%'+searchValue+'%'
                                    AND Status__c = 'Not yet disbursed' 
                                    ORDER BY createdDate ASC];                               
          return disbursalList;          
        }else {
          List<Disbursal__c> disbursalList = [SELECT Id, Name, Partner_Confirmation__c, Date_of_Disbursal__c, Loan__r.Name, 
                                        Disbursal_Percentage__c, Status__c, Amount__c, Type__c 
                                      FROM Disbursal__c 
                                      WHERE Partner__r.Name = 'BlueWave Customer Care'
                                      AND Status__c = 'Not yet disbursed'                                       
                                      ORDER BY createdDate ASC];                               
          return disbursalList;          
        }
    }

   @AuraEnabled
    public static void updateDisbursals(String disbursalId, Boolean disbursalValue) {
      List<Disbursal__c> disbursalList = [SELECT Id, Name, Partner_Confirmation__c  FROM Disbursal__c  WHERE Id = : disbursalId LIMIT 1];

      disbursalList.get(0).Partner_Confirmation__c = disbursalValue;
      update disbursalList;
    }    


   @AuraEnabled
    public static Map<String, List<Partner_Task__c>> getTaskMap (String loanId) {
        Map<String, List<Partner_Task__c>> taskMap = new Map<String, List<Partner_Task__c>>();
        User u = [SELECT Id, Partner_ID__c FROM User WHERE Id = :UserInfo.getUserId()];
        for (Partner_Task__c partnerTask : [SELECT Id, Name, Completion_Date__c, Parent_Task__r.Name, 
        									                       Status__c, Loan__r.Id, Loan__c, Task_Sequence__c,
                            										(SELECT Id, Name, Status__c, Completion_Date__c FROM
                            										subTasks__r)
                                      			FROM Partner_Task__c 
    		                                  	WHERE Parent__c = true
    		                                  	AND Sub_Task_Type__c = null
    		                                  	AND Parent_Task__c = null 
    		                                  	AND Loan__c = : loanId                                			                                			
                                      			ORDER BY Task_Sequence__c ASC]){
        	taskMap.put(partnerTask.Name, partnerTask.subTasks__r);
        }                              
        
        System.debug('taskMap is ' + taskMap);
        return taskMap;
    } 

   @AuraEnabled
    public static void saveCustomerInformation(Residential_Equipment__c equipment, String equipmentId, String loanId, Loan__c loan) {
        System.debug('begin the saveEquipmentInformation method');
        User u = [SELECT Id, Partner_ID__c FROM User WHERE Id = :UserInfo.getUserId()];
        if(equipment.Type_of_Module__c == ' ' ){
        }
        //update the equipment information
        Residential_Equipment__c equipmentRecord = [SELECT Id, Lead__r.Id, Name, Generator_Nameplate_Capacity__c, Type_of_Module__c, Number_of_Modules__c,
                                                           Type_of_Inverter__c, Number_of_Inverters__c, Mechanical_Installation_Date__c, Interconnection_date__c,
                                                           Mechanically_Installed__c, Interconnected__c 
                                                    FROM Residential_Equipment__c
                                                    WHERE Id = : equipmentId];
        if(equipment.Generator_NamePlate_Capacity__c != null){
          equipmentRecord.Generator_Nameplate_Capacity__c = equipment.Generator_NamePlate_Capacity__c;
        }
        if(String.isNotBlank(equipment.Type_of_Module__c)){
          equipmentRecord.Type_of_Module__c = equipment.Type_of_Module__c;
        }        
        if(equipment.Number_of_Modules__c != null){
          equipmentRecord.Number_of_Modules__c = equipment.Number_of_Modules__c;
        }
        if(String.isNotBlank(equipment.Type_of_Inverter__c)){
          equipmentRecord.Type_of_Inverter__c = equipment.Type_of_Inverter__c;
        }    
        if(equipment.Number_of_Inverters__c != null){
          equipmentRecord.Number_of_Inverters__c = equipment.Number_of_Inverters__c;
        }          
        if(equipment.Mechanical_Installation_Date__c != null){
          equipmentRecord.Mechanical_Installation_Date__c = equipment.Mechanical_Installation_Date__c;
        }     
        if(equipment.Interconnection_Date__c != null){
          equipmentRecord.Interconnection_Date__c = equipment.Interconnection_Date__c;
        }
        if(equipment.Mechanically_Installed__c != equipmentRecord.Mechanically_Installed__c){
          equipmentRecord.Mechanically_Installed__c = equipment.Mechanically_Installed__c;
        }
        if(equipment.Interconnected__c != equipmentRecord.Interconnected__c){
          equipmentRecord.Interconnected__c = equipment.Interconnected__c;
        }                                                                                                    


        update equipmentRecord;

        //update the loan information  
        Loan__c loanRecord = [SELECT Id, Name, Commencement_Datee__c, System_Costt__c  
                              FROM Loan__c
                              WHERE Id = : loanId];
        if(loan.Commencement_Datee__c  != null){
          loanRecord.Commencement_Datee__c   = loan.Commencement_Datee__c;      
        }
        if(loan.System_Costt__c  != null){
          loanRecord.System_Costt__c   = loan.System_Costt__c;      
        }        
        update loanRecord;

        Lead leadRecord = [SELECT Id, Update_Dummy__c FROM lead WHERE Id = : equipmentRecord.Lead__r.Id];
        if(leadRecord.Update_Dummy__c == true){
          leadRecord.Update_Dummy__c = false;
        }else{
          leadRecord.Update_Dummy__c = true;
        }
        update leadRecord;
    }
    
   //@AuraEnabled
   // public static void saveMechanicalInstallationDate(String equipmentId, String mechDate) {
   //     System.debug('begin the saveMechanicalInstallationDate method');
   //     System.debug('the equipment id is ' + equipmentId);
   //     System.debug('the mechDate is ' + mechDate);

   //     //DateTime mechDateTimeValue = DateTime.newInstance(mechDate);
   //     //Date mechDateVdalue =  Date.newinstance(mechDateTimeValue.year(), mechDateTimeValue.month(), mechDateTimeValue.day());
   //     //System.debug('the parsed date is ' + mechDateValue);

   //     User u = [SELECT Id, Partner_ID__c FROM User WHERE Id = :UserInfo.getUserId()];
   //     Residential_Equipment__c equipmentRecord = [SELECT Id, Name, Mechanical_Installation_Date__c
   //                                                 FROM Residential_Equipment__c
   //                                                 WHERE Id = : equipmentId];
   //     Date mechDateValue = Date.valueOf(mechDate);                                                    
   //     equipmentRecord.Mechanical_Installation_Date__c = mechDateValue;                                                    
   //     update equipmentRecord;
   // }

    @AuraEnabled
    public static Id saveTheFile(Id parentId, String fileName, String base64Data, String contentType) { 
        System.debug('begin the saveTheFile method');
        System.debug('parent id is ' + parentId);

        base64Data = EncodingUtil.urlDecode(base64Data, 'UTF-8');
        
        Attachment a = new Attachment();
        a.parentId = parentId;
 
        a.Body = EncodingUtil.base64Decode(base64Data);
        a.Name = fileName;
        a.ContentType = contentType;
        
        insert a;
        System.debug('the file is ' + a);
        return a.Id;
    }    
}