src/objects/BSST__c.object
<CustomObject>
    <fields>
        <fullName>Custom_ID__c</fullName>
        <label>Custom ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Partner__c</fullName>
        <label>Organization</label>
        <referenceTo>Partner__c</referenceTo>
        <relationshipLabel>Sales Team</relationshipLabel>
        <relationshipName>Boston_Solar_Sales_Team</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Sales Team</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Team</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Custom_ID__c</fullName>
        <label>Custom ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Load_Zone_Utility__c</fullName>
        <formula>Zip_Code_Lookup_Field__r.Load_Zone__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>XXXXX Load Zone Utility</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parcel_Zip__c</fullName>
        <description>Set at least by Form Assembly forms (e.g. 381607)</description>
        <label>Parcel Zip</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Utility__c</fullName>
        <formula>IF(INCLUDES(  Utility_1__c , &quot;Eversource&quot;), &quot;Eversource&quot;, 
IF(INCLUDES(  Utility_1__c , &quot;National Grid&quot;), &quot;National Grid&quot;,
IF(INCLUDES(  Utility_1__c , &quot;Unitil&quot;), &quot;Unitil&quot;,
IF(INCLUDES(  Utility_1__c , &quot;Municipal Electric Department&quot;), &quot;Municipal Electric Department&quot;,
IF(INCLUDES(  Utility_1__c , &quot;Duke Energy&quot;), &quot;Duke Energy&quot;, 
IF(INCLUDES(  Utility_1__c , &quot;SCE&amp;G&quot;), &quot;SCE&amp;G&quot;, 
 &quot;Other&quot;))))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>XXXXX Utility</label>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Lead</fullName>
        <active>true</active>
        <businessProcess>CS</businessProcess>
        <label>Lead</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Load_U__c.object
<CustomObject>
    <description>General list of Massachusetts Zip Codes and their corresponding Load Zones and Utiliy providers.</description>
    <fields>
        <fullName>LZ__c</fullName>
        <label>Load Zone</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Town__c</fullName>
        <label>Town</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Utility__c</fullName>
        <label>XXXX Utility</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <label>Load Zone &amp; Utility</label>
    <nameField>
        <label>Zip Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Load Zones &amp; Utilities</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Custom_ID__c</fullName>
        <label>Custom ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Load_Zone_Utility_4__c</fullName>
        <label>Load Zone &amp; Utility</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>NEMA Eversource</fullName>
                </value>
                <value>
                    <fullName>NEMA Municipal Electric Department</fullName>
                </value>
                <value>
                    <fullName>NEMA National Grid</fullName>
                </value>
                <value>
                    <fullName>NEMA/SEMA Eversource</fullName>
                </value>
                <value>
                    <fullName>NEMA/WCMA Municipal Electric Department</fullName>
                </value>
                <value>
                    <fullName>NEMA/WCMA National Grid</fullName>
                </value>
                <value>
                    <fullName>SEMA Eversource</fullName>
                </value>
                <value>
                    <fullName>SEMA Municipal Electric Department</fullName>
                </value>
                <value>
                    <fullName>SEMA National Grid</fullName>
                </value>
                <value>
                    <fullName>SEMA National Grid/Eversource</fullName>
                </value>
                <value>
                    <fullName>SEMA/WCMA National Grid</fullName>
                </value>
                <value>
                    <fullName>WCMA Eversource</fullName>
                </value>
                <value>
                    <fullName>WCMA Eversource / Municipal Electric Department</fullName>
                </value>
                <value>
                    <fullName>WCMA Municipal Electric Department</fullName>
                </value>
                <value>
                    <fullName>WCMA National Grid</fullName>
                </value>
                <value>
                    <fullName>WCMA Unitil</fullName>
                </value>
                <value>
                    <fullName>Manual Lookup Required</fullName>
                </value>
                <value>
                    <fullName>Bahamas Electricity Corporation</fullName>
                </value>
                <value>
                    <fullName>Grand Bahama Power Company</fullName>
                </value>
                <value>
                    <fullName>Orange and Rockland Utilities</fullName>
                </value>
                <value>
                    <fullName>Central Hudson Gas &amp; Electric</fullName>
                </value>
                <value>
                    <fullName>Green Mountain Power</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Parcel_ZIp__c</fullName>
        <label>Service Zip Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Utility__c</fullName>
        <formula>IF( 


right(TEXT( Load_Zone_Utility_4__c  ),5) = &apos;SCE&amp;G&apos;,

right(TEXT( Load_Zone_Utility_4__c  ),5),

IF( 


right(TEXT( Load_Zone_Utility_4__c  ),10) = &apos;Eversource&apos;,

right(TEXT( Load_Zone_Utility_4__c  ),10),

IF(

right(TEXT( Load_Zone_Utility_4__c  ),13) = &apos;National Grid&apos;,


right(TEXT( Load_Zone_Utility_4__c  ),13),

IF(

right(TEXT( Load_Zone_Utility_4__c  ),6) = &apos;Unitil&apos;,


right(TEXT( Load_Zone_Utility_4__c  ),6),

IF(

right(TEXT( Load_Zone_Utility_4__c  ),29) = &apos;Municipal Electric Department&apos;,


right(TEXT( Load_Zone_Utility_4__c  ),29),

IF(

TEXT( Load_Zone_Utility_4__c  ) = &apos;Manual Lookup Required&apos;,

&apos;Manual Lookup Required&apos;, null))))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Utility (OLD)</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Partner__c.object
<CustomObject>
    <label>Partner</label>
    <nameField>
        <label>Partner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partners</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Town__c.object
<CustomObject>
    <fields>
        <fullName>Utility__c</fullName>
        <label>Utility</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>National Grid</fullName>
                </value>
                <value>
                    <fullName>Eversource</fullName>
                </value>
                <value>
                    <fullName>Eversource/Muni</fullName>
                </value>
                <value>
                    <fullName>Eversource/NGRID</fullName>
                </value>
                <value>
                    <fullName>Municipal/NGRID</fullName>
                </value>
                <value>
                    <fullName>Municipal</fullName>
                </value>
                <value>
                    <fullName>Green Mountain Power</fullName>
                </value>
                <value>
                    <fullName>Orange &amp; Rockland</fullName>
                </value>
                <value>
                    <fullName>PSE&amp;G</fullName>
                </value>
                <value>
                    <fullName>SCE&amp;G</fullName>
                </value>
                <value>
                    <fullName>Unitil</fullName>
                </value>
                <value>
                    <fullName>Green Mountain</fullName>
                    <isActive>false</isActive>
                    <label>Green Mountain</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Town</label>
    <nameField>
        <label>Town Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Towns</pluralLabel>
    <recordTypes>
        <fullName>Test</fullName>
        <active>true</active>
        <label>Test</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Utility__c.object
<CustomObject>
    <fields>
        <fullName>Number_of_Decimal_Places__c</fullName>
        <inlineHelpText>Used for calculating kW subscriptions for SOs</inlineHelpText>
        <label>Number of Decimal Places</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Utility</label>
    <nameField>
        <label>Utility Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ZipCode_Utility_Junction__c.object
<CustomObject>
    <fields>
        <fullName>Load_Zone_Utility__c</fullName>
        <inlineHelpText>Lookup to the Load Zone and Utility Object</inlineHelpText>
        <label>Load Zone &amp; Utility</label>
        <referenceTo>Load_U__c</referenceTo>
        <relationshipLabel>ZipCode Utility Junctions</relationshipLabel>
        <relationshipName>ZipCode_Utility_Junctions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Utility__c</fullName>
        <label>Utility</label>
        <referenceTo>Utility__c</referenceTo>
        <relationshipLabel>ZipCode Utility Junctions</relationshipLabel>
        <relationshipName>ZipCode_Utility_Junctions</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>ZipCode Utility Junction</label>
    <nameField>
        <displayFormat>ZUJ-{00000}</displayFormat>
        <label>ZipCode Utility Junction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ZipCode Utility Junctions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/opp4LZUTriggerTestClass.cls
@isTest
private class opp4LZUTriggerTestClass 
{
 
Static testMethod void validateLZU()
{
        Utility__c eversource = new Utility__c(
            Name = 'Eversource',
            Number_of_Decimal_Places__c = 2
        );

        Utility__c nationalGrid = new Utility__c(
            Name = 'National Grid',
            Number_of_Decimal_Places__c = 2
        );

        insert new List<Utility__c>{eversource, nationalGrid};

        Load_U__c newLZU = new Load_U__c ( name = '02052', LZ__c= 'NEMA', town__c = 'Medfield');
        newLZU.name = '02052';
        newLZU.LZ__C = 'NEMA';
        newLZU.town__c = 'Medfield';
        insert newLZU;

        ZipCode_Utility_Junction__c junction = new ZipCode_Utility_Junction__c(
            Load_Zone_Utility__c = newLZU.Id,
            Utility__c = eversource.Id
        );
        insert junction;
        
        partner__c newPartner = new partner__c(name = 'Partner');
        insert newPartner;
        
        bsst__c newBSST = new BSST__c (name ='Cole Swain', partner__c = newPartner.id, custom_id__c = 'BWCSwain');
        Insert newBSST;

        lead newLead = new lead(firstName = 'Cole', lastName = 'Swain', company = 'BlueWave', status = 'Qualified', Parcel_Zip__c = '02052', custom_id__c = 'BWCSwain') ;

        insert newLead;    
 
        test.startTest();
        
               database.leadConvert lc = new database.leadConvert();
               lc.setLeadId(newLead.id);
 
               leadStatus convertStatus = [SELECT Id, MasterLabel FROM LeadStatus WHERE IsConverted=true LIMIT 1];
               lc.setConvertedStatus(convertStatus.MasterLabel);
 
               Database.LeadConvertResult lcr = Database.convertLead(lc);
               System.assert(lcr.isSuccess());
 
               lc.setOpportunityName('Cole Swain');
 
        test.stopTest();
               
               opportunity opQuery = [SELECT name,Load_Zone_Utility_4__c FROM opportunity WHERE name != null];
               system.assertEquals(null, opQuery.Load_Zone_Utility_4__c);
 
 
}
}