src/objects/BSST__c.object
<CustomObject>
    <fields>
        <fullName>A_Rate__c</fullName>
        <label>A Rate</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>B_Rate__c</fullName>
        <label>B Rate</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CSA_Threshold__c</fullName>
        <label>CSA Threshold</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Commission_Structure__c</fullName>
        <label>Commission Structure</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Custom_ID__c</fullName>
        <label>Custom ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Individual_Commission__c</fullName>
        <label>Individual Commission</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Partner__c</fullName>
        <label>Organization</label>
        <referenceTo>Partner__c</referenceTo>
        <relationshipLabel>Sales Team</relationshipLabel>
        <relationshipName>Boston_Solar_Sales_Team</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Rate_Key__c</fullName>
        <label>Rate Key</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Rate__c</fullName>
        <label>Loan Commission Rate</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>commission_cap__c</fullName>
        <label>Loan Cap</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Sales Team</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Team</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Commission_Structure__c.object
<CustomObject>
    <fields>
        <fullName>Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Partner</label>
        <referenceTo>Partner__c</referenceTo>
        <relationshipLabel>Commission Structures</relationshipLabel>
        <relationshipName>Commission_Structures</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Commission Structure</label>
    <nameField>
        <label>Commission Structure Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Commission Structures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Loan_Data__c.object
<CustomObject>
    <label>Capital Pool</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Capital Pools</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Loan_Traunch__c.object
<CustomObject>
    <fields>
        <fullName>Capital_Outflows__c</fullName>
        <label>Capital Reserved</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Initial_Capital__c</fullName>
        <label>Initial Capital</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Loan_Data__c</fullName>
        <label>Capital Pool</label>
        <referenceTo>Loan_Data__c</referenceTo>
        <relationshipLabel>Loan Tranches</relationshipLabel>
        <relationshipName>Loan_Tranches</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Tranche_Cap__c</fullName>
        <label>Net Cash to BlueWave</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Loan Tranche</label>
    <nameField>
        <label>Tranche</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Tranches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>BS_Sales_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Person</label>
        <referenceTo>BSST__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CS_Capacity_Allocated__c</fullName>
        <inlineHelpText>Sum of Future Customer Subscription (KW DC) on Utility Account Subscriptions when Opportunity is set to Complete. Used in Docusign.</inlineHelpText>
        <label>Customer Subscription kW DC at Complete</label>
        <precision>9</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Commission_Structure__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Commission Structure</label>
        <referenceTo>Commission_Structure__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Custom_ID__c</fullName>
        <label>Custom ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Line__c</fullName>
        <label>Product Line</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>System_Size__c</fullName>
        <inlineHelpText>kw - DC</inlineHelpText>
        <label>System Size (kW)</label>
        <precision>9</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Partner__c.object
<CustomObject>
    <fields>
        <fullName>A_Rate__c</fullName>
        <label>A Rate (kW DC)</label>
        <precision>13</precision>
        <scale>5</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>B_Rate__c</fullName>
        <label>B Rate (kW DC)</label>
        <precision>13</precision>
        <scale>5</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CSA_Threshold__c</fullName>
        <label>CSA Threshold (kW)</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Commission_Structure__c</fullName>
        <label>Commission Structure</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rate_Key__c</fullName>
        <label>Rate Key</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Partner</label>
    <nameField>
        <label>Partner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partners</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/testCalculateSalesCommissions.cls
@isTest
private class testCalculateSalesCommissions {

Static testMethod void CSAcalculateSalesComm(){

/*Date myDate = Date.newInstance(2015, 2, 17);

loan_data__c newData = new loan_data__c(name = 'Data');
insert newData;

Loan_Traunch__c newTranche = new Loan_Traunch__c (name = 'Avidia 1', loan_data__c = newData.id, Tranche_Cap__c = 1100, Initial_Capital__c = 500, capital_outflows__c = 300);
insert newTranche;

partner__c newPartner = new partner__c(name = 'Boston Solar',a_rate__c =0.08, b_rate__c= 0.1, commission_structure__c ='A');
insert newPartner;

BSST__c newBSST = new BSST__c(name = 'Cole Swain', custom_id__c = 'cole', a_rate__c =0.08, partner__c = newPartner.id, b_rate__c= 0.1, csa_threshold__c = 10, commission_structure__c = 'Vivint');
BSST__c newBSSTResi = new BSST__c(name = 'Tamara', custom_id__c = 'resi', a_rate__c =0.08, partner__c = newPartner.id, b_rate__c= 0.1, Rate__c = 50, commission_cap__c = 350);

insert newBSST;
insert newBSSTResi;

partner__c partnerQueryBS = [SELECT id FROM partner__c WHERE partner__c.name = 'Boston Solar'];
BSST__c salesQueryBS = [SELECT id FROM BSST__c WHERE BSST__c.name = 'Cole Swain'];

Opportunity newOpportunity = new Opportunity(BS_Sales_ID__c = newBSST.id, product_line__c = 'Community Solar', name = 'Tester', type = 'New Business', closeDate = myDate, stageName='Complete', CS_Capacity_Allocated__c = 5, custom_id__c = 'cole'); 
Opportunity newOpportunity2 = new Opportunity(BS_Sales_ID__c = newBSST.id, product_line__c = 'Community Solar',  name = 'Tester2', type = 'New Business', closeDate = myDate, stageName='Complete', CS_Capacity_Allocated__c = 3.2, custom_id__c = 'cole'); 
opportunity newOpportunity7 = new opportunity(loan_assignment__c = 'Automatic' , product_line__c = 'Residential Loan',  loan_traunch__c = newTranche.id, name = 'ResiTester', type = 'New Business', closeDate = myDate, stageName='Complete', system_size__c = 6, custom_id__c = 'resi');

insert newOpportunity;
insert newOpportunity2;
insert newOpportunity7;

test.startTest(); 
  
update newOpportunity;
update newOpportunity2;
update newOpportunity7;
   
test.stopTest();

BSST__c salesQuery = [SELECT name, individual_commission__c FROM BSST__c WHERE name = 'Cole Swain'];
 
system.assertEquals(null, salesQuery.individual_commission__c);
 
}

Static testMethod void CSBcalculateSalesComm(){

Date myDate = Date.newInstance(2015, 2, 17);

partner__c newpartner2 = new partner__c(name = 'Boston Solar',a_rate__c =0.08, b_rate__c= 0.1, commission_structure__c ='B');
insert newPartner2;

BSST__c newBSST2 = new BSST__c(name = 'Cole Swain',partner__c = newPartner2.id, custom_id__c = 'swain', a_rate__c =0.16, b_rate__c= 0.18, CSA_Threshold__c = 100, rate_key__c = 5,commission_structure__c ='B');

insert newBSST2; 


partner__c partnerQueryNBS = [SELECT id FROM partner__c WHERE partner__c.name = 'Boston Solar'];
BSST__c salesQueryNBS = [SELECT id FROM BSST__c WHERE BSST__c.name = 'Cole Swain'];

Opportunity newOpportunity3 = new Opportunity(product_line__c = 'Community Solar', name = 'Tester3', stageName = 'Complete', type = 'New Business', closeDate = myDate , CS_Capacity_Allocated__c = 3, custom_id__c = 'swain'); 
Opportunity newOpportunity4 = new Opportunity(product_line__c = 'Community Solar', name = 'Tester4', stageName = 'Complete', type = 'New Business', closeDate = myDate, CS_Capacity_Allocated__c = 8, custom_id__c = 'swain');


test.startTest(); 
  
insert newOpportunity3;
insert newOpportunity4;
update newOpportunity3;
update newOpportunity4;
   
test.stopTest();

BSST__c salesQuery2 = [SELECT name, individual_commission__c FROM BSST__c WHERE name = 'Cole Swain'];
 

}

Static testMethod void CSCcalculateSalesComm(){

Date myDate = Date.newInstance(2015, 2, 17);

partner__c newpartner3 = new partner__c(name = 'Boston Solar');
insert newPartner3;

BSST__c newBSST3 = new BSST__c(name = 'Cole Swain', partner__c = newPartner3.id, custom_id__c = 'coleswain', a_rate__c = 100, CSA_Threshold__c = 100, b_rate__c= 500, rate_key__c = 5,commission_structure__c ='C');
insert newBSST3; 


partner__c partnerQueryNBS = [SELECT id FROM partner__c WHERE partner__c.name = 'Boston Solar'];
BSST__c salesQueryNBS = [SELECT id FROM BSST__c WHERE BSST__c.name = 'Cole Swain'];


Opportunity newOpportunity5 = new Opportunity(product_line__c = 'Community Solar', name = 'Tester5', stageName = 'Complete', type = 'New Business', closeDate = myDate , CS_Capacity_Allocated__c = 3, custom_id__c ='coleswain' ); 
Opportunity newOpportunity6 = new Opportunity(product_line__c = 'Community Solar', name = 'Tester6', stageName = 'Complete', type = 'New Business', closeDate = myDate, CS_Capacity_Allocated__c = 8, custom_id__c ='coleswain' );

insert newOpportunity5;
insert newOpportunity6;

test.startTest(); 
  
Update newOpportunity5;
Update newOpportunity6;
   
test.stopTest();

BSST__c salesQuery3 = [SELECT name, individual_commission__c FROM BSST__c WHERE name = 'Cole Swain'];
 
*/
return;
}
}