src/objects/BSST__c.object
<CustomObject>
    <fields>
        <fullName>Custom_ID__c</fullName>
        <label>Custom ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Partner__c</fullName>
        <label>Organization</label>
        <referenceTo>Partner__c</referenceTo>
        <relationshipLabel>Sales Team</relationshipLabel>
        <relationshipName>Boston_Solar_Sales_Team</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Sales Team</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Team</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Custom_ID__c</fullName>
        <label>Custom ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Partner_Email__c</fullName>
        <label>Partner Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Partner_Lookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Partner</label>
        <referenceTo>Partner__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>bs_Sales_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Person</label>
        <referenceTo>BSST__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Lead</fullName>
        <active>true</active>
        <businessProcess>CS</businessProcess>
        <label>Lead</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Partner__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <label>Partner</label>
    <nameField>
        <label>Partner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partners</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/PartnerAssignmentHandler.cls
public class PartnerAssignmentHandler {
    private boolean m_isExecuting = false;
    private Integer BatchSize = 0;
    
    public PartnerAssignmentHandler(boolean isExecuting, Integer size){
        m_isExecuting = isExecuting;
        BatchSize = size;
    }
    public void onBeforeInsertOrUpdate(List<Lead> newLeads){
        assignPartnerToLead(newLeads);     
        System.debug('Partner Assignment Begin Execution');  
    }    
    
    public void assignPartnerToLead(List<Lead> leadList){
    	List<String> leadReferralCodeList = new List<String>();
    	List<Id> leadIdList = new List<Id>();

    	Map<String, BSST__c> partnerMap = new Map<String, BSST__c>();
    	for (Lead l : LeadList){
    		if(l.Custom_ID__c != null){
    			leadIdList.add(l.Id);
    		}
    	}
    	if(leadIdList.size()>0){
	    	for(lead l : [SELECT Id, Name, Custom_Id__c, Bs_sales_id__c, Partner_Email__c
	    					FROM Lead
	    					WHERE Id IN : leadIdList]){
	    		leadReferralCodeList.add(l.Custom_Id__c);
	    	}
	    	for (BSST__c partner : [SELECT Id, Name, Custom_Id__c, Partner__r.Id, Email__c 
	    							FROM BSST__c 
	    							WHERE Custom_Id__c IN : leadReferralCodeList]){
	    		partnerMap.put(partner.Custom_Id__c, partner);
	    	}
			System.debug('PartnerMap ' + partnerMap);     	
	    	if(partnerMap.size()>0){
	    		for(lead l : leadList){
	    			l.Partner_Lookup__c = partnerMap.get(l.Custom_Id__c).Partner__r.Id;
	    			l.Bs_sales_id__c = partnerMap.get(l.Custom_Id__c).Id;
	    			l.Partner_Email__c = partnerMap.get(l.Custom_Id__c).Email__c;
	    		}    		
	    	}
    	}
    }
}