src/objects/BSST__c.object
<CustomObject>
    <fields>
        <fullName>Partner__c</fullName>
        <label>Organization</label>
        <referenceTo>Partner__c</referenceTo>
        <relationshipLabel>Sales Team</relationshipLabel>
        <relationshipName>Boston_Solar_Sales_Team</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Sales Team</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Team</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Disbursal__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Disbursal Amount</label>
        <precision>9</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Disbursal_Percentage__c</fullName>
        <label>Disbursal Percentage</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Disbursal_Sequence__c</fullName>
        <label>Disbursal Sequence</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Loan__c</fullName>
        <label>Loan</label>
        <referenceTo>Loan__c</referenceTo>
        <relationshipLabel>Disbursals</relationshipLabel>
        <relationshipName>Disbursals</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Partner__c</fullName>
        <label>Partner</label>
        <referenceTo>Partner__c</referenceTo>
        <relationshipLabel>Disbursals</relationshipLabel>
        <relationshipName>Disbursals</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>This status field marks what stage the disbursal is in the disbursal process. It also marks disbursal as ready for disbursement, which plays a major role in determining which disbursal records show up in the Daily Disbursal reports for BlueWave and Avidia.</description>
        <inlineHelpText>This status field marks what stage the disbursal is in the disbursal process. It also marks disbursal as ready for disbursement, which plays a major role in determining which disbursal records show up in the Daily Disbursal reports for BlueWave and Avidi</inlineHelpText>
        <label>Disbursal Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Ready for Disbursement</fullName>
                </value>
                <value>
                    <fullName>Disbursed</fullName>
                </value>
                <value>
                    <fullName>Hold</fullName>
                </value>
                <value>
                    <fullName>Ready for FBO Funding</fullName>
                </value>
                <value>
                    <fullName>Due</fullName>
                </value>
                <value>
                    <fullName>Reimbursed</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                    <isActive>false</isActive>
                    <label>Complete</label>
                </value>
                <value>
                    <fullName>Not yet disbursed</fullName>
                    <isActive>false</isActive>
                    <label>Not yet disbursed</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Disbursal</label>
    <nameField>
        <label>Disbursal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Disbursals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Loan__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Set by LoanHandler when the Loan&apos;s Lead is converted to an Opportunity</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Loans</relationshipLabel>
        <relationshipName>Loans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Set by LoanHandler when the Loan is created from a Lead</inlineHelpText>
        <label>Partner</label>
        <referenceTo>Partner__c</referenceTo>
        <relationshipLabel>Loans</relationshipLabel>
        <relationshipName>Loans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is a lookup to the Product record assigned to this loan.  The designated Product informs key loan determinants (e.g. interest rate, term, form of promissory note).</description>
        <inlineHelpText>This is a lookup to the Product record assigned to this loan.  The designated Product informs key loan determinants (e.g. interest rate, term, form of promissory note).</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Loans</relationshipLabel>
        <relationshipName>Loans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Agent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Set by LoanHandler when creating the Loan from the Lead</inlineHelpText>
        <label>Sales Agent</label>
        <referenceTo>BSST__c</referenceTo>
        <relationshipLabel>Loans</relationshipLabel>
        <relationshipName>Loans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>System_Costt__c</fullName>
        <inlineHelpText>The request loan amount (could be different than the true system cost)</inlineHelpText>
        <label>XXX System Cost</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Funds_Disbursed__c</fullName>
        <label>Total Funds Disbursed</label>
        <summarizedField>Disbursal__c.Amount__c</summarizedField>
        <summaryFilterItems>
            <field>Disbursal__c.Status__c</field>
            <operation>equals</operation>
            <value>Disbursed</value>
        </summaryFilterItems>
        <summaryForeignKey>Disbursal__c.Loan__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Loan</label>
    <nameField>
        <label>Loan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loans</pluralLabel>
    <recordTypes>
        <fullName>Loan</fullName>
        <active>true</active>
        <label>Loan</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Partner__c.object
<CustomObject>
    <fields>
        <fullName>Total_Funds_Disbursed__c</fullName>
        <description>Sum of funds disbursed to Loan Partner</description>
        <label>Total Funds Disbursed</label>
        <summarizedField>Disbursal__c.Amount__c</summarizedField>
        <summaryFilterItems>
            <field>Disbursal__c.Status__c</field>
            <operation>equals</operation>
            <value>Disbursed</value>
        </summaryFilterItems>
        <summaryForeignKey>Disbursal__c.Partner__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Partner</label>
    <nameField>
        <label>Partner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partners</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Residential_Equipment__c.object
<CustomObject>
    <fields>
        <fullName>CEC_Production_Tracking_System_ID_Number__c</fullName>
        <label>CEC Production Tracking System ID Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Commonwealth_Solar_Rebate_Program__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Has the customer applied for funding through the Commonwealth Solar Rebate Program after 1/1/2010</description>
        <label>Commonwealth Solar Rebate Program</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contract_Execution_Date__c</fullName>
        <label>Contract Execution Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Estimated_On_Site_Behind_the_Meter_Load__c</fullName>
        <label>Estimated On-Site Behind the Meter Load</label>
        <precision>9</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Generator_Energized_Online_Date__c</fullName>
        <label>Generator Energized/Online Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Generator_Installation_Date__c</fullName>
        <label>Generator Installation Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Generator_Interconnection_Date__c</fullName>
        <label>Generator Interconnection Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Generator_Nameplate_Capacity__c</fullName>
        <label>Generator Nameplate Capacity (kW)</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Generator_Type__c</fullName>
        <description>Type of Photovoltaic System installed on the customer&apos;s roof-top</description>
        <label>Generator Type</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Initial_Solar_Meter_Reading_Date__c</fullName>
        <label>Initial Solar Meter Reading Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Initial_Solar_Meter_Reading__c</fullName>
        <label>Initial Solar Meter Reading</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Interconnected__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Interconnected</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Interconnection_Date__c</fullName>
        <label>Interconnection Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Inverter_Manufacturer__c</fullName>
        <label>Inverter Manufacturer</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Inverter_Model_Number__c</fullName>
        <label>Inverter Model Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Loan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Loan</label>
        <referenceTo>Loan__c</referenceTo>
        <relationshipLabel>Residential Equipment</relationshipLabel>
        <relationshipName>Residential_Equipment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MA_Facility_Sector__c</fullName>
        <label>MA Facility Sector</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Commercial</fullName>
                </value>
                <value>
                    <fullName>Government</fullName>
                </value>
                <value>
                    <fullName>Residential</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MA_Facility_Type__c</fullName>
        <label>MA Facility Type</label>
        <length>75</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mechanical_Installation_Date__c</fullName>
        <label>Mechanical Installation Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Mechanically_Installed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Mechanically Installed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Module_Array_Azimuth__c</fullName>
        <label>Module Array Azimuth</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Module_Array_Mounting_Type__c</fullName>
        <label>Module Array Mounting Type</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Module_Array_Tilt__c</fullName>
        <label>Module Array Tilt</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Module_Manufacturer__c</fullName>
        <label>Module Manufacturer</label>
        <length>45</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Residential Equipment</relationshipLabel>
        <relationshipName>Residential_Equipment</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Residential Equipment</label>
    <nameField>
        <label>Residential E Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Residential Equipment</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/User/fields/Partner_ID__c.field-meta.xml
<CustomField>
    <fullName>Partner_ID__c</fullName>
    <formula>Contact.Partner_Lookup__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Partner ID</label>
    <type>Text</type>
</CustomField>

src/classes/SLPCustomerPageHandler.cls
public class SLPCustomerPageHandler {                                     

    @AuraEnabled
    public static List<Loan__c> getLoanCustomers() {
        User u = [SELECT Id, Partner_ID__c FROM User WHERE Id = :UserInfo.getUserId()];
        List<Loan__c> loanList = [SELECT Id, Name, Sales_Agent__r.Name, Product__r.ProductCode, System_Costt__c, 
                         Total_Funds_Disbursed__c, Opportunity__r.StageName, Status__c
                                  FROM Loan__c WHERE Partner__c = : u.Partner_ID__c];
        return loanList;
    }
   
   @AuraEnabled
    public static List<Loan__c> getLoanCustomerWindow(String loanId) {
        User u = [SELECT Id, Partner_ID__c FROM User WHERE Id = :UserInfo.getUserId()];
        List<Loan__c> loanList = [SELECT Id, Name, Sales_Agent__r.Name, Product__r.ProductCode, System_Costt__c, 
                         Total_Funds_Disbursed__c, Opportunity__r.StageName, Status__c
                                  FROM Loan__c WHERE Id = : loanId];
    System.debug('Loan List is ' + loanList);                                  
        return loanList;
    }
   
   @AuraEnabled
    public static List<Task> getLoanCustomerTasks(String loanId) {
        User u = [SELECT Id, Partner_ID__c FROM User WHERE Id = :UserInfo.getUserId()];
        List<Task> taskList = [SELECT Id, Subject, Actual_Complete_Date__c, Status, Loan__r.Id, Loan__c, Loan_Partner_Sequence__c
                                  FROM Task WHERE Loan__c = : loanId 
                                  ORDER BY Loan_Partner_Sequence__c ASC];                               
        return taskList;
    }

   @AuraEnabled
    public static String getLoanCustomerCompletedTasks(String loanId) {
        User u = [SELECT Id, Partner_ID__c FROM User WHERE Id = :UserInfo.getUserId()];
        List<Task> completedTaskList = [SELECT Id, Subject, Actual_Complete_Date__c, Status, Loan__r.Id, Loan__c
                                  FROM Task WHERE Loan__c = : loanId 
                                  AND Status = 'Completed' 
                                  ORDER BY Actual_Complete_Date__c, Loan_Partner_Sequence__c DESC];  
    System.debug('The subject is ' + completedTaskList.get(0).Subject);                                                               
        return completedTaskList.get(0).Subject;
    } 
   
   @AuraEnabled
    public static List<Disbursal__c> getLoanDisbursals(String loanId) {
        User u = [SELECT Id, Partner_ID__c FROM User WHERE Id = :UserInfo.getUserId()];
        List<Disbursal__c> disbursalList = [SELECT Id, Disbursal_Percentage__c, Status__c, Amount__c, Type__c 
                                  FROM Disbursal__c WHERE Loan__c = : loanId 
                                  ORDER BY Disbursal_Sequence__c ASC];                               
        return disbursalList;
    }
   @AuraEnabled
    public static List<Residential_Equipment__c> getResidentialEquipment(String loanId) {
        User u = [SELECT Id, Partner_ID__c FROM User WHERE Id = :UserInfo.getUserId()];
        List<Residential_Equipment__c> relList = [SELECT Id, Name, CEC_Production_Tracking_System_ID_Number__c, Commonwealth_Solar_Rebate_Program__c,
                                    Contract_Execution_Date__c, Estimated_On_Site_Behind_the_Meter_Load__c, Generator_Energized_Online_Date__c,
                                    Generator_Installation_Date__c, Generator_Interconnection_Date__c, Generator_Nameplate_Capacity__c, 
                                    Generator_Type__c, Initial_Solar_Meter_Reading__c, Initial_Solar_Meter_Reading_Date__c, Interconnected__c,
                                    Interconnection_Date__c, Inverter_Manufacturer__c, Inverter_Model_Number__c, MA_Facility_Sector__c, MA_Facility_Type__c,
                                    Mechanical_Installation_Date__c, Mechanically_Installed__c,  Module_Array_Azimuth__c, Module_Array_Mounting_Type__c, Module_Array_Tilt__c,
                                    Module_Manufacturer__c, Module_Model_Number__c, Module_Mounting_Location__c, Module_Power_Rating__c,
                                    Number_of_Inverters__c, Number_of_Meters__c, Number_of_Modules__c, Percentage_of_System_Shaded__c, 
                                    PowerClerk_Application_ID__c, Remote_Monitorin_Systegm_Identifier__c, Remote_Monitoring_System_Vendor__c,
                                    Solar_Meter_Manufacturer__c,Solar_Meter_Model__c, Solar_Meter_Serial_Number__c, SREC_Opt_In_Calendar_Quarter__c, 
									Type_of_Module__c, Utility_Company__c        
                                  FROM Residential_Equipment__c WHERE Loan__c = : loanId];                               
        return relList;
    }    

}