src/objects/Case.object
<CustomObject>
    <recordTypes>
        <fullName>Case</fullName>
        <active>true</active>
        <businessProcess>Customer Care Case</businessProcess>
        <label>Case</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/LASERCA__Personal_Credit_Report__c.object
<CustomObject>
    <description>Experian Personal Credit Report, direct connect to Experian</description>
    <fields>
        <fullName>LASERCA__Credit_Score__c</fullName>
        <label>Credit Score</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <label>Personal Credit Report</label>
    <nameField>
        <label>Personal Credit Report Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Personal Credit Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Application_Complete_Date__c</fullName>
        <description>Date Flow application is completed.</description>
        <inlineHelpText>Date Flow application is completed.</inlineHelpText>
        <label>Application Complete Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Application_Status__c</fullName>
        <inlineHelpText>Where the potential customer is in the application process</inlineHelpText>
        <label>Internal Application Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Started</fullName>
                    <default>true</default>
                    <label>Started</label>
                </value>
                <value>
                    <fullName>Customer Info Completed</fullName>
                </value>
                <value>
                    <fullName>Contracts Signed</fullName>
                </value>
                <value>
                    <fullName>Application Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>No_Payment__c</fullName>
        <defaultValue>false</defaultValue>
        <description>W-019782</description>
        <inlineHelpText>Default unchecked; checked if the likely-assigned SSS does not require payment information (e.g. UCB product). If checked, this lead CANNOT be put on a SSS that requires capture of payment info.</inlineHelpText>
        <label>Not Requesting Payment Info</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Partner_Email__c</fullName>
        <label>Partner Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Personal_Credit_Report__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Personal Credit Report</label>
        <referenceTo>LASERCA__Personal_Credit_Report__c</referenceTo>
        <relationshipLabel>Leads (Personal Credit Report)</relationshipLabel>
        <relationshipName>Leads1</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Lead</fullName>
        <active>true</active>
        <businessProcess>CS</businessProcess>
        <label>Lead</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/System_Default__mdt.object
<CustomObject>
    <description>Used to default values in Apex/Flows to avoid hardcoding values</description>
    <fields>
        <fullName>Application_Complete_Email_Template__c</fullName>
        <description>Email Template DeveloperName for email sent to Partners after SSF has been completed</description>
        <label>Application Complete Email Template</label>
        <length>130</length>
        <type>Text</type>
    </fields>
    <label>System Default</label>
    <pluralLabel>System Defaults</pluralLabel>
</CustomObject>

src/classes/CSApplicationFinisher.cls
/**
 * Created by jeffparlin on 6/28/21.
 * @description Processes CS Leads which have entered an 'Application Complete' state, called from varying contexts
 * Tested By: CSLeadsRESTControllerV2Test
 */
public without sharing class CSApplicationFinisher {

    @TestVisible private static LeadSelector leadSelector = new LeadSelector();
    @TestVisible private static FeatureSelector featureSelector = new FeatureSelector();
    @TestVisible private static CSQualificationService qualificationService = new CSQualificationService();
    @TestVisible private static LeadService leadService = new LeadService();

    /**
     * @description Performs required actions when a CS Lead is marked as "complete" by SSF or API
     * Runs in async @future context.
     * @param leadId CS Lead record to process
     * @param setApplicationCompleteDate Set application complete date on Lead via Apex when called?
     */
    @Future
    public static void execute(Id leadId, Boolean setApplicationCompleteDate) {
        // Locate lead
        Lead lead = leadSelector.selectOne(leadId);
        if (lead == null) {
            String message = 'Unable to process CS lead application complete steps. Reprocess manually. Inputs:\nleadId: '
                + leadId + '\nsetApplicationCompleteDate: ' + setApplicationCompleteDate;
            Logger.logNow('CSApplicationFinisher', 'execute', message, Logger.ERROR);
            return;
        }

        // Perform actions on CS Lead application complete
        updateLeadOnComplete(lead, setApplicationCompleteDate);
        createAndSendCSPartnerEmail(lead);
        createQCCaseForNoMatchPCR(lead);
        UtilityDataRequestBuilder.createUDRs(new List<Id>{lead.Id});
        if (lead.No_Payment__c == false) {
            ZuoraAccountService.createAccounts(new Set<Id>{lead.Id});
        }
    }

    private static void updateLeadOnComplete(Lead lead, Boolean setApplicationCompleteDate) {
        if (setApplicationCompleteDate) {
            lead.Application_Complete_Date__c = Datetime.now();
        }
        lead.Application_Status__c = 'Application Completed';
        try {
            CSLeadsRESTControllerV2.setContinueApplicationLinks(lead, 'Application Completed');
            qualificationService.qualifyLead(lead);
            leadService.updateLead(lead);
        } catch (Exception e) {
            String message = 'Failed to update lead on application complete.\n\n' + e.getMessage() + '\n\n' + e.getStackTraceString();
            Logger.logNow('CSApplicationFinisher', 'updateLeadOnComplete', message, Logger.ERROR);
        }
    }

    /**
     * @description Method to send an email to the related Partner when the customer has completed their SSF
     * Application
     * @param Lead Lead that has completed the application
     */
    @TestVisible
    private static void createAndSendCSPartnerEmail(Lead lead) {
        System_Default__mdt systemDefault = featureSelector.getSystemDefaults();
        if (systemDefault.Application_Complete_Email_Template__c == null || lead?.Partner_Email__c == null) {
            Logger.logNow('CSLeadsService', 'createAndSendCSPartnerEmail',
                'Email was not sent to Partner for lead: ' + lead.Id + '; First confirm ' +
                    'that there is an email template found in System Default custom metadata. ' +
                    'Then confirm the lead is populated with a Partner Email.', Logger.WARN);
            return;
        }
        EmailTemplate template = MessagingService.getHtml(systemDefault.Application_Complete_Email_Template__c);
        String templateHtml = template.HtmlValue;
        templateHtml = templateHtml.replace('{{{Recipient.Name}}}', lead.Name);
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        mail.setOrgWideEmailAddressId(MessagingService.getCustomerCareEmail().Id);
        mail.setSubject('Application Completed for ' + lead.Name);
        mail.setHtmlBody(templateHtml);
        mail.setToAddresses(new List<String>{lead.Partner_Email__c});
        mail.setTargetObjectId(lead.Id);
        mail.setSaveAsActivity(true);
        mail.setTreatTargetObjectAsRecipient(false);

        try {
            MessagingService.sendEmail(new List<Messaging.SingleEmailMessage>{mail});
        } catch (Exception e) {
            Logger.logNow('CSApplicationFinisher', 'createAndSendCSPartnerEmail', e.getMessage() +
                '; ' + e.getStackTraceString());
        }
    }

    /**
    * When application is completed, if PCR is still a "No Match," we create a QC Case
    * @param lead lead that has completed the SSF Application
    */
    @TestVisible
    private static void createQCCaseForNoMatchPCR(Lead lead) {
        if (lead.Personal_Credit_Report__r.LASERCA__Credit_Score__c == '9999') {
            CaseFactory noMatchFactory  = new CaseFactory();
            noMatchFactory.setLead(lead);
            noMatchFactory.setQueueType('No FICO Match');
            System.enqueueJob(noMatchFactory);
        }
    }
}