src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Product_Line__c</fullName>
        <label>Product Line</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Community Solar</fullName>
                </value>
                <value>
                    <fullName>Solar Loan</fullName>
                </value>
                <value>
                    <fullName>None</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Shared_Solar_System__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Shared Solar System</label>
        <referenceTo>Shared_Solar_System__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Case</fullName>
        <active>true</active>
        <businessProcess>Customer Care Case</businessProcess>
        <label>Case</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Financial_Underwriting_Document__c.object
<CustomObject>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>A lookup to Lead</description>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipName>Underwrite_Financial_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Financial Underwriting Document</label>
    <nameField>
        <displayFormat>FD-{0000}</displayFormat>
        <label>Financial Underwriting Document Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Underwriting Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LASERCA__Credit_Report_Log__c.object
<CustomObject>
    <fields>
        <fullName>LASERCA__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Credit Report Logs</relationshipLabel>
        <relationshipName>Credit_Report_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LASERCA__Home_Address__c</fullName>
        <label>Home Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LASERCA__Home_City__c</fullName>
        <label>Home City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LASERCA__Home_State__c</fullName>
        <label>Home State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LASERCA__Home_Zip__c</fullName>
        <label>Home Zip</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LASERCA__Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Credit Report Logs</relationshipLabel>
        <relationshipName>Credit_Report_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LASERCA__Personal_Credit_Report__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Personal Credit Report</label>
        <referenceTo>LASERCA__Personal_Credit_Report__c</referenceTo>
        <relationshipLabel>Credit Report Logs</relationshipLabel>
        <relationshipName>Credit_Report_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LASERCA__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Credit Report Log</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Credit Report Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Report Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LASERCA__Personal_Credit_Report__c.object
<CustomObject>
    <description>Experian Personal Credit Report, direct connect to Experian</description>
    <fields>
        <fullName>LASERCA__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Guarantors&apos; credit to be run
If this holds a value, DTI is calculated off Coapplicant Income</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Personal Credit Report</relationshipLabel>
        <relationshipName>Personal_Credit_Reports</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LASERCA__Credit_Score_TransUnion__c</fullName>
        <label>Credit Score (TransUnion)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LASERCA__Credit_Score__c</fullName>
        <label>Credit Score</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LASERCA__Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Personal Credit Reports</relationshipLabel>
        <relationshipName>Personal_Credit_Reports</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LASERCA__Sum_of_monthly_Personal_Debt__c</fullName>
        <label>Sum of Monthly Personal Debt</label>
        <summarizedField>LASERCA__Trade_Accounts__c.LASERCA__Monthly_Payment__c</summarizedField>
        <summaryForeignKey>LASERCA__Trade_Accounts__c.LASERCA__Personal_Credit_Report__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Personal Credit Report</label>
    <nameField>
        <label>Personal Credit Report Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Personal Credit Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Electricity_Provider__c</fullName>
        <label>Utility from application</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LASERCA__Home_Address__c</fullName>
        <label>Home Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LASERCA__Home_City__c</fullName>
        <label>Home City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LASERCA__Home_State__c</fullName>
        <label>Home State</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LASERCA__Home_Zip__c</fullName>
        <label>Home Zip</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LoadZone__c</fullName>
        <inlineHelpText>Text Field (ex. SEMA, NEMA) If in a split load zone, this field will be populated with both until resolved (SEMA/NEMA)</inlineHelpText>
        <label>Load Zone</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Load_Zone_Utility__c</fullName>
        <formula>Zip_Code_Lookup_Field__r.Load_Zone__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>XXXXX Load Zone Utility</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Partner_Lookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Partner</label>
        <referenceTo>Partner__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Partner_Name__c</fullName>
        <formula>Partner_Lookup__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Partner Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Personal_Credit_Report__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Personal Credit Report</label>
        <referenceTo>LASERCA__Personal_Credit_Report__c</referenceTo>
        <relationshipLabel>Leads (Personal Credit Report)</relationshipLabel>
        <relationshipName>Leads1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Product lookup, for loans, set by an installer upon sending a new application or set by code after a credit check has determined qualifying products.</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_line__c</fullName>
        <label>Product Line</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Utility__c</fullName>
        <formula>IF(INCLUDES(  Utility_1__c , &quot;Eversource&quot;), &quot;Eversource&quot;, 
IF(INCLUDES(  Utility_1__c , &quot;National Grid&quot;), &quot;National Grid&quot;,
IF(INCLUDES(  Utility_1__c , &quot;Unitil&quot;), &quot;Unitil&quot;,
IF(INCLUDES(  Utility_1__c , &quot;Municipal Electric Department&quot;), &quot;Municipal Electric Department&quot;,
IF(INCLUDES(  Utility_1__c , &quot;Duke Energy&quot;), &quot;Duke Energy&quot;, 
IF(INCLUDES(  Utility_1__c , &quot;SCE&amp;G&quot;), &quot;SCE&amp;G&quot;, 
 &quot;Other&quot;))))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>XXXXX Utility</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Utility_relationship__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Utility</label>
        <referenceTo>Utility__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Lead</fullName>
        <active>true</active>
        <businessProcess>CS</businessProcess>
        <label>Lead</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Load_U__c.object
<CustomObject>
    <description>General list of Massachusetts Zip Codes and their corresponding Load Zones and Utiliy providers.</description>
    <fields>
        <fullName>Utility__c</fullName>
        <label>XXXX Utility</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <label>Load Zone &amp; Utility</label>
    <nameField>
        <label>Zip Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Load Zones &amp; Utilities</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Shared_Solar_System__c.object
<CustomObject
     >
    <articleTypeChannelDisplay n1:nil="true" />
    <customSettingsType n1:nil="true" />
    <description n1:nil="true" />
    <eventType n1:nil="true" />
    <fields>
        <fullName>Capacity_Available_to_be_Reserved__c</fullName>
        <formula>Total_CS_Capacity_kW_DC_Formula__c - (Pending_Small_CS_Capacity__c + Capacity_Committed_kW_DC__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Small CS Capacity not yet committed or pending; Result of Reserved Small CS Capacity - (Committed and Pending Small CS Capacity)</inlineHelpText>
        <label>Available Small CS Capacity</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Credit_Score_Requirement__c</fullName>
        <defaultValue>700</defaultValue>
        <inlineHelpText>Minimum accepted customer FICO score.</inlineHelpText>
        <label>Credit Score Requirement</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Open__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Open</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Primary customer product.</inlineHelpText>
        <label>Default Enrollment Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Shared Solar Systems</relationshipLabel>
        <relationshipName>Shared_Solar_Systems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Public__c</fullName>
        <defaultValue>false</defaultValue>
        <label>XXXPublic</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Service_Territories__c</fullName>
        <label>Service Territories</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Service_Territories</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Utility__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Utility</label>
        <referenceTo>Utility__c</referenceTo>
        <relationshipLabel>Shared Solar Systems</relationshipLabel>
        <relationshipName>Shared_Solar_Systems</relationshipName>
        <type>Lookup</type>
    </fields>
    <gender n1:nil="true" />
    <household>false</household>
    <label>Shared Solar System</label>
    <nameField>
        <label>Shared Solar System Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shared Solar Systems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <startsWith n1:nil="true" />
</CustomObject>

src/objects/ZipCode_Utility_Junction__c.object
<CustomObject>
    <fields>
        <fullName>Utility__c</fullName>
        <label>Utility</label>
        <referenceTo>Utility__c</referenceTo>
        <relationshipLabel>ZipCode Utility Junctions</relationshipLabel>
        <relationshipName>ZipCode_Utility_Junctions</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>ZipCode Utility Junction</label>
    <nameField>
        <displayFormat>ZUJ-{00000}</displayFormat>
        <label>ZipCode Utility Junction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ZipCode Utility Junctions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/Service_Territories.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>NEMA</fullName>
    </customValue>
    <customValue>
        <fullName>SEMA</fullName>
    </customValue>
    <customValue>
        <fullName>WCMA</fullName>
    </customValue>
    <customValue>
        <fullName>MN</fullName>
    </customValue>
    <customValue>
        <fullName>Capital</fullName>
    </customValue>
    <customValue>
        <fullName>Hudson Valley</fullName>
    </customValue>
    <customValue>
        <fullName>Mohawk Valley</fullName>
    </customValue>
    <customValue>
        <fullName>Central</fullName>
    </customValue>
    <customValue>
        <fullName>Genesee</fullName>
    </customValue>
    <customValue>
        <fullName>Dunwoodie</fullName>
    </customValue>
    <customValue>
        <fullName>N.Y.C.</fullName>
    </customValue>
    <customValue>
        <fullName>Millwood</fullName>
    </customValue>
    <customValue>
        <fullName>Long Island</fullName>
    </customValue>
    <customValue>
        <fullName>North</fullName>
    </customValue>
    <customValue>
        <fullName>West</fullName>
    </customValue>
    <customValue>
        <fullName>Maine</fullName>
    </customValue>
    <customValue>
        <fullName>Maine Public Service</fullName>
    </customValue>
    <customValue>
        <fullName>Bangor Hydro</fullName>
    </customValue>
    <masterLabel>Service Territories</masterLabel>
</GlobalValueSet>

src/classes/CSQualificationService.cls
/**
 * Created by SarahRenfro on 5/22/2019.
 *
 * Test: CSQualificationTestclass
 */

@SuppressWarnings('PMD.ApexCRUDViolation')
public without sharing class CSQualificationService {

    public static void underwriteWithFICO(
        Map<Id, LASERCA__Credit_Report_Log__c> triggerNewMap,
        Map<Id, LASERCA__Credit_Report_Log__c> triggerOldMap) {
        Set<Id> pcrIds = new Set<Id>();
        if (triggerOldMap == null) {
            for (LASERCA__Credit_Report_Log__c crl : triggerNewMap.values()) {
                if (crl.LASERCA__Status__c == 'Completed' || (crl.LASERCA__Status__c == 'Error' && crl.LASERCA__Personal_Credit_Report__c != null)) {
                    pcrIds.add(crl.LASERCA__Personal_Credit_Report__c);
                }
            }
        } else {
            for (Id oldId : triggerOldMap.keySet()) {
                if (triggerNewMap.get(oldId).LASERCA__Status__c == 'Completed' &&
                    triggerOldMap.get(oldId).LASERCA__Status__c != 'Completed') {
                    pcrIds.add(triggerNewMap.get(oldId).LASERCA__Personal_Credit_Report__c);
                }
            }
        }

        List<LASERCA__Personal_Credit_Report__c> completedPCRs = [
            SELECT Id, LASERCA__Lead__c, LASERCA__Lead__r.Personal_Credit_Report__c, Approval_Status__c,
                LASERCA__Contact__c, LASERCA__Sum_of_monthly_Personal_Debt__c, Lead_from_Contact__c,
                Maximum_Disbursement_Monthly__c, LASERCA__Credit_Score__c, LASERCA__Credit_Score_TransUnion__c
            FROM LASERCA__Personal_Credit_Report__c
            WHERE Id = :pcrIds
        ];

        List<String> leadIds = new List<String>();
        for (LASERCA__Personal_Credit_Report__c pcr : completedPCRs) {
            if (pcr.LASERCA__Lead__c != null) {
                leadIds.add(pcr.LASERCA__Lead__c);
            }
        }

        if (leadIds.isEmpty()) {
            return;
        }

        Map<Id, Lead> leadMap = getLeadMap(leadIds);

        if (leadMap.isEmpty()) {
            return;
        }

        //Query for all the Shared Solar Systems
        List<Shared_Solar_System__c> sharedSolarSystems = getSharedSolarSystems();

        List<Lead> updateLeads = new List<Lead>();
        List<LASERCA__Personal_Credit_Report__c> updatePCRs = new List<LASERCA__Personal_Credit_Report__c>();
        for (LASERCA__Personal_Credit_Report__c pcr : completedPCRs) {
            Lead lead = leadMap.get(pcr.LASERCA__Lead__c);
            Decimal creditScore = 0;

            //Handle No Match Leads and set credit score to 9999
            if (pcr.LASERCA__Credit_Score__c != null) {
                creditScore = Decimal.valueOf(pcr.LASERCA__Credit_Score__c);
                closeReportMissingCases(lead);
            } else {
                pcr.LASERCA__Credit_Score_TransUnion__c = '9999';
                pcr.LASERCA__Credit_Score__c = '9999';
                creditScore = 9999;
                updatePCRs.add(pcr);
                CaseFactory noMatchFactory  = new CaseFactory();
                noMatchFactory.setLead(lead);
                System.enqueueJob(noMatchFactory);
            }


            //Check if lead is qualified
            lead.Status = checkCSQualification(lead, sharedSolarSystems, creditScore);
            updateLeads.add(lead);

        }

        update updatePCRs;
        update updateLeads;
    }

    public String underwriteWithFinancialReview(Lead lead) {
        if (lead == null) {
            return null;
        }

        Set<Id> financialUnderwritingIds = new Set<Id>();
        if (lead.Underwrite_Financial_Documents__r != null) {
            for (Financial_Underwriting_Document__c fud : lead.Underwrite_Financial_Documents__r) {
                financialUnderwritingIds.add(fud.Id);
            }
        }

        List<ContentDocumentLink> contentDocLinks = new List<ContentDocumentLink>();
        if (!financialUnderwritingIds.isEmpty()) {
            contentDocLinks = [SELECT Id, LinkedEntityId FROM ContentDocumentLink WHERE LinkedEntityId = :financialUnderwritingIds];
        }
        List<Shared_Solar_System__c> sharedSolarSystems = getSharedSolarSystems();

        String result = 'Unqualified';
        if (!contentDocLinks.isEmpty()) {
            result = CSQualificationService.checkCSQualification(lead, sharedSolarSystems, null);
        }
        return result;
    }

    private static String checkCSQualification(Lead lead, List<Shared_Solar_System__c> sharedSolarSystems, Decimal creditScore) {
        for (Shared_Solar_System__c sss : sharedSolarSystems) {
            if (sss.Utility__c == lead.Utility_relationship__c &&
                (sss.Service_Territories__c != null && sss.Service_Territories__c.contains(lead.LoadZone__c)) &&
                ((sss.Sales_Partners__c != null &&
                    (sss.Sales_Partners__c.contains('All') || sss.Sales_Partners__c.contains(lead.Partner_Lookup__r.Name))) ||
                    sss.Public__c == true) &&
                sss.Product__c == lead.Product__c &&
                (creditScore == null || creditScore > sss.Credit_Score_Requirement__c)
                ) {
                return 'Qualified';
            }
        }

        return 'Unqualified';
    }

    private static Map<Id, Lead> getLeadMap(List<Id> leadIds) {
        return new Map<Id, Lead>(
        [
            SELECT Id, Utility_relationship__r.Id, Utility_relationship__r.Name, Utility_relationship__c, LoadZone__c, Partner_Name__c, Status,
                Company, Product_line__c, Electricity_Provider__c, LASERCA__Home_Address__c, LASERCA__Home_City__c,
                LASERCA__Home_State__c, LASERCA__Home_Zip__c, OwnerId, Product__c, Partner_Lookup__r.Name
            FROM Lead
            WHERE Id IN :leadIds
            AND Product_line__c = 'Community Solar'
        ]);
    }

    private static List<Shared_Solar_System__c> getSharedSolarSystems() {
        return [
            SELECT Id, Credit_Score_Requirement__c, Product__r.Id, Product__c, Public__c, Utility__c, Service_Territories__c,
                Sales_Partners__c
            FROM Shared_Solar_System__c
            WHERE Open__c = true
            AND Capacity_Available_to_be_Reserved__c > 0
            ORDER BY Credit_Score_Requirement__c ASC
        ];
    }


    public virtual class QualificationMatch {
        @AuraEnabled
        public Shared_Solar_System__c sss;
        @AuraEnabled
        public Boolean completeMatch = false;
        @AuraEnabled
        public Boolean isOpen = false;
        @AuraEnabled
        public Boolean hasCapacity = false;
        @AuraEnabled
        public Boolean hasLZ = false;
        @AuraEnabled
        public Boolean hasPartner = false;
        @AuraEnabled
        public Boolean minFICO = false;
    }

    public class QualificationInput {
        public List<QualificationMatch> qualificationMatches = new List<QualificationMatch>();
        private List<Id> utilityIds = new List<Id>();
        private String loadZone;
        private Id productId;
        private String partner;
        private Integer fico;
        private Partner__c partnerSobj;

        public QualificationInput(String product, String partner, String zipCode, String fico, String utility) {
            this.productId = (Id) product;

            partnerSobj = PartnerSelector.selectPartnerByPartnerId(partner);
            this.partner = partnerSobj.Name;

            if (fico != null) {
                this.fico = Integer.valueOf(fico);
            }

            List<ZipCode_Utility_Junction__c> zipCodeUtilityJunctions = ZipcodeUtilitiesSelector.selectZipcodeUtilitiesAndLoadzones(zipCode);
            this.loadZone = zipCodeUtilityJunctions[0].Load_Zone_Utility__r.LZ__c;

            if (utility == null) {
                for (ZipCode_Utility_Junction__c junction : zipCodeUtilityJunctions) {
                    this.utilityIds.add(junction.Utility__c);
                }
            } else {
                this.utilityIds.add(utility);
            }
        }

        public void createQualificationList() {
            SharedSolarSystemsSelector sssSelector = new SharedSolarSystemsSelector();
            List<Shared_Solar_System__c> sssList = sssSelector.selectSharedSolarSystemsForQualificationCheck(this.productId, this.utilityIds);

            for (Shared_Solar_System__c sss : sssList) {
                QualificationMatch matchResult = new QualificationMatch();
                matchResult.sss = sss;
                if (sss.Open__c) {
                    matchResult.isOpen = true;
                }
                if (sss.Capacity_Available_to_be_Reserved__c > 0) {
                    matchResult.hasCapacity = true;

                }
                if (sss.Service_Territories__c != null && sss.Service_Territories__c.contains(this.loadZone)) {
                    matchResult.hasLZ = true;
                }
                if (sss.Sales_Partners__c != null && (sss.Sales_Partners__c.contains('All') || sss.Sales_Partners__c.contains(this.partner))) {
                    matchResult.hasPartner = true;
                }
                if (this.fico == null || this.fico >= sss.Credit_Score_Requirement__c) {
                    matchResult.minFICO = true;
                }
                if (matchResult.isOpen &&
                    matchResult.hasCapacity &&
                    matchResult.hasLZ &&
                    matchResult.hasPartner &&
                    matchResult.minFICO
                    ) {
                    matchResult.completeMatch = true;
                }

                this.qualificationMatches.add(matchResult);
            }
        }
    }

    @SuppressWarnings('PMD.ExcessiveParameterList')
    @AuraEnabled
    public static List<QualificationMatch> getQualificationMatches(String product, String partner, String zipCode,
        String fico, String utility) {
        QualificationInput input = new QualificationInput(product, partner, zipCode, fico, utility);
        input.createQualificationList();
        return input.qualificationMatches;
    }

    public static void closeReportMissingCases(Lead lead) {
        List<Case> cases = new CaseSelector().selectOpenNoMatchCasesFromLead(lead);
        if (cases.size() > 0) {
            for (Case c : cases) {
                c.Status = 'Closed';
            }
            update cases;
        }
    }
}