src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Shared_Solar_System__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Shared Solar System</label>
        <referenceTo>Shared_Solar_System__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Case</fullName>
        <active>true</active>
        <businessProcess>Customer Care Case</businessProcess>
        <label>Case</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Production__c.object
<CustomObject>
    <fields>
        <fullName>Credits_Generated__c</fullName>
        <label>Credits Generated</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Production_kWh__c</fullName>
        <label>Production (kWh)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Shared_Solar_System__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Shared Solar System</label>
        <referenceTo>Shared_Solar_System__c</referenceTo>
        <relationshipLabel>Production</relationshipLabel>
        <relationshipName>Production</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Production</label>
    <nameField>
        <label>Production Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Production</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Schedule_Z__c.object
<CustomObject>
    <fields>
        <fullName>Date_Enacted_by_Utility__c</fullName>
        <inlineHelpText>Stamped by status change</inlineHelpText>
        <label>Date Enacted by Utility</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Shared_Solar_System__c</fullName>
        <label>Shared Solar System</label>
        <referenceTo>Shared_Solar_System__c</referenceTo>
        <relationshipName>Schedule_Zs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Must be updated via the &quot;Update Status &amp; Date&quot; button</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>QC in Process</fullName>
                    <default>true</default>
                    <label>QC in Process</label>
                </value>
                <value>
                    <fullName>QC Complete</fullName>
                </value>
                <value>
                    <fullName>Rejected Internal</fullName>
                </value>
                <value>
                    <fullName>Submitted to Asset Owner</fullName>
                </value>
                <value>
                    <fullName>Executed by Asset Owner</fullName>
                </value>
                <value>
                    <fullName>Submitted to Utility</fullName>
                </value>
                <value>
                    <fullName>Rejected by Utility</fullName>
                </value>
                <value>
                    <fullName>Enacted by Utility</fullName>
                </value>
                <value>
                    <fullName>Billing</fullName>
                </value>
                <value>
                    <fullName>Replaced</fullName>
                </value>
                <value>
                    <fullName>Executed by Asset Owner (old version)</fullName>
                    <isActive>false</isActive>
                    <label>Executed by Asset Owner &gt;&gt;&gt; Submit to Utility</label>
                </value>
                <value>
                    <fullName>Front Page QC Completed &gt;&gt;&gt; Submit to Asset Owner</fullName>
                    <isActive>false</isActive>
                    <label>Front Page QC Completed &gt;&gt;&gt; Submit to Asset Owner</label>
                </value>
                <value>
                    <fullName>New</fullName>
                    <isActive>false</isActive>
                    <label>New &gt;&gt;&gt; Complete Subscription QC</label>
                </value>
                <value>
                    <fullName>Rejected by Utility (old version)</fullName>
                    <isActive>false</isActive>
                    <label>Rejected</label>
                </value>
                <value>
                    <fullName>Replaced with newly Enacted Schedule Z</fullName>
                    <isActive>false</isActive>
                    <label>Replaced with newly Enacted Schedule Z</label>
                </value>
                <value>
                    <fullName>Submitted to Asset Owner &gt;&gt;&gt; Contact Asset Owner to get it Executed</fullName>
                    <isActive>false</isActive>
                    <label>Submitted to Asset Owner &gt;&gt;&gt; Contact Asset Owner to get it Executed</label>
                </value>
                <value>
                    <fullName>Submitted to Utility (old version)</fullName>
                    <isActive>false</isActive>
                    <label>Submitted to Utility &gt;&gt;&gt; Contact Utility to get it Enacted</label>
                </value>
                <value>
                    <fullName>QC Complete (old version)</fullName>
                    <isActive>false</isActive>
                    <label>Subscription QC Completed &gt;&gt;&gt; Complete Front Page QC</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Utility__c</fullName>
        <formula>Shared_Solar_System__r.Utility__r.Name</formula>
        <label>Utility</label>
        <type>Text</type>
    </fields>
    <label>Allocation Schedule</label>
    <nameField>
        <label>Allocation Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Allocation Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Service_Territory__c.object
<CustomObject>
    <fields>
        <fullName>Service_Territory__c</fullName>
        <label>Service Territory</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Service Territory</label>
    <nameField>
        <label>Zip Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Territories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Shared_Solar_System__c.object
<CustomObject
     >
    <articleTypeChannelDisplay n1:nil="true" />
    <customSettingsType n1:nil="true" />
    <description n1:nil="true" />
    <eventType n1:nil="true" />
    <fields>
        <fullName>Assemblage_Count__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Assemblage Count</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Assignment_Order__c</fullName>
        <label>Assignment Order</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Capacity_Committed_kW_DC__c</fullName>
        <inlineHelpText>Sum of Complete Small CS Subscriptions</inlineHelpText>
        <label>Committed Small CS Capacity</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Credit_Score_Requirement__c</fullName>
        <defaultValue>700</defaultValue>
        <inlineHelpText>Minimum accepted customer FICO score.</inlineHelpText>
        <label>Credit Score Requirement</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Expected_Yield_kWh_kW__c</fullName>
        <inlineHelpText>How much energy (kWh) is produced for every kW of project capacity. If yield increases, every kW of the project will produce more energy, and need more CS offtakers to use that capacity</inlineHelpText>
        <label>Expected Yield (kWh/kW)</label>
        <precision>12</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Open__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Open</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Reserved_Capacity_kW_DC__c</fullName>
        <inlineHelpText>Sum of New, Pending, or QC in Process Small CS subscriptions</inlineHelpText>
        <label>Pending Small CS Capacity</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Territories__c</fullName>
        <label>Service Territories</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Service_Territories</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Service_Territory__c</fullName>
        <label>XXXService Territory</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Duke Energy Carolinas (DEC)</fullName>
                </value>
                <value>
                    <fullName>Duke Energy Progress (DEP)</fullName>
                </value>
                <value>
                    <fullName>NEMA</fullName>
                </value>
                <value>
                    <fullName>SEMA</fullName>
                </value>
                <value>
                    <fullName>WCMA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_System_Size_kW_AC__c</fullName>
        <inlineHelpText>Total system size in kW AC.</inlineHelpText>
        <label>Total System Size (kW AC)</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_System_Size_kWh_DC__c</fullName>
        <inlineHelpText>Total system size in kW DC.</inlineHelpText>
        <label>Total System Size (kW DC)</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Utility__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Utility</label>
        <referenceTo>Utility__c</referenceTo>
        <relationshipLabel>Shared Solar Systems</relationshipLabel>
        <relationshipName>Shared_Solar_Systems</relationshipName>
        <type>Lookup</type>
    </fields>
    <gender n1:nil="true" />
    <household>false</household>
    <label>Shared Solar System</label>
    <nameField>
        <label>Shared Solar System Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shared Solar Systems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <startsWith n1:nil="true" />
</CustomObject>

src/objects/Transfer__c.object
<CustomObject>
    <fields>
        <fullName>Shared_Solar_System__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Transfer object is looking up to the SSS object.</description>
        <label>Shared Solar System</label>
        <referenceTo>Shared_Solar_System__c</referenceTo>
        <relationshipLabel>Transfers</relationshipLabel>
        <relationshipName>Transfers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Transfer</label>
    <nameField>
        <label>Transfer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transfers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Transfer_Part__c.object
<CustomObject>
    <fields>
        <fullName>Production__c</fullName>
        <description>A master-detail relationship from Transfer Parts up to Production</description>
        <label>Production</label>
        <referenceTo>Production__c</referenceTo>
        <relationshipLabel>Production Detail</relationshipLabel>
        <relationshipName>Transfer_Parts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Production Detail</label>
    <nameField>
        <label>Transfer Parts Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Production Detail</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Utility__c.object
<CustomObject>
    <fields>
        <fullName>Number_of_Decimal_Places__c</fullName>
        <inlineHelpText>Used for calculating kW subscriptions for SOs</inlineHelpText>
        <label>Number of Decimal Places</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Service_Territory__c</fullName>
        <inlineHelpText>Select the Territory(s) to which the data below will represent.</inlineHelpText>
        <label>XXService Territory</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Duke Energy Progress (DEP)</fullName>
                </value>
                <value>
                    <fullName>Duke Energy Carolinas (DEC)</fullName>
                </value>
                <value>
                    <fullName>All</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Utility</label>
    <nameField>
        <label>Utility Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Service_Territories.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>NEMA</fullName>
    </customValue>
    <customValue>
        <fullName>SEMA</fullName>
    </customValue>
    <customValue>
        <fullName>WCMA</fullName>
    </customValue>
    <customValue>
        <fullName>MN</fullName>
    </customValue>
    <customValue>
        <fullName>Capital</fullName>
    </customValue>
    <customValue>
        <fullName>Hudson Valley</fullName>
    </customValue>
    <customValue>
        <fullName>Mohawk Valley</fullName>
    </customValue>
    <customValue>
        <fullName>Central</fullName>
    </customValue>
    <customValue>
        <fullName>Genesee</fullName>
    </customValue>
    <customValue>
        <fullName>Dunwoodie</fullName>
    </customValue>
    <customValue>
        <fullName>N.Y.C.</fullName>
    </customValue>
    <customValue>
        <fullName>Millwood</fullName>
    </customValue>
    <customValue>
        <fullName>Long Island</fullName>
    </customValue>
    <customValue>
        <fullName>North</fullName>
    </customValue>
    <customValue>
        <fullName>West</fullName>
    </customValue>
    <customValue>
        <fullName>Maine</fullName>
    </customValue>
    <customValue>
        <fullName>Maine Public Service</fullName>
    </customValue>
    <customValue>
        <fullName>Bangor Hydro</fullName>
    </customValue>
    <masterLabel>Service Territories</masterLabel>
</GlobalValueSet>

src/classes/TransferPartServiceTest.cls
/**
 * Created by SarahRenfro on 9/5/2019.
 */

@IsTest
private class TransferPartServiceTest {

    @TestSetup
    public static void setupData() {

        Utility__c eversource = new Utility__c(
            Name = 'Eversource',
            Number_of_Decimal_Places__c = 2
        );

        insert eversource;

        Shared_Solar_System__c sss1 = new Shared_Solar_System__c(Name = 'Oxford Barrett St. P1',
            Service_Territory__c = 'SEMA',
            Service_Territories__c = 'SEMA',
            Open__c = true,
            Reserved_Capacity_kW_DC__c = '10',
            Capacity_Committed_kW_DC__c = 0,
            Total_System_Size_kWh_DC__c = 1445.86,
            Total_System_Size_kW_AC__c = 1000,
            Utility__c = eversource.Id,
            Credit_Score_Requirement__c = 300,
            Assignment_Order__c = '1',
            Expected_Yield_kWh_kW__c = 1300,
            Assemblage_Count__c = 1,
            Sales_Partners__c = 'All',
            Maximum_Subscription_Assemblage__c = 25);

        Shared_Solar_System__c sss2 = new Shared_Solar_System__c(Name = 'SSS 2',
            Service_Territory__c = 'NEMA',
            Service_Territories__c = 'NEMA',
            Open__c = true,
            Reserved_Capacity_kW_DC__c = '10',
            Capacity_Committed_kW_DC__c = 0,
            Total_System_Size_kWh_DC__c = 1445.86,
            Total_System_Size_kW_AC__c = 996,
            Utility__c = eversource.Id,
            Credit_Score_Requirement__c = 300,
            Assignment_Order__c = '2',
            Expected_Yield_kWh_kW__c = 1300,
            Assemblage_Count__c = 1,
            Sales_Partners__c = 'All',
            Maximum_Subscription_Assemblage__c = 25);

        insert new List<Shared_Solar_System__c> {sss1, sss2};

        Schedule_Z__c scheduleZ1 = new Schedule_Z__c(
            Name = '18-0515 Oxford Barrett St. P1',
            Shared_Solar_System__c = sss1.Id,
            Date_Enacted_by_Utility__c = Date.newInstance(2018,1,1),
            Status__c = 'Billing'
        );



        insert scheduleZ1;

        Production__c prod1 = new Production__c(
            Name = 'SSS 1 Production - May 2019',
            Shared_Solar_System__c = sss1.Id,
            Production_kWh__c = 20000,
            Credit_Value__c = 0.14,
            Credits_Generated__c = 10000,
            Start_Date__c = Date.newInstance(2019, 5, 1),
            End_Date__c = Date.newInstance(2019, 5, 29)
        );

        Production__c prod2 = new Production__c(
            Name = 'SSS 1 Production - June 2019',
            Shared_Solar_System__c = sss1.Id,
            Production_kWh__c = 15000,
            Credit_Value__c = 0.14,
            Credits_Generated__c = 8000,
            Start_Date__c = Date.newInstance(2019, 6, 1),
            End_Date__c = Date.newInstance(2019, 6, 29)
        );

        Production__c prod3 = new Production__c(
            Name = 'SSS 1 Production - July 2019',
            Shared_Solar_System__c = sss1.Id,
            Production_kWh__c = 10000,
            Credit_Value__c = 0.14,
            Credits_Generated__c = 5000,
            Start_Date__c = Date.newInstance(2019, 7, 1),
            End_Date__c = Date.newInstance(2019, 7, 29)
        );


        insert new List<Production__c> {prod1, prod2, prod3};

        Transfer_Part__c utilityFee = new Transfer_Part__c(
            Name = 'Eversource Utility Fee May 2019',
            Production__c = prod1.Id,
            Type__c = 'Fee',
            Fee_Paid_To__c = 'Utility',
            Amount__c = 10
        );

        insert utilityFee;

        //40 to be paid by excess
        Transfer__c onTime1 = new Transfer__c(
            Name = 'On-Time May Transfer',
            Allocation_Schedule__c = scheduleZ1.Id,
            Shared_Solar_System__c = sss1.Id,
            Attempted_Transfer__c = 9950,
            Transfer_Amount__c = 9950,
            Date_of_Transfer__c = Date.newInstance(2019, 6, 4)
        );

        //100 to be paid by excess
        Transfer__c onTime2 = new Transfer__c(
            Name = 'On-Time June Transfer',
            Allocation_Schedule__c = scheduleZ1.Id,
            Shared_Solar_System__c = sss1.Id,
            Attempted_Transfer__c = 7900,
            Transfer_Amount__c = 7900,
            Date_of_Transfer__c = Date.newInstance(2019, 7, 4)
        );

        //20 to be paid by excess
        Transfer__c onTimeToUpdate = new Transfer__c(
            Name = 'On-Time July Transfer',
            Allocation_Schedule__c = scheduleZ1.Id,
            Shared_Solar_System__c = sss1.Id,
            Attempted_Transfer__c = 4980,
            Transfer_Amount__c = 4980,
            Date_of_Transfer__c = Date.newInstance(2019, 8, 4)
        );

        insert new List<Transfer__c> {onTime1, onTime2, onTimeToUpdate};

        onTime1.Transfer_Type__c = 'On-Time';
        onTime2.Transfer_Type__c = 'On-Time';

        update new List<Transfer__c> {onTime1, onTime2};


    }


    @IsTest
    static void testOnTimeTransfer() {

        Transfer__c onTime = [
            SELECT Id, Transfer_Amount__c, Shared_Solar_System__r.Name, Total_Transferred__c, Transfer_Type__c
            FROM Transfer__c
            WHERE Name = 'On-Time July Transfer'
            LIMIT 1
        ];

        onTime.Transfer_Type__c = 'On-Time';
        update onTime;

        List<Transfer_Part__c> onTimeParts = [
          SELECT Id, Type__c, Amount__c, Transfer__c, Production__c
          FROM Transfer_Part__c
            WHERE Transfer__c = :onTime.Id
        ];

        Production__c production = [
            SELECT Id, Name, Credits_Transferred__c, Untransferred_Credits__c
            FROM Production__c
            WHERE Id = :onTimeParts[0].Production__c
            LIMIT 1
        ];

        Transfer__c checkTransfer = [SELECT Id, Total_Transferred__c FROM Transfer__c WHERE Id = :onTime.Id LIMIT 1];

        System.assertEquals(1, onTimeParts.size());
        System.assertEquals('Transfer', onTimeParts[0].Type__c);
        System.assertEquals(4980, onTimeParts[0].Amount__c);
        System.assertEquals(checkTransfer.Id, onTimeParts[0].Transfer__c);
        System.assertEquals(4980, checkTransfer.Total_Transferred__c);
        System.assertEquals('SSS 1 Production - July 2019', production.Name);
        System.assertEquals(4980, production.Credits_Transferred__c);
        System.assertEquals(20, production.Untransferred_Credits__c);


    }

    @IsTest
    public static void testExcessCreditTransfer() {

        Shared_Solar_System__c sss1 = [
            SELECT Id
            FROM Shared_Solar_System__c
            WHERE Name = 'Oxford Barrett St. P1'
            LIMIT 1
        ];

        Schedule_Z__c scheduleZ = [SELECT Id FROM Schedule_Z__c LIMIT 1];

        Transfer__c excessTransfer = new Transfer__c(
            Name = 'Excess May Transfer',
            Allocation_Schedule__c = scheduleZ.Id,
            Shared_Solar_System__c = sss1.Id,
            Attempted_Transfer__c = 40,
            Transfer_Amount__c = 40,
            Date_of_Transfer__c = Date.newInstance(2019, 8, 2)
        );

        insert excessTransfer;

        excessTransfer.Transfer_Type__c = 'Excess Credit';
        update excessTransfer;

        List<Transfer_Part__c> excessParts = [
            SELECT Id, Type__c, Amount__c, Transfer__c, Production__c
            FROM Transfer_Part__c
            WHERE Transfer__c = :excessTransfer.Id
        ];

        List<Production__c> productions = [
            SELECT Id, Name, Credits_Transferred__c, Untransferred_Credits__c
            FROM Production__c
            WHERE Id = :excessParts[0].Production__c
            ORDER BY Start_Date__c DESC
        ];

        Transfer__c checkTransfer = [
            SELECT Id, Total_Transferred__c
            FROM Transfer__c
            WHERE Id = :excessTransfer.Id
            LIMIT 1
        ];


        System.assertEquals(1, excessParts.size());
        System.assertEquals(40, excessParts[0].Amount__c);
        System.assertEquals(excessTransfer.Id, excessParts[0].Transfer__c);
        System.assertEquals(40, checkTransfer.Total_Transferred__c);
        System.assertEquals('Transfer', excessParts[0].Type__c);
        System.assertEquals('SSS 1 Production - May 2019', productions[0].Name);
        System.assertEquals(9990, productions[0].Credits_Transferred__c);
        System.assertEquals(0, productions[0].Untransferred_Credits__c);


    }

    @IsTest
    public static void testMultipleExcessCreditParts(){
        Shared_Solar_System__c sss1 = [
            SELECT Id
            FROM Shared_Solar_System__c
            WHERE Name = 'Oxford Barrett St. P1'
            LIMIT 1
        ];

        Schedule_Z__c scheduleZ = [SELECT Id FROM Schedule_Z__c LIMIT 1];

        Transfer__c excessTransfer = new Transfer__c(
            Name = 'Excess May Transfer',
            Allocation_Schedule__c = scheduleZ.Id,
            Shared_Solar_System__c = sss1.Id,
            Attempted_Transfer__c = 130,
            Transfer_Amount__c = 130,
            Date_of_Transfer__c = Date.newInstance(2019, 8, 2)
        );

        insert excessTransfer;

        excessTransfer.Transfer_Type__c = 'Excess Credit';
        update excessTransfer;

        List<Transfer_Part__c> excessParts = [
            SELECT Id, Type__c, Amount__c, Transfer__c, Production__c, Production__r.Name, Production__r.Id
            FROM Transfer_Part__c
            WHERE Transfer__c = :excessTransfer.Id
            ORDER BY Production__r.Start_Date__c ASC
        ];

        List<Production__c> productions = [
            SELECT Id, Name, Credits_Transferred__c, Untransferred_Credits__c
            FROM Production__c
            ORDER BY Start_Date__c ASC
        ];
        Transfer__c checkTransfer = [
            SELECT Id, Total_Transferred__c, Transfer_Amount__c
            FROM Transfer__c
            WHERE Id = :excessTransfer.Id
            LIMIT 1
        ];

        System.assertEquals(2, excessParts.size());
        System.assertEquals(checkTransfer.Total_Transferred__c, excessTransfer.Transfer_Amount__c);

        //First Transfer Part
        System.assertEquals(40, excessParts[0].Amount__c);
        System.assertEquals(excessTransfer.Id, excessParts[0].Transfer__c);
        System.assertEquals('Transfer', excessParts[0].Type__c);
        System.assertEquals('SSS 1 Production - May 2019', excessParts[0].Production__r.Name);
        System.assertEquals(productions[0].Id, excessParts[0].Production__r.Id);
        System.assertEquals(9990, productions[0].Credits_Transferred__c);
        System.assertEquals(0, productions[0].Untransferred_Credits__c);

        //Second Transfer Part
        System.assertEquals(90, excessParts[1].Amount__c);
        System.assertEquals(excessTransfer.Id, excessParts[1].Transfer__c);
        System.assertEquals('Transfer', excessParts[1].Type__c);
        System.assertEquals('SSS 1 Production - June 2019', excessParts[1].Production__r.Name);
        System.assertEquals(productions[1].Id, excessParts[1].Production__r.Id);
        System.assertEquals(7990, productions[1].Credits_Transferred__c);
        System.assertEquals(10, productions[1].Untransferred_Credits__c);

    }

    //TODO: WRITE RETURNED TRANSFER TEST


    @IsTest
    public static void testCreateCaseForTooMuchTransferCredit(){
        Shared_Solar_System__c sss1 = [
            SELECT Id
            FROM Shared_Solar_System__c
            WHERE Name = 'Oxford Barrett St. P1'
            LIMIT 1
        ];

        Schedule_Z__c scheduleZ = [SELECT Id FROM Schedule_Z__c LIMIT 1];

        Transfer__c excessTransfer = new Transfer__c(
            Name = 'Excess May Transfer',
            Allocation_Schedule__c = scheduleZ.Id,
            Shared_Solar_System__c = sss1.Id,
            Attempted_Transfer__c = 150,
            Transfer_Amount__c = 150,
            Date_of_Transfer__c = Date.newInstance(2019, 8, 2)
        );

        insert excessTransfer;

        excessTransfer.Transfer_Type__c = 'Excess Credit';
        update excessTransfer;

        List<Transfer_Part__c> excessParts = [
            SELECT Id, Type__c, Amount__c, Transfer__c, Production__c, Production__r.Name, Production__r.Id
            FROM Transfer_Part__c
            WHERE Transfer__c = :excessTransfer.Id
            ORDER BY Production__r.Start_Date__c ASC
        ];

        Transfer__c checkTransfer = [
            SELECT Id, Total_Transferred__c, Transfer_Amount__c
            FROM Transfer__c
            WHERE Id = :excessTransfer.Id
            LIMIT 1
        ];

        List<Case> checkCase = [SELECT Id, Subject FROM Case WHERE Shared_Solar_System__c = :excessTransfer.Shared_Solar_System__c];

        System.assertEquals(1, checkCase.size());
        System.assertEquals(2, excessParts.size());

        System.assertEquals(140, checkTransfer.Total_Transferred__c);
        System.assertEquals(150, checkTransfer.Transfer_Amount__c);

    }

    @IsTest
    public static void testUtilityFees() {

        Production__c production = [
            SELECT Id, Name, Credits_Transferred__c, Untransferred_Credits__c, Credits_Available_for_Allocation__c
            FROM Production__c
            WHERE Name = 'SSS 1 Production - June 2019'
            LIMIT 1
        ];

        System.assertEquals(8000, production.Credits_Available_for_Allocation__c);

        Transfer_Part__c utilityFee = new Transfer_Part__c(
            Name = 'Eversource Utility Fee May 2019',
            Production__c = production.Id,
            Type__c = 'Fee',
            Fee_Paid_To__c = 'Utility',
            Amount__c = 10
        );

        insert utilityFee;

        Production__c checkProd = [
            SELECT Id, Utility_Fees__c, Credits_Available_for_Allocation__c
            FROM Production__c
            WHERE Id =:production.Id
            LIMIT 1
        ];

        System.assertEquals(10, checkProd.Utility_Fees__c);
        System.assertEquals(7990, checkProd.Credits_Available_for_Allocation__c);

    }






}