src/objects/Client_Invoicing_Memo__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Contract_Fee_Detail__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Used to calculate Utilization Adjustments</inlineHelpText>
        <label>Contract Fee Detail</label>
        <referenceTo>Contract_Fee_Detail__c</referenceTo>
        <relationshipLabel>Client Invoicing Memos</relationshipLabel>
        <relationshipName>Client_Invoicing_Memos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Shared_Solar_System__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Used for Utilization Adjustments to Management Fees, populated by the Utilization Adjustment flow</inlineHelpText>
        <label>Shared Solar System</label>
        <referenceTo>Shared_Solar_System__c</referenceTo>
        <relationshipLabel>Client Invoicing Memos</relationshipLabel>
        <relationshipName>Client_Invoicing_Memos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subscription_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subscription Order</label>
        <referenceTo>Subscription_Order__c</referenceTo>
        <relationshipLabel>Client Invoicing Memos</relationshipLabel>
        <relationshipName>Client_Invoicing_Memos</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Client Invoicing Memo</label>
    <nameField>
        <displayFormat>CIM-{000000}</displayFormat>
        <label>Client Invoicing Memo Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Invoicing Memos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to relate multiple Client Contracts to a single opportunity</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contract_Fee_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Acquisition_Type_Reacquisition__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>As opposed to Acquistion. True if this fee is valid for reacquistion</inlineHelpText>
        <label>Acquisition Type: Reacquisition</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <inlineHelpText>The related Client Contract</inlineHelpText>
        <label>Contract</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Contract Fee Detail must be related to a contract with the record type = Client Contract</errorMessage>
            <filterItems>
                <field>Contract.RecordTypeId</field>
                <operation>equals</operation>
                <value>Client Contract</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Contract Fee Detail</relationshipLabel>
        <relationshipName>Contract_Fee_Detail</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Fee__c</fullName>
        <inlineHelpText>The annual $ value of the fee, see &quot;Fee Unit&quot; field for the denominator ($/W year or $/MW year or $/project year)</inlineHelpText>
        <label>Fee ($)</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Shared_Solar_System__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Used to make this CFD specific to a SSS when the ClientInvoicingFeeAssignmentService assigns a CFD to a Subscription Order when the SO is approved.</inlineHelpText>
        <label>Shared Solar System</label>
        <referenceTo>Shared_Solar_System__c</referenceTo>
        <relationshipLabel>Contract Fee Detail</relationshipLabel>
        <relationshipName>Contract_Fee_Detail</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Waive_Reacquisition_Fee_Max_Project__c</fullName>
        <inlineHelpText>Reacquisition fees will be waived until X% (annually) of the project (calculated by summing SOs with waived fee CIMs) has been reacquired after the initial period. If blank, all SOs will get CIMs to waive fees (potentially more than 100% of the project).</inlineHelpText>
        <label>Waive Reacq Fee: Max % After Period</label>
        <precision>7</precision>
        <scale>4</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Waive_Reacquisition_Fee_Number_Months__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>Must be populated at same time as field Waive Reacq Fee:Initial Period Milestone. The milestone + # of Months defines the end of the initial period, allowing us to waive fees before or after that initial period. Could be 0 but not blank.</inlineHelpText>
        <label>Waive Reacq Fee: # of Months</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Waive_Reacquisition_Fee_Project_Date__c</fullName>
        <inlineHelpText>Must be populated at same time as field Waive Reacq Fee: # of Months. The milestone + # of Months defines the end of the initial period, allowing us to waive fees before or after that initial period.</inlineHelpText>
        <label>Waive Reacq Fee:Initial Period Milestone</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Client_Invoicing_Events</valueSetName>
        </valueSet>
    </fields>
    <label>Contract Fee Detail</label>
    <nameField>
        <displayFormat>CFD-{000000}</displayFormat>
        <label>Contract Fee Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Fee Detail</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Shared_Solar_System__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>To change this system, use the Change SSS quick action</inlineHelpText>
        <label>Shared Solar System</label>
        <referenceTo>Shared_Solar_System__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Shared_Solar_System__c.object
<CustomObject
     >
    <articleTypeChannelDisplay n1:nil="true" />
    <customSettingsType n1:nil="true" />
    <description n1:nil="true" />
    <eventType n1:nil="true" />
    <fields>
        <fullName>Actual_COD_Date__c</fullName>
        <label>Actual COD Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Actual_PTO_Date_MANUAL__c</fullName>
        <description>Date the project reached PTO.</description>
        <inlineHelpText>Date the project reached PTO.</inlineHelpText>
        <label>Actual PTO Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Client_Acquisition_Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The field points to the same contract even if there is only one.</description>
        <inlineHelpText>Set automatically when a Client Contract is effective, and used for Client Invoicing. It could be the same as the Client Management Contract.</inlineHelpText>
        <label>Client Acquisition Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Client Acquisition Contract</relationshipLabel>
        <relationshipName>Shared_Solar_Systems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Client_Management_Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The field points to the same contract even if there is only one.</description>
        <inlineHelpText>Set automatically when a Client Contract is effective, and used for Client Invoicing. It could be the same as the Client Acquisition Contract.</inlineHelpText>
        <label>Client Management Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Client Management Contract</relationshipLabel>
        <relationshipName>Shared_Solar_Systems1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>First_Bill_Date__c</fullName>
        <inlineHelpText>Date of first bill sent to customers.</inlineHelpText>
        <label>First Bill Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Reacquisition_Start_Date__c</fullName>
        <inlineHelpText>The date at which acquisition is over and reacquisition begins, usually set by the first date at which an allocation schedule is accepted by the utility at 100%.</inlineHelpText>
        <label>Reacquisition Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Total_System_Size_kWh_DC__c</fullName>
        <inlineHelpText>Total system size in kW DC.</inlineHelpText>
        <label>Total System Size (kW DC)</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <gender n1:nil="true" />
    <household>false</household>
    <label>Shared Solar System</label>
    <nameField>
        <label>Shared Solar System Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shared Solar Systems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <startsWith n1:nil="true" />
</CustomObject>

src/objects/Subscription_Order__c.object
<CustomObject>
    <fields>
        <fullName>Approved_Change_in_Subscription__c</fullName>
        <description>This is the rounded net change in kW DC. When SO is approved, field is stamped with &apos;Calculated Change in Subscription kW DC.&apos; If Type = &apos;SSS Update,&apos; field is stamped with value of &apos;System Change in kW Subscription&apos; - &apos;Previous kW Subscription. It&apos;s important to have a static value for tracking purposes, and to use in rollup summary fields.</description>
        <inlineHelpText>This is the rounded net change in kW DC. When SO is approved, field is stamped with &apos;Calculated Change in Subscription kW DC.&apos; If Type = &apos;SSS Update,&apos; field is stamped with value of &apos;System Change in kW Subscription&apos; - &apos;Previous kW Subscription.</inlineHelpText>
        <label>Approved Change in Subscription (KW DC)</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Contract_Fee_Detail__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Acquisition rate charged to client for this change</inlineHelpText>
        <label>Contract Fee Detail</label>
        <referenceTo>Contract_Fee_Detail__c</referenceTo>
        <relationshipLabel>Subscription Orders</relationshipLabel>
        <relationshipName>Subscription_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <description>This is the date that the Subscription Order was approved. It is populated automatically when the Status field is set to approved. Subscription Orders cannot be edited once they&apos;ve been approved.</description>
        <inlineHelpText>This is the date that the Subscription Order was approved. It is populated automatically when the Status field is set to approved. Subscription Orders cannot be edited once they&apos;ve been approved.</inlineHelpText>
        <label>Effective Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Utility_Account_Subscription__c</fullName>
        <label>Utility Account Subscription</label>
        <referenceTo>Utility_Account_Subscription__c</referenceTo>
        <relationshipLabel>Subscription Orders</relationshipLabel>
        <relationshipName>Subscription_Orders</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Subscription Order</label>
    <nameField>
        <displayFormat>SO-{00000}</displayFormat>
        <label>Subscription Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscription Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Utility_Account_Subscription__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Utility Account Subscriptions</relationshipLabel>
        <relationshipName>Utility_Account_Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shared_Solar_System__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the SSS on the Opportunity when the UAS was created. The SSS on an existing UAS should never be changed.</description>
        <inlineHelpText>This is the SSS on the Opportunity when the UAS was created. The SSS on an existing UAS should never be changed.</inlineHelpText>
        <label>Shared Solar System</label>
        <referenceTo>Shared_Solar_System__c</referenceTo>
        <relationshipLabel>Utility Account Subscriptions</relationshipLabel>
        <relationshipName>Utility_Account_Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Utility Account Subscription</label>
    <nameField>
        <label>Utility Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Account Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/Client_Invoicing_Events.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Project Contract: Effective Date</fullName>
    </customValue>
    <customValue>
        <fullName>Contract: Effective Date</fullName>
    </customValue>
    <customValue>
        <fullName>Project: PTO</fullName>
    </customValue>
    <customValue>
        <fullName>Project: COD</fullName>
    </customValue>
    <customValue>
        <fullName>Project: First Customer Assignment Date</fullName>
    </customValue>
    <customValue>
        <fullName>Project: First Customer Bill Date</fullName>
    </customValue>
    <customValue>
        <fullName>Fee not Charged</fullName>
    </customValue>
    <customValue>
        <fullName>Customer: Assignment Date</fullName>
    </customValue>
    <customValue>
        <fullName>Project: Estimated COD or Customer: Assignment Date</fullName>
    </customValue>
    <customValue>
        <fullName>First Customer Bill Date</fullName>
        <isActive>false</isActive>
        <label>First Customer Bill Date</label>
    </customValue>
    <customValue>
        <fullName>First Customer Assignment Date</fullName>
        <isActive>false</isActive>
        <label>First Customer Assignment Date</label>
    </customValue>
    <customValue>
        <fullName>COD</fullName>
        <isActive>false</isActive>
        <label>COD</label>
    </customValue>
    <customValue>
        <fullName>PTO</fullName>
        <isActive>false</isActive>
        <label>PTO</label>
    </customValue>
    <customValue>
        <fullName>Contract Effective Date</fullName>
        <isActive>false</isActive>
        <label>Contract Effective Date</label>
    </customValue>
    <customValue>
        <fullName>First Bill</fullName>
        <isActive>false</isActive>
        <label>First Bill</label>
    </customValue>
    <masterLabel>Client Invoicing Events</masterLabel>
</GlobalValueSet>

src/classes/ClientInvoicingFeeWaiveServiceTest.cls
@isTest
public class ClientInvoicingFeeWaiveServiceTest {
    @IsTest
    private static void testSetSubscriptionOrderAcquisitionFee() {
        useMocks();
        List<Subscription_Order__c> orders = getSubscriptionOrderMocks();
        System.assertEquals(12,orders.size());

        ClientInvoicingFeeWaiveService service = new ClientInvoicingFeeWaiveService();
        service.setFeesToWaive(orders);

        List<Client_Invoicing_Memo__c> memosToInsert = (List<Client_Invoicing_Memo__c>)
            FFLibHelperTest.getRegisterNewListFromUnitOfWork(service.uow, 'Client_Invoicing_Memo__c');

        for (Client_Invoicing_Memo__c memo : memosToInsert) {
            String subOrderIdAsString = memo.Subscription_Order__c;

            // All subscription orders are 12 kW with a $0.10/W, so expect $-120 for a fully waived fee

            switch on subOrderIdAsString {
                when 'a9W3F000000A1P6UAK' {
                    System.assert(true,'Expected this fee to be waived with a COD Date Filter');
                    System.assertEquals(-120,memo.Amount__c);
                }
                when 'a9W3F000000A1P7UAK' {
                    System.assert(false,'Did not expect this fee to be waived with a COD Date Filter');
                }
                when 'a9W3F000000A2P7UAK' {
                    System.assert(true,'Expected this fee to be waived with a PTO Date Filter');
                    System.assertEquals(-120,memo.Amount__c);
                }
                when 'a9W3F000000A2P6UAK' {
                    System.assert(false,'Did not expect this fee to be waived with a PTO Date Filter');
                }
                when 'a9W3F000000A1P8UAK' {
                    System.assert(true,'Expected this fee to be waived with a First Bill Date Filter');
                    System.assertEquals(-120,memo.Amount__c);
                }
                when 'a9W3F000000A1P9UAK' {
                    System.assert(false,'Did not expect this fee to be waived with a First Bill Date Filter');
                }
                when 'a9W3F000000A1Q9UAK' {
                    System.assert(false,'Did not expect this fee to be waived with a Contract Effective Date Filter');
                }
                when 'a9W3F000000A1R9UAK' {
                    System.assert(true,'Expected this fee to be waived with a Contract Effective Date Filter');
                    System.assertEquals(-120,memo.Amount__c);
                }
                when 'a9W3F000000A1S9UAK' {
                    System.assert(true,'Expected this fee to be waived because it is under the 5% project max');
                    System.assertEquals(-120,memo.Amount__c);
                }
                when 'a9W3F000000A1T9UAK' {
                    System.assert(true,'Expected this fee to be waived because it is under the 5% project max');
                    // Only 9.24 kW left before hitting 5% cap, so only partially waived:
                    System.assertEquals(-92.36,memo.Amount__c);
                }
                when 'a9W3F000000A1U7UAK' {
                    System.assert(false,'Did not expect this fee to be waived because it is over the 5% project max');
                }
                when 'a9W3F000000A2U7UAK' {
                    System.assert(false,'Did not expect this fee to be waived because it is over the 5% project max');
                }
            }
        }
    }

    private static void useMocks() {
        ClientInvoicingFeeWaiveService.clientInvoicingMemoSelector = (ClientInvoicingMemoSelector) Test.createStub(ClientInvoicingMemoSelector.class, new MockClientInvoicingMemoSelector());
    }

    public class MockClientInvoicingMemoSelector extends MockProvider {
        public MockClientInvoicingMemoSelector() {
        }

        public override Object handleMethodCall(MethodCall methodCall) {
            String queryData = '{"a1J3F00000122b7UAA":39.76434,"a1J3F00000122b8UAA":101.788544}';

            Map<Id,Decimal> sssToWaivedAmountMap = (Map<Id,Decimal>) JSON.deserialize(queryData, Map<Id,Decimal>.class);

            switch on methodCall.stubbedMethodName {
                when 'getWaivedFeesBySSS' {
                    return sssToWaivedAmountMap;
                }
            }
            return null;
        }
    }

    public static List<Subscription_Order__c> getSubscriptionOrderMocks(){
        Date today = System.Today();
        Date sixMonthsAgo = today.addMonths(-6);
        Date fourMonthsAgo = today.addMonths(-4);
        Date monthFromToday = today.addMonths(1);

        String queryData = '[' +
            '{"Id":"a9W3F000000A1P6UAK","Effective_Date__c":"'+ String.valueOf(sixMonthsAgo) +'","Utility_Account_Subscription__c":"a1d3F0000013EV1QAM",' +
            '"Approved_Change_in_Subscription__c":12.00,"Contract_Fee_Detail__r":{"Fee__c":0.10,"Contract__r":{"StartDate":"2020-05-01"},' +
            '"Acquisition_Type_Reacquisition__c":true, "Waive_Reacquisition_Fee_Number_Months__c":8,"Waive_Reacquisition_Fee_Project_Date__c":"COD","Waive_Reacquisition_Fee_Max_Project__c":null},' +
            '"Utility_Account_Subscription__r":{"Id":"a1d3F0000013EV1QAM",' +
            '"Opportunity__c":"0063F00000MVO8EQAX","Shared_Solar_System__c":"a1J3F00000122b8UAA",' +
            '"Shared_Solar_System__r":{"Client_Acquisition_Contract__c":"8003F000000KMD9QAO","Client_Management_Contract__c":"8003F000000KNC9QAO",' +
            '"Total_System_Size_kWh_DC__c":1220,' +
            '"Actual_COD_Date__c":"'+ String.valueOf(sixMonthsAgo) +'","Actual_PTO_Date_MANUAL__c":"'+ String.valueOf(sixMonthsAgo) + '","First_Bill_Date__c":"'+ String.valueOf(fourMonthsAgo) + '",' +
            '"Reacquisition_Start_Date__c":"' + String.valueOf(monthFromToday) + '"},' +
            '"Opportunity__r":{"Id":"0063F00000MVO8EQAX","Customer_Group__c":"Residential","Partner_tag_lookup__c":"a0s3F000000thIBQAY","Partner_tag_lookup__r":{"Id":"a0s3F000000thIBQAY", ' +
            '"Account__r":{"Id":"0013F00000Y6WrnQAF","RecordType":{"Name":"Partner Account"}}}' +
            '}}},' +
            '{"Id":"a9W3F000000A1P7UAK","Effective_Date__c":"'+ String.valueOf(today) +'","Utility_Account_Subscription__c":"a1d3F0000014EV1QAM",' +
            '"Approved_Change_in_Subscription__c":12.00,"Contract_Fee_Detail__r":{"Fee__c":0.10,"Contract__r":{"StartDate":"2020-05-01"},' +
            '"Acquisition_Type_Reacquisition__c":true, "Waive_Reacquisition_Fee_Number_Months__c":2,"Waive_Reacquisition_Fee_Project_Date__c":"COD","Waive_Reacquisition_Fee_Max_Project__c":null},' +
            '"Utility_Account_Subscription__r":{"Id":"a1d3F0000014EV1QAM",' +
            '"Opportunity__c":"0063F00000MVO9EQAX","Shared_Solar_System__c":"a1J3F00000122b8UAA",' +
            '"Shared_Solar_System__r":{"Client_Acquisition_Contract__c":"8003F000000KMD9QAO","Client_Management_Contract__c":"8003F000000KNC9QAO",' +
            '"Total_System_Size_kWh_DC__c":1220,' +
            '"Actual_COD_Date__c":"'+ String.valueOf(sixMonthsAgo) +'","Actual_PTO_Date_MANUAL__c":"' + String.valueOf(sixMonthsAgo) + '","First_Bill_Date__c":"'+ String.valueOf(fourMonthsAgo) + '",' +
            '"Reacquisition_Start_Date__c":"' + String.valueOf(monthFromToday) + '"},' +
            '"Opportunity__r":{"Id":"0063F00000MVO9EQAX","Customer_Group__c":"Residential","Partner_tag_lookup__c":"a0s3F000000thIBQAY","Partner_tag_lookup__r":{"Id":"a0s3F000000xxIBQAY", ' +
            '"Account__r":{"Id":"0013F00000Y7WrnQAF","RecordType":{"Name":"Client Account"}}}' +
            '}}},' +
            '{"Id":"a9W3F000000A2P6UAK","Effective_Date__c":"'+ String.valueOf(today) +'","Utility_Account_Subscription__c":"a1d3F0000013EV1QAM",' +
            '"Approved_Change_in_Subscription__c":12.00,"Contract_Fee_Detail__r":{"Fee__c":0.10,"Contract__r":{"StartDate":"2020-05-01"},' +
            '"Acquisition_Type_Reacquisition__c":true, "Waive_Reacquisition_Fee_Number_Months__c":2,"Waive_Reacquisition_Fee_Project_Date__c":"PTO","Waive_Reacquisition_Fee_Max_Project__c":null},' +
            '"Utility_Account_Subscription__r":{"Id":"a1d3F0000013EV1QAM",' +
            '"Opportunity__c":"0063F00000AAO8EQAX","Shared_Solar_System__c":"a1J3F00000122b8UAA",' +
            '"Shared_Solar_System__r":{"Client_Acquisition_Contract__c":"8003F000000KMD9QAO","Client_Management_Contract__c":"8003F000000KNC9QAO",' +
            '"Total_System_Size_kWh_DC__c":1220,' +
            '"Actual_COD_Date__c":"'+ String.valueOf(sixMonthsAgo) +'","Actual_PTO_Date_MANUAL__c":"' + String.valueOf(sixMonthsAgo) + '","First_Bill_Date__c":"'+ String.valueOf(fourMonthsAgo) + '",' +
            '"Reacquisition_Start_Date__c":"' + String.valueOf(monthFromToday) + '"},' +
            '"Opportunity__r":{"Id":"0063F00000AAO8EQAX","Customer_Group__c":"Residential","Partner_tag_lookup__c":"a0s3F000000thIBQAY","Partner_tag_lookup__r":{"Id":"a0s3F000000thIBQAY", ' +
            '"Account__r":{"Id":"0013F00000Y6WrnQAF","RecordType":{"Name":"Partner Account"}}}' +
            '}}},' +
            '{"Id":"a9W3F000000A2P7UAK","Effective_Date__c":"'+ String.valueOf(today) +'","Utility_Account_Subscription__c":"a1d3F0000014EV1QAM",' +
            '"Approved_Change_in_Subscription__c":12.00,"Contract_Fee_Detail__r":{"Fee__c":0.10,"Contract__r":{"StartDate":"2020-05-01"},' +
            '"Acquisition_Type_Reacquisition__c":true, "Waive_Reacquisition_Fee_Number_Months__c":8,"Waive_Reacquisition_Fee_Project_Date__c":"PTO","Waive_Reacquisition_Fee_Max_Project__c":null},' +
            '"Utility_Account_Subscription__r":{"Id":"a1d3F0000014EV1QAM",' +
            '"Opportunity__c":"0063F00000MVO9EQAX","Shared_Solar_System__c":"a1J3F00000122b8UAA",' +
            '"Shared_Solar_System__r":{"Client_Acquisition_Contract__c":"8003F000000KMD9QAO","Client_Management_Contract__c":"8003F000000KNC9QAO",' +
            '"Total_System_Size_kWh_DC__c":1220,' +
            '"Actual_COD_Date__c":"'+ String.valueOf(sixMonthsAgo) +'","Actual_PTO_Date_MANUAL__c":"' + String.valueOf(sixMonthsAgo) + '","First_Bill_Date__c":"'+ String.valueOf(fourMonthsAgo) + '",' +
            '"Reacquisition_Start_Date__c":null},' +
            '"Opportunity__r":{"Id":"0063F00000MVO9EQAX","Customer_Group__c":"Residential","Partner_tag_lookup__c":"a0s3F000000thIBQAY","Partner_tag_lookup__r":{"Id":"a0s3F000000xxIBQAY", ' +
            '"Account__r":{"Id":"0013F00000Y7WrnQAF","RecordType":{"Name":"Client Account"}}}' +
            '}}},' +
            '{"Id":"a9W3F000000A1P8UAK","Effective_Date__c":"'+ String.valueOf(today) +'","Utility_Account_Subscription__c":"a1d3F0000015EV1QAM",' +
            '"Approved_Change_in_Subscription__c":-12.00,"Contract_Fee_Detail__r":{"Fee__c":0.10,"Contract__r":{"StartDate":"2020-05-01"},' +
            '"Acquisition_Type_Reacquisition__c":true, "Waive_Reacquisition_Fee_Number_Months__c":6,"Waive_Reacquisition_Fee_Project_Date__c":"First Customer Bill Date","Waive_Reacquisition_Fee_Max_Project__c":null},' +
            '"Utility_Account_Subscription__r":{"Id":"a1d3F0000015EV1QAM",' +
            '"Opportunity__c":"0063F00000MXO9EQAX","Shared_Solar_System__c":"a1J3F00000122b8UAA",' +
            '"Shared_Solar_System__r":{"Client_Acquisition_Contract__c":"8003F000000KMD9QAO","Client_Management_Contract__c":"8003F000000KNC9QAO",' +
            '"Total_System_Size_kWh_DC__c":1220,' +
            '"Actual_COD_Date__c":"'+ String.valueOf(sixMonthsAgo) +'","Actual_PTO_Date_MANUAL__c":"' + String.valueOf(sixMonthsAgo) + '","First_Bill_Date__c":"'+ String.valueOf(fourMonthsAgo) + '",' +
            '"Reacquisition_Start_Date__c":null},' +
            '"Opportunity__r":{"Id":"0063F00000MXO9EQAX","Customer_Group__c":"Residential","Partner_tag_lookup__c":"a0s3F000000thIBQAY","Partner_tag_lookup__r":{"Id":"a0s3F000000thIBQAY", ' +
            '"Account__r":{"Id":"0013F00000Y6WrnQAF","RecordType":{"Name":"Partner Account"}}}' +
            '}}},' +
            '{"Id":"a9W3F000000A1P9UAK","Effective_Date__c":"'+ String.valueOf(today) +'","Utility_Account_Subscription__c":"a1d3F0000016EV1QAM",' +
            '"Approved_Change_in_Subscription__c":12.00,"Contract_Fee_Detail__r":{"Fee__c":0.10,"Contract__r":{"StartDate":"2020-05-01"},' +
            '"Acquisition_Type_Reacquisition__c":true, "Waive_Reacquisition_Fee_Number_Months__c":0,"Waive_Reacquisition_Fee_Project_Date__c":"First Customer Bill Date","Waive_Reacquisition_Fee_Max_Project__c":null},' +
            '"Utility_Account_Subscription__r":{"Id":"a1d3F0000016EV1QAM",' +
            '"Opportunity__c":"0063F00000MWO9EQAX","Shared_Solar_System__c":"a1J3F00000122b8UAA",' +
            '"Shared_Solar_System__r":{"Client_Acquisition_Contract__c":"8003F000000KHH9QAO","Client_Management_Contract__c":"8003F000000KHH9QAO",' +
            '"Total_System_Size_kWh_DC__c":1220,' +
            '"Actual_COD_Date__c":"'+ String.valueOf(sixMonthsAgo) +'","Actual_PTO_Date_MANUAL__c":"' + String.valueOf(sixMonthsAgo) + '","First_Bill_Date__c":"'+ String.valueOf(fourMonthsAgo) + '",' +
            '"Reacquisition_Start_Date__c":null},' +
            '"Opportunity__r":{"Id":"0063F00000MWO9EQAX","Customer_Group__c":"Residential","Partner_tag_lookup__c":"a0s3F000000thIBQAY","Partner_tag_lookup__r":{"Id":"a0s3F000000thIBQAY", ' +
            '"Account__r":{"Id":"0013F00000Y6WrnQAF","RecordType":{"Name":"Partner Account"}}}' +
            '}}},' +
            '{"Id":"a9W3F000000A1Q9UAK","Effective_Date__c":"'+ String.valueOf(today) +'","Utility_Account_Subscription__c":"a1d3F0000016EV1QAM",' +
            '"Approved_Change_in_Subscription__c":12.00,"Contract_Fee_Detail__r":{"Fee__c":0.10,"Contract__r":{"StartDate":"'+ String.valueOf(fourMonthsAgo) + '"},' +
            '"Acquisition_Type_Reacquisition__c":true, "Waive_Reacquisition_Fee_Number_Months__c":1,"Waive_Reacquisition_Fee_Project_Date__c":"Contract Effective Date","Waive_Reacquisition_Fee_Max_Project__c":null},' +
            '"Utility_Account_Subscription__r":{"Id":"a1d3F0000016EV1QAM",' +
            '"Opportunity__c":"0063F00000MWO9EQAX","Shared_Solar_System__c":"a1J3F00000122b8UAA",' +
            '"Shared_Solar_System__r":{"Client_Acquisition_Contract__c":"8003F000000KHH9QAO","Client_Management_Contract__c":"8003F000000KHH9QAO",' +
            '"Total_System_Size_kWh_DC__c":1220,' +
            '"Actual_COD_Date__c":"'+ String.valueOf(sixMonthsAgo) +'","Actual_PTO_Date_MANUAL__c":"' + String.valueOf(sixMonthsAgo) + '","First_Bill_Date__c":"'+ String.valueOf(fourMonthsAgo) + '",' +
            '"Reacquisition_Start_Date__c":null},' +
            '"Opportunity__r":{"Id":"0063F00000MWO9EQAX","Customer_Group__c":"Non-Residential","Partner_tag_lookup__c":"a0s3F000000thIBQAY","Partner_tag_lookup__r":{"Id":"a0s3F000000thIBQAY", ' +
            '"Account__r":{"Id":"0013F00000Y6WrnQAF","RecordType":{"Name":"Partner Account"}}}' +
            '}}},' +
            '{"Id":"a9W3F000000A1R9UAK","Effective_Date__c":"'+ String.valueOf(today) +'","Utility_Account_Subscription__c":"a1d3F0000016EV1QAM",' +
            '"Approved_Change_in_Subscription__c":12.00,"Contract_Fee_Detail__r":{"Fee__c":0.10,"Contract__r":{"StartDate":"'+ String.valueOf(fourMonthsAgo) + '"},' +
            '"Acquisition_Type_Reacquisition__c":true, "Waive_Reacquisition_Fee_Number_Months__c":1,"Waive_Reacquisition_Fee_Project_Date__c":"Contract Effective Date","Waive_Reacquisition_Fee_Max_Project__c":null},' +
            '"Utility_Account_Subscription__r":{"Id":"a1d3F0000016EV1QAM",' +
            '"Opportunity__c":"0063F00000MWO9EQAX","Shared_Solar_System__c":"a1J3F00000122b8UAA",' +
            '"Shared_Solar_System__r":{"Client_Acquisition_Contract__c":"8003F000000KMD9QAO","Client_Management_Contract__c":"8003F000000KNC9QAO",' +
            '"Total_System_Size_kWh_DC__c":1220,' +
            '"Actual_COD_Date__c":"'+ String.valueOf(sixMonthsAgo) +'","Actual_PTO_Date_MANUAL__c":"' + String.valueOf(sixMonthsAgo) + '","First_Bill_Date__c":"'+ String.valueOf(fourMonthsAgo) + '",' +
            '"Reacquisition_Start_Date__c":null},' +
            '"Opportunity__r":{"Id":"0063F00000MWO9EQAX","Customer_Group__c":"Non-Residential","Partner_tag_lookup__c":"a0s3F000000thIBQAY","Partner_tag_lookup__r":{"Id":"a0s3F000000thIBQAY", ' +
            '"Account__r":{"Id":"0013F00000Y6WrnQAF","RecordType":{"Name":"Partner Account"}}}' +
            '}}},' +
            '{"Id":"a9W3F000000A1S9UAK","Effective_Date__c":"'+ String.valueOf(today) + '","Utility_Account_Subscription__c":"a1d3F0000017EV1QAM",' +
            '"Approved_Change_in_Subscription__c":12.00,"Contract_Fee_Detail__r":{"Fee__c":0.10,"Contract__r":{"StartDate":"2020-05-01"},' +
            '"Acquisition_Type_Reacquisition__c":true, "Waive_Reacquisition_Fee_Number_Months__c":null,"Waive_Reacquisition_Fee_Project_Date__c":null,"Waive_Reacquisition_Fee_Max_Project__c":5},' +
            '"Utility_Account_Subscription__r":{"Id":"a1d3F0000017EV1QAM",' +
            '"Opportunity__c":"0063F00000NWO9EQAX","Shared_Solar_System__c":"a1J3F00000122b7UAA",' +
            '"Shared_Solar_System__r":{"Client_Acquisition_Contract__c":"8003F000000KMD9QAO","Client_Management_Contract__c":"8003F000000KNC9QAO",' +
            '"Total_System_Size_kWh_DC__c":1220,' +
            '"Actual_COD_Date__c":"'+ String.valueOf(sixMonthsAgo) +'","Actual_PTO_Date_MANUAL__c":"' + String.valueOf(sixMonthsAgo) + '","First_Bill_Date__c":"'+ String.valueOf(fourMonthsAgo) + '",' +
            '"Reacquisition_Start_Date__c":null},' +
            '"Opportunity__r":{"Id":"0063F00000NWO9EQAX","Customer_Group__c":"Non-Residential","Partner_tag_lookup__c":"a0s3F000000thIBQAY","Partner_tag_lookup__r":{"Id":"a0s3F000000xxIBQAY", ' +
            '"Account__r":{"Id":"0013F00000Y7WrnQAF","RecordType":{"Name":"Client Account"}}}' +
            '}}},' +
            '{"Id":"a9W3F000000A1T9UAK","Effective_Date__c":"'+ String.valueOf(today) +  '","Utility_Account_Subscription__c":"a1d3F0000018EV1QAM",' +
            '"Approved_Change_in_Subscription__c":12.00,"Contract_Fee_Detail__r":{"Fee__c":0.10,"Contract__r":{"StartDate":"2020-05-01"},' +
            '"Acquisition_Type_Reacquisition__c":true, "Waive_Reacquisition_Fee_Number_Months__c":null,"Waive_Reacquisition_Fee_Project_Date__c":null,"Waive_Reacquisition_Fee_Max_Project__c":5},' +
            '"Utility_Account_Subscription__r":{"Id":"a1d3F0000018EV1QAM",' +
            '"Opportunity__c":"0063F00000XQO9EQAX","Shared_Solar_System__c":"a1J3F00000122b7UAA",' +
            '"Shared_Solar_System__r":{"Client_Acquisition_Contract__c":"8003F000000KMD9QAO","Client_Management_Contract__c":"8003F000000KNC9QAO",' +
            '"Total_System_Size_kWh_DC__c":1220,' +
            '"Actual_COD_Date__c":"'+ String.valueOf(sixMonthsAgo) +'","Actual_PTO_Date_MANUAL__c":"' + String.valueOf(sixMonthsAgo) + '","First_Bill_Date__c":"'+ String.valueOf(fourMonthsAgo) + '",' +
            '"Reacquisition_Start_Date__c":null},' +
            '"Opportunity__r":{"Id":"0063F00000NWO9EQAX","Customer_Group__c":"Anchor","Partner_tag_lookup__c":"a0s3F000000thIBQAY","Partner_tag_lookup__r":{"Id":"a0s3F000000xxIBQAY", ' +
            '"Account__r":{"Id":"0013F00000Y7WrnQAF","RecordType":{"Name":"Client Account"}}}' +
            '}}},' +
            '{"Id":"a9W3F000000A1U7UAK","Effective_Date__c":"'+ String.valueOf(today) + '","Utility_Account_Subscription__c":"a1d3F0000019EV1QAM",' +
            '"Approved_Change_in_Subscription__c":12.00,"Contract_Fee_Detail__r":{"Fee__c":0.10,"Contract__r":{"StartDate":"2020-05-01"},' +
            '"Acquisition_Type_Reacquisition__c":true, "Waive_Reacquisition_Fee_Number_Months__c":null,"Waive_Reacquisition_Fee_Project_Date__c":null,"Waive_Reacquisition_Fee_Max_Project__c":5},' +
            '"Utility_Account_Subscription__r":{"Id":"a1d3F0000019EV1QAM",' +
            '"Opportunity__c":"0063F00000XQO9EAAA","Shared_Solar_System__c":"a1J3F00000122b7UAA",' +
            '"Shared_Solar_System__r":{"Client_Acquisition_Contract__c":"8003F000000KMD9QAO","Client_Management_Contract__c":"8003F000000KNC9QAO",' +
            '"Total_System_Size_kWh_DC__c":1220,' +
            '"Actual_COD_Date__c":"'+ String.valueOf(sixMonthsAgo) +'","Actual_PTO_Date_MANUAL__c":"' + String.valueOf(sixMonthsAgo) + '","First_Bill_Date__c":"'+ String.valueOf(fourMonthsAgo) + '",' +
            '"Reacquisition_Start_Date__c":null},' +
            '"Opportunity__r":{"Id":"0063F00000MVO9EQAX","Customer_Group__c":"Public Offtake","Partner_tag_lookup__c":"a0s3F000000thIBQAY","Partner_tag_lookup__r":{"Id":"a0s3F000000thIBQAY", ' +
            '"Account__r":{"Id":"0013F00000Y6WrnQAF","RecordType":{"Name":"Partner Account"}}}' +
            '}}},' +
            '{"Id":"a9W3F000000A2U7UAK","Effective_Date__c":"'+ String.valueOf(today) + '","Utility_Account_Subscription__c":"a1d3F0000019EV1QAM",' +
            '"Approved_Change_in_Subscription__c":12.00,"Contract_Fee_Detail__r":{"Fee__c":0.10,"Contract__r":{"StartDate":"2020-05-01"},' +
            '"Acquisition_Type_Reacquisition__c":true, "Waive_Reacquisition_Fee_Number_Months__c":null,"Waive_Reacquisition_Fee_Project_Date__c":null,"Waive_Reacquisition_Fee_Max_Project__c":5},' +
            '"Utility_Account_Subscription__r":{"Id":"a1d3F0000025EV1QAM",' +
            '"Opportunity__c":"0063F00000ZZO9EAAA","Shared_Solar_System__c":"a1J3F00000122b7UAA",' +
            '"Shared_Solar_System__r":{"Client_Acquisition_Contract__c":"8003F000000KMD9QAO","Client_Management_Contract__c":"8003F000000KNC9QAO",' +
            '"Total_System_Size_kWh_DC__c":1220,' +
            '"Actual_COD_Date__c":"'+ String.valueOf(sixMonthsAgo) +'","Actual_PTO_Date_MANUAL__c":"' + String.valueOf(sixMonthsAgo) + '","First_Bill_Date__c":"'+ String.valueOf(fourMonthsAgo) + '",' +
            '"Reacquisition_Start_Date__c":"' + String.valueOf(monthFromToday) + '"},' +
            '"Opportunity__r":{"Id":"0063F00000ZZO9EAAA","Customer_Group__c":"Public Offtake","Partner_tag_lookup__c":"a0s3F000000thIBQAY","Partner_tag_lookup__r":{"Id":"a0s3F000000thIBQAY", ' +
            '"Account__r":{"Id":"0013F00000Y6WrnQAF","RecordType":{"Name":"Partner Account"}}}' +
            '}}}'+
            ']';
        return (List<Subscription_Order__c>) JSON.deserialize(queryData, List<Subscription_Order__c>.class);
    }
}