src/objects/Client_Invoicing_Memo__c.object
<CustomObject>
    <fields>
        <fullName>Contract_Fee_Detail__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Used to calculate Utilization Adjustments</inlineHelpText>
        <label>Contract Fee Detail</label>
        <referenceTo>Contract_Fee_Detail__c</referenceTo>
        <relationshipLabel>Client Invoicing Memos</relationshipLabel>
        <relationshipName>Client_Invoicing_Memos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Shared_Solar_System__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Used for Utilization Adjustments to Management Fees, populated by the Utilization Adjustment flow</inlineHelpText>
        <label>Shared Solar System</label>
        <referenceTo>Shared_Solar_System__c</referenceTo>
        <relationshipLabel>Client Invoicing Memos</relationshipLabel>
        <relationshipName>Client_Invoicing_Memos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subscription_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subscription Order</label>
        <referenceTo>Subscription_Order__c</referenceTo>
        <relationshipLabel>Client Invoicing Memos</relationshipLabel>
        <relationshipName>Client_Invoicing_Memos</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Client Invoicing Memo</label>
    <nameField>
        <displayFormat>CIM-{000000}</displayFormat>
        <label>Client Invoicing Memo Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Invoicing Memos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to relate multiple Client Contracts to a single opportunity</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contract_Fee_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Shared_Solar_System__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Used to make this CFD specific to a SSS when the ClientInvoicingFeeAssignmentService assigns a CFD to a Subscription Order when the SO is approved.</inlineHelpText>
        <label>Shared Solar System</label>
        <referenceTo>Shared_Solar_System__c</referenceTo>
        <relationshipLabel>Contract Fee Detail</relationshipLabel>
        <relationshipName>Contract_Fee_Detail</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contract Fee Detail</label>
    <nameField>
        <displayFormat>CFD-{000000}</displayFormat>
        <label>Contract Fee Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Fee Detail</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Customer_Group__c</fullName>
        <label>Customer Group</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Residential</fullName>
                </value>
                <value>
                    <fullName>Non-Residential</fullName>
                    <default>true</default>
                    <label>Non-Residential</label>
                </value>
                <value>
                    <fullName>Anchor</fullName>
                </value>
                <value>
                    <fullName>Business</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Partner_tag_lookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Partner</label>
        <referenceTo>Partner__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shared_Solar_System__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>To change this system, use the Change SSS quick action</inlineHelpText>
        <label>Shared Solar System</label>
        <referenceTo>Shared_Solar_System__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Partner__c.object
<CustomObject>
    <label>Partner</label>
    <nameField>
        <label>Partner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partners</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Shared_Solar_System__c.object
<CustomObject
     >
    <articleTypeChannelDisplay n1:nil="true" />
    <customSettingsType n1:nil="true" />
    <description n1:nil="true" />
    <eventType n1:nil="true" />
    <fields>
        <fullName>Client_Acquisition_Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The field points to the same contract even if there is only one.</description>
        <inlineHelpText>Set automatically when a Client Contract is effective, and used for Client Invoicing. It could be the same as the Client Management Contract.</inlineHelpText>
        <label>Client Acquisition Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Client Acquisition Contract</relationshipLabel>
        <relationshipName>Shared_Solar_Systems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Client_Management_Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The field points to the same contract even if there is only one.</description>
        <inlineHelpText>Set automatically when a Client Contract is effective, and used for Client Invoicing. It could be the same as the Client Acquisition Contract.</inlineHelpText>
        <label>Client Management Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Client Management Contract</relationshipLabel>
        <relationshipName>Shared_Solar_Systems1</relationshipName>
        <type>Lookup</type>
    </fields>
    <gender n1:nil="true" />
    <household>false</household>
    <label>Shared Solar System</label>
    <nameField>
        <label>Shared Solar System Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shared Solar Systems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <startsWith n1:nil="true" />
</CustomObject>

src/objects/Subscription_Order__c.object
<CustomObject>
    <fields>
        <fullName>Approved_Change_in_Subscription__c</fullName>
        <description>This is the rounded net change in kW DC. When SO is approved, field is stamped with &apos;Calculated Change in Subscription kW DC.&apos; If Type = &apos;SSS Update,&apos; field is stamped with value of &apos;System Change in kW Subscription&apos; - &apos;Previous kW Subscription. It&apos;s important to have a static value for tracking purposes, and to use in rollup summary fields.</description>
        <inlineHelpText>This is the rounded net change in kW DC. When SO is approved, field is stamped with &apos;Calculated Change in Subscription kW DC.&apos; If Type = &apos;SSS Update,&apos; field is stamped with value of &apos;System Change in kW Subscription&apos; - &apos;Previous kW Subscription.</inlineHelpText>
        <label>Approved Change in Subscription (KW DC)</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Contract_Fee_Detail__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Acquisition rate charged to client for this change</inlineHelpText>
        <label>Contract Fee Detail</label>
        <referenceTo>Contract_Fee_Detail__c</referenceTo>
        <relationshipLabel>Subscription Orders</relationshipLabel>
        <relationshipName>Subscription_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <description>This is the date that the Subscription Order was approved. It is populated automatically when the Status field is set to approved. Subscription Orders cannot be edited once they&apos;ve been approved.</description>
        <inlineHelpText>This is the date that the Subscription Order was approved. It is populated automatically when the Status field is set to approved. Subscription Orders cannot be edited once they&apos;ve been approved.</inlineHelpText>
        <label>Effective Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Utility_Account_Subscription__c</fullName>
        <label>Utility Account Subscription</label>
        <referenceTo>Utility_Account_Subscription__c</referenceTo>
        <relationshipLabel>Subscription Orders</relationshipLabel>
        <relationshipName>Subscription_Orders</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Subscription Order</label>
    <nameField>
        <displayFormat>SO-{00000}</displayFormat>
        <label>Subscription Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscription Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Utility_Account_Subscription__c.object
<CustomObject>
    <fields>
        <fullName>Customer_Group__c</fullName>
        <formula>Text(Opportunity__r.Customer_Group__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Customer Group</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Utility Account Subscriptions</relationshipLabel>
        <relationshipName>Utility_Account_Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shared_Solar_System__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the SSS on the Opportunity when the UAS was created. The SSS on an existing UAS should never be changed.</description>
        <inlineHelpText>This is the SSS on the Opportunity when the UAS was created. The SSS on an existing UAS should never be changed.</inlineHelpText>
        <label>Shared Solar System</label>
        <referenceTo>Shared_Solar_System__c</referenceTo>
        <relationshipLabel>Utility Account Subscriptions</relationshipLabel>
        <relationshipName>Utility_Account_Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Utility Account Subscription</label>
    <nameField>
        <label>Utility Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Account Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ClientInvoicingFeeAssignmentService.cls
/**
  @description Assigns Contract Fee Details to a Subscription Order, and generates Client Invoicing Memos, if necessary
  Tested By: ClientInvoicingFeeAssignmentServiceTest, ClientInvoicingFeeWaiveServiceTest
 */
public without sharing class ClientInvoicingFeeAssignmentService {
    @TestVisible private static SubscriptionOrderSelector subscriptionOrderSelector = new SubscriptionOrderSelector();
    private List<SubscriptionOrder> subOrdersAsFeeQualifications = new List<SubscriptionOrder>();
    private Set<Id> subscriptionOrderIds;
    private List<Subscription_Order__c> queriedSOs;
    @TestVisible
    private fflib_SObjectUnitOfWork uow = new fflib_SObjectUnitOfWork(
        new List<SObjectType> {
            Subscription_Order__c.SObjectType
        }
    );

    public ClientInvoicingFeeAssignmentService(Set<Id> subscriptionOrderIds) {
        this.subscriptionOrderIds = subscriptionOrderIds;
        init();
    }

    public void init(Set<Id> subscriptionOrderIds) {
        this.subscriptionOrderIds = subscriptionOrderIds;
        init();
    }

    private void init() {
        queriedSOs = subscriptionOrderSelector.selectByIds(subscriptionOrderIds);
        ContractRepository.initFromSubscriptionOrders(queriedSOs);
        for (Subscription_Order__c subOrder : queriedSOs) {
            if (hasRequiredFieldsForAssignment(subOrder)) {
                SubscriptionOrder feeQualifier = new SubscriptionOrder(subOrder);
                subOrdersAsFeeQualifications.add(feeQualifier);
            }
        }
    }

    /**
     * @description Future method to assign CFDs and generate CIMs outside of the SO approval transaction
     * @param subscriptionOrderIds Set of Subscription Order Ids to assign
     */
    @Future
    public static void setSubOrderContractFeeDetailInFuture(Set<Id> subscriptionOrderIds){
        try {
            ClientInvoicingFeeAssignmentService feeJob = new ClientInvoicingFeeAssignmentService(subscriptionOrderIds);
            feeJob.setSubOrderContractFeeDetail();
        } catch (Exception e) {
            Logger.logNow('ClientInvoicingFeeAssignmentService', 'setSubOrderContractFeeDetailInFuture', e.getMessage() + '\n' + e.getStackTraceString(), Logger.ERROR);
        }
    }

    /**
     * @description Instance method to assign CFDs and generate CIMs for use in anonymous apex
     */
    public void setSubOrderContractFeeDetail() {
        try {
            setSubscriptionOrderAcquisitionFee();
            uow.commitWork();
            Logger.flushLogs();

            uow = new fflib_SObjectUnitOfWork(new List<SObjectType> {Client_Invoicing_Memo__c.SObjectType});

            List<Subscription_Order__c> ordersAfterFeesAreSet = subscriptionOrderSelector.selectByIds(subscriptionOrderIds);
            ClientInvoicingFeeWaiveService waiveService = new ClientInvoicingFeeWaiveService();
            waiveService.waiveFeesIfNecessary(ordersAfterFeesAreSet, uow);
            uow.commitWork();
            Logger.flushLogs();
        } catch (Exception e){
            Logger.logNow(
                'ClientInvoicingFeeAssignmentService',
                'setSubOrderContractFeeDetail',
                e.getMessage() + '\n' + e.getStackTraceString() + '\n' + JSON.serialize(subscriptionOrderIds),
                Logger.ERROR
            );
        }
    }

    /**
     * @description Finds a matching CFD for each Subscription Order and registers the SO for update
     */
    @TestVisible
    private void setSubscriptionOrderAcquisitionFee() {
        for (SubscriptionOrder subOrder : subOrdersAsFeeQualifications) {
            matchSubscriptionOrderToFee(subOrder);
        }
    }

    /**
     * @description Registers a Subscription Order with a CFD update with this service's UOW.
     * @param subscriptionOrder The Subscription Order to get assigned a Contract Fee Detail
     * @return A Subscription Order with a potentially populated CFD
     */
    @TestVisible
    private Subscription_Order__c matchSubscriptionOrderToFee(SubscriptionOrder subscriptionOrder) {
        List<ContractFeeDetail> contractFeeDetails = getContractFeeDetailsFromContracts(subscriptionOrder, ContractRepository.getContractToContractFeeDetails());
        Subscription_Order__c orderToUpdate;
        MultiMap multiMapForDuplicateCFDCheck = MultiMap.newListInstance();
        for (ContractFeeDetail cfd : contractFeeDetails) {
            if (!cfd.matches(subscriptionOrder) || subscriptionOrder.contractFeeDetailId == cfd.recordId) {
                continue;
            }
            orderToUpdate = handleMatchingCFD(orderToUpdate, subscriptionOrder, cfd, multiMapForDuplicateCFDCheck);
        }
        if (orderToUpdate != null) {
            uow.registerDirty(orderToUpdate);
        }
        for (Object sharedSolarSystemId : multiMapForDuplicateCFDCheck.keySet()) {
            if (multiMapForDuplicateCFDCheck.getValues(sharedSolarSystemId).size() > 1) {
                Logger.logLater(
                    'ClientInvoicingFeeAssignmentService',
                    'matchSubscriptionOrderToFee',
                    'Multiple CFDs found for SO:\n' + JSON.serialize(subscriptionOrder),
                    Logger.ERROR
                );
            }
        }
        return orderToUpdate;
    }

    /**
     * @description Initializes or updates the subscriptionOrderSObj with the matching CFD, honoring the Shared Solar System override on the CFD.
     * @param subscriptionOrderSObj The Subscription Order SObject used to update the SO with a CFD.
     * @param subscriptionOrder The apex class that represents the Subscription Order SObject to be compared to the CFD
     * @param cfd The apex class that represents the Contract Fee Detail SObject to be compared to the SO
     * @param multiMapForDuplicateCFDCheck A MultiMap used to report if there are duplicate CFDs (with SSS specifications and without)
     * @return The subscriptionOrderSObj, which might be initialized to a new SO.
     */
    private Subscription_Order__c handleMatchingCFD(Subscription_Order__c subscriptionOrderSObj, SubscriptionOrder subscriptionOrder,
        ContractFeeDetail cfd, MultiMap multiMapForDuplicateCFDCheck) {
        multiMapForDuplicateCFDCheck.putValue(cfd.sharedSolarSystemId, cfd);
        if (subscriptionOrderSObj == null) {
            // This must be the first matching CFD, so we'll assign it to the SO independent of whether there's a
            // SSS override or not.
            subscriptionOrderSObj = new Subscription_Order__c(
                Id = subscriptionOrder.recordId,
                Contract_Fee_Detail__c = cfd.recordId
            );
        } else if (cfd.sharedSolarSystemId != null && cfd.sharedSolarSystemId == subscriptionOrder.sharedSolarSystemId) {
            // There's already a CFD that matches this SO, but it could be one that didn't have a SSS override.
            // Because this CFD is SSS specific and it matches the SO's SSS, we'll use it.
            subscriptionOrderSObj.Contract_Fee_Detail__c = cfd.recordId;
        }
        // Otherwise, the feeDetail must have a null or not matching SSS. Because there's already a CFD assigned to the SO (either a SSS
        // specific one or a duplicate), we'll skip assigning this.
        return subscriptionOrderSObj;
    }

    private List<ContractFeeDetail> getContractFeeDetailsFromContracts(SubscriptionOrder subOrder, MultiMap contractToFeeDetailMap) {
        List<ContractFeeDetail> contractDetails = new List<ContractFeeDetail>();
        // Max 2 contracts per Subscription Order (1 Acq, 1 Mgmt)
        for (Id contractId : subOrder.contractIds) {
            CollectionUtil.toTypedList(contractToFeeDetailMap.getValues(contractId), contractDetails);
        }
        return contractDetails;
    }

    private Boolean hasRequiredFieldsForAssignment(Subscription_Order__c subOrder){
        if (subOrder.Utility_Account_Subscription__r.Opportunity__r.Customer_Group__c != null &&
            subOrder.Utility_Account_Subscription__r.Opportunity__r.Partner_tag_lookup__r.Account__r.RecordType.Name != null &&
            subOrder.Approved_Change_in_Subscription__c != null &&
            subOrder.Effective_Date__c != null &&
            subOrder.Utility_Account_Subscription__r.Shared_Solar_System__c != null &&
            (subOrder.Utility_Account_Subscription__r.Shared_Solar_System__r.Client_Acquisition_Contract__c != null ||
                subOrder.Utility_Account_Subscription__r.Shared_Solar_System__r.Client_Management_Contract__c != null)) {
            return true;
        } else {
            return false;
        }
    }
}