src/objects/Client_Contract__c.object
<CustomObject>
    <description>Junction between Shared Solar System and Contract to allow effective dating contracts (e.g. future dated amendments).</description>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Client Contract related to the Shared Solar System. Required to be a Contract with the Client Contract record type.</inlineHelpText>
        <label>Contract</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The Contract needs to be a Client Contract record type</errorMessage>
            <filterItems>
                <field>Contract.RecordType.Name</field>
                <operation>equals</operation>
                <value>Client Contract</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Client Contracts</relationshipLabel>
        <relationshipName>Client_Contract_Junctions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <inlineHelpText>At the beginning of this day, the system will automatically populate the Shared Solar System with the related Contract according to the CS Services Type to be used for Client Invoicing.</inlineHelpText>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <inlineHelpText>At the end of this day, the contract will be automatically removed from the System (unless there is a subsequent Client Contract) and no longer used for client invoicing. Can be different from the Contract&apos;s End Date.</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Shared_Solar_System__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Shared Solar System related to this Contract.</inlineHelpText>
        <label>Shared Solar System</label>
        <referenceTo>Shared_Solar_System__c</referenceTo>
        <relationshipLabel>Client Contracts</relationshipLabel>
        <relationshipName>Client_Contract_Junctions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Contract</label>
    <nameField>
        <displayFormat>CC-{0000}</displayFormat>
        <label>Project Contract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contract_Fee_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Contract__c</fullName>
        <inlineHelpText>The related Client Contract</inlineHelpText>
        <label>Contract</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Contract Fee Detail must be related to a contract with the record type = Client Contract</errorMessage>
            <filterItems>
                <field>Contract.RecordTypeId</field>
                <operation>equals</operation>
                <value>Client Contract</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Contract Fee Detail</relationshipLabel>
        <relationshipName>Contract_Fee_Detail</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Shared_Solar_System__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Used to make this CFD specific to a SSS when the ClientInvoicingFeeAssignmentService assigns a CFD to a Subscription Order when the SO is approved.</inlineHelpText>
        <label>Shared Solar System</label>
        <referenceTo>Shared_Solar_System__c</referenceTo>
        <relationshipLabel>Contract Fee Detail</relationshipLabel>
        <relationshipName>Contract_Fee_Detail</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contract Fee Detail</label>
    <nameField>
        <displayFormat>CFD-{000000}</displayFormat>
        <label>Contract Fee Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Fee Detail</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Shared_Solar_System__c.object
<CustomObject
     >
    <articleTypeChannelDisplay n1:nil="true" />
    <customSettingsType n1:nil="true" />
    <description n1:nil="true" />
    <eventType n1:nil="true" />
    <gender n1:nil="true" />
    <household>false</household>
    <label>Shared Solar System</label>
    <nameField>
        <label>Shared Solar System Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shared Solar Systems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <startsWith n1:nil="true" />
</CustomObject>

src/classes/ContractRepository.cls
/**
 * @description Convenience class to get data about Contracts for client invoicing
 * Tested By: ContractRepositoryTest, ClientInvoicingFeeAssignmentServiceTest, ClientInvoicingFeeWaiveServiceTest
 */
public without sharing class ContractRepository {
    @TestVisible private static ClientContractSelector clientContractSelector = new ClientContractSelector();
    @TestVisible private static ContractFeeDetailSelector contractFeeDetailSelector = new ContractFeeDetailSelector();
    @TestVisible private static List<Client_Contract__c> clientContracts;
    @TestVisible private static MultiMap contractToFeeDetailMap;

    /**
     * @description Initializes this repository with all Project Contracts (Client_Contract__c) for Shared Solar Systems
     * @param sssIdsRequiringProjectContracts Shared Solar Systems for which this should get Project Contracts
     */
    public static void initFromSharedSolarSystems(Set<Id> sssIdsRequiringProjectContracts) {
        clientContracts = clientContractSelector.getClientContracts(sssIdsRequiringProjectContracts);
    }

    /**
     * @description Used after the repository is initialized from Shared Solar Systems to get the Effective Date for
     * a System
     * @param contractId The Management or Acquisition Contract Id for the client
     * @param sssId The Shared Solar System Id
     * @param asOfDate The effective date (of the subscription order)
     * @return The Effective Date for the Project Contract (Client_Contract__c), or null, if a Contract/System was not
     * effective for that Contract and System as of the asOfDate
     */
    public static Date getProjectContractEffectiveDate(Id contractId, Id sssId, Date asOfDate) {
        if (clientContracts == null) {
            throw new Util.BWException('ContractRepository needs to be initialized before getting client contracts');
        }
        for (Client_Contract__c clientContract : clientContracts) {
            if (contractId == clientContract.Contract__c &&
                sssId == clientContract.Shared_Solar_System__c &&
                DateUtil.between(clientContract.Effective_Date__c, asOfDate, clientContract.End_Date__c)) {
                return clientContract.Effective_Date__c;
            }
        }
        Logger.logLater(
            'ContractRepository',
            'getProjectContractEffectiveDate',
            'Could not find Project Contract for ' +
                'Contract ' + contractId + ' and System ' + sssId + ' that was effective on ' + asOfDate,
            Logger.ERROR
        );
        return null;
    }

    /**
     * @description Initializes the repository with Contract Fee Details from a set of Contract Ids
     * @param contractIds Set of Acquisition or Management Contract Ids
     */
    public static void initFromContractIds(Set<Id> contractIds) {
        List<Contract_Fee_Detail__c> feeDetailList = contractFeeDetailSelector.getContractDetailFromContract(contractIds);
        convertContractFeeListToFeeDetailMap(feeDetailList);
    }

    /**
     * @description Used after initializing the repository with Contract Ids to get a MultiMap of Contract to Contract Fee Details
     * @return MultiMap
     */
    public static MultiMap getContractToContractFeeDetails() {
        if (contractToFeeDetailMap == null) {
            throw new Util.BWException('ContractRepository needs to be initialized before getting contract fee details');
        }
        return contractToFeeDetailMap;
    }

    @TestVisible
    private static void convertContractFeeListToFeeDetailMap(List<Contract_Fee_Detail__c> contractFeeDetail) {
        contractToFeeDetailMap = MultiMap.newListInstance();

        for (Contract_Fee_Detail__c feeDetail : contractFeeDetail){
            ContractFeeDetail feeQualifier = new ContractFeeDetail(feeDetail);
            contractToFeeDetailMap.putValue(feeDetail.Contract__c, feeQualifier);
        }
    }
}