src/objects/Client_Contract__c.object
<CustomObject>
    <description>Junction between Shared Solar System and Contract to allow effective dating contracts (e.g. future dated amendments).</description>
    <fields>
        <fullName>CS_Services_Type__c</fullName>
        <inlineHelpText>Indicates how this Contract should be used for Client Invoicing, and which fields (Client Acquisition Contract and Client Management Contract) are populated on the System.</inlineHelpText>
        <label>CS Services Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>CS_Services_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Client Contract related to the Shared Solar System. Required to be a Contract with the Client Contract record type.</inlineHelpText>
        <label>Contract</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The Contract needs to be a Client Contract record type</errorMessage>
            <filterItems>
                <field>Contract.RecordType.Name</field>
                <operation>equals</operation>
                <value>Client Contract</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Client Contracts</relationshipLabel>
        <relationshipName>Client_Contract_Junctions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <inlineHelpText>At the beginning of this day, the system will automatically populate the Shared Solar System with the related Contract according to the CS Services Type to be used for Client Invoicing.</inlineHelpText>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <inlineHelpText>At the end of this day, the contract will be automatically removed from the System (unless there is a subsequent Client Contract) and no longer used for client invoicing. Can be different from the Contract&apos;s End Date.</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Shared_Solar_System__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Shared Solar System related to this Contract.</inlineHelpText>
        <label>Shared Solar System</label>
        <referenceTo>Shared_Solar_System__c</referenceTo>
        <relationshipLabel>Client Contracts</relationshipLabel>
        <relationshipName>Client_Contract_Junctions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Contract</label>
    <nameField>
        <displayFormat>CC-{0000}</displayFormat>
        <label>Project Contract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contract_Fee_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Acquisition_Channels_BCS_Acquired__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>True if this fee is valid for customers acquired by BCS</inlineHelpText>
        <label>Acq Channels: BCS Acquired</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Acquisition_Channels_Non_BCS_Acquired__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>True if this fee is valid for customers who were not acquired by BCS</inlineHelpText>
        <label>Acq Channels: Non-BCS Acquired</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Acquisition_Cust_Group_Not_Specified__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>True if this CFD applies to Opportunities without a Customer Group specified (typically the case)</inlineHelpText>
        <label>Acq Cust. Sub-Group: Not Specified</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Acquisition_Cust_Group_Residential__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>True if valid fee for customers with the Customer Group = Residential.
Small offtake (ie, Residential and Non-Residential Customer Groups) can be labeled as &quot;non-Demand Customers&quot; and Anchors can be labeled as &quot;Demand Customers&quot; in client contracts.</inlineHelpText>
        <label>Acquisition Cust. Group: Residential</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Acquisition_Sizing_Type_Upsizing__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>True if this fee is valid for increases in a customer subscription (+ kW)</inlineHelpText>
        <label>Acquisition Sizing Type: Upsizing</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Acquisition_Type_Reacquisition__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>As opposed to Acquistion. True if this fee is valid for reacquistion</inlineHelpText>
        <label>Acquisition Type: Reacquisition</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>In Approvals</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <inlineHelpText>The related Client Contract</inlineHelpText>
        <label>Contract</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Contract Fee Detail must be related to a contract with the record type = Client Contract</errorMessage>
            <filterItems>
                <field>Contract.RecordTypeId</field>
                <operation>equals</operation>
                <value>Client Contract</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Contract Fee Detail</relationshipLabel>
        <relationshipName>Contract_Fee_Detail</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Fee_Unit__c</fullName>
        <inlineHelpText>See Fee ($) field for numerator. Ie $/W, $/MW (implicitly, per year)</inlineHelpText>
        <label>Fee Unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>per W</fullName>
                </value>
                <value>
                    <fullName>per MW</fullName>
                </value>
                <value>
                    <fullName>per project</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Fee__c</fullName>
        <inlineHelpText>The annual $ value of the fee, see &quot;Fee Unit&quot; field for the denominator ($/W year or $/MW year or $/project year)</inlineHelpText>
        <label>Fee ($)</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Shared_Solar_System__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Used to make this CFD specific to a SSS when the ClientInvoicingFeeAssignmentService assigns a CFD to a Subscription Order when the SO is approved.</inlineHelpText>
        <label>Shared Solar System</label>
        <referenceTo>Shared_Solar_System__c</referenceTo>
        <relationshipLabel>Contract Fee Detail</relationshipLabel>
        <relationshipName>Contract_Fee_Detail</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contract Fee Detail</label>
    <nameField>
        <displayFormat>CFD-{000000}</displayFormat>
        <label>Contract Fee Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Fee Detail</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Parent_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shared_Solar_System__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>To change this system, use the Change SSS quick action</inlineHelpText>
        <label>Shared Solar System</label>
        <referenceTo>Shared_Solar_System__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Shared_Solar_System__c.object
<CustomObject
     >
    <articleTypeChannelDisplay n1:nil="true" />
    <customSettingsType n1:nil="true" />
    <description n1:nil="true" />
    <eventType n1:nil="true" />
    <fields>
        <fullName>CS_Services_Type__c</fullName>
        <description>Should use the CS Services Type global picklist, but can&apos;t because it&apos;s already created.</description>
        <inlineHelpText>Differentiates between projects where BlueWave is contracted to acquire customers and projects where customers are acquired by another party. Set automatically when a new related Client Contract record is effective</inlineHelpText>
        <label>CS Services Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Acquisition &amp; Management</fullName>
                </value>
                <value>
                    <fullName>Management Only</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <gender n1:nil="true" />
    <household>false</household>
    <label>Shared Solar System</label>
    <nameField>
        <label>Shared Solar System Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shared Solar Systems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <startsWith n1:nil="true" />
</CustomObject>

src/objects/Subscription_Order__c.object
<CustomObject>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <description>Subscription Orders will not be rolled up to the utility account subscription until they are marked as approved. Once approved, they cannot be changed.</description>
        <inlineHelpText>Subscription Orders will not be rolled up to the utility account subscription until they are marked as approved. Once approved, they cannot be changed.</inlineHelpText>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contract_Fee_Detail__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Acquisition rate charged to client for this change</inlineHelpText>
        <label>Contract Fee Detail</label>
        <referenceTo>Contract_Fee_Detail__c</referenceTo>
        <relationshipLabel>Subscription Orders</relationshipLabel>
        <relationshipName>Subscription_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <description>This is the date that the Subscription Order was approved. It is populated automatically when the Status field is set to approved. Subscription Orders cannot be edited once they&apos;ve been approved.</description>
        <inlineHelpText>This is the date that the Subscription Order was approved. It is populated automatically when the Status field is set to approved. Subscription Orders cannot be edited once they&apos;ve been approved.</inlineHelpText>
        <label>Effective Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Transfer</fullName>
                </value>
                <value>
                    <fullName>Cancellation</fullName>
                </value>
                <value>
                    <fullName>Shared Solar System Update</fullName>
                </value>
                <value>
                    <fullName>Resize</fullName>
                </value>
                <value>
                    <fullName>Initial</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Subscription Order</label>
    <nameField>
        <displayFormat>SO-{00000}</displayFormat>
        <label>Subscription Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscription Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Utility_Account_Subscription__c.object
<CustomObject>
    <fields>
        <fullName>Shared_Solar_System__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the SSS on the Opportunity when the UAS was created. The SSS on an existing UAS should never be changed.</description>
        <inlineHelpText>This is the SSS on the Opportunity when the UAS was created. The SSS on an existing UAS should never be changed.</inlineHelpText>
        <label>Shared Solar System</label>
        <referenceTo>Shared_Solar_System__c</referenceTo>
        <relationshipLabel>Utility Account Subscriptions</relationshipLabel>
        <relationshipName>Utility_Account_Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Utility Account Subscription</label>
    <nameField>
        <label>Utility Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Account Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/CS_Services_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Acquisition &amp; Management</fullName>
    </customValue>
    <customValue>
        <fullName>Management Only</fullName>
    </customValue>
    <customValue>
        <fullName>Acquisition Only</fullName>
    </customValue>
    <masterLabel>CS Services Type</masterLabel>
</GlobalValueSet>

src/classes/ClientInvoicingBatchReconcilerTest.cls
/**
 * Created by PeterYao on 6/2/2021.
 */

@IsTest
public with sharing class ClientInvoicingBatchReconcilerTest {
    @TestSetup
    public static void setupData() {
        SharedSolarSystemHandlerTest.setupData();
        Account account = [SELECT Id FROM Account LIMIT 1];
        Contract contractA = new Contract(
            Name = 'Client Contract A',
            AccountId = account.Id,
            RecordTypeId = Schema.SObjectType.Contract.getRecordTypeInfosByName().get('Client Contract').getRecordTypeId(),
            StartDate = System.today().addYears(-1)
        );
        insert contractA;
        Contract_Fee_Detail__c cfd = new Contract_Fee_Detail__c(
            Contract__c = contractA.Id,
            Fee__c = 0.10,
            Fee_Unit__c = 'per W',
            Acquisition_Type_Reacquisition__c = true,
            Acquisition_Cust_Group_Residential__c = true,
            Acquisition_Channels_BCS_Acquired__c = true,
            Acquisition_Channels_Non_BCS_Acquired__c = true,
            Acquisition_Sizing_Type_Upsizing__c = true,
            Acquisition_Cust_Group_Not_Specified__c = true,
            Approval_Status__c = 'Approved'
        );
        insert cfd;

        List<Shared_Solar_System__c> sharedSolarSystems = [
            SELECT Id, (SELECT Id FROM Opportunities__r LIMIT 1)
            FROM Shared_Solar_System__c
            ORDER BY Name
        ];

        List<Client_Contract__c> clientContracts = new List<Client_Contract__c>();
        for (Shared_Solar_System__c sss : sharedSolarSystems) {
            clientContracts.add(new Client_Contract__c(
                Shared_Solar_System__c = sss.Id,
                Contract__c = contractA.Id,
                CS_Services_Type__c = 'Acquisition & Management',
                Effective_Date__c = System.today(),
                End_Date__c = System.today().addYears(1)
            ));
        }
        insert clientContracts;
        sharedSolarSystems[0].Reacquisition_Start_Date__c = System.today().addYears(-1);
        update sharedSolarSystems[0];

        Utility_Account_Subscription__c uas = [
            SELECT Id, Opportunity__c, Opportunity__r.AccountId
            FROM Utility_Account_Subscription__c
            WHERE Opportunity__c = :sharedSolarSystems[0].Opportunities__r[0].Id
            LIMIT 1
        ];

        Subscription_Order__c so = new Subscription_Order__c(
            Effective_Date__c = System.today(),
            Type__c = 'Initial',
            Utility_Account_Subscription__c = uas.Id,
            New_Annual_kWh__c = 4800,
            Previous_Annual_kwh__c = 0
        );
        // so2 should have a Client Invoicing Type of Transfer, which will make Client Invoicing Fee $0, which we should not waive
        Subscription_Order__c so2 = new Subscription_Order__c(
            Effective_Date__c = System.today(),
            Type__c = 'Transfer',
            Utility_Account_Subscription__c = uas.Id,
            New_Annual_kWh__c = 5000,
            Previous_Annual_kwh__c = 4800
        );
        ContractRepository.clientContracts = null;
        ContractRepository.contractToFeeDetailMap = null;
        insert new List<Subscription_Order__c>{so, so2};
    }

    @IsTest
    private static void systemTest() {
        Subscription_Order__c subscriptionOrderShouldNotHaveCFD = [
            SELECT Contract_Fee_Detail__c
            FROM Subscription_Order__c
            WHERE Contract_Fee_Detail__c = NULL
            LIMIT 1
        ];
        Subscription_Order__c subscriptionOrderShouldHaveCFD = [
            SELECT Contract_Fee_Detail__c
            FROM Subscription_Order__c
            WHERE Contract_Fee_Detail__c != NULL
            LIMIT 1
        ];
        subscriptionOrderShouldNotHaveCFD.Contract_Fee_Detail__c = subscriptionOrderShouldHaveCFD.Contract_Fee_Detail__c;
        subscriptionOrderShouldHaveCFD.Contract_Fee_Detail__c = null;
        update new List<Subscription_Order__c>{subscriptionOrderShouldHaveCFD, subscriptionOrderShouldNotHaveCFD};

        Test.startTest();
        new ClientInvoicingBatchReconciler().execute(null);
        Test.stopTest();
        List<Error_Log__c> errorLogs = [
            SELECT Message__c
            FROM Error_Log__c
            WHERE Method__c = 'setSubscriptionOrderAcquisitionFee'
            AND Severity__c = :Logger.WARN
        ];
        System.assertEquals(1, errorLogs.size(), 'Expected one warning about SOs with the wrong CFD');
        System.assert(errorLogs[0].Message__c.contains(subscriptionOrderShouldHaveCFD.Id + ' has CFD: null but should have'),
            'BatchReconciler should have found subscriptionOrderShouldHaveCFD to have a null CFD');
        System.assert(errorLogs[0].Message__c.contains(subscriptionOrderShouldNotHaveCFD.Id + ' has CFD: ' + subscriptionOrderShouldNotHaveCFD.Contract_Fee_Detail__c + ' but should have'),
            'BatchReconciler should have found subscriptionOrderShouldNotHaveCFD to have a CFD when it should not');
    }
}