src/objects/Client_Invoicing_Memo__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Contract_Fee_Detail__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Used to calculate Utilization Adjustments</inlineHelpText>
        <label>Contract Fee Detail</label>
        <referenceTo>Contract_Fee_Detail__c</referenceTo>
        <relationshipLabel>Client Invoicing Memos</relationshipLabel>
        <relationshipName>Client_Invoicing_Memos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Production_Detail__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Used to calculate Utilization Adjustments</inlineHelpText>
        <label>Production Detail</label>
        <referenceTo>Transfer_Part__c</referenceTo>
        <relationshipLabel>Client Invoicing Memos</relationshipLabel>
        <relationshipName>Client_Invoicing_Memos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shared_Solar_System__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Used for Utilization Adjustments to Management Fees, populated by the Utilization Adjustment flow</inlineHelpText>
        <label>Shared Solar System</label>
        <referenceTo>Shared_Solar_System__c</referenceTo>
        <relationshipLabel>Client Invoicing Memos</relationshipLabel>
        <relationshipName>Client_Invoicing_Memos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Waived Acquisition / Reacquisition Fee</fullName>
                    <default>true</default>
                    <label>Waived Acquisition / Reacquisition Fee</label>
                </value>
                <value>
                    <fullName>Adjustment for Resize Fee</fullName>
                </value>
                <value>
                    <fullName>Utilization Adjustment to Management Fee</fullName>
                </value>
                <value>
                    <fullName>Manual Adjustment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Client Invoicing Memo</label>
    <nameField>
        <displayFormat>CIM-{000000}</displayFormat>
        <label>Client Invoicing Memo Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Invoicing Memos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contract_Fee_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Contract__c</fullName>
        <inlineHelpText>The related Client Contract</inlineHelpText>
        <label>Contract</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Contract Fee Detail must be related to a contract with the record type = Client Contract</errorMessage>
            <filterItems>
                <field>Contract.RecordTypeId</field>
                <operation>equals</operation>
                <value>Client Contract</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Contract Fee Detail</relationshipLabel>
        <relationshipName>Contract_Fee_Detail</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Fee_Unit__c</fullName>
        <inlineHelpText>See Fee ($) field for numerator. Ie $/W, $/MW (implicitly, per year)</inlineHelpText>
        <label>Fee Unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>per W</fullName>
                </value>
                <value>
                    <fullName>per MW</fullName>
                </value>
                <value>
                    <fullName>per project</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Fee__c</fullName>
        <inlineHelpText>The annual $ value of the fee, see &quot;Fee Unit&quot; field for the denominator ($/W year or $/MW year or $/project year)</inlineHelpText>
        <label>Fee ($)</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Shared_Solar_System__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Used to make this CFD specific to a SSS when the ClientInvoicingFeeAssignmentService assigns a CFD to a Subscription Order when the SO is approved.</inlineHelpText>
        <label>Shared Solar System</label>
        <referenceTo>Shared_Solar_System__c</referenceTo>
        <relationshipLabel>Contract Fee Detail</relationshipLabel>
        <relationshipName>Contract_Fee_Detail</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Utilization_Adjustment_Amount__c</fullName>
        <inlineHelpText>For every 1% decrease in utilization, the management fee will decrease by this $ amount.</inlineHelpText>
        <label>Utilization Adjustment Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Utilization_Adjustment_Floor__c</fullName>
        <inlineHelpText>Utilization adjustments cannot be more than X percent of the management fee in a given month</inlineHelpText>
        <label>Utilization Adjustment Floor</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Utilization_Adjustment_Multiplier__c</fullName>
        <inlineHelpText>For every 1% decrease in utilization, the management fee will decrease by this percent.</inlineHelpText>
        <label>Utilization Adjustment Multiplier</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Utilization_Adjustment_Type__c</fullName>
        <label>Utilization Adjustment Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Multiplier (%)</fullName>
                </value>
                <value>
                    <fullName>Amount ($)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Contract Fee Detail</label>
    <nameField>
        <displayFormat>CFD-{000000}</displayFormat>
        <label>Contract Fee Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Fee Detail</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Production__c.object
<CustomObject>
    <fields>
        <fullName>Shared_Solar_System__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Shared Solar System</label>
        <referenceTo>Shared_Solar_System__c</referenceTo>
        <relationshipLabel>Production</relationshipLabel>
        <relationshipName>Production</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Production</label>
    <nameField>
        <label>Production Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Production</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Shared_Solar_System__c.object
<CustomObject
     >
    <articleTypeChannelDisplay n1:nil="true" />
    <customSettingsType n1:nil="true" />
    <description n1:nil="true" />
    <eventType n1:nil="true" />
    <fields>
        <fullName>Client_Management_Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The field points to the same contract even if there is only one.</description>
        <inlineHelpText>Set automatically when a Client Contract is effective, and used for Client Invoicing. It could be the same as the Client Acquisition Contract.</inlineHelpText>
        <label>Client Management Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Client Management Contract</relationshipLabel>
        <relationshipName>Shared_Solar_Systems1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Serviced_Capacity__c</fullName>
        <formula>IF(
NOT (ISPICKVAL(Billing_Anchors__c,&quot;Bluewave&quot;)),
Total_System_Size_kWh_DC__c - Anchor_Capacity_Reserved__c,
Total_System_Size_kWh_DC__c 
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>If BlueWave services the anchor, anchor capacity is included, if not, the total size of the project minus the anchor capacity</inlineHelpText>
        <label>Serviced Capacity</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <gender n1:nil="true" />
    <household>false</household>
    <label>Shared Solar System</label>
    <nameField>
        <label>Shared Solar System Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shared Solar Systems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <startsWith n1:nil="true" />
</CustomObject>

src/objects/Transfer__c.object
<CustomObject>
    <fields>
        <fullName>Bill_Period__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The Transfer object is looking up to the Bill Period object.</description>
        <label>Bill Period</label>
        <referenceTo>Bill_Period__c</referenceTo>
        <relationshipLabel>Transfers</relationshipLabel>
        <relationshipName>Transfers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shared_Solar_System__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Transfer object is looking up to the SSS object.</description>
        <label>Shared Solar System</label>
        <referenceTo>Shared_Solar_System__c</referenceTo>
        <relationshipLabel>Transfers</relationshipLabel>
        <relationshipName>Transfers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Transfer</label>
    <nameField>
        <label>Transfer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transfers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Transfer_Part__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Change_in_Utilization__c</fullName>
        <formula>IF(ISPICKVAL(Type__c,&quot;Transfer&quot;),
IF(Production__r.Billing_Method__c == &apos;kWh&apos;,
IF(
AND(
ISPICKVAL(Transfer__r.Transfer_Type__c,&apos;Main&apos;)
,kWh_Amount__c != 0
),
IF(kWh_Amount__c &lt; 0, -1, 1)*(ABS(kWh_Amount__c) - ABS(Production__r.Production_kWh__c)) /Production__r.Production_kWh__c,
IF(
kWh_Amount__c != 0,
kWh_Amount__c /Production__r.Production_kWh__c,
0
)
),
IF(
AND(
ISPICKVAL(Transfer__r.Transfer_Type__c,&apos;Main&apos;)
,Amount__c != 0
),
IF(Amount__c &lt; 0, -1, 1)*(ABS(Amount__c) - ABS(Production__r.Credits_Available_for_Allocation__c)) /Production__r.Credits_Available_for_Allocation__c,
IF(
Amount__c != 0,
Amount__c /Production__r.Credits_Available_for_Allocation__c,
0
)
)
)
,
0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The % effect of a detail record on the utilization of the parent production record. The difference between 100% utilization and reality. When all credits have been transferred, the sum will = 0. If credits are still outstanding, the sum will be negative.</inlineHelpText>
        <label>Change in Utilization</label>
        <precision>18</precision>
        <scale>9</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Production__c</fullName>
        <description>A master-detail relationship from Transfer Parts up to Production</description>
        <label>Production</label>
        <referenceTo>Production__c</referenceTo>
        <relationshipLabel>Production Detail</relationshipLabel>
        <relationshipName>Transfer_Parts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Transfer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>A lookup relationship from Transfer Parts up to Transfer.</description>
        <label>Transfer</label>
        <referenceTo>Transfer__c</referenceTo>
        <relationshipName>Transfer_Parts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Transfer</fullName>
                </value>
                <value>
                    <fullName>Fee</fullName>
                </value>
                <value>
                    <fullName>Incentive Payment</fullName>
                </value>
                <value>
                    <fullName>Unsubscribed Credits</fullName>
                </value>
                <value>
                    <fullName>Customer Savings</fullName>
                </value>
                <value>
                    <fullName>Payment</fullName>
                </value>
                <value>
                    <fullName>Unserviced</fullName>
                </value>
                <value>
                    <fullName>Bill</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Production Detail</label>
    <nameField>
        <label>Transfer Parts Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Production Detail</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ClientInvoicingUtilizationService.cls
/**
 * Created by peteryao on 8/30/20.
 * Tested By: ClientInvoicingUtilizationServiceTest
 */

public without sharing class ClientInvoicingUtilizationService {
    private static ContractFeeDetailSelector cfdSelector = new ContractFeeDetailSelector();
    private static ProductionDetailSelector productionDetailSelector = new ProductionDetailSelector();
    @TestVisible
    private static fflib_SObjectUnitOfWork uow = new fflib_SObjectUnitOfWork(
        new List<SObjectType>{Client_Invoicing_Memo__c.SObjectType}
    );

    public List<Client_Invoicing_Memo__c> createMemosForUtilizationAdjustments() {
        uow.registerWork(new Logger());
        List<Contract_Fee_Detail__c> utilizationCFDs = cfdSelector.getContractDetailsWithUtilizationAdjustment();
        MultiMap cfdsByContract = CollectionUtil.multiMapByField(utilizationCFDs, Contract_Fee_Detail__c.Contract__c);
        List<Transfer_Part__c> productionDetailsWithUtilizationChanges =
            productionDetailSelector.getRecentUtilizationChangesByContract(CollectionUtil.toIds(cfdsByContract.keySet()));

        List<Client_Invoicing_Memo__c> memosToInsert = new List<Client_Invoicing_Memo__c>();
        for (Transfer_Part__c productionDetail : productionDetailsWithUtilizationChanges) {
            if (!productionDetail.Client_Invoicing_Memos__r.isEmpty()) {
                // Skip it since we've already generated the utilization fee for this production detail
                continue;
            }
            Contract_Fee_Detail__c cfd = getCfdForProductionDetail(cfdsByContract, productionDetail);
            if (cfd == null) {
                // We already logged an error, we should skip this one too
                continue;
            }
            memosToInsert.add(new UtilizationFeeInput(cfd, productionDetail).registerClientInvoicingMemo());
        }
        uow.commitWork();
        return memosToInsert;
    }

    private Contract_Fee_Detail__c getCfdForProductionDetail(MultiMap cfdsByContract, Transfer_Part__c productionDetail) {
        List<Contract_Fee_Detail__c> contractFeeDetails = new List<Contract_Fee_Detail__c>();
        CollectionUtil.toTypedList(cfdsByContract.getValues(productionDetail.Production__r.Shared_Solar_System__r.Client_Management_Contract__c), contractFeeDetails);
        if (contractFeeDetails.size() != 1) {
            Logger.logLater(
                'ClientInvoicingUtilizationService',
                'createMemosForUtilizationAdjustments',
                'Skipping Production Detail because of unexpected contract fee details : ' + productionDetail.Id + '\n' + contractFeeDetails,
                Logger.ERROR
            );
            return null;
        }
        Contract_Fee_Detail__c cfd = contractFeeDetails[0];
        return cfd;
    }

    @TestVisible
    private class UtilizationFeeInput {
        private Decimal changeInUtilization;
        private String utilizationAdjustmentType;
        private Decimal managementFee;
        private String managementFeeUnits;
        private Decimal monthlyManagementFeeDollars;
        private Decimal utilizationAdjustmentMultiplier;
        private Decimal utilizationAdjustmentAmount;
        private Decimal utilizationAdjustmentFloor;
        private Decimal floorDollars;
        private Decimal servicedCapacity;
        private Id contractFeeDetailId;
        private Id productionDetailId;
        private Id sharedSolarSystemId;
        private String sharedSolarSystemName;
        private Decimal utilizationFee;
        private Date billDate;

        @TestVisible
        private UtilizationFeeInput(Contract_Fee_Detail__c cfd, Transfer_Part__c productionDetail) {
            changeInUtilization = productionDetail.Change_in_Utilization__c/100;
            utilizationAdjustmentType = cfd.Utilization_Adjustment_Type__c;
            managementFee = cfd.Fee__c;
            managementFeeUnits = cfd.Fee_Unit__c;
            utilizationAdjustmentMultiplier = cfd.Utilization_Adjustment_Multiplier__c; // a true multiplier, not a percent
            utilizationAdjustmentAmount = cfd.Utilization_Adjustment_Amount__c;
            if (cfd.Utilization_Adjustment_Floor__c != null) {
                utilizationAdjustmentFloor = cfd.Utilization_Adjustment_Floor__c/100;
            }
            servicedCapacity = productionDetail.Production__r.Shared_Solar_System__r.Serviced_Capacity__c;
            contractFeeDetailId = cfd.Id;
            productionDetailId = productionDetail.Id;
            sharedSolarSystemId = productionDetail.Production__r.Shared_Solar_System__c;
            sharedSolarSystemName = productionDetail.Production__r.Shared_Solar_System__r.Name;
            billDate = productionDetail.Transfer__r.Bill_Period__r.Bill_Date__c;

            switch on managementFeeUnits {
                when 'per W' {
                    monthlyManagementFeeDollars = managementFee * 1000 * servicedCapacity / 12; //  $/W * 1000W/kW * kW = $
                } when 'per MW' {
                    monthlyManagementFeeDollars = managementFee / 1000 * servicedCapacity / 12; //  $/MW * 1MW/1000kW * kW = $
                } when 'per project' {
                    monthlyManagementFeeDollars = managementFee * servicedCapacity / 12 ;
                } when else {
                    throw new Util.BWException('UtilizationFeeInput, fee Units not recognized for CFD: ' + JSON.serialize(cfd));
                }
            }
            monthlyManagementFeeDollars = monthlyManagementFeeDollars.setScale(2);
            if (utilizationAdjustmentFloor != null) {
                floorDollars = -(utilizationAdjustmentFloor * monthlyManagementFeeDollars).setScale(2);
            }

            utilizationFee = getUtilizationFee().setScale(2);
        }

        @TestVisible
        private Decimal getUtilizationFee() {
            Decimal utilizationFee = 0;
            switch on utilizationAdjustmentType {
                when 'Multiplier (%)' {
                    utilizationFee = changeInUtilization * monthlyManagementFeeDollars * utilizationAdjustmentMultiplier;
                } when 'Amount ($)' {
                    // Since for every 1% in utilization change, we decrease by the utilization adjustment amount, we
                    // need to bring the changeInUtilization (e.g. .02 back up to a percent)
                    utilizationFee = changeInUtilization * 100 * utilizationAdjustmentAmount;
                } when else {
                    throw new Util.BWException('UtilizationFeeService, Utilization Adjustment Type not recognized: ' + utilizationAdjustmentType);
                }
            }
            if (utilizationAdjustmentFloor != null) {
                utilizationFee = Math.max(floorDollars, utilizationFee);
            }
            return utilizationFee;
        }

        private Client_Invoicing_Memo__c registerClientInvoicingMemo() {
            Client_Invoicing_Memo__c memo = new Client_Invoicing_Memo__c(
                Shared_Solar_System__c = sharedSolarSystemId,
                Production_Detail__c = productionDetailId,
                Contract_Fee_Detail__c = contractFeeDetailId,
                Amount__c = utilizationFee,
                Type__c = 'Utilization Adjustment to Management Fee',
                Effective_Date__c = billDate,
                Details__c = JSON.serializePretty(this)
            );
            uow.registerNew(memo);
            return memo;
        }
    }
}