src/objects/Client_Allocation_Schedule_Subscription__c.object
<CustomObject>
    <fields>
        <fullName>Allocation_Schedule_Subscription__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Related to Allocation Schedule Subscription object, populated via code</inlineHelpText>
        <label>Allocation Schedule Subscription</label>
        <referenceTo>Schedule_Z_Subscription__c</referenceTo>
        <relationshipLabel>Client Allocation Schedule Subscriptions</relationshipLabel>
        <relationshipName>Client_Allocation_Schedule_Subscriptions</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Allocation_Schedule__c</fullName>
        <description>A master-detail relationship up to allocation schedule</description>
        <label>Allocation Schedule</label>
        <referenceTo>Schedule_Z__c</referenceTo>
        <relationshipLabel>Client Allocation Schedule Subscriptions</relationshipLabel>
        <relationshipName>Client_Allocation_Schedule_Subscriptions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Client_Utility_Account_Subscription__c</fullName>
        <description>A master-detail relationship up to Client Utility Account Subscription</description>
        <label>Client Utility Account Subscription</label>
        <referenceTo>Client_Utility_Account_Subscription__c</referenceTo>
        <relationshipLabel>Client Allocation Schedule Subscriptions</relationshipLabel>
        <relationshipName>Client_Allocation_Schedule_Subscriptions</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Customer_Subscription_kW_DC__c</fullName>
        <formula>Allocation_Schedule_Subscription__r.Customer_Subscription_kW_DC__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The kW DC value of the customer&apos;s subscription</inlineHelpText>
        <label>Customer Subscription kW DC</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <label>Client Allocation Schedule Subscription</label>
    <nameField>
        <label>Client Allocation Schedule  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Client Allocation Schedule Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Client_Utility_Account_Subscription__c.object
<CustomObject>
    <fields>
        <fullName>Annual_Cost_of_Electricity_Future__c</fullName>
        <formula>IF(
$CustomMetadata.Custom_Feature_Enablement__mdt.Subscription_Orders.Feature_is_Enabled__c=true
,
Utility_Account_Subscription__r.Annual_Cost_Future_Rollup__c
,
Utility_Account_Subscription__r.Subscribed_Annual_Cost_of_Electricity__c
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Annual Cost of Electricity (Future)</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Annual_kWh_Subscription_Future__c</fullName>
        <formula>IF(
$CustomMetadata.Custom_Feature_Enablement__mdt.Subscription_Orders.Feature_is_Enabled__c=true
,
 Utility_Account_Subscription__r.Annual_kWh_Subscription_Future_Rollup__c
,
Utility_Account_Subscription__r.Annual_kwh_subscription_future__c
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Annual kWh Subscription (Future)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <description>Opportunity Name</description>
        <formula>Utility_Account_Subscription__r.Opportunity__r.Name</formula>
        <label>Customer</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Shared_Solar_System__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Shared Solar System</label>
        <referenceTo>Shared_Solar_System__c</referenceTo>
        <relationshipLabel>Client Utility Account Subscriptions</relationshipLabel>
        <relationshipName>Client_Utility_Account_Subscriptions</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
</CustomObject>

force-app/main/default/objects/Client_Utility_Account_Subscription__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <formula>Utility_Account_Subscription__r.Opportunity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Customer Name</inlineHelpText>
    <label>Opportunity</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Client_Utility_Account_Subscription__c/fields/Utility_Account_Subscription__c.field-meta.xml
<CustomField>
    <fullName>Utility_Account_Subscription__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Related to Utility Account Subscription object, populated via code</inlineHelpText>
    <label>Utility Account Subscription</label>
    <referenceTo>Utility_Account_Subscription__c</referenceTo>
    <relationshipLabel>Client Utility Account Subscriptions</relationshipLabel>
    <relationshipName>Client_Utility_Account_Subscriptions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/objects/Shared_Solar_System__c.object
<CustomObject
     >
    <articleTypeChannelDisplay n1:nil="true" />
    <customSettingsType n1:nil="true" />
    <description n1:nil="true" />
    <eventType n1:nil="true" />
    <gender n1:nil="true" />
    <household>false</household>
    <label>Shared Solar System</label>
    <nameField>
        <label>Shared Solar System Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shared Solar Systems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <startsWith n1:nil="true" />
</CustomObject>

src/objects/Utility_Account_Subscription__c.object
<CustomObject>
    <fields>
        <fullName>Annual_kwh_subscription_future__c</fullName>
        <description>Used for SMART CS contracts. It is the counterpart to annual cost of electricity field, and is used to calculate the future customer subscription kW DC field for Opportunities with the SMART CS contract. It is populated manually.</description>
        <inlineHelpText>Used for SMART CS contracts. It is the counterpart to annual cost of electricity field, and is used to calculate the future customer subscription kW DC field for Opportunities with the SMART CS contract. It is populated manually.</inlineHelpText>
        <label>xxAnnual kWh Subscription (Future)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Customer_Subscription_KW_DC__c</fullName>
        <description>Made the system name logic so that Allocation Schedule customers will not change to unrounded values</description>
        <formula>IF(

$CustomMetadata.Custom_Feature_Enablement__mdt.Subscription_Orders.Feature_is_Enabled__c=true
,
Future_Customer_Subscription_KWDC_Rollup__c
,

IF(AND(TEXT(Opportunity__r.Product__r.Customer_Subscription_Type__c)=&apos;kWh&apos;,Annual_kwh_subscription_future__c&gt;0),Annual_kwh_subscription_future__c/Opportunity__r.Shared_Solar_System__r.Expected_Yield_kWh_kW__c, 
IF( UAS_Number__c &gt; 1 , 

Subscribed_Annual_Cost_of_Electricity__c / Opportunity__r.NMC_Value__c / Opportunity__r.Shared_Solar_System__r.Expected_Yield_kWh_kW__c, 

IF( 

OR(Auto_Unround__c = TRUE , AND(UAS_Number__c = 1 , calculated_annual_cost_of_electricity__c != Subscribed_Annual_Cost_of_Electricity__c )), 

Subscribed_Annual_Cost_of_Electricity__c / Opportunity__r.NMC_Value__c/ Opportunity__r.Shared_Solar_System__r.Expected_Yield_kWh_kW__c, 


IF( 

OR(AND(UAS_Number__c = 1 , calculated_annual_cost_of_electricity__c = Subscribed_Annual_Cost_of_Electricity__c ), Opportunity__r.Shared_Solar_System_Name__c = &apos;Fairhaven Mill Rd&apos;, Opportunity__r.Shared_Solar_System_Name__c = &apos;Oxford Clara Barton&apos;), 

Round(( Subscribed_Annual_Cost_of_Electricity__c / Opportunity__r.NMC_Value__c/ Opportunity__r.Shared_Solar_System__r.Expected_Yield_kWh_kW__c) * 4, 0)/4,0))))
)</formula>
        <inlineHelpText>Dynamic Subscription</inlineHelpText>
        <label>Future Customer Subscription (KW DC)</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Utility Account Subscriptions</relationshipLabel>
        <relationshipName>Utility_Account_Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shared_Solar_System_Name__c</fullName>
        <formula>IF(
$CustomMetadata.Custom_Feature_Enablement__mdt.Subscription_Orders.Feature_is_Enabled__c=true,
Shared_Solar_System__r.Name,
Opportunity__r.Shared_Solar_System_Name__c
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Shared Solar System Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Shared_Solar_System__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the SSS on the Opportunity when the UAS was created. The SSS on an existing UAS should never be changed.</description>
        <inlineHelpText>This is the SSS on the Opportunity when the UAS was created. The SSS on an existing UAS should never be changed.</inlineHelpText>
        <label>Shared Solar System</label>
        <referenceTo>Shared_Solar_System__c</referenceTo>
        <relationshipLabel>Utility Account Subscriptions</relationshipLabel>
        <relationshipName>Utility_Account_Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Utility Account Subscription</label>
    <nameField>
        <label>Utility Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Account Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ClientReportObjectSelector.cls
/**
 * Created by SarahRenfro on 10/7/2019.
 *
 * Tested By: ClientReportingServiceTest
 */

public with sharing class ClientReportObjectSelector {
    @SuppressWarnings('PMD.ApexCRUDViolation')
    public static List<Client_Utility_Account_Subscription__c> getClientUASesByUASIds(Set<Id> uasIds) {
        return [
            SELECT Id, Customer__c, Annual_Cost_of_Electricity_Future__c, Annual_kWh_Subscription_Future__c, Shared_Solar_System__c, Utility_Account_Subscription__c
            FROM Client_Utility_Account_Subscription__c
            WHERE Utility_Account_Subscription__c IN :uasIds
        ];
    }

    @SuppressWarnings('PMD.ApexCRUDViolation')
    public static List<Client_Utility_Account_Subscription__c> getClientUASesByOppIds(Set<Id> oppIds) {
        return [
            SELECT Id, Customer__c, Annual_Cost_of_Electricity_Future__c, Annual_kWh_Subscription_Future__c,
                Shared_Solar_System__c, Utility_Account_Subscription__c, Utility_Account_Subscription__r.Opportunity__c,
                Utility_Account_Subscription__r.Shared_Solar_System_Name__c
            FROM Client_Utility_Account_Subscription__c
            WHERE Utility_Account_Subscription__r.Opportunity__c IN :oppIds
        ];
    }

    @SuppressWarnings('PMD.ApexCRUDViolation')
    public static List<Client_Allocation_Schedule_Subscription__c> getClientALSSBySZSIds(Set<Id> szsIds) {
        return [
            SELECT Id, Client_Utility_Account_Subscription__c, Customer_Subscription_kW_DC__c, Allocation_Schedule__c
            FROM Client_Allocation_Schedule_Subscription__c
            WHERE Allocation_Schedule_Subscription__c IN :szsIds
        ];
    }



}