src/objects/Client_Invoicing_Memo__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Shared_Solar_System__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Used for Utilization Adjustments to Management Fees, populated by the Utilization Adjustment flow</inlineHelpText>
        <label>Shared Solar System</label>
        <referenceTo>Shared_Solar_System__c</referenceTo>
        <relationshipLabel>Client Invoicing Memos</relationshipLabel>
        <relationshipName>Client_Invoicing_Memos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subscription_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subscription Order</label>
        <referenceTo>Subscription_Order__c</referenceTo>
        <relationshipLabel>Client Invoicing Memos</relationshipLabel>
        <relationshipName>Client_Invoicing_Memos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Waived Acquisition / Reacquisition Fee</fullName>
                    <default>true</default>
                    <label>Waived Acquisition / Reacquisition Fee</label>
                </value>
                <value>
                    <fullName>Adjustment for Resize Fee</fullName>
                </value>
                <value>
                    <fullName>Utilization Adjustment to Management Fee</fullName>
                </value>
                <value>
                    <fullName>Manual Adjustment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Client Invoicing Memo</label>
    <nameField>
        <displayFormat>CIM-{000000}</displayFormat>
        <label>Client Invoicing Memo Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Invoicing Memos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Shared_Solar_System__c.object
<CustomObject
     >
    <articleTypeChannelDisplay n1:nil="true" />
    <customSettingsType n1:nil="true" />
    <description n1:nil="true" />
    <eventType n1:nil="true" />
    <gender n1:nil="true" />
    <household>false</household>
    <label>Shared Solar System</label>
    <nameField>
        <label>Shared Solar System Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shared Solar Systems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <startsWith n1:nil="true" />
</CustomObject>

src/objects/Subscription_Order__c.object
<CustomObject>
    <fields>
        <fullName>Approved_Change_in_Subscription__c</fullName>
        <description>This is the rounded net change in kW DC. When SO is approved, field is stamped with &apos;Calculated Change in Subscription kW DC.&apos; If Type = &apos;SSS Update,&apos; field is stamped with value of &apos;System Change in kW Subscription&apos; - &apos;Previous kW Subscription. It&apos;s important to have a static value for tracking purposes, and to use in rollup summary fields.</description>
        <inlineHelpText>This is the rounded net change in kW DC. When SO is approved, field is stamped with &apos;Calculated Change in Subscription kW DC.&apos; If Type = &apos;SSS Update,&apos; field is stamped with value of &apos;System Change in kW Subscription&apos; - &apos;Previous kW Subscription.</inlineHelpText>
        <label>Approved Change in Subscription (KW DC)</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <description>This is the date that the Subscription Order was approved. It is populated automatically when the Status field is set to approved. Subscription Orders cannot be edited once they&apos;ve been approved.</description>
        <inlineHelpText>This is the date that the Subscription Order was approved. It is populated automatically when the Status field is set to approved. Subscription Orders cannot be edited once they&apos;ve been approved.</inlineHelpText>
        <label>Effective Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Transfer</fullName>
                </value>
                <value>
                    <fullName>Cancellation</fullName>
                </value>
                <value>
                    <fullName>Shared Solar System Update</fullName>
                </value>
                <value>
                    <fullName>Resize</fullName>
                </value>
                <value>
                    <fullName>Initial</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Utility_Account_Subscription__c</fullName>
        <label>Utility Account Subscription</label>
        <referenceTo>Utility_Account_Subscription__c</referenceTo>
        <relationshipLabel>Subscription Orders</relationshipLabel>
        <relationshipName>Subscription_Orders</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Subscription Order</label>
    <nameField>
        <displayFormat>SO-{00000}</displayFormat>
        <label>Subscription Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscription Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Utility_Account_Log__c.object
<CustomObject>
    <label>Utility Account Log</label>
    <nameField>
        <label>Utility Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Account Logs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Utility_Account_Subscription__c.object
<CustomObject>
    <fields>
        <fullName>Shared_Solar_System__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the SSS on the Opportunity when the UAS was created. The SSS on an existing UAS should never be changed.</description>
        <inlineHelpText>This is the SSS on the Opportunity when the UAS was created. The SSS on an existing UAS should never be changed.</inlineHelpText>
        <label>Shared Solar System</label>
        <referenceTo>Shared_Solar_System__c</referenceTo>
        <relationshipLabel>Utility Account Subscriptions</relationshipLabel>
        <relationshipName>Utility_Account_Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Utility_Account_Log__c</fullName>
        <inlineHelpText>The related UAL</inlineHelpText>
        <label>Utility Account Log</label>
        <referenceTo>Utility_Account_Log__c</referenceTo>
        <relationshipLabel>Utility Account Subscriptions</relationshipLabel>
        <relationshipName>Utility_Account_Subscriptions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Utility Account Subscription</label>
    <nameField>
        <label>Utility Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Account Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/ClientInvoicingMemoSelectorTest.cls
@IsTest
public with sharing class ClientInvoicingMemoSelectorTest {
    @testSetup public static void setupTestData(){
        Util.disableAllTriggers();
        Shared_Solar_System__c sssOne = new Shared_Solar_System__c(Name = 'Test SSS One');
        Shared_Solar_System__c sssTwo = new Shared_Solar_System__c(Name = 'Test SSS Two');
        insert new List<Shared_Solar_System__c>{sssOne,sssTwo};

        Utility_Account_Log__c ualOne = new Utility_Account_Log__c(Name = '000124');
        insert ualOne;

        Utility_Account_Subscription__c uasOne = new Utility_Account_Subscription__c(
            Name = '000123',
            Shared_Solar_System__c = sssOne.Id,
            Utility_Account_Log__c = ualOne.Id
        );
        Utility_Account_Subscription__c uasTwo = new Utility_Account_Subscription__c(
            Name = '000123',
            Shared_Solar_System__c = sssTwo.Id,
            Utility_Account_Log__c = ualOne.Id
        );
        insert new List<Utility_Account_Subscription__c>{uasOne,uasTwo};

        Subscription_Order__c orderOne = new Subscription_Order__c(
            Utility_Account_Subscription__c = uasOne.Id,
            Approved_Change_in_Subscription__c = 10
        );
        Subscription_Order__c orderTwo = new Subscription_Order__c(
            Utility_Account_Subscription__c = uasOne.Id,
            Approved_Change_in_Subscription__c = 10
        );
        Subscription_Order__c orderThree = new Subscription_Order__c(
            Utility_Account_Subscription__c = uasTwo.Id,
            Approved_Change_in_Subscription__c = 10
        );
        Subscription_Order__c orderFour = new Subscription_Order__c(
            Utility_Account_Subscription__c = uasTwo.Id,
            Approved_Change_in_Subscription__c = 10
        );
        List<Subscription_Order__c> ordersToInsert = new List<Subscription_Order__c>{
            orderOne, orderTwo, orderThree, orderFour
        };
        insert ordersToInsert;

        List<Client_Invoicing_Memo__c> memosToInsert = new List<Client_Invoicing_Memo__c>();
        for (Subscription_Order__c order : ordersToInsert){
            Client_Invoicing_Memo__c memo = new Client_Invoicing_Memo__c(
                Subscription_Order__c = order.Id,
                Effective_Date__c = System.today(),
                Amount__c = -10,
                Type__c = 'Waived Acquisition / Reacquisition Fee'
            );
            memosToInsert.add(memo);
        }
        insert memosToInsert;
        Util.enableAllTriggers();
    }

    @IsTest
    public static void testGetWaivedFeesBySSS() {
        List<Shared_Solar_System__c> sssList = [
            SELECT Id
            FROM Shared_Solar_System__c
            ORDER BY Name
        ];
        Set<Id> sssIdSet = new Set<Id>();
        for (Shared_Solar_System__c sss : sssList){
            sssIdSet.add(sss.Id);
        }
        System.assert(sssIdSet.size() > 0, 'Expected at least two SSSes in this test but got ' + sssIdSet.size());

        ClientInvoicingMemoSelector selector = new ClientInvoicingMemoSelector();
        MultiMap kwMap = selector.getWaivedFeesBySSS(sssIdSet);

        System.assertEquals(2,kwMap.getValues(sssList[0].Id).size(), 'Expected test setup to create two fee waive CIMs for Test SSS One');
        System.assertEquals(2,kwMap.getValues(sssList[1].Id).size(), 'Expected test setup to create two fee waive CIMs for Test SSS Two');
    }
}