src/objects/Commission_Payment__c.object
<CustomObject>
    <fields>
        <fullName>Amount_Due__c</fullName>
        <label>Amount Due</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Commission_Structure__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Commission Structure</label>
        <referenceTo>Commission_Structure__c</referenceTo>
        <relationshipLabel>Commission Payments</relationshipLabel>
        <relationshipName>Commission_Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Commission Payments</relationshipLabel>
        <relationshipName>Commission_Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Due</fullName>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Commission Payment</label>
    <nameField>
        <label>Commission Payment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Commission Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Commission_Payment__c/fields/Contract_Execution_Amount__c.field-meta.xml
<CustomField>
    <fullName>Contract_Execution_Amount__c</fullName>
    <label>Contract Execution Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Commission_Payment__c/fields/First_Bill_Paid_Amount__c.field-meta.xml
<CustomField>
    <fullName>First_Bill_Paid_Amount__c</fullName>
    <label>First Bill Paid Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Commission_Payment__c/fields/First_Bill_Sent_Amount__c.field-meta.xml
<CustomField>
    <fullName>First_Bill_Sent_Amount__c</fullName>
    <label>First Bill Sent Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/objects/Commission_Structure__c.object
<CustomObject>
    <label>Commission Structure</label>
    <nameField>
        <label>Commission Structure Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Commission Structures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Commission_Structure__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Commission Structure</label>
        <referenceTo>Commission_Structure__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Subscription_Order__c.object
<CustomObject>
    <fields>
        <fullName>Client_Assignment_Agreement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Assignment Agreement contract, populated when the Assignment Agreement on the corresponding Opportunity (or Opportunity&apos;s Contract) is populated or changed</inlineHelpText>
        <label>Client Assignment Agreement</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Subscription Orders</relationshipLabel>
        <relationshipName>Subscription_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Subscription Order</label>
    <nameField>
        <displayFormat>SO-{00000}</displayFormat>
        <label>Subscription Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscription Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription_Order__c/fields/Contract_Close_Commission__c.field-meta.xml
<CustomField>
    <fullName>Contract_Close_Commission__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Contract Close Commission Payment record this Subscription Order is applied to. If no value, this Subscription Order has not been applied to a Commission Payment record yet.</inlineHelpText>
    <label>Contract Close Commission</label>
    <referenceTo>Commission_Payment__c</referenceTo>
    <relationshipLabel>Contract_Close_Subscription_Orders</relationshipLabel>
    <relationshipName>Subscription_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscription_Order__c/fields/Contract_Close_Estimated_Commission__c.field-meta.xml
<CustomField>
    <fullName>Contract_Close_Estimated_Commission__c</fullName>
    <formula>CASE(Utility_Account_Subscription__r.Opportunity__r.Commission_Structure__r.Type__c,
 &quot;Variable by kW&quot;, 
  Utility_Account_Subscription__r.Opportunity__r.Commission_Structure__r.Cents_kW_DC_Up_Front__c * 1000 *  Approved_Change_in_Subscription__c,
 &quot;Fixed by Annual kWh&quot;,
  IF(ISPICKVAL(Type__c, &quot;Initial&quot;), 0, 0),
 0
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Estimated Commission owed to partner on Contract Close based on Approved Change in Subscription and Commission Rate specified on deal Commission Structure</inlineHelpText>
    <label>Contract Close Estimated Commission</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Subscription_Order__c/fields/First_Bill_Paid_Commission__c.field-meta.xml
<CustomField>
    <fullName>First_Bill_Paid_Commission__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>First Bill Paid Commission Payment record this Subscription Order is applied to. If no value, this Subscription Order has not been applied to a Commission Payment record yet.</inlineHelpText>
    <label>First Bill Paid Commission</label>
    <referenceTo>Commission_Payment__c</referenceTo>
    <relationshipLabel>Subscription Orders (First Bill Paid Commission)</relationshipLabel>
    <relationshipName>First_Bill_Paid_Subscription_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscription_Order__c/fields/First_Bill_Paid_Estimated_Commission__c.field-meta.xml
<CustomField>
    <fullName>First_Bill_Paid_Estimated_Commission__c</fullName>
    <formula>CASE(Utility_Account_Subscription__r.Opportunity__r.Commission_Structure__r.Type__c,
 &quot;Variable by kW&quot;, 
  Utility_Account_Subscription__r.Opportunity__r.Commission_Structure__r.Cents_kW_DC_First_Bill_Paid__c * 1000 * Approved_Change_in_Subscription__c,
 &quot;Fixed by Annual kWh&quot;,
  IF(ISPICKVAL(Type__c, &quot;Initial&quot;), 0, 0),
 0
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Estimated Commission owed to partner on First Bill Paid based on Approved Change in Subscription and Commission Rate specified on deal Commission Structure</inlineHelpText>
    <label>First Bill Paid Estimated Commission</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Subscription_Order__c/fields/First_Bill_Sent_Commission__c.field-meta.xml
<CustomField>
    <fullName>First_Bill_Sent_Commission__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>First Bill Sent Commission Payment record this Subscription Order is applied to. If no value, this Subscription Order has not been applied to a Commission Payment record yet.</inlineHelpText>
    <label>First Bill Sent Commission</label>
    <referenceTo>Commission_Payment__c</referenceTo>
    <relationshipLabel>Subscription Orders (First Bill Sent Commission)</relationshipLabel>
    <relationshipName>First_Bill_Subscription_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscription_Order__c/fields/First_Bill_Sent_Estimated_Commission__c.field-meta.xml
<CustomField>
    <fullName>First_Bill_Sent_Estimated_Commission__c</fullName>
    <formula>CASE(Utility_Account_Subscription__r.Opportunity__r.Commission_Structure__r.Type__c,
 &quot;Variable by kW&quot;, 
  Utility_Account_Subscription__r.Opportunity__r.Commission_Structure__r.Cents_kW_DC_First_Bill__c * 1000 * Approved_Change_in_Subscription__c,
 &quot;Fixed by Annual kWh&quot;,
  IF(ISPICKVAL(Type__c, &quot;Initial&quot;), 0, 0),
 0
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Estimated Commission owed to partner on First Bill Sent based on Approved Change in Subscription and Commission Rate specified on deal Commission Structure</inlineHelpText>
    <label>First Bill Sent Estimated Commission</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/InvocableCommissionStructureChangerTest.cls
@IsTest
public class InvocableCommissionStructureChangerTest {

    @IsTest
    public static void testWithBadOpportunityStage() {
        Opportunity opp = getOpp(false, true);
        UniversalMocker oppSelectorMock = UniversalMocker.mock(OpportunitiesSelector.class);
        oppSelectorMock.when('getOpportunityWithCommissionPayments').thenReturn(opp);

        UniversalMocker uowMock = UniversalMocker.mock(fflib_SObjectUnitOfWork.class);
        InvocableCommissionStructureChanger.opportunitiesSelector = (OpportunitiesSelector) oppSelectorMock.createStub();
        InvocableCommissionStructureChanger.oppUOW = (fflib_SObjectUnitOfWork) uowMock.createStub();

        InvocableCommissionStructureChanger.CommissionChangeData changeData =
            new InvocableCommissionStructureChanger.CommissionChangeData();
        changeData.opportunityId = opp.Id;
        changeData.newCommissionStructureId = Util.getFakeId(Commission_Structure__c.SObjectType);

        List<String> validationErrors = InvocableCommissionStructureChanger.invokeCommissionStructureChange(
            new List<InvocableCommissionStructureChanger.CommissionChangeData>{
                changeData
            });

        System.assert(validationErrors.contains(InvocableCommissionStructureChanger.INVALID_STAGE_ERROR),
            'The opportunity stage of IsWon = false should prevent commission structure change');
        uowMock.assertThat().method('commitWork').wasNeverCalled();
    }

    @IsTest
    public static void testWithApprovedCommissionPayment() {
        Opportunity opp = getOpp(true, true);
        UniversalMocker oppSelectorMock = UniversalMocker.mock(OpportunitiesSelector.class);
        oppSelectorMock.when('getOpportunityWithCommissionPayments').thenReturn(opp);

        UniversalMocker uowMock = UniversalMocker.mock(fflib_SObjectUnitOfWork.class);
        InvocableCommissionStructureChanger.opportunitiesSelector = (OpportunitiesSelector) oppSelectorMock.createStub();
        InvocableCommissionStructureChanger.oppUOW = (fflib_SObjectUnitOfWork) uowMock.createStub();

        InvocableCommissionStructureChanger.CommissionChangeData changeData =
            new InvocableCommissionStructureChanger.CommissionChangeData();
        changeData.opportunityId = opp.Id;
        changeData.newCommissionStructureId = Util.getFakeId(Commission_Structure__c.SObjectType);

        List<String> validationErrors = InvocableCommissionStructureChanger.invokeCommissionStructureChange(
            new List<InvocableCommissionStructureChanger.CommissionChangeData>{
                changeData
            });

        System.assert(validationErrors.contains(InvocableCommissionStructureChanger.APPROVED_PAYMENTS_ERROR),
            'Approved commission payments should have been found, preventing commission structure change');
        uowMock.assertThat().method('commitWork').wasNeverCalled();
    }

    @IsTest
    public static void testCommissionRecalculation() {
        FeatureService.Mock mockFeatureService = new FeatureService.Mock(new Map<String,Boolean>{
            'New_Partner_Commission_Generator' => true
        });
        InvocableCommissionStructureChanger.featureService = (FeatureService)
            Test.createStub(FeatureService.class, mockFeatureService);
        Opportunity opp = getOpp(true, false);
        UniversalMocker oppSelectorMock = UniversalMocker.mock(OpportunitiesSelector.class);
        oppSelectorMock.when('getOpportunityWithCommissionPayments').thenReturn(opp);

        UniversalMocker oppUOWMock = UniversalMocker.mock(fflib_SObjectUnitOfWork.class);
        UniversalMocker paymentUOWMock = UniversalMocker.mock(fflib_SObjectUnitOfWork.class);
        InvocableCommissionStructureChanger.opportunitiesSelector = (OpportunitiesSelector) oppSelectorMock.createStub();
        InvocableCommissionStructureChanger.oppUOW = (fflib_SObjectUnitOfWork) oppUOWMock.createStub();
        InvocableCommissionStructureChanger.commissionPaymentUOW = (fflib_SObjectUnitOfWork) paymentUOWMock.createStub();

        InvocableCommissionStructureChanger.CommissionChangeData changeData =
            new InvocableCommissionStructureChanger.CommissionChangeData();
        changeData.opportunityId = opp.Id;
        changeData.newCommissionStructureId = Util.getFakeId(Commission_Structure__c.SObjectType);

        UniversalMocker paymentSelector = UniversalMocker.mock(CommissionPaymentSelector.class);
        paymentSelector.when('getWithSubscriptionOrdersBySingleOpp').thenReturn(getCommissionPayments());
        PartnerCommissionCalculator.paymentSelector = (CommissionPaymentSelector) paymentSelector.createStub();

        List<String> validationErrors = InvocableCommissionStructureChanger.invokeCommissionStructureChange(
            new List<InvocableCommissionStructureChanger.CommissionChangeData>{
                changeData
            });

        System.assert(validationErrors.isEmpty(), 'No validation errors should be present when trying to change structure');
        oppUOWMock.assertThat().method('commitWork').wasCalled(1);
        paymentUOWMock.assertThat().method('commitWork').wasCalled(1);

        List<Commission_Payment__c> payments = (List<Commission_Payment__c>)
            paymentUOWMock.forMethod('registerDirty').andInvocationNumber(0).getValueOf('records');
        Commission_Payment__c updatedCommissionPayment = payments[0];
        System.assertEquals(1000, updatedCommissionPayment.Amount_Due__c, 'Amount due should reflect SOs');
        System.assertEquals(500, updatedCommissionPayment.Contract_Execution_Amount__c, 'Contract ex due should reflect SOs');
        System.assertEquals(250, updatedCommissionPayment.First_Bill_Sent_Amount__c, 'First bill sent due should reflect SOs');
        System.assertEquals(250, updatedCommissionPayment.First_Bill_Paid_Amount__c, 'First bill paid due due should reflect SOs');
    }

    private static Opportunity getOpp(Boolean isWon, Boolean withApprovedPayment) {
        sfab_FabricatedSObject commissionPayment = new sfab_FabricatedSObject(Commission_Payment__c.class);
        commissionPayment.setField(Commission_Payment__c.Status__c, withApprovedPayment == true ? 'Approved' : 'Pending Approval');

        sfab_FabricatedSObject opp = new sfab_FabricatedSObject(Opportunity.class);
        opp.setField(Opportunity.Id, Util.getFakeId(Opportunity.SObjectType));
        opp.setField(Opportunity.IsWon, isWon);
        opp.setChildren('Commission_Payments__r', new List<sfab_FabricatedSObject>{
            commissionPayment
        });

        return (Opportunity) opp.toSObject();
    }

    private static List<Commission_Payment__c> getCommissionPayments() {
        sfab_FabricatedSObject commissionPayment = new sfab_FabricatedSObject(Commission_Payment__c.class);
        commissionPayment.setField(Commission_Payment__c.Amount_Due__c, 500);
        commissionPayment.setField(Commission_Payment__c.Contract_Execution_Amount__c, 400);
        commissionPayment.setField(Commission_Payment__c.First_Bill_Sent_Amount__c, 50);
        commissionPayment.setField(Commission_Payment__c.First_Bill_Paid_Amount__c, 50);

        sfab_FabricatedSObject subscriptionOrder = new sfab_FabricatedSObject(Subscription_Order__c.class);
        subscriptionOrder.setField(Subscription_Order__c.Id, Util.getFakeId(Subscription_Order__c.SObjectType));
        subscriptionOrder.setField(Subscription_Order__c.Contract_Close_Estimated_Commission__c, 500);
        subscriptionOrder.setField(Subscription_Order__c.First_Bill_Paid_Estimated_Commission__c, 250);
        subscriptionOrder.setField(Subscription_Order__c.First_Bill_Sent_Estimated_Commission__c, 250);

        commissionPayment.setChildren('Subscription_Orders__r', new List<sfab_FabricatedSObject>{subscriptionOrder});
        commissionPayment.setChildren('First_Bill_Subscription_Orders__r', new List<sfab_FabricatedSObject>{subscriptionOrder});
        commissionPayment.setChildren('First_Bill_Paid_Subscription_Orders__r', new List<sfab_FabricatedSObject>{subscriptionOrder});

        return new List<Commission_Payment__c>{
            (Commission_Payment__c) commissionPayment.toSObject()
        };
    }
}