src/objects/Commission_Structure__c.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Commission Structures</relationshipLabel>
        <relationshipName>Commission_Structures</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Commission Structure</label>
    <nameField>
        <label>Commission Structure Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Commission Structures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Commission_Structure__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <inlineHelpText>Controls how Commission Payments are generated</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Variable by kW</fullName>
            </value>
            <value>
                <fullName>Fixed by Annual kWh</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Management_Fee__c</fullName>
        <inlineHelpText>Annual management fee ($/MW DC) for Small Offtake customers. Manually entered by CSBD at contract execution. If blended rate, include blended rate in both Anchor and Small Offtake fields.</inlineHelpText>
        <label>XXSmall Offtake Management Fee</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This is used for customer contracts to show the product and contract that was used.</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contract_Fee_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Contract__c</fullName>
        <inlineHelpText>The related Client Contract</inlineHelpText>
        <label>Contract</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Contract Fee Detail must be related to a contract with the record type = Client Contract</errorMessage>
            <filterItems>
                <field>Contract.RecordTypeId</field>
                <operation>equals</operation>
                <value>Client Contract</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Contract Fee Detail</relationshipLabel>
        <relationshipName>Contract_Fee_Detail</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Management_Fee_Type__c</fullName>
        <inlineHelpText>One-Time fees are often called &quot;onboarding fees&quot;</inlineHelpText>
        <label>Management Fee Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>One-Time</fullName>
                </value>
                <value>
                    <fullName>Recurring</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Management_Fee__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Management Fee</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Contract Fee Detail</relationshipLabel>
        <relationshipName>Contract_Fee_Detail</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shared_Solar_System__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Used to make this CFD specific to a SSS when the ClientInvoicingFeeAssignmentService assigns a CFD to a Subscription Order when the SO is approved.</inlineHelpText>
        <label>Shared Solar System</label>
        <referenceTo>Shared_Solar_System__c</referenceTo>
        <relationshipLabel>Contract Fee Detail</relationshipLabel>
        <relationshipName>Contract_Fee_Detail</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contract Fee Detail</label>
    <nameField>
        <displayFormat>CFD-{000000}</displayFormat>
        <label>Contract Fee Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Fee Detail</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>LASER_Credit_Score__c</fullName>
        <formula>Personal_Credit_Report__r.LASERCA__Credit_Score__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>LASER Credit Score</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Product lookup, for loans, set by an installer upon sending a new application or set by code after a credit check has determined qualifying products.</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Lead</fullName>
        <active>true</active>
        <businessProcess>CS</businessProcess>
        <label>Lead</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Partner_Shared_Solar_System_Eligibility__c.object
<CustomObject>
    <description>Control partner access to Shared Solar Systems</description>
    <fields>
        <fullName>Shared_Solar_System__c</fullName>
        <inlineHelpText>Shared Solar System that the partner is eligible to sell</inlineHelpText>
        <label>Shared Solar System</label>
        <referenceTo>Shared_Solar_System__c</referenceTo>
        <relationshipLabel>Eligible Partners</relationshipLabel>
        <relationshipName>Partner_Shared_Solar_System_Accesses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <inlineHelpText>Date on which this record begins to be active</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Partner Shared Solar System Access</label>
    <nameField>
        <displayFormat>PSSA-{0000}</displayFormat>
        <label>Partner Shared Solar System Access Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Shared Solar System Accesses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Max_Subscription_kW_AC_for_DC_calc__c</fullName>
        <inlineHelpText>When populated, multiplied by the Conversion Ratio on SSS to populate Maximum Subscription Capacity (kW DC). Intended to be set to 25 kW AC for SMART projects.</inlineHelpText>
        <label>Max Subscription kW AC for DC calc</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Shared_Solar_System__c.object
<CustomObject
     >
    <articleTypeChannelDisplay n1:nil="true" />
    <customSettingsType n1:nil="true" />
    <description n1:nil="true" />
    <eventType n1:nil="true" />
    <fields>
        <fullName>Actual_COD_Date__c</fullName>
        <label>Actual COD Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Actual_PTO_Date_MANUAL__c</fullName>
        <description>Date the project reached PTO.</description>
        <inlineHelpText>Date the project reached PTO.</inlineHelpText>
        <label>Actual PTO Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Available_SMB_Underwriting_Method_Docs__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Available SMB Underwriting Method: Docs</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Available_SMB_Underwriting_Method_FICO__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Used by the QualificationService for both SMB and Resi customers</inlineHelpText>
        <label>Available Underwriting Method: FICO</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Client_Management_Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The field points to the same contract even if there is only one.</description>
        <inlineHelpText>Set automatically when a Client Contract is effective, and used for Client Invoicing. It could be the same as the Client Acquisition Contract.</inlineHelpText>
        <label>Client Management Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Client Management Contract</relationshipLabel>
        <relationshipName>Shared_Solar_Systems1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Credit_Score_Requirement__c</fullName>
        <defaultValue>700</defaultValue>
        <inlineHelpText>Minimum accepted customer FICO score.</inlineHelpText>
        <label>Credit Score Requirement</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Customer_Assignment_Date__c</fullName>
        <description>Populated with the Company Signature Date from the first Assignment Agreement signed by the Client</description>
        <inlineHelpText>Populated with the Company Signature Date from the first Assignment Agreement signed by the Client</inlineHelpText>
        <label>Customer Assignment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>First_Bill_Date__c</fullName>
        <inlineHelpText>Date of first bill sent to customers.</inlineHelpText>
        <label>First Bill Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Management_Revenue_Start_Date__c</fullName>
        <description>Previously entered/updated by Accounting, but automated with W-019836</description>
        <inlineHelpText>Accounting managed field for estimating project revenue, set daily based on the Client Management Contract&apos;s &quot;Contract Fee Detail&quot; and associated date fields.</inlineHelpText>
        <label>Management Revenue Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Maximum_Subscription_Capacity_kWDC__c</fullName>
        <inlineHelpText>Automatically set if the related Product has a &quot;Max Subscription kW AC for DC calc&quot; set (25 kW AC for SMART projects) and both Total System Size kWh DC and Total System Size kW AC fields populated</inlineHelpText>
        <label>Maximum Subscription Capacity (kW DC)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Primary customer product.</inlineHelpText>
        <label>Default Enrollment Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Shared Solar Systems</relationshipLabel>
        <relationshipName>Shared_Solar_Systems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RiskCalc_Minimum__c</fullName>
        <label>RiskCalc Minimum</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Moody_s_Ratings</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_System_Size_kW_AC__c</fullName>
        <inlineHelpText>Total system size in kW AC.</inlineHelpText>
        <label>Total System Size (kW AC)</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_System_Size_kWh_DC__c</fullName>
        <inlineHelpText>Total system size in kW DC.</inlineHelpText>
        <label>Total System Size (kW DC)</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <gender n1:nil="true" />
    <household>false</household>
    <label>Shared Solar System</label>
    <nameField>
        <label>Shared Solar System Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shared Solar Systems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <startsWith n1:nil="true" />
</CustomObject>

force-app/main/default/globalValueSets/Moody_s_Ratings.globalValueSet-meta.xml
<GlobalValueSet>
    
    <customValue>
        
        <fullName>Aaa</fullName>
        
        
        <label>Aaa</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>Aa1</fullName>
        
        
        <label>Aa1</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>Aa2</fullName>
        
        
        <label>Aa2</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>Aa3</fullName>
        
        
        <label>Aa3</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>A1</fullName>
        
        
        <label>A1</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>A2</fullName>
        
        
        <label>A2</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>A3</fullName>
        
        
        <label>A3</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>Baa1</fullName>
        
        
        <label>Baa1</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>Baa2</fullName>
        
        
        <label>Baa2</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>Baa3</fullName>
        
        
        <label>Baa3</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>Ba1</fullName>
        
        
        <label>Ba1</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>Ba2</fullName>
        
        
        <label>Ba2</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>Ba3</fullName>
        
        
        <label>Ba3</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>B1</fullName>
        
        
        <label>B1</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>B2</fullName>
        
        
        <label>B2</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>B3</fullName>
        
        
        <label>B3</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>Caa1</fullName>
        
        
        <label>Caa1</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>Caa2</fullName>
        
        
        <label>Caa2</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>Ca</fullName>
        
        
        <label>Ca</label>
        
    </customValue>
    
    <customValue>
        
        <fullName>C</fullName>
        
        
        <label>C</label>
        
    </customValue>
    
    <masterLabel>Moody&apos;s Ratings</masterLabel>
    
    
</GlobalValueSet>

force-app/main/default/classes/SharedSolarSystemsTest.cls
/**
 * @description Created by peteryao on 8/5/20.
 */
@IsTest
public with sharing class SharedSolarSystemsTest {

    @IsTest
    private static void testRecalculateMaximumSubscriptionCapacityForNonSMART() {
        SharedSolarSystemCapacityCalculator.productSelector = (ProductSelector) Test.createStub(ProductSelector.class, new MockProductSelector(true));
        List<Shared_Solar_System__c> sharedSolarSystems = new List<Shared_Solar_System__c>{
            new Shared_Solar_System__c()
        };
        try {
            new SharedSolarSystemCapacityCalculator().calculateMaximumSubscriptionCapacityForSMART(sharedSolarSystems);
            System.assert(true, 'We should not have thrown an exception trying to calculate max capacity with null values');
        } catch (Exception e) {
            System.assert(false, e.getMessage() + '\n' + e.getStackTraceString());
        }
    }

    @IsTest
    private static void testRecalculateMaximumSubscriptionCapacityIncludingSMART() {
        SharedSolarSystemCapacityCalculator.productSelector = (ProductSelector) Test.createStub(ProductSelector.class, new MockProductSelector(false));
        Shared_Solar_System__c smartSystem = new Shared_Solar_System__c(
            Name = 'SMART',
            Product__c = Util.getFakeId(Product2.SObjectType),
            Total_System_Size_kWh_DC__c = 100,
            Total_System_Size_kW_AC__c = 50
        );
        Shared_Solar_System__c smartSystemNoDC = new Shared_Solar_System__c(
            Name = 'SMART No DC',
            Product__c = Util.getFakeId(Product2.SObjectType),
            Total_System_Size_kW_AC__c = 50
        );
        Shared_Solar_System__c nonSMARTSystem = new Shared_Solar_System__c(
            Name = 'Dumb',
            Product__c = Util.incrementFakeId(smartSystem.Product__c),
            Total_System_Size_kWh_DC__c = 100,
            Total_System_Size_kW_AC__c = 50
        );
        List<Shared_Solar_System__c> sharedSolarSystems = new List<Shared_Solar_System__c>{
            smartSystem, smartSystemNoDC, nonSMARTSystem
        };
        try {
            new SharedSolarSystemCapacityCalculator().calculateMaximumSubscriptionCapacityForSMART(sharedSolarSystems);
        } catch (Exception e) {
            System.assert(false, e.getMessage() + '\n' + e.getStackTraceString());
        }
        for (Shared_Solar_System__c sss : sharedSolarSystems) {
            if (sss.Name == 'SMART') {
                System.assertEquals(25 * (100 / 50), sss.Maximum_Subscription_Capacity_kWDC__c, 'Expected to set Max Capacity for SMART');
            }
            if (sss.Name == 'Dumb' || sss.Name == 'SMART No DC') {
                System.assertEquals(null, sss.Maximum_Subscription_Capacity_kWDC__c, 'Expected to have to set Max Capacity manually');
            }
        }
    }

    @IsTest
    private static void testUpdateManagementRevenueStartDate() {
        Date ptoDate = Date.newInstance(2020, 1, 1);
        Date codDate = Date.newInstance(2020, 1, 1);
        Date assignmentDate = Date.newInstance(2020, 1, 1);
        Date billDate = Date.newInstance(2020, 2, 1);
        Shared_Solar_System__c ptoSystemWithPTOTrigger = new Shared_Solar_System__c(
            Id = Util.getFakeId(Shared_Solar_System__c.SObjectType),
            Name = 'PTO System With PTO Trigger',
            Client_Management_Contract__c = Util.getFakeId(Contract.SObjectType),
            Actual_PTO_Date_MANUAL__c = ptoDate
        );
        Shared_Solar_System__c codSystemWithPTOTrigger = new Shared_Solar_System__c(
            Id = Util.incrementFakeId(ptoSystemWithPTOTrigger.Id),
            Name = 'COD System With PTO Trigger',
            Client_Management_Contract__c = Util.getFakeId(Contract.SObjectType),
            Actual_COD_Date__c = codDate
        );
        Shared_Solar_System__c firstAssignAndBillSystemWithTrigger = new Shared_Solar_System__c(
            Id = Util.incrementFakeId(codSystemWithPTOTrigger.Id),
            Name = 'First Customer Assigned and Billed with Triggers',
            Client_Management_Contract__c = Util.incrementFakeId(ptoSystemWithPTOTrigger.Client_Management_Contract__c),
            Customer_Assignment_Date__c = assignmentDate,
            First_Bill_Date__c = billDate
        );
        Shared_Solar_System__c systemWithNoManagementContract = new Shared_Solar_System__c(
            Id = Util.incrementFakeId(firstAssignAndBillSystemWithTrigger.Id),
            Name = 'No Management Contract',
            Customer_Assignment_Date__c = assignmentDate,
            First_Bill_Date__c = billDate
        );
        Shared_Solar_System__c codSystemWithCODTrigger = new Shared_Solar_System__c(
            Id = Util.incrementFakeId(systemWithNoManagementContract.Id),
            Name = 'COD System With COD Trigger',
            Client_Management_Contract__c = codSystemWithPTOTrigger.Client_Management_Contract__c,
            Actual_COD_Date__c = codDate
        );
        List<Shared_Solar_System__c> mockSharedSolarSystems = new List<Shared_Solar_System__c>{
            ptoSystemWithPTOTrigger,
            codSystemWithPTOTrigger,
            firstAssignAndBillSystemWithTrigger,
            systemWithNoManagementContract,
            codSystemWithCODTrigger
        };
        SharedSolarSystemInvoicer.contractFeeDetailSelector =
            (ContractFeeDetailSelector) Test.createStub(ContractFeeDetailSelector.class, new MockContractFeeDetailSelector(codSystemWithCODTrigger.Id));
        try {
            fflib_SObjectUnitOfWork uow = new fflib_SObjectUnitOfWork(
                new List<SObjectType>{
                    Shared_Solar_System__c.SObjectType
                },
                new FFLibHelperTest.MockDML()
            );
            new SharedSolarSystemInvoicer().updateManagementRevenueStartDate(uow, mockSharedSolarSystems);
        } catch (Exception e) {
            System.assert(false, e.getMessage() + '\n' + e.getStackTraceString());
        }
        System.assertEquals(ptoDate, ptoSystemWithPTOTrigger.Management_Revenue_Start_Date__c,
            'The mock should return a CFD with a PTO trigger for a system with a PTO date');
        System.assertEquals(null, codSystemWithPTOTrigger.Management_Revenue_Start_Date__c,
            'A system with a COD date and no PTO date should not have a CFD with that trigger');
        System.assertEquals(DateUtil.min(assignmentDate, billDate), firstAssignAndBillSystemWithTrigger.Management_Revenue_Start_Date__c,
            'If there are multiple management CFDs, we should evaluate all of them and choose the earlier date');
        System.assertEquals(null, systemWithNoManagementContract.Management_Revenue_Start_Date__c,
            'A system with no management contract should not get a revenue start date');
        System.assertNotEquals(null, codSystemWithCODTrigger.Management_Revenue_Start_Date__c,
            'COD System with COD Trigger should have a Revenue Start Date set because of a system specific CFD');
    }

    @IsTest
    private static void testMeetsUnderwritingCriteria() {
        SharedSolarSystemQualifier sharedSolarSystemQualifier = new SharedSolarSystemQualifier();
        Shared_Solar_System__c sss = new Shared_Solar_System__c(
            Available_SMB_Underwriting_Method_FICO__c = true,
            Available_SMB_Underwriting_Method_Docs__c = true,
            Credit_Score_Requirement__c = 750,
            RiskCalc_Minimum__c = 'Ba3'
        );

        // 800 FICO Lead
        Lead fico800Lead = getLead('FICO', '800', null);
        Boolean fico800LeadQualifies = sharedSolarSystemQualifier.meetsUnderwritingCriteria(
            fico800Lead, sss, fico800Lead.LASER_Credit_Score__c
        );
        System.assertEquals(true, fico800LeadQualifies,
            'lead with FICO of 800 should meet underwriting for a system with FICO min of 750');

        // 700 FICO Lead
        Lead fico700Lead = getLead('FICO', '700', null);
        Boolean fico700LeadQualifies = sharedSolarSystemQualifier.meetsUnderwritingCriteria(
            fico700Lead, sss, fico700Lead.LASER_Credit_Score__c
        );
        System.assertEquals(false, fico700LeadQualifies,
            'lead with FICO of 700 should NOT meet underwriting for a system with FICO min of 750'
        );

        sss.Available_SMB_Underwriting_Method_FICO__c = false;

        // 800 FICO Lead on System with Fin Docs Underwriting (not FICO)
        fico800LeadQualifies = sharedSolarSystemQualifier.meetsUnderwritingCriteria(
            fico800Lead, sss, fico800Lead.LASER_Credit_Score__c);
        System.assertEquals(false, fico800LeadQualifies,
            'lead with FICO of 800 should not meet underwriting for a system that is not available to qualify for FICO'
        );

        // Moody Aaa Lead
        Lead moodysAaaLead = getLead('Financial Review', null, 'Aaa');
        Boolean moodysAaaQualifies = sharedSolarSystemQualifier.meetsUnderwritingCriteria(
            moodysAaaLead, sss, moodysAaaLead.LASER_Credit_Score__c
        );
        System.assertEquals(true, moodysAaaQualifies,
            'Finanical Review lead with a Moody\'s of Aaa should meet underwriting for a system with RiskCalc min of Ba3'
        );

        // Moody Ba3 Lead
        Lead moodysBa3Lead = getLead('Financial Review', null, 'Ba3');
        Boolean moodysBa3LeadQualifies = sharedSolarSystemQualifier.meetsUnderwritingCriteria(
            moodysBa3Lead, sss, moodysBa3Lead.LASER_Credit_Score__c
        );
        System.assertEquals(true, moodysBa3LeadQualifies,
            'Finanical Review lead with a Moody\'s of Ba3 should meet underwriting for a system with RiskCalc min of Ba3'
        );

        // Moody C1 Lead
        Lead moodysC1Lead = getLead('Financial Review', null, 'C1');
        Boolean moodysC1LeadQualifies = sharedSolarSystemQualifier.meetsUnderwritingCriteria(
            moodysC1Lead, sss, moodysC1Lead.LASER_Credit_Score__c
        );
        System.assertEquals(false, moodysC1LeadQualifies,
            'Finanical Review lead with a Moody\'s of C1 should not meet underwriting for a system with RiskCalc min of Ba3'
        );

        sss.Available_SMB_Underwriting_Method_Docs__c = false;

        // Disable Financial Docs Underwriting
        moodysAaaQualifies = sharedSolarSystemQualifier.meetsUnderwritingCriteria(
            moodysAaaLead, sss, moodysAaaLead.LASER_Credit_Score__c
        );
        System.assertEquals(false, moodysAaaQualifies,
            'Finanical Review lead with a Moody\'s of Aaa should not meet underwriting for a system that is not available to qualify');
    }

    /**
     * @description MOCKS AND HELPER METHODS ***
     **/
    public class MockProductSelector extends MockProvider {
        private Boolean returnEmpty;
        public MockProductSelector(Boolean returnEmpty) {
            this.returnEmpty = returnEmpty;
        }
        public override Object handleMethodCall(MethodCall methodCall) {
            switch on methodCall.stubbedMethodName {
                when 'selectForACToDCConversion' {
                    if (returnEmpty) {
                        return new List<Product2>();
                    } else {
                        Product2 smartProduct = new Product2(
                            Id = Util.getFakeId(Product2.SObjectType),
                            Max_Subscription_kW_AC_for_DC_calc__c = 25
                        );
                        return new List<Product2>{
                            smartProduct
                        };
                    }
                }
            }
            return null;
        }
    }

    public class MockContractFeeDetailSelector extends MockProvider {
        Id systemSpecificCFDId;
        public MockContractFeeDetailSelector(String sssId) {
            this.systemSpecificCFDId = sssId;
        }

        public override Object handleMethodCall(MethodCall methodCall) {
            switch on methodCall.stubbedMethodName {
                when 'getContractDetailFromContract' {
                    Contract_Fee_Detail__c cfdPTO = new Contract_Fee_Detail__c(
                        Contract__c = Util.getFakeId(Contract.SObjectType),
                        Management_Fee__c = true,
                        Management_Fee_Type__c = 'Recurring',
                        Management_Fee_Trigger__c = 'Project: PTO'
                    );
                    Contract_Fee_Detail__c cfdCustomerAssigned = new Contract_Fee_Detail__c(
                        Contract__c = Util.incrementFakeId(cfdPTO.Contract__c),
                        Management_Fee__c = true,
                        Management_Fee_Type__c = 'Recurring',
                        Management_Fee_Trigger__c = 'Project: First Customer Assignment Date'
                    );
                    Contract_Fee_Detail__c cfdFirstBilled = new Contract_Fee_Detail__c(
                        Contract__c = cfdCustomerAssigned.Contract__c,
                        Management_Fee__c = true,
                        Management_Fee_Type__c = 'Recurring',
                        Management_Fee_Trigger__c = 'Project: First Customer Bill Date'
                    );
                    Contract_Fee_Detail__c cfdCODForSSS = new Contract_Fee_Detail__c(
                        Contract__c = Util.getFakeId(Contract.SObjectType),
                        Management_Fee__c = true,
                        Management_Fee_Type__c = 'Recurring',
                        Management_Fee_Trigger__c = 'Project: COD',
                        Shared_Solar_System__c = systemSpecificCFDId
                    );
                    return new List<Contract_Fee_Detail__c>{
                        cfdPTO, cfdCustomerAssigned, cfdFirstBilled, cfdCODForSSS
                    };
                }
            }
            return null;
        }
    }

    private static Lead getLead(String underwritingCriteria, String creditScore, String moodys) {
        sfab_FabricatedSObject fabbedLead = new sfab_FabricatedSObject(Lead.class);
        fabbedLead.setField(Lead.Underwriting_Criteria__c, underwritingCriteria);
        fabbedLead.setField(Lead.LASER_Credit_Score__c, creditScore);
        fabbedLead.setField(Lead.Moody_s_Risk_Calc__c, moodys);
        return (Lead) fabbedLead.toSObject();
    }

    @TestVisible
    private static List<Partner_Shared_Solar_System_Eligibility__c> getPartnerEligibilities(
        Shared_Solar_System__c sharedSolarSystem, Account partnerAccount)
    {
        return getPartnerEligibilities(new List<Shared_Solar_System__c>{
            sharedSolarSystem
        }, new List<Account>{
            partnerAccount
        });
    }

    @TestVisible
    private static List<Partner_Shared_Solar_System_Eligibility__c> getPartnerEligibilities(
        List<Shared_Solar_System__c> sharedSolarSystems, List<Account> partnerAccounts)
    {
        Map<String, Commission_Structure__c> commissionStructureMap = getCommissionStructures(sharedSolarSystems, partnerAccounts);
        List<Partner_Shared_Solar_System_Eligibility__c> partnerSharedSolarSystemEligibilities =
            new List<Partner_Shared_Solar_System_Eligibility__c>();
        for (Shared_Solar_System__c sss : sharedSolarSystems) {
            for (Account partnerAccount : partnerAccounts) {
                String csKey = partnerAccount.Id + '-' + sss.Product__c;
                partnerSharedSolarSystemEligibilities.add(new Partner_Shared_Solar_System_Eligibility__c(
                    Shared_Solar_System__c = sss.Id,
                    Account__c = partnerAccount.Id,
                    Commission_Structure__c = commissionStructureMap.get(csKey).Id,
                    Start_Date__c = Date.newInstance(2020, 1, 1)
                ));
            }
        }
        return partnerSharedSolarSystemEligibilities;
    }

    @TestVisible
    private static Map<String, Commission_Structure__c> getCommissionStructures(
        List<Shared_Solar_System__c> sharedSolarSystems, List<Account> partnerAccounts)
    {
        Map<String, Commission_Structure__c> commissionStructureMap = new Map<String, Commission_Structure__c>();
        Set<Id> productIds = new Set<Id>();
        for (Shared_Solar_System__c sss : sharedSolarSystems) {
            productIds.add(sss.Product__c);
        }

        for (Account partner : partnerAccounts) {
            for (Id product : productIds) {
                String mapKey = partner.Id + '-' + product;
                Commission_Structure__c commissionStructure = new Commission_Structure__c(
                    Name = 'Test Commission Structure',
                    Cents_kW_DC_First_Bill__c = 0.03,
                    Cents_kW_DC_Up_Front__c = 0.08,
                    Cents_kW_DC_First_Bill_Paid__c = 0.02,
                    Partner_Account__c = partner.Id,
                    Product__c = product,
                    Type__c = 'Variable by kW'
                );
                commissionStructureMap.put(mapKey, commissionStructure);
            }
        }

        insert commissionStructureMap.values();
        return commissionStructureMap;
    }

    @IsTest
    private static void systemsShouldSortByApplicationTypeThenByCODOrAssignmentOrder() {
        sfab_FabricatedSObject fabbedSSS1 = new sfab_FabricatedSObject(Shared_Solar_System__c.class);
        fabbedSSS1.setField(Shared_Solar_System__c.Name, 'SSS1');
        fabbedSSS1.setField(Shared_Solar_System__c.Assignment_Order__c, 1);
        fabbedSSS1.setField(Shared_Solar_System__c.Estimated_COD_Date_Manual__c, Date.newInstance(2022,1,1));
        fabbedSSS1.setField(Shared_Solar_System__c.Project_Capacity_Available_kW_DC__c, 1000);
        fabbedSSS1.setField(Shared_Solar_System__c.Capacity_Available_to_be_Reserved__c, 100);
        fabbedSSS1.setField(Shared_Solar_System__c.Perch_Acq_Available_LMI_Capacity__c, 1000);

        sfab_FabricatedSObject fabbedSSS2 = new sfab_FabricatedSObject(Shared_Solar_System__c.class);
        fabbedSSS2.setField(Shared_Solar_System__c.Name, 'SSS2');
        fabbedSSS2.setField(Shared_Solar_System__c.Assignment_Order__c, 2);
        fabbedSSS2.setField(Shared_Solar_System__c.Estimated_COD_Date_Manual__c, Date.newInstance(2022,1,1));
        fabbedSSS2.setField(Shared_Solar_System__c.Project_Capacity_Available_kW_DC__c, 100);
        fabbedSSS2.setField(Shared_Solar_System__c.Capacity_Available_to_be_Reserved__c, 100);
        fabbedSSS2.setField(Shared_Solar_System__c.Perch_Acq_Available_LMI_Capacity__c, 100);


        sfab_FabricatedSObject fabbedSSS3 = new sfab_FabricatedSObject(Shared_Solar_System__c.class);
        fabbedSSS3.setField(Shared_Solar_System__c.Name, 'SSS3');
        fabbedSSS3.setField(Shared_Solar_System__c.Assignment_Order__c, 3);
        fabbedSSS3.setField(Shared_Solar_System__c.Estimated_COD_Date_Manual__c, Date.newInstance(2021,12,1));
        fabbedSSS3.setField(Shared_Solar_System__c.Project_Capacity_Available_kW_DC__c, 100);
        fabbedSSS3.setField(Shared_Solar_System__c.Capacity_Available_to_be_Reserved__c, 100);
        fabbedSSS3.setField(Shared_Solar_System__c.Perch_Acq_Available_LMI_Capacity__c, 0);

        List<SharedSolarSystemQualifier.SortedSystem> systemsToSort = new List<SharedSolarSystemQualifier.SortedSystem>();
        systemsToSort.add(new SharedSolarSystemQualifier.SortedSystem((Shared_Solar_System__c) fabbedSSS2.toSObject(), 'Automatic - Assignment Order'));
        systemsToSort.add(new SharedSolarSystemQualifier.SortedSystem((Shared_Solar_System__c) fabbedSSS1.toSObject(), 'Automatic - Assignment Order'));
        systemsToSort.sort();

        System.assertEquals('SSS1', systemsToSort[0].sss.Name, 'Expected SSS1 to be sorted first by assignment order');
        System.assertEquals('SSS2', systemsToSort[1].sss.Name, 'Expected SSS2 to be sorted second by assignment order');

        systemsToSort = new List<SharedSolarSystemQualifier.SortedSystem>();
        systemsToSort.add(new SharedSolarSystemQualifier.SortedSystem((Shared_Solar_System__c) fabbedSSS1.toSObject(), 'Automatic - COD Date/Available Capacity'));
        systemsToSort.add(new SharedSolarSystemQualifier.SortedSystem((Shared_Solar_System__c) fabbedSSS2.toSObject(), 'Automatic - COD Date/Available Capacity'));
        systemsToSort.add(new SharedSolarSystemQualifier.SortedSystem((Shared_Solar_System__c) fabbedSSS3.toSObject(), 'Automatic - COD Date/Available Capacity'));
        systemsToSort.sort();

        System.assertEquals('SSS3', systemsToSort[0].sss.Name, 'Expected SSS3 to be sorted first because it has the oldest COD');
        System.assertEquals('SSS2', systemsToSort[1].sss.Name, 'Expected SSS2 to be sorted second because it has the smallest Available Capacity');
        System.assertEquals('SSS1', systemsToSort[2].sss.Name, 'Expected SSS1 to be sorted last because it has the largest Available Capacity');
    }
}