src/objects/Commission_Structure__c.object
<CustomObject>
    <fields>
        <fullName>Cents_kW_DC_First_Bill_Paid__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Enter the cents per kW DC the partner receives when the customer pays their first bill. This could be zero if they get the second part of their commission after the first bill is sent.</description>
        <inlineHelpText>Enter the cents per kW DC the partner receives when the customer pays their first bill. This could be zero if they get the second part of their commission after the first bill is sent.</inlineHelpText>
        <label>Cents/kW DC First Bill Paid</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Cents_kW_DC_First_Bill__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Enter the cents per kW DC the partner receives up when the customer gets their first bill. This could be zero if they get the second part of their commission after the first bill is fully paid.</description>
        <inlineHelpText>Enter the cents per kW DC the partner receives up when the customer gets their first bill. This could be zero if they get the second part of their commission after the first bill is fully paid.</inlineHelpText>
        <label>Cents/kW DC First Bill Sent</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Cents_kW_DC_Up_Front__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Enter the cents per kW DC the partner receives up front, after full contract execution.</description>
        <inlineHelpText>Enter the cents per kW DC the partner receives up front, after full contract execution.</inlineHelpText>
        <label>Cents/kW DC Contract Execution</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Partner</label>
        <referenceTo>Partner__c</referenceTo>
        <relationshipLabel>Commission Structures</relationshipLabel>
        <relationshipName>Commission_Structures</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Commission Structures</relationshipLabel>
        <relationshipName>Commission_Structures</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Commission Structure</label>
    <nameField>
        <label>Commission Structure Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Commission Structures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Commission_Structure__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <inlineHelpText>Controls how Commission Payments are generated</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Variable by kW</fullName>
            </value>
            <value>
                <fullName>Fixed by Annual kWh</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Partner__c.object
<CustomObject>
    <fields>
        <fullName>Commission_Structure__c</fullName>
        <label>Commission Structure</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <label>Partner</label>
    <nameField>
        <label>Partner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partners</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/CommissionStructureSelectorTest.cls
@IsTest
public with sharing class CommissionStructureSelectorTest {
    @TestSetup public static void testSetup() {
        Product2 product1 = new Product2(
            Name = '10% Product',
            ProductCode = 'CS - BlueWave - 10%',
            IsActive = true);
        insert product1;
        Product2 product2 = new Product2(
            Name = '20% Product',
            ProductCode = 'CS - BlueWave - 20%',
            IsActive = true);
        insert product2;

        Partner__c partnerOne = new Partner__c(
            Name = 'Partner One'
        );
        Partner__c partnerTwo = new Partner__c(
            Name = 'Partner Two'
        );
        insert new List<Partner__c>{
            partnerOne, partnerTwo
        };

        Commission_Structure__c commissionOne = new Commission_Structure__c(
            Name = 'Commission Structure One',
            Partner__c = partnerOne.Id,
            Product__c = product1.Id,
            Cents_kW_DC_Up_Front__c = 0.10,
            Cents_kW_DC_First_Bill__c = 0.23,
            Cents_kW_DC_First_Bill_Paid__c = 0.11,
            Type__c = 'Variable by kW'
        );
        Commission_Structure__c commissionTwo = new Commission_Structure__c(
            Name = 'Commission Structure Two',
            Partner__c = partnerOne.Id,
            Product__c = product2.Id,
            Cents_kW_DC_Up_Front__c = 0.12,
            Cents_kW_DC_First_Bill_Paid__c = 0.50,
            Type__c = 'Variable by kW'
        );
        Commission_Structure__c commissionThree = new Commission_Structure__c(
            Name = 'Commission Structure Two',
            Partner__c = partnerTwo.Id,
            Product__c = product2.Id,
            Cents_kW_DC_Up_Front__c = 0.12,
            Cents_kW_DC_First_Bill_Paid__c = 0.50,
            Type__c = 'Variable by kW'
        );
        insert new List<Commission_Structure__c>{
            commissionOne, commissionTwo, commissionThree
        };
    }

    @IsTest
    public static void getCommissionStructureMapByIds() {
        Map<Id, Commission_Structure__c> commissionStructuresIds = new Map<Id, Commission_Structure__c>([SELECT Id FROM Commission_Structure__c]);
        Map<Id, Commission_Structure__c> checkMap = new CommissionStructureSelector().getCommissionStructureMapByIds(commissionStructuresIds.keySet());
        System.assertEquals(3, checkMap.size(), 'Selector should return a map of 3 Commission Structures');
    }
}