src/objects/Commission_Payment__c.object
<CustomObject>
    <fields>
        <fullName>Amount_Due__c</fullName>
        <label>Amount Due</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Commission Payment</label>
    <nameField>
        <label>Commission Payment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Commission Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Commission_Payment__c/fields/Contract_Execution_Amount__c.field-meta.xml
<CustomField>
    <fullName>Contract_Execution_Amount__c</fullName>
    <label>Contract Execution Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Commission_Payment__c/fields/First_Bill_Paid_Amount__c.field-meta.xml
<CustomField>
    <fullName>First_Bill_Paid_Amount__c</fullName>
    <label>First Bill Paid Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Commission_Payment__c/fields/First_Bill_Sent_Amount__c.field-meta.xml
<CustomField>
    <fullName>First_Bill_Sent_Amount__c</fullName>
    <label>First Bill Sent Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/objects/Subscription_Order__c.object
<CustomObject>
    <label>Subscription Order</label>
    <nameField>
        <displayFormat>SO-{00000}</displayFormat>
        <label>Subscription Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscription Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription_Order__c/fields/Contract_Close_Commission__c.field-meta.xml
<CustomField>
    <fullName>Contract_Close_Commission__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Contract Close Commission Payment record this Subscription Order is applied to. If no value, this Subscription Order has not been applied to a Commission Payment record yet.</inlineHelpText>
    <label>Contract Close Commission</label>
    <referenceTo>Commission_Payment__c</referenceTo>
    <relationshipLabel>Contract_Close_Subscription_Orders</relationshipLabel>
    <relationshipName>Subscription_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscription_Order__c/fields/Contract_Close_Estimated_Commission__c.field-meta.xml
<CustomField>
    <fullName>Contract_Close_Estimated_Commission__c</fullName>
    <formula>CASE(Utility_Account_Subscription__r.Opportunity__r.Commission_Structure__r.Type__c,
 &quot;Variable by kW&quot;, 
  Utility_Account_Subscription__r.Opportunity__r.Commission_Structure__r.Cents_kW_DC_Up_Front__c * 1000 *  Approved_Change_in_Subscription__c,
 &quot;Fixed by Annual kWh&quot;,
  IF(ISPICKVAL(Type__c, &quot;Initial&quot;), 0, 0),
 0
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Estimated Commission owed to partner on Contract Close based on Approved Change in Subscription and Commission Rate specified on deal Commission Structure</inlineHelpText>
    <label>Contract Close Estimated Commission</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Subscription_Order__c/fields/First_Bill_Paid_Commission__c.field-meta.xml
<CustomField>
    <fullName>First_Bill_Paid_Commission__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>First Bill Paid Commission Payment record this Subscription Order is applied to. If no value, this Subscription Order has not been applied to a Commission Payment record yet.</inlineHelpText>
    <label>First Bill Paid Commission</label>
    <referenceTo>Commission_Payment__c</referenceTo>
    <relationshipLabel>Subscription Orders (First Bill Paid Commission)</relationshipLabel>
    <relationshipName>First_Bill_Paid_Subscription_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscription_Order__c/fields/First_Bill_Paid_Estimated_Commission__c.field-meta.xml
<CustomField>
    <fullName>First_Bill_Paid_Estimated_Commission__c</fullName>
    <formula>CASE(Utility_Account_Subscription__r.Opportunity__r.Commission_Structure__r.Type__c,
 &quot;Variable by kW&quot;, 
  Utility_Account_Subscription__r.Opportunity__r.Commission_Structure__r.Cents_kW_DC_First_Bill_Paid__c * 1000 * Approved_Change_in_Subscription__c,
 &quot;Fixed by Annual kWh&quot;,
  IF(ISPICKVAL(Type__c, &quot;Initial&quot;), 0, 0),
 0
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Estimated Commission owed to partner on First Bill Paid based on Approved Change in Subscription and Commission Rate specified on deal Commission Structure</inlineHelpText>
    <label>First Bill Paid Estimated Commission</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Subscription_Order__c/fields/First_Bill_Sent_Commission__c.field-meta.xml
<CustomField>
    <fullName>First_Bill_Sent_Commission__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>First Bill Sent Commission Payment record this Subscription Order is applied to. If no value, this Subscription Order has not been applied to a Commission Payment record yet.</inlineHelpText>
    <label>First Bill Sent Commission</label>
    <referenceTo>Commission_Payment__c</referenceTo>
    <relationshipLabel>Subscription Orders (First Bill Sent Commission)</relationshipLabel>
    <relationshipName>First_Bill_Subscription_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscription_Order__c/fields/First_Bill_Sent_Estimated_Commission__c.field-meta.xml
<CustomField>
    <fullName>First_Bill_Sent_Estimated_Commission__c</fullName>
    <formula>CASE(Utility_Account_Subscription__r.Opportunity__r.Commission_Structure__r.Type__c,
 &quot;Variable by kW&quot;, 
  Utility_Account_Subscription__r.Opportunity__r.Commission_Structure__r.Cents_kW_DC_First_Bill__c * 1000 * Approved_Change_in_Subscription__c,
 &quot;Fixed by Annual kWh&quot;,
  IF(ISPICKVAL(Type__c, &quot;Initial&quot;), 0, 0),
 0
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Estimated Commission owed to partner on First Bill Sent based on Approved Change in Subscription and Commission Rate specified on deal Commission Structure</inlineHelpText>
    <label>First Bill Sent Estimated Commission</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/PartnerCommissionCalculator.cls
/**
 * @description Created by jeffparlin on 5/4/22. Determines and sets Partner Commission Amounts.
 * - Calculates Commission Payment records based on input SO's. Used in InvocableCommissionStructureChanger.cls
 * - Stamps approved commission amounts on SO's when Commission Payments are marked as approved
 * Tested By: PartnerCommissionGenerationTest, InvocableCommissionStructureChangerTest
 */
public without sharing class PartnerCommissionCalculator {

    @TestVisible private static CommissionPaymentSelector paymentSelector = new CommissionPaymentSelector();
    public List<Input> paymentDetails;

    /**
     * @description Constructor used for VariableRateCommissionProcessor where Subscription Order lookups have not yet been
     * committed to the database
     */
    public PartnerCommissionCalculator(List<Input> payments) {
        this.paymentDetails = payments;
    }

    /**
     * @description Constructor to handle Commission Payments for a single Opportunity
     * @param opportunityId Opportunity
     */
    public PartnerCommissionCalculator(Id opportunityId) {
        this.paymentDetails = parseInputsFromQuery(paymentSelector.getWithSubscriptionOrdersBySingleOpp(opportunityId));
    }

    public class Input {
        public Commission_Payment__c record;
        public Boolean requiresUpsert = false;
        public List<Subscription_Order__c> contractCloseOrders = new List<Subscription_Order__c>();
        public List<Subscription_Order__c> firstBillSentOrders = new List<Subscription_Order__c>();
        public List<Subscription_Order__c> firstBillPaidOrders = new List<Subscription_Order__c>();
    }

    public void calculate() {
        for (Input payment : this.paymentDetails) {
            Decimal amountDue = 0;
            Decimal contractExecutionAmount = 0;
            Decimal firstBillSentAmount = 0;
            Decimal firstBillPaidAmount = 0;

            for (Subscription_Order__c order : payment.contractCloseOrders) {
                amountDue += order.Contract_Close_Estimated_Commission__c;
                contractExecutionAmount += order.Contract_Close_Estimated_Commission__c;
            }
            for (Subscription_Order__c order : payment.firstBillSentOrders) {
                amountDue += order.First_Bill_Sent_Estimated_Commission__c;
                firstBillSentAmount += order.First_Bill_Sent_Estimated_Commission__c;
            }
            for (Subscription_Order__c order : payment.firstBillPaidOrders) {
                amountDue += order.First_Bill_Paid_Estimated_Commission__c;
                firstBillPaidAmount += order.First_Bill_Paid_Estimated_Commission__c;
            }

            if (Util.nullToZero(payment?.record.Amount_Due__c) != amountDue) {
                payment.record.Amount_Due__c = amountDue;
                payment.requiresUpsert = true;
            }
            if (Util.nullToZero(payment?.record.Contract_Execution_Amount__c) != contractExecutionAmount) {
                payment.record.Contract_Execution_Amount__c = contractExecutionAmount;
                payment.requiresUpsert = true;
            }
            if (Util.nullToZero(payment?.record.First_Bill_Sent_Amount__c) != firstBillSentAmount) {
                payment.record.First_Bill_Sent_Amount__c = firstBillSentAmount;
                payment.requiresUpsert = true;
            }
            if (Util.nullToZero(payment?.record.First_Bill_Paid_Amount__c) != firstBillPaidAmount) {
                payment.record.First_Bill_Paid_Amount__c = firstBillPaidAmount;
                payment.requiresUpsert = true;
            }
        }
    }

    public List<Commission_Payment__c> getUpsertList() {
        List<Commission_Payment__c> upsertList = new List<Commission_Payment__c>();
        for (Input paymentDetail : this.paymentDetails) {
            if (paymentDetail.requiresUpsert) {
                upsertList.add(paymentDetail.record);
            }
        }
        return upsertList;
    }

    private static List<Input> parseInputsFromQuery(List<Commission_Payment__c> payments) {
        List<Input> inputList = new List<Input>();
        for (Commission_Payment__c paymentRecord : payments) {
            Input payment = new Input();
            payment.record = paymentRecord;
            payment.contractCloseOrders = paymentRecord.Subscription_Orders__r;
            payment.firstBillSentOrders = paymentRecord.First_Bill_Subscription_Orders__r;
            payment.firstBillPaidOrders = paymentRecord.First_Bill_Paid_Subscription_Orders__r;
            inputList.add(payment);
        }
        return inputList;
    }
}