src/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Assignment_Agreement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assignment Agreement</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Assignment agreement must be a contract with record type = Assignment Agreement</errorMessage>
            <filterItems>
                <field>Contract.RecordTypeId</field>
                <operation>equals</operation>
                <value>Assignment Agreement</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Customer Assignments (Contracts)</relationshipLabel>
        <relationshipName>CustomerAssignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to relate multiple Client Contracts to a single opportunity</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Parent_Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This field is normally populated on contracts that are amendments to an active contract.It is also used for customer contracts that are covered by a boilerplate terms/generic contract that allows us to generate project specific contracts on their behalf.</inlineHelpText>
        <label>Parent Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>ParentContracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This is used for customer contracts to show the product and contract that was used.</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract/fields/Addendum_Sent_Date__c.field-meta.xml
<CustomField>
    <fullName>Addendum_Sent_Date__c</fullName>
    <description>Filled when the customer received the project specific disclosure form.</description>
    <inlineHelpText>Filled when the customer received the project specific disclosure form.</inlineHelpText>
    <label>Addendum Sent Date</label>
    <type>Date</type>
</CustomField>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Assignment_Agreement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assignment Agreement</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Assignment Agreement must be a contract with record type = Assignment Agreement</errorMessage>
            <filterItems>
                <field>Contract.RecordTypeId</field>
                <operation>equals</operation>
                <value>Assignment Agreement</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Customer Assignments (Opportunity)</relationshipLabel>
        <relationshipName>CustomerAssignmentsOpp</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Schedule_Z__c.object
<CustomObject>
    <label>Allocation Schedule</label>
    <nameField>
        <label>Allocation Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Allocation Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Schedule_Z_Subscription__c.object
<CustomObject>
    <fields>
        <fullName>Schedule_Z__c</fullName>
        <label>Allocation Schedule</label>
        <referenceTo>Schedule_Z__c</referenceTo>
        <relationshipName>Schedule_Z_Subscriptions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Utility_Account_Subscription__c</fullName>
        <label>Utility Account Subscription</label>
        <referenceTo>Utility_Account_Subscription__c</referenceTo>
        <relationshipName>Schedule_Z_Subscriptions</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Allocation Schedule Subscription</label>
    <nameField>
        <displayFormat>ALSS-{0000}</displayFormat>
        <label>Allocation Schedule Subscription Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Allocation Schedule Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Utility_Account_Subscription__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Utility Account Subscriptions</relationshipLabel>
        <relationshipName>Utility_Account_Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Utility Account Subscription</label>
    <nameField>
        <label>Utility Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Account Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/InvocableSelectAllocationContracts.cls
/**
 * Created by Kristin White
 * 
 * Tested by: ContractSelectorTest
 */
@SuppressWarnings('PMD.ApexCRUDViolation')
public without sharing class InvocableSelectAllocationContracts {
    
    @InvocableMethod(Label='selectContractsForAllocationSchedule' Description='Gets Contracts for an Allocation Schedule without an Addendum Sent Date')
    public static List<List<Contract>> selectContractsForAllocationSchedule(List<Id> allocationScheduleId) {
        List<Schedule_Z_Subscription__c> szsList = [
            SELECT Utility_Account_Subscription__r.Opportunity__r.ContractId
            FROM Schedule_Z_Subscription__c
            WHERE Schedule_Z__c IN : allocationScheduleId
        ];
        List<Id> szsContractIdList = new List<Id>();
        for(Schedule_Z_Subscription__c szs : szsList){
            szsContractIdList.add(szs.Utility_Account_Subscription__r.Opportunity__r.ContractId);
        }
        List<Contract> szsContractList = [
            SELECT Id, Name, Parent_Contract__c, AccountId, Product__c,
            Addendum_Sent_Date__c, Assignment_Agreement__c
            FROM Contract
            WHERE Id IN :szsContractIdList
            AND Addendum_Sent_Date__c = null
        ];
        return new List<List<Contract>>{szsContractList};
    }
    
}