src/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Management_Fee_Trigger__c</fullName>
        <description>Shows Management Fee trigger event.</description>
        <inlineHelpText>Shows Management Fee trigger event.</inlineHelpText>
        <label>XXManagement Fee Trigger</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Client_Invoicing_Events</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Management_Fee__c</fullName>
        <inlineHelpText>Annual management fee ($/MW DC) for Small Offtake customers. Manually entered by CSBD at contract execution. If blended rate, include blended rate in both Anchor and Small Offtake fields.</inlineHelpText>
        <label>XXSmall Offtake Management Fee</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This is used for customer contracts to show the product and contract that was used.</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contract_Fee_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Contract__c</fullName>
        <inlineHelpText>The related Client Contract</inlineHelpText>
        <label>Contract</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Contract Fee Detail must be related to a contract with the record type = Client Contract</errorMessage>
            <filterItems>
                <field>Contract.RecordTypeId</field>
                <operation>equals</operation>
                <value>Client Contract</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Contract Fee Detail</relationshipLabel>
        <relationshipName>Contract_Fee_Detail</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Management_Fee_Trigger__c</fullName>
        <inlineHelpText>The SSS milestone date that starts management fees - can be used for either one-time or recurring fees. For one time, the date the charge is incurred. For recurring, the start date that the recurring charge begins</inlineHelpText>
        <label>Management Fee Trigger</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Client_Invoicing_Events</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Management_Fee_Type__c</fullName>
        <inlineHelpText>One-Time fees are often called &quot;onboarding fees&quot;</inlineHelpText>
        <label>Management Fee Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>One-Time</fullName>
                </value>
                <value>
                    <fullName>Recurring</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Management_Fee__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Management Fee</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Contract Fee Detail</relationshipLabel>
        <relationshipName>Contract_Fee_Detail</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shared_Solar_System__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Used to make this CFD specific to a SSS when the ClientInvoicingFeeAssignmentService assigns a CFD to a Subscription Order when the SO is approved.</inlineHelpText>
        <label>Shared Solar System</label>
        <referenceTo>Shared_Solar_System__c</referenceTo>
        <relationshipLabel>Contract Fee Detail</relationshipLabel>
        <relationshipName>Contract_Fee_Detail</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contract Fee Detail</label>
    <nameField>
        <displayFormat>CFD-{000000}</displayFormat>
        <label>Contract Fee Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Fee Detail</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Partner_Shared_Solar_System_Eligibility__c.object
<CustomObject>
    <description>Control partner access to Shared Solar Systems</description>
    <fields>
        <fullName>Account__c</fullName>
        <inlineHelpText>Partner Account</inlineHelpText>
        <label>Partner Account</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The Account must have a record type of Partner Account</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Partner Account</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Shared Solar Systems</relationshipLabel>
        <relationshipName>Partner_Shared_Solar_System_Accesses</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Shared_Solar_System__c</fullName>
        <inlineHelpText>Shared Solar System that the partner is eligible to sell</inlineHelpText>
        <label>Shared Solar System</label>
        <referenceTo>Shared_Solar_System__c</referenceTo>
        <relationshipLabel>Eligible Partners</relationshipLabel>
        <relationshipName>Partner_Shared_Solar_System_Accesses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Partner Shared Solar System Access</label>
    <nameField>
        <displayFormat>PSSA-{0000}</displayFormat>
        <label>Partner Shared Solar System Access Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Shared Solar System Accesses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Max_Subscription_kW_AC_for_DC_calc__c</fullName>
        <inlineHelpText>When populated, multiplied by the Conversion Ratio on SSS to populate Maximum Subscription Capacity (kW DC). Intended to be set to 25 kW AC for SMART projects.</inlineHelpText>
        <label>Max Subscription kW AC for DC calc</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Shared_Solar_System__c.object
<CustomObject
     >
    <articleTypeChannelDisplay n1:nil="true" />
    <customSettingsType n1:nil="true" />
    <description n1:nil="true" />
    <eventType n1:nil="true" />
    <fields>
        <fullName>Actual_COD_Date__c</fullName>
        <label>Actual COD Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Actual_PTO_Date_MANUAL__c</fullName>
        <description>Date the project reached PTO.</description>
        <inlineHelpText>Date the project reached PTO.</inlineHelpText>
        <label>Actual PTO Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Client_Management_Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The field points to the same contract even if there is only one.</description>
        <inlineHelpText>Set automatically when a Client Contract is effective, and used for Client Invoicing. It could be the same as the Client Acquisition Contract.</inlineHelpText>
        <label>Client Management Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Client Management Contract</relationshipLabel>
        <relationshipName>Shared_Solar_Systems1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Assignment_Date__c</fullName>
        <description>Populated with the Company Signature Date from the first Assignment Agreement signed by the Client</description>
        <inlineHelpText>Populated with the Company Signature Date from the first Assignment Agreement signed by the Client</inlineHelpText>
        <label>Customer Assignment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>First_Bill_Date__c</fullName>
        <inlineHelpText>Date of first bill sent to customers.</inlineHelpText>
        <label>First Bill Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Management_Revenue_Start_Date__c</fullName>
        <description>Previously entered/updated by Accounting, but automated with W-019836</description>
        <inlineHelpText>Accounting managed field for estimating project revenue, set daily based on the Client Management Contract&apos;s &quot;Contract Fee Detail&quot; and associated date fields.</inlineHelpText>
        <label>Management Revenue Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Maximum_Subscription_Capacity_kWDC__c</fullName>
        <inlineHelpText>Automatically set if the related Product has a &quot;Max Subscription kW AC for DC calc&quot; set (25 kW AC for SMART projects) and both Total System Size kWh DC and Total System Size kW AC fields populated</inlineHelpText>
        <label>Maximum Subscription Capacity (kW DC)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Primary customer product.</inlineHelpText>
        <label>Default Enrollment Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Shared Solar Systems</relationshipLabel>
        <relationshipName>Shared_Solar_Systems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total_System_Size_kW_AC__c</fullName>
        <inlineHelpText>Total system size in kW AC.</inlineHelpText>
        <label>Total System Size (kW AC)</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_System_Size_kWh_DC__c</fullName>
        <inlineHelpText>Total system size in kW DC.</inlineHelpText>
        <label>Total System Size (kW DC)</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <gender n1:nil="true" />
    <household>false</household>
    <label>Shared Solar System</label>
    <nameField>
        <label>Shared Solar System Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shared Solar Systems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <startsWith n1:nil="true" />
</CustomObject>

src/globalValueSets/Client_Invoicing_Events.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Project Contract: Effective Date</fullName>
    </customValue>
    <customValue>
        <fullName>Contract: Effective Date</fullName>
    </customValue>
    <customValue>
        <fullName>Project: PTO</fullName>
    </customValue>
    <customValue>
        <fullName>Project: COD</fullName>
    </customValue>
    <customValue>
        <fullName>Project: First Customer Assignment Date</fullName>
    </customValue>
    <customValue>
        <fullName>Project: First Customer Bill Date</fullName>
    </customValue>
    <customValue>
        <fullName>Fee not Charged</fullName>
    </customValue>
    <customValue>
        <fullName>Customer: Assignment Date</fullName>
    </customValue>
    <customValue>
        <fullName>Project: Estimated COD or Customer: Assignment Date</fullName>
    </customValue>
    <customValue>
        <fullName>First Customer Bill Date</fullName>
        <isActive>false</isActive>
        <label>First Customer Bill Date</label>
    </customValue>
    <customValue>
        <fullName>First Customer Assignment Date</fullName>
        <isActive>false</isActive>
        <label>First Customer Assignment Date</label>
    </customValue>
    <customValue>
        <fullName>COD</fullName>
        <isActive>false</isActive>
        <label>COD</label>
    </customValue>
    <customValue>
        <fullName>PTO</fullName>
        <isActive>false</isActive>
        <label>PTO</label>
    </customValue>
    <customValue>
        <fullName>Contract Effective Date</fullName>
        <isActive>false</isActive>
        <label>Contract Effective Date</label>
    </customValue>
    <customValue>
        <fullName>First Bill</fullName>
        <isActive>false</isActive>
        <label>First Bill</label>
    </customValue>
    <masterLabel>Client Invoicing Events</masterLabel>
</GlobalValueSet>

src/classes/SharedSolarSystemsTest.cls
/**
 * Created by peteryao on 8/5/20.
 */
@IsTest
public with sharing class SharedSolarSystemsTest {
    @IsTest
    private static void testRecalculateMaximumSubscriptionCapacityForNonSMART() {
        SharedSolarSystems.productSelector = (ProductSelector) Test.createStub(ProductSelector.class, new MockProductSelector(true));
        List<Shared_Solar_System__c> sharedSolarSystems = new List<Shared_Solar_System__c>{new Shared_Solar_System__c()};
        try {
            new SharedSolarSystems(sharedSolarSystems).calculateMaximumSubscriptionCapacityForSMART();
            System.assert(true, 'We should not have thrown an exception trying to calculate max capacity with null values');
        } catch (Exception e) {
            System.assert(false, e.getMessage() + '\n' + e.getStackTraceString());
        }
    }

    @IsTest
    private static void testRecalculateMaximumSubscriptionCapacityIncludingSMART() {
        SharedSolarSystems.productSelector = (ProductSelector) Test.createStub(ProductSelector.class, new MockProductSelector(false));
        Shared_Solar_System__c smartSystem = new Shared_Solar_System__c(
            Name = 'SMART',
            Product__c = Util.getFakeId(Product2.SObjectType),
            Total_System_Size_kWh_DC__c = 100,
            Total_System_Size_kW_AC__c = 50
        );
        Shared_Solar_System__c smartSystemNoDC = new Shared_Solar_System__c(
            Name = 'SMART No DC',
            Product__c = Util.getFakeId(Product2.SObjectType),
            Total_System_Size_kW_AC__c = 50
        );
        Shared_Solar_System__c nonSMARTSystem = new Shared_Solar_System__c(
            Name = 'Dumb',
            Product__c = Util.incrementFakeId(smartSystem.Product__c),
            Total_System_Size_kWh_DC__c = 100,
            Total_System_Size_kW_AC__c = 50
        );
        List<Shared_Solar_System__c> sharedSolarSystems = new List<Shared_Solar_System__c>{smartSystem, smartSystemNoDC, nonSMARTSystem};
        try {
            new SharedSolarSystems(sharedSolarSystems).calculateMaximumSubscriptionCapacityForSMART();
        } catch (Exception e) {
            System.assert(false, e.getMessage() + '\n' + e.getStackTraceString());
        }
        for (Shared_Solar_System__c sss : sharedSolarSystems) {
            if (sss.Name == 'SMART') {
                System.assertEquals(25 * (100/50), sss.Maximum_Subscription_Capacity_kWDC__c, 'Expected to set Max Capacity for SMART');
            }
            if (sss.Name == 'Dumb' || sss.Name == 'SMART No DC') {
                System.assertEquals(null, sss.Maximum_Subscription_Capacity_kWDC__c, 'Expected to have to set Max Capacity manually');
            }
        }
    }
    @IsTest
    private static void testUpdateManagementRevenueStartDate() {
        Date ptoDate = Date.newInstance(2020,1,1);
        Date codDate = Date.newInstance(2020,1,1);
        Date assignmentDate = Date.newInstance(2020,1,1);
        Date billDate = Date.newInstance(2020,2,1);
        Shared_Solar_System__c ptoSystemWithPTOTrigger = new Shared_Solar_System__c(
            Id = Util.getFakeId(Shared_Solar_System__c.SObjectType),
            Name = 'PTO System With PTO Trigger',
            Client_Management_Contract__c = Util.getFakeId(Contract.SObjectType),
            Actual_PTO_Date_MANUAL__c = ptoDate
        );
        Shared_Solar_System__c codSystemWithPTOTrigger = new Shared_Solar_System__c(
            Id = Util.incrementFakeId(ptoSystemWithPTOTrigger.Id),
            Name = 'COD System With PTO Trigger',
            Client_Management_Contract__c = Util.getFakeId(Contract.SObjectType),
            Actual_COD_Date__c = codDate
        );
        Shared_Solar_System__c firstAssignAndBillSystemWithTrigger = new Shared_Solar_System__c(
            Id = Util.incrementFakeId(codSystemWithPTOTrigger.Id),
            Name = 'First Customer Assigned and Billed with Triggers',
            Client_Management_Contract__c = Util.incrementFakeId(ptoSystemWithPTOTrigger.Client_Management_Contract__c),
            Customer_Assignment_Date__c = assignmentDate,
            First_Bill_Date__c = billDate
        );
        Shared_Solar_System__c systemWithNoManagementContract = new Shared_Solar_System__c(
            Id = Util.incrementFakeId(firstAssignAndBillSystemWithTrigger.Id),
            Name = 'No Management Contract',
            Customer_Assignment_Date__c = assignmentDate,
            First_Bill_Date__c = billDate
        );
        Shared_Solar_System__c codSystemWithCODTrigger = new Shared_Solar_System__c(
            Id = Util.incrementFakeId(systemWithNoManagementContract.Id),
            Name = 'COD System With COD Trigger',
            Client_Management_Contract__c = codSystemWithPTOTrigger.Client_Management_Contract__c,
            Actual_COD_Date__c = codDate
        );
        List<Shared_Solar_System__c> mockSharedSolarSystems = new List<Shared_Solar_System__c>{
            ptoSystemWithPTOTrigger,
            codSystemWithPTOTrigger,
            firstAssignAndBillSystemWithTrigger,
            systemWithNoManagementContract,
            codSystemWithCODTrigger
        };
        SharedSolarSystems.contractFeeDetailSelector =
            (ContractFeeDetailSelector) Test.createStub(ContractFeeDetailSelector.class, new MockContractFeeDetailSelector(codSystemWithCODTrigger.Id));
        try {
            fflib_SObjectUnitOfWork uow = new fflib_SObjectUnitOfWork(
                new List<SObjectType>{Shared_Solar_System__c.SObjectType},
                new FFLibHelperTest.MockDML()
            );
            new SharedSolarSystems(mockSharedSolarSystems).updateManagementRevenueStartDate(uow);
        } catch (Exception e) {
            System.assert(false, e.getMessage() + '\n' + e.getStackTraceString());
        }
        System.assertEquals(ptoDate, ptoSystemWithPTOTrigger.Management_Revenue_Start_Date__c,
            'The mock should return a CFD with a PTO trigger for a system with a PTO date');
        System.assertEquals(null, codSystemWithPTOTrigger.Management_Revenue_Start_Date__c,
            'A system with a COD date and no PTO date should not have a CFD with that trigger');
        System.assertEquals(DateUtil.min(assignmentDate, billDate), firstAssignAndBillSystemWithTrigger.Management_Revenue_Start_Date__c,
            'If there are multiple management CFDs, we should evaluate all of them and choose the earlier date');
        System.assertEquals(null, systemWithNoManagementContract.Management_Revenue_Start_Date__c,
            'A system with no management contract should not get a revenue start date');
        System.assertNotEquals(null, codSystemWithCODTrigger.Management_Revenue_Start_Date__c,
            'COD System with COD Trigger should have a Revenue Start Date set because of a system specific CFD');
    }

    @TestVisible
    private static List<Partner_Shared_Solar_System_Eligibility__c> getPartnerEligibilities(Shared_Solar_System__c sharedSolarSystem, Account partnerAccount) {
        return getPartnerEligibilities(new List<Shared_Solar_System__c>{sharedSolarSystem}, new List<Account>{partnerAccount});
    }

    @TestVisible
    private static List<Partner_Shared_Solar_System_Eligibility__c> getPartnerEligibilities(List<Shared_Solar_System__c> sharedSolarSystems, List<Account> partnerAccounts) {
        List<Partner_Shared_Solar_System_Eligibility__c> partnerSharedSolarSystemEligibilities =
            new List<Partner_Shared_Solar_System_Eligibility__c>();
        for (Shared_Solar_System__c sss : sharedSolarSystems) {
            for (Account partnerAccount : partnerAccounts) {
                partnerSharedSolarSystemEligibilities.add(new Partner_Shared_Solar_System_Eligibility__c(
                    Shared_Solar_System__c = sss.Id,
                    Account__c = partnerAccount.Id,
                    Active__c = true
                ));
            }
        }
        return partnerSharedSolarSystemEligibilities;
    }

    /*************
      *** MOCKS ***
      *************/
    public class MockProductSelector extends MockProvider {
        private Boolean returnEmpty;
        public MockProductSelector(Boolean returnEmpty) {
            this.returnEmpty = returnEmpty;
        }
        public override Object handleMethodCall(MethodCall methodCall) {
            switch on methodCall.stubbedMethodName {
                when 'selectForACToDCConversion' {
                    if (returnEmpty) {
                        return new List<Product2>();
                    } else {
                        Product2 smartProduct = new Product2(
                            Id = Util.getFakeId(Product2.SObjectType),
                            Max_Subscription_kW_AC_for_DC_calc__c = 25
                        );
                        return new List<Product2>{smartProduct};
                    }
                }
            }
            return null;
        }
    }
    public class MockContractFeeDetailSelector extends MockProvider {
        Id systemSpecificCFDId;
        public MockContractFeeDetailSelector(String sssId) {
            this.systemSpecificCFDId = sssId;
        }

        public override Object handleMethodCall(MethodCall methodCall) {
            switch on methodCall.stubbedMethodName {
                when 'getContractDetailFromContract' {
                    Contract_Fee_Detail__c cfdPTO = new Contract_Fee_Detail__c(
                        Contract__c = Util.getFakeId(Contract.SObjectType),
                        Management_Fee__c = true,
                        Management_Fee_Type__c = 'Recurring',
                        Management_Fee_Trigger__c = 'Project: PTO'
                    );
                    Contract_Fee_Detail__c cfdCustomerAssigned = new Contract_Fee_Detail__c(
                        Contract__c = Util.incrementFakeId(cfdPTO.Contract__c),
                        Management_Fee__c = true,
                        Management_Fee_Type__c = 'Recurring',
                        Management_Fee_Trigger__c = 'Project: First Customer Assignment Date'
                    );
                    Contract_Fee_Detail__c cfdFirstBilled = new Contract_Fee_Detail__c(
                        Contract__c = cfdCustomerAssigned.Contract__c,
                        Management_Fee__c = true,
                        Management_Fee_Type__c = 'Recurring',
                        Management_Fee_Trigger__c = 'Project: First Customer Bill Date'
                    );
                    Contract_Fee_Detail__c cfdCODForSSS = new Contract_Fee_Detail__c(
                        Contract__c = Util.getFakeId(Contract.SObjectType),
                        Management_Fee__c = true,
                        Management_Fee_Type__c = 'Recurring',
                        Management_Fee_Trigger__c = 'Project: COD',
                        Shared_Solar_System__c = systemSpecificCFDId
                    );
                    return new List<Contract_Fee_Detail__c>{cfdPTO, cfdCustomerAssigned, cfdFirstBilled, cfdCODForSSS};
                }
            }
            return null;
        }
    }
}