src/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Assignment_Agreement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assignment Agreement</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Assignment agreement must be a contract with record type = Assignment Agreement</errorMessage>
            <filterItems>
                <field>Contract.RecordTypeId</field>
                <operation>equals</operation>
                <value>Assignment Agreement</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Customer Assignments (Contracts)</relationshipLabel>
        <relationshipName>CustomerAssignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contract_Type__c</fullName>
        <label>Contract Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Anchor Customer Contract</fullName>
                </value>
                <value>
                    <fullName>BPD Scout Agreement</fullName>
                </value>
                <value>
                    <fullName>Client Service Agreement</fullName>
                </value>
                <value>
                    <fullName>Consumer Disclosure Form</fullName>
                </value>
                <value>
                    <fullName>Customer Assignment</fullName>
                </value>
                <value>
                    <fullName>Customer Contract Template</fullName>
                </value>
                <value>
                    <fullName>Engineering, Procurement and Construction Contract (EPC)</fullName>
                </value>
                <value>
                    <fullName>Financing Agreement</fullName>
                </value>
                <value>
                    <fullName>Lease Option Agreement</fullName>
                </value>
                <value>
                    <fullName>Membership Interest Purchase Agreement (MIPA) and Ancillary Documents</fullName>
                </value>
                <value>
                    <fullName>NDA</fullName>
                </value>
                <value>
                    <fullName>Sales Partner Agreement</fullName>
                </value>
                <value>
                    <fullName>Small-Offtake Customer Contract</fullName>
                </value>
                <value>
                    <fullName>Vendor Agreement</fullName>
                </value>
                <value>
                    <fullName>Generic</fullName>
                </value>
                <value>
                    <fullName>Project Specific</fullName>
                </value>
                <value>
                    <fullName>Lease Agreement</fullName>
                    <isActive>false</isActive>
                    <label>Lease Agreement</label>
                </value>
                <value>
                    <fullName>Loan Origination and Servicing Agreement</fullName>
                    <isActive>false</isActive>
                    <label>Loan Origination and Servicing Agreement</label>
                </value>
                <value>
                    <fullName>Membership Interest Purchase Agreement (MIPA)</fullName>
                    <isActive>false</isActive>
                    <label>Membership Interest Purchase Agreement (MIPA)</label>
                </value>
                <value>
                    <fullName>Partner MSA</fullName>
                    <isActive>false</isActive>
                    <label>Partner MSA</label>
                </value>
                <value>
                    <fullName>Partner SOW</fullName>
                    <isActive>false</isActive>
                    <label>Partner SOW</label>
                </value>
                <value>
                    <fullName>Partner SSA</fullName>
                    <isActive>false</isActive>
                    <label>Partner SSA</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This is used for customer contracts to show the product and contract that was used.</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Assignment_Agreement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assignment Agreement</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Assignment Agreement must be a contract with record type = Assignment Agreement</errorMessage>
            <filterItems>
                <field>Contract.RecordTypeId</field>
                <operation>equals</operation>
                <value>Assignment Agreement</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Customer Assignments (Opportunity)</relationshipLabel>
        <relationshipName>CustomerAssignmentsOpp</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/ContractMigrationService.cls
// Tested by ContractMigrationServiceTest

public without sharing class ContractMigrationService {

    @TestVisible
    private fflib_SObjectUnitOfWork uow = new fflib_SObjectUnitOfWork(
        new List<SObjectType> {
            Opportunity.SObjectType
        }
    );

    public Map<Id,Contract> oppToContractMap = new Map<Id,Contract>();

    public void executeForOpps(List<Opportunity> oppList){
        convertOpportunityToContract(oppList);
        Logger.flushLogs();
        uow.commitWork();
    }

    public void convertOpportunityToContract(List<Opportunity> oppList) {
        Id customerRecordType = Schema.SObjectType.Contract.getRecordTypeInfosByName().get('Customer Contract').getRecordTypeId();
        for (Opportunity opp : oppList){
            Contract newContract = new Contract(
                AccountId = opp.AccountId,
                Product__c = opp.Product__c,
                RecordTypeId = customerRecordType,
                Contract_Type__c = 'Project Specific',
                Assignment_Agreement__c = opp.Assignment_Agreement__c
            );
            oppToContractMap.put(opp.Id,newContract);
        }
        insert oppToContractMap.values();
        for (Opportunity opp : oppList){
            Contract cntrt = oppToContractMap.get(opp.Id);
            opp.ContractId = cntrt.Id;
            uow.registerDirty(opp);
        }
    }
}