src/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to relate multiple Client Contracts to a single opportunity</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contract_Fee_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Acquisition_Channels_BCS_Acquired__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>True if this fee is valid for customers acquired by BCS</inlineHelpText>
        <label>Acq Channels: BCS Acquired</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Acquisition_Channels_Non_BCS_Acquired__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>True if this fee is valid for customers who were not acquired by BCS</inlineHelpText>
        <label>Acq Channels: Non-BCS Acquired</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Acquisition_Cust_Group_Anchor__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>True if this fee is valid for customers with the Customer Group = Anchor.
Small offtake (ie, Residential and Non-Residential Customer Groups) can be labeled as &quot;non-Demand Customers&quot; and Anchors can be labeled as &quot;Demand Customers&quot; in client contracts.</inlineHelpText>
        <label>Acquisition Cust. Group: Anchor</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Acquisition_Cust_Group_Non_Residential__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>True if valid fee for customers with Customer Group = Non-Residential.
Small offtake (ie, Residential and Non-Residential Customer Groups) can be labeled as &quot;non-Demand Customers&quot; and Anchors can be labeled as &quot;Demand Customers&quot; in client contracts.</inlineHelpText>
        <label>Acquisition Cust. Group: Non-Residential</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Acquisition_Cust_Group_Public_Offtake__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>True if this CFD is valid for customers with the Customer Sub-Group = Public Offtake.</inlineHelpText>
        <label>Acq Cust. Sub-Group: Public Offtake</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Acquisition_Cust_Group_Residential__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>True if valid fee for customers with the Customer Group = Residential.
Small offtake (ie, Residential and Non-Residential Customer Groups) can be labeled as &quot;non-Demand Customers&quot; and Anchors can be labeled as &quot;Demand Customers&quot; in client contracts.</inlineHelpText>
        <label>Acquisition Cust. Group: Residential</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Acquisition_Sizing_Type_Downsizing__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>True if this fee is valid for decreases in a customer subscription (- kW)</inlineHelpText>
        <label>Acquisition Sizing Type: Downsizing</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Acquisition_Sizing_Type_Upsizing__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>True if this fee is valid for increases in a customer subscription (+ kW)</inlineHelpText>
        <label>Acquisition Sizing Type: Upsizing</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Acquisition_Type_Acquisition__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>As opposed to Reacquistion. True if this fee is valid for acquistion</inlineHelpText>
        <label>Acquisition Type: Acquisition</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Acquisition_Type_Reacquisition__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>As opposed to Acquistion. True if this fee is valid for reacquistion</inlineHelpText>
        <label>Acquisition Type: Reacquisition</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <inlineHelpText>The related Client Contract</inlineHelpText>
        <label>Contract</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Contract Fee Detail must be related to a contract with the record type = Client Contract</errorMessage>
            <filterItems>
                <field>Contract.RecordTypeId</field>
                <operation>equals</operation>
                <value>Client Contract</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Contract Fee Detail</relationshipLabel>
        <relationshipName>Contract_Fee_Detail</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Fee__c</fullName>
        <inlineHelpText>The annual $ value of the fee, see &quot;Fee Unit&quot; field for the denominator ($/W year or $/MW year or $/project year)</inlineHelpText>
        <label>Fee ($)</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Shared_Solar_System__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Used to make this CFD specific to a SSS when the ClientInvoicingFeeAssignmentService assigns a CFD to a Subscription Order when the SO is approved.</inlineHelpText>
        <label>Shared Solar System</label>
        <referenceTo>Shared_Solar_System__c</referenceTo>
        <relationshipLabel>Contract Fee Detail</relationshipLabel>
        <relationshipName>Contract_Fee_Detail</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contract Fee Detail</label>
    <nameField>
        <displayFormat>CFD-{000000}</displayFormat>
        <label>Contract Fee Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Fee Detail</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Customer_Group__c</fullName>
        <label>Customer Group</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Residential</fullName>
                </value>
                <value>
                    <fullName>Non-Residential</fullName>
                    <default>true</default>
                    <label>Non-Residential</label>
                </value>
                <value>
                    <fullName>Anchor</fullName>
                </value>
                <value>
                    <fullName>Business</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Partner_tag_lookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Partner</label>
        <referenceTo>Partner__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shared_Solar_System__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>To change this system, use the Change SSS quick action</inlineHelpText>
        <label>Shared Solar System</label>
        <referenceTo>Shared_Solar_System__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Partner__c.object
<CustomObject>
    <label>Partner</label>
    <nameField>
        <label>Partner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partners</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Shared_Solar_System__c.object
<CustomObject
     >
    <articleTypeChannelDisplay n1:nil="true" />
    <customSettingsType n1:nil="true" />
    <description n1:nil="true" />
    <eventType n1:nil="true" />
    <fields>
        <fullName>Client_Acquisition_Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The field points to the same contract even if there is only one.</description>
        <inlineHelpText>Set automatically when a Client Contract is effective, and used for Client Invoicing. It could be the same as the Client Management Contract.</inlineHelpText>
        <label>Client Acquisition Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Client Acquisition Contract</relationshipLabel>
        <relationshipName>Shared_Solar_Systems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Client_Management_Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The field points to the same contract even if there is only one.</description>
        <inlineHelpText>Set automatically when a Client Contract is effective, and used for Client Invoicing. It could be the same as the Client Acquisition Contract.</inlineHelpText>
        <label>Client Management Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Client Management Contract</relationshipLabel>
        <relationshipName>Shared_Solar_Systems1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reacquisition_Start_Date__c</fullName>
        <inlineHelpText>The date at which acquisition is over and reacquisition begins, usually set by the first date at which an allocation schedule is accepted by the utility at 100%.</inlineHelpText>
        <label>Reacquisition Start Date</label>
        <type>Date</type>
    </fields>
    <gender n1:nil="true" />
    <household>false</household>
    <label>Shared Solar System</label>
    <nameField>
        <label>Shared Solar System Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shared Solar Systems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <startsWith n1:nil="true" />
</CustomObject>

src/objects/Subscription_Order__c.object
<CustomObject>
    <fields>
        <fullName>Approved_Change_in_Subscription__c</fullName>
        <description>This is the rounded net change in kW DC. When SO is approved, field is stamped with &apos;Calculated Change in Subscription kW DC.&apos; If Type = &apos;SSS Update,&apos; field is stamped with value of &apos;System Change in kW Subscription&apos; - &apos;Previous kW Subscription. It&apos;s important to have a static value for tracking purposes, and to use in rollup summary fields.</description>
        <inlineHelpText>This is the rounded net change in kW DC. When SO is approved, field is stamped with &apos;Calculated Change in Subscription kW DC.&apos; If Type = &apos;SSS Update,&apos; field is stamped with value of &apos;System Change in kW Subscription&apos; - &apos;Previous kW Subscription.</inlineHelpText>
        <label>Approved Change in Subscription (KW DC)</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Contract_Fee_Detail__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Acquisition rate charged to client for this change</inlineHelpText>
        <label>Contract Fee Detail</label>
        <referenceTo>Contract_Fee_Detail__c</referenceTo>
        <relationshipLabel>Subscription Orders</relationshipLabel>
        <relationshipName>Subscription_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <description>This is the date that the Subscription Order was approved. It is populated automatically when the Status field is set to approved. Subscription Orders cannot be edited once they&apos;ve been approved.</description>
        <inlineHelpText>This is the date that the Subscription Order was approved. It is populated automatically when the Status field is set to approved. Subscription Orders cannot be edited once they&apos;ve been approved.</inlineHelpText>
        <label>Effective Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Utility_Account_Subscription__c</fullName>
        <label>Utility Account Subscription</label>
        <referenceTo>Utility_Account_Subscription__c</referenceTo>
        <relationshipLabel>Subscription Orders</relationshipLabel>
        <relationshipName>Subscription_Orders</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Subscription Order</label>
    <nameField>
        <displayFormat>SO-{00000}</displayFormat>
        <label>Subscription Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscription Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Utility_Account_Subscription__c.object
<CustomObject>
    <fields>
        <fullName>Customer_Group__c</fullName>
        <formula>Text(Opportunity__r.Customer_Group__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Customer Group</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Utility Account Subscriptions</relationshipLabel>
        <relationshipName>Utility_Account_Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shared_Solar_System__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the SSS on the Opportunity when the UAS was created. The SSS on an existing UAS should never be changed.</description>
        <inlineHelpText>This is the SSS on the Opportunity when the UAS was created. The SSS on an existing UAS should never be changed.</inlineHelpText>
        <label>Shared Solar System</label>
        <referenceTo>Shared_Solar_System__c</referenceTo>
        <relationshipLabel>Utility Account Subscriptions</relationshipLabel>
        <relationshipName>Utility_Account_Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Utility Account Subscription</label>
    <nameField>
        <label>Utility Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Account Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ClientInvoicingFeeAssignmentServiceTest.cls
@isTest
public class ClientInvoicingFeeAssignmentServiceTest {
    @IsTest
    private static void testSetSubscriptionOrderAcquisitionFee() {
        useMocks();
        List<Subscription_Order__c> ordersToRun = getSubscriptionOrderMocks();
        System.assertEquals(13,ordersToRun.size());

        ClientInvoicingFeeAssignmentService service = new ClientInvoicingFeeAssignmentService();
        service.setSubscriptionOrderAcquisitionFee(ordersToRun);

        List<Subscription_Order__c> ordersToUpdate = (List<Subscription_Order__c>)
            FFLibHelperTest.getRegisterDirtyListFromUnitOfWork(service.uow, 'Subscription_Order__c');

        for (Subscription_Order__c order : ordersToUpdate){
            String subOrderIdAsString = order.Id;
            String feeDetailIdAsString = order.Contract_Fee_Detail__c;
            String message = 'Could not match contract fee detail to SO where: ';

            switch on subOrderIdAsString {
                when 'a9W3F000000A1P6UAK' {
                    System.assertEquals(
                        'a123F000001VLE7AAA',
                        feeDetailIdAsString,
                        message + 'bcs acquired, residential, upsizing, reacq start date is in future'
                    );
                }
                when 'a9W3F000000A1P7UAK' {
                    System.assertEquals(
                        'a123F000001VLE7BBB',
                        feeDetailIdAsString,
                        message + 'not bcs acquired, residential, upsizing, reacq start date is in future'
                    );
                }
                when 'a9W3F000000A2P6UAK' {
                    System.assertEquals(
                        'a123F000001VLE7EEE',
                        feeDetailIdAsString,
                        message + 'bcs acquired, residential, upsizing, reacq start date is in past'
                    );
                }
                when 'a9W3F000000A2P7UAK' {
                    System.assertEquals(
                        'a123F000001VLE7BBB',
                        feeDetailIdAsString,
                        message + 'not bcs acquired, residential, upsizing, reacq start date is null'
                    );
                }
                when 'a9W3F000000A1P8UAK' {
                    System.assertEquals(
                        'a123F000001VLE7GGG',
                        feeDetailIdAsString,
                        message + 'bcs acquired, residential, downsizing, reacq start date is null'
                    );
                }
                when 'a9W3F000000A1P9UAK' {
                    System.assertEquals(
                        'a123F000001VLE7HHH',
                        feeDetailIdAsString,
                        message + 'bcs acquired, residential, upsizing, reacq start date is null'
                    );
                }
                when 'a9W3F000000A1Q9UAK' {
                    System.assertEquals(
                        'a123F000001VLE7HHH',
                        feeDetailIdAsString,
                        message + 'bcs acquired, non-residential, upsizing, reacq start date is null'
                    );
                }
                when 'a9W3F000000A1R9UAK' {
                    System.assertEquals(
                        'a123F000001VLE7AAA',
                        feeDetailIdAsString,
                        message + 'bcs acquired, non-residential, upsizing, reacq start date is null'
                    );
                }
                when 'a9W3F000000A1S9UAK' {
                    System.assertEquals(
                        'a123F000001VLE7BBB',
                        feeDetailIdAsString,
                        message + 'not bcs acquired, non-residential, upsizing, reacq start date is null'
                    );
                }
                when 'a9W3F000000A1T9UAK' {
                    System.assertEquals(
                        'a123F000001VLE7CCC',
                        feeDetailIdAsString,
                        message + 'not bcs acquired, anchor, upsizing, reacq start date is null'
                    );
                }
                when 'a9W3F000000A1U7UAK' {
                    System.assertEquals(
                        'a123F000001VLE7CCC',
                        feeDetailIdAsString,
                        message + 'bcs acquired, public offtake, upsizing, reacq start date is null'
                    );
                }
                when 'a9W3F000000A2U7UAK' {
                    System.assertEquals(
                        'a123F000001VLE7DDD',
                        feeDetailIdAsString,
                        message + 'bcs acquired, public offtake, upsizing, reacq start date is in past'
                    );
                }
                when 'a9W3F000000A1V9UAK' {
                    System.assertEquals(
                        'a123F000001VLE7GGG',
                        feeDetailIdAsString,
                        message + 'bcs acquired, anchor, downsizing, reacq start date is null'
                    );
                }
                when else {
                    System.assert(false,'Did not expect this Sub. Order ID' + subOrderIdAsString);
                }
            }
        }

    }

    @IsTest
    private static void testGetCancellationRate (){
        useMocks();
        List<Subscription_Order__c> ordersToRun = getSubscriptionOrderMocks();
        System.assertEquals(13,ordersToRun.size());

        ClientInvoicingFeeAssignmentService service = new ClientInvoicingFeeAssignmentService();
        service.setSubscriptionOrderAcquisitionFee(ordersToRun);

        System.assertEquals(0.14,service.getCancellationFee(ordersToRun[0]), 'Expected upsizing reacq rate for BCS Acquired Small Offtake');
        System.assertEquals(0.15,service.getCancellationFee(ordersToRun[1]), 'Expected upsizing reacq rate for NON-BCS Acquired Small Offtake');
        System.assertEquals(0.14,service.getCancellationFee(ordersToRun[2]), 'Expected upsizing reacq rate for BCS Acquired Small Offtake');
        System.assertEquals(0.15,service.getCancellationFee(ordersToRun[3]), 'Expected upsizing reacq rate for NON-BCS Acquired Small Offtake');
        System.assertEquals(0.14,service.getCancellationFee(ordersToRun[4]), 'Expected upsizing reacq rate for BCS Acquired Small Offtake');
    }

    private static void useMocks() {
        ClientInvoicingFeeAssignmentService.contractFeeDetailSelector = (ContractFeeDetailSelector) Test.createStub(ContractFeeDetailSelector.class, new MockFeeDetailSelector());
        ClientInvoicingFeeAssignmentService.subscripOrderSelector = (SubscriptionOrderSelector) Test.createStub(SubscriptionOrderSelector.class, new MockSubscriptionOrderSelector());
    }

    public class MockFeeDetailSelector extends MockProvider {
        public MockFeeDetailSelector() {
        }

        public override Object handleMethodCall(MethodCall methodCall) {
            Contract_Fee_Detail__c acqBcsAcquiredNonAnchor = new Contract_Fee_Detail__c(
                Id = 'a123F000001VLE7AAA',
                Contract__c = '8003F000000KMD9QAO',
                Acquisition_Channels_BCS_Acquired__c = true,
                Acquisition_Channels_Non_BCS_Acquired__c = false,
                Acquisition_Cust_Group_Anchor__c = false,
                Acquisition_Cust_Group_Public_Offtake__c = false,
                Acquisition_Cust_Group_Residential__c = true,
                Acquisition_Cust_Group_Non_Residential__c = true,
                Acquisition_Sizing_Type_Downsizing__c = false,
                Acquisition_Sizing_Type_Upsizing__c = true,
                Acquisition_Type_Acquisition__c = true,
                Acquisition_Type_Reacquisition__c = false,
                Fee__c = 0.10
            );
            Contract_Fee_Detail__c acqNonBcsAcquiredNonAnchor = new Contract_Fee_Detail__c(
                Id = 'a123F000001VLE7BBB',
                Contract__c = '8003F000000KMD9QAO',
                Acquisition_Channels_BCS_Acquired__c = false,
                Acquisition_Channels_Non_BCS_Acquired__c = true,
                Acquisition_Cust_Group_Anchor__c = false,
                Acquisition_Cust_Group_Public_Offtake__c = false,
                Acquisition_Cust_Group_Residential__c = true,
                Acquisition_Cust_Group_Non_Residential__c = true,
                Acquisition_Sizing_Type_Downsizing__c = false,
                Acquisition_Sizing_Type_Upsizing__c = true,
                Acquisition_Type_Acquisition__c = true,
                Acquisition_Type_Reacquisition__c = false,
                Fee__c = 0.11
            );
            Contract_Fee_Detail__c acqAnchor = new Contract_Fee_Detail__c(
                Id = 'a123F000001VLE7CCC',
                Contract__c = '8003F000000KMD9QAO',
                Acquisition_Channels_BCS_Acquired__c = true,
                Acquisition_Channels_Non_BCS_Acquired__c = true,
                Acquisition_Cust_Group_Anchor__c = true,
                Acquisition_Cust_Group_Public_Offtake__c = true,
                Acquisition_Cust_Group_Residential__c = false,
                Acquisition_Cust_Group_Non_Residential__c = false,
                Acquisition_Sizing_Type_Downsizing__c = false,
                Acquisition_Sizing_Type_Upsizing__c = true,
                Acquisition_Type_Acquisition__c = true,
                Acquisition_Type_Reacquisition__c = false,
                Fee__c = 0.12
            );
            Contract_Fee_Detail__c reacqAnchor = new Contract_Fee_Detail__c(
                Id = 'a123F000001VLE7DDD',
                Contract__c = '8003F000000KMD9QAO',
                Acquisition_Channels_BCS_Acquired__c = true,
                Acquisition_Channels_Non_BCS_Acquired__c = true,
                Acquisition_Cust_Group_Anchor__c = true,
                Acquisition_Cust_Group_Public_Offtake__c = true,
                Acquisition_Cust_Group_Residential__c = false,
                Acquisition_Cust_Group_Non_Residential__c = false,
                Acquisition_Sizing_Type_Downsizing__c = false,
                Acquisition_Sizing_Type_Upsizing__c = true,
                Acquisition_Type_Acquisition__c = false,
                Acquisition_Type_Reacquisition__c = true,
                Fee__c = 0.13
            );
            Contract_Fee_Detail__c reacqBcsAcquiredNonAnchor = new Contract_Fee_Detail__c(
                Id = 'a123F000001VLE7EEE',
                Contract__c = '8003F000000KMD9QAO',
                Acquisition_Channels_BCS_Acquired__c = true,
                Acquisition_Channels_Non_BCS_Acquired__c = false,
                Acquisition_Cust_Group_Anchor__c = false,
                Acquisition_Cust_Group_Public_Offtake__c = false,
                Acquisition_Cust_Group_Residential__c = true,
                Acquisition_Cust_Group_Non_Residential__c = true,
                Acquisition_Sizing_Type_Downsizing__c = false,
                Acquisition_Sizing_Type_Upsizing__c = true,
                Acquisition_Type_Acquisition__c = false,
                Acquisition_Type_Reacquisition__c = true,
                Fee__c = 0.14
            );
            Contract_Fee_Detail__c reacqNonBcsAcquiredNonAnchor = new Contract_Fee_Detail__c(
                Id = 'a123F000001VLE7FFF',
                Contract__c = '8003F000000KMD9QAO',
                Acquisition_Channels_BCS_Acquired__c = false,
                Acquisition_Channels_Non_BCS_Acquired__c = true,
                Acquisition_Cust_Group_Anchor__c = false,
                Acquisition_Cust_Group_Public_Offtake__c = false,
                Acquisition_Cust_Group_Residential__c = true,
                Acquisition_Cust_Group_Non_Residential__c = true,
                Acquisition_Sizing_Type_Downsizing__c = false,
                Acquisition_Sizing_Type_Upsizing__c = true,
                Acquisition_Type_Acquisition__c = false,
                Acquisition_Type_Reacquisition__c = true,
                Fee__c = 0.15
            );
            Contract_Fee_Detail__c downsizingAll = new Contract_Fee_Detail__c(
                Id = 'a123F000001VLE7GGG',
                Contract__c = '8003F000000KNC9QAO',
                Acquisition_Channels_BCS_Acquired__c = true,
                Acquisition_Channels_Non_BCS_Acquired__c = true,
                Acquisition_Cust_Group_Anchor__c = true,
                Acquisition_Cust_Group_Public_Offtake__c = true,
                Acquisition_Cust_Group_Residential__c = true,
                Acquisition_Cust_Group_Non_Residential__c = true,
                Acquisition_Sizing_Type_Downsizing__c = true,
                Acquisition_Sizing_Type_Upsizing__c = false,
                Acquisition_Type_Acquisition__c = true,
                Acquisition_Type_Reacquisition__c = true,
                Fee__c = 0.16
            );
            Contract_Fee_Detail__c sameRateForAll = new Contract_Fee_Detail__c(
                Id = 'a123F000001VLE7HHH',
                Contract__c = '8003F000000KHH9QAO',
                Acquisition_Channels_BCS_Acquired__c = true,
                Acquisition_Channels_Non_BCS_Acquired__c = true,
                Acquisition_Cust_Group_Anchor__c = true,
                Acquisition_Cust_Group_Public_Offtake__c = true,
                Acquisition_Cust_Group_Residential__c = true,
                Acquisition_Cust_Group_Non_Residential__c = true,
                Acquisition_Sizing_Type_Downsizing__c = true,
                Acquisition_Sizing_Type_Upsizing__c = true,
                Acquisition_Type_Acquisition__c = true,
                Acquisition_Type_Reacquisition__c = true,
                Fee__c = 0.17
            );

            List<Contract_Fee_Detail__c> cfdList = new List<Contract_Fee_Detail__c>{
                acqBcsAcquiredNonAnchor, acqNonBcsAcquiredNonAnchor, acqAnchor,
                reacqBcsAcquiredNonAnchor, reacqNonBcsAcquiredNonAnchor, reacqAnchor,
                downsizingAll, sameRateForAll
            };
            switch on methodCall.stubbedMethodName {
                when 'getContractDetailFromContract' {
                    return cfdList;
                }
            }
            return null;
        }
    }
    public class MockSubscriptionOrderSelector extends MockProvider {
        public MockSubscriptionOrderSelector() {
        }

        public override Object handleMethodCall(MethodCall methodCall) {
            switch on methodCall.stubbedMethodName {
                when 'selectByIds' {
                    return getSubscriptionOrderMocks();
                }
            }
            return null;
        }
    }

    public static List<Subscription_Order__c> getSubscriptionOrderMocks(){
        Date today = System.Today();
        Date monthFromToday = today.addMonths(1);
        Date monthAgo = today.addMonths(-1);

        String queryData = '[' +
            '{"Id":"a9W3F000000A1P6UAK","Effective_Date__c":"'+ String.valueOf(today) +'","Utility_Account_Subscription__c":"a1d3F0000013EV1QAM",' +
            '"Approved_Change_in_Subscription__c":12.00,' +
            '"Utility_Account_Subscription__r":{"Id":"a1d3F0000013EV1QAM",' +
            '"Opportunity__c":"0063F00000MVO8EQAX",' +
            '"Shared_Solar_System__c":"a1J3F00000122b7UAA",' +
            '"Shared_Solar_System__r":{"Client_Acquisition_Contract__c":"8003F000000KMD9QAO",' +
            '"Client_Management_Contract__c":"8003F000000KNC9QAO",' +
            '"Reacquisition_Start_Date__c":"' + String.valueOf(monthFromToday) + '"},' +
            '"Opportunity__r":{"Id":"0063F00000MVO8EQAX","Customer_Group__c":"Residential",' +
            '"Partner_tag_lookup__c":"a0s3F000000thIBQAY",' +
            '"Partner_tag_lookup__r":{"Id":"a0s3F000000thIBQAY", ' +
            '"Account__r":{"Id":"0013F00000Y6WrnQAF","RecordType":{"Name":"Partner Account"}}}' +
            '}}},' +
            '{"Id":"a9W3F000000A1P7UAK","Effective_Date__c":"'+ String.valueOf(today) +'","Utility_Account_Subscription__c":"a1d3F0000014EV1QAM",' +
            '"Approved_Change_in_Subscription__c":12.00,' +
            '"Utility_Account_Subscription__r":{"Id":"a1d3F0000014EV1QAM",' +
            '"Opportunity__c":"0063F00000MVO9EQAX",' +
            '"Shared_Solar_System__c":"a1J3F00000122b7UAA",' +
            '"Shared_Solar_System__r":{"Client_Acquisition_Contract__c":"8003F000000KMD9QAO",' +
            '"Client_Management_Contract__c":"8003F000000KNC9QAO",' +
            '"Reacquisition_Start_Date__c":"' + String.valueOf(monthFromToday) + '"},' +
            '"Opportunity__r":{"Id":"0063F00000MVO9EQAX","Customer_Group__c":"Residential",' +
            '"Partner_tag_lookup__c":"a0s3F000000thIBQAY",' +
            '"Partner_tag_lookup__r":{"Id":"a0s3F000000xxIBQAY", ' +
            '"Account__r":{"Id":"0013F00000Y7WrnQAF","RecordType":{"Name":"Client Account"}}}' +
            '}}},' +
            '{"Id":"a9W3F000000A2P6UAK","Effective_Date__c":"'+ String.valueOf(today) +'","Utility_Account_Subscription__c":"a1d3F0000013EV1QAM",' +
            '"Approved_Change_in_Subscription__c":12.00,' +
            '"Utility_Account_Subscription__r":{"Id":"a1d3F0000013EV1QAM",' +
            '"Opportunity__c":"0063F00000AAO8EQAX",' +
            '"Shared_Solar_System__c":"a1J3F00000122b7UAA",' +
            '"Shared_Solar_System__r":{"Client_Acquisition_Contract__c":"8003F000000KMD9QAO",' +
            '"Client_Management_Contract__c":"8003F000000KNC9QAO",' +
            '"Reacquisition_Start_Date__c":"' + String.valueOf(monthAgo) + '"},' +
            '"Opportunity__r":{"Id":"0063F00000AAO8EQAX","Customer_Group__c":"Residential",' +
            '"Partner_tag_lookup__c":"a0s3F000000thIBQAY",' +
            '"Partner_tag_lookup__r":{"Id":"a0s3F000000thIBQAY", ' +
            '"Account__r":{"Id":"0013F00000Y6WrnQAF","RecordType":{"Name":"Partner Account"}}}' +
            '}}},' +
            '{"Id":"a9W3F000000A2P7UAK","Effective_Date__c":"'+ String.valueOf(today) +'","Utility_Account_Subscription__c":"a1d3F0000014EV1QAM",' +
            '"Approved_Change_in_Subscription__c":12.00,' +
            '"Utility_Account_Subscription__r":{"Id":"a1d3F0000014EV1QAM",' +
            '"Opportunity__c":"0063F00000MVO9EQAX",' +
            '"Shared_Solar_System__c":"a1J3F00000122b7UAA",' +
            '"Shared_Solar_System__r":{"Client_Acquisition_Contract__c":"8003F000000KMD9QAO",' +
            '"Client_Management_Contract__c":"8003F000000KNC9QAO",' +
            '"Reacquisition_Start_Date__c":null},' +
            '"Opportunity__r":{"Id":"0063F00000MVO9EQAX","Customer_Group__c":"Residential",' +
            '"Partner_tag_lookup__c":"a0s3F000000thIBQAY",' +
            '"Partner_tag_lookup__r":{"Id":"a0s3F000000xxIBQAY", ' +
            '"Account__r":{"Id":"0013F00000Y7WrnQAF","RecordType":{"Name":"Client Account"}}}' +
            '}}},' +
            '{"Id":"a9W3F000000A1P8UAK","Effective_Date__c":"'+ String.valueOf(today) +'","Utility_Account_Subscription__c":"a1d3F0000015EV1QAM",' +
            '"Approved_Change_in_Subscription__c":-12.00,' +
            '"Utility_Account_Subscription__r":{"Id":"a1d3F0000015EV1QAM",' +
            '"Opportunity__c":"0063F00000MXO9EQAX",' +
            '"Shared_Solar_System__c":"a1J3F00000122b7UAA",' +
            '"Shared_Solar_System__r":{"Client_Acquisition_Contract__c":"8003F000000KMD9QAO",' +
            '"Client_Management_Contract__c":"8003F000000KNC9QAO",' +
            '"Reacquisition_Start_Date__c":null},' +
            '"Opportunity__r":{"Id":"0063F00000MXO9EQAX","Customer_Group__c":"Residential",' +
            '"Partner_tag_lookup__c":"a0s3F000000thIBQAY",' +
            '"Partner_tag_lookup__r":{"Id":"a0s3F000000thIBQAY", ' +
            '"Account__r":{"Id":"0013F00000Y6WrnQAF","RecordType":{"Name":"Partner Account"}}}' +
            '}}},' +
            '{"Id":"a9W3F000000A1P9UAK","Effective_Date__c":"'+ String.valueOf(today) +'","Utility_Account_Subscription__c":"a1d3F0000016EV1QAM",' +
            '"Approved_Change_in_Subscription__c":12.00,' +
            '"Utility_Account_Subscription__r":{"Id":"a1d3F0000016EV1QAM",' +
            '"Opportunity__c":"0063F00000MWO9EQAX",' +
            '"Shared_Solar_System__c":"a1J3F00000122b8UAA",' +
            '"Shared_Solar_System__r":{"Client_Acquisition_Contract__c":"8003F000000KHH9QAO",' +
            '"Client_Management_Contract__c":"8003F000000KHH9QAO",' +
            '"Reacquisition_Start_Date__c":null},' +
            '"Opportunity__r":{"Id":"0063F00000MWO9EQAX","Customer_Group__c":"Residential",' +
            '"Partner_tag_lookup__c":"a0s3F000000thIBQAY",' +
            '"Partner_tag_lookup__r":{"Id":"a0s3F000000thIBQAY", ' +
            '"Account__r":{"Id":"0013F00000Y6WrnQAF","RecordType":{"Name":"Partner Account"}}}' +
            '}}},' +
            '{"Id":"a9W3F000000A1Q9UAK","Effective_Date__c":"'+ String.valueOf(today) +'","Utility_Account_Subscription__c":"a1d3F0000016EV1QAM",' +
            '"Approved_Change_in_Subscription__c":12.00,' +
            '"Utility_Account_Subscription__r":{"Id":"a1d3F0000016EV1QAM",' +
            '"Opportunity__c":"0063F00000MWO9EQAX",' +
            '"Shared_Solar_System__c":"a1J3F00000122b8UAA",' +
            '"Shared_Solar_System__r":{"Client_Acquisition_Contract__c":"8003F000000KHH9QAO",' +
            '"Client_Management_Contract__c":"8003F000000KHH9QAO",' +
            '"Reacquisition_Start_Date__c":null},' +
            '"Opportunity__r":{"Id":"0063F00000MWO9EQAX","Customer_Group__c":"Non-Residential",' +
            '"Partner_tag_lookup__c":"a0s3F000000thIBQAY",' +
            '"Partner_tag_lookup__r":{"Id":"a0s3F000000thIBQAY", ' +
            '"Account__r":{"Id":"0013F00000Y6WrnQAF","RecordType":{"Name":"Partner Account"}}}' +
            '}}},' +
            '{"Id":"a9W3F000000A1R9UAK","Effective_Date__c":"'+ String.valueOf(today) +'","Utility_Account_Subscription__c":"a1d3F0000016EV1QAM",' +
            '"Approved_Change_in_Subscription__c":12.00,' +
            '"Utility_Account_Subscription__r":{"Id":"a1d3F0000016EV1QAM",' +
            '"Opportunity__c":"0063F00000MWO9EQAX",' +
            '"Shared_Solar_System__c":"a1J3F00000122b7UAA",' +
            '"Shared_Solar_System__r":{"Client_Acquisition_Contract__c":"8003F000000KMD9QAO",' +
            '"Client_Management_Contract__c":"8003F000000KNC9QAO",' +
            '"Reacquisition_Start_Date__c":null},' +
            '"Opportunity__r":{"Id":"0063F00000MWO9EQAX","Customer_Group__c":"Non-Residential",' +
            '"Partner_tag_lookup__c":"a0s3F000000thIBQAY",' +
            '"Partner_tag_lookup__r":{"Id":"a0s3F000000thIBQAY", ' +
            '"Account__r":{"Id":"0013F00000Y6WrnQAF","RecordType":{"Name":"Partner Account"}}}' +
            '}}},' +
            '{"Id":"a9W3F000000A1S9UAK","Effective_Date__c":"'+ String.valueOf(today) +'","Utility_Account_Subscription__c":"a1d3F0000017EV1QAM",' +
            '"Approved_Change_in_Subscription__c":12.00,' +
            '"Utility_Account_Subscription__r":{"Id":"a1d3F0000017EV1QAM",' +
            '"Opportunity__c":"0063F00000NWO9EQAX",' +
            '"Shared_Solar_System__c":"a1J3F00000122b7UAA",' +
            '"Shared_Solar_System__r":{"Client_Acquisition_Contract__c":"8003F000000KMD9QAO",' +
            '"Client_Management_Contract__c":"8003F000000KNC9QAO",' +
            '"Reacquisition_Start_Date__c":null},' +
            '"Opportunity__r":{"Id":"0063F00000NWO9EQAX","Customer_Group__c":"Non-Residential",' +
            '"Partner_tag_lookup__c":"a0s3F000000thIBQAY",' +
            '"Partner_tag_lookup__r":{"Id":"a0s3F000000xxIBQAY", ' +
            '"Account__r":{"Id":"0013F00000Y7WrnQAF","RecordType":{"Name":"Client Account"}}}' +
            '}}},' +
            '{"Id":"a9W3F000000A1T9UAK","Effective_Date__c":"'+ String.valueOf(today) +'","Utility_Account_Subscription__c":"a1d3F0000018EV1QAM",' +
            '"Approved_Change_in_Subscription__c":12.00,' +
            '"Utility_Account_Subscription__r":{"Id":"a1d3F0000018EV1QAM",' +
            '"Opportunity__c":"0063F00000XQO9EQAX",' +
            '"Shared_Solar_System__c":"a1J3F00000122b7UAA",' +
            '"Shared_Solar_System__r":{"Client_Acquisition_Contract__c":"8003F000000KMD9QAO",' +
            '"Client_Management_Contract__c":"8003F000000KNC9QAO",' +
            '"Reacquisition_Start_Date__c":null},' +
            '"Opportunity__r":{"Id":"0063F00000NWO9EQAX","Customer_Group__c":"Anchor",' +
            '"Partner_tag_lookup__c":"a0s3F000000thIBQAY",' +
            '"Partner_tag_lookup__r":{"Id":"a0s3F000000xxIBQAY", ' +
            '"Account__r":{"Id":"0013F00000Y7WrnQAF","RecordType":{"Name":"Client Account"}}}' +
            '}}},' +
            '{"Id":"a9W3F000000A1U7UAK","Effective_Date__c":"'+ String.valueOf(today) +'","Utility_Account_Subscription__c":"a1d3F0000019EV1QAM",' +
            '"Approved_Change_in_Subscription__c":12.00,' +
            '"Utility_Account_Subscription__r":{"Id":"a1d3F0000019EV1QAM",' +
            '"Opportunity__c":"0063F00000XQO9EAAA",' +
            '"Shared_Solar_System__c":"a1J3F00000122b7UAA",' +
            '"Shared_Solar_System__r":{"Client_Acquisition_Contract__c":"8003F000000KMD9QAO",' +
            '"Client_Management_Contract__c":"8003F000000KNC9QAO",' +
            '"Reacquisition_Start_Date__c":null},' +
            '"Opportunity__r":{"Id":"0063F00000MVO9EQAX","Customer_Group__c":"Public Offtake",' +
            '"Partner_tag_lookup__c":"a0s3F000000thIBQAY",' +
            '"Partner_tag_lookup__r":{"Id":"a0s3F000000thIBQAY", ' +
            '"Account__r":{"Id":"0013F00000Y6WrnQAF","RecordType":{"Name":"Partner Account"}}}' +
            '}}},' +
            '{"Id":"a9W3F000000A2U7UAK","Effective_Date__c":"'+ String.valueOf(today) +'","Utility_Account_Subscription__c":"a1d3F0000019EV1QAM",' +
            '"Approved_Change_in_Subscription__c":12.00,' +
            '"Utility_Account_Subscription__r":{"Id":"a1d3F0000025EV1QAM",' +
            '"Opportunity__c":"0063F00000ZZO9EAAA",' +
            '"Shared_Solar_System__c":"a1J3F00000122b7UAA",' +
            '"Shared_Solar_System__r":{"Client_Acquisition_Contract__c":"8003F000000KMD9QAO",' +
            '"Client_Management_Contract__c":"8003F000000KNC9QAO",' +
            '"Reacquisition_Start_Date__c":"' + String.valueOf(monthAgo) + '"},' +
            '"Opportunity__r":{"Id":"0063F00000ZZO9EAAA","Customer_Group__c":"Public Offtake",' +
            '"Partner_tag_lookup__c":"a0s3F000000thIBQAY",' +
            '"Partner_tag_lookup__r":{"Id":"a0s3F000000thIBQAY", ' +
            '"Account__r":{"Id":"0013F00000Y6WrnQAF","RecordType":{"Name":"Partner Account"}}}' +
            '}}},' +
            '{"Id":"a9W3F000000A1V9UAK","Effective_Date__c":"'+ String.valueOf(today) +'","Utility_Account_Subscription__c":"a1d3F0000020EV1QAM",' +
            '"Approved_Change_in_Subscription__c":-12.00,' +
            '"Utility_Account_Subscription__r":{"Id":"a1d3F0000020EV1QAM",' +
            '"Opportunity__c":"0063F00000ZQO9EQAX",' +
            '"Shared_Solar_System__c":"a1J3F00000122b7UAA",' +
            '"Shared_Solar_System__r":{"Client_Acquisition_Contract__c":"8003F000000KMD9QAO",' +
            '"Client_Management_Contract__c":"8003F000000KNC9QAO",' +
            '"Reacquisition_Start_Date__c":null},' +
            '"Opportunity__r":{"Id":"0063F00000NWO9EQAX","Customer_Group__c":"Anchor",' +
            '"Partner_tag_lookup__c":"a0s3F000000thIBQAY",' +
            '"Partner_tag_lookup__r":{"Id":"a0s3F000000thIBQAY", ' +
            '"Account__r":{"Id":"0013F00000Y6WrnQAF","RecordType":{"Name":"Partner Account"}}}' +
            '}}}' +
            ']';
        return (List<Subscription_Order__c>) JSON.deserialize(queryData, List<Subscription_Order__c>.class);
    }
}