src/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This is used for customer contracts to show the product and contract that was used.</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Loan__c.object
<CustomObject>
    <fields>
        <fullName>Acquisition_Status__c</fullName>
        <formula>TEXT(Opportunity__r.StageName)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Used in Loan Servicer</inlineHelpText>
        <label>XXX Acquisition Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Commencement_Datee__c</fullName>
        <inlineHelpText>The estimated commencement date of the loan, 30 days after the estimated completion date. Set by installers when providing system information.</inlineHelpText>
        <label>Commencement Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Loan_Number__c</fullName>
        <displayFormat>BW{0000000}</displayFormat>
        <externalId>true</externalId>
        <inlineHelpText>Auto-Number used to identify the Loan with external parties (like third party servicing)</inlineHelpText>
        <label>Loan Number</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Loan_Term__c</fullName>
        <description>This is a formula referencing the Loan Term as defined in the assigned Product.  It represents the length of the amortization period of the loan in months.</description>
        <formula>Product__r.Loan_Term__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>This is a formula referencing the Loan Term as defined in the assigned Product.  It represents the length of the amortization period of the loan in months.</inlineHelpText>
        <label>Loan Term</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is a lookup to the Product record assigned to this loan.  The designated Product informs key loan determinants (e.g. interest rate, term, form of promissory note).</description>
        <inlineHelpText>This is a lookup to the Product record assigned to this loan.  The designated Product informs key loan determinants (e.g. interest rate, term, form of promissory note).</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Loans</relationshipLabel>
        <relationshipName>Loans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>System_Costt__c</fullName>
        <inlineHelpText>The request loan amount (could be different than the true system cost)</inlineHelpText>
        <label>XXX System Cost</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Unique_ID__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>LoanHandler uses to assign tranches and MCEC reporting</inlineHelpText>
        <label>Unique ID</label>
        <length>45</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Loan</label>
    <nameField>
        <label>Loan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loans</pluralLabel>
    <recordTypes>
        <fullName>Loan</fullName>
        <active>true</active>
        <label>Loan</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Loan_Payment__c.object
<CustomObject>
    <fields>
        <fullName>Loan__c</fullName>
        <label>Loan</label>
        <referenceTo>Loan__c</referenceTo>
        <relationshipLabel>Loan Payments</relationshipLabel>
        <relationshipName>Loan_Payments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Period__c</fullName>
        <inlineHelpText>Index of Loan Payment for this loan, starting at 0 (representing the first payment) and going to Loan Term + Interest Only Period - 1.</inlineHelpText>
        <label>Period</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unique_ID__c</fullName>
        <externalId>true</externalId>
        <label>Unique ID</label>
        <length>45</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Loan Payment</label>
    <nameField>
        <displayFormat>LP-{000000}</displayFormat>
        <label>Loan Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Loan_Interest_Only_Period__c</fullName>
        <label>Loan Interest Only Period</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Loan_Interest_Rate__c</fullName>
        <label>Loan Interest Rate</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Loan_Term__c</fullName>
        <label>Loan Term</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/LoanServicer.cls
/*************************************************************************************
 * Created By:  Peter Yao 
 * Description: Called from LoanTrigger. 
 *              Creates Loan Payment records based on Loan and Loan Product parameters. 
 *              Loan Payment records would be related to each other through the Prior 
 *              Period Loan Payment lookup.
 * Test: LoanServicerTest
 *************************************************************************************/

public with sharing class LoanServicer {
    private LoanPaymentRepo repo;

    public LoanServicer() {
        repo = new LoanPaymentRepo();
    }

    public void validateLoanChange() {
        for (Loan__c loan : Trigger.new) {
            if (loanLocked(loan)) {
                loan.addError('Cannot update Product, Commencement date, or System Cost ' +
                              'for a Loan that is Complete or Contract Pending');
            }
        }
    }

    // Expects to be called after loan insert or update. If a loan isn't locked down,
    // we're safe to delete and re-create loan payments on loan update.
    public void createNewLoanPayments() {
        for (Loan__c loan : Trigger.new) {
            if (populatedForLPCreation(loan)) {
                if (Trigger.isInsert) {
                    repo.registerProduct(loan);
                } else if (!loanLocked(loan) &&
                           loanParamsUpdated(loan)) {
                    repo.registerProduct(loan);
                }
            }
        }
        repo.queryProducts();

        for (Loan__c loan : Trigger.new) {
            if (populatedForLPCreation(loan)) {
                if (Trigger.isInsert) {
                    repo.createLoanPayments(loan);
                } else if (!loanLocked(loan) &&
                           loanParamsUpdated(loan)) {
                    repo.deleteLoanPaymentsForLoan(loan);
                    repo.createLoanPayments(loan);
                }
            }
        }

        repo.executeDML();
    }

    private Boolean populatedForLPCreation(Loan__c loan) {
        if (loan.Product__c != null &&
            loan.Commencement_Datee__c != null &&
            loan.System_Costt__c > 0) {
            return true;
        } else {
            return false;
        }
    }

    private Boolean loanLocked(Loan__c loan) {
        if (loan.Acquisition_Status__c == 'Complete' ||
            loan.Acquistion_Status__c == 'Contract Pending') {
            return true;
        } else {
            return false;
        }
    }

    private Boolean loanParamsUpdated(Loan__c loan) {
        if (loan.Product__c != Trigger.oldMap.get(loan.Id).Product__c ||
            loan.Commencement_Datee__c != Trigger.oldMap.get(loan.Id).Commencement_Datee__c ||
            loan.System_Costt__c != Trigger.oldMap.get(loan.Id).System_Costt__c) {
            return true;
        } else {
            return false;
        }
    } 

    private Boolean requiresLoanPaymentRecalc(Loan__c loan) {
        if (!loanLocked(loan) &&
            loanParamsUpdated(loan)) {
            return true;
        } else {
            return false;
        }
    }

    // Assumes there are 
    public class LoanPaymentRepo {
        private Set<Id> loanIdstoDeleteLPs;
        private List<Loan_Payment__c> loanPaymentsToCreate;
        private Set<Id> productIds;
        private Map<Id, Product__c> productMap;
        
        public LoanPaymentRepo() {
            loanIdstoDeleteLPs = new Set<Id>();
            loanPaymentsToCreate = new List<Loan_Payment__c>();
            productIds = new Set<Id>();
            productMap = new Map<Id, Product2>();
        }

        public void executeDML() {
            deleteLoanPayments();
            // saveNewLoanPayments();
            // updateNewLoanPayments();
        }

        public void createLoanPayments(Loan__c loan) {
            for (Integer period = 0; period < loanTermPlusIO; period++) {
                loanPaymentsToCreate.add(createLP(period, loan);
            }
        }

        private Loan_Payment__c createLP(Integer period, Loan__c loan) {
            Loan_Payment__c loanPayment = new Loan_Payment__c();
            loanPayment.Unique_Id__c = loan.Loan_Number__c + '|' + period;
            loanPayment.Period__c = period;

        }

        public void deleteLoanPaymentsForLoan(Loan__c loan) {
            loanIdsToDeleteLPs.add(loan.Id);
        }

        public deleteLoanPayments() {
            if (loanIdstoDeleteLPs.size() > 0) {
                List<Loan_Payment__c> loanPayments = [SELECT Id
                                                      FROM Loan_Payment__c
                                                      WHERE Loan__c in :loanIds];
                if (loanPayments.size() > 0) {
                    delete loanPayments;
                }
            }
        }

        public void registerProduct(Loan__c loan) {
            productIds.add(loan.Product__c);
        }

        public void queryProducts() {
            productMap = [SELECT Id, Loan_Interest_Only_Period__c, Loan_Term__c, Loan_Interest_Rate__c
                          FROM Product2
                          WHERE Id in :productIds];
        }
    }

}