src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/CSCLP_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>These are the settings for the CSCLP</description>
    <fields>
        <fullName>Report_IDs__c</fullName>
        <description>This is the field the designates which reports go into the CSCLP</description>
        <label>Report IDs</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Report_Names__c</fullName>
        <description>This field represents the reports names a user in the CSCLP will see. Please list them out delimited by commas.</description>
        <inlineHelpText>This field represents the reports names a user in the CSCLP will see. Please list them out delimited by commas.</inlineHelpText>
        <label>Report Names</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CSCLP Settings</label>
</CustomObject>

src/classes/CSCLPTestclass.cls
@isTest
public class CSCLPTestclass {
	@isTest 
    public static void testClientReportData() {
		Account clientAccount = new Account(Name = 'Client Account');
		insert clientAccount;

		Contact clientContact = new Contact(FirstName = 'First',
											Email = 'clientContact@bluewave-capital.com',
											LastName = 'Last',
											AccountId = clientAccount.Id);
		insert clientContact;

		User clientUser = new User (ProfileId = [SELECT Id from Profile WHERE Name = 'CS Client Partner Login'].Id,
									FirstName = 'TEst67823323',
									LastName = 'Blue',
									Username = 'TEst67823323@bluewavesolar.com',
									Email = 'clientUser@test.com',
									Alias = 'TEst678',
									ContactId = clientContact.Id,
									CommunityNickname = 'TEst678',
									TimeZoneSidKey = 'America/New_York',
									LocaleSidKey = 'en_US',
									EmailEncodingKey = 'ISO-8859-1',
									LanguageLocaleKey = 'en_US');
		Util.insertSObj(clientUser);

        CSCLP_Settings__c csclpSettings = new CSCLP_Settings__c();
        csclpSettings.Name = 'Test';
        csclpSettings.Report_IDs__c = '000x';
        csclpSettings.Report_Names__c = 'Test';
        insert csclpSettings;

		System.runAs (clientUser) {
			CSCLPController.ClientReportData clientReportData = new CSCLPController.ClientReportData();
			clientReportData = CSCLPController.getClientReportData();
			System.debug(clientReportData);
			System.assertEquals(clientReportData.reports.get('Test'), '000x');
	    }
    }
}