src/objects/CS_Reserved_Capacity__c.object
<CustomObject>
    <label>CS Reserved Capacity</label>
    <nameField>
        <label>CS Reserved Capacity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CS Reserved Capacities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>CS_Capacity_Allocated__c</fullName>
        <inlineHelpText>Sum of Future Customer Subscription (KW DC) on Utility Account Subscriptions when Opportunity is set to Complete. Used in Docusign.</inlineHelpText>
        <label>Customer Subscription kW DC at Complete</label>
        <precision>9</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CS_Reserved_Capacity__c</fullName>
        <label>Project Reserved Capacity (kW)</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/ProjectTestAddReservedCapacity.cls
@isTest
private class ProjectTestAddReservedCapacity {

Static testMethod void ProjectaddReservedCapacity(){

Account myAccount = new Account(name = 'Test Account');
insert myAccount;

Date myDate = Date.newInstance(2015, 2, 17);
MPM4_BASE__Milestone1_Project__c myProject = new MPM4_BASE__Milestone1_Project__c(name = 'Tester');
insert myProject;

Opportunity newOpportunity = new Opportunity(name = 'Tester', account = myAccount, type = 'New Business', closeDate = myDate, stageName='New', CS_Capacity_Allocated__c = 100, Assigned_CS_Project__c = myProject.id ); 

test.startTest();
 
insert newOpportunity;
 
test.stopTest();
 
MPM4_BASE__Milestone1_Project__c ProjectQuery = [SELECT name, cs_reserved_capacity__c FROM MPM4_BASE__Milestone1_Project__c WHERE name = 'Tester'];
 
system.assertEquals(null, ProjectQuery.cs_reserved_capacity__c);
 
 
}
}