src/objects/Custom_Feature_Enablement__mdt.object
<CustomObject>
    <fields>
        <fullName>Feature_is_Enabled__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Field is set to TRUE to enable the feature.</description>
        <inlineHelpText>Field is set to TRUE to enable the feature.</inlineHelpText>
        <label>Feature is Enabled?</label>
        <type>Checkbox</type>
    </fields>
    <label>Custom Feature Enablement</label>
    <pluralLabel>Custom Feature Enablements</pluralLabel>
</CustomObject>

src/classes/FeatureSelector.cls
/**
 * Created by SarahRenfro on 1/29/2020.
 *
 * TestedBy: FeatureServiceTest
 */
@SuppressWarnings('PMD.ApexCRUDViolation')
public inherited sharing class FeatureSelector {

    public Custom_Feature_Enablement__mdt getCustomFeature(String developerName) {
         return [
            SELECT Id, MasterLabel, Feature_is_Enabled__c
            FROM Custom_Feature_Enablement__mdt
            WHERE DeveloperName = :developerName
        ];
    }
}