src/objects/Disbursal__c.object
<CustomObject>
    <fields>
        <fullName>Loan__c</fullName>
        <label>Loan</label>
        <referenceTo>Loan__c</referenceTo>
        <relationshipLabel>Disbursals</relationshipLabel>
        <relationshipName>Disbursals</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Partner__c</fullName>
        <label>Partner</label>
        <referenceTo>Partner__c</referenceTo>
        <relationshipLabel>Disbursals</relationshipLabel>
        <relationshipName>Disbursals</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Unique_ID__c</fullName>
        <externalId>true</externalId>
        <label>Unique ID</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <label>Disbursal</label>
    <nameField>
        <label>Disbursal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Disbursals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Loan__c.object
<CustomObject>
    <fields>
        <fullName>Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Set by LoanHandler when the Loan is created from a Lead</inlineHelpText>
        <label>Partner</label>
        <referenceTo>Partner__c</referenceTo>
        <relationshipLabel>Loans</relationshipLabel>
        <relationshipName>Loans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is a lookup to the Product record assigned to this loan.  The designated Product informs key loan determinants (e.g. interest rate, term, form of promissory note).</description>
        <inlineHelpText>This is a lookup to the Product record assigned to this loan.  The designated Product informs key loan determinants (e.g. interest rate, term, form of promissory note).</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Loans</relationshipLabel>
        <relationshipName>Loans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Unique_ID__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>LoanHandler uses to assign tranches and MCEC reporting</inlineHelpText>
        <label>Unique ID</label>
        <length>45</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Loan</label>
    <nameField>
        <label>Loan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loans</pluralLabel>
    <recordTypes>
        <fullName>Loan</fullName>
        <active>true</active>
        <label>Loan</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Partner__c.object
<CustomObject>
    <label>Partner</label>
    <nameField>
        <label>Partner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partners</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Disbursal_Terms__c</fullName>
        <label>Disbursal Terms</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>30% Contract Signature, 60% Mechanical Installation, 10% Interconnection</fullName>
                </value>
                <value>
                    <fullName>30% Building Permit Approved, 60% Mechanical Installation, 10% Interconnection</fullName>
                </value>
                <value>
                    <fullName>35% Contract Signature, 65% Interconnection</fullName>
                </value>
                <value>
                    <fullName>20% Building Permit Approved, 70% Mechanical Installation, 0% CED Ensemble, 10% Interconnection</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/QueueableDisbursalUpsert.cls
/**
 * Created by abarnes on 12/6/2018.
 */

public class QueueableDisbursalUpsert implements Queueable {

    private Loan__c loan;

    public QueueableDisbursalUpsert(Loan__c newLoan) {
        this.loan = newLoan;
    }

    public void execute(QueueableContext context) {
        Map<String, String> disbursalStatuses = new Map<String, String>();
        Map<String, Decimal> disbursalAmounts = new Map<String, Decimal>();
        List<Disbursal__c> disbursals = new List<Disbursal__c>();
        List<Id> loanIds = new List<Id> {loan.Id};
        List<Loan__c> loanList = new List<Loan__c> {loan};

        Partner__c partner = [SELECT Id, Name FROM Partner__c WHERE Id = :loan.Partner__c];
        Product2 product = [SELECT Id, Disbursal_Terms__c FROM Product2 WHERE Id = :loan.Product__c];

        loan.Product__r = product;
        loan.Partner__r = partner;

        DisbursalHandler dh = new DisbursalHandler();

        loanIds = dh.getLoanIdsFromLoanList(loanList);
        disbursals = dh.getDisbursalsFromLoan(loanIds);
        disbursalStatuses = dh.getDisbursalStatusMap(disbursals);
        disbursalAmounts = dh.getDisbursalAmountMap(disbursals);
        disbursals = dh.createAndTrueUpDisbursals(loanList, disbursalStatuses, disbursalAmounts);
        upsert disbursals Unique_ID__c;
    }

}