src/objects/Energy_Usage_Update__c.object
<CustomObject>
    <description>Energy_Usage_Update__c</description>
    <fields>
        <fullName>Bill_Status__c</fullName>
        <label>Bill Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Host Account Bill Uploaded</fullName>
                </value>
                <value>
                    <fullName>Host Account Bill QCed</fullName>
                </value>
                <value>
                    <fullName>Credit Transfers QCed</fullName>
                </value>
                <value>
                    <fullName>Ready to Generate</fullName>
                </value>
                <value>
                    <fullName>Bills QCed</fullName>
                </value>
                <value>
                    <fullName>Email Bills Sent</fullName>
                </value>
                <value>
                    <fullName>Letter Bills Sent</fullName>
                </value>
                <value>
                    <fullName>Autopay QCed</fullName>
                </value>
                <value>
                    <fullName>Not Billing this Month</fullName>
                </value>
                <value>
                    <fullName>New Production Update</fullName>
                    <isActive>false</isActive>
                    <label>New Production Update</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Billing_Method__c</fullName>
        <formula>TEXT(Shared_Solar_System__r.Billing_Method__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Billing Method</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_Period_End_Date__c</fullName>
        <label>Billing Period End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Billing_Period_Start_Date__c</fullName>
        <label>Billing Period Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Credits_on_Bill_Period__c</fullName>
        <formula>CASE( 
MONTH(Billing_Period_Start_Date__c), 
1, &quot;February&quot;, 
2, &quot;March&quot;, 
3, &quot;April&quot;, 
4, &quot;May&quot;, 
5, &quot;June&quot;, 
6, &quot;July&quot;, 
7, &quot;August&quot;, 
8, &quot;September&quot;, 
9, &quot;October&quot;, 
10, &quot;November&quot;, 
11, &quot;December&quot;, 
&quot;January&quot; 
)&amp;&quot; - &quot;&amp; 
CASE( 
MONTH(Billing_Period_End_Date__c), 
1, &quot;February&quot;, 
2, &quot;March&quot;, 
3, &quot;April&quot;, 
4, &quot;May&quot;, 
5, &quot;June&quot;, 
6, &quot;July&quot;, 
7, &quot;August&quot;, 
8, &quot;September&quot;, 
9, &quot;October&quot;, 
10, &quot;November&quot;, 
11, &quot;December&quot;, 
&quot;January&quot; 
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Credits on Bill Period</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Generate_Bills__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Bills Generated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MonthDate__c</fullName>
        <formula>if( month( Date__c ) == 1, &quot;January&quot;, 
if( month( Date__c ) == 2, &quot;February&quot;, 
if( month( Date__c ) == 3, &quot;March&quot;, 
if( month( Date__c ) == 4, &quot;April&quot;, 
if( month( Date__c ) == 5, &quot;May&quot;, 
if( month( Date__c ) == 6, &quot;June&quot;, 
if( month( Date__c ) == 7, &quot;July&quot;, 
if( month( Date__c ) == 8, &quot;August&quot;, 
if( month( Date__c ) == 9, &quot;September&quot;, 
if( month( Date__c ) == 10, &quot;October&quot;, 
if( month( Date__c ) == 11, &quot;November&quot;, 
if( month( Date__c ) == 12, &quot;December&quot;, null))))))))))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Month</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Month_Number__c</fullName>
        <formula>month(Date__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Month Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Net_Metering_Rate_Applied_2_of_4__c</fullName>
        <label>Net Metering Rate Applied (2 of 4)</label>
        <precision>16</precision>
        <scale>6</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Net_Metering_Rate_Applied_3_of_4__c</fullName>
        <label>Net Metering Rate Applied (3 of 4)</label>
        <precision>16</precision>
        <scale>6</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Net_Metering_Rate_Applied_4_of_4__c</fullName>
        <label>Net Metering Rate Applied (4 of 4)</label>
        <precision>16</precision>
        <scale>6</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Net_Metering_Rate_Applied__c</fullName>
        <label>Net Metering Rate Applied</label>
        <precision>16</precision>
        <scale>6</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Production__c</fullName>
        <label>Production (kWh)</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Production_kWh_2_of_4__c</fullName>
        <label>Production kWh (2 of 4)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Production_kWh_3_of_4__c</fullName>
        <label>Production kWh (3 of 4)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Production_kWh_4_of_4__c</fullName>
        <label>Production kWh (4 of 4)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Schedule_Z__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Allocation Schedule</label>
        <referenceTo>Schedule_Z__c</referenceTo>
        <relationshipLabel>Production Updates</relationshipLabel>
        <relationshipName>Production_Updates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shared_Solar_System__c</fullName>
        <label>Shared Solar System</label>
        <referenceTo>Shared_Solar_System__c</referenceTo>
        <relationshipLabel>Production Updates</relationshipLabel>
        <relationshipName>Production_Updates</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Total_System_NMCs_2_of_4__c</fullName>
        <inlineHelpText>Total credits produced as reported by the utility, including unsubscribed and subscribed credits for 2 of 4</inlineHelpText>
        <label>NMCs Available for Allocation (2 of 4)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_System_NMCs_3_of_4__c</fullName>
        <inlineHelpText>Total credits produced as reported by the utility, including unsubscribed and subscribed credits for 3 of 4</inlineHelpText>
        <label>NMCs Available for Allocation (3 of 4)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_System_NMCs_4_of_4__c</fullName>
        <inlineHelpText>Total credits produced as reported by the utility, including unsubscribed and subscribed credits for 4 of 4</inlineHelpText>
        <label>NMCs Available for Allocation (4 of 4)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_System_NMCs__c</fullName>
        <inlineHelpText>Total credits produced as reported by the utility, including unsubscribed and subscribed credits</inlineHelpText>
        <label>NMCs Available for Allocation</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>YearDate__c</fullName>
        <formula>text(year(Date__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Year</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <label>Production Update</label>
    <nameField>
        <label>Energy Update</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Production Updates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Production__c.object
<CustomObject>
    <fields>
        <fullName>Billing_Method__c</fullName>
        <formula>TEXT(Shared_Solar_System__r.Billing_Method__c)</formula>
        <inlineHelpText>Bills are generated differently depending on NMC or kWh</inlineHelpText>
        <label>Billing Method</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Shared_Solar_System__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Shared Solar System</label>
        <referenceTo>Shared_Solar_System__c</referenceTo>
        <relationshipLabel>Production</relationshipLabel>
        <relationshipName>Production</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Production</label>
    <nameField>
        <label>Production Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Production</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Schedule_Z__c.object
<CustomObject>
    <fields>
        <fullName>Shared_Solar_System__c</fullName>
        <label>Shared Solar System</label>
        <referenceTo>Shared_Solar_System__c</referenceTo>
        <relationshipName>Schedule_Zs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Allocation Schedule</label>
    <nameField>
        <label>Allocation Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Allocation Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Shared_Solar_System__c.object
<CustomObject
     >
    <articleTypeChannelDisplay n1:nil="true" />
    <customSettingsType n1:nil="true" />
    <description n1:nil="true" />
    <eventType n1:nil="true" />
    <fields>
        <fullName>Billing_Method__c</fullName>
        <label>Billing Method</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>NMC</fullName>
                </value>
                <value>
                    <fullName>kWh</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <gender n1:nil="true" />
    <household>false</household>
    <label>Shared Solar System</label>
    <nameField>
        <label>Shared Solar System Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shared Solar Systems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <startsWith n1:nil="true" />
</CustomObject>

src/classes/ProductionUpdateSelector.cls
/* Created by Jordan Pentaleri on 2/11/19
Description: place to hold queries for production updates
Tests: ProductionUpdateSelectorTest
*/

public class ProductionUpdateSelector {
    public static List<Energy_Usage_Update__c> getProductionUpdatesByMonth(Integer billMonth, String billYear) {
        return [
            SELECT Name, Id, Shared_Solar_System__c, Schedule_Z__c,
            YearDate__c, Credits_on_Bill_Period__c,
            MonthDate__c, Total_System_NMCs__c, Production__c,
            Generate_Bills__c, Total_System_NMCs_2_of_4__c,
            Total_System_NMCs_3_of_4__c, Production_kWh_2_of_4__c,
            Production_kWh_3_of_4__c, Total_System_NMCs_4_of_4__c,
            Production_kWh_4_of_4__c, Net_Metering_Rate_Applied__c,
            Billing_Method__c, Date__c, Billing_Period_Start_Date__c,
            Billing_Period_End_Date__c, Month_Number__c, Year__c,
            Net_Metering_Rate_Applied_2_of_4__c,
            Net_Metering_Rate_Applied_3_of_4__c,
            Net_Metering_Rate_Applied_4_of_4__c,
            Shared_Solar_System__r.Name,
            Schedule_Z__r.Name, Bill_Status__c
            FROM Energy_Usage_Update__c
            WHERE Month_Number__c = : billMonth
            AND YearDate__c = : billYear
            ORDER BY Name, Generate_Bills__c
        ];
    }

    public static List<Energy_Usage_Update__c> getAllProductionUpdatesById(List<Id> prodUpdateIdList) {
        return [
            SELECT Name, Id, Shared_Solar_System__c, Schedule_Z__c,
                YearDate__c, Credits_on_Bill_Period__c,
                MonthDate__c, Total_System_NMCs__c, Production__c,
                Generate_Bills__c, Total_System_NMCs_2_of_4__c,
                Total_System_NMCs_3_of_4__c, Production_kWh_2_of_4__c,
                Production_kWh_3_of_4__c, Total_System_NMCs_4_of_4__c,
                Production_kWh_4_of_4__c, Net_Metering_Rate_Applied__c,
                Billing_Method__c, Date__c, Billing_Period_Start_Date__c,
                Billing_Period_End_Date__c, Month_Number__c, Year__c,
                Net_Metering_Rate_Applied_2_of_4__c,
                Net_Metering_Rate_Applied_3_of_4__c,
                Net_Metering_Rate_Applied_4_of_4__c,
                Shared_Solar_System__r.Name,
                Schedule_Z__r.Name, Bill_Status__c
            FROM Energy_Usage_Update__c
            WHERE Id IN : prodUpdateIdList
        ];
    }
}