src/objects/Entity__c.object
<CustomObject>
    <label>Entity</label>
    <nameField>
        <label>Entity</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>ACH_Account_Number__c</fullName>
        <label>ACH Account Number</label>
        <length>20</length>
        <maskChar>asterisk</maskChar>
        <maskType>lastFour</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>ACH_Account_Type__c</fullName>
        <label>ACH Account Type</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ACH_Bank_Name__c</fullName>
        <label>ACH Bank Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ACH_Bank_Routing_Number__c</fullName>
        <label>ACH Bank Routing Number</label>
        <length>20</length>
        <maskChar>asterisk</maskChar>
        <maskType>lastFour</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>ACH_Name_on_Account__c</fullName>
        <label>ACH Name on Account</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CS_Capacity_Allocated__c</fullName>
        <inlineHelpText>Sum of Future Customer Subscription (KW DC) on Utility Account Subscriptions when Opportunity is set to Complete. Used in Docusign.</inlineHelpText>
        <label>Customer Subscription kW DC at Complete</label>
        <precision>9</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Shared_Solar_System__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>To change this system, use the Change SSS quick action</inlineHelpText>
        <label>Shared Solar System</label>
        <referenceTo>Shared_Solar_System__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Utility__c</fullName>
        <formula>IF( 


right(TEXT( Load_Zone_Utility_4__c  ),5) = &apos;SCE&amp;G&apos;,

right(TEXT( Load_Zone_Utility_4__c  ),5),

IF( 


right(TEXT( Load_Zone_Utility_4__c  ),10) = &apos;Eversource&apos;,

right(TEXT( Load_Zone_Utility_4__c  ),10),

IF(

right(TEXT( Load_Zone_Utility_4__c  ),13) = &apos;National Grid&apos;,


right(TEXT( Load_Zone_Utility_4__c  ),13),

IF(

right(TEXT( Load_Zone_Utility_4__c  ),6) = &apos;Unitil&apos;,


right(TEXT( Load_Zone_Utility_4__c  ),6),

IF(

right(TEXT( Load_Zone_Utility_4__c  ),29) = &apos;Municipal Electric Department&apos;,


right(TEXT( Load_Zone_Utility_4__c  ),29),

IF(

TEXT( Load_Zone_Utility_4__c  ) = &apos;Manual Lookup Required&apos;,

&apos;Manual Lookup Required&apos;, null))))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Utility (OLD)</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Service_Territory__c.object
<CustomObject>
    <fields>
        <fullName>Service_Territory__c</fullName>
        <label>Service Territory</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Service Territory</label>
    <nameField>
        <label>Zip Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Territories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Shared_Solar_System__c.object
<CustomObject
     >
    <articleTypeChannelDisplay n1:nil="true" />
    <customSettingsType n1:nil="true" />
    <description n1:nil="true" />
    <eventType n1:nil="true" />
    <fields>
        <fullName>Assemblage_Count__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Assemblage Count</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Assignment_Order__c</fullName>
        <label>Assignment Order</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Capacity_Committed_kW_DC__c</fullName>
        <inlineHelpText>Sum of Complete Small CS Subscriptions</inlineHelpText>
        <label>Committed Small CS Capacity</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Class__c</fullName>
        <formula>IF ( OR( 

Name = &quot;Oxford Barrett St. P2&quot;, Name = &quot;Oxford Barrett St. P1&quot;), &quot;Class 2&quot;,

IF(AND(   Total_System_Size_kW_AC__c &gt; 60, Total_System_Size_kW_AC__c &lt;= 1000), &quot;Class 2&quot;, 

IF ( Total_System_Size_kW_AC__c &gt; 1000, &quot;Class 3&quot;, null)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>MA Specific
Based on size of project (1MW), if the SSS falls into Class II or Class III categories</inlineHelpText>
        <label>System Class</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Credit_Score_Requirement__c</fullName>
        <defaultValue>700</defaultValue>
        <inlineHelpText>Minimum accepted customer FICO score.</inlineHelpText>
        <label>Credit Score Requirement</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Expected_Yield_kWh_kW__c</fullName>
        <inlineHelpText>How much energy (kWh) is produced for every kW of project capacity. If yield increases, every kW of the project will produce more energy, and need more CS offtakers to use that capacity</inlineHelpText>
        <label>Expected Yield (kWh/kW)</label>
        <precision>12</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Open__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Open</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Reserved_Capacity_kW_DC__c</fullName>
        <inlineHelpText>Sum of New, Pending, or QC in Process Small CS subscriptions</inlineHelpText>
        <label>Pending Small CS Capacity</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Territory__c</fullName>
        <label>XXXService Territory</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Duke Energy Carolinas (DEC)</fullName>
                </value>
                <value>
                    <fullName>Duke Energy Progress (DEP)</fullName>
                </value>
                <value>
                    <fullName>NEMA</fullName>
                </value>
                <value>
                    <fullName>SEMA</fullName>
                </value>
                <value>
                    <fullName>WCMA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>System_Utility__c</fullName>
        <label>Utility</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_System_Size_kW_AC__c</fullName>
        <inlineHelpText>Total system size in kW AC.</inlineHelpText>
        <label>Total System Size (kW AC)</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_System_Size_kWh_DC__c</fullName>
        <inlineHelpText>Total system size in kW DC.</inlineHelpText>
        <label>Total System Size (kW DC)</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Utility_NMC_Tariff__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sizing Method</label>
        <referenceTo>Utility_NMC_Tariff__c</referenceTo>
        <relationshipLabel>Shared Solar Systems</relationshipLabel>
        <relationshipName>Shared_Solar_Systems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Utility__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Utility</label>
        <referenceTo>Utility__c</referenceTo>
        <relationshipLabel>Shared Solar Systems</relationshipLabel>
        <relationshipName>Shared_Solar_Systems</relationshipName>
        <type>Lookup</type>
    </fields>
    <gender n1:nil="true" />
    <household>false</household>
    <label>Shared Solar System</label>
    <nameField>
        <label>Shared Solar System Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shared Solar Systems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <startsWith n1:nil="true" />
</CustomObject>

src/objects/Utility__c.object
<CustomObject>
    <fields>
        <fullName>Service_Territory__c</fullName>
        <inlineHelpText>Select the Territory(s) to which the data below will represent.</inlineHelpText>
        <label>XXService Territory</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Duke Energy Progress (DEP)</fullName>
                </value>
                <value>
                    <fullName>Duke Energy Carolinas (DEC)</fullName>
                </value>
                <value>
                    <fullName>All</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Utility</label>
    <nameField>
        <label>Utility Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Utility_NMC_Tariff__c.object
<CustomObject>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Class 2</fullName>
                </value>
                <value>
                    <fullName>Class 3</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sizing_Rate__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sizing Rate</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Utility__c</fullName>
        <label>Utility</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value_of_Net_Metering_Credit__c</fullName>
        <label>Value of Net Metering Credit</label>
        <precision>11</precision>
        <scale>6</scale>
        <type>Currency</type>
    </fields>
    <label>Sizing Method</label>
    <nameField>
        <label>Utility and Class</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sizing Methods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ChargentOrderCreationhandlertest.cls
@isTest
private class ChargentOrderCreationhandlertest {

Static testMethod void ChargentOrderCreationhandlertest (){

        Utility_NMC_Tariff__c eversizeNMC = new Utility_NMC_Tariff__c ( Name = 'Eversource SEMA Class 2', 
                                                                        Utility__c = 'Eversource', 
                                                                        Class__c = 'Class 2',
                                                                        Value_of_Net_Metering_Credit__c = 0.1848,
                                                                        Sizing_Rate__c = TRUE);
        Insert eversizeNMC;

        Entity__c entityOne = new Entity__c ( Name = 'BlueWave ProjectCo');
        Insert entityOne;
        
        Shared_Solar_System__c sss1 = new Shared_Solar_System__c(   Name = 'Oxford Barrett St. P1',
                                                                    Service_Territory__c = 'SEMA',
                                                                    Open__c = true,
                                                                    Reserved_Capacity_kW_DC__c = '0',
                                                                    Capacity_Committed_kW_DC__c = 0,
                                                                    Total_System_Size_kWh_DC__c = 1445.86,
                                                                    Total_System_Size_kW_AC__c  = 996,
                                                                    System_Utility__c = 'Eversource',
                                                                    Credit_Score_Requirement__c = 200,
                                                                    Assignment_order__c = '1',
                                                                    Utility_NMC_Tariff__c = eversizeNMC.Id,
                                                                    Expected_Yield_kWh_kW__c = 1300,
                                                                    Assemblage_Count__c = 1,
                                                                    Sales_Partners__c = 'All',
                                                                    Maximum_Subscription_Assemblage__c = 25);
        insert sss1;

        Account accountA = new Account(name = 'Account A',
            RecordTypeId = '012j00000010Ha3');       
        Insert accountA;  

        ChargentBase__Gateway__c chGateway  = new ChargentBase__Gateway__c(Name = 'BW Community Solar Payments Account Gateway',
                                                                           ChargentBase__Merchant_ID__c = '235986',
                                                                           ChargentBase__Active__c = TRUE,
                                                                           Entity__c = entityOne.Id,
                                                                           Shared_Solar_System__c = sss1.Id);
        insert chGateway;
        
        Opportunity oppone = new Opportunity(Name = 'Jordan Jordan',
                                             AccountId = accountA.Id,
                                             Shared_Solar_System__c = sss1.Id,
                                             StageName = 'Complete',
                                             CS_Capacity_Allocated__c = 25,
                                             CloseDate = System.today());
        insert oppone;
        
        oppone.ACH_Account_Number__c = '123456790';
        oppone.ACH_Account_Type__c = 'Checking';
        oppone.ACH_Bank_Name__c = 'Bank of America';
        oppone.ACH_Bank_Routing_Number__c = '129383578';
        oppone.ACH_Name_on_Account__c = 'Jordan Pentaleri';

        update oppone;

        List <ChargentOrders__ChargentOrder__c > orderlist = [  SELECT Id, ChargentOrders__Bank_Name__c,
                                                                ChargentOrders__Bank_Routing_Number__c, 
                                                                ChargentOrders__Bank_Account_Type__c,
                                                                ChargentOrders__Bank_Account_Number__c, 
                                                                ChargentOrders__Bank_Account_Name__c,
                                                                ChargentOrders__Gateway__c 
                                                                FROM ChargentOrders__ChargentOrder__c];

        Test.StartTest();
        
        for (ChargentOrders__ChargentOrder__c choOrder : orderList) {
            System.assertEquals(choOrder.ChargentOrders__Bank_Name__c,'Bank of America');
            System.assertEquals(choOrder.ChargentOrders__Bank_Routing_Number__c,'129383578');
            System.assertEquals(choOrder.ChargentOrders__Bank_Account_Type__c,'Checking');
            System.assertEquals(choOrder.ChargentOrders__Bank_Account_Number__c,'123456790');
            System.assertEquals(choOrder.ChargentOrders__Bank_Account_Name__c,'Jordan Pentaleri');
            System.assertEquals(choOrder.ChargentOrders__Gateway__c,chGateway.Id);
        }

        Test.StopTest();
        
}
}