src/objects/Error_Log__c.object
<CustomObject>
    <description>Used for custom logging</description>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Severity__c</fullName>
        <inlineHelpText>Severity level used for filtering</inlineHelpText>
        <label>Severity</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Error</fullName>
                </value>
                <value>
                    <fullName>Warn</fullName>
                </value>
                <value>
                    <fullName>Info</fullName>
                </value>
                <value>
                    <fullName>Debug</fullName>
                </value>
                <value>
                    <fullName>Fine</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Error Log</label>
    <nameField>
        <displayFormat>EL-{0000}</displayFormat>
        <label>Error log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ZuoraPaymentRunSchedulerTest.cls
/**
 * Created by peteryao on 12/13/19.
 */
@IsTest
public with sharing class ZuoraPaymentRunSchedulerTest {
    @IsTest
    private static void testPaymentRunCreation() {
        String queryResponse = '[{"DueDate":"2019-11-09"}]';
        ZuoraPaymentRunScheduler paymentRunScheduler = new ZuoraPaymentRunScheduler();
        paymentRunScheduler.executePostQueryJob(null, queryResponse);
        System.assertEquals(1, ZuoraAPIHelper.endpointsCalled.size());
        System.assert(ZuoraAPIHelper.endpointsCalled[0].endpoint.contains('payment-runs'), 'Expected to post a new payment run');
    }

    @IsTest
    private static void testNoPaymentRun() {
        String queryResponse = '[]';
        ZuoraPaymentRunScheduler paymentRunScheduler = new ZuoraPaymentRunScheduler();
        paymentRunScheduler.executePostQueryJob(null, queryResponse);
        System.assertEquals(0, ZuoraAPIHelper.endpointsCalled.size());
        System.assertEquals(1, [SELECT Id FROM Error_Log__c WHERE Severity__c = :Logger.ERROR AND Class__c = 'ZuoraPaymentRunScheduler'].size());
    }

    @IsTest
    private static void testPaymentRunExecute() {
        ZuoraPaymentRunScheduler paymentRunScheduler = new ZuoraPaymentRunScheduler();
        Boolean caughtException = false;
        try {
            Test.startTest();
            System.schedule('TestPaymentRunScheduler', '0 0 9 1 * ? *', paymentRunScheduler);
            Test.stopTest();
        } catch (Exception e) {
            caughtException = true;
        }
        System.assert(!caughtException, 'Expected the scheduled job to run without exception');
    }

}