src/objects/Glynt_Configuration__mdt.object
<CustomObject>
    <fields>
        <fullName>Authorization_Type__c</fullName>
        <inlineHelpText>Select Basic for User Flow, and OAuth for Machine to Machine (https://api.glynt.ai/v6/docs#auth)</inlineHelpText>
        <label>Authorization Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>OAuth</fullName>
                    <default>true</default>
                    <label>OAuth</label>
                </value>
                <value>
                    <fullName>Basic</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Data_Pool_Id__c</fullName>
        <inlineHelpText>e.g. f6qD82</inlineHelpText>
        <label>Data Pool Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Extraction_Processor__c</fullName>
        <inlineHelpText>Class that implements GlyntExtractionService.Processor to process completed extractions</inlineHelpText>
        <label>Extraction Processor</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Extraction_Query_Timeout__c</fullName>
        <inlineHelpText>Minutes to try retrieving an extraction before timing out</inlineHelpText>
        <label>Extraction Query Timeout</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Production__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Indicates this is the production configuration, not for use in sandboxes</inlineHelpText>
        <label>Production</label>
        <type>Checkbox</type>
    </fields>
    <label>Glynt Configuration</label>
    <pluralLabel>Glynt Configurations</pluralLabel>
</CustomObject>

src/objects/Production__c.object
<CustomObject>
    <label>Production</label>
    <nameField>
        <label>Production Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Production</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/GlyntSelector.cls
/**
 * @description Gets Glynt Custom Metadata
 * Tested By: GlyntAPIHelperTest
 */

public without sharing class GlyntSelector {
    public List<Glynt_Configuration__mdt> getGlyntConfiguration() {
        return [
            SELECT Id, Data_Pool_Id__c, Extraction_Processor__c, Extraction_Query_Timeout__c, Authorization_Type__c
            FROM Glynt_Configuration__mdt
            WHERE Production__c = :!Util.isSandboxOrTest()
        ];
    }
}