src/objects/Invoice__c.object
<CustomObject>
    <description>Zuora Invoice object. Invoices are bills that you send to customers.</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Received &gt;&gt; QC</fullName>
                </value>
                <value>
                    <fullName>QC Complete &gt;&gt; Submit to Accounting</fullName>
                </value>
                <value>
                    <fullName>Submitted to Accounting</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner</label>
    <referenceTo>Partner__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <label>Product Line</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Community Solar</fullName>
            </value>
            <value>
                <fullName>Residential Loan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Partner__c.object
<CustomObject>
    <label>Partner</label>
    <nameField>
        <label>Partner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partners</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/PartnerInvoiceSelector.cls
/**
 * Test: PartnerInvoiceSelectorTest
 */
@SuppressWarnings('PMD.ApexCRUDViolation')
public inherited sharing class PartnerInvoiceSelector {
    public List<Invoice__c> getPendingPartnerInvoices(Set<Id> partnerIds, Date dueDate) {
        List<Invoice__c> partnerInvoices = [
            SELECT Id, Partner__c, Due_Date__c
            FROM Invoice__c
            WHERE Partner__c IN : partnerIds
            AND Product_Line__c = 'Community Solar'
            AND Status__c = 'Received >> QC'
            AND Due_Date__c >= : dueDate
            ORDER BY Due_Date__c
        ];
        return partnerInvoices;
    }
}