src/objects/Journal_Entry__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>External_Id__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>200</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Journal Entry</label>
    <nameField>
        <displayFormat>JE-{000000000}</displayFormat>
        <label>Journal Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Journal Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Production__c.object
<CustomObject>
    <label>Production</label>
    <nameField>
        <label>Production Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Production</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Transfer__c.object
<CustomObject>
    <fields>
        <fullName>Transfer_Amount__c</fullName>
        <inlineHelpText>Transfer Amount populated from Utility Account Bill</inlineHelpText>
        <label>Transfer Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Transfer</label>
    <nameField>
        <label>Transfer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transfers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Transfer_Part__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Bill_Part__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bill Part</label>
        <referenceTo>Transfer_Part__c</referenceTo>
        <relationshipName>Bill_Parts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Journal_Entry__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Journal Entry</label>
        <referenceTo>Journal_Entry__c</referenceTo>
        <relationshipName>Transfer_Parts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Production__c</fullName>
        <description>A master-detail relationship from Transfer Parts up to Production</description>
        <label>Production</label>
        <referenceTo>Production__c</referenceTo>
        <relationshipLabel>Production Detail</relationshipLabel>
        <relationshipName>Transfer_Parts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Transfer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>A lookup relationship from Transfer Parts up to Transfer.</description>
        <label>Transfer</label>
        <referenceTo>Transfer__c</referenceTo>
        <relationshipName>Transfer_Parts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Transfer</fullName>
                </value>
                <value>
                    <fullName>Fee</fullName>
                </value>
                <value>
                    <fullName>Incentive Payment</fullName>
                </value>
                <value>
                    <fullName>Unsubscribed Credits</fullName>
                </value>
                <value>
                    <fullName>Customer Savings</fullName>
                </value>
                <value>
                    <fullName>Payment</fullName>
                </value>
                <value>
                    <fullName>Unserviced</fullName>
                </value>
                <value>
                    <fullName>Bill</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Production Detail</label>
    <nameField>
        <label>Transfer Parts Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Production Detail</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ProductionDetailSelector.cls
// Tested by ProductionDetailSelectorTest
@SuppressWarnings('PMD.ApexCRUDViolation')
public inherited sharing class ProductionDetailSelector {
    public Map<Id, List<Transfer_Part__c>> getTransferPartMap(Set<Id> transferIds) {
        Map<Id, List<Transfer_Part__c>> partsMap = new Map<Id, List<Transfer_Part__c>>();
        List<Transfer_Part__c> parts = [
            SELECT Id, Transfer__c, Amount__c, Transfer__r.Transfer_Amount__c, Production__c, Production__r.Name
            FROM Transfer_Part__c
            WHERE Transfer__c IN : transferIds
            AND Type__c = 'Transfer'
        ];

        for (Transfer_Part__c part : parts){
            Id keyValue = part.Transfer__c;
            if (partsMap.containsKey(keyValue)){
                List<Transfer_Part__c> partsList = partsMap.get(keyValue);
                partsList.add(part);
                partsMap.put(keyValue, partsList);
            } else {
                partsMap.put(keyValue, new List<Transfer_Part__c>{part});
            }
        }
        return partsMap;
    }

    public Map<String, List<Transfer_Part__c>> getInvoicePartMap(Set<String> invoiceEntries) {
        Map<String, List<Transfer_Part__c>> partsMap = new Map<String, List<Transfer_Part__c>>();
        List<Transfer_Part__c> parts = [
            SELECT Id, Transfer__c, Amount__c, Transfer__r.Transfer_Amount__c,
                Production__c, Production__r.Name, Journal_Entry__c, Journal_Entry__r.External_Id__c
            FROM Transfer_Part__c
            WHERE Journal_Entry__r.External_Id__c IN : invoiceEntries
            AND Type__c = 'Bill'
        ];

        for (Transfer_Part__c part : parts){
            String keyValue = part.Journal_Entry__r.External_Id__c;
            if (partsMap.containsKey(keyValue)){
                List<Transfer_Part__c> partsList = partsMap.get(keyValue);
                partsList.add(part);
                partsMap.put(keyValue, partsList);
            } else {
                partsMap.put(keyValue, new List<Transfer_Part__c>{part});
            }
        }
        return partsMap;
    }

    public Map<Id,Decimal> getPaymentSum(Set<String> invoiceEntries) {
        Map<Id,Decimal> paymentSumMap = new Map<Id,Decimal>();
        List<AggregateResult> payments = [
            SELECT SUM(Amount__c) sumPayments, Bill_Part__c
            FROM Transfer_Part__c
            WHERE Bill_Part__r.Journal_Entry__r.External_Id__c IN : invoiceEntries
            AND Type__c = 'Payment'
            GROUP BY Bill_Part__c
        ];
        for (AggregateResult payment : payments){
            paymentSumMap.put((Id)payment.get('Bill_Part__c'), (Decimal)payment.get('sumPayments'));
        }
        return paymentSumMap;
    }
}