src/objects/Journal_Entry__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Object_Type__c</fullName>
        <label>Object Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>InvoiceItem</fullName>
                </value>
                <value>
                    <fullName>CreditMemo</fullName>
                </value>
                <value>
                    <fullName>DebitMemo</fullName>
                </value>
                <value>
                    <fullName>PaymentPart</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Reason_Code__c</fullName>
        <inlineHelpText>Debit and Credit Memos Only, Equivalent to Adjustment Type in SF</inlineHelpText>
        <label>Reason Code</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>Journal Entry</label>
    <nameField>
        <displayFormat>JE-{000000000}</displayFormat>
        <label>Journal Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Journal Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Journal_Entry__c/fields/Credit_Memo_Unapplied_Amount__c.field-meta.xml
<CustomField>
    <fullName>Credit_Memo_Unapplied_Amount__c</fullName>
    <inlineHelpText>The Credit Memo amount that is left as a balance to be applied to a future Invoice Item or Debit Memo</inlineHelpText>
    <label>Credit Memo Unapplied Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/objects/Transfer_Part__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Journal_Entry__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Journal Entry</label>
        <referenceTo>Journal_Entry__c</referenceTo>
        <relationshipName>Transfer_Parts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Production Detail</label>
    <nameField>
        <label>Transfer Parts Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Production Detail</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/ProductionToBillJEAuditor.cls
/**
 * Description: Ensures that the ProductionToBillService and manual edits result in Production Details that roll up
 * to Journal Entry amounts
 * Tested By: ProductionToBillAuditorTest
 */

public without sharing class ProductionToBillJEAuditor implements Database.Batchable<SObject>, Database.Stateful {
    public String jesCreatedOrModifiedToday =
        'SELECT Id, Amount__c, Credit_Memo_Unapplied_Amount__c FROM Journal_Entry__c WHERE CreatedDate = TODAY OR LastModifiedDate = TODAY';
    public String jesForPDsCreatedOrModifiedToday =
        'SELECT Id, Amount__c, Credit_Memo_Unapplied_Amount__c\n' +
            'FROM Journal_Entry__c\n' +
            'WHERE CreatedDate != TODAY AND LastModifiedDate != TODAY\n' +
            'AND Id IN (SELECT Journal_Entry__c\n' +
            '           FROM Transfer_Part__c\n' +
            '           WHERE Journal_Entry__c != NULL\n' +
            '           AND (CreatedDate = TODAY OR LastModifiedDate = TODAY))';
    public String query;
    @TestVisible private String errors = '';
    @TestVisible private static JournalEntrySelector journalEntrySelector = new JournalEntrySelector();

    public ProductionToBillJEAuditor() {
        query = jesCreatedOrModifiedToday;
    }

    public Database.QueryLocator start(Database.BatchableContext context) {
        Logger.logNow('ProductionToBillJEAuditor', 'start', 'Starting auditor with query:\n' + query, Logger.FINE);
        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext context, List<Object> scope) {
        try {
            Map<Id, Journal_Entry__c> journalEntryMap = new Map<Id, Journal_Entry__c>((List<Journal_Entry__c>) scope);
            List<AggregateResultProxy> aggregateProductionDetails  = journalEntrySelector.selectForReconciliation(journalEntryMap.values());
            for (AggregateResultProxy aggregateResultProxy : aggregateProductionDetails) {
                reconcileProductionDetailAggregate(aggregateResultProxy, journalEntryMap);
            }
            logJournalEntriesWithoutPDs(journalEntryMap);
        } catch (Exception e) {
            Logger.logNow('ProductionToBillJEAuditor', 'execute', e.getMessage() + '\n' + e.getStackTraceString(), Logger.ERROR);
        }
    }

    private void reconcileProductionDetailAggregate(AggregateResultProxy aggregateResultProxy, Map<Id, Journal_Entry__c> journalEntryMap) {
        Map<String, Object> pdAggregate = aggregateResultProxy.getValuesByAlias();
        Id jeId = (Id) pdAggregate.get('Journal_Entry__c');
        String objectType = (String) pdAggregate.get('Object_Type__c');
        String reasonCode = (String) pdAggregate.get('Reason_Code__c');
        Decimal amount = (Decimal) pdAggregate.get('AMOUNT');
        Journal_Entry__c journalEntry = journalEntryMap.get(jeId);
        Decimal amountToCompare = amount;
        if ((objectType == 'CreditMemo' && reasonCode == 'Production') || objectType == 'DebitMemo') {
            amountToCompare = -amount;
        }
        // The Credit Memo Unapplied Amount will show up as a PD in the future, but for now, add it to the aggregate amount
        amountToCompare += Util.nullToZero(journalEntry.Credit_Memo_Unapplied_Amount__c);
        if (journalEntry.Amount__c != amountToCompare) {
            errors += 'JE: ' + jeId + ', Amount: ' + journalEntry.Amount__c + ', PD Sum: ' + amount +
                ', type: ' + objectType + ', reason:' + reasonCode + '\n';
        }
        journalEntryMap.remove(jeId);
    }

    private void logJournalEntriesWithoutPDs(Map<Id, Journal_Entry__c> journalEntryMap) {
        if (journalEntryMap.isEmpty()) {
            return;
        }
        for (Journal_Entry__c je : journalEntryMap.values()) {
            if (je.Amount__c != 0) {
                errors += 'JE: ' + je.Id + ' has no production details\n';
            }
        }
    }

    public void finish(Database.BatchableContext context) {
        if (errors != '') {
            Logger.logNow('ProductionToBillJEAuditor', 'finish', errors, Logger.ERROR);
        }
        if (!Test.isRunningTest()) {
            queueNextJob();
        }
    }

    @TestVisible
    private Object queueNextJob() {
        if (query == jesCreatedOrModifiedToday) {
            ProductionToBillJEAuditor pdAuditor = new ProductionToBillJEAuditor();
            pdAuditor.query = jesForPDsCreatedOrModifiedToday;
            Database.executeBatch(pdAuditor);
            return pdAuditor;
        } else if (query == jesForPDsCreatedOrModifiedToday) {
            ProductionToBillExServicedUASBAuditor externallyServicedUASBAuditor = new ProductionToBillExServicedUASBAuditor();
            Database.executeBatch(externallyServicedUASBAuditor);
            return externallyServicedUASBAuditor;
        }
        return null;
    }

}