src/objects/Journal_Entry__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Applied_Record_Id__c</fullName>
        <inlineHelpText>For payment part items, either an InvoiceItemId or a DebitMemoId to show what record the payment is applied to</inlineHelpText>
        <label>Applied Record Id</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object_Type__c</fullName>
        <label>Object Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>InvoiceItem</fullName>
                </value>
                <value>
                    <fullName>CreditMemo</fullName>
                </value>
                <value>
                    <fullName>DebitMemo</fullName>
                </value>
                <value>
                    <fullName>PaymentPart</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Reason_Code__c</fullName>
        <inlineHelpText>Debit and Credit Memos Only, Equivalent to Adjustment Type in SF</inlineHelpText>
        <label>Reason Code</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>Journal Entry</label>
    <nameField>
        <displayFormat>JE-{000000000}</displayFormat>
        <label>Journal Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Journal Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Production__c.object
<CustomObject>
    <label>Production</label>
    <nameField>
        <label>Production Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Production</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Transfer__c.object
<CustomObject>
    <label>Transfer</label>
    <nameField>
        <label>Transfer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transfers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Transfer_Part__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Bill_Part__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bill Part</label>
        <referenceTo>Transfer_Part__c</referenceTo>
        <relationshipName>Bill_Parts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Journal_Entry__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Journal Entry</label>
        <referenceTo>Journal_Entry__c</referenceTo>
        <relationshipName>Transfer_Parts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Production__c</fullName>
        <description>A master-detail relationship from Transfer Parts up to Production</description>
        <label>Production</label>
        <referenceTo>Production__c</referenceTo>
        <relationshipLabel>Production Detail</relationshipLabel>
        <relationshipName>Transfer_Parts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Transfer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>A lookup relationship from Transfer Parts up to Transfer.</description>
        <label>Transfer</label>
        <referenceTo>Transfer__c</referenceTo>
        <relationshipName>Transfer_Parts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Transfer</fullName>
                </value>
                <value>
                    <fullName>Fee</fullName>
                </value>
                <value>
                    <fullName>Incentive Payment</fullName>
                </value>
                <value>
                    <fullName>Unsubscribed Credits</fullName>
                </value>
                <value>
                    <fullName>Customer Savings</fullName>
                </value>
                <value>
                    <fullName>Payment</fullName>
                </value>
                <value>
                    <fullName>Unserviced</fullName>
                </value>
                <value>
                    <fullName>Bill</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Production Detail</label>
    <nameField>
        <label>Transfer Parts Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Production Detail</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/ProductionDetailPaymentService.cls
// Tested By: ProductionDetailPaymentTest, ProductionDetailDebitMemoTest
@SuppressWarnings('PMD.ApexCRUDViolation')
public without sharing class ProductionDetailPaymentService implements Database.AllowsCallouts {
    @TestVisible
    private Map<Id, Decimal> partToPaymentMap = new Map<Id, Decimal>();
    public List<Transfer_Part__c> productionDetailToInsert = new List<Transfer_Part__c>();
    @TestVisible
    private static ProductionDetailSelector productionDetailSelector = new ProductionDetailSelector();

    public void createProductionDetailFromCollectionItem(List<Journal_Entry__c> paymentEntries) {
        calculateProductionDetailFromCollectionItem(paymentEntries);
        insert productionDetailToInsert;
    }

    public void calculateProductionDetailFromCollectionItem(List<Journal_Entry__c> paymentEntries) {
        Set<String> invoiceOrDebitMemoIds = new Set<String>();
        for (Journal_Entry__c entry : paymentEntries) {
            invoiceOrDebitMemoIds.add(entry.Applied_Record_Id__c);
        }

        Map<String, List<Transfer_Part__c>> billPartsOrDebitMemoMap = productionDetailSelector.getInvoicePartMap(invoiceOrDebitMemoIds);
        partToPaymentMap = productionDetailSelector.getPaymentSum(invoiceOrDebitMemoIds);

        for (Journal_Entry__c paymentEntry : paymentEntries) {
            List<Transfer_Part__c> invoicePartOrDebitMemo = billPartsOrDebitMemoMap.get(paymentEntry.Applied_Record_Id__c);
            if (invoicePartOrDebitMemo != null) {
                distributePaymentAmongInvoicesOrDebitMemos(paymentEntry, invoicePartOrDebitMemo);
            }
        }
    }

    @TestVisible
    private void distributePaymentAmongInvoicesOrDebitMemos(Journal_Entry__c paymentEntry, List<Transfer_Part__c> invoicePartOrDebitMemos) {
        Decimal paymentAmount = paymentEntry.Amount__c;

        for (Transfer_Part__c invoicePartOrDebitMemo : invoicePartOrDebitMemos) {
            if (paymentAmount <= 0) {
                continue;
            }

            Decimal applicationAmount;
            if (paymentEntry.Object_Type__c == 'DebitMemo') {
                // If the paymentEntry for which we're creating a Production Detail is a Debit Memo, it's a returned payment.
                // invoicePartOrDebitMemo is the PD for the InvoiceItem or DM that the returned payment is applied to - there
                // could be multiple PDs if the invoice item covers multiple production periods, like a920a0000007xuUAAQ.
                // For those cases, we don't want to apply more than the payment amount or the invoicePartOrDebitMemo, but
                // invoicePartOrDebitMemo could be negative (since it could be a Returned Payment Debit Memo like a920a00000080iiAAA).
                // So we need to take the abs of invoicePartOrDebitMemo.
                applicationAmount = Math.min(Math.abs(invoicePartOrDebitMemo.Amount__c), paymentAmount);
            } else {
                Decimal invoicePartPayments = Util.nullToZero(partToPaymentMap.get(invoicePartOrDebitMemo.Id));
                // The Production Details for Debit Memos are negative (they are negative payments), but we need to pay
                // them, so we need to take the abs of that amount.
                Decimal invoicePartBalance = Math.abs(invoicePartOrDebitMemo.Amount__c) - invoicePartPayments;
                if (invoicePartBalance <= 0) {
                    continue;
                }
                applicationAmount = Math.min(invoicePartBalance, paymentAmount);
                invoicePartPayments += applicationAmount;
                partToPaymentMap.put(invoicePartOrDebitMemo.Id, invoicePartPayments);
            }

            productionDetailToInsert.add(createCollectionProductionDetail(paymentEntry, invoicePartOrDebitMemo, applicationAmount));
            paymentAmount -= applicationAmount;
        }
    }

    private Transfer_Part__c createCollectionProductionDetail(Journal_Entry__c paymentEntry, Transfer_Part__c invoicePart, Decimal applicationAmount) {
        Transfer_Part__c payPart = new Transfer_Part__c(
            Name = 'Collection Item',
            Production__c = invoicePart.Production__c,
            Transfer__c = invoicePart.Transfer__c,
            Bill_Part__c = invoicePart.Id,
            Journal_Entry__c = paymentEntry.Id,
            Type__c = (paymentEntry.Reason_Code__c=='No Longer Billing'?'No Longer Billing':'Payment'),
            Amount__c = applicationAmount
        );

        // Returned payments create (-) production details to cancel existing payment record
        if (paymentEntry.Object_Type__c == 'DebitMemo' && paymentEntry.Reason_Code__c == 'Returned Payment') {
            payPart.Name = 'Returned Payment';
            payPart.Amount__c = -applicationAmount;
        }
        return payPart;

    }
}