src/objects/Journal_Entry__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Journal Entry</label>
    <nameField>
        <displayFormat>JE-{000000000}</displayFormat>
        <label>Journal Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Journal Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Transfer_Part__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Bill_Part__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bill Part</label>
        <referenceTo>Transfer_Part__c</referenceTo>
        <relationshipName>Bill_Parts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Journal_Entry__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Journal Entry</label>
        <referenceTo>Journal_Entry__c</referenceTo>
        <relationshipName>Transfer_Parts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Transfer</fullName>
                </value>
                <value>
                    <fullName>Fee</fullName>
                </value>
                <value>
                    <fullName>Incentive Payment</fullName>
                </value>
                <value>
                    <fullName>Unsubscribed Credits</fullName>
                </value>
                <value>
                    <fullName>Customer Savings</fullName>
                </value>
                <value>
                    <fullName>Payment</fullName>
                </value>
                <value>
                    <fullName>Unserviced</fullName>
                </value>
                <value>
                    <fullName>Bill</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Production Detail</label>
    <nameField>
        <label>Transfer Parts Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Production Detail</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/ProductionDetailPaymentTest.cls
/**
 * @description Created by PeterYao on 8/13/2021.
 */
@IsTest
public with sharing class ProductionDetailPaymentTest {
    @IsTest
    public static void testCreateProductionDetailFromCollectionItem() {
        ProductionToBillServiceTest.useMocks();
        List<Transfer_Part__c> beforeBillParts = [
            SELECT Id
            FROM Transfer_Part__c
            WHERE Type__c = 'Payment'
        ];

        System.assertEquals(0, beforeBillParts.size());

        List<Journal_Entry__c> collectionEntries = ProductionToBillServiceTest.getPaymentJournalEntries();
        ProductionDetailPaymentService service = new ProductionDetailPaymentService();
        service.calculateProductionDetailFromCollectionItem(collectionEntries);

        List<Transfer_Part__c> paymentParts = service.productionDetailToInsert;

        System.assertEquals(8, paymentParts.size());

        for (Transfer_Part__c part : paymentParts) {
            switch on String.valueOf(part.Bill_Part__c + '/' + part.Journal_Entry__c) {
                when 'a8y0a000000Gu3rAAA' {
                    // Balance is zero, no part should be made:
                    System.assert(false);
                }
                when 'a8y0a000000Gu3rBBB/a920a000000HuJoAAA' {
                    System.assertEquals(120, part.Amount__c);
                }
                when 'a8y0a000000Gu3rCCC/a920a000000HuJoAAA' {
                    System.assertEquals(1.87, part.Amount__c);
                }
                when 'a8y0a000000Gu3rDDD/a920a000000HuJoAAB' {
                    System.assertEquals(29, part.Amount__c);
                }
                when 'a8y0a000000Gu3rEEE/a920a000000HuJoAAC' {
                    System.assertEquals(30.61, part.Amount__c);
                }
                when 'a8y0a000000Gu3rEEE/a920a000000HuJoAAB' {
                    System.assertEquals(2.72, part.Amount__c);
                }
                when 'a8y0a000000Gu3rFFF/a920a000000HuJoAAC' {
                    System.assertEquals(29.39, part.Amount__c);
                }
                when 'a8y0a000000Gu3rGGG/a920a000000HuJoAAD' {
                    System.assertEquals(37.23, part.Amount__c);
                }
                when 'a8y0a000000Gu3rGGG/a920a000000HuJoAAE' {
                    System.assertEquals(62.55, part.Amount__c);
                }
                when else {
                    System.assert(false);
                }
            }
        }
    }
}