src/objects/Journal_Entry__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Applied_Record_Id__c</fullName>
        <inlineHelpText>For payment part items, either an InvoiceItemId or a DebitMemoId to show what record the payment is applied to</inlineHelpText>
        <label>Applied Record Id</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client Unique Id</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Account__c</fullName>
        <label>Customer Unique Id</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Lookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Journal Entries (Customer Account)</relationshipLabel>
        <relationshipName>Journal_Entries1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Deposit_Account__c</fullName>
        <inlineHelpText>Either Gateway or Lockbox that a payment was accepted into</inlineHelpText>
        <label>Deposit Account</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>External_Id__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>200</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Object_Type__c</fullName>
        <label>Object Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>InvoiceItem</fullName>
                </value>
                <value>
                    <fullName>CreditMemo</fullName>
                </value>
                <value>
                    <fullName>DebitMemo</fullName>
                </value>
                <value>
                    <fullName>PaymentPart</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Paid_To_Client__c</fullName>
        <inlineHelpText>The client to whom payments were directed. Ie, the owner of the gateway or lockbox at the time of the payment</inlineHelpText>
        <label>Paid To Client</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project Unique Id</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Query_Type__c</fullName>
        <inlineHelpText>When we download data from Zuora, we use 5 different types of queries. Same as object type, but query for Payment Parts applied to Debit Memos and those applied to Invoices separately</inlineHelpText>
        <label>Query Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>InvoiceItem</fullName>
                </value>
                <value>
                    <fullName>CreditMemo</fullName>
                </value>
                <value>
                    <fullName>DebitMemo</fullName>
                </value>
                <value>
                    <fullName>PaymentPart_DM</fullName>
                </value>
                <value>
                    <fullName>PaymentPart_IV</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Ready_for_Production_Detail__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Marked as true on insert, marked as false once production detail records are created</inlineHelpText>
        <label>Ready for Production Detail</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Reason_Code__c</fullName>
        <inlineHelpText>Debit and Credit Memos Only, Equivalent to Adjustment Type in SF</inlineHelpText>
        <label>Reason Code</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Returned_PaymentPart_Id__c</fullName>
        <inlineHelpText>Set by the ZuoraGLService. Relateds a debit memo to a PaymentPartItem so the P2B process can create (-) Production Details to reduce Credits Paid for same Production period</inlineHelpText>
        <label>Returned Payment Part Id</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>Journal Entry</label>
    <nameField>
        <displayFormat>JE-{000000000}</displayFormat>
        <label>Journal Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Journal Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Transfer_Part__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Journal_Entry__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Journal Entry</label>
        <referenceTo>Journal_Entry__c</referenceTo>
        <relationshipName>Transfer_Parts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Production Detail</label>
    <nameField>
        <label>Transfer Parts Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Production Detail</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/JournalEntrySelector.cls
// Tested By: JournalEntrySelectorTest, PartnerCommissionServiceTest, ZuoraGLServiceTest

@SuppressWarnings('PMD.ApexCRUDViolation')
public inherited sharing class JournalEntrySelector {
    public List<Journal_Entry__c> getSFJournalEntries(Date startDate, Date endDate, String queryType) {
        List<Journal_Entry__c> journalEntries = [
            SELECT Id, External_Id__c, Date__c, Amount__c, Project__c, Client__c, Customer_Account__c,
                Paid_To_Client__c, Deposit_Account__c
            FROM Journal_Entry__c
            WHERE Date__c >= :startDate
            AND Date__c < :endDate
            AND Query_Type__c = :queryType
        ];
        return journalEntries;
    }

    public List<AggregateResultProxy> getCommissionEntriesByAccount(Set<String> accountNumber) {
        List<AggregateResultProxy> groupedResultProxies = new List<AggregateResultProxy>();
        for (AggregateResult result : [
            SELECT Customer_Account__c,Object_Type__c,Project__c
            FROM Journal_Entry__c
            WHERE Customer_Account__c IN :accountNumber
            AND (Object_Type__c = 'InvoiceItem' OR Object_Type__c = 'PaymentPart')
            AND Amount__c != 0
            GROUP BY Customer_Account__c, Object_Type__c, Project__c
        ]) {
            groupedResultProxies.add(new AggregateResultProxy().withAggregateResult(result));
        }
        return groupedResultProxies;
    }

    public List<Journal_Entry__c> getSFJournalEntriesFromExternalId(Set<String> externalIds) {
        List<Journal_Entry__c> journalEntries = [
            SELECT Id, External_Id__c, Date__c, Amount__c, Project__c, Client__c, Customer_Account__c,
                Paid_To_Client__c, Deposit_Account__c, Object_Type__c, Query_Type__c, Applied_Record_Id__c
            FROM Journal_Entry__c
            WHERE External_Id__c IN :externalIds
        ];
        return journalEntries;
    }

    public List<Journal_Entry__c> getEntriesWithoutProductionDetail(List<String> objectTypes, Integer batchSize) {
        List<Journal_Entry__c> journalEntries = [
            SELECT Id, Name, External_Id__c, Date__c, Amount__c, Project__c, Client__c, Customer_Account__c, Paid_To_Client__c,
                Deposit_Account__c, Applied_Record_Id__c, Reason_Code__c, Object_Type__c, Returned_PaymentPart_Id__c,
                CreatedDate, (SELECT Id FROM Transfer_Parts__r)
            FROM Journal_Entry__c
            WHERE Object_Type__c IN :objectTypes
            AND Ready_for_Production_Detail__c = TRUE
            ORDER BY Date__c, Name
            LIMIT :batchSize
        ];
        return journalEntries;
    }

    public Map<String, Journal_Entry__c> getEntriesMapByIds(Set<String> externalIds) {
        Map<String, Journal_Entry__c> entryMap = new Map<String, Journal_Entry__c>();
        for (Journal_Entry__c entry : [SELECT Id, Applied_Record_Id__c, External_Id__c FROM Journal_Entry__c WHERE External_Id__c IN :externalIds]) {
            entryMap.put(entry.External_Id__c, entry);
        }
        return entryMap;
    }

    public List<Journal_Entry__c> getCommissionableEntriesFromToday() {
        return [
            SELECT Customer_Lookup__c, Project__c, Date__c, Object_Type__c, Customer_Account__c
            FROM Journal_Entry__c
            WHERE CreatedDate = TODAY
            AND (Object_Type__c = 'InvoiceItem' OR Object_Type__c = 'PaymentPart')
            AND Amount__c != 0
            ORDER BY Date__c ASC
        ];
    }

    public List<AggregateResultProxy> selectForReconciliation(List<Journal_Entry__c> journalEntriesToReconcile) {
        List<AggregateResultProxy> groupedResultProxies = new List<AggregateResultProxy>();
        for (AggregateResult result : [
            SELECT Journal_Entry__c, Journal_Entry__r.Reason_Code__c, Journal_Entry__r.Object_Type__c, SUM(Amount__c) AMOUNT
            FROM Transfer_Part__c
            WHERE Journal_Entry__c IN :journalEntriesToReconcile
            GROUP BY Journal_Entry__c, Journal_Entry__r.Reason_Code__c, Journal_Entry__r.Object_Type__c
        ]) {
            groupedResultProxies.add(new AggregateResultProxy().withAggregateResult(result));
        }
        return groupedResultProxies;
    }
}