src/objects/LASERCA__Personal_Credit_Report__c.object
<CustomObject>
    <description>Experian Personal Credit Report, direct connect to Experian</description>
    <label>Personal Credit Report</label>
    <nameField>
        <label>Personal Credit Report Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Personal Credit Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Personal_Credit_Report_Co_Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Personal Credit Report (Co-Applicant)</label>
        <referenceTo>LASERCA__Personal_Credit_Report__c</referenceTo>
        <relationshipLabel>Leads (Personal Credit Report (Co-Applicant))</relationshipLabel>
        <relationshipName>Leads2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Personal_Credit_Report__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Personal Credit Report</label>
        <referenceTo>LASERCA__Personal_Credit_Report__c</referenceTo>
        <relationshipLabel>Leads (Personal Credit Report)</relationshipLabel>
        <relationshipName>Leads1</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Lead</fullName>
        <active>true</active>
        <businessProcess>CS</businessProcess>
        <label>Lead</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/QueueableApplicationReview.cls
/**
 * Created by mstackhouse on 7/3/2018.
 * Description: 
 * Test: 
 */


public class QueueableApplicationReview implements Queueable {
    public static Id leadId;

    public QueueableApplicationReview(Lead queuedLead) {
        leadId = queuedLead.Id;
    }

    public void execute(QueueableContext context) {
        PCRApprovalHandler pcrApprovalHandler = new PCRApprovalHandler();
        Lead lead = pcrApprovalHandler.getLeadsForCreditAnalysis(new Set<Id>{leadId})[0];
        if (pcrApprovalHandler.leadReadyForPrequalCheck(lead)) {
            List<LASERCA__Personal_Credit_Report__c> pcrsToUpdate = new List<LASERCA__Personal_Credit_Report__c>();
            lead = pcrApprovalHandler.runCreditReviewProcess(lead, null, null);
            update lead;
            pcrsToUpdate.add(lead.Personal_Credit_Report__r);
            if (lead.Personal_Credit_Report_Co_Applicant__c != null) {
                pcrsToUpdate.add(lead.Personal_Credit_Report_Co_Applicant__r);
            }
            update pcrsToUpdate;
        } else if (!Test.isRunningTest()) {
            System.enqueueJob(new QueueableApplicationReview(lead));
        }
    }
}