src/objects/LASERCA__Personal_Credit_Report__c.object
<CustomObject>
    <description>Experian Personal Credit Report, direct connect to Experian</description>
    <fields>
        <fullName>LASERCA__Credit_Score_TransUnion__c</fullName>
        <label>Credit Score (TransUnion)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Personal Credit Report</label>
    <nameField>
        <label>Personal Credit Report Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Personal Credit Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Customer_type__c</fullName>
        <label>Customer type</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LASER_Credit_Score__c</fullName>
        <formula>Personal_Credit_Report__r.LASERCA__Credit_Score__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>LASER Credit Score</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LoadZone__c</fullName>
        <inlineHelpText>Text Field (ex. SEMA, NEMA) If in a split load zone, this field will be populated with both until resolved (SEMA/NEMA)</inlineHelpText>
        <label>Load Zone</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Moody_s_Risk_Calc__c</fullName>
        <inlineHelpText>Score returned from Moody&apos;s Rrisk Calc engine</inlineHelpText>
        <label>Moody&apos;s Risk Calc</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Moody_s_Ratings</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Personal_Credit_Report__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Personal Credit Report</label>
        <referenceTo>LASERCA__Personal_Credit_Report__c</referenceTo>
        <relationshipLabel>Leads (Personal Credit Report)</relationshipLabel>
        <relationshipName>Leads1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Product lookup, for loans, set by an installer upon sending a new application or set by code after a credit check has determined qualifying products.</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Referral_Name__c</fullName>
        <inlineHelpText>Please enter the name of the person who referred you.</inlineHelpText>
        <label>Referral Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Underwriting_Criteria__c</fullName>
        <defaultValue>&apos;None&apos;</defaultValue>
        <inlineHelpText>What method we used to underwrite the customer. Investment-Grade and Financial Review are limited to anchors.</inlineHelpText>
        <label>Underwriting Criteria</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Underwriting_Criteria</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Utility__c</fullName>
        <formula>IF(INCLUDES(  Utility_1__c , &quot;Eversource&quot;), &quot;Eversource&quot;, 
IF(INCLUDES(  Utility_1__c , &quot;National Grid&quot;), &quot;National Grid&quot;,
IF(INCLUDES(  Utility_1__c , &quot;Unitil&quot;), &quot;Unitil&quot;,
IF(INCLUDES(  Utility_1__c , &quot;Municipal Electric Department&quot;), &quot;Municipal Electric Department&quot;,
IF(INCLUDES(  Utility_1__c , &quot;Duke Energy&quot;), &quot;Duke Energy&quot;, 
IF(INCLUDES(  Utility_1__c , &quot;SCE&amp;G&quot;), &quot;SCE&amp;G&quot;, 
 &quot;Other&quot;))))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>XXXXX Utility</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Utility_relationship__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Utility</label>
        <referenceTo>Utility__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Lead</fullName>
        <active>true</active>
        <businessProcess>CS</businessProcess>
        <label>Lead</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Ignore_Load_Zones_When_Qualifying__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Determines whether or not Load Zones should be considered when qualifying a lead</inlineHelpText>
        <label>Ignore Load Zones When Qualifying</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Shared_Solar_System__c.object
<CustomObject
     >
    <articleTypeChannelDisplay n1:nil="true" />
    <customSettingsType n1:nil="true" />
    <description n1:nil="true" />
    <eventType n1:nil="true" />
    <fields>
        <fullName>Anchor_Capacity_Reserved__c</fullName>
        <inlineHelpText>Sum of all Anchor Subscriptions</inlineHelpText>
        <label>Committed Anchor Capacity</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Available_SMB_Underwriting_Method_Docs__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Available SMB Underwriting Method: Docs</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Available_SMB_Underwriting_Method_FICO__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Used by the QualificationService for both SMB and Resi customers</inlineHelpText>
        <label>Available Underwriting Method: FICO</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Capacity_Committed_kW_DC__c</fullName>
        <inlineHelpText>Sum of Complete Small CS Subscriptions</inlineHelpText>
        <label>Committed Small CS Capacity</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Credit_Score_Requirement__c</fullName>
        <defaultValue>700</defaultValue>
        <inlineHelpText>Minimum accepted customer FICO score.</inlineHelpText>
        <label>Credit Score Requirement</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Open__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Open</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Primary customer product.</inlineHelpText>
        <label>Default Enrollment Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Shared Solar Systems</relationshipLabel>
        <relationshipName>Shared_Solar_Systems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Public__c</fullName>
        <defaultValue>false</defaultValue>
        <label>XXXPublic</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Reserved_Anchor_Capacity__c</fullName>
        <inlineHelpText>Manual input for reserved anchor and public offtake capacity when under Onboarding or Acquisition stage</inlineHelpText>
        <label>Reserved Anchor Capacity</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Reserved_Capacity_kW_DC__c</fullName>
        <inlineHelpText>Sum of New, Pending, or QC in Process Small CS subscriptions</inlineHelpText>
        <label>Pending Small CS Capacity</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RiskCalc_Minimum__c</fullName>
        <label>RiskCalc Minimum</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Moody_s_Ratings</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Service_Territories__c</fullName>
        <label>Service Territories</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Service_Territories</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_System_Size_kWh_DC__c</fullName>
        <inlineHelpText>Total system size in kW DC.</inlineHelpText>
        <label>Total System Size (kW DC)</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Utility__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Utility</label>
        <referenceTo>Utility__c</referenceTo>
        <relationshipLabel>Shared Solar Systems</relationshipLabel>
        <relationshipName>Shared_Solar_Systems</relationshipName>
        <type>Lookup</type>
    </fields>
    <gender n1:nil="true" />
    <household>false</household>
    <label>Shared Solar System</label>
    <nameField>
        <label>Shared Solar System Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shared Solar Systems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <startsWith n1:nil="true" />
</CustomObject>

src/objects/Utility__c.object
<CustomObject>
    <label>Utility</label>
    <nameField>
        <label>Utility Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Moody_s_Ratings.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Aaa</fullName>
    </customValue>
    <customValue>
        <fullName>Aa1</fullName>
    </customValue>
    <customValue>
        <fullName>Aa2</fullName>
    </customValue>
    <customValue>
        <fullName>Aa3</fullName>
    </customValue>
    <customValue>
        <fullName>A1</fullName>
    </customValue>
    <customValue>
        <fullName>A2</fullName>
    </customValue>
    <customValue>
        <fullName>A3</fullName>
    </customValue>
    <customValue>
        <fullName>Baa1</fullName>
    </customValue>
    <customValue>
        <fullName>Baa2</fullName>
    </customValue>
    <customValue>
        <fullName>Baa3</fullName>
    </customValue>
    <customValue>
        <fullName>Ba1</fullName>
    </customValue>
    <customValue>
        <fullName>Ba2</fullName>
    </customValue>
    <customValue>
        <fullName>Ba3</fullName>
    </customValue>
    <customValue>
        <fullName>B1</fullName>
    </customValue>
    <customValue>
        <fullName>B2</fullName>
    </customValue>
    <customValue>
        <fullName>B3</fullName>
    </customValue>
    <customValue>
        <fullName>Caa1</fullName>
    </customValue>
    <customValue>
        <fullName>Caa2</fullName>
    </customValue>
    <customValue>
        <fullName>Ca</fullName>
    </customValue>
    <customValue>
        <fullName>C</fullName>
    </customValue>
    <masterLabel>Moody&apos;s Ratings</masterLabel>
</GlobalValueSet>

src/globalValueSets/Service_Territories.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>NEMA</fullName>
    </customValue>
    <customValue>
        <fullName>SEMA</fullName>
    </customValue>
    <customValue>
        <fullName>WCMA</fullName>
    </customValue>
    <customValue>
        <fullName>MN</fullName>
    </customValue>
    <customValue>
        <fullName>Capital</fullName>
    </customValue>
    <customValue>
        <fullName>Hudson Valley</fullName>
    </customValue>
    <customValue>
        <fullName>Mohawk Valley</fullName>
    </customValue>
    <customValue>
        <fullName>Central</fullName>
    </customValue>
    <customValue>
        <fullName>Genesee</fullName>
    </customValue>
    <customValue>
        <fullName>Dunwoodie</fullName>
    </customValue>
    <customValue>
        <fullName>N.Y.C.</fullName>
    </customValue>
    <customValue>
        <fullName>Millwood</fullName>
    </customValue>
    <customValue>
        <fullName>Long Island</fullName>
    </customValue>
    <customValue>
        <fullName>North</fullName>
    </customValue>
    <customValue>
        <fullName>West</fullName>
    </customValue>
    <customValue>
        <fullName>Maine</fullName>
    </customValue>
    <customValue>
        <fullName>Maine Public Service</fullName>
    </customValue>
    <customValue>
        <fullName>Bangor Hydro</fullName>
    </customValue>
    <masterLabel>Service Territories</masterLabel>
</GlobalValueSet>

src/globalValueSets/Underwriting_Criteria.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>FICO</fullName>
        <default>true</default>
        <label>FICO</label>
    </customValue>
    <customValue>
        <fullName>Investment-Grade</fullName>
    </customValue>
    <customValue>
        <fullName>Financial Review</fullName>
    </customValue>
    <customValue>
        <fullName>Past Payment History</fullName>
    </customValue>
    <customValue>
        <fullName>None</fullName>
    </customValue>
    <masterLabel>Underwriting Criteria</masterLabel>
</GlobalValueSet>

src/classes/InvocableLeadQualificationTest.cls
/**
 * Created by: Kristin White on 12/17/2020
 * 
 */
@IsTest
public with sharing class InvocableLeadQualificationTest {
    
    @TestSetup 
    public static void testSetup() {
        Product2 product1 = new Product2(
            Name = 'testProduct1',
            Ignore_Load_Zones_When_Qualifying__c = True
        );
        insert product1;
        
        Utility__c utility1 = new Utility__c(
            Name = 'testUtility1'
        );
        insert utility1;
        
        LASERCA__Personal_Credit_Report__c pcr1 = new LASERCA__Personal_Credit_Report__c(
            LASERCA__Credit_Score_TransUnion__c = '100'
        );        
        insert pcr1;
        
        Lead lead1 = new Lead (
            Customer_type__c = 'Commercial',
            LastName = 'testLead1',
            Referral_Name__c = 'testLead1',
            Company = 'testBlueWave1',
            Status = 'New',
            Moody_s_Risk_Calc__c = 'Aaa',
            Personal_Credit_Report__c = pcr1.Id,
            Utility_relationship__c = utility1.Id,
            LoadZone__c = 'SEMA',
            Product__c = null,
            Underwriting_Criteria__c = 'Financial Review'
        ); 
        insert lead1;
        
        Shared_Solar_System__c sss1 = new Shared_Solar_System__c(
            RiskCalc_Minimum__c = 'Ba3', 
            Open__c = True, 
            Name = 'testSSS1',
            Utility__c = utility1.Id,
            Product__c = product1.Id,
            Service_Territories__c = 'SEMA',
            Public__c = True,
            Credit_Score_Requirement__c = 10,
            Capacity_Committed_kW_DC__c = 100,
            Reserved_Capacity_kW_DC__c = '100',
            Anchor_Capacity_Reserved__c = 10,
            Reserved_Anchor_Capacity__c = 10,
            Total_System_Size_kWh_DC__c = 500,
            Available_SMB_Underwriting_Method_Docs__c = True,
            Available_SMB_Underwriting_Method_FICO__c = True
        );   
        insert SSS1;
    }
    
    private static Shared_Solar_System__c getTestSSS(String name) {
        return [
            SELECT Id, Name, Open__c, RiskCalc_Minimum__c, Utility__c, Product__c, Public__c, 
            Credit_Score_Requirement__c, Capacity_Committed_kW_DC__c, Reserved_Capacity_kW_DC__c, 
            Anchor_Capacity_Reserved__c, Reserved_Anchor_Capacity__c, Total_System_Size_kWh_DC__c, 
            Available_SMB_Underwriting_Method_Docs__c, Available_SMB_Underwriting_Method_FICO__c 
            FROM Shared_Solar_System__c
            WHERE Name = :name
        ];
    }
    
    private static Lead getTestLead(String referralName) {
        return [
            SELECT Id, Referral_Name__c, Moody_s_Risk_Calc__c, Status, LASER_Credit_Score__c
            FROM Lead
            WHERE Referral_Name__c = :referralName
        ];
    }
    
    @IsTest
    static void testQualifiedFICOLead() {
        List<Id> leadList = new List<Id>();
        Lead lead = getTestLead('testLead1');
        lead.Underwriting_Criteria__c = 'FICO';
        update lead;
        leadList.add(lead.Id);
        InvocableLeadQualification.runLeadQualificationCheck(leadList);
        Lead updatedLead = getTestLead('testLead1');
        System.assertEquals('Qualified', updatedLead.Status, 'The lead.Status should update to Qualified becuase ' + 
                            'the lead.LASER_Credit_Score__c is greater than the sss.Credit_Score_Requirement__c');
    }
    
    @IsTest
    static void testUnqualifiedFICOLead() {
        List<Id> leadList = new List<Id>();
        Lead lead = getTestLead('testLead1');
        lead.Underwriting_Criteria__c = 'FICO';
        update lead;
        Shared_Solar_System__c sss = getTestSSS('testSSS1');
        sss.Available_SMB_Underwriting_Method_FICO__c = False;
        update sss;
        leadList.add(lead.Id);
        InvocableLeadQualification.runLeadQualificationCheck(leadList);
        Lead updatedLead = getTestLead('testLead1');
        System.assertEquals('Unqualified', updatedLead.Status, 'The lead.Status should update to Qualified becuase ' + 
                            'the Available_SMB_Underwriting_Method_FICO__c is false.');
    }
    
    @IsTest
    static void testNullMoodysFinReviewLead() {
        List<Id> leadList = new List<Id>();
        Lead lead = getTestLead('testLead1');
        lead.Moody_s_Risk_Calc__c = null;
        update lead;
        leadList.add(lead.Id);
        InvocableLeadQualification.runLeadQualificationCheck(leadList);
        Lead updatedLead = getTestLead('testLead1');
        System.assertEquals('Unqualified', updatedLead.Status, 'The lead.Status should update to Unqualified because ' + 
                            'the Moody RiskCalc is null.');
    }
    
    @IsTest
    static void testNullRiskCalcMinFinReviewLead() {
        List<Id> leadList = new List<Id>();
        Lead lead = getTestLead('testLead1');
        Shared_Solar_System__c sss = getTestSSS('testSSS1');
        sss.RiskCalc_Minimum__c = null;
        update sss;
        leadList.add(lead.Id);
        InvocableLeadQualification.runLeadQualificationCheck(leadList);
        Lead updatedLead = getTestLead('testLead1');
        System.assertEquals('Unqualified', updatedLead.Status, 'The lead.Status should update to Unqualified becuase ' + 
                            'the RiskCalc Minimum is null.');
    }
    
    @IsTest
    static void testFalseAvailableSMBFinReviewLead() {
        List<Id> leadList = new List<Id>();
        Lead lead = getTestLead('testLead1');
        Shared_Solar_System__c sss = getTestSSS('testSSS1');
        sss.Available_SMB_Underwriting_Method_Docs__c = False;
        update sss;
        leadList.add(lead.Id);
        InvocableLeadQualification.runLeadQualificationCheck(leadList);
        Lead updatedLead = getTestLead('testLead1');
        System.assertEquals('Unqualified', updatedLead.Status, 'The lead.Status should update to Unqualified becuase ' + 
                            'the Available_SMB_Underwriting_Method_Docs__c is false.');
    }
    
    @IsTest
    static void testMoodyScoresFinReviewLead() {
        List<Id> leadList = new List<Id>();
        Lead lead = getTestLead('testLead1');
        leadList.add(lead.Id);
        InvocableLeadQualification.runLeadQualificationCheck(leadList);
        Lead updatedLead1 = getTestLead('testLead1');
        System.assertEquals('Qualified', updatedLead1.Status, 'The lead.Status should update to Qualified becuase ' + 
                            'the Moody score is above the RiskCalc Min.');
        
        lead.Moody_s_Risk_Calc__c = 'Ba3';
        update lead;
        InvocableLeadQualification.runLeadQualificationCheck(leadList);
        Lead updatedLead2 = getTestLead('testLead1');
        System.assertEquals('Qualified', updatedLead2.Status, 'The lead.Status should update to Qualified becuase ' + 
                            'the Moody score is equal to the RiskCalc Min.');
        
        lead.Moody_s_Risk_Calc__c = 'Caa1';
        update lead;
        InvocableLeadQualification.runLeadQualificationCheck(leadList);
        Lead updatedLead3 = getTestLead('testLead1');
        System.assertEquals('Unqualified', updatedLead3.Status, 'The lead.Status should update to Unqualified becuase ' + 
                            'the Moody score is less than the RiskCalc Min.');
    }
    
    
    
}