src/objects/LASERCA__Personal_Credit_Report__c.object
<CustomObject>
    <description>Experian Personal Credit Report, direct connect to Experian</description>
    <fields>
        <fullName>LASERCA__Credit_Score__c</fullName>
        <label>Credit Score</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LASERCA__Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Personal Credit Reports</relationshipLabel>
        <relationshipName>Personal_Credit_Reports</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LASERCA__Total_High_Credit__c</fullName>
        <label>Total High Credit</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Personal Credit Report</label>
    <nameField>
        <label>Personal Credit Report Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Personal Credit Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Annual_Income_Currency__c</fullName>
        <label>Annual Income</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>FICO_Score_Approval__c</fullName>
        <label>FICO Score Approval</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>debt_income_status__c</fullName>
        <label>Debt/Income Approval (DEACTIVATE)</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Lead</fullName>
        <active>true</active>
        <businessProcess>CS</businessProcess>
        <label>Lead</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/mapDebtToIncomeTestClass.cls
@isTest
private class mapDebtToIncomeTestClass {

Static testMethod void mapDebtToIncomeTest(){

lead newLead = new lead(firstName = 'Cole', lastName = 'Swain', company = 'BlueWave', status = 'contacted', annual_income_currency__c = 105000) ;

LASERCA__Personal_Credit_Report__c newPCR = new LASERCA__Personal_Credit_Report__c ( name = 'TestCase', LASERCA__Total_High_Credit__c =50000, LASERCA__Credit_Score__c= '715', LASERCA__Lead__c = newLead.id);

Insert newPCR;

test.startTest();
 
insert newLead;
 
test.stopTest();
 
lead leadQuery = [SELECT FICO_score_approval__c, Debt_Income_Status__c FROM lead WHERE firstName = 'Cole'];
 
system.assertEquals(null, leadQuery.FICO_score_approval__c);
 
 
}
}