src/objects/LASERCA__Personal_Credit_Report__c.object
<CustomObject>
    <description>Experian Personal Credit Report, direct connect to Experian</description>
    <fields>
        <fullName>LASERCA__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Guarantors&apos; credit to be run
If this holds a value, DTI is calculated off Coapplicant Income</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Personal Credit Report</relationshipLabel>
        <relationshipName>Personal_Credit_Reports</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LASERCA__Credit_Score__c</fullName>
        <label>Credit Score</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LASERCA__Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Personal Credit Reports</relationshipLabel>
        <relationshipName>Personal_Credit_Reports</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Personal Credit Report</label>
    <nameField>
        <label>Personal Credit Report Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Personal Credit Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Application_Complete_Date__c</fullName>
        <description>Date Flow application is completed.</description>
        <inlineHelpText>Date Flow application is completed.</inlineHelpText>
        <label>Application Complete Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Personal_Credit_Report__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Personal Credit Report</label>
        <referenceTo>LASERCA__Personal_Credit_Report__c</referenceTo>
        <relationshipLabel>Leads (Personal Credit Report)</relationshipLabel>
        <relationshipName>Leads1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/CreditReportSelector.cls
/**
 * @description Created by SarahRenfro on 3/10/2021.
 * TestedBy: CSQualificationTestclass
 */
@SuppressWarnings('PMD.ApexCRUDViolation')
public without sharing class CreditReportSelector {

    public List<LASERCA__Personal_Credit_Report__c> getCompletedPCRs(Set<Id> pcrIds) {
        return [
            SELECT Id, LASERCA__Lead__c, LASERCA__Lead__r.Personal_Credit_Report__c, LASERCA__Lead__r.Application_Complete_Date__c,
                LASERCA__Contact__c, Lead_from_Contact__c, LASERCA__Credit_Score__c
            FROM LASERCA__Personal_Credit_Report__c
            WHERE Id = :pcrIds
        ];
    }
}