src/objects/LASERCA__Personal_Credit_Report__c.object
<CustomObject>
    <description>Experian Personal Credit Report, direct connect to Experian</description>
    <label>Personal Credit Report</label>
    <nameField>
        <label>Personal Credit Report Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Personal Credit Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Automatic_Product_Assignment__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Automatic Product Assignment</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LASERCA__Home_State__c</fullName>
        <label>Home State</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LASER_Credit_Score__c</fullName>
        <formula>Personal_Credit_Report__r.LASERCA__Credit_Score__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>LASER Credit Score</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Loan_Financing_Fee__c</fullName>
        <label>Loan Financing Fee</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product_Program__c</fullName>
        <description>This designates what program the customer&apos;s product is a part of. It gets its value from the product record relates to this lead. An example would be Perch&apos;s Solar Loan took part in the Massachusetts Solar Loan Program so the program would be MSLP.</description>
        <inlineHelpText>This designates what program the customer&apos;s product is a part of. It gets its value from the product record relates to this lead. An example would be Perch&apos;s Solar Loan took part in the Massachusetts Solar Loan Program so the program would be MSLP.</inlineHelpText>
        <label>Product Program</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>BlueWave Solar Loan</fullName>
                </value>
                <value>
                    <fullName>MSLP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Product lookup, for loans, set by an installer upon sending a new application or set by code after a credit check has determined qualifying products.</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_line__c</fullName>
        <label>Product Line</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Technology_Platform_Fee__c</fullName>
        <inlineHelpText>Calculated by Product</inlineHelpText>
        <label>XXX Technology Platform Fee</label>
        <precision>16</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <recordTypes>
        <fullName>Lead</fullName>
        <active>true</active>
        <businessProcess>CS</businessProcess>
        <label>Lead</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Credit_Maximum__c</fullName>
        <label>Credit Maximum</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Credit_Minimum__c</fullName>
        <inlineHelpText>The credit approval logic treats this as inclusive, so a credit score = credit minimum is qualified</inlineHelpText>
        <label>Credit Minimum</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Loan_Financing_Fee_Terms__c</fullName>
        <label>Loan Financing Fee Terms</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Maximum (5%, $1,250)</fullName>
                </value>
                <value>
                    <fullName>No Financing Fee</fullName>
                </value>
                <value>
                    <fullName>Maximum (7%, $1,250)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Loan_Interest_Rate__c</fullName>
        <label>Loan Interest Rate</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Loan_Term__c</fullName>
        <label>Loan Term</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <label>Product Type</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>MSLP</fullName>
                </value>
                <value>
                    <fullName>BlueWave Solar Loan</fullName>
                </value>
                <value>
                    <fullName>SMART - Community Solar</fullName>
                </value>
                <value>
                    <fullName>SREC - Community Solar</fullName>
                </value>
                <value>
                    <fullName>CED Ensemble</fullName>
                </value>
                <value>
                    <fullName>VDER - Community Solar</fullName>
                </value>
                <value>
                    <fullName>Net Energy Billing (NEB)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
                <value>
                    <fullName>MN</fullName>
                </value>
                <value>
                    <fullName>MS</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
                <value>
                    <fullName>NE</fullName>
                </value>
                <value>
                    <fullName>NV</fullName>
                </value>
                <value>
                    <fullName>NH</fullName>
                </value>
                <value>
                    <fullName>NJ</fullName>
                </value>
                <value>
                    <fullName>NM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Technology_Platform_Fee__c</fullName>
        <label>Technology Platform Fee</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Program__c.object
<CustomObject>
    <description>CS Programs</description>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>State_abbreviations</valueSetName>
        </valueSet>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/State__c.object
<CustomObject>
    <description>State object used to store information about Utility Account annual usage estimates</description>
    <label>State</label>
    <nameField>
        <label>State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>States</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/State_abbreviations.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>AK</fullName>
    </customValue>
    <customValue>
        <fullName>AL</fullName>
    </customValue>
    <customValue>
        <fullName>AR</fullName>
    </customValue>
    <customValue>
        <fullName>AZ</fullName>
    </customValue>
    <customValue>
        <fullName>CA</fullName>
    </customValue>
    <customValue>
        <fullName>CO</fullName>
    </customValue>
    <customValue>
        <fullName>CT</fullName>
    </customValue>
    <customValue>
        <fullName>DE</fullName>
    </customValue>
    <customValue>
        <fullName>FL</fullName>
    </customValue>
    <customValue>
        <fullName>GA</fullName>
    </customValue>
    <customValue>
        <fullName>HI</fullName>
    </customValue>
    <customValue>
        <fullName>IA</fullName>
    </customValue>
    <customValue>
        <fullName>ID</fullName>
    </customValue>
    <customValue>
        <fullName>IL</fullName>
    </customValue>
    <customValue>
        <fullName>IN</fullName>
    </customValue>
    <customValue>
        <fullName>KS</fullName>
    </customValue>
    <customValue>
        <fullName>KY</fullName>
    </customValue>
    <customValue>
        <fullName>LA</fullName>
    </customValue>
    <customValue>
        <fullName>MA</fullName>
    </customValue>
    <customValue>
        <fullName>MD</fullName>
    </customValue>
    <customValue>
        <fullName>ME</fullName>
    </customValue>
    <customValue>
        <fullName>MI</fullName>
    </customValue>
    <customValue>
        <fullName>MN</fullName>
    </customValue>
    <customValue>
        <fullName>MO</fullName>
    </customValue>
    <customValue>
        <fullName>MS</fullName>
    </customValue>
    <customValue>
        <fullName>MT</fullName>
    </customValue>
    <customValue>
        <fullName>NC</fullName>
    </customValue>
    <customValue>
        <fullName>ND</fullName>
    </customValue>
    <customValue>
        <fullName>NE</fullName>
    </customValue>
    <customValue>
        <fullName>NH</fullName>
    </customValue>
    <masterLabel>State abbreviations</masterLabel>
</GlobalValueSet>

src/classes/ProductAssignmentHandler.cls
public with sharing class ProductAssignmentHandler {
    private boolean m_isExecuting = false;
    private Integer BatchSize = 0;
    
    public ProductAssignmentHandler(boolean isExecuting, Integer size){
        m_isExecuting = isExecuting;
        BatchSize = size;
    }
    /*public void OnBeforeLeadInsert(Lead[] newLeads){
        assignLoanProductToLead(newLeads);
    }*/
    public void onBeforeUpdate(List<Lead> newLeads, Map<ID, Lead> oldLeadsMap){
        assignLoanProductToLead(newLeads, oldLeadsMap);       
    }
    public void onBeforePCRUpdate(List<LASERCA__Personal_Credit_Report__c> pcrList){
        assignLoanProductToLeadViaPCR(pcrList);
    }    
    
    public List<Product2> getProductRecords(){
       List<Product2> productList = new List<Product2>();                                   
        //query for all of the products that are active | NOTE: will need to add queried fields as new product variations come into the system. Look for a way to return all fields.
        for(Product2 productRecord : [SELECT Id, Name, Program__c,IsActive, Loan_Financing_Fee_Terms__c, Loan_Term__c, Technology_Platform_Fee__c,
                                        Product_Type__c, State__c, Credit_Minimum__c, Credit_Maximum__c, Loan_Interest_Rate__c
                                        FROM Product2 
                                        WHERE isActive = TRUE]){
            productList.add(productRecord);
        }
        return productList;        
    }
 
    //assigns the appropriate product record to the triggered leads.
    public void assignLoanProductToLead(List<Lead> leadList, Map<ID, Lead> oldLeadsMap){
        Boolean runProductAssignment;
        List<Product2> productList = new List<Product2>();
        for (Lead leadRecord : leadList) {
            if (!leadRecord.Automatic_Product_Assignment__c) {
                runProductAssignment = false;
            } else {
                runProductAssignment = true;
                break;
            }
        }     
        if (runProductAssignment) {
           productList = getProductRecords();            
        }
        for(Lead leadRecord : leadList){
            if(leadRecord.Automatic_Product_Assignment__c == true 
                && leadRecord.Product_Line__c == 'Residential Loan' 
                //&& (leadRecord.Status == 'Qualified' || leadRecord.Pre_Approval_form__c == true ) 
                && leadRecord.Loan_Term__c != null 
                && oldLeadsMap.get(leadRecord.Id).Status != 'Qualified'){
                    //run through all of the products per lead to find the specific product suitable for this customer.
                    if(productList.size() > 0){
                        for(Product2 productRecord : productList){
                            //****Product Line could have issues as all leads, opps, etc. are set as Residential Loan and the Product is going to be Solar Loan. Also, home state is returned after credit.
                            if(productRecord.IsActive == true 
                                && productRecord.Product_Type__c == leadRecord.Product_Line__c 
                                && productRecord.Program__c == leadRecord.Product_Program__c 
                                && productRecord.Loan_Term__c == leadRecord.Loan_term__c 
                                && productRecord.State__c == leadRecord.LASERCA__Home_State__c ){
                                if(leadRecord.LASER_Credit_Score__c >= productRecord.Credit_Minimum__c && leadRecord.LASER_Credit_Score__c <= productRecord.Credit_Maximum__c){
                                    //assign the product to the lead
                                    if(leadRecord.DOER_Solar_Loan__c == true && productRecord.Program__c == 'MSLP'){
                                        leadRecord.Product__c = productRecord.Id;
                                        if (productRecord.Technology_Platform_Fee__c != 0 && productRecord.Technology_Platform_Fee__c != null){
                                            LeadRecord.Technology_Platform_Fee__c = (productRecord.Technology_Platform_Fee__c)/100 * leadRecord.Requested_Loan_Amount__c;
                                        } else {LeadRecord.Technology_Platform_Fee__c = 0;}
                                        if(productRecord.Loan_Financing_Fee_Terms__c == 'Maximum (5%, $1,250)'){
                                            leadRecord.Loan_Financing_Fee__c = Math.Max(leadRecord.Requested_Loan_Amount__c * .05, 1250);
                                            //leadRecord.Loan_Principal__c = leadRecord.Requested_Loan_Amount__c + leadRecord.Loan_Financing_Fee__c;
                                        }else if(productRecord.Loan_Financing_Fee_Terms__c == 'Maximum (7%, $1,250)'){
                                            leadRecord.Loan_Financing_Fee__c = Math.Max(leadRecord.Requested_Loan_Amount__c * .07, 1250);
                                            //leadRecord.Loan_Principal__c = leadRecord.Requested_Loan_Amount__c + leadRecord.Loan_Financing_Fee__c;
                                        }else if(productRecord.Loan_Financing_Fee_Terms__c == 'No Financing Fee'){
                                            //leadRecord.Loan_Principal__c = leadRecord.Requested_Loan_Amount__c;
                                            leadRecord.Loan_Financing_Fee__c = null;                                        
                                        }
                                    }
                                    if (leadRecord.DOER_Solar_Loan__c == false && productRecord.Program__c != 'MSLP'){
                                        leadRecord.Product__c = productRecord.Id;  
                                        if (productRecord.Technology_Platform_Fee__c != 0 && productRecord.Technology_Platform_Fee__c != null){
                                            LeadRecord.Technology_Platform_Fee__c = (productRecord.Technology_Platform_Fee__c)/100 * leadRecord.Requested_Loan_Amount__c;
                                        } else {LeadRecord.Technology_Platform_Fee__c = 0;}      
                                        if(productRecord.Loan_Financing_Fee_Terms__c == 'Maximum (5%, $1,250)'){
                                            leadRecord.Loan_Financing_Fee__c = Math.Max(leadRecord.Requested_Loan_Amount__c * .05, 1250);
                                            //leadRecord.Loan_Principal__c = leadRecord.Requested_Loan_Amount__c + leadRecord.Loan_Financing_Fee__c;
                                        }else if(productRecord.Loan_Financing_Fee_Terms__c == 'Maximum (7%, $1,250)'){
                                            leadRecord.Loan_Financing_Fee__c = Math.Max(leadRecord.Requested_Loan_Amount__c * .07, 1250);
                                            //leadRecord.Loan_Principal__c = leadRecord.Requested_Loan_Amount__c + leadRecord.Loan_Financing_Fee__c;
                                        }else if(productRecord.Loan_Financing_Fee_Terms__c == 'No Financing Fee'){
                                            //leadRecord.Loan_Principal__c = leadRecord.Requested_Loan_Amount__c;
                                            leadRecord.Loan_Financing_Fee__c = null;
                                        }                                                                   
                                    }                                                                                                             
                                }
                            else{
                                continue;
                            }
                        }                    
                    }
                }
            }   
        } 
    }
    /*the following class is needed in order to follow sequencing with the Pre-Qualification process. 
    Interest rate is needed to calculate the monthly payment, which is needed to pre-qualify the customer. 
    the assignment at the lead level required an additional update. 
    This howver allows for the trade accounts to be factored in after the product has been assigned.*/
    public void assignLoanProductToLeadViaPCR(List<LASERCA__Personal_Credit_Report__c> pcrList){
       List<String> pcrLeadIdList = new List<String>();
       for (LASERCA__Personal_Credit_Report__c pcrRecord : pcrList){
            pcrLeadIdList.add(pcrRecord.PCR_Lead_ID__c);
       }
       List<Lead> leadList = [SELECT Id, DOER_Solar_Loan__c, Product_Program__c, Name, Status, Product_Line__c, Product__c, Automatic_Product_Assignment__c,
                                    Loan_Term__c, LASERCA__Home_State__c, LASER_Credit_Score__c, Loan_Financing_Fee__c, 
                                    Pre_Approval_form__c, Requested_Loan_Amount__c, Product__r.Name
                                FROM Lead
                                WHERE Id IN : pcrLeadIdList
                                AND isConverted = false];

       List<Product2> productList = new List<Product2>(getProductRecords());
        for(Lead leadRecord : leadList){
            if(leadRecord.Product_Line__c == 'Residential Loan' && 
             leadRecord.Loan_Term__c != null){
                //run through all of the products per lead to find the specific product suitable for this customer.
                if(productList.size() > 0){
                    for(Product2 productRecord : productList){
                        //****Product Line could have issues as all leads, opps, etc. are set as Residential Loan and the Product is going to be Solar Loan. Also, home state is returned after credit.                      
                        if(leadRecord.Automatic_Product_Assignment__c == true && 
                            productRecord.Program__c == leadRecord.Product_Program__c &&
                            productRecord.Product_Type__c == leadRecord.Product_Line__c &&
                            productRecord.Loan_Term__c == leadRecord.Loan_term__c && 
                            productRecord.State__c == leadRecord.LASERCA__Home_State__c ){
                                if(leadRecord.LASER_Credit_Score__c >= productRecord.Credit_Minimum__c && 
                                    leadRecord.LASER_Credit_Score__c <= productRecord.Credit_Maximum__c){
                                    //assign the product to the lead
                                   if(leadRecord.DOER_Solar_Loan__c == true && productRecord.Program__c == 'MSLP'){
                                    leadRecord.Product__c = productRecord.Id;
                                        if(productRecord.Loan_Financing_Fee_Terms__c == 'Maximum (5%, $1,250)'){
                                            leadRecord.Loan_Financing_Fee__c = Math.Max(leadRecord.Requested_Loan_Amount__c * .05, 1250);
                                            //leadRecord.Loan_Principal__c = leadRecord.Requested_Loan_Amount__c + leadRecord.Loan_Financing_Fee__c;
                                        }else if(productRecord.Loan_Financing_Fee_Terms__c == 'Maximum (7%, $1,250)'){
                                            leadRecord.Loan_Financing_Fee__c = Math.Max(leadRecord.Requested_Loan_Amount__c * .07, 1250);
                                            //leadRecord.Loan_Principal__c = leadRecord.Requested_Loan_Amount__c + leadRecord.Loan_Financing_Fee__c;
                                        }else if(productRecord.Loan_Financing_Fee_Terms__c == 'No Financing Fee'){
                                            //leadRecord.Loan_Principal__c = leadRecord.Requested_Loan_Amount__c;
                                            leadRecord.Loan_Financing_Fee__c = null;                                        
                                        }
                                    }
                                    if (leadRecord.DOER_Solar_Loan__c == false && productRecord.Program__c != 'MSLP'){
                                        leadRecord.Product__c = productRecord.Id;        
                                        if(productRecord.Loan_Financing_Fee_Terms__c == 'Maximum (5%, $1,250)'){
                                            leadRecord.Loan_Financing_Fee__c = Math.Max(leadRecord.Requested_Loan_Amount__c * .05, 1250);
                                            //leadRecord.Loan_Principal__c = leadRecord.Requested_Loan_Amount__c + leadRecord.Loan_Financing_Fee__c;
                                        }else if(productRecord.Loan_Financing_Fee_Terms__c == 'Maximum (7%, $1,250)'){
                                            leadRecord.Loan_Financing_Fee__c = Math.Max(leadRecord.Requested_Loan_Amount__c * .07, 1250);
                                            //leadRecord.Loan_Principal__c = leadRecord.Requested_Loan_Amount__c + leadRecord.Loan_Financing_Fee__c;
                                        }else if(productRecord.Loan_Financing_Fee_Terms__c == 'No Financing Fee'){
                                            //leadRecord.Loan_Principal__c = leadRecord.Requested_Loan_Amount__c;
                                            leadRecord.Loan_Financing_Fee__c = null;
                                        }                                                                   
                                    }                                                        
                                }
                        }
                        else{
                            continue;
                        }
                    }                    
                }
            }
        }
        update leadList;       
    }    
} 