src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Auto_QC_Error_Debug__c</fullName>
        <description>Debugging information for Auto Lead Qualification &amp; Conversion process</description>
        <inlineHelpText>Debugging information, if relevant, for Auto Lead Qualification &amp; Conversion process</inlineHelpText>
        <label>Auto QC Error Debug</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Auto_QC_Failure_Details__c</fullName>
        <description>Failures encountered during Auto Lead Qualification &amp; Conversion when more than one is encountered. See CSLeadsConverter / CSLeadConversionValidator.</description>
        <inlineHelpText>Failures encountered during Auto Lead Qualification &amp; Conversion when more than one is encountered</inlineHelpText>
        <label>Auto QC Failure Details</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Auto_QC_Failure_Reason__c</fullName>
        <description>Failure encountered during Auto Lead Qualification &amp; Conversion. See CSLeadsConverter / CSLeadConversionValidator.</description>
        <inlineHelpText>Failure encountered during Auto Lead Qualification &amp; Conversion</inlineHelpText>
        <label>Auto QC Failure Reason</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Conversion Failure</fullName>
                </value>
                <value>
                    <fullName>Lead Already Converted</fullName>
                </value>
                <value>
                    <fullName>Testcase Lead</fullName>
                </value>
                <value>
                    <fullName>Application Incomplete</fullName>
                </value>
                <value>
                    <fullName>Invalid Email</fullName>
                </value>
                <value>
                    <fullName>Incomplete UALs</fullName>
                </value>
                <value>
                    <fullName>No Qualified Systems Found</fullName>
                </value>
                <value>
                    <fullName>System Product Mismatch</fullName>
                </value>
                <value>
                    <fullName>Auto QC Turned Off</fullName>
                </value>
                <value>
                    <fullName>Multiple Issues</fullName>
                </value>
                <value>
                    <fullName>No Demand Capacity Available</fullName>
                </value>
                <value>
                    <fullName>Unresolved Split Load Zone</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Auto_QC_Last_Runtime__c</fullName>
        <description>Last runtime of Auto Qualification &amp; Conversion process</description>
        <inlineHelpText>Last runtime of Auto Qualification &amp; Conversion process</inlineHelpText>
        <label>Auto QC Last Runtime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Product lookup, for loans, set by an installer upon sending a new application or set by code after a credit check has determined qualifying products.</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Selected_SSS_For_Conversion__c</fullName>
        <description>SSS that have been selected by the user to be considered for Subscriptions during Conversion</description>
        <label>Selected SSS For Conversion</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Utility__c</fullName>
        <formula>IF(INCLUDES(  Utility_1__c , &quot;Eversource&quot;), &quot;Eversource&quot;, 
IF(INCLUDES(  Utility_1__c , &quot;National Grid&quot;), &quot;National Grid&quot;,
IF(INCLUDES(  Utility_1__c , &quot;Unitil&quot;), &quot;Unitil&quot;,
IF(INCLUDES(  Utility_1__c , &quot;Municipal Electric Department&quot;), &quot;Municipal Electric Department&quot;,
IF(INCLUDES(  Utility_1__c , &quot;Duke Energy&quot;), &quot;Duke Energy&quot;, 
IF(INCLUDES(  Utility_1__c , &quot;SCE&amp;G&quot;), &quot;SCE&amp;G&quot;, 
 &quot;Other&quot;))))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>XXXXX Utility</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Utility_relationship__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Utility</label>
        <referenceTo>Utility__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Lead</fullName>
        <active>true</active>
        <businessProcess>CS</businessProcess>
        <label>Lead</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Shared_Solar_System__c.object
<CustomObject
     >
    <articleTypeChannelDisplay n1:nil="true" />
    <customSettingsType n1:nil="true" />
    <description n1:nil="true" />
    <eventType n1:nil="true" />
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Primary customer product.</inlineHelpText>
        <label>Default Enrollment Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Shared Solar Systems</relationshipLabel>
        <relationshipName>Shared_Solar_Systems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Utility__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Utility</label>
        <referenceTo>Utility__c</referenceTo>
        <relationshipLabel>Shared Solar Systems</relationshipLabel>
        <relationshipName>Shared_Solar_Systems</relationshipName>
        <type>Lookup</type>
    </fields>
    <gender n1:nil="true" />
    <household>false</household>
    <label>Shared Solar System</label>
    <nameField>
        <label>Shared Solar System Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shared Solar Systems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <startsWith n1:nil="true" />
</CustomObject>

src/objects/System_Properties__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>System Properties</label>
</CustomObject>

force-app/main/default/objects/System_Properties__c/fields/CS_Auto_Lead_Conversion_Batch_Size__c.field-meta.xml
<CustomField>
    <fullName>CS_Auto_Lead_Conversion_Batch_Size__c</fullName>
    <description>See CSLeadsConverter, CSLeadConversionValidator</description>
    <inlineHelpText>Batch size for queueables in the &quot;Auto Lead Qualification &amp; Conversion&quot; process for Community Solar leads. Toggle this if limits are reached for existing batches. For reference, Lead conversion triggers UAS creation and a slew of other code, which if unoptimized, can result in batch failures if the batch size is too large.</inlineHelpText>
    <label>CS Auto Lead Conversion Batch Size</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/objects/Utility__c.object
<CustomObject>
    <label>Utility</label>
    <nameField>
        <label>Utility Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Utility_Account_Log__c.object
<CustomObject>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Utility Account Logs</relationshipLabel>
        <relationshipName>Utility_Account_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Utility__c</fullName>
        <formula>Lead__r.Electricity_Provider__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>xxxUtility</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Utility_lookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Utility</label>
        <referenceTo>Utility__c</referenceTo>
        <relationshipLabel>Utility Account Logs</relationshipLabel>
        <relationshipName>Utility_Account_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Utility Account Log</label>
    <nameField>
        <label>Utility Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Account Logs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/CSLeadsConverter.cls
/**
 * @description Created by jeffparlin on 9/23/21. Validates and converts leads input by caller. Leveraged by apex and
 *      Lead Qualification/Conversion flow. This class uses a bulkified design pattern which can support multiple
 *      Leads passing through per instance.
 * Tested By: CSLeadsConverterTest
 */
public without sharing class CSLeadsConverter implements Queueable {

    @TestVisible private static Integer queueableBatchSize = (Integer)
        System_Properties__c.getValues('System')?.CS_Auto_Lead_Conversion_Batch_Size__c;
    @TestVisible private static LeadSelector leadSelector = new LeadSelector();
    @TestVisible private static SharedSolarSystemsSelector systemsSelector = new SharedSolarSystemsSelector();
    @TestVisible private static UtilitySelector utilitySelector = new UtilitySelector();

    private Boolean isAutoConversionContext = false;
    private Map<Id, LeadConvertDetail> conversions = new Map<Id, LeadConvertDetail>();
    private List<Database.LeadConvert> conversionsReady;
    private Set<Id> autoConvertLeads = new Set<Id>();
    private Map<Id, Shared_Solar_System__c> systemsForEnrollment;

    /**
     * @description Constructor used by Flow to run Lead conversion for specified LeadConvertDetail objects
     * @param details List of LeadConvertDetail wrapper objects housing Lead Conversion information
     */
    public CSLeadsConverter(List<LeadConvertDetail> details) {
        systemsForEnrollment = new Map<Id, Shared_Solar_System__c>(systemsSelector.getSharedSolarSystemsForEnrollment());
        mapConversions(details);
    }

    /**
     * @description Constructor used by Queueable Apex/Auto Lead Qualification & Conversion
     * @param leadIdsForAutoConversion Set of Lead Ids to run lead conversion for
     */
    public CSLeadsConverter(Set<Id> leadIdsForAutoConversion) {
        this.autoConvertLeads = leadIdsForAutoConversion;
    }

    /**
     * @description Flow invocation of CS Lead conversion (synchronous)
     * @param details LeadConvertDetail objects which house conversion information
     *      Due to this running in a Flow context, the array size of details wil always be 1
     * @return Return version of the LeadConvertDetail complete with errors and error messages, if encountered
     */
    @InvocableMethod(Label='Invocable Lead Converter' Description='Converts CS Leads')
    public static List<LeadConvertDetail> invocableConvertLead(List<LeadConvertDetail> details) {
        CSLeadsConverter converter = new CSLeadsConverter(details);
        converter.convert();
        return details;
    }

    /**
     * @description Queueable invocation of CS Lead Conversion (asynchronous), see UtilityAccountLogTriggerHandler
     *      Handles job chaining in the event of a large bolus of incoming conversions --
     *      The Lead conversion process is CPU Time extensive as of this impl, so restrict batches to smaller chunks
     * @param ctx Queueable context
     */
    public void execute(QueueableContext ctx) {
        isAutoConversionContext = true;
        List<Id> leadIdsToProcess = new List<Id>(autoConvertLeads);
        try {
            Set<Id> leadsForNextBatch = new Set<Id>();
            for (Integer i = leadIdsToProcess.size()-1; i >= queueableBatchSize; i--) {
                Id currentLeadId = leadIdsToProcess[i];
                leadIdsToProcess.remove(i);
                leadsForNextBatch.add(currentLeadId);
            }

            autoConvertLeads = new Set<Id>(leadIdsToProcess);
            List<LeadConvertDetail> details = constructDetailsByLeads();
            mapConversions(details);
            convert();

            if (!leadsForNextBatch.isEmpty() && !Test.isRunningTest()) {
                System.enqueueJob(new CSLeadsConverter(leadsForNextBatch));
            }
        } catch (Exception e) {
            String message = 'Error encountered while running CSLeadsConverter in Queueable context. Leads impacted: '
                + autoConvertLeads + '\n\n' + e.getMessage() + ' ' + e.getStackTraceString();
            Logger.logNow('CSLeadsConverter', 'execute (queueable)', message, Logger.ERROR);
        }
    }

    /**
     * @description Primary execution chain here
     */
    private void convert() {
        retrieveDependencies();
        validateInputs();
        modifyLeadsWithInputs();
        constructConversionData();
        commitConversion();
        updateLeadsWithConversionResults();
    }

    /**
     * @description Maps Lead Id to LeadConvertDetail object for reference if needed
     * @param details List of LeadConvertDetail objects
     */
    private void mapConversions(List<LeadConvertDetail> details) {
        for (LeadConvertDetail detail : details) {
            this.conversions.put(detail.leadId, detail);
        }
    }

    /**
     * @description Constructs LeadConvertDetail objects for passed-in Lead Ids, intended for Lead Auto Conversion context
     * @return List of LeadConvertDetail objects to be used by remainder of class
     */
    private List<LeadConvertDetail> constructDetailsByLeads() {
        List<LeadConvertDetail> details = new List<LeadConvertDetail>();
        systemsForEnrollment = new Map<Id, Shared_Solar_System__c>(systemsSelector.getSharedSolarSystemsForEnrollment());
        SharedSolarSystems systemsHelper = new SharedSolarSystems(systemsForEnrollment.values());
        List<Lead> leads = leadSelector.selectAll(autoConvertLeads);
        for (Lead lead : leads) {
            LeadConvertDetail detail = new LeadConvertDetail();
            List<Shared_Solar_System__c> qualifiedSystemsForLead = systemsHelper.getQualifiedForLead(lead);
            detail.leadId = lead.Id;
            detail.selectedProductId = lead.Product__c;
            detail.selectedSystemIds = CollectionUtil.getIds(qualifiedSystemsForLead);
            detail.autoConversion = isAutoConversionContext;
            details.add(detail);
        }
        return details;
    }

    /**
     * @description Retrieves dependencies needed for processing Lead Conversion and caches in LeadConvertDetail object
     */
    @TestVisible
    private void retrieveDependencies() {
        Map<Id, Utility__c> utilityMap = utilitySelector.getAllUtilitiesMap();
        Map<Id, Lead> leadMap = leadSelector.getLeadsForConversion(conversions.keySet());

        for (LeadConvertDetail detail : conversions.values()) {
            detail.lead = leadMap.get(detail.leadId);
            detail.utilityAccountLogs = detail.lead.Utility_Account_Logs__r;
            detail.utility = utilityMap.get(detail.lead.Utility_relationship__c);
            for (Id systemId : detail.selectedSystemIds) {
                detail.selectedSystems.add(systemsForEnrollment.get(systemId));
            }
        }
    }

    /**
     * @description Runs validation check on each LeadConvertDetail before continuing down the Lead Conversion path
     */
    @TestVisible
    private void validateInputs() {
        for (LeadConvertDetail detail : conversions.values()) {
            new CSLeadConversionValidator(detail).validate();
        }
    }

    @SuppressWarnings('PMD.ApexCRUDViolation')
    private void modifyLeadsWithInputs() {
        List<Lead> leadsToUpdate = new List<Lead>();
        for (LeadConvertDetail detail : conversions.values()) {
            Lead lead = new Lead(Id = detail.leadId);
            lead.Status = !detail.selectedSystems.isEmpty() ? 'Qualified' : lead.Status;
            lead.Selected_SSS_For_Conversion__c = getSelectedSystemIds(detail);
            lead.Product__c = detail.selectedProductId;
            leadsToUpdate.add(lead);
        }
        updateLeads(leadsToUpdate, true);
    }

    @TestVisible
    private void updateLeads(List<Lead> leadsToUpdate, Boolean preConversion) {
        try {
            update leadsToUpdate;
        } catch (Exception e) {
            Boolean isUnableToLockRowError = e.getMessage().contains('UNABLE_TO_LOCK_ROW');
            if (isUnableToLockRowError && !isAutoConversionContext) {
                throw new Util.BWException(e.getMessage());
            }
            Logger.logNow('CSLeadsConverter', 'updateLeads ' + (preConversion ? '(pre-Convert)' : '(post-Convert)'),
                e.getMessage(), Logger.ERROR);
        }
    }

    @TestVisible
    private String getSelectedSystemIds(LeadConvertDetail detail) {
        String selectedSystems = '';
        for (Shared_Solar_System__c sss : detail.selectedSystems) {
            selectedSystems += sss.Id + '/';
        }
        return selectedSystems;
    }

    @TestVisible
    private void constructConversionData() {
        conversionsReady = new List<Database.LeadConvert>();
        for (LeadConvertDetail detail : conversions.values()) {
            if (detail.error == null) {
                Database.LeadConvert conversion = new Database.LeadConvert();
                conversion.setLeadId(detail.leadId);
                conversion.setOwnerId(System.UserInfo.getUserId());
                conversion.setConvertedStatus('Qualified');
                conversion.setDoNotCreateOpportunity(true);
                conversionsReady.add(conversion);
            }
        }
    }

    @TestVisible
    private void commitConversion() {
        if (conversionsReady.isEmpty()) {
            return;
        }
        List<Database.LeadConvertResult> results = Database.convertLead(conversionsReady, false);
        for (Database.LeadConvertResult result : results) {
            if (!result.isSuccess()) {
                LeadConvertDetail detail = conversions.get(result.getLeadId());
                detail.error = CSLeadConversionValidator.CONVERSION_FAILURE;
                detail.errorsEncountered.add(CSLeadConversionValidator.CONVERSION_FAILURE);
                detail.errorMessage = result.getErrors().toString();
            }
        }
    }

    /**
     * @description Updates Leads with results of Auto-Conversions only
     */
    private void updateLeadsWithConversionResults() {
        List<Lead> leadsToUpdate = new List<Lead>();
        for (LeadConvertDetail detail : conversions.values()) {
            Lead lead = new Lead(Id = detail.leadId);
            lead.Auto_QC_Last_Runtime__c = System.now();
            lead.Auto_QC_Failure_Reason__c = detail.errorsEncountered.size() > 1 ? CSLeadConversionValidator.MULTIPLE_ISSUES : detail.error;
            lead.Auto_QC_Failure_Details__c = String.join(new List<String>(detail.errorsEncountered), ', ');
            lead.Auto_QC_Error_Debug__c = detail.errorMessage;
            leadsToUpdate.add(lead);
        }
        updateLeads(leadsToUpdate, false);
    }
}