src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Parcel_Zip__c</fullName>
        <description>Set at least by Form Assembly forms (e.g. 381607)</description>
        <label>Parcel Zip</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Territory__c</fullName>
        <label>Service Territory</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Lead</fullName>
        <active>true</active>
        <businessProcess>CS</businessProcess>
        <label>Lead</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Service_Territory__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Territory__c</fullName>
        <label>Service Territory</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Service Territory</label>
    <nameField>
        <label>Zip Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Territories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/assignServiceTerritoryTest.cls
@isTest
private class assignServiceTerritoryTest {

Static testMethod void validateAssignServiceTerritory(){

lead newLead = new lead(firstName = 'Cole', lastName = 'Swain', company = 'BlueWave', status = 'contacted', Parcel_Zip__c = '29501') ;
service_territory__c newServiceTerritory = new service_territory__c ( name = '29501', service_territory__c = 'Duke Energy Progress (DEP)', city__c = 'Florence');

Insert newServiceTerritory;

test.startTest();
 
insert newLead;
 
test.stopTest();
 
lead leadQuery = [SELECT firstName, service_territory__c FROM lead WHERE firstName = 'Cole'];
 
system.assertEquals('Duke Energy Progress (DEP)' , leadQuery.service_territory__c);
 
 
}
}