src/objects/Lead.object
<CustomObject>
    <recordTypes>
        <fullName>Lead</fullName>
        <active>true</active>
        <businessProcess>CS</businessProcess>
        <label>Lead</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Set by OpportunityTriggerHandler on Opportunity creation, assuming Opportunity.Lead_ID__c (a text field) is also being set via Lead Mapping.</inlineHelpText>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shared_Solar_System__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>To change this system, use the Change SSS quick action</inlineHelpText>
        <label>Shared Solar System</label>
        <referenceTo>Shared_Solar_System__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Shared_Solar_System__c.object
<CustomObject
     >
    <articleTypeChannelDisplay n1:nil="true" />
    <customSettingsType n1:nil="true" />
    <description n1:nil="true" />
    <eventType n1:nil="true" />
    <gender n1:nil="true" />
    <household>false</household>
    <label>Shared Solar System</label>
    <nameField>
        <label>Shared Solar System Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shared Solar Systems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <startsWith n1:nil="true" />
</CustomObject>

force-app/main/default/classes/CustomerPortalActivator.cls
/**
 * @description Creates new portal users when opportunities are updated to be Complete
 * Tested By: OpportunityTriggerTest
 */
public without sharing class CustomerPortalActivator {
    public void activatePortalAfterInsert(Map<Id, Opportunity> newOpps) {
        List<Opportunity> listOpps = new List<Opportunity>();
        for (Opportunity Opp : newOpps.values()) {
            if (newOpps.get(Opp.Id).StageName == 'Complete') {
                listOpps.add(newOpps.get(Opp.Id));
            }
        }
        activatePortal(listOpps);
    }
    public void activatePortalAfterUpdate(Map<Id, Opportunity> newOpps, Map<Id, Opportunity> oldOpps) {
        List<Opportunity> listOpps = new List<Opportunity>();
        for (Opportunity Opp : newOpps.values()) {
            if (newOpps.get(Opp.Id).StageName != oldOpps.get(Opp.Id).StageName && newOpps.get(Opp.Id).StageName == 'Complete') {
                listOpps.add(newOpps.get(Opp.Id));
            }
        }
        activatePortal(listOpps);
    }
    public void activatePortal(List<Opportunity> oppsNewlyCompleted) {
        for (Opportunity opp : oppsNewlyCompleted) {
            Map<String, SObject> flowParameters = new Map<String, SObject>();
            flowParameters.put('sov_Opportunity', opp);
            if (opp.Lead__c == null || opp.Shared_Solar_System__c == null) {
                // We need a lead and system to activate a portal. Anchor opportunities may not have both (but do not
                // need portal accounts)
                continue;
            }
            flowParameters.put('sov_Lead', new Lead(Id = opp.Lead__c));
            flowParameters.put('sov_SSS', new Shared_Solar_System__c(Id = opp.Shared_Solar_System__c));
            Flow.Interview.Portal_Activation activatePortal = new Flow.Interview.Portal_Activation(flowParameters);
            activatePortal.start();
        }
    }
}