src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Zuora_Payment_Ref_Id_Expiration_Date__c</fullName>
        <description>Date/Time of Zuora Ref Id expiration. If time has past, the Id is invalid</description>
        <inlineHelpText>The date that the customer&apos;s payment information expires in Zuora&apos;s system, if it has not be moved onto a Zuora account</inlineHelpText>
        <label>Zuora Payment Ref Id Expiration Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Zuora_Payment_Ref_Id__c</fullName>
        <description>Zuora Payment Reference Id should be passed from the Originations platform during their processes. The Payment Info Id will need to be associated with a customer&apos;s Zuora account once we create it. The Payment information expires, so reference Zuora_Payment_Ref_Id_Expiration_Date__c to make sure the Id is still valid.</description>
        <label>Zuora Payment Ref Id</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Lead</fullName>
        <active>true</active>
        <businessProcess>CS</businessProcess>
        <label>Lead</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/LeadSelector.cls
/*************************************************************************************
 * Created By: peteryao on 2019-04-30  
 * Description: 
 * Test: LeadSelectorTest
 *************************************************************************************/

public without sharing class LeadSelector {
    public static List<Lead> selectConvertedByIds(List<Id> leadIds) {
        return [
            SELECT Id, ConvertedAccountId, Zuora_Payment_Ref_Id__c, Zuora_Payment_Ref_Id_Expiration_Date__c
            FROM Lead
            WHERE Id IN :leadIds
            AND ConvertedAccountId != NULL
        ];
    }
}