src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Load_Zone__c</fullName>
        <label>XXXX Load Zone</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>NEMA</fullName>
                </value>
                <value>
                    <fullName>SEMA</fullName>
                </value>
                <value>
                    <fullName>WCMA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Service_Territory__c</fullName>
        <label>Service Territory</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Utility__c</fullName>
        <formula>IF(INCLUDES(  Utility_1__c , &quot;Eversource&quot;), &quot;Eversource&quot;, 
IF(INCLUDES(  Utility_1__c , &quot;National Grid&quot;), &quot;National Grid&quot;,
IF(INCLUDES(  Utility_1__c , &quot;Unitil&quot;), &quot;Unitil&quot;,
IF(INCLUDES(  Utility_1__c , &quot;Municipal Electric Department&quot;), &quot;Municipal Electric Department&quot;,
IF(INCLUDES(  Utility_1__c , &quot;Duke Energy&quot;), &quot;Duke Energy&quot;, 
IF(INCLUDES(  Utility_1__c , &quot;SCE&amp;G&quot;), &quot;SCE&amp;G&quot;, 
 &quot;Other&quot;))))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>XXXXX Utility</label>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Lead</fullName>
        <active>true</active>
        <businessProcess>CS</businessProcess>
        <label>Lead</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Load_U__c.object
<CustomObject>
    <description>General list of Massachusetts Zip Codes and their corresponding Load Zones and Utiliy providers.</description>
    <fields>
        <fullName>LZ__c</fullName>
        <label>Load Zone</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Load_Zone__c</fullName>
        <label>XXXXX Load Zone &amp; Utility</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Town__c</fullName>
        <label>Town</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Utility__c</fullName>
        <label>XXXX Utility</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <label>Load Zone &amp; Utility</label>
    <nameField>
        <label>Zip Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Load Zones &amp; Utilities</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Partner__c.object
<CustomObject>
    <fields>
        <fullName>service_territory__c</fullName>
        <label>Load Zone</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>All</fullName>
                </value>
                <value>
                    <fullName>NEMA</fullName>
                </value>
                <value>
                    <fullName>SEMA</fullName>
                </value>
                <value>
                    <fullName>WCMA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Partner</label>
    <nameField>
        <label>Partner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partners</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Service_Territory__c.object
<CustomObject>
    <fields>
        <fullName>Service_Territory__c</fullName>
        <label>Service Territory</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Service Territory</label>
    <nameField>
        <label>Zip Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Territories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Shared_Solar_System__c.object
<CustomObject
     >
    <articleTypeChannelDisplay n1:nil="true" />
    <customSettingsType n1:nil="true" />
    <description n1:nil="true" />
    <eventType n1:nil="true" />
    <fields>
        <fullName>Capacity_Committed_kW_DC__c</fullName>
        <inlineHelpText>Sum of Complete Small CS Subscriptions</inlineHelpText>
        <label>Committed Small CS Capacity</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Class__c</fullName>
        <formula>IF ( OR( 

Name = &quot;Oxford Barrett St. P2&quot;, Name = &quot;Oxford Barrett St. P1&quot;), &quot;Class 2&quot;,

IF(AND(   Total_System_Size_kW_AC__c &gt; 60, Total_System_Size_kW_AC__c &lt;= 1000), &quot;Class 2&quot;, 

IF ( Total_System_Size_kW_AC__c &gt; 1000, &quot;Class 3&quot;, null)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>MA Specific
Based on size of project (1MW), if the SSS falls into Class II or Class III categories</inlineHelpText>
        <label>System Class</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Credit_Score_Requirement__c</fullName>
        <defaultValue>700</defaultValue>
        <inlineHelpText>Minimum accepted customer FICO score.</inlineHelpText>
        <label>Credit Score Requirement</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Open__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Open</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Reserved_Capacity_kW_DC__c</fullName>
        <inlineHelpText>Sum of New, Pending, or QC in Process Small CS subscriptions</inlineHelpText>
        <label>Pending Small CS Capacity</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Territory__c</fullName>
        <label>XXXService Territory</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Duke Energy Carolinas (DEC)</fullName>
                </value>
                <value>
                    <fullName>Duke Energy Progress (DEP)</fullName>
                </value>
                <value>
                    <fullName>NEMA</fullName>
                </value>
                <value>
                    <fullName>SEMA</fullName>
                </value>
                <value>
                    <fullName>WCMA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>System_Utility__c</fullName>
        <label>Utility</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_System_Size_kW_AC__c</fullName>
        <inlineHelpText>Total system size in kW AC.</inlineHelpText>
        <label>Total System Size (kW AC)</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_System_Size_kWh_DC__c</fullName>
        <inlineHelpText>Total system size in kW DC.</inlineHelpText>
        <label>Total System Size (kW DC)</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Utility_NMC_Tariff__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sizing Method</label>
        <referenceTo>Utility_NMC_Tariff__c</referenceTo>
        <relationshipLabel>Shared Solar Systems</relationshipLabel>
        <relationshipName>Shared_Solar_Systems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Utility__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Utility</label>
        <referenceTo>Utility__c</referenceTo>
        <relationshipLabel>Shared Solar Systems</relationshipLabel>
        <relationshipName>Shared_Solar_Systems</relationshipName>
        <type>Lookup</type>
    </fields>
    <gender n1:nil="true" />
    <household>false</household>
    <label>Shared Solar System</label>
    <nameField>
        <label>Shared Solar System Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shared Solar Systems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <startsWith n1:nil="true" />
</CustomObject>

src/objects/Town__c.object
<CustomObject>
    <fields>
        <fullName>Load_Zone__c</fullName>
        <label>Load Zone</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>NEMA</fullName>
                </value>
                <value>
                    <fullName>SEMA</fullName>
                </value>
                <value>
                    <fullName>WCMA</fullName>
                </value>
                <value>
                    <fullName>WCMA/SEMA</fullName>
                </value>
                <value>
                    <fullName>NEMA/SEMA</fullName>
                </value>
                <value>
                    <fullName>NEMA/WCMA</fullName>
                </value>
                <value>
                    <fullName>Oran</fullName>
                    <isActive>false</isActive>
                    <label>Oran</label>
                </value>
                <value>
                    <fullName>WCMA/NEMA</fullName>
                    <isActive>false</isActive>
                    <label>WCMA/NEMA</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Utility__c</fullName>
        <label>Utility</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>National Grid</fullName>
                </value>
                <value>
                    <fullName>Eversource</fullName>
                </value>
                <value>
                    <fullName>Eversource/Muni</fullName>
                </value>
                <value>
                    <fullName>Eversource/NGRID</fullName>
                </value>
                <value>
                    <fullName>Municipal/NGRID</fullName>
                </value>
                <value>
                    <fullName>Municipal</fullName>
                </value>
                <value>
                    <fullName>Green Mountain Power</fullName>
                </value>
                <value>
                    <fullName>Orange &amp; Rockland</fullName>
                </value>
                <value>
                    <fullName>PSE&amp;G</fullName>
                </value>
                <value>
                    <fullName>SCE&amp;G</fullName>
                </value>
                <value>
                    <fullName>Unitil</fullName>
                </value>
                <value>
                    <fullName>Green Mountain</fullName>
                    <isActive>false</isActive>
                    <label>Green Mountain</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Town</label>
    <nameField>
        <label>Town Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Towns</pluralLabel>
    <recordTypes>
        <fullName>Test</fullName>
        <active>true</active>
        <label>Test</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Utility__c.object
<CustomObject>
    <fields>
        <fullName>Service_Territory__c</fullName>
        <inlineHelpText>Select the Territory(s) to which the data below will represent.</inlineHelpText>
        <label>XXService Territory</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Duke Energy Progress (DEP)</fullName>
                </value>
                <value>
                    <fullName>Duke Energy Carolinas (DEC)</fullName>
                </value>
                <value>
                    <fullName>All</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Utility</label>
    <nameField>
        <label>Utility Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Utility_NMC_Tariff__c.object
<CustomObject>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Class 2</fullName>
                </value>
                <value>
                    <fullName>Class 3</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Load_Zone__c</fullName>
        <label>Load Zone</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sizing_Rate__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sizing Rate</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Utility__c</fullName>
        <label>Utility</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value_of_Net_Metering_Credit__c</fullName>
        <label>Value of Net Metering Credit</label>
        <precision>11</precision>
        <scale>6</scale>
        <type>Currency</type>
    </fields>
    <label>Sizing Method</label>
    <nameField>
        <label>Utility and Class</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sizing Methods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/mapAvailableCapacityTest.cls
@isTest
private class mapAvailableCapacityTest{

Static testMethod void mapAvailableCapacity(){


Date myDate = Date.newInstance(2015, 2, 17);
        
        Utility_NMC_Tariff__c everSEMA = new Utility_NMC_Tariff__c (
                Name = 'Eversource SEMA Class 2', 
                Utility__c = 'Eversource', 
                Class__c = 'Class 2',
                Value_of_Net_Metering_Credit__c = 0.1848,
                Sizing_Rate__c = TRUE
                );

        insert everSEMA;

        Utility_NMC_Tariff__c everNEMA = new Utility_NMC_Tariff__c (
                Name = 'Eversource NEMA Class 2', 
                Utility__c = 'Eversource', 
                Class__c = 'Class 2',
                Value_of_Net_Metering_Credit__c = 0.1218,
                Sizing_Rate__c = TRUE
                );

        insert everNEMA;

        Load_U__c semaLZU = new Load_U__c ( 
                Name = '02633', 
                Load_zone__c = 'SEMA Eversource', 
                LZ__c = 'SEMA', 
                Utility__C = 'Eversource', 
                Town__c= 'Southtown');

        Load_U__c nemaLZU = new Load_U__c ( 
                Name = '01570', 
                Load_zone__c= 'NEMA Eversource', 
                LZ__c = 'NEMA', 
                Utility__C = 'Eversource', 
                Town__c= 'Westtown');

        Insert semaLZU;
        Insert nemaLZU;
        
        system.debug(semaLZU);

        Shared_Solar_System__c sss = new Shared_Solar_System__c(Name = 'No Capacity SSS',
                                                                        Service_Territory__c = 'SEMA',
                                                                        Open__c = true,
                                                                        //Reserved_Capacity_kW_DC__c = '500',
                                                                        Capacity_Committed_kW_DC__c = 500,
                                                                        Total_System_Size_kWh_DC__c = 500,
                                                                        Total_System_Size_kW_AC__c  = 500,
                                                                        System_Utility__c = 'Eversource',
                                                                        Credit_Score_Requirement__c = 200,
                                                                        Assignment_order__c = '2',
                                                                        Utility_NMC_Tariff__c = everSEMA.Id,
                                                                        Expected_Yield_kWh_kW__c = 1300,
                                                                        Assemblage_Count__c = 1,
                                                                        Sales_Partners__c = 'All',
                                                                        Maximum_Subscription_Assemblage__c = 25);

    Shared_Solar_System__c sss0 = new Shared_Solar_System__c(Name = 'Oxford NEMA',
                                                                        Service_Territory__c = 'NEMA',
                                                                        Open__c = true,
                                                                        Reserved_Capacity_kW_DC__c = '0',
                                                                        Capacity_Committed_kW_DC__c = 0,
                                                                        Total_System_Size_kWh_DC__c = 1200,
                                                                        Total_System_Size_kW_AC__c  = 996,
                                                                        System_Utility__c = 'Eversource',
                                                                        Credit_Score_Requirement__c = 200,
                                                                        Assignment_order__c = '2',
                                                                        Utility_NMC_Tariff__c = everNEMA.Id,
                                                                        Expected_Yield_kWh_kW__c = 1300,
                                                                        Assemblage_Count__c = 1,
                                                                        Sales_Partners__c = 'Boston Solar; SolWorks',
                                                                        Maximum_Subscription_Assemblage__c = 25);

    Shared_Solar_System__c sss1 = new Shared_Solar_System__c(Name = 'Oxford SEMA P1',
                                                                       Service_Territory__c = 'SEMA',
                                                                       Open__c = true,
                                                                       Reserved_Capacity_kW_DC__c = '0',
                                                                       Capacity_Committed_kW_DC__c = 0,
                                                                       Total_System_Size_kWh_DC__c = 1445,
                                                                       Total_System_Size_kW_AC__c  = 996,
                                                                       System_Utility__c = 'Eversource',
                                                                       Credit_Score_Requirement__c = 200,
                                                                       Assignment_order__c = '1',
                                                                       Utility_NMC_Tariff__c = everSEMA.Id,
                                                                       Expected_Yield_kWh_kW__c = 1300,
                                                                       Assemblage_Count__c = 1,
                                                                       Sales_Partners__c = 'All',
                                                                       Maximum_Subscription_Assemblage__c = 25);

    Shared_Solar_System__c sss2 = new Shared_Solar_System__c(Name = 'Oxford SEMA P2',
                                                                        Service_Territory__c = 'SEMA',
                                                                        Open__c = true,
                                                                        Reserved_Capacity_kW_DC__c = '0',
                                                                        Capacity_Committed_kW_DC__c = 0,
                                                                        Total_System_Size_kWh_DC__c = 1800,
                                                                        Total_System_Size_kW_AC__c  = 996,
                                                                        System_Utility__c = 'Eversource',
                                                                        Credit_Score_Requirement__c = 800,
                                                                        Assignment_order__c = '2',
                                                                        Utility_NMC_Tariff__c = everSEMA.Id,
                                                                        Expected_Yield_kWh_kW__c = 1300,
                                                                        Assemblage_Count__c = 1,
                                                                        Sales_Partners__c = 'All',
                                                                        Maximum_Subscription_Assemblage__c = 25);


    insert new List<Shared_Solar_System__c>{sss, sss0, sss1, sss2};

    Partner__c partnerA = new Partner__c(Name = 'Boston Solar');
    insert partnerA;

    BSST__c salesteam = new BSST__c (Name = 'Boston Solar',
                       Custom_ID__c = 'PA',
                       Partner__c = partnerA.Id);
    insert salesteam;
    
    Account accountA = new Account(name = 'Account A',
            RecordTypeId = '012j00000010Ha3');       

        Account accountB = new Account(name = 'Account B',
            RecordTypeId = '012j00000010Ha3');       

        Account accountC = new Account(name = 'Account C',
            RecordTypeId = '012j00000010Ha3');       

        Account accountD = new Account(name = 'Account D',
            RecordTypeId = '012j00000010Ha3');       
        
        Insert accountA;
        Insert accountB;
        Insert accountC;
        Insert accountD;   

 /* 
      Lead leadA = new Lead(LastName = 'Last',
                      FirstName = 'One',
                      Email = 'test@email.com',
                      Electricity_Provider__c = 'Eversource',
                      Utility_1__c = 'Eversource',
                      Load_Zone__c = 'NEMA',
                      Company = 'Cloud Jedi',
                      Custom_ID__c = 'PA',
                      Product_Line__c = 'Community Solar',
                      Parent_Account__c = accountA.Id,
                      System_Assignment__c = 'Automatic - Assignment Order');
      
      insert leadA;

    
                LASERCA__Personal_Credit_Report__c pcrA = (LASERCA__Personal_Credit_Report__c)TestFactory.createSObject(new LASERCA__Personal_Credit_Report__c(
                                                                                        LASERCA__Lead__c = leadA.Id,
                                                                                        LASERCA__Credit_Score_TransUnion__c = '700'), true);
                //lead.Personal_Credit_Report__c = pcrB.Id;
            update leadA;
 */       

      Lead leadB = new Lead(LastName = 'Last',
                      FirstName = 'Two',
                      Email = 'test@email.com',
                      Electricity_Provider__c = 'Eversource',
                      Utility_1__c = 'Eversource',
                      Load_Zone__c = 'NEMA',
                      Company = 'Cloud Jedi',
                      //Status = 'Qualified',
                      Product_Line__c = 'Community Solar',
                      Parent_Account__c = accountB.Id,
                      System_Assignment__c = 'Automatic - Assignment Order');
      
      insert leadB;

                  LASERCA__Personal_Credit_Report__c pcrB = (LASERCA__Personal_Credit_Report__c)TestFactory.createSObject(new LASERCA__Personal_Credit_Report__c(
                                                                                        LASERCA__Lead__c = leadB.Id,
                                                                                        LASERCA__Credit_Score_TransUnion__c = '700'), true);
                //lead.Personal_Credit_Report__c = pcrB.Id;
            update leadB;


      Lead leadC = new Lead(LastName = 'Last',
                      FirstName = 'Three',
                      Email = 'test@email.com',
                      Electricity_Provider__c = 'Eversource',
                      Utility_1__c = 'Eversource',
                      Load_Zone__c = 'SEMA',
                      Company = 'Cloud Jedi',
                      //Status = 'Qualified',
                      Product_Line__c = 'Community Solar',
                      Parent_Account__c = accountC.Id,
                      System_Assignment__c = 'Automatic - Assignment Order');
      
      insert leadC;

                  LASERCA__Personal_Credit_Report__c pcrC = (LASERCA__Personal_Credit_Report__c)TestFactory.createSObject(new LASERCA__Personal_Credit_Report__c(
                                                                                        LASERCA__Lead__c = leadC.Id,
                                                                                        LASERCA__Credit_Score_TransUnion__c = '680'), true);
                //lead.Personal_Credit_Report__c = pcrB.Id;
            update leadC;
/*
      Lead leadD = new Lead(LastName = 'Last',
                      FirstName = 'Four',
                      Email = 'test@email.com',
                      Electricity_Provider__c = 'Eversource',
                      Utility_1__c = 'Eversource',
                      Load_Zone__c = 'SEMA',
                      Company = 'Cloud Jedi',
                      //Status = 'Qualified',
                      Product_Line__c = 'Community Solar',
                      Parent_Account__c = accountD.Id,
                      System_Assignment__c = 'Automatic - Assignment Order');
      
      insert leadD;

                  LASERCA__Personal_Credit_Report__c pcrD = (LASERCA__Personal_Credit_Report__c)TestFactory.createSObject(new LASERCA__Personal_Credit_Report__c(
                                                                                        LASERCA__Lead__c = leadD.Id,
                                                                                        LASERCA__Credit_Score_TransUnion__c = '800'), true);
                //lead.Personal_Credit_Report__c = pcrB.Id;
            update leadD;
  */    
      List <Lead> updatedLeadList = [SELECT Id, FirstName, Available_Capacity__c FROM Lead];
        system.debug(updatedLeadList);


        Test.StartTest();
        for(Lead lead : updatedLeadList){

          if(lead.FirstName == 'One'){
              system.Assert(lead.Available_Capacity__c == 1200);
          }

          if(lead.FirstName == 'Two'){
              system.Assert(lead.Available_Capacity__c == 0);
          }

          if(lead.FirstName == 'Three'){
              system.Assert(lead.Available_Capacity__c == 1445);
          }

          if(lead.FirstName == 'Four'){
              system.Assert(lead.Available_Capacity__c == 3245);
          } 
        }
        Test.StopTest();
 
}
}