src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Custom_ID__c</fullName>
        <label>Custom ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LASERCA__Home_Address__c</fullName>
        <label>Home Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LASERCA__Home_City__c</fullName>
        <label>Home City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LASERCA__Home_State__c</fullName>
        <label>Home State</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LASERCA__Home_Zip__c</fullName>
        <label>Home Zip</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LASERCA__Social_Security_Number__c</fullName>
        <label>**Deprecated SSN</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_line__c</fullName>
        <label>Product Line</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Lead</fullName>
        <active>true</active>
        <businessProcess>CS</businessProcess>
        <label>Lead</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/User/fields/Partner_ID__c.field-meta.xml
<CustomField>
    <fullName>Partner_ID__c</fullName>
    <formula>Contact.Partner_Lookup__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Partner ID</label>
    <type>Text</type>
</CustomField>

src/classes/SLPAddCustomer.cls
public class SLPAddCustomer {
 @AuraEnabled
    public static void addNewLeadRecord (Lead newLead) {
        System.debug('begin the addCustomer method');

        User u = [SELECT Id, Partner_ID__c FROM User WHERE Id = :UserInfo.getUserId()];
        String propertyString = newLead.firstName + ' ' + newLead.lastName;
        newLead.Company = propertyString;
        newLead.Custom_ID__c = 'BWCCSwain';
        newLead.Product_Line__c = 'Residential Loan';

        //Lead newLead = new Lead(
        //	FirstName = firstName,
        //	LastName = lastName,
        //	Company = propertyString,
        //	LASERCA__Home_Address__c = street,
        //	LASERCA__Home_City__c = state,
        //	LASERCA__Home_State__c = city,
        //	LASERCA__Home_Zip__c = zip,
        //	Email = email,
        //	LASERCA__Social_Security_Number__c = ssn);
        insert newLead;
        //String firstName, String lastName, String street, String state, String city, String zip, String email, String ssn
    }
    
}