src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Customer_type__c</fullName>
        <label>Customer type</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Product lookup, for loans, set by an installer upon sending a new application or set by code after a credit check has determined qualifying products.</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Utility__c</fullName>
        <formula>IF(INCLUDES(  Utility_1__c , &quot;Eversource&quot;), &quot;Eversource&quot;, 
IF(INCLUDES(  Utility_1__c , &quot;National Grid&quot;), &quot;National Grid&quot;,
IF(INCLUDES(  Utility_1__c , &quot;Unitil&quot;), &quot;Unitil&quot;,
IF(INCLUDES(  Utility_1__c , &quot;Municipal Electric Department&quot;), &quot;Municipal Electric Department&quot;,
IF(INCLUDES(  Utility_1__c , &quot;Duke Energy&quot;), &quot;Duke Energy&quot;, 
IF(INCLUDES(  Utility_1__c , &quot;SCE&amp;G&quot;), &quot;SCE&amp;G&quot;, 
 &quot;Other&quot;))))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>XXXXX Utility</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/State__c.object
<CustomObject>
    <description>State object used to store information about Utility Account annual usage estimates</description>
    <label>State</label>
    <nameField>
        <label>State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>States</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Utility__c.object
<CustomObject>
    <label>Utility</label>
    <nameField>
        <label>Utility Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Utility_Account_Log__c.object
<CustomObject>
    <fields>
        <fullName>Annual_kWh__c</fullName>
        <description>Value from most recent UDR. 
Used for customer sizing on SMART contracts.</description>
        <inlineHelpText>Value from most recent UDR.
Used for customer sizing on SMART contracts.</inlineHelpText>
        <label>Annual kWh</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Average_Demand__c</fullName>
        <description>Value from most recent UDR.</description>
        <inlineHelpText>Value from most recent UDR.</inlineHelpText>
        <label>Average Demand</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Utility Account Logs</relationshipLabel>
        <relationshipName>Utility_Account_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_State__c</fullName>
        <label>Service State</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Utility__c</fullName>
        <formula>Lead__r.Electricity_Provider__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>xxxUtility</label>
        <type>Text</type>
    </fields>
    <label>Utility Account Log</label>
    <nameField>
        <label>Utility Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Account Logs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Utility_Data_Request__c.object
<CustomObject
     >
    <fields>
        <fullName>Account_Number__c</fullName>
        <complianceGroup>PII</complianceGroup>
        <label>Account Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_Type__c</fullName>
        <description>E=Customer receives supply from an ESCO
U=Customer receives supply from the Utility</description>
        <inlineHelpText>E=Customer receives supply from an ESCO
U=Customer receives supply from the Utility</inlineHelpText>
        <label>Account Type</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address_Line_1__c</fullName>
        <complianceGroup>PII</complianceGroup>
        <label>Address Line 1</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address_Line_2__c</fullName>
        <complianceGroup>PII</complianceGroup>
        <label>Address Line 2</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Annual_kWh__c</fullName>
        <description>Value calculated from UDRP Quantities in the last 12 months where the Measurement Unit = KH and the Measurement Significance Code = 51</description>
        <inlineHelpText>Value calculated from UDRP Quantities in the last 12 months where the Measurement Unit = KH and the Measurement Significance Code = 51</inlineHelpText>
        <label>Annual kWh</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Average_Demand__c</fullName>
        <description>Value calculated from UDRP Quantities in the last 12 months where the Measurement Unit = K1 and the Measurement Significance Code = 51</description>
        <inlineHelpText>Value calculated from UDRP Quantities in the last 12 months where the Measurement Unit = K1 and the Measurement Significance Code = 51</inlineHelpText>
        <label>Average Demand</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <complianceGroup>PII</complianceGroup>
        <label>City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Name__c</fullName>
        <complianceGroup>PII</complianceGroup>
        <label>Customer Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Government_Credit_Code__c</fullName>
        <description>N=No, account does not have a NYPA Discount
Y=Yes, account does have a NYPA Discount</description>
        <inlineHelpText>N=No, account does not have a NYPA Discount
Y=Yes, account does have a NYPA Discount</inlineHelpText>
        <label>Government Credit Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LDC_Customer_Eligibility__c</fullName>
        <description>N=No, the account is not receiving Utility Discounts/Incentive Rates
Y=Yes, the account is receiving Utility Discounts/Incentive Rates</description>
        <inlineHelpText>N=No, the account is not receiving Utility Discounts/Incentive Rates
Y=Yes, the account is receiving Utility Discounts/Incentive Rates</inlineHelpText>
        <label>LDC Customer Eligibility</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Num_months_Annual_kWh__c</fullName>
        <description>The number of months used in the Annual kWh calculation.</description>
        <inlineHelpText>The number of months used in the Annual kWh calculation.</inlineHelpText>
        <label>Number of months used in Annual kWh</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Num_months_Average_Demand__c</fullName>
        <description>The number of months used in the Average Demand calculation.</description>
        <inlineHelpText>The number of months used in the Average Demand calculation.</inlineHelpText>
        <label>Number of months used in Average Demand</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Old_Account_Number__c</fullName>
        <complianceGroup>PII</complianceGroup>
        <description>Required when LDC acct number has changed in the last 90 days</description>
        <inlineHelpText>Required when LDC acct number has changed in the last 90 days</inlineHelpText>
        <label>Old Account Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <complianceGroup>PII</complianceGroup>
        <label>State</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Utility_Account_Log__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Utility Account Log</label>
        <referenceTo>Utility_Account_Log__c</referenceTo>
        <relationshipLabel>Utility Data Requests</relationshipLabel>
        <relationshipName>Utility_Data_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Utility__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Utility</label>
        <referenceTo>Utility__c</referenceTo>
        <relationshipLabel>Utility Data Requests</relationshipLabel>
        <relationshipName>Utility_Data_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <complianceGroup>PII</complianceGroup>
        <label>Zip Code</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>Utility Data Request</label>
    <nameField>
        <displayFormat>UDR-{00000}</displayFormat>
        <label>Utility Data Request</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Utility Data Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/UtilityDataRequestSelector.cls
/**
 * Created by: Kristin White on 10/19/2020
 * 
 * Tested by: UtilityDataRequestServiceTest
 */

@SuppressWarnings('PMD.ApexCRUDViolation')
public class UtilityDataRequestSelector {
    
    public Map<Id, Utility_Data_Request__c> selectMapForKWHById(List<Utility_Data_Request__c> udrList) {
        Map<Id, Utility_Data_Request__c> selectedUDRs = new Map<Id, Utility_Data_Request__c>([
            SELECT Id, Name, Annual_kWh__c, Request_Status__c, State__c, Utility__c, Average_Demand__c, 
            Utility_Account_Log__c, Account_Number__c, Account_Type__c, Utility_Account_Log__r.Service_State__c, 
            Utility_Account_Log__r.Lead__r.Product__r.X4_month_sizing_method__c, Customer_Name__c, Zip_Code__c,
            Utility_Account_Log__r.Lead__r.Customer_type__c, Num_months_Average_Demand__c, City__c, 
            Old_Account_Number__c, Num_months_Annual_kWh__c, Address_Line_1__c, Address_Line_2__c,
            Government_Credit_Code__c, LDC_Customer_Eligibility__c
            FROM Utility_Data_Request__c 
            WHERE Id IN :(udrList)
        ]);
        return selectedUDRs;
    }
}