src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Product lookup, for loans, set by an installer upon sending a new application or set by code after a credit check has determined qualifying products.</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Set by OpportunityTriggerHandler on Opportunity creation, assuming Opportunity.Lead_ID__c (a text field) is also being set via Lead Mapping.</inlineHelpText>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shared_Solar_System__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>To change this system, use the Change SSS quick action</inlineHelpText>
        <label>Shared Solar System</label>
        <referenceTo>Shared_Solar_System__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Customer_Subscription_Type__c</fullName>
        <label>Customer Subscription Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>kWh</fullName>
                </value>
                <value>
                    <fullName>Electricity Cost ($)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sizing_Method__c</fullName>
        <label>Sizing Method</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Project Ratio</fullName>
                </value>
                <value>
                    <fullName>Rate Class Ratio</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Rate_Class__c.object
<CustomObject>
    <description>This object stores utility rate class information. It&apos;s different from NMC Tariffs.</description>
    <fields>
        <fullName>Utility_NMC_Tariff__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sizing Method</label>
        <referenceTo>Utility_NMC_Tariff__c</referenceTo>
        <relationshipLabel>Rate Classes</relationshipLabel>
        <relationshipName>Rate_Classes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Rate Class</label>
    <nameField>
        <label>Rate Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rate Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Shared_Solar_System__c.object
<CustomObject
     >
    <articleTypeChannelDisplay n1:nil="true" />
    <customSettingsType n1:nil="true" />
    <description n1:nil="true" />
    <eventType n1:nil="true" />
    <fields>
        <fullName>Maximum_Subscription_Cost__c</fullName>
        <formula>Maximum_Subscription_Capacity_kWDC__c *  NMC_Value__c *  Expected_Yield_kWh_kW__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Maximum Subscription Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Primary customer product.</inlineHelpText>
        <label>Default Enrollment Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Shared Solar Systems</relationshipLabel>
        <relationshipName>Shared_Solar_Systems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Utility_NMC_Tariff__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sizing Method</label>
        <referenceTo>Utility_NMC_Tariff__c</referenceTo>
        <relationshipLabel>Shared Solar Systems</relationshipLabel>
        <relationshipName>Shared_Solar_Systems</relationshipName>
        <type>Lookup</type>
    </fields>
    <gender n1:nil="true" />
    <household>false</household>
    <label>Shared Solar System</label>
    <nameField>
        <label>Shared Solar System Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shared Solar Systems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <startsWith n1:nil="true" />
</CustomObject>

src/objects/Subscription_Order__c.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Subscription Orders</relationshipLabel>
        <relationshipName>Subscription_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Size_Ratio__c</fullName>
        <defaultValue>1</defaultValue>
        <description>Size Ratio from Sizing Method used to calculate subscription size</description>
        <inlineHelpText>Size Ratio from Sizing Method used to calculate subscription size</inlineHelpText>
        <label>Size Ratio</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Transfer</fullName>
                </value>
                <value>
                    <fullName>Cancellation</fullName>
                </value>
                <value>
                    <fullName>Shared Solar System Update</fullName>
                </value>
                <value>
                    <fullName>Resize</fullName>
                </value>
                <value>
                    <fullName>Initial</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Utility_Account_Subscription__c</fullName>
        <label>Utility Account Subscription</label>
        <referenceTo>Utility_Account_Subscription__c</referenceTo>
        <relationshipLabel>Subscription Orders</relationshipLabel>
        <relationshipName>Subscription_Orders</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Utility_NMC_Tariff__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>This is the Sizing Method used to calculate the Subscription at the time this record was created.</description>
        <inlineHelpText>This is the Sizing Method used to calculate the Subscription at the time this record was created.</inlineHelpText>
        <label>Sizing Method</label>
        <referenceTo>Utility_NMC_Tariff__c</referenceTo>
        <relationshipLabel>Subscription Orders</relationshipLabel>
        <relationshipName>Subscription_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Subscription Order</label>
    <nameField>
        <displayFormat>SO-{00000}</displayFormat>
        <label>Subscription Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscription Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Utility_Account_Log__c.object
<CustomObject>
    <fields>
        <fullName>Annual_Cost_of_Electricity__c</fullName>
        <description>This is used for the SREC CS Product sizing. It is the total dollar amount a customer spends annually on their electric utility bill for this account. It is initially filled in with an estimate from the customer/partner during the CS application process, then filled in by Ops with the QCed amount.</description>
        <inlineHelpText>Used for SREC CS Product sizing. It&apos;s the total dollar amount spent annually on the electric utility bill. It is initially filled in with an estimate from the customer/partner during the CS application process, then filled in by Ops with the QCed amount.</inlineHelpText>
        <label>Annual Cost of Electricity</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Annual_kWh__c</fullName>
        <description>Value from most recent UDR. 
Used for customer sizing on SMART contracts.</description>
        <inlineHelpText>Value from most recent UDR.
Used for customer sizing on SMART contracts.</inlineHelpText>
        <label>Annual kWh</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Utility Account Logs</relationshipLabel>
        <relationshipName>Utility_Account_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Utility Account Logs</relationshipLabel>
        <relationshipName>Utility_Account_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Utility_NMC_Tariff__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Utility NMC Tariff</label>
        <referenceTo>Utility_NMC_Tariff__c</referenceTo>
        <relationshipLabel>Utility Account Logs</relationshipLabel>
        <relationshipName>Utility_Account_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Utility Account Log</label>
    <nameField>
        <label>Utility Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Account Logs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Utility_Account_Subscription__c.object
<CustomObject>
    <fields>
        <fullName>Annual_Cost_of_Electricity__c</fullName>
        <description>Total cost of electricity at the UAL level.</description>
        <label>Full Annual Cost of Electricity</label>
        <precision>9</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Utility Account Subscriptions</relationshipLabel>
        <relationshipName>Utility_Account_Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shared_Solar_System__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the SSS on the Opportunity when the UAS was created. The SSS on an existing UAS should never be changed.</description>
        <inlineHelpText>This is the SSS on the Opportunity when the UAS was created. The SSS on an existing UAS should never be changed.</inlineHelpText>
        <label>Shared Solar System</label>
        <referenceTo>Shared_Solar_System__c</referenceTo>
        <relationshipLabel>Utility Account Subscriptions</relationshipLabel>
        <relationshipName>Utility_Account_Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sizing_Method__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Sizing Method with either NMC Value or Size Ratio to be used in calculating subscriptions</description>
        <inlineHelpText>Sizing Method with either NMC Value or Size Ratio to be used in calculating subscriptions. If you need to change the Sizing Method, log a new Subscription Order via button.</inlineHelpText>
        <label>Sizing Method</label>
        <referenceTo>Utility_NMC_Tariff__c</referenceTo>
        <relationshipLabel>Utility Account Subscriptions</relationshipLabel>
        <relationshipName>Utility_Account_Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Utility_Account_Log__c</fullName>
        <inlineHelpText>The related UAL</inlineHelpText>
        <label>Utility Account Log</label>
        <referenceTo>Utility_Account_Log__c</referenceTo>
        <relationshipLabel>Utility Account Subscriptions</relationshipLabel>
        <relationshipName>Utility_Account_Subscriptions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>calculated_annual_cost_of_electricity__c</fullName>
        <defaultValue>0</defaultValue>
        <description>The Minimum of Total UAL Cost and Maximum SSS Cost. (As more UAS are created, UAL Cost is deducted)</description>
        <label>Calculated Annual Cost of Electricity</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Utility Account Subscription</label>
    <nameField>
        <label>Utility Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Account Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Utility_NMC_Tariff__c.object
<CustomObject>
    <fields>
        <fullName>Size_Ratio__c</fullName>
        <label>Size Ratio</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Value_of_Net_Metering_Credit__c</fullName>
        <label>Value of Net Metering Credit</label>
        <precision>11</precision>
        <scale>6</scale>
        <type>Currency</type>
    </fields>
    <label>Sizing Method</label>
    <nameField>
        <label>Utility and Class</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sizing Methods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CSUtilityAccountSubscriptionFactory.cls
/**
 * @description : Created by mstackhouse on 12/17/2018.
 * Tested by: CSUtilityAccountSubscriptionFactoryTest
 */
public with sharing class CSUtilityAccountSubscriptionFactory {

    private static final String CAPACITY = 'kWh';
    private static final String COST = 'Electricity Cost ($)';

    @TestVisible
    private static Map<Id, SSSSubscription> sssSubscriptionMap = new Map<Id, SSSSubscription>();

    public class UASOrder {
        public Utility_Account_Subscription__c uas;
        public Subscription_Order__c sOrder;
    }

    public class SSSSubscription {
        public Shared_Solar_System__c sss;
        public String sizingMethod;
        public String customerSubscriptionType;
        public Decimal maximumKWH;
        public Decimal maximumCost;
        public SSSSubscription(Shared_Solar_System__c sss) {
            this.sss = sss;
            this.sizingMethod = sss.Product__r.Sizing_Method__c;
            this.customerSubscriptionType = sss.Product__r.Customer_Subscription_Type__c;
            this.maximumKWH = SharedSolarSystems.calculateMaximumkWh(sss);
            this.maximumCost = sss.Maximum_Subscription_Cost__c;
        }
    }

    @TestVisible
    private class UtilityAccountLogWrapper {
        public Utility_Account_Log__c ual;
        public Utility_NMC_Tariff__c sizingMethod;
        public Decimal annualCostOfElectricity;
        public Decimal remainingCapacity;
        public Decimal remainingCost;
        public String subscriptionType;
        public Integer uasNumberCount;
        public UtilityAccountLogWrapper(Utility_Account_Log__c ual) {
            this.ual = ual;
            this.sizingMethod = getUALSizingMethod(ual);
            this.remainingCapacity = calculateAnnualAmount(ual.Annual_kWh__c, ual.Annual_Cost_of_Electricity__c, this.sizingMethod.Value_of_Net_Metering_Credit__c, CAPACITY);
            this.remainingCost = calculateAnnualAmount(ual.Annual_Cost_of_Electricity__c, ual.Annual_kWh__c, this.sizingMethod.Value_of_Net_Metering_Credit__c, COST);
            this.annualCostOfElectricity = this.remainingCost;
            this.subscriptionType = ual.Lead__r.Product__r.Customer_Subscription_Type__c;
            this.uasNumberCount = 1;
        }
    }

    private class SubscriptionAllocation {
        public Decimal ualRemainingAllocation;
        public Decimal sssRemainingSubscriptionAmount;
        public Decimal annualAmountAssigned;
        public Decimal allocationPercentage;
    }

    public static void generateSubscriptions(List<Utility_Account_Log__c> uals, List<Shared_Solar_System__c> sharedSolarSystems,
        List<Opportunity> opportunities, fflib_SObjectUnitOfWork uow) {
        for (Shared_Solar_System__c sss : sharedSolarSystems) {
            sssSubscriptionMap.put(sss.Id, new SSSSubscription(sss));
        }

        for (Utility_Account_Log__c ual : uals) {
            try {
                createUAS(ual, opportunities, uow);
            } catch (Exception e) {
                Logger.logNow('CSUtilityAccountSubscriptionFactory', 'generateSubscriptions', JSON.serialize(ual) + '\n' + e.getMessage() + '\n' + e.getStackTraceString(), Logger.ERROR);
                throw new Util.BWException();
            }
        }
    }

    @TestVisible
    private static void createUAS(Utility_Account_Log__c ual, List<Opportunity> opportunities, fflib_SObjectUnitOfWork uow) {
        UtilityAccountLogWrapper ualInfo = new UtilityAccountLogWrapper(ual);
        for (Opportunity opportunity : opportunities) {
            // Break loop if nothing left on UAL to allocate
            if (ualInfo.remainingCapacity <= 0 && ualInfo.remainingCost <= 0) {
                break;
            }
            createUASFromOpportunity(ualInfo, opportunity, uow);
        }
    }

    private static void createUASFromOpportunity(UtilityAccountLogWrapper ualInfo, Opportunity opportunity, fflib_SObjectUnitOfWork uow) {
        SSSSubscription sssSubscription = sssSubscriptionMap.get(opportunity.Shared_Solar_System__c);
        if (sssSubscription == null) {
            return;
        }
        String subscriptionType = ualInfo.subscriptionType == CAPACITY || ualInfo.subscriptionType == COST ? ualInfo.subscriptionType : sssSubscription.customerSubscriptionType;
        if (subscriptionType == CAPACITY) {
            createUASByCapacity(ualInfo, sssSubscription, opportunity, uow);
        }
        if (subscriptionType == COST) {
            createUASbyCost(ualInfo, sssSubscription, opportunity, uow);
        }
    }

    private static void createUASByCapacity(UtilityAccountLogWrapper ualInfo, SSSSubscription sssSubscription, Opportunity opportunity, fflib_SObjectUnitOfWork uow) {
        Decimal sizeRatio = sssSubscription.sizingMethod == 'Rate Class Ratio' && ualInfo.sizingMethod.Size_Ratio__c != null ? ualInfo.sizingMethod.Size_Ratio__c : 1.0;
        Decimal sssRemainingSubscriptionCapacity = (sssSubscription.maximumKWH / sizeRatio).setScale(2, RoundingMode.HALF_DOWN);
        SubscriptionAllocation subscriptionAllocation = calculateAllocations(sssRemainingSubscriptionCapacity, ualInfo.remainingCapacity);
        if (subscriptionAllocation == null) {
            return;
        }
        // update the totals using our calculations
        sssSubscription.maximumKWH = subscriptionAllocation.sssRemainingSubscriptionAmount * sizeRatio;
        ualInfo.remainingCapacity = subscriptionAllocation.ualRemainingAllocation;
        // keep the ual totals even by subtracting the same percentage from the ual remaining cost allocation
        ualInfo.remainingCost -= (ualInfo.remainingCost * subscriptionAllocation.allocationPercentage);
        Utility_Account_Subscription__c uas = createUASObject(ualInfo, opportunity.Id);
        uow.registerNew(uas, Utility_Account_Subscription__c.Opportunity__c, opportunity);
        populateSizingMethod(ualInfo, uas, sssSubscription);
        ualInfo.uasNumberCount++;
        createSOByCapacity(uas, subscriptionAllocation.annualAmountAssigned, uow);
    }

    private static void createUASbyCost(UtilityAccountLogWrapper ualInfo, SSSSubscription sssSubscription, Opportunity opportunity, fflib_SObjectUnitOfWork uow) {
        SubscriptionAllocation subscriptionAllocation = calculateAllocations(sssSubscription.maximumCost, ualInfo.remainingCost);
        if (subscriptionAllocation == null) {
            return;
        }
        sssSubscription.maximumCost = subscriptionAllocation.sssRemainingSubscriptionAmount;
        ualInfo.remainingCost = subscriptionAllocation.ualRemainingAllocation;
        ualInfo.remainingCapacity -= (ualInfo.remainingCapacity * subscriptionAllocation.allocationPercentage);
        Utility_Account_Subscription__c uas = createUASObject(ualInfo, opportunity.Id);
        uas.calculated_annual_cost_of_electricity__c = subscriptionAllocation.annualAmountAssigned;
        uas.Annual_Cost_of_Electricity__c = ualInfo.annualCostOfElectricity;
        uow.registerNew(uas, Utility_Account_Subscription__c.Opportunity__c, opportunity);
        populateSizingMethod(ualInfo, uas, sssSubscription);
        ualInfo.uasNumberCount++;
        createSOByCost(uas, subscriptionAllocation.annualAmountAssigned, uow);
    }

    private static SubscriptionAllocation calculateAllocations(Decimal sssRemainingSubscriptionAmount, Decimal ualRemainingAllocation) {
        // do not create subscription if there is nothing left to allocate
        if (sssRemainingSubscriptionAmount == 0 || ualRemainingAllocation == 0) {
            return null;
        }
        SubscriptionAllocation subscriptionAllocation = new SubscriptionAllocation();
        subscriptionAllocation.annualAmountAssigned = Math.min(sssRemainingSubscriptionAmount, ualRemainingAllocation);
        // deduct the annual assigned amount from the sssSubscription and ual totals
        subscriptionAllocation.sssRemainingSubscriptionAmount = sssRemainingSubscriptionAmount - subscriptionAllocation.annualAmountAssigned;
        subscriptionAllocation.ualRemainingAllocation = ualRemainingAllocation - subscriptionAllocation.annualAmountAssigned;
        subscriptionAllocation.allocationPercentage = subscriptionAllocation.annualAmountAssigned / ualRemainingAllocation;
        return subscriptionAllocation;
    }

    private static Utility_NMC_Tariff__c getUALSizingMethod(Utility_Account_Log__c ual) {
        if (ual.Utility_Rate_Class__c == null || ual.Utility_Rate_Class__r.Utility_NMC_Tariff__c == null) {
            return new Utility_NMC_Tariff__c();
        }
        return ual.Utility_Rate_Class__r.Utility_NMC_Tariff__r;
    }

    private static Decimal calculateAnnualAmount(Decimal annualAmount, Decimal amountToConvert, Decimal netMeteringCredit, String type) {
        // use annual amount value if it was already set
        if (annualAmount != null) {
            return annualAmount;
        }
        // we cannot calculate anything if there is no value for conversion or there is no net metering credit
        if (amountToConvert == null || netMeteringCredit == null || netMeteringCredit == 0) {
            return 0;
        }
        // use the net metering credit as a ratio if the value has not been calculated yet
        Decimal netMeteringRatio = type == CAPACITY ? (1 / netMeteringCredit) : netMeteringCredit;
        return (amountToConvert * netMeteringRatio);
    }

    private static Utility_Account_Subscription__c createUASObject(UtilityAccountLogWrapper ualInfo, Id opportunityId) {

        Utility_Account_Subscription__c uas = new Utility_Account_Subscription__c(
            Name = ualInfo.ual.Name,
            Name_on_Account__c = ualInfo.ual.Name_on_Account__c,
            Opportunity__c = opportunityId,
            Utility_Account_Log__c = ualInfo.ual.Id,
            UAS_Number__c = ualInfo.uasNumberCount
        );

        return uas;
    }

    private static void populateSizingMethod(UtilityAccountLogWrapper ualInfo, Utility_Account_Subscription__c uas, SSSSubscription sssSubscription) {
        if (sssSubscription.sizingMethod == 'Rate Class Ratio' && ualInfo.ual.Utility_Rate_Class__c != null) {
            uas.Sizing_Method__c = ualInfo.sizingMethod.Id;
        } else {
            uas.Sizing_Method__c = sssSubscription.sss.Utility_NMC_Tariff__c;
        }
    }

    @TestVisible
    private static void createSOByCapacity(Utility_Account_Subscription__c uas, Decimal annualElectricityCapacityAssigned, fflib_SObjectUnitOfWork uow) {
        Subscription_Order__c so = new Subscription_Order__c(
            Type__c = 'Initial',
            New_Annual_kWh__c = annualElectricityCapacityAssigned,
            Effective_Date__c = System.now(),
            Approval_Status__c = 'Approved'
        );
        uow.registerNew(so, Subscription_Order__c.Utility_Account_Subscription__c, uas);
    }

    @TestVisible
    private static void createSOByCost(Utility_Account_Subscription__c uas, Decimal annualElectricityCostAssigned, fflib_SObjectUnitOfWork uow) {
        Subscription_Order__c so = new Subscription_Order__c(
            Type__c = 'Initial',
            New_Annual_Cost__c = annualElectricityCostAssigned,
            Effective_Date__c = System.now(),
            Approval_Status__c = 'Approved'
        );
        uow.registerNew(so, Subscription_Order__c.Utility_Account_Subscription__c, uas);
    }

}