src/objects/Load_U__c.object
<CustomObject>
    <description>General list of Massachusetts Zip Codes and their corresponding Load Zones and Utiliy providers.</description>
    <fields>
        <fullName>LZ__c</fullName>
        <label>Load Zone</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Town__c</fullName>
        <label>Town</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Utility__c</fullName>
        <label>XXXX Utility</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <label>Load Zone &amp; Utility</label>
    <nameField>
        <label>Zip Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Load Zones &amp; Utilities</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Town__c.object
<CustomObject>
    <fields>
        <fullName>Utility__c</fullName>
        <label>Utility</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>National Grid</fullName>
                </value>
                <value>
                    <fullName>Eversource</fullName>
                </value>
                <value>
                    <fullName>Eversource/Muni</fullName>
                </value>
                <value>
                    <fullName>Eversource/NGRID</fullName>
                </value>
                <value>
                    <fullName>Municipal/NGRID</fullName>
                </value>
                <value>
                    <fullName>Municipal</fullName>
                </value>
                <value>
                    <fullName>Green Mountain Power</fullName>
                </value>
                <value>
                    <fullName>Orange &amp; Rockland</fullName>
                </value>
                <value>
                    <fullName>PSE&amp;G</fullName>
                </value>
                <value>
                    <fullName>SCE&amp;G</fullName>
                </value>
                <value>
                    <fullName>Unitil</fullName>
                </value>
                <value>
                    <fullName>Green Mountain</fullName>
                    <isActive>false</isActive>
                    <label>Green Mountain</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Town</label>
    <nameField>
        <label>Town Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Towns</pluralLabel>
    <recordTypes>
        <fullName>Test</fullName>
        <active>true</active>
        <label>Test</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Utility__c.object
<CustomObject>
    <fields>
        <fullName>Collect_Customer_POD_Number__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>When checked, we collect the customer PoD ID in SSF. Some utilities use this number to lookup EDI data</inlineHelpText>
        <label>Collect Customer PoD ID</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>POD_Id_Format__c</fullName>
        <inlineHelpText>The PoD Id format. Places groups of numbers in the desired format and uses regex capture groups as placeholders. Include prefix if applicable. Ex: for PoD Ids formatted XXX-XXX-XX the POD Id Format value is $1-$2-$3., for PoD Ids with the prefix R01 and formatted R01-XXX-XXX the POD Id Format value is R01-$1-$2.</inlineHelpText>
        <label>POD Id Format</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>POD_Id_Length__c</fullName>
        <inlineHelpText>Length of POD Ids. Ex: if POD Ids are written XXXX-XX-XX the length is 8. Prefixes are included in length. Ex: R01-XXXX-XXXX is length 11.</inlineHelpText>
        <label>POD Id Length</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>POD_Id_Prefix__c</fullName>
        <inlineHelpText>Used for automatically adding the POD Id prefix on forms.</inlineHelpText>
        <label>POD Id Prefix</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>POD_Id_Regex_Groups__c</fullName>
        <inlineHelpText>Regex for breaking utility account numbers into capture groups for formatting. Ex: to format a POD Id as XX-XXXX-XXXX-XXXX-X use the regex (\d{0,2})(\d{0,4})(\d{0,4})(\d{0,4})(\d?). Delimiters are captured in the POD Id Regex Delimiter field.</inlineHelpText>
        <label>POD Id Regex Groups</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Utility_Account_Number_Format__c</fullName>
        <inlineHelpText>The utility account number format. Places groups of numbers in the desired format and uses regex capture groups as placeholders. Include prefix if applicable. Ex: for UANs formatted XXX-XXX-XX the UAN Format value is $1-$2-$3. for UANs with prefix R01 and formatted R01-XXX-XXX the UAN Format value is R01-$1-$2.</inlineHelpText>
        <label>UAN Format</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Utility_Account_Number_Length__c</fullName>
        <inlineHelpText>Length of utility account numbers. Ex: if UANs are written XXXX-XX-XX the length is 8. Prefixes are included in length. Ex: R01-XXXX-XXXX is length 11.</inlineHelpText>
        <label>UAN Length</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Utility_Account_Number_Prefix__c</fullName>
        <inlineHelpText>Used for automatically adding the utility account number prefix on forms.</inlineHelpText>
        <label>UAN Prefix</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Utility_Account_Number_Regex_Groups__c</fullName>
        <inlineHelpText>Regex for breaking utility account numbers into capture groups for formatting. Ex: to format a utility account number as XX-XXXX-XXXX-XXXX-X use the regex (\d{0,2})(\d{0,4})(\d{0,4})(\d{0,4})(\d?). Delimiters are captured in the UAN Regex Delimiter field.</inlineHelpText>
        <label>UAN Regex Groups</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Utility_Data_Collection_Mechanism__c</fullName>
        <label>Utility Data Collection Mechanism</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>File Upload</fullName>
                    <default>true</default>
                    <label>File Upload</label>
                </value>
                <value>
                    <fullName>EDI</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Utility</label>
    <nameField>
        <label>Utility Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ZipCode_Utility_Junction__c.object
<CustomObject>
    <fields>
        <fullName>Load_Zone_Utility__c</fullName>
        <inlineHelpText>Lookup to the Load Zone and Utility Object</inlineHelpText>
        <label>Load Zone &amp; Utility</label>
        <referenceTo>Load_U__c</referenceTo>
        <relationshipLabel>ZipCode Utility Junctions</relationshipLabel>
        <relationshipName>ZipCode_Utility_Junctions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Utility__c</fullName>
        <label>Utility</label>
        <referenceTo>Utility__c</referenceTo>
        <relationshipLabel>ZipCode Utility Junctions</relationshipLabel>
        <relationshipName>ZipCode_Utility_Junctions</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>ZipCode Utility Junction</label>
    <nameField>
        <displayFormat>ZUJ-{00000}</displayFormat>
        <label>ZipCode Utility Junction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ZipCode Utility Junctions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ZipcodeUtilitiesSelector.cls
/**
 * Created by mstackhouse on 1/23/2019.
 * Description: Used to query zipcode utility junctions
 * Test: ZipcodeUtilitySelectorTest
 */

@SuppressWarnings('PMD.ApexCRUDViolation')
public inherited sharing class ZipcodeUtilitiesSelector {
    public static List<ZipCode_Utility_Junction__c> selectZipcodeUtilitiesAndLoadzones(String zipcode) {
        List<ZipCode_Utility_Junction__c> zipcodeUtilities = [
            SELECT
                Utility__r.Id,
                Utility__r.Name,
                Utility__r.Utility_Data_Collection_Mechanism__c,
                Utility__r.Collect_Customer_POD_number__c,
                Utility__r.Utility_Account_Number_Regex_Groups__c,
                Utility__r.Utility_Account_Number_Format__c,
                Utility__r.Utility_Account_Number_Prefix__c,
                Utility__r.Utility_Account_Number_Length__c,
                Utility__r.POD_Id_Regex_Groups__c,
                Utility__r.POD_Id_Format__c,
                Utility__r.POD_Id_Prefix__c,
                Utility__r.POD_Id_Length__c,
                Load_Zone_Utility__r.LZ__c,
                Load_Zone_Utility__r.Town__c,
                Load_Zone_Utility__r.Id,
                Load_Zone_Utility__r.Name
            FROM ZipCode_Utility_Junction__c
            WHERE Load_Zone_Utility__r.Name = :zipcode
        ];

        return zipcodeUtilities;
    }

    public static Set<String> selectZipCodesServedByUtility(String utilityId) {
        Set<String> zipCodesServed = new Set<String>();
        for (ZipCode_Utility_Junction__c junction : [
            SELECT Load_Zone_Utility__r.Name
            FROM ZipCode_Utility_Junction__c
            WHERE Utility__c = :utilityId
            ORDER BY Load_Zone_Utility__r.Name
        ]) {
            zipCodesServed.add(junction.Load_Zone_Utility__r.Name);
        }

        return zipCodesServed;
    }

}