src/objects/Load_U__c.object
<CustomObject>
    <description>General list of Massachusetts Zip Codes and their corresponding Load Zones and Utiliy providers.</description>
    <fields>
        <fullName>LZ__c</fullName>
        <label>Load Zone</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Town__c</fullName>
        <label>Town</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Utility__c</fullName>
        <label>XXXX Utility</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <label>Load Zone &amp; Utility</label>
    <nameField>
        <label>Zip Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Load Zones &amp; Utilities</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Town__c.object
<CustomObject>
    <fields>
        <fullName>Utility__c</fullName>
        <label>Utility</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>National Grid</fullName>
                </value>
                <value>
                    <fullName>Eversource</fullName>
                </value>
                <value>
                    <fullName>Eversource/Muni</fullName>
                </value>
                <value>
                    <fullName>Eversource/NGRID</fullName>
                </value>
                <value>
                    <fullName>Municipal/NGRID</fullName>
                </value>
                <value>
                    <fullName>Municipal</fullName>
                </value>
                <value>
                    <fullName>Green Mountain Power</fullName>
                </value>
                <value>
                    <fullName>Orange &amp; Rockland</fullName>
                </value>
                <value>
                    <fullName>PSE&amp;G</fullName>
                </value>
                <value>
                    <fullName>SCE&amp;G</fullName>
                </value>
                <value>
                    <fullName>Unitil</fullName>
                </value>
                <value>
                    <fullName>Green Mountain</fullName>
                    <isActive>false</isActive>
                    <label>Green Mountain</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Town</label>
    <nameField>
        <label>Town Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Towns</pluralLabel>
    <recordTypes>
        <fullName>Test</fullName>
        <active>true</active>
        <label>Test</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Utility__c.object
<CustomObject>
    <fields>
        <fullName>Number_of_Decimal_Places__c</fullName>
        <inlineHelpText>Used for calculating kW subscriptions for SOs</inlineHelpText>
        <label>Number of Decimal Places</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Utility</label>
    <nameField>
        <label>Utility Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ZipCode_Utility_Junction__c.object
<CustomObject>
    <fields>
        <fullName>Load_Zone_Utility__c</fullName>
        <inlineHelpText>Lookup to the Load Zone and Utility Object</inlineHelpText>
        <label>Load Zone &amp; Utility</label>
        <referenceTo>Load_U__c</referenceTo>
        <relationshipLabel>ZipCode Utility Junctions</relationshipLabel>
        <relationshipName>ZipCode_Utility_Junctions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Utility__c</fullName>
        <label>Utility</label>
        <referenceTo>Utility__c</referenceTo>
        <relationshipLabel>ZipCode Utility Junctions</relationshipLabel>
        <relationshipName>ZipCode_Utility_Junctions</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>ZipCode Utility Junction</label>
    <nameField>
        <displayFormat>ZUJ-{00000}</displayFormat>
        <label>ZipCode Utility Junction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ZipCode Utility Junctions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/ZipcodeUtilitiesSelectorTest.cls
/**
 * Created by mstackhouse on 1/23/2019.
 * Description: 
 * Test: 
 */

@IsTest
public with sharing class ZipcodeUtilitiesSelectorTest {

    public static zipcodeUtilitiesTestData insertTestData() {
        // Insert Utilities
        Utility__c eversource = new Utility__c(
            Name = 'Eversource',
            Number_of_Decimal_Places__c = 2
        );
        Utility__c nationalGrid = new Utility__c(
            Name = 'National Grid',
            Number_of_Decimal_Places__c = 2
        );
        List<Utility__c> utilities = new List<Utility__c>{eversource, nationalGrid};
        insert utilities;

        // Insert Load Zones
        Load_U__c lzu12345 = new Load_U__c (
            Name = '12345',
            LZ__c = 'SEMA',
            Town__c= 'Medfield'
        );
        Load_U__c lzu54321 = new Load_U__c (
            Name = '54321',
            LZ__c = 'SEMA',
            Town__c= 'Medfield'
        );
        List<Load_U__c> loadZones = new List<Load_U__c>{lzu12345, lzu54321};
        insert loadZones;

        // Insert Zipcode Utility Junctions
        ZipCode_Utility_Junction__c junction = new ZipCode_Utility_Junction__c(
            Load_Zone_Utility__c = lzu12345.Id,
            Utility__c = eversource.Id
        );
        ZipCode_Utility_Junction__c junction2 = new ZipCode_Utility_Junction__c(
            Load_Zone_Utility__c = lzu54321.Id,
            Utility__c = nationalGrid.Id
        );
        List<Zipcode_Utility_Junction__c> junctions= new List<ZipCode_Utility_Junction__c>{junction, junction2};
        insert junctions;

        return new zipcodeUtilitiesTestData(utilities, loadZones, junctions);
    }

    public class zipcodeUtilitiesTestData {
        public List<Utility__c> utilities;
        public List<Load_U__c> loadZones;
        public List<ZipCode_Utility_Junction__c> junctions;

        public zipcodeUtilitiesTestData(
            List<Utility__c> utilities, List<Load_U__c> loadZones, List<ZipCode_Utility_Junction__c> junctions)
        {
            this.utilities = utilities;
            this.loadZones = loadZones;
            this.junctions = junctions;
        }
    }

    @IsTest
    public static void testGetZipcodeUtilitiesAndLoadzones() {
        zipcodeUtilitiesTestData dataSet = insertTestData();

        // Test no match query
        List<ZipCode_Utility_Junction__c> noJunctions = ZipcodeUtilitiesSelector.selectZipcodeUtilitiesAndLoadzones('11111');
        System.assertEquals(0, noJunctions.size());

        // Test query match with one junction record found
        List<ZipCode_Utility_Junction__c> junctions12345 = ZipcodeUtilitiesSelector.selectZipcodeUtilitiesAndLoadzones('12345');
        System.assertEquals(1, junctions12345.size());
        System.assertEquals(dataSet.junctions[0].Id, junctions12345[0].Id);
        System.assertEquals(dataSet.utilities[0].Id, junctions12345[0].Utility__r.Id);
        System.assertEquals(dataSet.loadZones[0].Name, junctions12345[0].Load_Zone_Utility__r.Name);
        System.assertEquals(dataSet.loadZones[0].Id, junctions12345[0].Load_Zone_Utility__r.Id);

        // Test selectZipCodesServedByUtility query match
        Set<String> zipsServedByUtility = ZipcodeUtilitiesSelector.selectZipCodesServedByUtility((String) dataSet.utilities[0].Id);
        List<String> zipsServed = new List<String>(zipsServedByUtility);
        System.assertEquals(1, zipsServedByUtility.size());
        System.assertEquals(dataSet.loadZones[0].Name, zipsServed[0], 'Incorrect result for query of zipcodes served by Utility');
    }
}