src/objects/Loan__c.object
<CustomObject>
    <fields>
        <fullName>Loan_Number__c</fullName>
        <displayFormat>BW{0000000}</displayFormat>
        <externalId>true</externalId>
        <inlineHelpText>Auto-Number used to identify the Loan with external parties (like third party servicing)</inlineHelpText>
        <label>Loan Number</label>
        <type>AutoNumber</type>
    </fields>
    <label>Loan</label>
    <nameField>
        <label>Loan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loans</pluralLabel>
    <recordTypes>
        <fullName>Loan</fullName>
        <active>true</active>
        <label>Loan</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Loan_Payment__c.object
<CustomObject>
    <fields>
        <fullName>Cash_Code__c</fullName>
        <inlineHelpText>Cash Code as defined by Lease Dimensions. 
125 = cash payment (money was actually sent to lockbox and applied to account)
130 = non-cash payment (no physical transfer of money, a request from BW goes to LD to lower the principal, ex. IBLS reductions)</inlineHelpText>
        <label>Cash Code</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>125</fullName>
                </value>
                <value>
                    <fullName>130</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Check_Number__c</fullName>
        <inlineHelpText>Check Number or payment identifier (if paid via ACH)</inlineHelpText>
        <label>Check Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Interest_Applied__c</fullName>
        <inlineHelpText>Sum of Transaction Application Interest Applied</inlineHelpText>
        <label>Actual Interest Applied</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Loan__c</fullName>
        <label>Loan</label>
        <referenceTo>Loan__c</referenceTo>
        <relationshipLabel>Loan Payments</relationshipLabel>
        <relationshipName>Loan_Payments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Payment_Due_Date2__c</fullName>
        <label>Payment Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Period__c</fullName>
        <inlineHelpText>Index of Loan Payment for this loan, starting at 0 (representing the first payment) and going to Loan Term + Interest Only Period - 1.</inlineHelpText>
        <label>Period</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Principal_Applied__c</fullName>
        <inlineHelpText>Sum of Transaction Application Principal Applied</inlineHelpText>
        <label>Actual Principal Applied</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Prior_Period_Loan_Payment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Link to the prior Loan Payment, used to update Cumulative fields</inlineHelpText>
        <label>Prior Period Loan Payment</label>
        <referenceTo>Loan_Payment__c</referenceTo>
        <relationshipLabel>Next Loan Payments</relationshipLabel>
        <relationshipName>Loan_Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Loan Payment</label>
    <nameField>
        <displayFormat>LP-{000000}</displayFormat>
        <label>Loan Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/System_Properties__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>System Properties</label>
</CustomObject>

src/objects/Transaction_Application__c.object
<CustomObject>
    <fields>
        <fullName>Cash_Code__c</fullName>
        <label>Cash Code</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>125</fullName>
                </value>
                <value>
                    <fullName>129</fullName>
                </value>
                <value>
                    <fullName>130</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Check_Number__c</fullName>
        <inlineHelpText>Lease Dimensions Check Number</inlineHelpText>
        <label>Check Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>INTEREST PAYMENT
PRINCIPAL PAYDOWN
ASSET WRITEDOWN
PAYMENT PAST DUE INTEREST
INTEREST CREDIT
INTEREST CREDIT REVERSAL
PRINCIPAL PAYDOWN REVERSAL
INTEREST PAYMENT REVERSAL
PRINCIPAL PAYMENT
PRINCIPAL WRITEDOWN
PRINCIPAL PAYMENT REVERSAL
PAST DUE INTEREST PAYMENT REVERSAL
PRINCIPAL WRITEDOWN REVERSAL</description>
        <inlineHelpText>Lease Dimensions Transaction Description</inlineHelpText>
        <label>Description</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>IBL PMT - INTEREST</fullName>
                </value>
                <value>
                    <fullName>IBL PRN PAYDOWN</fullName>
                </value>
                <value>
                    <fullName>WRITE DOWN ASST INVN</fullName>
                </value>
                <value>
                    <fullName>PAYMENT OTHER CHARGE</fullName>
                </value>
                <value>
                    <fullName>IBL INT CR</fullName>
                </value>
                <value>
                    <fullName>IBL INT CR REV</fullName>
                </value>
                <value>
                    <fullName>IBL PRN PAYDOWN REV</fullName>
                </value>
                <value>
                    <fullName>IBL PMT REV - INT</fullName>
                </value>
                <value>
                    <fullName>IBL PMT - PRINCIPAL</fullName>
                </value>
                <value>
                    <fullName>IBL PRN WRITE-DOWN</fullName>
                </value>
                <value>
                    <fullName>IBL PMT REV - PRN</fullName>
                </value>
                <value>
                    <fullName>PMT REV OTHER CHARGE</fullName>
                </value>
                <value>
                    <fullName>IBL PRN WRITE-DN REV</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <inlineHelpText>Lease Dimensions Effective Date</inlineHelpText>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Interest_Applied__c</fullName>
        <inlineHelpText>Amount of interest that is applied to the related Loan Payment. Should be negative when reducing interest owed.</inlineHelpText>
        <label>Interest Applied</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Invoice_Due_Date__c</fullName>
        <inlineHelpText>Lease Dimensions Invoice Due Date, used to find a loan payment to apply to.</inlineHelpText>
        <label>Invoice Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Invoice_Number__c</fullName>
        <inlineHelpText>Lease Dimensions Invoice Number</inlineHelpText>
        <label>Invoice Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Loan_Payment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Loan Payment</label>
        <referenceTo>Loan_Payment__c</referenceTo>
        <relationshipLabel>Transaction Applications</relationshipLabel>
        <relationshipName>Transaction_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Principal_Applied__c</fullName>
        <inlineHelpText>Amount of principal that is applied to the related Loan Payment. Should be negative when reducing principal owed.</inlineHelpText>
        <label>Principal Applied</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Principal_Paydown_Reason__c</fullName>
        <inlineHelpText>Paydown reason (triggers loan reamortization)</inlineHelpText>
        <label>Principal Paydown Reason</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Paydown_Reasons</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Process_Date__c</fullName>
        <inlineHelpText>Lease Dimensions Process Date</inlineHelpText>
        <label>Process Date</label>
        <type>Date</type>
    </fields>
    <label>Transaction Application</label>
    <nameField>
        <displayFormat>TA-{0000}</displayFormat>
        <label>Transaction Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transaction Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Paydown_Reasons.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>IBLS</fullName>
    </customValue>
    <customValue>
        <fullName>Customer</fullName>
    </customValue>
    <description>Paydown reasons which update principal and trigger loan reamortization</description>
    <masterLabel>Paydown Reasons</masterLabel>
</GlobalValueSet>

src/classes/LeaseDimensionsImportController.cls
/**
 * Created By: Peter Yao
 * Description:  Creates Transaction Applications from a Lease Dimensions daily or monthly payment 
 *               file saved as a CSV
 *               Assumes 16 columns, from Portfolio through Comments
 * Tested by: LeaseDimensionsImportControllerTest
 **/

public without sharing class LeaseDimensionsImportController {
    public Document document {
        get {
            if (document == null)
                document = new Document();
            return document;
        }
        set;
    }
    public String filename {get;set;}
    public String lastDocProcessed {get;set;}
    transient List<Loan__c> loansFound;
    transient Set<String> loanNumbers;
    transient List<ReportLine> reportLines;
    transient Map<String, Loan__c> loanMap;
    public static Map<String, String> descriptionMap =
        new Map<String, String>{'IBL PMT - INTEREST' => 'Interest',
                                'IBL PRN PAYDOWN' => 'Principal',
                                'WRITE DOWN ASST INVN' => 'Principal',
                                'PAYMENT OTHER CHARGE' => 'Interest',
                                'IBL INT CR' => 'Interest',
                                'IBL INT CR REV' => 'Interest',
                                'IBL PRN PAYDOWN REV' => 'Principal',
                                'IBL PMT REV - INT' => 'Interest',
                                'IBL PMT - PRINCIPAL' => 'Principal',
                                'IBL PRN WRITE-DOWN' => 'Principal',
                                'IBL PMT REV - PRN' => 'Principal',
                                'PMT REV OTHER CHARGE' => 'Interest',
                                'IBL PRN WRITE-DN REV' => 'Principal'};

    public LeaseDimensionsImportController() {
        System_Properties__c sysProp = System_Properties__c.getAll().values()[0];
        lastDocProcessed = sysProp.Last_Lease_Dimensions_File_Processed__c;
    }

    public void processCSV() {
        loadCSV();
        generateTAs();
        Logger.flushLogs();
        System_Properties__c sysProp = System_Properties__c.getAll().values()[0];
        sysProp.Last_Lease_Dimensions_File_Processed__c = filename;
        update sysProp;
    }

    private void loadCSV() {
        CSVReader csvReader = new CSVReader(document.body.toString());
        String[] line;
        ReportLine rl;
        loanNumbers = new Set<String>();
        reportLines = new List<ReportLine>();
        while ((line = csvReader.readLine()) != null) {
            if (!isEmpty(line) &&
                !line[0].contains('Portfolio')) {
                try {
                    rl = new ReportLine(line);
                    reportLines.add(rl);
                    loanNumbers.add(rl.loanNumber);
                } catch (LDImportException ldie) {
                    Logger.logLater('LeaseDimensionsImportController', 'loadCSV', ldie.getMessage());
                }
            }
        }
        
        loanMap = new Map<String, Loan__c>();
        for (Loan__c loan : [SELECT Id, Loan_Number__c,
                             (SELECT Id, Period__c, Payment_Due_Date2__c
                              FROM Loan_Payments__r
                              WHERE Period__c <> null
                              ORDER BY Period__c)
                             FROM Loan__c
                             WHERE Loan_Number__c IN :loanNumbers]) {
            loanMap.put(loan.Loan_Number__c, loan);
        }
    }

    private void generateTAs() {
        List<Transaction_Application__c> taList = new List<Transaction_Application__c>();
        Transaction_Application__c ta;
        Loan__c loan;
        for (ReportLine rl : reportLines) {
            try {
                loan = loanMap.get(rl.loanNumber);
                if (loan != null) {
                    taList.add(rl.getTA(loan));
                }
            } catch (LDImportException ldie) {
                Logger.logLater('LeaseDimensionsImportController', 'loadCSV', ldie.getMessage());
            }
        }
        Logger.logLater('LeaseDimensionsImportController', 'loadCSV', 
                        'Inserting ' + taList.size() + ' transaction applications from ' + filename);
        insert taList;
    }

    private class ReportLine {
        String portfolio;
        String company;
        String region;
        String office;
        String account;
        String loanNumber;
        String customerName;
        Date processDate;
        Date paymentEffectiveDate;
        Date invoiceDueDate;
        String transactionDescription;
        String invoiceNumber;
        String checkNumber;
        String cashCode;
        Decimal amount;
        String reversalReason;
        String comments;
        
        private ReportLine(String[] inputLine) {
            if (inputLine.size() != 16 ||
                // Excel saves non-printing characters when saving to csv, so use contains instead of equals
                inputLine[0].contains('Portfolio') ||
                inputLine[4].equals('')) {
                throw new LDImportException('Not processing this line: ' + inputLine);
            }
            portfolio = inputLine[0];
            company = inputLine[1];
            region = inputLine[2];
            office = inputLine[3];
            account = inputLine[4];
            if (account.trim().startsWith('BW')) {
                loanNumber = account.trim();
            } else {
                loanNumber = 'BW' + account.trim().leftPad(7).replace(' ','0');
            }
            customerName = inputLine[5];
            processDate = Date.parse(inputLine[6].trim());
            if (!String.isBlank(inputLine[7])) {
                paymentEffectiveDate = Date.parse(inputLine[7].trim());
            }
            if (!String.isBlank(inputLine[8])) {
                invoiceDueDate = Date.parse(inputLine[8].trim());
            }
            transactionDescription = inputLine[9];
            invoiceNumber = inputLine[10];
            checkNumber = inputLine[11];
            cashCode = inputLine[12];
            amount = parse(inputLine[13]);
            reversalReason = inputLine[14];
            comments = inputLine[15];
        }

        private Decimal parse(String parsed) {
            if (parsed.contains('(') || parsed.contains(')')) {
                parsed = parsed.replaceAll('[(), ]', '');
                return Decimal.valueOf(parsed) * -1;
            } else {
                parsed = parsed.replaceAll('[, ]', '');
                return Decimal.valueOf(parsed);
            }
        }        

        public Transaction_Application__c getTA(Loan__c loan) {
            Transaction_Application__c ta =
                new Transaction_Application__c(Process_Date__c = processDate,
                                               Effective_Date__c = paymentEffectiveDate,
                                               Description__c = transactionDescription,
                                               Invoice_Number__c = invoiceNumber,
                                               Invoice_Due_Date__c = invoiceDueDate,
                                               Check_Number__c = checkNumber,
                                               Cash_Code__c = cashCode,
                                               Comments__c = (String.isBlank(reversalReason)?'':(reversalReason+'\n')) + comments);
            for (Loan_Payment__c lp : loan.Loan_Payments__r) {
                Date applyDate;
                if (invoiceDueDate != null) {
                    applyDate = invoiceDueDate;
                } else if (paymentEffectiveDate != null) {
                    applyDate = paymentEffectiveDate;
                } else {
                    applyDate = processDate;
                }
                if (LoanServicer.appliesTo(applyDate, lp)) {
                    ta.Loan_Payment__c = lp.Id;
                    break;
                }
            }
            if (ta.Loan_Payment__c == null) {
                throw new LDImportException('Could not find a loan payment to relate to. ' +
                                            'Loan: ' + account + ' Invoice Due Date: ' + invoiceDueDate);
            }
            String principalOrInterest;
            if ((principalOrInterest = descriptionMap.get(transactionDescription)) == null) {
                throw new LDImportException('Unknown transaction description found: ' + transactionDescription);
            } else if (principalOrInterest.equals('Principal')) {
                ta.Principal_Applied__c = amount;
            } else {
                ta.Interest_Applied__c = amount;
            }
            if (transactionDescription.equals('IBL PRN WRITE-DN REV') ||
                transactionDescription.equals('IBL PRN WRITE-DOWN') ||
                transactionDescription.equals('WRITE DOWN ASST INVN')) {
                if (comments.toUpperCase().contains('CUSTOMER')) {
                    ta.Principal_Paydown_Reason__c = 'Customer';
                } else {
                    ta.Principal_Paydown_Reason__c = 'IBLS';
                }
            }
            return ta;
        }
    }
    
    public boolean isEmpty(List<String> strings) {
        for (String s : strings) {
            if (!String.isEmpty(s.trim())) {
                return false;
            }
        }
        return true;
    }
    
    public class LDImportException extends Exception {}

}