src/objects/Loan__c.object
<CustomObject>
    <fields>
        <fullName>IRBD_Interest_Only_Date_Received__c</fullName>
        <label>IRBD (Interest Only) Date Received</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Loan_Data__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Capital Pool</label>
        <referenceTo>Loan_Data__c</referenceTo>
        <relationshipLabel>Loans</relationshipLabel>
        <relationshipName>Loans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Loan_Tranche__c</fullName>
        <label>Loan Tranche</label>
        <referenceTo>Loan_Traunch__c</referenceTo>
        <relationshipLabel>Loans</relationshipLabel>
        <relationshipName>Loans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Set by LoanHandler when the Loan&apos;s Lead is converted to an Opportunity</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Loans</relationshipLabel>
        <relationshipName>Loans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Unique_ID__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>LoanHandler uses to assign tranches and MCEC reporting</inlineHelpText>
        <label>Unique ID</label>
        <length>45</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Loan</label>
    <nameField>
        <label>Loan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loans</pluralLabel>
    <recordTypes>
        <fullName>Loan</fullName>
        <active>true</active>
        <label>Loan</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Loan_Data__c.object
<CustomObject>
    <fields>
        <fullName>Month__c</fullName>
        <label>Month</label>
        <picklist>
            <picklistValues>
                <fullName>January</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>February</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>March</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>April</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>May</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>June</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>July</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>August</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>September</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>October</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>November</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>December</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <picklist>
            <picklistValues>
                <fullName>2015</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2016</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2017</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2018</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2019</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2020</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Capital Pool</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Capital Pools</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Loan_Payment__c.object
<CustomObject>
    <fields>
        <fullName>Interest_Payment__c</fullName>
        <label>Interest Payment</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Loan__c</fullName>
        <label>Loan</label>
        <referenceTo>Loan__c</referenceTo>
        <relationshipLabel>Loan Payments</relationshipLabel>
        <relationshipName>Loan_Payments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Month__c</fullName>
        <formula>CASE(MONTH(  Payment_Due_Date2__c  ), 1, &quot;January&quot;, 2, &quot;February&quot;, 3, &quot;March&quot;,  4, &quot;April&quot;,  5, &quot;May&quot;,  6, &quot;June&quot;, 7, &quot;July&quot;, 8, &quot;August&quot;, 9, &quot;September&quot;, 10, &quot;October&quot;, 11, &quot;November&quot;, 12, &quot;December&quot;, &quot;None&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Month</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_1__c</fullName>
        <label>Date of Payment</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Payment_Number2__c</fullName>
        <label>Payment Number</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Principal_Payment__c</fullName>
        <label>Principal Payment</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Unique_ID__c</fullName>
        <externalId>true</externalId>
        <label>Unique ID</label>
        <length>45</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year (Inactive)</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>2015</fullName>
                </value>
                <value>
                    <fullName>2016</fullName>
                </value>
                <value>
                    <fullName>2017</fullName>
                </value>
                <value>
                    <fullName>2018</fullName>
                </value>
                <value>
                    <fullName>2019</fullName>
                </value>
                <value>
                    <fullName>2020</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Loan Payment</label>
    <nameField>
        <displayFormat>LP-{000000}</displayFormat>
        <label>Loan Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Loan_Traunch__c.object
<CustomObject>
    <fields>
        <fullName>Loan_Data__c</fullName>
        <label>Capital Pool</label>
        <referenceTo>Loan_Data__c</referenceTo>
        <relationshipLabel>Loan Tranches</relationshipLabel>
        <relationshipName>Loan_Tranches</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Loan Tranche</label>
    <nameField>
        <label>Tranche</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Tranches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>CS_Capacity_Allocated__c</fullName>
        <inlineHelpText>Sum of Future Customer Subscription (KW DC) on Utility Account Subscriptions when Opportunity is set to Complete. Used in Docusign.</inlineHelpText>
        <label>Customer Subscription kW DC at Complete</label>
        <precision>9</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Month__c</fullName>
        <formula>CASE(MONTH(CloseDate), 1, &quot;January&quot;, 2, &quot;February&quot;, 3, &quot;March&quot;, 4, &quot;April&quot;, 5, &quot;May&quot;, 6, &quot;June&quot;, 7, &quot;July&quot;, 8, &quot;August&quot;, 9, &quot;September&quot;, 10, &quot;October&quot;, 11, &quot;November&quot;, 12, &quot;December&quot;, &quot;None&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Month</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unique_ID__c</fullName>
        <label>Unique ID</label>
        <length>45</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <formula>text(year(CloseDate))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Year</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TestGLcreation.cls
@isTest
private class TestGLcreation{

Static testMethod void testGLcreation(){

Date myDate = Date.newInstance(2015, 2, 17);

Opportunity newOpportunity = new Opportunity(

name = 'Tester', 
type = 'New Business', 
closeDate = myDate, 
stageName='New', 
CS_Capacity_Allocated__c = 100,
DOER_Solar_Loan__c = TRUE,
IRBD_Interest_Only_Date_Received__c = myDate,
Disbursal_1_Contract_Signature_Checkbox__c = myDate,
Disbursal_2_Mechanical_Install_Checkbox__c = myDate,
Disbursal_3_Full_Install_Checkbox__c = myDate); 

insert newOpportunity;

loan_data__c newLoanData = new loan_data__c (
name = 'Loan Data', 
month__c = 'August', 
year__c = '2015');

insert newLoanData;

loan_traunch__c newLoanTranche = new loan_traunch__c (
loan_data__c = newLoanData.id, 
name = 'Loan Tranche');

insert newLoanTranche;

loan__c newLoan = new loan__c(
name = 'Loan', 
opportunity__c = newOpportunity.id, 
loan_tranche__c = newLoanTranche.id);

insert newLoan;

loan_payment__c newLoanPayment = new loan_payment__c ( 
name = 'Loan Payment', 
loan__c = newLoan.id,
interest_payment__c = 300,
principal_payment__c = 100, 
payment_1__c = myDate, 
payment_number2__c = 1, 
year__c = '2015',
Unique_ID__c = 'abvksjfkjri2j');


test.startTest();
insert newLoanPayment;
test.stopTest();
 
 
 
}
}