src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Set by OpportunityTriggerHandler on Opportunity creation, assuming Opportunity.Lead_ID__c (a text field) is also being set via Lead Mapping.</inlineHelpText>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Username__c</fullName>
        <label>Username</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Utility__c.object
<CustomObject>
    <fields>
        <fullName>Utility_DUNS_Number__c</fullName>
        <inlineHelpText>Used in the EDI integration as unique identifier for utilities</inlineHelpText>
        <label>Utility DUNS Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Utility</label>
    <nameField>
        <label>Utility Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Utility__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Account associated to this utitliy. This is where utility contacts and communications can be tracked.</inlineHelpText>
    <label>Utility Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Utilities</relationshipLabel>
    <relationshipName>Utilities</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Utility_Account_Log__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Utility Account Logs</relationshipLabel>
        <relationshipName>Utility_Account_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Address_Update__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checked if the UAL address info was different from the most recent UDR address info.</description>
        <inlineHelpText>Checked if the UAL address info was different from the most recent UDR address info.</inlineHelpText>
        <label>Address Update</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Annual_Cost_of_Electricity__c</fullName>
        <description>This is used for the SREC CS Product sizing. It is the total dollar amount a customer spends annually on their electric utility bill for this account. It is initially filled in with an estimate from the customer/partner during the CS application process, then filled in by Ops with the QCed amount.</description>
        <inlineHelpText>Used for SREC CS Product sizing. It&apos;s the total dollar amount spent annually on the electric utility bill. It is initially filled in with an estimate from the customer/partner during the CS application process, then filled in by Ops with the QCed amount.</inlineHelpText>
        <label>Annual Cost of Electricity</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Annual_kWh__c</fullName>
        <description>Value from most recent UDR. 
Used for customer sizing on SMART contracts.</description>
        <inlineHelpText>Value from most recent UDR.
Used for customer sizing on SMART contracts.</inlineHelpText>
        <label>Annual kWh</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Average_Demand__c</fullName>
        <description>Value from most recent UDR.</description>
        <inlineHelpText>Value from most recent UDR.</inlineHelpText>
        <label>Average Demand</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Utility Account Logs</relationshipLabel>
        <relationshipName>Utility_Account_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NYPA__c</fullName>
        <description>Checked during QC for National Grid NY if an account is NYPA.</description>
        <label>NYPA</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Name_on_Account__c</fullName>
        <label>Name on Utility Account</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Num_UDRPs_Annual_kWh__c</fullName>
        <label>Number of UDRPs used in Annual kWh</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Num_UDRPs_Avg_Demand__c</fullName>
        <label>Number of UDRPs used in Average Demand</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Premise_Number__c</fullName>
        <inlineHelpText>Xcel (MN) Requirement, also used in NYSEG/EGE. This number is premise specific, they do not change/move with a customer.</inlineHelpText>
        <label>Premise/PoD ID</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Previous_Name_on_Utility_Account__c</fullName>
        <label>Previous Name on Utility Account</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Previous_Service_Address__c</fullName>
        <label>Previous Service Address</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Previous_Service_City__c</fullName>
        <label>Previous Service City</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Previous_Service_State__c</fullName>
        <label>Previous Service State</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Previous_Service_Zip_Code__c</fullName>
        <label>Previous Service Zip Code</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>QC_Status__c</fullName>
        <description>Status of Utility Data Request for automated data collection (e.g. EDI) on this Utility Account</description>
        <inlineHelpText>Status of Utility Data Request for automated data collection (e.g. EDI) on this Utility Account</inlineHelpText>
        <label>QC Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending Utility Data</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Pending BW Review</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RNY__c</fullName>
        <description>Checked during QC for National Grid NY if an account is RNY.</description>
        <label>RNY</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Service_Address__c</fullName>
        <label>Service Address</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_City__c</fullName>
        <label>Service City</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_State__c</fullName>
        <label>Service State</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Zip_Code__c</fullName>
        <label>Service Zip Code</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Username__c</fullName>
        <label>Username</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Utility_Rate_Class__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is populated by sales/operations. It is the utility rate class that a specific utility account has.</description>
        <inlineHelpText>Automatically populated for EDI-enabled utilities if related UDRP records have a Rate Class/Subclass matching a Rate Class record. Otherwise, manually populated by sales/ops from the Utility Bill and changed through the &quot;Recalculate Subscriptions&quot; button.</inlineHelpText>
        <label>Rate Class</label>
        <referenceTo>Rate_Class__c</referenceTo>
        <relationshipLabel>Utility Account Logs</relationshipLabel>
        <relationshipName>Utility_Account_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Utility_lookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Utility</label>
        <referenceTo>Utility__c</referenceTo>
        <relationshipLabel>Utility Account Logs</relationshipLabel>
        <relationshipName>Utility_Account_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Utility Account Log</label>
    <nameField>
        <label>Utility Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Account Logs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Utility_Account_Subscription__c.object
<CustomObject>
    <fields>
        <fullName>Annual_Cost_of_Electricity__c</fullName>
        <description>Total cost of electricity at the UAL level.</description>
        <label>Full Annual Cost of Electricity</label>
        <precision>9</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Name_on_Account__c</fullName>
        <description>Customer&apos;s name on their electric bill</description>
        <label>Name on Account</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Utility_Account_Log__c</fullName>
        <inlineHelpText>The related UAL</inlineHelpText>
        <label>Utility Account Log</label>
        <referenceTo>Utility_Account_Log__c</referenceTo>
        <relationshipLabel>Utility Account Subscriptions</relationshipLabel>
        <relationshipName>Utility_Account_Subscriptions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Utility Account Subscription</label>
    <nameField>
        <label>Utility Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Account Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Utility_Data_Request__c.object
<CustomObject
     >
    <fields>
        <fullName>Annual_kWh__c</fullName>
        <description>Value calculated from UDRP Quantities in the last 12 months where the Measurement Unit = KH and the Measurement Significance Code = 51</description>
        <inlineHelpText>Value calculated from UDRP Quantities in the last 12 months where the Measurement Unit = KH and the Measurement Significance Code = 51</inlineHelpText>
        <label>Annual kWh</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Average_Demand__c</fullName>
        <description>Value calculated from UDRP Quantities in the last 12 months where the Measurement Unit = K1 and the Measurement Significance Code = 51</description>
        <inlineHelpText>Value calculated from UDRP Quantities in the last 12 months where the Measurement Unit = K1 and the Measurement Significance Code = 51</inlineHelpText>
        <label>Average Demand</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Utility_Account_Log__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Utility Account Log</label>
        <referenceTo>Utility_Account_Log__c</referenceTo>
        <relationshipLabel>Utility Data Requests</relationshipLabel>
        <relationshipName>Utility_Data_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Utility Data Request</label>
    <nameField>
        <displayFormat>UDR-{00000}</displayFormat>
        <label>Utility Data Request</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Utility Data Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Utility_Data_Request__c/fields/Num_UDRPs_Annual_kWh__c.field-meta.xml
<CustomField>
    <fullName>Num_UDRPs_Annual_kWh__c</fullName>
    <label>Number of UDRPs used in Annual kWh</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Utility_Data_Request__c/fields/Num_UDRPs_Avg_Demand__c.field-meta.xml
<CustomField>
    <fullName>Num_UDRPs_Avg_Demand__c</fullName>
    <label>Number of UDRPs used in Average Demand</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Utility_Data_Request__c/fields/Premise_Number__c.field-meta.xml
<CustomField>
    <fullName>Premise_Number__c</fullName>
    <label>Premise/PoD ID</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

src/classes/UALSelector.cls
/**
 * Created by jlugo on 2019-07-10.
 * Tested by: UALSelectorTest, UtilityDataRequestServiceTest, and system tests in RESTRouterV2Test
 */
@SuppressWarnings('PMD.ApexCRUDViolation')
public without sharing class UALSelector {
    
    public Utility_Account_Log__c selectOne(Id utilityAccountLogId) {
        List<Utility_Account_Log__c> uals = this.selectAll(new Set<Id>{utilityAccountLogId});
        if (uals.isEmpty()) {
            return null;
        }
        return uals[0];
    }
    
    public List<Utility_Account_Log__c> selectAll(Set<Id> utilityAccountLogIds) {
        return [
            SELECT Id, Name, Name_on_Account__c, Service_Address__c, Service_City__c, Service_State__c,
                Service_Zip_Code__c, Annual_kWh__c, Annual_Cost_of_Electricity__c, Account__c, Lead__c,
                Average_Demand__c, Utility_lookup__c, Utility_Rate_Class__c, Utility_Rate_Class__r.Name,
            	Num_UDRPs_Annual_kWh__c, Num_UDRPs_Avg_Demand__c, NYPA__c, RNY__c, Address_Update__c,
            	Username__c, Previous_Name_on_Utility_Account__c, Previous_Service_Address__c, QC_Status__c,
            	Previous_Service_City__c, Previous_Service_State__c, Previous_Service_Zip_Code__c, Premise_Number__c
            FROM Utility_Account_Log__c
            WHERE Id = :utilityAccountLogIds
        ];
    }
    
    public Map<Id,Utility_Account_Log__c> selectAllMap(Set<Id> utilityAccountLogIds) {
        return new Map<Id, Utility_Account_Log__c>([
            SELECT Id, Name, Name_on_Account__c, Service_Address__c, Service_City__c, Service_State__c,
                Service_Zip_Code__c, Annual_kWh__c, Annual_Cost_of_Electricity__c, Account__c, Lead__c,
                Average_Demand__c, Utility_lookup__c, Utility_Rate_Class__c, Utility_Rate_Class__r.Name,
            	Num_UDRPs_Annual_kWh__c, Num_UDRPs_Avg_Demand__c, NYPA__c, RNY__c, Address_Update__c,
            	Username__c, Previous_Name_on_Utility_Account__c, Previous_Service_Address__c, QC_Status__c,
            	Previous_Service_City__c, Previous_Service_State__c, Previous_Service_Zip_Code__c, Premise_Number__c
            FROM Utility_Account_Log__c
            WHERE Id = :utilityAccountLogIds
        ]);
    }
    
    public Map<Id, Utility_Account_Log__c> selectAllByLeadMap(Set<Id> leadIds) {
        return new Map<Id, Utility_Account_Log__c>([
            SELECT Id, Name, Name_on_Account__c, Service_Address__c, Service_City__c, Service_State__c,
                Service_Zip_Code__c, Annual_kWh__c, Annual_Cost_of_Electricity__c, Account__c, Lead__c,
                Average_Demand__c, Utility_lookup__c, Utility_Rate_Class__c, Utility_Rate_Class__r.Name,
            	Num_UDRPs_Annual_kWh__c, Num_UDRPs_Avg_Demand__c, NYPA__c, RNY__c, Address_Update__c,
            	Username__c, Previous_Name_on_Utility_Account__c, Previous_Service_Address__c, QC_Status__c,
            	Previous_Service_City__c, Previous_Service_State__c, Previous_Service_Zip_Code__c, Premise_Number__c
            FROM Utility_Account_Log__c
            WHERE Lead__c = :leadIds
        ]);
    }

    public List<Utility_Account_Log__c> selectUalsWithUdrs(List<Id> leadIds) {

        return [
            SELECT Id, Name, Utility_lookup__r.Utility_DUNS_Number__c, Utility_lookup__c, Utility_lookup__r.Name,
                Utility_lookup__r.Utility_Data_Collection_Mechanism__c, QC_Status__c, Premise_Number__c,
                Utility_lookup__r.Use_Glynt__c,
                (SELECT Id FROM Utility_Data_Requests__r)
            FROM Utility_Account_Log__c
            WHERE Lead__c IN :leadIds
            AND (Utility_lookup__r.Utility_Data_Collection_Mechanism__c = 'EDI'
            OR (Utility_lookup__r.Utility_Data_Collection_Mechanism__c = 'File Upload' AND Utility_lookup__r.Use_Glynt__c = TRUE))
        ];
    }

    public List<Utility_Account_Log__c> selectDuplicateUALs(String ualNumber) {
        return [
            SELECT
                Id,
                Name,
                Lead__r.Application_Complete_Date__c,
                Lead__r.Continue_Application_Link__c,
                Lead__r.IsConverted,
                Lead__r.Status,
                Opportunity__r.StageName,
                (SELECT Id, Opportunity__r.StageName
                    FROM Utility_Account_Subscriptions__r
                    WHERE Next_Schedule_Z_Status__c = 'Active Subscription'
                )
            FROM Utility_Account_Log__c
            WHERE Name = :ualNumber
            AND Lead__r.LastName != 'Testcase'
        ];
    }
}