src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Custom_ID__c</fullName>
        <label>Custom ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NMC_Tariff__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>NMC Tariff</label>
        <referenceTo>Utility_NMC_Tariff__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Utility_NMC_Tariff__c.object
<CustomObject>
    <label>Sizing Method</label>
    <nameField>
        <label>Utility and Class</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sizing Methods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/nmcCustomIdTriggerTestClass.cls
@isTest
private class nmcCustomIdTriggerTestClass {

Static testMethod void nmcCustomIdTrigger(){

Date myDate = Date.newInstance(2015, 2, 17);

MPM4_BASE__Milestone1_Project__c newProject = new MPM4_BASE__Milestone1_Project__c( name = 'tester', Total_MWDC__c = 500);

insert newProject;

opportunity newOpp = new opportunity(name = 'Cole Swain', custom_id__c = 'Cole 1',StageName = 'New', closeDate = myDate) ;
Utility_NMC_Tariff__c newNMC = new Utility_NMC_Tariff__c(name ='Eversource Class 2');

Insert newNMC;

Utility_NMC_Tariff__c NMCQuery = [SELECT id FROM Utility_NMC_Tariff__c WHERE name = 'Eversource Class 2'];

test.startTest();
 
insert newOpp;
 
test.stopTest();
 
opportunity oppQuery = [SELECT name, NMC_Tariff__c FROM opportunity WHERE name = 'Cole Swain'];
 
system.assertEquals(null, oppQuery.NMC_Tariff__c);
 
 
}
}