src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>355</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Shared_Solar_System__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>To change this system, use the Change SSS quick action</inlineHelpText>
        <label>Shared Solar System</label>
        <referenceTo>Shared_Solar_System__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Shared_Solar_System__c.object
<CustomObject
     >
    <articleTypeChannelDisplay n1:nil="true" />
    <customSettingsType n1:nil="true" />
    <description n1:nil="true" />
    <eventType n1:nil="true" />
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <gender n1:nil="true" />
    <household>false</household>
    <label>Shared Solar System</label>
    <nameField>
        <label>Shared Solar System Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shared Solar Systems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <startsWith n1:nil="true" />
</CustomObject>

src/objects/Subscription_Order__c.object
<CustomObject>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <description>Subscription Orders will not be rolled up to the utility account subscription until they are marked as approved. Once approved, they cannot be changed.</description>
        <inlineHelpText>Subscription Orders will not be rolled up to the utility account subscription until they are marked as approved. Once approved, they cannot be changed.</inlineHelpText>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <description>This is the date that the Subscription Order was approved. It is populated automatically when the Status field is set to approved. Subscription Orders cannot be edited once they&apos;ve been approved.</description>
        <inlineHelpText>This is the date that the Subscription Order was approved. It is populated automatically when the Status field is set to approved. Subscription Orders cannot be edited once they&apos;ve been approved.</inlineHelpText>
        <label>Effective Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>New_Annual_kWh__c</fullName>
        <inlineHelpText>This is the new annual kwh that the UAS will have once this SO is effective.</inlineHelpText>
        <label>New Annual kWh</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Previous_kw_DC_Subscription__c</fullName>
        <description>This is the kw dc subscription on the related UAS at the time to subscription order was created.</description>
        <label>Previous kw DC Subscription</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Transfer</fullName>
                </value>
                <value>
                    <fullName>Cancellation</fullName>
                </value>
                <value>
                    <fullName>Shared Solar System Update</fullName>
                </value>
                <value>
                    <fullName>Resize</fullName>
                </value>
                <value>
                    <fullName>Initial</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Utility_Account_Subscription__c</fullName>
        <label>Utility Account Subscription</label>
        <referenceTo>Utility_Account_Subscription__c</referenceTo>
        <relationshipLabel>Subscription Orders</relationshipLabel>
        <relationshipName>Subscription_Orders</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Utility_NMC_Tariff__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>This is the Sizing Method used to calculate the Subscription at the time this record was created.</description>
        <inlineHelpText>This is the Sizing Method used to calculate the Subscription at the time this record was created.</inlineHelpText>
        <label>Sizing Method</label>
        <referenceTo>Utility_NMC_Tariff__c</referenceTo>
        <relationshipLabel>Subscription Orders</relationshipLabel>
        <relationshipName>Subscription_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Subscription Order</label>
    <nameField>
        <displayFormat>SO-{00000}</displayFormat>
        <label>Subscription Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscription Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Subscription_Transfer__c.object
<CustomObject>
    <description>This relates Utility Account Subscriptions that are being transferred and holds the value and date information for the amount that is being transferred.</description>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <description>Effective Date of the subscription transfer.  This is the date that the new Allocation Schedule containing the new subscriptions is enacted.</description>
        <inlineHelpText>Effective Date of the subscription transfer.  This is the date that the new Allocation Schedule containing the new subscriptions is enacted.</inlineHelpText>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Sum_of_New_Subscriptions__c</fullName>
        <description>Sum of subscriptions being created by this Subscription Transfer</description>
        <inlineHelpText>Sum of subscriptions being created by this Subscription Transfer.  Populate based on % subscription x Project Size on Allocation Schedule Subscriptions.</inlineHelpText>
        <label>Sum of New Subscription (kW DC)</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sum_of_Old_Subscriptions__c</fullName>
        <description>Sum of subscriptions being replaced by this Subscription Transfer.</description>
        <inlineHelpText>Sum of subscriptions being replaced by this Subscription Transfer.  Populate based on % subscription x Project Size on Allocation Schedule Subscriptions.</inlineHelpText>
        <label>Sum of Old Subscriptions (kW DC)</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <label>Subscription Transfer</label>
    <nameField>
        <displayFormat>ST-{000}</displayFormat>
        <label>Subscription Transfer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscription Transfers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Utility_Account_Subscription__c.object
<CustomObject>
    <fields>
        <fullName>Annual_Cost_Future_Rollup__c</fullName>
        <inlineHelpText>This is a rollup of all approved subscription orders</inlineHelpText>
        <label>Annual Cost (Future)</label>
        <summarizedField>Subscription_Order__c.Change_in_Annual_Cost__c</summarizedField>
        <summaryFilterItems>
            <field>Subscription_Order__c.Approval_Status__c</field>
            <operation>equals</operation>
            <value>Approved</value>
        </summaryFilterItems>
        <summaryForeignKey>Subscription_Order__c.Utility_Account_Subscription__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Annual_kWh_Subscription_Future_Rollup__c</fullName>
        <inlineHelpText>This is a rollup of all approved subscription orders.</inlineHelpText>
        <label>Annual kWh Subscription (Future)</label>
        <summarizedField>Subscription_Order__c.Change_in_Annual_kWh__c</summarizedField>
        <summaryFilterItems>
            <field>Subscription_Order__c.Approval_Status__c</field>
            <operation>equals</operation>
            <value>Approved</value>
        </summaryFilterItems>
        <summaryForeignKey>Subscription_Order__c.Utility_Account_Subscription__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Future_Customer_Subscription_KWDC_Rollup__c</fullName>
        <inlineHelpText>This is a rollup of all approved subscription orders.</inlineHelpText>
        <label>Future Customer Subscription (KW DC)</label>
        <summarizedField>Subscription_Order__c.Approved_Change_in_Subscription__c</summarizedField>
        <summaryFilterItems>
            <field>Subscription_Order__c.Approval_Status__c</field>
            <operation>equals</operation>
            <value>Approved</value>
        </summaryFilterItems>
        <summaryForeignKey>Subscription_Order__c.Utility_Account_Subscription__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Next_Schedule_Z_Status__c</fullName>
        <defaultValue>&quot;Active Subscription&quot;</defaultValue>
        <inlineHelpText>Controls whether this subscription should be added to future Allocation Schedules. Select &apos;Active Subscription&apos; to include it, or &apos;Inactive Subscription&apos; to exclude it.</inlineHelpText>
        <label>Next Allocation Schedule Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active Subscription</fullName>
                    <default>true</default>
                    <label>Active Subscription</label>
                </value>
                <value>
                    <fullName>Inactive Subscription</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Shared_Solar_System__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the SSS on the Opportunity when the UAS was created. The SSS on an existing UAS should never be changed.</description>
        <inlineHelpText>This is the SSS on the Opportunity when the UAS was created. The SSS on an existing UAS should never be changed.</inlineHelpText>
        <label>Shared Solar System</label>
        <referenceTo>Shared_Solar_System__c</referenceTo>
        <relationshipLabel>Utility Account Subscriptions</relationshipLabel>
        <relationshipName>Utility_Account_Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sizing_Method__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Sizing Method with either NMC Value or Size Ratio to be used in calculating subscriptions</description>
        <inlineHelpText>Sizing Method with either NMC Value or Size Ratio to be used in calculating subscriptions. If you need to change the Sizing Method, log a new Subscription Order via button.</inlineHelpText>
        <label>Sizing Method</label>
        <referenceTo>Utility_NMC_Tariff__c</referenceTo>
        <relationshipLabel>Utility Account Subscriptions</relationshipLabel>
        <relationshipName>Utility_Account_Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subscription_Type__c</fullName>
        <description>This is the Customer Subscription Type field from the Product assigned to the Opportunity the UAS is for. It determines if the UAS should use the Annual kWh of Annual Cost fields for sizing, and is used by a validation rule to prevent the wrong sizing fields from being used.</description>
        <formula>TEXT(Opportunity__r.Product__r.Customer_Subscription_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>This is the Customer Subscription Type field from the Product assigned to the Opportunity the UAS is for. Determines if the Annual kWh or the Annual Cost fields should be used, and is used by a validation rule to prevent usage of the wrong sizing fields.</inlineHelpText>
        <label>Subscription Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transferred_From__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the lookup to the Subscription Transfer that is used to relate the newly created UAS to the Subscription Transfer that created it.</description>
        <inlineHelpText>This should be populated when a new UAS is created from a Subscription Transfer.  There should usually be one UAS created by a single Subscription Transfer unless a UAS is being split into multiple new UASs.</inlineHelpText>
        <label>Transferred From</label>
        <referenceTo>Subscription_Transfer__c</referenceTo>
        <relationshipLabel>Transferred to UASs</relationshipLabel>
        <relationshipName>Utility_Account_Subscriptions1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Transferred_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the lookup to the transfer object which relates to both this UAS and the UAS that is replacing it.</description>
        <inlineHelpText>This should be populated when a UAS is transferred to a new one via Subscription Transfer.  You should typically make a new transfer for each UAS that is being transferred unless they are being combined.</inlineHelpText>
        <label>Transferred To</label>
        <referenceTo>Subscription_Transfer__c</referenceTo>
        <relationshipLabel>Transferred From UASs</relationshipLabel>
        <relationshipName>Utility_Account_Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Utility Account Subscription</label>
    <nameField>
        <label>Utility Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Account Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SubscriptionTransferService.cls
/**
 * @description Transfers subscriptions between or within customers. They need three Subscription Orders: one to zero
 * out the old UAS, a Transfer SO to move the old capacity to the new UAS, and a Resize to handle any change in capacity
 * due to yield, system size, or decimal changes.
 * Tested By: SubscriptionTransferServiceTest
 */
public without sharing class SubscriptionTransferService {
    private static UASSelector uasSelectorInstance = new UASSelector();
    @TestVisible private static SharedSolarSystemsSelector sssSelector = new SharedSolarSystemsSelector();
    private static SubscriptionTransferCalculator calculator = new SubscriptionTransferCalculator();
    @TestVisible private static fflib_SObjectUnitOfWork uowForTransferSO = new fflib_SObjectUnitOfWork(
        new List<SObjectType>{
            Opportunity.SObjectType,
            Subscription_Transfer__c.SObjectType,
            Utility_Account_Subscription__c.SObjectType,
            Subscription_Order__c.SObjectType
        }
    );
    // Since the Resize SO depends on UAS Future_Customer_Subscription_KWDC_Rollup__c including the value of the new
    // Transfer SO, the Resize SO needs to happen in a subsequent transaction
    @TestVisible private static fflib_SObjectUnitOfWork uowForResizeSO = new fflib_SObjectUnitOfWork(
        new List<SObjectType>{
            Subscription_Order__c.SObjectType
        }
    );

    /**
     * @description Changes the SSS on the opportunity by:
     * - zeroing out the existing UASes
     * - setting the existing UASes to inactive
     * - creating a new UAS for each of the existing UASes on the new SSS
     * - creating a new subscription order for each of the new UASes
     * - updating the opportunity's SSS
     * @param oppId oppId
     * @param newSSSId new SSS Id
     */
    public void changeOpportunitySSS(Id oppId, Id newSSSId) {
        Shared_Solar_System__c sss = sssSelector.selectOne(newSSSId);
        Opportunity opp = new Opportunity(
            Id = oppId,
            Shared_Solar_System__c = newSSSId
        );
        uowForTransferSO.registerDirty(opp);
        //Get all createable fields for Active Subscriptions - if we add more fields later, this query will still grab them
        List<Utility_Account_Subscription__c> oldUASes = uasSelectorInstance.getUASForCloneByOpp(new Set<Id>{oppId});
        for (Utility_Account_Subscription__c oldUAS : oldUASes) {
            Utility_Account_Subscription__c uasForNewSSS = cloneNewUAS(oldUAS, newSSSId, sss.Name);
            Decimal desiredAmount =
                oldUAS.Subscription_Type__c == 'kWh' ? oldUAS.Annual_kWh_Subscription_Future_Rollup__c : oldUAS.Annual_Cost_Future_Rollup__c;
            registerTransferAndResize(oldUAS, uasForNewSSS, sss, desiredAmount);
        }
        UtilityAccountSubscriptions utilityAccountSubscriptions = new UtilityAccountSubscriptions(oldUASes);
        utilityAccountSubscriptions.registerSubscriptionOrdersToZeroOutUAS('Transfer', uowForTransferSO);
        uowForTransferSO.commitWork();
        uowForResizeSO.commitWork();
    }

    /**
     * @description Transfers a subscription from an existing UAS to another existing UAS (between customers)
     * @param oldUASId Id of the old UAS, with Annual_kWh or cost rollups
     * @param newUASId Id of the new UAS
     * @param amountToTransfer Total amount to transfer, including any resize portion, either in kWh or dollars
     * depending on the subscription type
     */
    public void transferToUAS(Id oldUASId, Id newUASId, Decimal amountToTransfer) {
        Map<Id, Utility_Account_Subscription__c> uasMap =
            new Map<Id, Utility_Account_Subscription__c>(UASSelector.selectByIds(new Set<Id>{newUASId, oldUASId}));
        Utility_Account_Subscription__c oldUAS = uasMap.get(oldUASId);
        Utility_Account_Subscription__c newUAS = uasMap.get(newUASId);

        if (oldUAS.Subscription_Type__c != newUAS.Subscription_Type__c) {
            throw new Util.BWException('Subscriptions must be the same type, ' +
                'the old UAS is ' + oldUAS.Subscription_Type__c + ' and the new UAS is ' + newUAS.Subscription_Type__c);
        }

        Shared_Solar_System__c sss = sssSelector.selectOne(newUAS.Shared_Solar_System__c);

        registerTransferAndResize(oldUAS, newUAS, sss, amountToTransfer);

        UtilityAccountSubscriptions utilityAccountSubscriptions =
            new UtilityAccountSubscriptions(new List<Utility_Account_Subscription__c>{oldUAS});
        utilityAccountSubscriptions.registerSubscriptionOrdersToZeroOutUAS('Transfer', uowForTransferSO);
        uowForTransferSO.commitWork();
        uowForResizeSO.commitWork();
    }

    private void registerTransferAndResize(Utility_Account_Subscription__c oldUAS, Utility_Account_Subscription__c newUAS,
        Shared_Solar_System__c sss, Decimal desiredAnnualkWhOrCost) {
        Subscription_Transfer__c transfer = getNewSubscriptionTransferRecord(oldUAS);
        uowForTransferSO.registerNew(transfer);
        uowForTransferSO.registerDirty(oldUAS, Utility_Account_Subscription__c.Transferred_To__c, transfer);
        if (newUAS.Id == null) {
            uowForTransferSO.registerNew(newUAS, Utility_Account_Subscription__c.Transferred_From__c, transfer);
        } else {
            uowForTransferSO.registerDirty(newUAS, Utility_Account_Subscription__c.Transferred_From__c, transfer);
        }

        Subscription_Order__c transferSO = getNewTransferSO(oldUAS, newUAS, sss);
        uowForTransferSO.registerNew(transferSO, Subscription_Order__c.Utility_Account_Subscription__c, newUAS);

        Subscription_Order__c resizeSO = getNewResizeSO(
            'Residual resize when transferring from UAS ' + oldUAS.Id,
            newUAS.Subscription_Type__c,
            desiredAnnualkWhOrCost
        );
        uowForResizeSO.registerNew(resizeSO, Subscription_Order__c.Utility_Account_Subscription__c, newUAS);

        oldUAS.Next_Schedule_Z_Status__c = 'Inactive Subscription';
        uowForTransferSO.registerDirty(oldUAS);
    }

    private Subscription_Transfer__c getNewSubscriptionTransferRecord(Utility_Account_Subscription__c oldUAS) {
        Subscription_Transfer__c transfer = new Subscription_Transfer__c();
        if (oldUAS.Subscription_Type__c == 'kWh') {
            transfer.Sum_of_Old_Subscriptions__c = oldUAS.Annual_kWh_Subscription_Future_Rollup__c;
            transfer.Sum_of_New_Subscriptions__c = oldUAS.Annual_kWh_Subscription_Future_Rollup__c;
        } else {
            transfer.Sum_of_Old_Subscriptions__c = oldUAS.Annual_Cost_Future_Rollup__c;
            transfer.Sum_of_New_Subscriptions__c = oldUAS.Annual_Cost_Future_Rollup__c;
        }
        return transfer;
    }

    private Subscription_Order__c getNewTransferSO(Utility_Account_Subscription__c oldUAS,
        Utility_Account_Subscription__c newUAS, Shared_Solar_System__c sss) {
        Subscription_Order__c so = new Subscription_Order__c(
            Type__c = 'Transfer',
            Approval_Status__c = 'Approved',
            Effective_Date__c = System.now()
        );
        Decimal amountToTransfer = 0;
        if (oldUAS.Future_Customer_Subscription_KWDC_Rollup__c == 0 &&
            !oldUAS.Subscription_Orders__r.isEmpty() &&
            oldUAS.Subscription_Orders__r[0].Type__c == 'Cancellation') {
            amountToTransfer = oldUAS.Subscription_Orders__r[0].Previous_kw_DC_Subscription__c;
        } else {
            amountToTransfer = oldUAS.Future_Customer_Subscription_KWDC_Rollup__c;
        }
        Decimal annualkWhOrCost = calculator.getAnnualkWhOrCost(
            oldUAS.Subscription_Type__c,
            sss,
            oldUAS.Sizing_Method__r,
            amountToTransfer,
            // If the new UAS already exists, we want to include the current subscription when calculating the amount
            // to back into. But if it doesn't exist yet, it might be cloned and still have a
            // Future_Customer_Subscription_KWDC_Rollup__c value which we want to ignore
            (newUAS.Id == null?0:newUAS.Future_Customer_Subscription_KWDC_Rollup__c)
        );
        setCostOrkWh(so, oldUAS.Subscription_Type__c, annualkWhOrCost);
        so.Comments__c = 'Transferring ' + oldUAS.Future_Customer_Subscription_KWDC_Rollup__c;
        return so;
    }

    private Subscription_Order__c getNewResizeSO(String comment, String subscriptionType, Decimal newAmount) {
        Subscription_Order__c resizeSO = new Subscription_Order__c(
            Type__c = 'Resize',
            Approval_Status__c = 'Approved',
            Effective_Date__c = System.now(),
            Comments__c = comment
        );
        setCostOrkWh(resizeSO, subscriptionType, newAmount);
        return resizeSO;
    }

    private void setCostOrkWh(Subscription_Order__c so, String subscriptionType, Decimal amount) {
        if (subscriptionType == 'kWh') {
            so.New_Annual_kWh__c = amount;
        } else {
            so.New_Annual_Cost__c = amount;
        }
    }

    private Utility_Account_Subscription__c cloneNewUAS(Utility_Account_Subscription__c oldUAS, Id newSSSId, String newSSSName) {
        Utility_Account_Subscription__c uasForNewSSS = oldUAS.clone(false, true, false, false);
        uasForNewSSS.Shared_Solar_System__c = newSSSId;
        uasForNewSSS.Subscription_Comment_c__c = 'UAS created as transfer from  ' + oldUAS.Shared_Solar_System__r.Name +
            ' to ' + newSSSName;
        return uasForNewSSS;
    }
}