src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Customer_Subscription_Type__c</fullName>
        <label>Customer Subscription Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>kWh</fullName>
                </value>
                <value>
                    <fullName>Electricity Cost ($)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Subscription_Order__c.object
<CustomObject>
    <fields>
        <fullName>Allocation_Schedule_Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The first allocation schedule subscription created after this subscription order. The allocation schedule may or may not be accepted and executed by the utility.</inlineHelpText>
        <label>Allocation Schedule Subscription</label>
        <referenceTo>Schedule_Z_Subscription__c</referenceTo>
        <relationshipLabel>Subscription Orders</relationshipLabel>
        <relationshipName>Subscription_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <description>Subscription Orders will not be rolled up to the utility account subscription until they are marked as approved. Once approved, they cannot be changed.</description>
        <inlineHelpText>Subscription Orders will not be rolled up to the utility account subscription until they are marked as approved. Once approved, they cannot be changed.</inlineHelpText>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Client_Assignment_Agreement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Assignment Agreement contract, populated when the Assignment Agreement on the corresponding Opportunity (or Opportunity&apos;s Contract) is populated or changed</inlineHelpText>
        <label>Client Assignment Agreement</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Subscription Orders</relationshipLabel>
        <relationshipName>Subscription_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date_Enacted_By_Utility__c</fullName>
        <formula>IF(
NOT(ISBLANK(Allocation_Schedule_Subscription__r.Schedule_Z__r.Date_Enacted_by_Utility__c)),
Allocation_Schedule_Subscription__r.Schedule_Z__r.Date_Enacted_by_Utility__c,
Utility_Account_Subscription__r.Date_Removed_from_Project__c
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Date Enacted By Utility</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>New_Annual_Cost__c</fullName>
        <inlineHelpText>This is the new annual cost that the UAS will have once the SO is effective.</inlineHelpText>
        <label>New Annual Cost</label>
        <precision>16</precision>
        <scale>6</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>New_Annual_kWh__c</fullName>
        <inlineHelpText>This is the new annual kwh that the UAS will have once this SO is effective.</inlineHelpText>
        <label>New Annual kWh</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Previous_Annual_Cost__c</fullName>
        <description>This is the Annual Cost on the UAS at the time the subscription order was created</description>
        <inlineHelpText>This is the Annual Cost on the UAS at the time the subscription order was created</inlineHelpText>
        <label>Previous Annual Cost</label>
        <precision>16</precision>
        <scale>6</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Previous_Annual_kwh__c</fullName>
        <description>This is the Annual kwh on the related UAS when the Subscription Order was created.</description>
        <inlineHelpText>This is the Annual kwh on the related UAS when the Subscription Order was created.</inlineHelpText>
        <label>Previous Annual kwh</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Previous_Percent_Share_of_System__c</fullName>
        <description>This is the Percent Share of System that was on the related UAS at the time the Subscription Order was created.</description>
        <inlineHelpText>This is the Percent Share of System that was on the related UAS at the time the Subscription Order was created.</inlineHelpText>
        <label>Previous Percent Share of System</label>
        <precision>18</precision>
        <scale>5</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Previous_kw_DC_Subscription__c</fullName>
        <description>This is the kw dc subscription on the related UAS at the time to subscription order was created.</description>
        <label>Previous kw DC Subscription</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Subscription Orders</relationshipLabel>
        <relationshipName>Subscription_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>System_Change_Percent_Share_of_System__c</fullName>
        <formula>ROUND(   System_Change_kW_DC_Subscription__c / Total_System_Size_kW_DC__c , Utility_Number_of_Decimal_Places__c + 2)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>New Percent Share of System</label>
        <precision>18</precision>
        <scale>5</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>System_Change_kW_DC_Rounded__c</fullName>
        <formula>System_Change_Percent_Share_of_System__c  * Total_System_Size_kW_DC__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>This uses the System Change Percent Share of System multiplied by the Total System Size in kW DC to find the kw DC Subscription value.</inlineHelpText>
        <label>New kW DC (Rounded)</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>System_Change_kW_DC_Subscription__c</fullName>
        <description>March 2021: Lucy and Peter suggest something like this:
CASE(Product__r.Customer_Subscription_Type__c,
     &apos;kWh&apos;, 
     (New_Annual_kWh__c*BLANKVALUE(Size_Ratio__c,1))/ Expected_Yield_kWh_kW__c,
     &apos;Annual Cost ($)&apos;, 
     New_Annual_Cost__c / BLANKVALUE(Value_of_NMC__c,1)/Expected_Yield_kWh_kW__c,
     &apos;&apos;
     )
There are historical records that would change (maybe for the better) because of a null Size Ratio that we should consider when making this change</description>
        <formula>IF(

TEXT( Product__r.Customer_Subscription_Type__c )=&apos;kWh&apos;,

IF(
AND(
$CustomMetadata.Custom_Feature_Enablement__mdt.Sizing_Method.Feature_is_Enabled__c = true,
NOT(ISBLANK(Utility_Account_Subscription__r.Sizing_Method__c))
),
(New_Annual_kWh__c*Size_Ratio__c)/ Expected_Yield_kWh_kW__c,
New_Annual_kWh__c / Expected_Yield_kWh_kW__c
) ,

IF( Utility_Account_Subscription__r.UAS_Number__c &gt; 1 ,

New_Annual_Cost__c / Value_of_NMC__c / Expected_Yield_kWh_kW__c,

IF(

OR( Utility_Account_Subscription__r.Auto_Unround__c = TRUE , Utility_Account_Subscription__r.UAS_Number__c = 1),
New_Annual_Cost__c / Value_of_NMC__c/Expected_Yield_kWh_kW__c,


IF(

OR(Utility_Account_Subscription__r.UAS_Number__c=1, Utility_Account_Subscription__r.Shared_Solar_System__r.Name = &apos;Fairhaven Mill Rd&apos;,

Utility_Account_Subscription__r.Shared_Solar_System__r.Name= &apos;Oxford Clara Barton&apos;),

Round(( New_Annual_Cost__c / Value_of_NMC__c/Expected_Yield_kWh_kW__c) * 4, 0)/4,0))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>New kW DC Subscription</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_System_Size_kW_DC__c</fullName>
        <description>This is the Total System Size kW DC on the related shared solar system at the time the subscription order was created.</description>
        <inlineHelpText>This is the Total System Size kW DC on the related shared solar system at the time the subscription order was created.</inlineHelpText>
        <label>Total System Size kW DC</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Utility_Account_Subscription__c</fullName>
        <label>Utility Account Subscription</label>
        <referenceTo>Utility_Account_Subscription__c</referenceTo>
        <relationshipLabel>Subscription Orders</relationshipLabel>
        <relationshipName>Subscription_Orders</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Utility_Number_of_Decimal_Places__c</fullName>
        <description>This is the number of decimal places on the related utility record. It is static, and stamped at record creation. We need it in case the decimal places on Utility ever changes.</description>
        <inlineHelpText>This is the number of decimal places on the related utility record. It is static, and stamped at record creation.</inlineHelpText>
        <label>Utility: Number of Decimal Places</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Subscription Order</label>
    <nameField>
        <displayFormat>SO-{00000}</displayFormat>
        <label>Subscription Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscription Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Utility_Account_Subscription__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Utility Account Subscriptions</relationshipLabel>
        <relationshipName>Utility_Account_Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Utility Account Subscription</label>
    <nameField>
        <label>Utility Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Account Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SubscriptionOrderSelector.cls
/**
 * Created by SarahRenfro on 2/11/2020.
 *
 * Tested By: SubscriptionManagementServiceTestclass, SubscriptionOrderSelectorTest
 */
@SuppressWarnings('PMD.ApexCRUDViolation')
public inherited sharing class SubscriptionOrderSelector {
    public List<Subscription_Order__c> selectByIds(Set<Id> soIds) {
        return [
            SELECT Id,
                Name,
                New_Annual_Cost__c,
                New_Annual_kWh__c,
                Previous_Annual_Cost__c,
                Previous_Annual_kwh__c,
                Previous_Percent_Share_of_System__c,
                Previous_kw_DC_Subscription__c,
                Product__r.Customer_Subscription_Type__c,
                System_Change_Percent_Share_of_System__c,
                System_Change_kW_DC_Subscription__c,
                System_Change_kW_DC_Rounded__c,
                Total_System_Size_kW_DC__c,
                Utility_Number_of_Decimal_Places__c
            FROM Subscription_Order__c
            WHERE Id IN :soIds
        ];
    }

    public List<Subscription_Order__c> selectUnenactedByUASId(Set<Id> uasIds) {
        return [
            SELECT Id, Name,
                Utility_Account_Subscription__c,
                Allocation_Schedule_Subscription__c
            FROM Subscription_Order__c
            WHERE Utility_Account_Subscription__c IN : uasIds
            AND Date_Enacted_By_Utility__c = null
        ];
    }

    public List<Subscription_Order__c> selectApprovedByOppIds(Set<Id> oppIds) {
        return [
            SELECT Id, Client_Assignment_Agreement__c, Utility_Account_Subscription__r.Opportunity__c
            FROM Subscription_Order__c
            WHERE Utility_Account_Subscription__r.Opportunity__c IN :oppIds
            AND Approval_Status__c = 'Approved'
        ];
    }

    public List<Subscription_Order__c> selectApprovedByContractIds(Set<Id> contractIds) {
        return [
            SELECT Id, Client_Assignment_Agreement__c, Utility_Account_Subscription__r.Opportunity__r.ContractId
            FROM Subscription_Order__c
            WHERE Utility_Account_Subscription__r.Opportunity__r.ContractId IN :contractIds
            AND Approval_Status__c = 'Approved'
        ];
    }
}