src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Shared_Solar_System__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>To change this system, use the Change SSS quick action</inlineHelpText>
        <label>Shared Solar System</label>
        <referenceTo>Shared_Solar_System__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Utility__c</fullName>
        <formula>IF( 


right(TEXT( Load_Zone_Utility_4__c  ),5) = &apos;SCE&amp;G&apos;,

right(TEXT( Load_Zone_Utility_4__c  ),5),

IF( 


right(TEXT( Load_Zone_Utility_4__c  ),10) = &apos;Eversource&apos;,

right(TEXT( Load_Zone_Utility_4__c  ),10),

IF(

right(TEXT( Load_Zone_Utility_4__c  ),13) = &apos;National Grid&apos;,


right(TEXT( Load_Zone_Utility_4__c  ),13),

IF(

right(TEXT( Load_Zone_Utility_4__c  ),6) = &apos;Unitil&apos;,


right(TEXT( Load_Zone_Utility_4__c  ),6),

IF(

right(TEXT( Load_Zone_Utility_4__c  ),29) = &apos;Municipal Electric Department&apos;,


right(TEXT( Load_Zone_Utility_4__c  ),29),

IF(

TEXT( Load_Zone_Utility_4__c  ) = &apos;Manual Lookup Required&apos;,

&apos;Manual Lookup Required&apos;, null))))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Utility (OLD)</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Schedule_Z__c.object
<CustomObject>
    <fields>
        <fullName>Shared_Solar_System__c</fullName>
        <label>Shared Solar System</label>
        <referenceTo>Shared_Solar_System__c</referenceTo>
        <relationshipName>Schedule_Zs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Utility__c</fullName>
        <formula>Shared_Solar_System__r.Utility__r.Name</formula>
        <label>Utility</label>
        <type>Text</type>
    </fields>
    <label>Allocation Schedule</label>
    <nameField>
        <label>Allocation Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Allocation Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Schedule_Z_Subscription__c.object
<CustomObject>
    <fields>
        <fullName>Customer_Subscription_kW_DC__c</fullName>
        <inlineHelpText>The size of the UAS at the time of Allocation Schedule filing</inlineHelpText>
        <label>Customer Subscription kW DC</label>
        <precision>9</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Decimal_Places__c</fullName>
        <defaultValue>4</defaultValue>
        <inlineHelpText>The number of decimal places listed on the Allocation Schedule at the time of Allocation Schedule filing</inlineHelpText>
        <label>Number of Decimal Places</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Schedule_Z__c</fullName>
        <label>Allocation Schedule</label>
        <referenceTo>Schedule_Z__c</referenceTo>
        <relationshipName>Schedule_Z_Subscriptions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>System_Size_kW_DC__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>The size of the solar system at the time of Allocation Schedule filing</inlineHelpText>
        <label>System Size (kW DC)</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Utility_Account_Subscription__c</fullName>
        <label>Utility Account Subscription</label>
        <referenceTo>Utility_Account_Subscription__c</referenceTo>
        <relationshipName>Schedule_Z_Subscriptions</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Allocation Schedule Subscription</label>
    <nameField>
        <displayFormat>ALSS-{0000}</displayFormat>
        <label>Allocation Schedule Subscription Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Allocation Schedule Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Shared_Solar_System__c.object
<CustomObject
     >
    <articleTypeChannelDisplay n1:nil="true" />
    <customSettingsType n1:nil="true" />
    <description n1:nil="true" />
    <eventType n1:nil="true" />
    <fields>
        <fullName>Utility__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Utility</label>
        <referenceTo>Utility__c</referenceTo>
        <relationshipLabel>Shared Solar Systems</relationshipLabel>
        <relationshipName>Shared_Solar_Systems</relationshipName>
        <type>Lookup</type>
    </fields>
    <gender n1:nil="true" />
    <household>false</household>
    <label>Shared Solar System</label>
    <nameField>
        <label>Shared Solar System Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shared Solar Systems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <startsWith n1:nil="true" />
</CustomObject>

src/objects/Utility__c.object
<CustomObject>
    <fields>
        <fullName>Number_of_Decimal_Places__c</fullName>
        <inlineHelpText>Used for calculating kW subscriptions for SOs</inlineHelpText>
        <label>Number of Decimal Places</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Utility</label>
    <nameField>
        <label>Utility Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Utility_Account_Subscription__c.object
<CustomObject>
    <fields>
        <fullName>Customer_Subscription_KW_DC_STATIC__c</fullName>
        <description>Customer Subscription value at point of sale. This field is not dynamic and is populated based on a workflow.</description>
        <inlineHelpText>Used for billing. Populated when Opportunity Stage Name is Pending BW Signature through a process builder. Once the Opp stage is set to Complete the Opp then aggregates this instead of the dynamic.</inlineHelpText>
        <label>XXCurrent Customer Subscription (kW DC)</label>
        <precision>9</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Customer_Subscription_KW_DC__c</fullName>
        <description>Made the system name logic so that Allocation Schedule customers will not change to unrounded values</description>
        <formula>IF(

$CustomMetadata.Custom_Feature_Enablement__mdt.Subscription_Orders.Feature_is_Enabled__c=true
,
Future_Customer_Subscription_KWDC_Rollup__c
,

IF(AND(TEXT(Opportunity__r.Product__r.Customer_Subscription_Type__c)=&apos;kWh&apos;,Annual_kwh_subscription_future__c&gt;0),Annual_kwh_subscription_future__c/Opportunity__r.Shared_Solar_System__r.Expected_Yield_kWh_kW__c, 
IF( UAS_Number__c &gt; 1 , 

Subscribed_Annual_Cost_of_Electricity__c / Opportunity__r.NMC_Value__c / Opportunity__r.Shared_Solar_System__r.Expected_Yield_kWh_kW__c, 

IF( 

OR(Auto_Unround__c = TRUE , AND(UAS_Number__c = 1 , calculated_annual_cost_of_electricity__c != Subscribed_Annual_Cost_of_Electricity__c )), 

Subscribed_Annual_Cost_of_Electricity__c / Opportunity__r.NMC_Value__c/ Opportunity__r.Shared_Solar_System__r.Expected_Yield_kWh_kW__c, 


IF( 

OR(AND(UAS_Number__c = 1 , calculated_annual_cost_of_electricity__c = Subscribed_Annual_Cost_of_Electricity__c ), Opportunity__r.Shared_Solar_System_Name__c = &apos;Fairhaven Mill Rd&apos;, Opportunity__r.Shared_Solar_System_Name__c = &apos;Oxford Clara Barton&apos;), 

Round(( Subscribed_Annual_Cost_of_Electricity__c / Opportunity__r.NMC_Value__c/ Opportunity__r.Shared_Solar_System__r.Expected_Yield_kWh_kW__c) * 4, 0)/4,0))))
)</formula>
        <inlineHelpText>Dynamic Subscription</inlineHelpText>
        <label>Future Customer Subscription (KW DC)</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Next_Schedule_Z_Status__c</fullName>
        <defaultValue>&quot;Active Subscription&quot;</defaultValue>
        <inlineHelpText>Controls whether this subscription should be added to future Allocation Schedules. Select &apos;Active Subscription&apos; to include it, or &apos;Inactive Subscription&apos; to exclude it.</inlineHelpText>
        <label>Next Allocation Schedule Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active Subscription</fullName>
                    <default>true</default>
                    <label>Active Subscription</label>
                </value>
                <value>
                    <fullName>Inactive Subscription</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity_Stage__c</fullName>
        <formula>Text(Opportunity__r.StageName)</formula>
        <label>Opportunity Stage</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Utility Account Subscriptions</relationshipLabel>
        <relationshipName>Utility_Account_Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shared_Solar_System__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the SSS on the Opportunity when the UAS was created. The SSS on an existing UAS should never be changed.</description>
        <inlineHelpText>This is the SSS on the Opportunity when the UAS was created. The SSS on an existing UAS should never be changed.</inlineHelpText>
        <label>Shared Solar System</label>
        <referenceTo>Shared_Solar_System__c</referenceTo>
        <relationshipLabel>Utility Account Subscriptions</relationshipLabel>
        <relationshipName>Utility_Account_Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Utility__c</fullName>
        <formula>Opportunity__r.UtilityMapper__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Utility</label>
        <type>Text</type>
    </fields>
    <label>Utility Account Subscription</label>
    <nameField>
        <label>Utility Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Account Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ScheduleZTriggerHandler.cls
/**
 * Created by mstackhouse on 5/15/2018.
 *
 * When a schedule Z is created this class creates subscriptions from a customer's UAS.
 *
 *
 * Tested by: ScheduleZTriggerHandlerTest
 */

public with sharing class ScheduleZTriggerHandler {
    public static void createSubscriptions(List<Schedule_Z__c> scheduleZList) {
        Set<Id> scheduleZIds = new Set<Id>();
        Set<Id> sssList = new Set<Id>();
        for (Schedule_Z__c scheduleZ : scheduleZList) {
            sssList.add(scheduleZ.Shared_Solar_System__c);
            scheduleZIds.add(scheduleZ.Id);
        }

        List<Utility_Account_Subscription__c> accountSubscriptions = [
            SELECT Id, Customer_Subscription_KW_DC__c, Opportunity__r.Shared_Solar_System__c,
                Customer_Subscription_KW_DC_STATIC__c
            FROM Utility_Account_Subscription__c
            WHERE Opportunity__r.Shared_Solar_System__c IN : sssList
            AND Next_Schedule_Z_Status__c = 'Active Subscription'
            AND Opportunity_Stage__c = 'Complete'
        ];

        List<Schedule_Z__c> scheduleZListWithSystemSize = [
            SELECT Id, Shared_Solar_System__r.Total_System_Size_kW_DC_QC__c,
                Shared_Solar_System__r.Utility__r.Number_of_Decimal_Places__c
            FROM Schedule_Z__c
            WHERE Id IN : scheduleZIds
        ];

        List<Schedule_Z_Subscription__c> scheduleZSubscriptions = new List<Schedule_Z_Subscription__c>();

        for (Schedule_Z__c scheduleZ : scheduleZListWithSystemSize) {
            for (Utility_Account_Subscription__c uas : accountSubscriptions) {
                if (scheduleZ.Shared_Solar_System__c == uas.Opportunity__r.Shared_Solar_System__c) {
                    Decimal customerSubscriptionkWh;
                    if (uas.Customer_Subscription_KW_DC__c == null) {
                        customerSubscriptionkWh = uas.Customer_Subscription_KW_DC_STATIC__c;
                    } else {
                        customerSubscriptionkWh = uas.Customer_Subscription_KW_DC__c;
                    }
                    Schedule_Z_Subscription__c newSubscription = new Schedule_Z_Subscription__c(
                        Customer_Subscription_kW_DC__c = customerSubscriptionkWh,
                        Utility_Account_Subscription__c = uas.Id,
                        Schedule_Z__c = scheduleZ.Id,
                        Number_of_Decimal_Places__c = scheduleZ.Shared_Solar_System__r.Utility__r.Number_of_Decimal_Places__c,
                        System_Size_kW_DC__c = scheduleZ.Shared_Solar_System__r.Total_System_Size_kW_DC_QC__c
                    );
                    scheduleZSubscriptions.add(newSubscription);
                }
            }
        }

        insert scheduleZSubscriptions;
    }
}