src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>NMC_Tariff__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>NMC Tariff</label>
        <referenceTo>Utility_NMC_Tariff__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shared_Solar_System__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>To change this system, use the Change SSS quick action</inlineHelpText>
        <label>Shared Solar System</label>
        <referenceTo>Shared_Solar_System__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Utility__c</fullName>
        <formula>IF( 


right(TEXT( Load_Zone_Utility_4__c  ),5) = &apos;SCE&amp;G&apos;,

right(TEXT( Load_Zone_Utility_4__c  ),5),

IF( 


right(TEXT( Load_Zone_Utility_4__c  ),10) = &apos;Eversource&apos;,

right(TEXT( Load_Zone_Utility_4__c  ),10),

IF(

right(TEXT( Load_Zone_Utility_4__c  ),13) = &apos;National Grid&apos;,


right(TEXT( Load_Zone_Utility_4__c  ),13),

IF(

right(TEXT( Load_Zone_Utility_4__c  ),6) = &apos;Unitil&apos;,


right(TEXT( Load_Zone_Utility_4__c  ),6),

IF(

right(TEXT( Load_Zone_Utility_4__c  ),29) = &apos;Municipal Electric Department&apos;,


right(TEXT( Load_Zone_Utility_4__c  ),29),

IF(

TEXT( Load_Zone_Utility_4__c  ) = &apos;Manual Lookup Required&apos;,

&apos;Manual Lookup Required&apos;, null))))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Utility (OLD)</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Shared_Solar_System__c.object
<CustomObject
     >
    <articleTypeChannelDisplay n1:nil="true" />
    <customSettingsType n1:nil="true" />
    <description n1:nil="true" />
    <eventType n1:nil="true" />
    <fields>
        <fullName>Client_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The client account field designates that party in which this shared solar system is being serviced for.</description>
        <inlineHelpText>The client account field designates that party in which this shared solar system is being serviced for.</inlineHelpText>
        <label>Client Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Shared Solar Systems</relationshipLabel>
        <relationshipName>Shared_Solar_Systems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Expected_Yield_kWh_kW__c</fullName>
        <inlineHelpText>How much energy (kWh) is produced for every kW of project capacity. If yield increases, every kW of the project will produce more energy, and need more CS offtakers to use that capacity</inlineHelpText>
        <label>Expected Yield (kWh/kW)</label>
        <precision>12</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Primary customer product.</inlineHelpText>
        <label>Default Enrollment Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Shared Solar Systems</relationshipLabel>
        <relationshipName>Shared_Solar_Systems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total_System_Size_kWh_DC__c</fullName>
        <inlineHelpText>Total system size in kW DC.</inlineHelpText>
        <label>Total System Size (kW DC)</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Utility_NMC_Tariff__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sizing Method</label>
        <referenceTo>Utility_NMC_Tariff__c</referenceTo>
        <relationshipLabel>Shared Solar Systems</relationshipLabel>
        <relationshipName>Shared_Solar_Systems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Utility__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Utility</label>
        <referenceTo>Utility__c</referenceTo>
        <relationshipLabel>Shared Solar Systems</relationshipLabel>
        <relationshipName>Shared_Solar_Systems</relationshipName>
        <type>Lookup</type>
    </fields>
    <gender n1:nil="true" />
    <household>false</household>
    <label>Shared Solar System</label>
    <nameField>
        <label>Shared Solar System Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shared Solar Systems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <startsWith n1:nil="true" />
</CustomObject>

src/objects/Shared_Solar_System_Order__c.object
<CustomObject>
    <fields>
        <fullName>Shared_Solar_System__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The SSS record that the order is for.</description>
        <inlineHelpText>This is the Shared Solar System that will be updated once the order is approved.</inlineHelpText>
        <label>Shared Solar System</label>
        <referenceTo>Shared_Solar_System__c</referenceTo>
        <relationshipLabel>Shared Solar System Orders</relationshipLabel>
        <relationshipName>Shared_Solar_System_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total_System_Size_kW_DC__c</fullName>
        <inlineHelpText>This will be the new value of the kW DC System Size field on the related Shared Solar System once the order is approved.</inlineHelpText>
        <label>Total System Size (kW DC)</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Shared Solar System Order</label>
    <nameField>
        <displayFormat>SSSO-{00000}</displayFormat>
        <label>Shared Solar System Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shared Solar System Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Subscription_Order__c.object
<CustomObject>
    <fields>
        <fullName>Client_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>This is the Client Account that was on the related Shared Solar System at the time the Subscription Order was created.</description>
        <inlineHelpText>This is the Client Account that was on the related Shared Solar System at the time the Subscription Order was created.</inlineHelpText>
        <label>Client Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscription Orders</relationshipLabel>
        <relationshipName>Subscription_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Expected_Yield_kWh_kW__c</fullName>
        <description>This is the Expected Yield (kWh/kW) from the related shared solar system at the time the subscription order was created.</description>
        <inlineHelpText>This is the Expected Yield (kWh/kW) from the related shared solar system at the time the subscription order was created.</inlineHelpText>
        <label>Expected Yield (kWh/kW)</label>
        <precision>12</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Subscription Orders</relationshipLabel>
        <relationshipName>Subscription_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shared_Solar_System_Order__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>This is the related Shared Solar System Order that the Subscription Order was created from.</inlineHelpText>
        <label>Shared Solar System Order</label>
        <referenceTo>Shared_Solar_System_Order__c</referenceTo>
        <relationshipLabel>Subscription Orders</relationshipLabel>
        <relationshipName>Subscription_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total_System_Size_kW_DC__c</fullName>
        <description>This is the Total System Size kW DC on the related shared solar system at the time the subscription order was created.</description>
        <inlineHelpText>This is the Total System Size kW DC on the related shared solar system at the time the subscription order was created.</inlineHelpText>
        <label>Total System Size kW DC</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Utility_Account_Subscription__c</fullName>
        <label>Utility Account Subscription</label>
        <referenceTo>Utility_Account_Subscription__c</referenceTo>
        <relationshipLabel>Subscription Orders</relationshipLabel>
        <relationshipName>Subscription_Orders</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Utility_NMC_Tariff__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>This is the Sizing Method used to calculate the Subscription at the time this record was created.</description>
        <inlineHelpText>This is the Sizing Method used to calculate the Subscription at the time this record was created.</inlineHelpText>
        <label>Sizing Method</label>
        <referenceTo>Utility_NMC_Tariff__c</referenceTo>
        <relationshipLabel>Subscription Orders</relationshipLabel>
        <relationshipName>Subscription_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Utility_Number_of_Decimal_Places__c</fullName>
        <description>This is the number of decimal places on the related utility record. It is static, and stamped at record creation. We need it in case the decimal places on Utility ever changes.</description>
        <inlineHelpText>This is the number of decimal places on the related utility record. It is static, and stamped at record creation.</inlineHelpText>
        <label>Utility: Number of Decimal Places</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Value_of_NMC__c</fullName>
        <description>This is the Value of NMC that was on the related NMC Tariff at the time the subscription order was created.</description>
        <inlineHelpText>This is the Value of NMC that was on the related NMC Tariff at the time the subscription order was created.</inlineHelpText>
        <label>Value of NMC</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Currency</type>
    </fields>
    <label>Subscription Order</label>
    <nameField>
        <displayFormat>SO-{00000}</displayFormat>
        <label>Subscription Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscription Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Utility__c.object
<CustomObject>
    <fields>
        <fullName>Number_of_Decimal_Places__c</fullName>
        <inlineHelpText>Used for calculating kW subscriptions for SOs</inlineHelpText>
        <label>Number of Decimal Places</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Utility</label>
    <nameField>
        <label>Utility Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Utility_Account_Subscription__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Utility Account Subscriptions</relationshipLabel>
        <relationshipName>Utility_Account_Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shared_Solar_System__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the SSS on the Opportunity when the UAS was created. The SSS on an existing UAS should never be changed.</description>
        <inlineHelpText>This is the SSS on the Opportunity when the UAS was created. The SSS on an existing UAS should never be changed.</inlineHelpText>
        <label>Shared Solar System</label>
        <referenceTo>Shared_Solar_System__c</referenceTo>
        <relationshipLabel>Utility Account Subscriptions</relationshipLabel>
        <relationshipName>Utility_Account_Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Utility__c</fullName>
        <formula>Opportunity__r.UtilityMapper__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Utility</label>
        <type>Text</type>
    </fields>
    <label>Utility Account Subscription</label>
    <nameField>
        <label>Utility Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Account Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Utility_NMC_Tariff__c.object
<CustomObject>
    <fields>
        <fullName>Utility__c</fullName>
        <label>Utility</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value_of_NMC__c</fullName>
        <formula>Value_of_Net_Metering_Credit__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Value of NMC</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Currency</type>
    </fields>
    <label>Sizing Method</label>
    <nameField>
        <label>Utility and Class</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sizing Methods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SubscriptionManagementService.cls
/**
 * Created by SarahRenfro on 11/15/2019.
 *
 * Description: Used to create/update/insert Subscription Orders and Shared Solar System Orders
 *
 * Tested By: SubscriptionManagementServiceTest
 */

public without sharing class SubscriptionManagementService {
    @TestVisible
    private static UASSelector uasSelector = new UASSelector();
    @TestVisible
    private static SharedSolarSystemsSelector sssSelector = new SharedSolarSystemsSelector();

    public void populateSubscriptionOrder(List<Subscription_Order__c> soList) {
        Set<Id> uasIds = new Set<Id>();
        for (Subscription_Order__c so : soList) {
            uasIds.add(so.Utility_Account_Subscription__c);
        }
        
        Map<Id, Utility_Account_Subscription__c> uasMap = uasSelector.getUASMap(uasIds);

        for (Subscription_Order__c so : soList) {
            Utility_Account_Subscription__c uas = uasMap.get(so.Utility_Account_Subscription__c);
            so.Client_Account__c = uas.Shared_Solar_System__r.Client_Account__c;
            so.Expected_Yield_kWh_kW__c = uas.Shared_Solar_System__r.Expected_Yield_kWh_kW__c;
            so.Total_System_Size_kW_DC__c = uas.Shared_Solar_System__r.Total_System_Size_kWh_DC__c;
            so.Utility_Number_of_Decimal_Places__c = uas.Shared_Solar_System__r.Utility__r.Number_of_Decimal_Places__c;
            so.Utility_NMC_Tariff__c = uas.Opportunity__r.NMC_Tariff__c;
            so.Value_of_NMC__c = uas.Opportunity__r.NMC_Tariff__r.Value_of_NMC__c;
            so.Product__c = uas.Opportunity__r.Product__c;
        }
    }

    @SuppressWarnings('PMD.ApexCRUDViolation')
    public void handleSystemOrderChange(List<Shared_Solar_System_Order__c> sssoList, Map<Id, Shared_Solar_System_Order__c> oldMap) {
        List<Shared_Solar_System__c> sssToUpdate = new List<Shared_Solar_System__c>();
            List<Subscription_Order__c> soListToInsert = new List<Subscription_Order__c>();
            for(Shared_Solar_System_Order__c ssso : sssoList) {
            if (ssso.Approval_Status__c == 'Approved' && oldMap.get(ssso.Id).Approval_Status__c != 'Approved') {
                Shared_Solar_System__c sss = updateSSSFromSSSO(ssso);
                sssToUpdate.add(sss);
                List<Subscription_Order__c> soList = createSubscriptionOrdersFromSSSO(ssso);
                soListToInsert.addAll(soList);
            }
        }

        update sssToUpdate;
        insert soListToInsert;
    }

    public Shared_Solar_System__c updateSSSFromSSSO(Shared_Solar_System_Order__c ssso) {
        Shared_Solar_System__c sssToUpdate = sssSelector.selectOne(ssso.Shared_Solar_System__c);
        sssToUpdate.Apex_Context__c = true;
        if (ssso.Total_System_Size_kW_DC__c != null && (ssso.Total_System_Size_kW_DC__c != sssToUpdate.Total_System_Size_kWh_DC__c)) {
            sssToUpdate.Total_System_Size_kWh_DC__c = ssso.Total_System_Size_kW_DC__c;
        }

        if (ssso.Yield__c != null && (ssso.Yield__c != sssToUpdate.Expected_Yield_kWh_kW__c)) {
            sssToUpdate.Expected_Yield_kWh_kW__c = ssso.Yield__c;
        }

        return sssToUpdate;
    }

    public List<Subscription_Order__c> createSubscriptionOrdersFromSSSO(Shared_Solar_System_Order__c ssso) {
        List<Utility_Account_Subscription__c> uasList = uasSelector.selectBySharedSolarSystem(ssso.Shared_Solar_System__c);
        Id systemChangeOrder = Schema.SObjectType.Subscription_Order__c.getRecordTypeInfosByName().get('System Change Order').getRecordTypeId();
        List<Subscription_Order__c> soList = new List<Subscription_Order__c>();

        for (Utility_Account_Subscription__c uas : uasList) {
            Subscription_Order__c so = new Subscription_Order__c(
                RecordTypeId = systemChangeOrder,
                Type__c = 'Shared Solar System Update',
                Shared_Solar_System_Order__c = ssso.Id,
                Utility_Account_Subscription__c = uas.Id,
                Approval_Status__c = 'Approved',
                Effective_Date__c = System.now(),
                Previous_Annual_Cost__c = uas.Annual_Cost_Future_Rollup__c,
                Previous_Annual_kwh__c = uas.Annual_kWh_Subscription_Future_Rollup__c,
                Previous_kw_DC_Subscription__c = uas.Future_Customer_Subscription_KWDC_Rollup__c,
                Previous_Percent_Share_of_System__c = uas.Future_Share_of_System_Rollup__c,
                Change_in_Annual_Cost__c = 0,
                Change_in_Annual_kWh__c = 0
            );
            soList.add(so);
        }

        return soList;
    }

}