src/objects/Partner__c.object
<CustomObject>
    <label>Partner</label>
    <nameField>
        <label>Partner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partners</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Partner_Alert__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This checkbox allows the operator to turn alerts on/off on the partner portal.</description>
        <inlineHelpText>True - Visible on Partner Portal
False - Not Visible on Partner Portal</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <description>This is the date in which the alert was created</description>
        <inlineHelpText>Date of Creation</inlineHelpText>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Importance__c</fullName>
        <description>This allows for the user to signify the level of importance of this alert. It determines the color and location of the alert on the portal. Alerts labeled as 1 go front and center on the dashboard in a bright red text and pop-up upon login. Level 2 alerts are placed at the top, however they are not in colored in red. Level 3 alerts are placed in the alerts tab of the portal, where the partner has to click into in order to view.</description>
        <inlineHelpText>1 - Urgent
2 - Important
3 - Standard</inlineHelpText>
        <label>Importance</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Partner Alert</label>
    <nameField>
        <label>Subject</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner Alerts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Partner_Alert_Filter__c.object
<CustomObject>
    <description>This object allows the partner alerts to be designated to specific partners</description>
    <fields>
        <fullName>Acknowledged__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field allows the portal user to close out the alert and therefore not have it pop up again on their feed.</description>
        <inlineHelpText>If this is checked, it means that the use has acknowledged this information in the alert.</inlineHelpText>
        <label>Acknowledged</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Partner_Alert__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the relationship to the Partner Alert object</description>
        <label>Partner Alert</label>
        <referenceTo>Partner_Alert__c</referenceTo>
        <relationshipLabel>Partner Alert Filters</relationshipLabel>
        <relationshipName>Partner_Alert_Filters</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the relationship to the Partner Object</description>
        <inlineHelpText>Select which partner you&apos;d like to see this alert.</inlineHelpText>
        <label>Partner</label>
        <referenceTo>Partner__c</referenceTo>
        <relationshipLabel>Partner Alert Filters</relationshipLabel>
        <relationshipName>Partner_Alert_Filters</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Partner Alert Filter</label>
    <nameField>
        <label>Partner Alert Filter Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner Alert Filters</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/SLPAlertsHandler.cls
public without sharing class SLPAlertsHandler {
	@AuraEnabled 
	public static List<Partner_Alert__c> getPartnerAlerts (String partnerId) {
		System.debug('Begin the getPartnerAlerts method');
		List<Partner_Alert__c> alertList = new List<Partner_Alert__c>();
	    String partnerKey = SLPUserHelper.getpartnerId(); 
	    Partner__c partnerRecord;
	    if (partnerKey == null || partnerKey == '') {
	      partnerKey = SLPUserHelper.getBWCCId();
	    }

	 	for (Partner_Alert__c partnerAlert : [SELECT Id, Name, Body__c, Date__c, 
	 												(SELECT Id, Name, Acknowledged__c, Partner__r.Name 
	 												FROM Partner_Alert_Filters__r)
	 							  				FROM Partner_Alert__c
	 							  				WHERE Active__c = true
	 							  				ORDER BY Importance__c DESC, Date__c ASC]){
	 		for (Partner_Alert_Filter__c alertFilter : partnerAlert.Partner_Alert_Filters__r) {
	 			if(alertFilter.Partner__r.Id == partnerKey) {
	 				alertList.add(partnerAlert);
	 			}
	 		}
	 	}
	 	return alertList;   	    
	}

	@AuraEnabled 
	public static Partner_Alert__c getPartnerAlert (String alertId) {
		System.debug('Begin the getPartnerAlert method');
		List<Partner_Alert__c> alertList = new List<Partner_Alert__c>();
	 	Partner_Alert__c partnerAlert = [SELECT Id, Name, Body__c, Date__c
 							  				FROM Partner_Alert__c
 							  				WHERE Id = : alertId];	 	
	 	return partnerAlert;   	    
	}

}