src/objects/Partner_Shared_Solar_System_Eligibility__c.object
<CustomObject>
    <description>Control partner access to Shared Solar Systems</description>
    <fields>
        <fullName>Account__c</fullName>
        <inlineHelpText>Partner Account</inlineHelpText>
        <label>Partner Account</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The Account must have a record type of Partner Account</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Partner Account</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Shared Solar Systems</relationshipLabel>
        <relationshipName>Partner_Shared_Solar_System_Accesses</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <inlineHelpText>Date after which this record ceases to be active</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Shared_Solar_System__c</fullName>
        <inlineHelpText>Shared Solar System that the partner is eligible to sell</inlineHelpText>
        <label>Shared Solar System</label>
        <referenceTo>Shared_Solar_System__c</referenceTo>
        <relationshipLabel>Eligible Partners</relationshipLabel>
        <relationshipName>Partner_Shared_Solar_System_Accesses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <inlineHelpText>Date on which this record begins to be active</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Partner Shared Solar System Access</label>
    <nameField>
        <displayFormat>PSSA-{0000}</displayFormat>
        <label>Partner Shared Solar System Access Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Shared Solar System Accesses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Shared_Solar_System__c.object
<CustomObject
     >
    <articleTypeChannelDisplay n1:nil="true" />
    <customSettingsType n1:nil="true" />
    <description n1:nil="true" />
    <eventType n1:nil="true" />
    <gender n1:nil="true" />
    <household>false</household>
    <label>Shared Solar System</label>
    <nameField>
        <label>Shared Solar System Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shared Solar Systems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <startsWith n1:nil="true" />
</CustomObject>

src/classes/PartnerSSSEligibilities.cls
/**
 * Created by PeterYao on 2/27/2021.
 * Tested By: PartnerSSSEligibilitiesTest
 */

public without sharing class PartnerSSSEligibilities {
    private List<Partner_Shared_Solar_System_Eligibility__c> records;
    @TestVisible private static PartnerSSSEligibilitySelector partnerSSSEligibilitySelector = new PartnerSSSEligibilitySelector();

    public PartnerSSSEligibilities(List<Partner_Shared_Solar_System_Eligibility__c> partnerEligibilities) {
        this.records = partnerEligibilities;
    }

    /**
     * @description Ensures the records in this class are valid: that they have a start date, that the end date is after
     * the start, and that they do not overlap with any existing records for the same System and Account
     */
    public void validate() {
        List<Partner_Shared_Solar_System_Eligibility__c> existingEligibilities = getExistingEligibilities();
        for (Partner_Shared_Solar_System_Eligibility__c partnerEligibility : records) {
            validate(partnerEligibility, existingEligibilities);
        }
    }

    public void preventDeleteForPreviouslyActiveRecords() {
        for (Partner_Shared_Solar_System_Eligibility__c partnerEligibility : records) {
            if (partnerEligibility.Start_Date__c <= System.today()) {
                partnerEligibility.addError('You cannot delete ' + partnerEligibility.Id + ' which that started in the past');
            }
        }
    }

    private List<Partner_Shared_Solar_System_Eligibility__c> getExistingEligibilities() {
        Set<Id> partnerAccountIds = new Set<Id>();
        for (Partner_Shared_Solar_System_Eligibility__c partnerEligibility : records) {
            partnerAccountIds.add(partnerEligibility.Account__c);
        }
        return partnerSSSEligibilitySelector.getSSSByPartner(partnerAccountIds);
    }

    private void validate(Partner_Shared_Solar_System_Eligibility__c newEligibility,
        List<Partner_Shared_Solar_System_Eligibility__c> existingEligibilities) {
        if (newEligibility.Start_Date__c == null) {
            newEligibility.addError('The start date must be populated');
            return;
        }
        if (newEligibility.End_Date__c != null && newEligibility.End_Date__c < newEligibility.Start_Date__c) {
            newEligibility.addError('The end date should be after the start date');
            return;
        }
        for (Partner_Shared_Solar_System_Eligibility__c existingEligibility : existingEligibilities) {
            if (hasExisting(newEligibility, existingEligibility)) {
                newEligibility.addError('An existing Partner SSS Access ('+ existingEligibility.Id +') is active at the ' +
                    'same time this one would be. Please change the dates');
                return;
            }
        }
    }

    private static Boolean hasExisting(Partner_Shared_Solar_System_Eligibility__c newEligibility,
        Partner_Shared_Solar_System_Eligibility__c existingEligibility)
    {
        return newEligibility.Id != existingEligibility.Id &&
            newEligibility.Shared_Solar_System__c == existingEligibility.Shared_Solar_System__c &&
            newEligibility.Account__c == existingEligibility.Account__c &&
            DateUtil.overlapsDates(
                existingEligibility.Start_Date__c,
                existingEligibility.End_Date__c,
                newEligibility.Start_Date__c,
                newEligibility.End_Date__c
            );
    }

}