src/objects/Partner__c.object
<CustomObject>
    <fields>
        <fullName>Products__c</fullName>
        <label>Products</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Community Solar</fullName>
                </value>
                <value>
                    <fullName>Residential Loan</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Partner</label>
    <nameField>
        <label>Partner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partners</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Partner_Alert__c.object
<CustomObject>
    <label>Partner Alert</label>
    <nameField>
        <label>Subject</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner Alerts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Partner_Alert_Filter__c.object
<CustomObject>
    <description>This object allows the partner alerts to be designated to specific partners</description>
    <fields>
        <fullName>Partner_Alert__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the relationship to the Partner Alert object</description>
        <label>Partner Alert</label>
        <referenceTo>Partner_Alert__c</referenceTo>
        <relationshipLabel>Partner Alert Filters</relationshipLabel>
        <relationshipName>Partner_Alert_Filters</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the relationship to the Partner Object</description>
        <inlineHelpText>Select which partner you&apos;d like to see this alert.</inlineHelpText>
        <label>Partner</label>
        <referenceTo>Partner__c</referenceTo>
        <relationshipLabel>Partner Alert Filters</relationshipLabel>
        <relationshipName>Partner_Alert_Filters</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Partner Alert Filter</label>
    <nameField>
        <label>Partner Alert Filter Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner Alert Filters</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/PartnerAlertHandler.cls
public with sharing class PartnerAlertHandler {
    
    public void OnAfterInsert(Partner_Alert__c[] newPartnerAlerts){
        createPartnerAlertFilters(newPartnerAlerts);
    }

    public string createPartnerAlertFilters (Partner_Alert__c[] partnerAlerts){
        Date today = Date.today();
        List<Partner_Alert_Filter__c> partnerAlertFilterList = new List<Partner_Alert_Filter__c>();
        for (Partner__c partner : [SELECT Id, Name FROM Partner__c WHERE Products__c INCLUDES ('Residential Loan')]) {
            for (Partner_Alert__c partnerAlert : partnerAlerts) {
                Partner_Alert_Filter__c alertFilter = new Partner_Alert_Filter__c(
                Partner_Alert__c = partnerAlert.Id,
                Partner__c = partner.Id,
                Name = partner.name + ' - ' + partnerAlert.Name + ' - ' + today);
                partnerAlertFilterList.add(alertFilter);                
            }
        }    

//global with sharing class PartnerAlertHandler {
//    webservice static string PartnerAlertHandler (String partnerAlertId){
//    	Date today = Date.today();
//    	List<Partner_Alert_Filter__c> partnerAlertFilterList = new List<Partner_Alert_Filter__c>();
//    	for (Partner__c partner : [SELECT Id, Name FROM Partner__c WHERE Products__c INCLUDES ('Residential Loan')]) {
//    		Partner_Alert_Filter__c alertFilter = new Partner_Alert_Filter__c(
//    			Partner_Alert__c = partnerAlertId,
//    			Partner__c = partner.Id,
//    			Name = partner.name + ' - ' + partnerAlertId + ' - ' + today);
//    		partnerAlertFilterList.add(alertFilter);
//    	}
    	insert partnerAlertFilterList;
    	return 'Success';	
    }   
}