src/objects/Product_Escalation_Schedule__c.object
<CustomObject>
    <description>If the product values will change over time, use a schedule to time those updates</description>
    <label>Product Escalation Schedule</label>
    <nameField>
        <label>Product Escalation Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Escalation Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product_Escalator__c.object
<CustomObject>
    <fields>
        <fullName>New_NMC_Discount__c</fullName>
        <inlineHelpText>When escalator is active, this field will override the NMC Discount field on the Product</inlineHelpText>
        <label>New NMC Discount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>New_Solar_Electricity_Rate__c</fullName>
        <inlineHelpText>When escalator is active, this field will override the Solar Electricity Rate field on the Product</inlineHelpText>
        <label>New Solar Electricity Rate</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product_Escalation_Schedule__c</fullName>
        <label>Product Escalation Schedule</label>
        <referenceTo>Product_Escalation_Schedule__c</referenceTo>
        <relationshipLabel>Product Escalators</relationshipLabel>
        <relationshipName>Product_Escalators</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Product Escalator</label>
    <nameField>
        <displayFormat>PE-{00000}</displayFormat>
        <label>Product Escalator Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Escalators</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Escalator__c/fields/Starting_Credit_Transfer__c.field-meta.xml
<CustomField>
    <fullName>Starting_Credit_Transfer__c</fullName>
    <inlineHelpText>The number credit transfer at which this rate will be enacted. Credit transfer is defined by the number of non-zero NMC transfers on the production updates for a SSS</inlineHelpText>
    <label>Starting Credit Transfer</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/classes/ProductEscalatorSelector.cls
/**
 * Test: ProductEscalatorTest
*/


public without sharing class ProductEscalatorSelector {
    public static Map<Id, List<Product_Escalator__c>> getProductEscalationMap(){
        Map<Id, List<Product_Escalator__c>> escalatorMap = new Map<Id, List<Product_Escalator__c>>();
        for (Product_Escalation_Schedule__c productSchedule : [
            SELECT Id, (
                SELECT Id, Product_Escalation_Schedule__c, New_NMC_Discount__c,
                    New_Solar_Electricity_Rate__c, Starting_Credit_Transfer__c
                FROM Product_Escalators__r
                ORDER BY Starting_Credit_Transfer__c DESC
            )
            FROM Product_Escalation_Schedule__c
        ]) {
            escalatorMap.put(productSchedule.Id, productSchedule.Product_Escalators__r);
        }
        return escalatorMap;
    }
}