src/objects/Product_Escalator__c.object
<CustomObject>
    <fields>
        <fullName>New_Solar_Electricity_Rate__c</fullName>
        <inlineHelpText>When escalator is active, this field will override the Solar Electricity Rate field on the Product</inlineHelpText>
        <label>New Solar Electricity Rate</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Credit_Transfers__c</fullName>
        <inlineHelpText>The number credit transfer at which this rate will be enacted. Credit transfer is defined by the number of non-zero NMC transfers on the production updates for a SSS</inlineHelpText>
        <label>Number of Credit Transfers</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Product Escalator</label>
    <nameField>
        <displayFormat>PE-{00000}</displayFormat>
        <label>Product Escalator Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Escalators</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ProductServiceTest.cls
@isTest
public class ProductServiceTest {
    @isTest public static void testAMPEscalation() {
        List<Product_Escalator__c> oldAmpSchedule = ProductService.createEscalators(0.019, 0.1327, 20, 12);
        List<Product_Escalator__c> newAmpSchedule = ProductService.createEscalators(0.019, 0.1378, 20, 12);

        System.assertEquals(21, oldAmpSchedule.size());
        System.assertEquals(21, newAmpSchedule.size());

        System.assertEquals(0,oldAmpSchedule[0].Number_of_Credit_Transfers__c);
        System.assertEquals(0.1327,oldAmpSchedule[0].New_Solar_Electricity_Rate__c);

        System.assertEquals(120,oldAmpSchedule[10].Number_of_Credit_Transfers__c);
        System.assertEquals(120,newAmpSchedule[10].Number_of_Credit_Transfers__c);
        System.assertEquals(0.1602,oldAmpSchedule[10].New_Solar_Electricity_Rate__c);
        System.assertEquals(0.1663,newAmpSchedule[10].New_Solar_Electricity_Rate__c);

        System.assertEquals(240,newAmpSchedule[20].Number_of_Credit_Transfers__c);
        System.assertEquals(0.2007,newAmpSchedule[20].New_Solar_Electricity_Rate__c);
    }
}