src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Disclosure_Form_Conga_Template__c</fullName>
        <inlineHelpText>This is the ID of the Conga template used in SSF for the disclosure form for Contracts generated off of the Contract object.</inlineHelpText>
        <label>Disclosure Form Conga Template</label>
        <length>180</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Rate_Class__c.object
<CustomObject>
    <description>This object stores utility rate class information. It&apos;s different from NMC Tariffs.</description>
    <fields>
        <fullName>Suppress_Disclosure_Form__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Suppress Disclosure Form</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Utility__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The utility that the rate class is for.</description>
        <inlineHelpText>The utility that the rate class is for.</inlineHelpText>
        <label>Utility</label>
        <referenceTo>Utility__c</referenceTo>
        <relationshipLabel>Rate Classes</relationshipLabel>
        <relationshipName>Rate_Classes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Rate Class</label>
    <nameField>
        <label>Rate Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rate Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Shared_Solar_System__c.object
<CustomObject
     >
    <articleTypeChannelDisplay n1:nil="true" />
    <customSettingsType n1:nil="true" />
    <description n1:nil="true" />
    <eventType n1:nil="true" />
    <fields>
        <fullName>Available_SMB_Underwriting_Method_Docs__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Available SMB Underwriting Method: Docs</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Available_SMB_Underwriting_Method_FICO__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Used by the QualificationService for both SMB and Resi customers</inlineHelpText>
        <label>Available Underwriting Method: FICO</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Capacity_Available_to_be_Reserved__c</fullName>
        <formula>Total_CS_Capacity_kW_DC_Formula__c - (Pending_Small_CS_Capacity__c + Capacity_Committed_kW_DC__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Small CS Capacity not yet committed or pending; Result of Reserved Small CS Capacity - (Committed and Pending Small CS Capacity)</inlineHelpText>
        <label>Available Small CS Capacity</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Do_Not_Ask_for_Payment_Method__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Default unchecked; checked if the SSS does not require payment information (e.g. UCB product)</inlineHelpText>
        <label>Do Not Ask for Payment Method</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Do_Not_Underwrite__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Default unchecked; checked if the SSS does not require underwriting for applicants (e.g. UCB product)</description>
        <inlineHelpText>Default unchecked; checked if the SSS does not require underwriting for applicants (e.g. UCB product)</inlineHelpText>
        <label>Do Not Underwrite</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Utility__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Utility</label>
        <referenceTo>Utility__c</referenceTo>
        <relationshipLabel>Shared Solar Systems</relationshipLabel>
        <relationshipName>Shared_Solar_Systems</relationshipName>
        <type>Lookup</type>
    </fields>
    <gender n1:nil="true" />
    <household>false</household>
    <label>Shared Solar System</label>
    <nameField>
        <label>Shared Solar System Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shared Solar Systems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <startsWith n1:nil="true" />
</CustomObject>

force-app/main/default/objects/Shared_Solar_System__c/fields/Perch_Acq_Available_LMI_Capacity__c.field-meta.xml
<CustomField>
    <fullName>Perch_Acq_Available_LMI_Capacity__c</fullName>
    <formula>Perch_Acq_Reserved_LMI_Capacity__c - (Perch_Acq_Pending_LMI_Capacity__c + Perch_Acq_Committed_LMI_Capacity__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Perch acquired LMI Capacity not yet committed or pending; Result of Reserved LMI Capacity - (Committed and Pending LMI Capacity)</inlineHelpText>
    <label>Perch Acq Available LMI Capacity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

src/objects/Utility__c.object
<CustomObject>
    <fields>
        <fullName>POD_Id_Format__c</fullName>
        <inlineHelpText>The PoD Id format. Places groups of numbers in the desired format and uses regex capture groups as placeholders. Include prefix if applicable. Ex: for PoD Ids formatted XXX-XXX-XX the POD Id Format value is $1-$2-$3., for PoD Ids with the prefix R01 and formatted R01-XXX-XXX the POD Id Format value is R01-$1-$2.</inlineHelpText>
        <label>POD Id Format</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>POD_Id_Length__c</fullName>
        <inlineHelpText>Length of POD Ids. Ex: if POD Ids are written XXXX-XX-XX the length is 8. Prefixes are included in length. Ex: R01-XXXX-XXXX is length 11.</inlineHelpText>
        <label>POD Id Length</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>POD_Id_Prefix__c</fullName>
        <inlineHelpText>Used for automatically adding the POD Id prefix on forms.</inlineHelpText>
        <label>POD Id Prefix</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>POD_Id_Regex_Groups__c</fullName>
        <inlineHelpText>Regex for breaking utility account numbers into capture groups for formatting. Ex: to format a POD Id as XX-XXXX-XXXX-XXXX-X use the regex (\d{0,2})(\d{0,4})(\d{0,4})(\d{0,4})(\d?). Delimiters are captured in the POD Id Regex Delimiter field.</inlineHelpText>
        <label>POD Id Regex Groups</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Utility_Account_Number_Format__c</fullName>
        <inlineHelpText>The utility account number format. Places groups of numbers in the desired format and uses regex capture groups as placeholders. Include prefix if applicable. Ex: for UANs formatted XXX-XXX-XX the UAN Format value is $1-$2-$3. for UANs with prefix R01 and formatted R01-XXX-XXX the UAN Format value is R01-$1-$2.</inlineHelpText>
        <label>UAN Format</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Utility_Account_Number_Length__c</fullName>
        <inlineHelpText>Length of utility account numbers. Ex: if UANs are written XXXX-XX-XX the length is 8. Prefixes are included in length. Ex: R01-XXXX-XXXX is length 11.</inlineHelpText>
        <label>UAN Length</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Utility_Account_Number_Prefix__c</fullName>
        <inlineHelpText>Used for automatically adding the utility account number prefix on forms.</inlineHelpText>
        <label>UAN Prefix</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Utility_Account_Number_Regex_Groups__c</fullName>
        <inlineHelpText>Regex for breaking utility account numbers into capture groups for formatting. Ex: to format a utility account number as XX-XXXX-XXXX-XXXX-X use the regex (\d{0,2})(\d{0,4})(\d{0,4})(\d{0,4})(\d?). Delimiters are captured in the UAN Regex Delimiter field.</inlineHelpText>
        <label>UAN Regex Groups</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Utility_Data_Collection_Mechanism__c</fullName>
        <label>Utility Data Collection Mechanism</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>File Upload</fullName>
                    <default>true</default>
                    <label>File Upload</label>
                </value>
                <value>
                    <fullName>EDI</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Utility</label>
    <nameField>
        <label>Utility Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/RestZipCode.cls
/**
 * Created by peteryao on 2/7/20.
 * Tested By: CSLeadsRESTControllerV2Test
 */

@SuppressWarnings('PMD.ExcessivePublicCount')
public inherited sharing class RestZipCode {
    public String zipCode;
    public Boolean hasCapacity;
    public Boolean hasLMICapacity;
    public Boolean hasSmallCSCapacity;
    public Boolean collectRateClass;
    public Set<Utility> utilities;
    public Set<String> loadZones;
    public Set<Product> products;
    public Set<RateClass> rateClasses;
    public List<SolarSystem> solarSystems;
    public Set<String> utilityZipCodesServed;
    public Boolean ficoUnderwriting;
    public Boolean finDocsUnderwriting;
    public Boolean collectPayment;
    public Boolean underwrite;
    public Boolean collectPOD;

    public RestZipCode(CapacityService.ZipcodeResponse response) {
        this.zipCode = response.zipcode;
        this.hasCapacity = response.hasCapacity();
        this.hasLMICapacity = response.hasLMICapacity();
        this.hasSmallCSCapacity = response.hasSmallCSCapacity();
        this.collectRateClass = response.collectRateClass();
        this.utilities = response.utilities == null ? getUtilities(new Set<Utility__c>()) : getUtilities(response.utilities);
        this.loadZones = response.loadZoneNames;
        this.products = response.products == null ? getProducts(new Set<Product2>()) : getProducts(response.products);
        this.rateClasses = response.rateClasses == null ? getRateClasses(new Set<Rate_Class__c>()) : getRateClasses(response.rateClasses);
        this.solarSystems = response.sharedSolarSystems == null ? getSolarSystems(new List<Shared_Solar_System__c>()) : getSolarSystems(response.sharedSolarSystems);
        this.utilityZipCodesServed = response.utilityZipCodesServed;
        this.ficoUnderwriting = response.ficoUnderwriting;
        this.finDocsUnderwriting = response.finDocsUnderwriting;
        this.collectPayment = response.collectPayment;
        this.underwrite = response.underwrite;
        this.collectPOD = response.collectPOD;
    }

    private Set<Utility> getUtilities(Set<Utility__c> utilitySobjs) {
        Set<Utility> utilities = new Set<Utility>();
        for (Utility__c utility : utilitySobjs) {
            utilities.add(new Utility(
                utility.Id,
                utility.Name,
                utility.Utility_Data_Collection_Mechanism__c,
                utility.Utility_Account_Number_Regex_Groups__c,
                utility.Utility_Account_Number_Format__c,
                utility.Utility_Account_Number_Prefix__c,
                utility.Utility_Account_Number_Length__c,
                utility.POD_Id_Regex_Groups__c,
                utility.POD_Id_Format__c,
                utility.POD_Id_Prefix__c,
                utility.POD_Id_Length__c
            ));
        }
        return utilities;
    }

    private Set<Product> getProducts(Set<Product2> productSobjs) {
        Set<Product> products = new Set<Product>();
        for (Product2 prod : productSobjs) {
            products.add(new Product(prod.Id,
                prod.Name, prod.Disclosure_Form_Conga_Template__c));
        }
        return products;
    }

    private Set<RateClass> getRateClasses(Set<Rate_Class__c> rateClassSobjs) {
        Set<RateClass> rateClasses = new Set<RateClass>();
        for (Rate_Class__c rc : rateClassSobjs) {
            rateClasses.add(new RateClass(rc.Id, rc.Name, rc.Suppress_Disclosure_Form__c));
        }
        return rateClasses;
    }

    private List<SolarSystem> getSolarSystems(List<Shared_Solar_System__c> sssSobjs) {
        List<SolarSystem> solarSystems = new List<SolarSystem>();
        for (Shared_Solar_System__c sss : sssSobjs) {
            solarSystems.add(new SolarSystem(sss.Id, sss.Name, sss.Capacity_Available_to_be_Reserved__c > 0 ? true : false, sss.Perch_Acq_Available_LMI_Capacity__c > 0 ? true : false, sss.Available_SMB_Underwriting_Method_FICO__c, sss.Available_SMB_Underwriting_Method_Docs__c, !sss.Do_Not_Ask_for_Payment_Method__c, !sss.Do_Not_Underwrite__c));
        }
        return solarSystems;
    }

    public class Utility {
        public String utilityId;
        public String name;
        public String dataCollectionMethod;
        public String uanRegexGroups;
        public String uanFormat;
        public String uanPrefix;
        public Decimal uanLength;
        public String podIdRegexGroups;
        public String podIdFormat;
        public String podIdPrefix;
        public Decimal podIdLength;

        public Utility(String id, String name) {
            this.utilityId = id;
            this.name = name;
            this.dataCollectionMethod = 'File Upload';
        }

        public Utility(String id, String name, String dataCollectionMethod, String uanRegexGroups, String uanFormat, String uanPrefix, Decimal uanLength, String podIdRegexGroups, String podIdFormat, String podIdPrefix, Decimal podIdLength) {
            this.utilityId = id;
            this.name = name;
            this.dataCollectionMethod = dataCollectionMethod;
            this.uanRegexGroups = uanRegexGroups;
            this.uanFormat = uanFormat;
            this.uanPrefix = uanPrefix;
            this.uanLength = uanLength;
            this.podIdRegexGroups = podIdRegexGroups;
            this.podIdFormat = podIdFormat;
            this.podIdPrefix = podIdPrefix;
            this.podIdLength = podIdLength;
        }
    }

    public class Product {
        public String productId;
        public String name;
        public Boolean standaloneDisclosureForm;

        public Product(String id, String name, String disclosureFormTemplate) {
            this.productId = id;
            this.name = name;
            this.standaloneDisclosureForm = (disclosureFormTemplate != null);
        }
    }

    public class RateClass {
        public String rateClassId;
        public String name;
        public Boolean suppressDisclosureForm;

        public RateClass(String id, String name, Boolean suppressDisclosureForm) {
            this.rateClassId = id;
            this.name = name;
            this.suppressDisclosureForm = suppressDisclosureForm;
        }
    }

    public class SolarSystem {
        public String sssId;
        public String name;
        public Boolean smallCsCapacityAvailable;
        public Boolean lmiCapacityAvailable;
        public Boolean ficoUnderwriting;
        public Boolean finDocsUnderwriting;
        public Boolean collectPayment;
        public Boolean underwrite;

        public SolarSystem(String id, String name, Boolean smallCsCapacityAvailable, Boolean lmiCapacityAvailable,
            Boolean ficoUnderwriting, Boolean finDocsUnderwriting, Boolean collectPayment, Boolean underwrite) {
            this.sssId = id;
            this.name = name;
            this.smallCsCapacityAvailable = smallCsCapacityAvailable;
            this.lmiCapacityAvailable = lmiCapacityAvailable;
            this.ficoUnderwriting = ficoUnderwriting;
            this.finDocsUnderwriting = finDocsUnderwriting;
            this.collectPayment = collectPayment;
            this.underwrite = underwrite;
        }
    }
}