src/objects/Rate_Class__c.object
<CustomObject>
    <description>This object stores utility rate class information. It&apos;s different from NMC Tariffs.</description>
    <fields>
        <fullName>Utility__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The utility that the rate class is for.</description>
        <inlineHelpText>The utility that the rate class is for.</inlineHelpText>
        <label>Utility</label>
        <referenceTo>Utility__c</referenceTo>
        <relationshipLabel>Rate Classes</relationshipLabel>
        <relationshipName>Rate_Classes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Rate Class</label>
    <nameField>
        <label>Rate Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rate Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Utility__c.object
<CustomObject>
    <label>Utility</label>
    <nameField>
        <label>Utility Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Utility_Account_Log__c.object
<CustomObject>
    <fields>
        <fullName>Utility_Rate_Class__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is populated by sales/operations. It is the utility rate class that a specific utility account has.</description>
        <inlineHelpText>Automatically populated for EDI-enabled utilities if related UDRP records have a Rate Class/Subclass matching a Rate Class record. Otherwise, manually populated by sales/ops from the Utility Bill and changed through the &quot;Recalculate Subscriptions&quot; button.</inlineHelpText>
        <label>Rate Class</label>
        <referenceTo>Rate_Class__c</referenceTo>
        <relationshipLabel>Utility Account Logs</relationshipLabel>
        <relationshipName>Utility_Account_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Utility__c</fullName>
        <formula>Lead__r.Electricity_Provider__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>xxxUtility</label>
        <type>Text</type>
    </fields>
    <label>Utility Account Log</label>
    <nameField>
        <label>Utility Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Account Logs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Utility_Data_Request__c.object
<CustomObject
     >
    <fields>
        <fullName>Utility_Account_Log__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Utility Account Log</label>
        <referenceTo>Utility_Account_Log__c</referenceTo>
        <relationshipLabel>Utility Data Requests</relationshipLabel>
        <relationshipName>Utility_Data_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Utility__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Utility</label>
        <referenceTo>Utility__c</referenceTo>
        <relationshipLabel>Utility Data Requests</relationshipLabel>
        <relationshipName>Utility_Data_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Utility Data Request</label>
    <nameField>
        <displayFormat>UDR-{00000}</displayFormat>
        <label>Utility Data Request</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Utility Data Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Utility_Data_Request_Period__c.object
<CustomObject>
    <fields>
        <fullName>Rate_Class_Lookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Rate Class</label>
        <referenceTo>Rate_Class__c</referenceTo>
        <relationshipLabel>Utility Data Request Periods</relationshipLabel>
        <relationshipName>Utility_Data_Request_Periods</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rate_Class__c</fullName>
        <description>Utility rate code as found in the tariff. (This code can be used to retrieve rates from a utility&apos;s web site.)</description>
        <inlineHelpText>Utility rate code as found in the tariff. (This code can be used to retrieve rates from a utility&apos;s web site.)</inlineHelpText>
        <label>Rate Class Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Start_Date__c</fullName>
        <label>Service Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Utility_Data_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Utility Data Request</label>
        <referenceTo>Utility_Data_Request__c</referenceTo>
        <relationshipLabel>Utility Data Request Periods</relationshipLabel>
        <relationshipName>Utility_Data_Request_Periods</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Utility Data Request Period</label>
    <nameField>
        <displayFormat>UDRP-{0000}</displayFormat>
        <label>Utility Data Request Period</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Utility Data Request Periods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/UtilityDataRequestPeriodSelector.cls
/**
 * Created by: Kristin White on 9/28/2020
 * 
 * Tested by: UtilityDataRequestServiceTest and UtilityDataRequestPeriodSelectorTest
 */

@SuppressWarnings('PMD.ApexCRUDViolation')
public inherited sharing class UtilityDataRequestPeriodSelector {
    public List<Utility_Data_Request_Period__c> selectByUDR(Set<Id> udrIdSet) {
        
        List<Utility_Data_Request_Period__c> udrpList = [
            SELECT Id, Name, Utility_Data_Request__c, Rate_Class__c, Rate_Class_Lookup__c, Service_Start_Date__c, Rate_Class_Lookup__r.Id,
            Utility_Data_Request__r.Utility__c, Utility_Data_Request__r.Utility_Account_Log__r.Utility_Rate_Class__c
            FROM Utility_Data_Request_Period__c 
            WHERE Utility_Data_Request__c IN :udrIdSet
            ORDER BY Utility_Data_Request__c ASC, Service_Start_Date__c DESC
        ];
        
        return udrpList;
    }
    
}