src/objects/Rate_Class__c.object
<CustomObject>
    <description>This object stores utility rate class information. It&apos;s different from NMC Tariffs.</description>
    <fields>
        <fullName>EDI_Rate_Class__c</fullName>
        <description>Used by the UtilityDataRequestService to populate the &quot;Rate Class&quot; lookup on a Utility Data Request Period, where this field matches the &quot;Rate Class&quot; text field on the Utility Data Request Period.</description>
        <inlineHelpText>Used by the UtilityDataRequestService to populate the &quot;Rate Class&quot; lookup on a Utility Data Request Period, where this field matches the &quot;Rate Class&quot; text field on the Utility Data Request Period.</inlineHelpText>
        <label>EDI Rate Class</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Utility__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The utility that the rate class is for.</description>
        <inlineHelpText>The utility that the rate class is for.</inlineHelpText>
        <label>Utility</label>
        <referenceTo>Utility__c</referenceTo>
        <relationshipLabel>Rate Classes</relationshipLabel>
        <relationshipName>Rate_Classes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Rate Class</label>
    <nameField>
        <label>Rate Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rate Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Utility_Account_Log__c.object
<CustomObject>
    <fields>
        <fullName>Annual_kWh__c</fullName>
        <description>Value from most recent UDR. 
Used for customer sizing on SMART contracts.</description>
        <inlineHelpText>Value from most recent UDR.
Used for customer sizing on SMART contracts.</inlineHelpText>
        <label>Annual kWh</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Average_Demand__c</fullName>
        <description>Value from most recent UDR.</description>
        <inlineHelpText>Value from most recent UDR.</inlineHelpText>
        <label>Average Demand</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NYPA__c</fullName>
        <description>Checked during QC for National Grid NY if an account is NYPA.</description>
        <label>NYPA</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Num_UDRPs_Annual_kWh__c</fullName>
        <label>Number of UDRPs used in Annual kWh</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Num_UDRPs_Avg_Demand__c</fullName>
        <label>Number of UDRPs used in Average Demand</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>QC_Status__c</fullName>
        <description>Status of Utility Data Request for automated data collection (e.g. EDI) on this Utility Account</description>
        <inlineHelpText>Status of Utility Data Request for automated data collection (e.g. EDI) on this Utility Account</inlineHelpText>
        <label>QC Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending Utility Data</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Pending BW Review</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RNY__c</fullName>
        <description>Checked during QC for National Grid NY if an account is RNY.</description>
        <label>RNY</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Utility_Rate_Class__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is populated by sales/operations. It is the utility rate class that a specific utility account has.</description>
        <inlineHelpText>Automatically populated for EDI-enabled utilities if related UDRP records have a Rate Class/Subclass matching a Rate Class record. Otherwise, manually populated by sales/ops from the Utility Bill and changed through the &quot;Recalculate Subscriptions&quot; button.</inlineHelpText>
        <label>Rate Class</label>
        <referenceTo>Rate_Class__c</referenceTo>
        <relationshipLabel>Utility Account Logs</relationshipLabel>
        <relationshipName>Utility_Account_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Utility__c</fullName>
        <formula>Lead__r.Electricity_Provider__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>xxxUtility</label>
        <type>Text</type>
    </fields>
    <label>Utility Account Log</label>
    <nameField>
        <label>Utility Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Account Logs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Utility_Data_Request__c.object
<CustomObject
     >
    <fields>
        <fullName>Address_Line_1__c</fullName>
        <complianceGroup>PII</complianceGroup>
        <label>Address Line 1</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Annual_kWh__c</fullName>
        <description>Value calculated from UDRP Quantities in the last 12 months where the Measurement Unit = KH and the Measurement Significance Code = 51</description>
        <inlineHelpText>Value calculated from UDRP Quantities in the last 12 months where the Measurement Unit = KH and the Measurement Significance Code = 51</inlineHelpText>
        <label>Annual kWh</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Average_Demand__c</fullName>
        <description>Value calculated from UDRP Quantities in the last 12 months where the Measurement Unit = K1 and the Measurement Significance Code = 51</description>
        <inlineHelpText>Value calculated from UDRP Quantities in the last 12 months where the Measurement Unit = K1 and the Measurement Significance Code = 51</inlineHelpText>
        <label>Average Demand</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Customer_Name__c</fullName>
        <complianceGroup>PII</complianceGroup>
        <label>Customer Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Government_Credit_Code__c</fullName>
        <description>N=No, account does not have a NYPA Discount
Y=Yes, account does have a NYPA Discount</description>
        <inlineHelpText>N=No, account does not have a NYPA Discount
Y=Yes, account does have a NYPA Discount</inlineHelpText>
        <label>Government Credit Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LDC_Customer_Eligibility__c</fullName>
        <description>N=No, the account is not receiving Utility Discounts/Incentive Rates
Y=Yes, the account is receiving Utility Discounts/Incentive Rates</description>
        <inlineHelpText>N=No, the account is not receiving Utility Discounts/Incentive Rates
Y=Yes, the account is receiving Utility Discounts/Incentive Rates</inlineHelpText>
        <label>LDC Customer Eligibility</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Request_Status_new__c</fullName>
        <formula>IF(OR(ISPICKVAL(Header_Status__c,&quot;Error&quot;),ISPICKVAL(Detail_Status__c, &quot;Error&quot;)),&quot;Error&quot;,
    IF(AND(ISPICKVAL(Header_Status__c,&quot;Data Received&quot;),ISPICKVAL(Detail_Status__c, &quot;Data Received&quot;)),&quot;Data Received&quot;,
        IF(AND(ISPICKVAL(Header_Status__c,&quot;Complete&quot;),ISPICKVAL(Detail_Status__c,&quot;Complete&quot;)),&quot;Complete&quot;,
            IF(OR(ISPICKVAL(Header_Status__c,&quot;Data Received&quot;),ISPICKVAL(Header_Status__c,&quot;Complete&quot;),ISPICKVAL(Detail_Status__c,&quot;Data Received&quot;),ISPICKVAL(Detail_Status__c,&quot;Complete&quot;)),&quot;Partial Data Received&quot;,
                IF(ISPICKVAL(Header_Status__c, &quot;Sent&quot;),&quot;Sent&quot;,
                    IF(ISPICKVAL(Header_Status__c, &quot;Pending&quot;),&quot;Pending&quot;,&quot;Error&quot;)
                )
            )
        )
    )
)</formula>
        <inlineHelpText>Overall status of the request based on the header and detail status fields. Both header and detail statuses must be complete for the request status to change to complete.</inlineHelpText>
        <label>Request Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Utility_Account_Log__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Utility Account Log</label>
        <referenceTo>Utility_Account_Log__c</referenceTo>
        <relationshipLabel>Utility Data Requests</relationshipLabel>
        <relationshipName>Utility_Data_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Utility__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Utility</label>
        <referenceTo>Utility__c</referenceTo>
        <relationshipLabel>Utility Data Requests</relationshipLabel>
        <relationshipName>Utility_Data_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Utility Data Request</label>
    <nameField>
        <displayFormat>UDR-{00000}</displayFormat>
        <label>Utility Data Request</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Utility Data Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Utility_Data_Request__c/fields/Num_UDRPs_Annual_kWh__c.field-meta.xml
<CustomField>
    <fullName>Num_UDRPs_Annual_kWh__c</fullName>
    <label>Number of UDRPs used in Annual kWh</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Utility_Data_Request__c/fields/Num_UDRPs_Avg_Demand__c.field-meta.xml
<CustomField>
    <fullName>Num_UDRPs_Avg_Demand__c</fullName>
    <label>Number of UDRPs used in Average Demand</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/objects/Utility_Data_Request_Period__c.object
<CustomObject>
    <fields>
        <fullName>Measurement_Unit__c</fullName>
        <description>AJ=Adjusted Kilowatt Demand
HH=Hundred Cubic Feet (CCF)
K1=Kilowatt Demand/kW
K2=Kilovolt Amperes Reactive Demand/kVAR
K3=Kilovolt Amperes Reactive Hour/kVARh
K4=Kilovolt Amperes/kVA
KH=Kilowatt Hour/kWh
TD=Therms TZ=Thousand Cubic Feet (MCF)</description>
        <inlineHelpText>AJ=Adjusted Kilowatt Demand
HH=Hundred Cubic Feet (CCF)
K1=Kilowatt Demand/kW
K2=Kilovolt Amperes Reactive Demand/kVAR
K3=Kilovolt Amperes Reactive Hour/kVARh
K4=Kilovolt Amperes/kVA
KH=Kilowatt Hour/kWh
TD=Therms TZ=Thousand Cubic Feet (MCF)</inlineHelpText>
        <label>Measurement Unit</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rate_Class_Lookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Rate Class</label>
        <referenceTo>Rate_Class__c</referenceTo>
        <relationshipLabel>Utility Data Request Periods</relationshipLabel>
        <relationshipName>Utility_Data_Request_Periods</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rate_Class__c</fullName>
        <description>Utility rate code as found in the tariff. (This code can be used to retrieve rates from a utility&apos;s web site.)</description>
        <inlineHelpText>Utility rate code as found in the tariff. (This code can be used to retrieve rates from a utility&apos;s web site.)</inlineHelpText>
        <label>Rate Class Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rate_Subclass__c</fullName>
        <description>This segment must be sent if a rate subclass is applicable. Provides further clarification of the Utility Rate Service Class. Prior to 11/2/2015 O&amp;R would send the Capacity Obligation in this field.</description>
        <inlineHelpText>This segment must be sent if a rate subclass is applicable. Provides further clarification of the Utility Rate Service Class. Prior to 11/2/2015 O&amp;R would send the Capacity Obligation in this field.</inlineHelpText>
        <label>Rate Subclass</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Utility_Data_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Utility Data Request</label>
        <referenceTo>Utility_Data_Request__c</referenceTo>
        <relationshipLabel>Utility Data Request Periods</relationshipLabel>
        <relationshipName>Utility_Data_Request_Periods</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Utility Data Request Period</label>
    <nameField>
        <displayFormat>UDRP-{0000}</displayFormat>
        <label>Utility Data Request Period</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Utility Data Request Periods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/UtilityDataRequestService.cls
/**
 * Created by: Kristin White on 9/28/2020
 * 
 * Test: UtilityDataRequestServiceTest
 * 
 */
@SuppressWarnings('ApexDocValidation')
public without sharing class UtilityDataRequestService {
    @TestVisible private Map<Id,Utility_Data_Request__c> completedUDRMap = new Map<Id,Utility_Data_Request__c>();
    @TestVisible private Map<Id,Utility_Data_Request__c> newUDRMap;
    @TestVisible private Map<Id,Utility_Data_Request__c> oldUDRMap;
    @TestVisible private Map<String,Rate_Class__c> rateClassWithEDIMap;
    @TestVisible private Map<Id,Utility_Account_Log__c> ualsWithCompletedUDRMap;
    @TestVisible private Map<Id,Id> udrToRateClassMap = new Map<Id,Id>();
    @TestVisible private Map<Id,List<Utility_Data_Request_Period__c>> completedUDRToUdrpMap;
    @TestVisible private fflib_SObjectUnitOfWork uow;
    @TestVisible private static RateClassesSelector rateClassesSelector = new RateClassesSelector();
    @TestVisible private static UtilityDataRequestPeriodSelector udrpSelector = new UtilityDataRequestPeriodSelector();
    @TestVisible private static UtilityDataRequestSelector udrSelector = new UtilityDataRequestSelector();
    @TestVisible private static UALSelector ualSelector = new UALSelector();
    /**
     * Constructor for service class instance
     * @param oldUDRMap Trigger.oldMap
     * @param newUDRMap Trigger.newMap
     */
    public UtilityDataRequestService(Map<Id,Utility_Data_Request__c> oldUDRMap, Map<Id,Utility_Data_Request__c> newUDRMap) {
        this.oldUDRMap = oldUDRMap;
        this.newUDRMap = newUDRMap;
    }
    /**
     * @description Populates the UDR.Annual_kWh and the UAL.Annual_kWh with the value calculated in the getAnnualkWh method.
     * Only want to update where the UDR Request Status is being updated to Complete from something else.
     */
    public void beforeStatusUpdatedToComplete() {
        try {
            setupTriggerContext();
            setAnnualkWhAndAvgDemandOnUDRs();
            // Flags the related UDRPs that were used in Annual kWh and Avg Demand calcs
            uow.commitWork();
        } catch (Exception e ) {
            String message = 'Unable to commit work before completion of UDRs: ' + completedUDRMap.keySet().toString()
                + '\n\n' + e.getMessage() + '\n\n' + e.getStackTraceString();
            Logger.logLater('UtilityDataRequestService', 'beforeStatusUpdatedToComplete', message);
        }
        Logger.flushLogs();
    }
    /**
     * @description Method used when a UDR record status is updated to 'Complete' from previously being something else
     * <p></p>
     * Handles related UDRP and UAL modifications
     */
    public void afterStatusUpdatedToComplete() {
        try {
            setupTriggerContext();
            populateUDRPRateClassOnCompletedUDRs();
            updateUALForCompletedUDRs();
            uow.commitWork();
        } catch (Exception e ) {
            String message = 'Unable to commit work on completion of UDRs: ' + completedUDRMap.keySet().toString()
                + '\n\n' + e.getMessage() + '\n\n' + e.getStackTraceString();
            Logger.logLater('UtilityDataRequestService', 'afterStatusUpdatedToComplete', message);
        }
        Logger.flushLogs();
    }

    private void setupTriggerContext() {
        // Instance UOW
        uow = new fflib_SObjectUnitOfWork(
            new List<SObjectType>{
                Utility_Data_Request_Period__c.getSObjectType(),
                Utility_Account_Log__c.getSObjectType()
            }
        );
        // Map completed UDRs for further processing
        for (Utility_Data_Request__c udr : newUDRMap.values()) {
            if (udr.Request_Status_new__c == 'Complete' && oldUDRMap.get(udr.Id).Request_Status_new__c != 'Complete') {
                completedUDRMap.put(udr.Id,udr);
            }
        }
        // Retrieve Rate Classes, UDR->UDRPs, and UALs for Completed UDRs
        rateClassWithEDIMap = rateClassesSelector.selectWithEDI();
        completedUDRToUdrpMap = udrpSelector.selectByUDR(completedUDRMap.keySet());
        ualsWithCompletedUDRMap = ualSelector.selectAllMap(
            CollectionUtil.mapByIdField(completedUDRMap.values(), Utility_Data_Request__c.Utility_Account_Log__c).keySet()
        );
    }

    private void setAnnualkWhAndAvgDemandOnUDRs(){
        Map<Id, UDRWrapper> udrObjectMap = new Map<Id, UDRWrapper>();
        for (Id udrId : completedUDRToUdrpMap.keySet()){
            UDRWrapper currentUDR = new UDRWrapper(udrId);
            currentUDR.addUDRPs(completedUDRToUdrpMap.get(udrId));
            udrObjectMap.put(udrId, currentUDR);
        }
        //Need to get map of new UDRs with specific query criteria needed for the kWh calculation
        Map<Id, Utility_Data_Request__c> udrMap = udrSelector.selectMapForKWHById(completedUDRMap.values());
        for (Utility_Data_Request__c udr : completedUDRMap.values()) {
            Utility_Data_Request__c currentUDR = udrMap.get(udr.Id);
            UDRWrapper currentUdrObject = udrObjectMap.get(udr.Id);
            if (currentUdrObject == null) {
                continue;
            }
            UDRPTotalCalculator kWhHelper = new UDRPTotalCalculator(uow);
            kWhHelper.setAnnualkWh(currentUDR, currentUdrObject.getListKH());
            udr.Annual_kWh__c = kWhHelper.kWh;
            udr.Num_UDRPs_Annual_kWh__c = kWhHelper.numberOfUDRPsUsedInCalc;

            UDRPTotalCalculator avgDemandHelper = new UDRPTotalCalculator(uow);
            avgDemandHelper.setAverageDemand(currentUdrObject.getListK1());
            udr.Average_Demand__c = avgDemandHelper.avgDemand;
            udr.Num_UDRPs_Avg_Demand__c = avgDemandHelper.numberOfUDRPsUsedInCalc;
        }
    }

    private void populateUDRPRateClassOnCompletedUDRs() {
        // Only want to update the Rate Classes if the Status updated from something else to Complete
        for (Id udrId : completedUDRToUdrpMap.keySet()) {
            populateRateClassOnUDRP(udrId);
        }
    }

    private void updateUALForCompletedUDRs() {
        for (Id udrId : completedUDRMap.keySet()) {
            Utility_Account_Log__c ual = ualsWithCompletedUDRMap.get(completedUDRMap.get(udrId).Utility_Account_Log__c);
            ual.Utility_Rate_Class__c = udrToRateClassMap.get(udrId);
            populateFieldsOnUAL(ual, completedUDRMap.get(udrId));
        }
        // Register work
        uow.registerDirty(ualsWithCompletedUDRMap.values());
    }
    /**
     * @description Populates the UDRP.Rate_Class_Lookup__c where 
     * the Rate Class object's EDI_Rate_Class__c text matches the UDRP's Rate_Subclass__c text.
     */
    private void populateRateClassOnUDRP(Id udrId) {
        List<Utility_Data_Request_Period__c> udrpList = completedUDRToUdrpMap.get(udrId);
        Boolean firstKH = false;
        for (Utility_Data_Request_Period__c udrp : udrpList) {
            String rateSubclass = udrp.Rate_Subclass__c;
            String rateClass = udrp.Rate_Class__c;
            udrp.Rate_Class_Lookup__c = setRateClassLookupOnUDRP(rateSubclass, rateClass, udrp);
            uow.registerDirty(udrp);
            if (!firstKH && udrp.Measurement_Unit__c == 'KH') {
                // Only the first UDRP (most recent service date) where the Measurement_Unit is KH, is what we use for Rate Class lookup elsewhere
                udrToRateClassMap.put(udrId, udrp.Rate_Class_Lookup__c);
                firstKH = true;
            }
        }
    }
    private Id setRateClassLookupOnUDRP(String rateSubclass, String rateClass, Utility_Data_Request_Period__c udrp) {
        Rate_Class__c rateSubclassSObj = rateClassWithEDIMap.get(rateSubclass);
        Rate_Class__c rateClassSObj = rateClassWithEDIMap.get(rateClass);
        if (udrp.Utility_Data_Request__r.Utility__c == rateSubclassSObj?.Utility__c) {
            return rateSubclassSObj.Id;
        } else if (udrp.Utility_Data_Request__r.Utility__c == rateClassSObj?.Utility__c) {
            return rateClassSObj.Id;
        }
        return null;
    }

    private void populateFieldsOnUAL(Utility_Account_Log__c ual, Utility_Data_Request__c udr) {
        ual.Annual_kWh__c = udr.Annual_kWh__c;
        ual.Average_Demand__c = udr.Average_Demand__c;

        ual.Num_UDRPs_Annual_kWh__c = udr.Num_UDRPs_Annual_kWh__c;
        ual.Num_UDRPs_Avg_Demand__c = udr.Num_UDRPs_Avg_Demand__c;

        ual.NYPA__c = convertYesNo(udr.Government_Credit_Code__c);
        ual.RNY__c = convertYesNo(udr.LDC_Customer_Eligibility__c);
        Boolean addressStatus = ualNameAddressChange(ual, udr);
        if (ual.NYPA__c == 'Yes' || ual.RNY__c == 'Yes') {
            ual.QC_Status__c = 'Pending BW Review';
        } else if (addressStatus) {
            ual.QC_Status__c = 'Complete';
        } else {
            ual.QC_Status__c = 'Pending BW Review';
        }
    }
    private String convertYesNo(String singleChar) {
        if (singleChar == 'N') {
            return 'No';
        } else if (singleChar == 'Y') {
            return 'Yes';
        }
        return null;
    }
    private Boolean ualNameAddressChange(Utility_Account_Log__c ual, Utility_Data_Request__c udr) {
        // returns true if there is no difference between the UDR and UAL addresses
        // returns false if there is a difference between the UDR and UAL addresses
        String udrName = getComparisonString(udr.Customer_Name__c);
        String udrAddress1 = getComparisonString(udr.Address_Line_1__c);
        String udrAddress2 = getComparisonString(udr.Address_Line_2__c);
        String udrAddress = udrAddress1 + udrAddress2;
        String udrCity = getComparisonString(udr.City__c);
        String udrState = getComparisonString(udr.State__c);
        String udrZip = getComparisonString(udr.Zip_Code__c);
        String ualName = getComparisonString(ual.Name_on_Account__c);
        String ualAddress = getComparisonString(ual.Service_Address__c);
        String ualCity = getComparisonString(ual.Service_City__c);
        String ualState = getComparisonString(ual.Service_State__c);
        String ualZip = getComparisonString(ual.Service_Zip_Code__c);
        if (udrName + '|' + udrAddress + '|' + udrCity + '|' + udrState + '|' + udrZip !=
            ualName + '|' + ualAddress + '|' + ualCity + '|' + ualState + '|' + ualZip) {
            ual.Address_Update__c = true;
        } else {
            return true;
        }
        ual.Previous_Name_on_Utility_Account__c = cleanString(ual.Name_on_Account__c);
        ual.Previous_Service_Address__c = cleanString(ual.Service_Address__c);
        ual.Previous_Service_City__c = cleanString(ual.Service_City__c);
        ual.Previous_Service_State__c = cleanString(ual.Service_State__c);
        ual.Previous_Service_Zip_Code__c = cleanString(ual.Service_Zip_Code__c);
        ual.Name_on_Account__c = cleanString(udr.Customer_Name__c);
        ual.Service_Address__c = cleanString(udr.Address_Line_1__c) + ' ' + cleanString(udr.Address_Line_2__c);
        ual.Service_City__c = cleanString(udr.City__c);
        ual.Service_State__c = cleanString(udr.State__c);
        ual.Service_Zip_Code__c = cleanString(udr.Zip_Code__c);
        return false;
    }
    private String getComparisonString(String str) {
        if (str == 'null' || str == null) {
            return '';
        }
        str = str.replaceAll('\\s+','');
        str = str.replaceAll('[^a-zA-Z0-9]','');
        str = str.toUpperCase();
        return str;
    }
    private String cleanString(String str) {
        if (str == 'null' || str == null) {
            return '';
        }
        return str;
    }
}