src/objects/Shared_Solar_System__c.object
<CustomObject
     >
    <articleTypeChannelDisplay n1:nil="true" />
    <customSettingsType n1:nil="true" />
    <description n1:nil="true" />
    <eventType n1:nil="true" />
    <fields>
        <fullName>Billing_Method__c</fullName>
        <label>Billing Method</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>NMC</fullName>
                </value>
                <value>
                    <fullName>kWh</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Capacity_Committed_kW_DC__c</fullName>
        <inlineHelpText>Sum of Complete Small CS Subscriptions</inlineHelpText>
        <label>Committed Small CS Capacity</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Billed_Production_Periods__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>The count of production periods that have First Date Production Billed populated</inlineHelpText>
        <label>Number of Billed Production Periods</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Reserved_Capacity_kW_DC__c</fullName>
        <inlineHelpText>Sum of New, Pending, or QC in Process Small CS subscriptions</inlineHelpText>
        <label>Pending Small CS Capacity</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_System_Size_kW_AC__c</fullName>
        <inlineHelpText>Total system size in kW AC.</inlineHelpText>
        <label>Total System Size (kW AC)</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_System_Size_kWh_DC__c</fullName>
        <inlineHelpText>Total system size in kW DC.</inlineHelpText>
        <label>Total System Size (kW DC)</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <gender n1:nil="true" />
    <household>false</household>
    <label>Shared Solar System</label>
    <nameField>
        <label>Shared Solar System Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shared Solar Systems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <startsWith n1:nil="true" />
</CustomObject>

src/objects/Transfer__c.object
<CustomObject>
    <fields>
        <fullName>Attempted_Transfer__c</fullName>
        <inlineHelpText>Credits Available for Allocation from Production period used for calculating bills</inlineHelpText>
        <label>Attempted Credit Transfer</label>
        <precision>13</precision>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Attempted_kWh_Transfer__c</fullName>
        <inlineHelpText>Total Production from Production period used for calculating bills</inlineHelpText>
        <label>Attempted kWh Transfer</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Billing_Method__c</fullName>
        <formula>TEXT(Shared_Solar_System__r.Billing_Method__c)</formula>
        <inlineHelpText>Bills are generated differently depending on NMC or kWh</inlineHelpText>
        <label>Billing Method</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bills_Generated__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Bills Generated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Date_of_Transfer__c</fullName>
        <label>Date of Transfer</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Default_Credit_Value__c</fullName>
        <inlineHelpText>NMCRate for creating UASBs in markets where $ credit value is NOT set at the customer level (MA)</inlineHelpText>
        <label>Default Credit Value</label>
        <precision>18</precision>
        <scale>8</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Shared_Solar_System__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Transfer object is looking up to the SSS object.</description>
        <label>Shared Solar System</label>
        <referenceTo>Shared_Solar_System__c</referenceTo>
        <relationshipLabel>Transfers</relationshipLabel>
        <relationshipName>Transfers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Transfer_Amount__c</fullName>
        <inlineHelpText>Transfer Amount populated from Utility Account Bill</inlineHelpText>
        <label>Transfer Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Transfer_Type__c</fullName>
        <label>Transfer Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Excess Credit</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
                <value>
                    <fullName>Main</fullName>
                </value>
                <value>
                    <fullName>One-Off</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Transfer</label>
    <nameField>
        <label>Transfer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transfers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Transfer_Part__c.object
<CustomObject>
    <fields>
        <fullName>Main_Transfer_Default_Credit_Value__c</fullName>
        <inlineHelpText>Stamped from the Transfer at creation, if the production detail is linked to a Main Transfer</inlineHelpText>
        <label>Main Transfer Default Credit Value</label>
        <precision>11</precision>
        <scale>8</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Transfer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>A lookup relationship from Transfer Parts up to Transfer.</description>
        <label>Transfer</label>
        <referenceTo>Transfer__c</referenceTo>
        <relationshipName>Transfer_Parts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Production Detail</label>
    <nameField>
        <label>Transfer Parts Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Production Detail</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TransferServiceTest.cls
@IsTest
private class TransferServiceTest {
    @IsTest
    public static void testSSSBilledProductionCount(){
        useMocks();
        List<Transfer__c> newTransfers = getTransferMocks();
        Map<Id, Transfer__c> oldTransferMap = new Map<Id, Transfer__c>();
        for (Transfer__c transfer : newTransfers){
            Transfer__c oldTransfer = new Transfer__c(
                Bills_Generated__c = false
            );
            oldTransferMap.put(transfer.Id, oldTransfer);
        }

        TransferService service = new TransferService();
        service.changeInBillsGenerated(newTransfers,oldTransferMap);

        // 6 Transfers, but only for 4 SSSes. Of the 4, only 3 require an update:
        System.assertEquals(3,service.sssToUpdate.size());

        for (Shared_Solar_System__c sssToUp : service.sssToUpdate){
            if (sssToUp.Id == 'a1J3K0000005hM0UAI'){
                System.assertEquals(7,sssToUp.Number_of_Billed_Production_Periods__c);
            } else if (sssToUp.Id == 'a1J3K0000006hM0UAI'){
                System.assertEquals(0,sssToUp.Number_of_Billed_Production_Periods__c);
            } else if (sssToUp.Id == 'a1J3K0000007hM0UAI'){
                System.assertEquals(4,sssToUp.Number_of_Billed_Production_Periods__c);
            } else {
                System.assert(false);
            }
        }
    }

    @IsTest
    public static void testTriggers(){
        Shared_Solar_System__c sss1 = new Shared_Solar_System__c(
            Name = 'Project 1A',
            Billing_Method__c = 'NMC',
            Reserved_Capacity_kW_DC__c = '10',
            Capacity_Committed_kW_DC__c = 0,
            Total_System_Size_kWh_DC__c = 1445.86,
            Total_System_Size_kW_AC__c = 1000,
            Maximum_Subscription_Assemblage__c = 25);
        insert sss1;

        Transfer__c transferP1 = new Transfer__c(
            Shared_Solar_System__c = sss1.Id,
            Attempted_Transfer__c = 100,
            Attempted_kWh_Transfer__c = 100,
            Transfer_Amount__c = 100,
            Date_of_Transfer__c = Date.newInstance(2019, 6, 4),
            Name = 'TRF',
            Bills_Generated__c = false
        );
        insert transferP1;
        transferP1.Default_Credit_Value__c = 0.12;
        update transferP1;
        delete transferP1;

        List<Transfer__c> transfers = [
            SELECT Id
            FROM Transfer__c
        ];
        System.assertEquals(0,transfers.size());
    }

    @IsTest
    private static void testCreditValueChange(){
        useMocks();
        Map<Id, Transfer__c> oldTransferMap = new Map<Id, Transfer__c>();
        List<Transfer__c> newTransfers = new List<Transfer__c>();

        List<Transfer__c> oldTransfers = getTransferMocks();

        for (Transfer__c oldTransfer : oldTransfers){
            oldTransfer.Default_Credit_Value__c = 0.17;
            if (oldTransfer.Id == 'a903K000000028ZQAQ'){
                oldTransfer.Default_Credit_Value__c = null;
            }
            oldTransferMap.put(oldTransfer.Id, oldTransfer);
        }

        newTransfers = getTransferMocks();
        for (Transfer__c transfer : newTransfers){
            transfer.Default_Credit_Value__c = 0.12;
            if (transfer.Id == 'a903K000000026ZQAQ'){
                transfer.Default_Credit_Value__c = null;
            } else if (transfer.Id == 'a903K000000011ZQAQ'){
                transfer.Default_Credit_Value__c = 0.17;
            }
        }

        TransferService service = new TransferService();
        List<Transfer_Part__c> partsToUpdate = service.findPartsOnCreditValueUpdate(newTransfers, oldTransferMap);
        System.assertEquals(5,partsToUpdate.size());
        Map<Id, Transfer_Part__c> partMap = new Map<Id, Transfer_Part__c>();

        for (Transfer_Part__c part : partsToUpdate){
            partMap.put(part.Transfer__c, part);
        }

        System.assertEquals(0.12,partMap.get('a903K000000028ZQAQ').Main_Transfer_Default_Credit_Value__c,
            'main transfer credit value was updated from null to a value, but the transfer part did not update'
        );
        System.assertEquals(null,partMap.get('a903K000000026ZQAQ').Main_Transfer_Default_Credit_Value__c,
            'main transfer credit value was updated from a value to null, but the transfer part did not update'
        );
        System.assertEquals(null,partMap.get('a903K000000011ZQAQ'),
            'main transfer credit value was updated to the same value as before, transfer part should not have updated'
        );
        System.assertEquals(0.12,partMap.get('a903K000000027ZQAQ').Main_Transfer_Default_Credit_Value__c,
            'main transfer credit value was updated, but the transfer part did not update'
        );
        System.assertEquals(0.12,partMap.get('a903K000000029ZQAQ').Main_Transfer_Default_Credit_Value__c,
            'main transfer credit value was updated, but the transfer part did not update'
        );
    }

    public static List<Transfer__c> getTransferMocks(){
        Transfer__c transferOne = new Transfer__c(Id = 'a903K000000026ZQAQ', Transfer_Type__c = 'Main', Bills_Generated__c = true, Shared_Solar_System__c = 'a1J3K0000006hM0UAI');
        Transfer__c transferTwo = new Transfer__c(Id = 'a903K000000027ZQAQ', Transfer_Type__c = 'Main', Bills_Generated__c = true, Shared_Solar_System__c = 'a1J3K0000008hM0UAI');
        Transfer__c transferThree = new Transfer__c(Id = 'a903K000000028ZQAQ', Transfer_Type__c = 'Main', Bills_Generated__c = true, Shared_Solar_System__c = 'a1J3K0000008hM0UAI');
        Transfer__c transferFour = new Transfer__c(Id = 'a903K000000029ZQAQ', Transfer_Type__c = 'Main', Bills_Generated__c = true, Shared_Solar_System__c = 'a1J3K0000007hM0UAI');
        Transfer__c transferFive = new Transfer__c(Id = 'a903K000000010ZQAQ', Transfer_Type__c = 'Main', Bills_Generated__c = true, Shared_Solar_System__c = 'a1J3K0000007hM0UAI');
        Transfer__c transferSix = new Transfer__c(Id = 'a903K000000011ZQAQ', Transfer_Type__c = 'Main', Bills_Generated__c = true, Shared_Solar_System__c = 'a1J3K0000005hM0UAI');
        return new List<Transfer__c>{
            transferOne, transferTwo, transferThree, transferFour, transferFive, transferSix
        };
    }

    private static void useMocks() {
        TransferService.prodSelector = (ProductionSelector) Test.createStub(ProductionSelector.class, new MockProductionSelector());
        TransferService.prodDetailSelector = (ProductionDetailSelector) Test.createStub(ProductionDetailSelector.class, new MockProductionDetailSelector());
        TransferService.sssSelector = (SharedSolarSystemsSelector) Test.createStub(SharedSolarSystemsSelector.class, new MockSSSSelctor());
    }

    public class MockProductionSelector extends MockProvider {
        public MockProductionSelector() {
        }

        public override Object handleMethodCall(MethodCall methodCall) {
            Map<Id,Integer> sssIdToCountMap = new Map<Id,Integer>();
            sssIdToCountMap.put('a1J3K0000005hM0UAI',7);
            sssIdToCountMap.put('a1J3K0000008hM0UAI',3);
            sssIdToCountMap.put('a1J3K0000007hM0UAI',4);
            sssIdToCountMap.put('a1J3K0000006hM0UAI',0);

            switch on methodCall.stubbedMethodName {
                when 'getBilledProductionBySSS' {
                    return sssIdToCountMap;
                }
            }
            return null;
        }
    }

    public class MockSSSSelctor extends MockProvider {
        public MockSSSSelctor() {
        }

        public override Object handleMethodCall(MethodCall methodCall) {
            Map<Id, Shared_Solar_System__c> sssMap = new Map<Id, Shared_Solar_System__c>();
            Shared_Solar_System__c sssOne = new Shared_Solar_System__c(
                Id = 'a1J3K0000005hM0UAI',
                Number_of_Billed_Production_Periods__c = 3
            );
            Shared_Solar_System__c sssTwo = new Shared_Solar_System__c(
                Id = 'a1J3K0000006hM0UAI',
                Number_of_Billed_Production_Periods__c = 3
            );
            Shared_Solar_System__c sssThree = new Shared_Solar_System__c(
                Id = 'a1J3K0000007hM0UAI',
                Number_of_Billed_Production_Periods__c = 3
            );
            Shared_Solar_System__c sssFour = new Shared_Solar_System__c(
                Id = 'a1J3K0000008hM0UAI',
                Number_of_Billed_Production_Periods__c = 3
            );
            sssMap.put(sssOne.Id, sssOne);
            sssMap.put(sssTwo.Id, sssTwo);
            sssMap.put(sssThree.Id, sssThree);
            sssMap.put(sssFour.Id, sssFour);
            switch on methodCall.stubbedMethodName {
                when 'getSSSMap' {
                    return sssMap;
                }
            }
            return null;
        }
    }

    public class MockProductionDetailSelector extends MockProvider {
        public MockProductionDetailSelector() {
        }

        public override Object handleMethodCall(MethodCall methodCall) {
            String partsAsString = '' +
                '[{"Transfer__c":"a903K000000026ZQAQ","Transfer__r":{"Id":"a903K000000026ZQAQ","Default_Credit_Value__c":null}},' +
                '{"Transfer__c":"a903K000000027ZQAQ","Transfer__r":{"Id":"a903K000000027ZQAQ","Default_Credit_Value__c":0.12}},' +
                '{"Transfer__c":"a903K000000028ZQAQ","Transfer__r":{"Id":"a903K000000028ZQAQ","Default_Credit_Value__c":0.12}},' +
                '{"Transfer__c":"a903K000000029ZQAQ","Transfer__r":{"Id":"a903K000000029ZQAQ","Default_Credit_Value__c":0.12}},' +
                '{"Transfer__c":"a903K000000010ZQAQ","Transfer__r":{"Id":"a903K000000010ZQAQ","Default_Credit_Value__c":0.12}}]';

            switch on methodCall.stubbedMethodName {
                when 'getPartsFromTransfer' {
                    return (List<Transfer_Part__c>)JSON.deserialize(partsAsString,List<Transfer_Part__c>.class);
                }
            }
            return null;
        }
    }
}