src/objects/Shared_Solar_System__c.object
<CustomObject
     >
    <articleTypeChannelDisplay n1:nil="true" />
    <customSettingsType n1:nil="true" />
    <description n1:nil="true" />
    <eventType n1:nil="true" />
    <gender n1:nil="true" />
    <household>false</household>
    <label>Shared Solar System</label>
    <nameField>
        <label>Shared Solar System Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shared Solar Systems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <startsWith n1:nil="true" />
</CustomObject>

src/objects/Utility_Account_Log__c.object
<CustomObject>
    <fields>
        <fullName>Average_Demand__c</fullName>
        <description>Value from most recent UDR.</description>
        <inlineHelpText>Value from most recent UDR.</inlineHelpText>
        <label>Average Demand</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Utility Account Log</label>
    <nameField>
        <label>Utility Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Account Logs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Utility_Account_Log__c/fields/Exclude_from_Demand_Capacity__c.field-meta.xml
<CustomField>
    <fullName>Exclude_from_Demand_Capacity__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>When checked, this customer UAL is not included in demand capacity for a SSS due to an exemption for residential load for mass meter exceptions.</inlineHelpText>
    <label>Exclude from Demand Capacity</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/UALCapacityRollupInitializer.cls
/**
 * @description Created by jeffparlin on 9/9/21.
 * Aggregates Shared_Solar_System__c records to queue for capacity rollup recalculation based on changes on Utility_Account_Log__c records
 * Intended for use with SystemCapacityRollupCalculator. Included in UtilityAccountLogTriggerHandler.
 * Tested By: SystemCapacityRollupCalculatorTest
 */
public without sharing class UALCapacityRollupInitializer implements SystemCapacityRollupCalculator.Initializer {

    private Map<Id, Utility_Account_Log__c> oldMap;
    private List<Utility_Account_Log__c> newList;

    public UALCapacityRollupInitializer(Map<Id, Utility_Account_Log__c> ualOldMap, List<Utility_Account_Log__c> ualNew) {
        this.oldMap = ualOldMap;
        this.newList = ualNew;
    }

    /**
     * @description Get Shared_Solar_System__c records to queue for capacity rollup recalculation based on scenarios:
     *      1. Any changes to Average_Demand__c (after update context)
     *      2. Any changes to Exclude_from_Demand_Capacity__c (after update context)
     * These situations indicate a value change for Pending or Committed capacity SSS rollup field(s))s
     * @return Set of Shared_Solar_System__c Ids
     */
    public Set<Id> getSystemsToCheckCapacityRollups() {
        Set<Utility_Account_Log__c> targetUals = new Set<Utility_Account_Log__c>();
        for (Utility_Account_Log__c newUal : newList) {
            Utility_Account_Log__c oldUal = oldMap.get(newUal.Id);
            if (oldUal.Exclude_from_Demand_Capacity__c != newUal.Exclude_from_Demand_Capacity__c ||
                oldUal.Average_Demand__c != newUal.Average_Demand__c) {
                targetUals.add(newUal);
            }
        }
        return new SharedSolarSystemsSelector().getSSSByUAL(targetUals);
    }
}