src/objects/State__c.object
<CustomObject>
    <description>State object used to store information about Utility Account annual usage estimates</description>
    <fields>
        <fullName>Avg_Annual_Resi_kWh__c</fullName>
        <description>Stores Utility Account annual usage estimates</description>
        <inlineHelpText>Stores Utility Account annual usage estimates</inlineHelpText>
        <label>Avg Annual Resi kWh</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>State</label>
    <nameField>
        <label>State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>States</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Utility_Account_Log__c.object
<CustomObject>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Utility Account Logs</relationshipLabel>
        <relationshipName>Utility_Account_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_State__c</fullName>
        <label>Service State</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <label>Utility Account Log</label>
    <nameField>
        <label>Utility Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Account Logs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Utility_Data_Request__c.object
<CustomObject
     >
    <fields>
        <fullName>State__c</fullName>
        <complianceGroup>PII</complianceGroup>
        <label>State</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Utility_Account_Log__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Utility Account Log</label>
        <referenceTo>Utility_Account_Log__c</referenceTo>
        <relationshipLabel>Utility Data Requests</relationshipLabel>
        <relationshipName>Utility_Data_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Utility Data Request</label>
    <nameField>
        <displayFormat>UDR-{00000}</displayFormat>
        <label>Utility Data Request</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Utility Data Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Utility_Data_Request_Period__c.object
<CustomObject>
    <fields>
        <fullName>Num_Days__c</fullName>
        <description>The number of days covered from Start Date to End Date.</description>
        <formula>(Service_End_Date__c - Service_Start_Date__c) + 1</formula>
        <inlineHelpText>The number of days covered from Start Date to End Date.</inlineHelpText>
        <label>Number of Days</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Used_in_Annual_kWh_Calculation__c</fullName>
        <defaultValue>false</defaultValue>
        <description>True if this UDRP is used in the UDR Annual kWh calculation.</description>
        <inlineHelpText>True if this UDRP is used in the UDR Annual kWh calculation.</inlineHelpText>
        <label>Used in Annual kWh Calculation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Used_in_Average_Demand_Calculation__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checked if the UDRP record was used to calculate the Average Demand of the related UDR/UAL</description>
        <inlineHelpText>Checked if the UDRP record was used to calculate the Average Demand of the related UDR/UAL</inlineHelpText>
        <label>Used in Average Demand Calculation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Utility_Data_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Utility Data Request</label>
        <referenceTo>Utility_Data_Request__c</referenceTo>
        <relationshipLabel>Utility Data Request Periods</relationshipLabel>
        <relationshipName>Utility_Data_Request_Periods</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Utility Data Request Period</label>
    <nameField>
        <displayFormat>UDRP-{0000}</displayFormat>
        <label>Utility Data Request Period</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Utility Data Request Periods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/UDRPTotalCalculator.cls
/**
 * @description Used by UtilityDataRequestService to calculate Annual kWh and Average Demand on a UDR
 * Tested By UtilityDataRequestServiceTest
 */
public with sharing class UDRPTotalCalculator {
    @TestVisible private static StateSelector stateSelector = new StateSelector();
    public Integer numberOfUDRPsUsedInCalc = 0;
    private Decimal days = 0;
    private Decimal quantity = 0;
    public Decimal kWh = 0;
    public Decimal avgDemand = 0;
    private fflib_SObjectUnitOfWork uow;

    public UDRPTotalCalculator(fflib_SObjectUnitOfWork uow) {
        this.uow = uow;
    }

    public void setAnnualkWh(Utility_Data_Request__c udr, List <Utility_Data_Request_Period__c> udrpList) {
        String customerType = udr.Utility_Account_Log__r.Lead__r.Customer_type__c;

        if (udrpList.size() == 0) {
            return;
        }

        for (Utility_Data_Request_Period__c udrp : udrpList){
            if (updateUDRPTotals(udrp, Schema.Utility_Data_Request_Period__c.Used_in_Annual_kWh_Calculation__c)) {
                break;
            }
        }
        updatekWh(customerType, udr);
    }

    public void setAverageDemand(List <Utility_Data_Request_Period__c> udrpList) {
        if (udrpList.size() == 0) {
            return;
        }

        for (Utility_Data_Request_Period__c udrp : udrpList) {
            if (updateUDRPTotals(udrp, Schema.Utility_Data_Request_Period__c.Used_in_Average_Demand_Calculation__c)) {
                break;
            }
        }
        avgDemand = (quantity/days)*30;
        avgDemand = avgDemand.setScale(2);
    }

    private void updatekWh(String customerType, Utility_Data_Request__c udr) {
        if (days>=120 || (customerType == 'Residential' && customerType!= null)) {
            kWh=(quantity/days)*365;
        } else if ((days > 0) && (customerType != 'Residential' && customerType != null)) {
            String sizingMethod = udr.Utility_Account_Log__r.Lead__r.Product__r.X4_month_sizing_method__c;
            if (sizingMethod == 'State Average Annual Usage') {
                State__c state = stateSelector.selectByName(udr.Utility_Account_Log__r.Service_State__c);
                kWh = state.Avg_Annual_Resi_kWh__c;
            }
            //additional sizingMethods will be added later
        }
        kWh = kWh.setScale(2);
    }

    private Boolean updateUDRPTotals(Utility_Data_Request_Period__c udrp, SObjectField fieldToUpdate) {
        Decimal potentialNumDaysWithUDRP = days + udrp.Num_Days__c;

        if (potentialNumDaysWithUDRP == 365) {
            includeUDRP(udrp, fieldToUpdate);
            return true;
        } else if (potentialNumDaysWithUDRP < 365) {
            includeUDRP(udrp, fieldToUpdate);
            return false;
        } else if (365 - days > potentialNumDaysWithUDRP - 365) {
            includeUDRP(udrp, fieldToUpdate);
            return true;
        } else if (365 - days < potentialNumDaysWithUDRP - 365) {
            return true;
        }
        return true;
    }

    private void includeUDRP(Utility_Data_Request_Period__c udrp, SObjectField fieldToUpdate) {
        udrp.put(fieldToUpdate, true);
        uow.registerDirty(udrp);
        numberOfUDRPsUsedInCalc++;
        days = days + udrp.Num_Days__c;
        quantity = quantity + udrp.Quantity__c;
    }
}