src/objects/System_Bill__c.object
<CustomObject>
    <fields>
        <fullName>Delete_this_del__c</fullName>
        <formula>Carry_Over_Balance__c * 10000000</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Delete this</label>
        <precision>18</precision>
        <scale>16</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Past_Bill_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Past Bill Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>YTD_Billed__c</fullName>
        <label>YTD Billed</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>YTD_Payments__c</fullName>
        <label>YTD Payments</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>System Bill</label>
    <nameField>
        <label>System Bill Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>System Bills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SystemBillQualityChecker.cls
/**
 * Created by pyao on 12/17/2018.
 * Description: Checks System Bills after insert and update for validity (only two decimals
 * on currency fields, other checks to be added in the future)
 * Tested By: SystemBillQualityCheckerTest
 */

public with sharing class SystemBillQualityChecker {
    @Future
    public static void checkDecimalScale(Set<Id> systemBillIds) {
        List<SObject> systemBills = getSystemBillsWithCurrencyFields(new List<Id>(systemBillIds));
        List<Id> systemBillsWithTooManyDecimals = new List<Id>();
        for (SObject sObj : systemBills) {
            if (hasFractionalCentField(sObj)) {
                systemBillsWithTooManyDecimals.add(sObj.Id);
            }
        }

        if (!systemBillsWithTooManyDecimals.isEmpty()) {
            Logger.logNow('SystemBillQualityChecker', 'checkDecimalScale',
                systemBillsWithTooManyDecimals.size() + ' System Bills have fractional decimals which we might not handle: (' +
                    String.join(systemBillsWithTooManyDecimals, ', ') + ')');
        }
    }

    private static Boolean hasFractionalCentField(SObject sObj) {
        Map<String, Object> fieldMap = sObj.getPopulatedFieldsAsMap();
        for (String field : fieldMap.keySet()) {
            if (field == 'Id') {
                continue;
            } else {
                if (((Decimal) fieldMap.get(field)).scale() > 2) {
                    return true;
                }
            }
        }
        return false;
    }

    @TestVisible
    private static List<SObject> getSystemBillsWithCurrencyFields(List<Id> systemBillIds) {
        Schema.SObjectType systemBillType = Schema.getGlobalDescribe().get('System_Bill__c');
        DescribeSObjectResult soDescribe = systemBillType.getDescribe();
        List<String> currencyFields = new List<String>();
        for (SObjectField field : soDescribe.fields.getMap().values()) {
            DescribeFieldResult fieldResult = field.getDescribe();
            // Four fields aren't used in downstream calculations
            if (fieldResult.getType() == Schema.DisplayType.CURRENCY &&
                fieldResult.getName() != 'Delete_this_del__c' &&
                fieldResult.getName() != 'YTD_Payments__c' &&
                fieldResult.getName() != 'YTD_Billed__c' &&
                fieldResult.getName() != 'Past_Bill_Amount__c') {
                currencyFields.add((String) fieldResult.getName());
            }
        }

        String soql = 'SELECT ' + String.join(currencyFields, ', ') +
            ' FROM System_Bill__c ' +
            ' WHERE ID in :systemBillIds';
        return Database.query( soql);
    }
}