src/objects/Utility__c.object
<CustomObject>
    <label>Utility</label>
    <nameField>
        <label>Utility Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Utility_Account_Log__c.object
<CustomObject>
    <fields>
        <fullName>Annual_kWh__c</fullName>
        <description>Value from most recent UDR. 
Used for customer sizing on SMART contracts.</description>
        <inlineHelpText>Value from most recent UDR.
Used for customer sizing on SMART contracts.</inlineHelpText>
        <label>Annual kWh</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Name_on_Account__c</fullName>
        <label>Name on Utility Account</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Proposed_kWh__c</fullName>
        <description>Is equal to Annual kWh * ual.Tariff.Sizing_Ratio</description>
        <inlineHelpText>Used to size customer&apos;s subscriptions by kWh, is based on Annual kWh * Sizing Ratio. Should be value used when re-sizing customers</inlineHelpText>
        <label>Proposed kWh</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Utility_NMC_Tariff__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Utility NMC Tariff</label>
        <referenceTo>Utility_NMC_Tariff__c</referenceTo>
        <relationshipLabel>Utility Account Logs</relationshipLabel>
        <relationshipName>Utility_Account_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Utility__c</fullName>
        <formula>Lead__r.Electricity_Provider__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>xxxUtility</label>
        <type>Text</type>
    </fields>
    <label>Utility Account Log</label>
    <nameField>
        <label>Utility Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Account Logs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Utility_NMC_Tariff__c.object
<CustomObject>
    <fields>
        <fullName>Customer_Type__c</fullName>
        <label>Customer Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Residential</fullName>
                </value>
                <value>
                    <fullName>Non-Residential</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Maximum_kWh__c</fullName>
        <label>Maximum kWh</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Size_Ratio__c</fullName>
        <label>Size Ratio</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Utility__c</fullName>
        <label>Utility</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value_of_Net_Metering_Credit__c</fullName>
        <label>Value of Net Metering Credit</label>
        <precision>11</precision>
        <scale>6</scale>
        <type>Currency</type>
    </fields>
    <label>Sizing Method</label>
    <nameField>
        <label>Utility and Class</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sizing Methods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/UtilityAccountLogTriggerHandlerTest.cls
/**
 * Created by mstackhouse on 12/17/2018.
 * Description: 
 * Test: 
 */

@IsTest
public with sharing class UtilityAccountLogTriggerHandlerTest {
    @IsTest
    public static void testUpdateProposedkWhWithTariff() {
        Utility_NMC_Tariff__c eversourceG1 =  new Utility_NMC_Tariff__c(
            Value_of_Net_Metering_Credit__c = .70578,
            Name = 'Eversource G1',
            Utility__c = 'Eversource',
            Size_Ratio__c = 1.1,
            Customer_Type__c = 'Non-Residential',
            Maximum_kWh__c = 10000,
            Date__c = Date.today()
        );
        insert eversourceG1;

        Utility_Account_Log__c ual = new Utility_Account_Log__c(
            Annual_kWh__c = 1000,
            Proposed_kWh__c = 1000,
            Name_on_Account__c = 'Primary 1',
            Utility_NMC_Tariff__c = eversourceG1.Id
        );
        insert ual;

        System.assertEquals(1000, ual.Proposed_kWh__c);

        ual.Annual_kWh__c = 2000;
        update ual;

        Utility_Account_Log__c ualAfterUpdate = [
            SELECT Id, Annual_kWh__c, Proposed_kWh__c, Utility_NMC_Tariff__c
            FROM Utility_Account_Log__c
            WHERE Id = :ual.Id
            LIMIT 1
        ];

        System.assertEquals(ualAfterUpdate.Annual_kWh__c * eversourceG1.Size_Ratio__c, ualAfterUpdate.Proposed_kWh__c);
        System.assertEquals(eversourceG1.Id, ualAfterUpdate.Utility_NMC_Tariff__c);
        System.assertNotEquals(ual.Proposed_kWh__c, ualAfterUpdate.Proposed_kWh__c);
    }

    @IsTest
    public static void testUpdateProposedkWhWithoutTariff() {
        Utility_Account_Log__c ual = new Utility_Account_Log__c(
            Annual_kWh__c = 1000,
            Proposed_kWh__c = 1000,
            Name_on_Account__c = 'Primary 1'
        );
        insert ual;

        System.assertEquals(1000, ual.Proposed_kWh__c);

        ual.Annual_kWh__c = 2000;
        update ual;

        Utility_Account_Log__c ualAfterUpdate = [
            SELECT Id, Annual_kWh__c, Proposed_kWh__c, Utility_NMC_Tariff__c
            FROM Utility_Account_Log__c
            WHERE Id = :ual.Id
            LIMIT 1
        ];

        System.assertEquals(2000, ualAfterUpdate.Proposed_kWh__c);
        System.assertEquals(null, ualAfterUpdate.Utility_NMC_Tariff__c);
        System.assertNotEquals(ual.Proposed_kWh__c, ualAfterUpdate.Proposed_kWh__c);
    }

    @IsTest
    public static void testDontUpdateProposedkWh() {
        Utility_Account_Log__c ual = new Utility_Account_Log__c(
            Annual_kWh__c = 1000,
            Proposed_kWh__c = 1234,
            Name_on_Account__c = 'Primary 1'
        );
        insert ual;

        System.assertEquals(1234, ual.Proposed_kWh__c);

        ual.Name_on_Account__c = 'Primary Two';
        update ual;

        Utility_Account_Log__c ualAfterUpdate = [
            SELECT Id, Annual_kWh__c, Proposed_kWh__c, Utility_NMC_Tariff__c
            FROM Utility_Account_Log__c
            WHERE Id = :ual.Id
            LIMIT 1
        ];

        System.assertEquals(1234, ualAfterUpdate.Proposed_kWh__c);
        System.assertEquals(null, ualAfterUpdate.Utility_NMC_Tariff__c);
        System.assertEquals(ual.Annual_kWh__c, ualAfterUpdate.Annual_kWh__c);
        System.assertEquals(ual.Proposed_kWh__c, ualAfterUpdate.Proposed_kWh__c);
    }
}