src/objects/Utility_Account_Log__c.object
<CustomObject>
    <fields>
        <fullName>Account_ID__c</fullName>
        <formula>Account__r.Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Utility Account Logs</relationshipLabel>
        <relationshipName>Utility_Account_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Annual_Cost_of_Electricity__c</fullName>
        <description>This is used for the SREC CS Product sizing. It is the total dollar amount a customer spends annually on their electric utility bill for this account. It is initially filled in with an estimate from the customer/partner during the CS application process, then filled in by Ops with the QCed amount.</description>
        <inlineHelpText>Used for SREC CS Product sizing. It&apos;s the total dollar amount spent annually on the electric utility bill. It is initially filled in with an estimate from the customer/partner during the CS application process, then filled in by Ops with the QCed amount.</inlineHelpText>
        <label>Annual Cost of Electricity</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Name_on_Account__c</fullName>
        <label>Name on Utility Account</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Address__c</fullName>
        <label>Service Address</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_City__c</fullName>
        <label>Service City</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_State__c</fullName>
        <label>Service State</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Zip_Code__c</fullName>
        <label>Service Zip Code</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>Utility Account Log</label>
    <nameField>
        <label>Utility Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Account Logs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/CreateUALController.cls
public class CreateUALController {
    @AuraEnabled
    public static List<Utility_Account_Log__c> getUALs(String propAccount) {
        List<Utility_Account_Log__c> ualList = [SELECT Id, Name, Account__c, Annual_Cost_of_Electricity__c, Service_Address__c, Service_City__c, 
                                                Service_State__c, Service_Zip_Code__c, Name_on_Account__c, Account_ID__c 
                                                FROM Utility_Account_Log__c 
                                                WHERE Account_ID__c = : propAccount];
        return ualList;
    }
}