src/objects/Utility__c.object
<CustomObject>
    <fields>
        <fullName>Auto_Qualify_Convert_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>See CSLeadsConverter.cls</description>
        <inlineHelpText>Indicates if Leads should undergo automatic Qualification &amp; Conversion when all Utility Account Logs for that Lead have been marked QC Status as &apos;Complete&apos;</inlineHelpText>
        <label>Auto Qualify &amp; Convert Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Average_Demand_Threshold__c</fullName>
        <defaultValue>25.00</defaultValue>
        <description>Average Demand (kW DC) at which a subscription is considered a &quot;Demand Subscription&quot; (used to identify Demand capacity limits on Projects)</description>
        <inlineHelpText>Average Demand (kW DC) at which a subscription is considered a &quot;Demand Subscription&quot; (used to identify Demand capacity limits on Projects)</inlineHelpText>
        <label>Average Demand Threshold</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Utility</label>
    <nameField>
        <label>Utility Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/UtilitySelector.cls
/**
 * @description Created by jeffparlin on 10/1/21.
 * Tested By: CSLeadsConverterTest
 */
@SuppressWarnings('PMD.ApexCRUDViolation')
public without sharing class UtilitySelector {

    public Map<Id, Utility__c> getAllUtilitiesMap() {
        return new Map<Id, Utility__c>(
        [
            SELECT Id, Average_Demand_Threshold__c, Auto_Qualify_Convert_Active__c
            FROM Utility__c
        ]);
    }

}