src/objects/Zuora__CustomerAccount__c.object
<CustomObject>
    <description>Zuora Billing Account object.  An account is a customer account that collects all of the critical information about the customer, such as contact information, payment terms, and payment methods. You can use a customer account to track subscriptions, amendments, and transactions, such as invoices and payments.</description>
    <fields>
        <fullName>Zuora__PaymentGateway__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Payment Gateway</label>
        <referenceTo>Zuora__PaymentGateway__c</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>Billing_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Zuora__Payment__c.object
<CustomObject>
    <description>Zuora Payment object.  A payment is the money that customers send to pay for charges related to their subscriptions.
The Payment object holds all of the information about an individual payment, including the payment amount and to which invoices the payment is applied.</description>
    <fields>
        <fullName>Payment_Gateway__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The default payment gateway on the Billing Account when the Payment is downloaded (which is the payment gateway that is used to make the payment).</inlineHelpText>
        <label>Payment Gateway</label>
        <referenceTo>Zuora__PaymentGateway__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora__BillingAccount__c</fullName>
        <description>The billing account that the payment is for.</description>
        <inlineHelpText>The billing account that the payment is for.</inlineHelpText>
        <label>Billing Account</label>
        <referenceTo>Zuora__CustomerAccount__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Zuora__Type__c</fullName>
        <description>Indicates if the payment is external or electronic.</description>
        <inlineHelpText>Indicates if the payment is external or electronic.</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Electronic</fullName>
                </value>
                <value>
                    <fullName>External</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Payment</label>
    <nameField>
        <label>Payment Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Zuora__PaymentGateway__c.object
<CustomObject>
    <fields>
        <fullName>Zuora__IsDefault__c</fullName>
        <label>IsDefault</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Payment Gateway</label>
    <nameField>
        <label>PaymentGateway Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Gateways</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ZuoraGatewayAssigner.cls
/**
 * Tested By: ZuoraGatewayAssignerTest
 */

public with sharing class ZuoraGatewayAssigner {
    private ZuoraAccountSelector zuoraAccountSelector = new ZuoraAccountSelector();
    private static Id defaultGatewayId;
    static {
        List<Zuora__PaymentGateway__c> allGateways = new GatewaySelector().getAllZuoraGateways();
        for (Zuora__PaymentGateway__c gateway : allGateways) {
            if (gateway.Zuora__IsDefault__c == 'true') {
                defaultGatewayId = gateway.Id;
            }
        }
    }

    public void setGatewayOnPayment(List<Zuora__Payment__c> newPayments) {
        MultiMap paymentsByBillingAccount = CollectionUtil.multiMapByField(newPayments, Zuora__Payment__c.Zuora__BillingAccount__c);
        Set<Id> billingAccountIds = CollectionUtil.toIds(paymentsByBillingAccount.keySet());
        Map<Id, Zuora__CustomerAccount__c> billingAccountsById =
            new Map<Id, Zuora__CustomerAccount__c>(zuoraAccountSelector.getBillingAccountsById(billingAccountIds));
        for (Zuora__Payment__c payment : newPayments) {
            if (payment.Zuora__Type__c == 'Electronic') {
                payment.Payment_Gateway__c = billingAccountsById.get(payment.Zuora__BillingAccount__c).Zuora__PaymentGateway__c;
                if (payment.Payment_Gateway__c == null) {
                    payment.Payment_Gateway__c = defaultGatewayId;
                }
            }
        }
    }
}