src/objects/Zuora__CustomerAccount__c.object
<CustomObject>
    <description>Zuora Billing Account object.  An account is a customer account that collects all of the critical information about the customer, such as contact information, payment terms, and payment methods. You can use a customer account to track subscriptions, amendments, and transactions, such as invoices and payments.</description>
    <fields>
        <fullName>Zuora__Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>R00N40000001kyLcEAI</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Zuora__AutoPay__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Auto Pay</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Zuora__Balance__c</fullName>
        <label>Bill To Account Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Zuora__Batch__c</fullName>
        <label>Batch</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__Zuora_Id__c</fullName>
        <description>The Zuora Id (external primary key) of this Billing Account.</description>
        <inlineHelpText>The Zuora Id (external primary key) of this Billing Account.</inlineHelpText>
        <label>Zuora Id</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ZuoraAccountSelectorTest.cls
@IsTest
public with sharing class ZuoraAccountSelectorTest {

    private static Zuora__CustomerAccount__c insertDataGetAccountId() {
        Account newSFAccount = new Account(
            Name = 'Account Name'
        );
        insert newSFAccount;

        Zuora__CustomerAccount__c newAccount = new Zuora__CustomerAccount__c(
            Name = 'Account Name',
            Zuora__Account__c = newSFAccount.Id,
            Zuora__Zuora_Id__c = '2c92c0f86b78f56c016b7b00480c2e24'
        );
        insert newAccount;
        return newAccount;
    }

    @IsTest
    static void testAccountQuery() {
        Id newAccountId = insertDataGetAccountId().Id;
        ZuoraAccountSelector.AccountWithPaymentMethod acctWithPayMethod;
        acctWithPayMethod = new ZuoraAccountSelector().getAccountWithDefaultPaymentMethod(newAccountId);

        System.assertEquals(230.00, acctWithPayMethod.account.Balance);
        System.assertEquals(false, acctWithPayMethod.account.AutoPay);
        System.assertEquals('***********0002', acctWithPayMethod.paymentMethod.CreditCardMaskNumber);
        System.assertEquals('CreditCard', acctWithPayMethod.paymentMethod.Type);
    }

    @IsTest
    static void testAccountWithPaymentMethodQuery() {
        String zuoraId = '2c92c0f86b78f56c016b7b00480c2e24';
        ZuoraAccountSelector selector = new ZuoraAccountSelector();
        ZuoraAPI.ZuoraAccount account = selector.getAccountFromZuora(zuoraId);

        System.assertEquals(false, account.AutoPay);
        System.assertEquals(230.00, account.Balance);
    }

    @IsTest
    static void testGetGateway() {
        ZuoraAccountSelector selector = new ZuoraAccountSelector();
        ZuoraAPI.PaymentGateway shouldBeDefault = selector.getGatewayIdFromGatewayName(null);
        ZuoraAPI.PaymentGateway shouldNotBeDefault = selector.getGatewayIdFromGatewayName('Not Default Gateway');

        System.assertEquals('Default Gateway Name', shouldBeDefault.name);
        System.assertEquals('Not Default Gateway', shouldNotBeDefault.name);
        System.assertNotEquals(shouldBeDefault.id, shouldNotBeDefault.id);
    }

    @IsTest
    private static void testGetAutopayAccountsWithBalance() {
        ZuoraAccountSelector selector = new ZuoraAccountSelector();
        List<ZuoraAPI.ZuoraAccount> accounts = selector.getAutopayAccountsWithBalance();
        System.assert(accounts.size() > 0);
    }

    @IsTest
    private static void getAutopayAccountsWithBalanceForEmail() {
        Zuora__CustomerAccount__c account = insertDataGetAccountId();
        account.Zuora__AutoPay__c = true;
        account.Zuora__Balance__c = 45.58;
        account.Zuora__Batch__c = 'Batch2';
        update account;
        ZuoraAccountSelector selector = new ZuoraAccountSelector();
        System.assert(selector.getAutopayAccountsWithBalanceForEmail().size() > 0, 'No rows found for query');
    }
}